"""Author Lecture 38 from verified primary sources and unchanged published panels."""
from pathlib import Path
import json,re
p=Path(__file__).resolve().parent
raw=json.loads((p/'references.json').read_text());photos=json.loads((p/'photos.json').read_text())
short={'S80':'Seyfarth et al. (1980a)','A80':'Seyfarth et al. (1980b)','P15':'Price et al. (2015)','P14':'Price & Fischer (2014)','O15':'Ortiz-Rios et al. (2015)','D23':'Deshpande et al. (2023)','M23':'Mohr et al. (2023)'}
refs={k:', '.join(x['authors'])+f" ({x['year']}). {x['title']}. {x['journal']} {x['volume']}"+(f"({x['issue']})" if x['issue'] else '')+f":{x['pages']}. https://doi.org/{x['doi']}" for k,x in raw.items()}
figdesc={
'A80_1':('A80','1','Leopard, eagle and snake alarm spectrograms from three callers.'),
'A80_2':('A80','2','Alarm spectrograms displayed to 16 kHz.'),
'A80_3':('A80','3','Adult male leopard alarms and adult female eagle alarms.'),
'A80_4':('A80','4','Single-unit and multi-unit leopard alarms.'),
'S80_1':('S80','1','Age-related breadth of stimuli eliciting eagle alarms.'),
'S80_T1':('S80','Table 1','Playback responses on the ground and in trees.'),
'P15_1A':('P15','1A','Acoustic clusters of female calls across predator and aggressive contexts.'),
'P15_1B':('P15','1B','Female calls separated by predator context.'),
'P15_1C':('P15','1C','Female predator and aggression calls occupy overlapping acoustic space.'),
'P15_2A':('P15','2A','Acoustic clusters of male predator calls.'),
'P15_2B':('P15','2B','Male alarm calls grouped by predator context.'),
'P15_2C':('P15','2C','South African male barks to real leopards, models and aggression.'),
'O15_1AB':('O15','1A–B','Auditory task and sparse MRI acquisition timing.'),
'O15_1C':('O15','1C','Environmental sounds, monkey calls and scrambled-call spectrograms.'),
'O15_1D':('O15','1D','Published modulation spectra of the three sound categories.'),
'O15_2A':('O15','2A','Auditory activation on anatomical cortical surfaces.'),
'O15_2B':('O15','2B','Anatomical MRI sections through activated auditory regions.'),
'O15_2C':('O15','2C','Left and right auditory BOLD responses.'),
'O15_3A':('O15','3A','Call-versus-environment activation on anatomical cortical surfaces.'),
'O15_3B':('O15','3B','Call-versus-scrambled-call activation on anatomical cortical surfaces.'),
'O15_4A':('O15','4A','Anatomical localization of overlapping call-selective contrasts.'),
'O15_4B':('O15','4B','Call-selective anatomical regions shared across animals.'),
'P14_1':('P14','1A–B','Responses to snake and leopard models, including tree height.'),
'P14_2':('P14','2','Paired snake and leopard chirp spectrograms.'),
'P14_3':('P14','3','Overlapping distributions of snake and leopard chirps.'),
'P14_4':('P14','4A–C','Playback response, tree climbing and persistence after priming.'),
'D23_1':('D23','1A–B','Male bark exemplars from predator and intergroup encounters.'),
'D23_2':('D23','2','Published spatial arrangement of the intergroup playback experiment.'),
'D23_3':('D23','3','Speaker-directed looking duration with and without an intergroup encounter.'),
'D23_4':('D23','4','Vigilance duration with and without an intergroup encounter.'),
'M23_1':('M23','1','Juvenile and adult alarm production to unfamiliar raptor models.'),
'M23_2':('M23','2','Juvenile alarm production in three audience conditions.')}
def fig(k):
 if k in photos:return dict(photos[k])
 a,n,desc=figdesc[k];label=n if n.startswith('Table') else 'Fig. '+n
 return {'kind':'article','path':'figures/'+k+'.png','caption':short[a].replace('1980a','1980').replace('1980b','1980')+', '+label+'. '+desc,'source_url':'https://doi.org/'+raw[a]['doi']}
slides=[]
def add(title,asset,keys,*paras):
 assert len(paras)==3
 words=len(re.findall(r"\S+",' '.join(paras)));assert 90<=words<=170,(title,words)
 slides.append({'title':title,'layout':'figure-right','figure_width':5.8,'body':list(paras),'transcript':list(paras),'cite':'; '.join(short[k] for k in keys),'refs':[refs[k] for k in keys],'figure':fig(asset)})
add('Vervet alarms distinguish classes of danger','vervet',['S80','A80'],
'**Alarm calls** are vocal signals associated with danger. Free-ranging vervet monkeys, now classified as _Chlorocebus pygerythrus_, produced different calls during encounters with terrestrial predators, aerial predators and snakes. These categories were identified from recordings and observations during a 14-month study in Amboseli, Kenya.',
'Seyfarth, Cheney and Marler played recorded calls when predators were absent. Monkeys changed their looking direction and escape behavior according to the call type within the 10 s observation window. The playback separated hearing an alarm from directly seeing its usual eliciting predator.',
'**Referential signaling** concerns information about external objects or events. Predator-appropriate responses support that functional interpretation, while leaving unresolved whether a caller intends to describe a predator or a listener represents it in a human-like symbolic form.')
add('Leopard alarms recruit escape into trees','leopard',['S80','A80'],
'Leopards are terrestrial ambush predators: an attack can approach a monkey moving or feeding on the ground. In Amboseli, leopard-associated alarm calls were followed by movement into trees. Escape location therefore mattered, rather than movement alone being the relevant response.',
'Playback trials used a concealed speaker without a leopard present. The investigators filmed behavior before and after the call, comparing the same recipients across the alarm event. Ground-dwelling subjects were more likely to run into trees after leopard alarms than after the other alarm categories.',
'An alarm could initiate an appropriate escape without direct visual identification of the predator. This behavioral result identifies an acoustic contribution to defensive action; it does not establish an obligatory reflex, nor does it measure the neuronal pathway generating the movement.')
add('Eagle alarms redirect attention and cover seeking','eagle',['S80','A80'],
'Martial eagles attack from above, so looking upward and reaching protective cover can address a different threat from climbing away from a leopard. Field observers recorded eagle-associated calls while monitoring the recipients’ position and subsequent behavior in the same habitat.',
'When these recordings were broadcast without an eagle present, monkeys on the ground looked upward and sometimes ran into cover. Monkeys already in trees could leave the tree. Responses were evaluated during the 10 s after playback against behavior during the preceding 10 s.',
'The contrasting actions depend partly on the recipient’s vulnerability at that location. A shared call category need not prescribe one fixed motor sequence. The experiment supports discrimination of aerial danger without demonstrating a representation of a particular individual eagle.')
add('Snake alarms recruit ground-directed inspection','python',['S80','A80'],
'**Snake alarms** were high-pitched chutter-like vocalizations associated with pythons and other threatening snake encounters. Ground-directed inspection can locate a nearby threat whose danger differs from an aerial attack. Looking down and approaching a snake were distinguished from running into a tree.',
'In predator-free playbacks, snake calls caused more ground-directed looking than the other call types. The researchers scored behavior before and after the broadcast, using the same 10 s window for comparison. The speaker supplied sound while the physical snake stimulus was absent.',
'This contrast supports a relationship between call category and defensive assessment. Inspection is an action that can obtain additional evidence; it is not itself a measurement of conceptual meaning. Calling, looking, approaching and escaping are distinct components of the response.')
add('Acoustic structure distinguishes alarm categories','A80_1',['A80'],
'A **spectrogram** represents acoustic energy across time and frequency. The classic recordings compared leopard, eagle and snake calls from identified adults and a juvenile. Horizontal time scales and vertical frequency scales permit comparison of tonal structure, duration and repeated acoustic units.',
'The recordings used a 300 Hz analysis filter and frequency displays extending from 80 to 8000 Hz for these examples. Eagle alarms contained low-frequency components, snake alarms had higher-frequency chutter structure, and leopard calls included short tonal units or repeated sequences.',
'Differences were detectable both in the recordings and by listeners in the field. Acoustic distinctness establishes a basis for discrimination, but a spectrogram alone cannot establish what monkeys infer. The behavioral playback experiment supplies a separate test of the consequences of hearing these sounds.')
add('Caller sex changes form within an alarm category','A80_3',['A80'],
'An **acoustic unit** is an individual sound element, whereas a sequence contains several such elements. Adult male leopard alarms often consisted of repeated units. Female and juvenile leopard alarms could instead contain a single short element, despite being associated with the same predator category.',
'Seyfarth and colleagues compared calls from identified individuals rather than assuming that one waveform represented the entire population. Their spectrograms preserve 0.5 s time scales. Some females also produced multi-unit leopard calls, especially when a predator was close or attacking.',
'Call category and detailed acoustic form are therefore related but distinct descriptions. Variation among callers does not eliminate a shared behavioral function. These observations do not by themselves separate effects of sex, body characteristics, threat proximity and individual differences in vocal production.')
add('Playback isolates sound from predator visibility','S80_T1',['S80','A80'],
'**Playback** presents a previously recorded signal to test its effect on a recipient. The classic field experiment concealed the loudspeaker and broadcast leopard, eagle or snake alarms when no predator was present. Speaker orientation and call order were varied across trials.',
'The Science report compared the 10 s before each broadcast with the 10 s afterward. Ground responses distinguished tree escape, cover seeking and looking up or down. The corresponding table also separates monkeys already in trees from those on the ground.',
'Removing the predator addresses the alternative that recipients merely copied responses to something they could see. It leaves acoustic and social information in the call available. A response to sound is evidence about reception, while the caller’s own motives require different observations or manipulations.')
add('Long and short calls retain category differences','A80_4',['A80','S80'],
'Call **duration** is the time occupied by the vocalization; a longer call can also contain more repeated units. Natural recordings permitted the investigators to construct short and long versions while retaining the characteristic structure associated with each alarm category.',
'Short stimuli averaged 0.3 s and contained one acoustic unit. Long stimuli averaged 3.7 s and contained approximately five units. Matched recordings from the same caller helped separate duration from differences in caller identity, and playback compared the resulting defensive responses.',
'Changing duration did not erase the principal differences between response categories. The result argues against duration alone explaining leopard, eagle and snake responses. It does not imply that duration is behaviorally irrelevant, because urgency and response magnitude can vary independently of the kind of action selected.')
add('Amplitude alone does not explain alarm responses','A80_1',['A80','S80'],
'**Amplitude** concerns sound magnitude, while acoustic structure includes its frequency distribution and temporal pattern. The natural calls differed in loudness: reconstructed field playback levels averaged 56 dB for leopard alarms, 53 dB for eagle alarms and 48 dB for snake alarms.',
'The investigators also compared responses where amplitude ranges overlapped and conducted amplitude-equalized trials. Category differences in defensive behavior persisted. These controls addressed whether louder sounds simply produced a different degree of generalized disturbance rather than a different kind of response.',
'The evidence rejects amplitude as a sufficient explanation for the category-specific actions in this preparation. It does not establish that internal arousal contributes nothing to natural calling. Sound level, caller state and external danger can covary without being interchangeable explanations for every measured response.')
add('Receiver location changes the available escape action','S80_T1',['S80','A80'],
'**Context** includes the recipient’s surroundings and position when a signal arrives. The classic experiments tested subjects on the ground and subjects in trees, allowing the same alarm category to be evaluated where available refuge and vulnerability differed.',
'Ground subjects commonly escaped upward after leopard alarms, whereas eagle alarms could make tree-dwelling monkeys leave the tree. The 10 s scoring windows compared these actions with each individual’s behavior before playback, rather than treating all movement as one defensive response.',
'A stable association with a danger class is compatible with context-dependent action. The same external threat can demand different movements from different starting positions. These experiments did not support a context-only account of all alarm distinctions, because different calls also elicited contrasting responses in the same setting.')
add('Infants classify threats more broadly than adults','S80_1',['S80'],
'**Ontogeny** is change during an individual’s development. In the Amboseli observations, infants gave eagle alarms to a broad range of birds and sometimes to harmless stimuli. Adult callers restricted such alarms more strongly to dangerous aerial species, including martial eagles.',
'The published comparison follows alarms collected across 14 months and displays the stimuli associated with infant, juvenile and adult calling. Infants’ errors were structured: aerial stimuli tended to elicit eagle calls, terrestrial mammals leopard calls, and long thin objects snake calls.',
'The developmental difference is consistent with refinement within broad perceptual categories. It does not mean infants begin without discrimination. Because these were observations across age classes, the contribution of maturation, personal experience and learning from adults could not be isolated by this comparison alone.')
add('Development refines recognition within broad classes','S80_1',['S80'],
'**Predator classification** assigns different encountered objects to threat categories. The classic developmental observations contrasted broad infant categories with narrower adult associations. Adults encountered many harmless species without alarming and more selectively called to predators relevant to the local habitat.',
'The eagle-alarm comparison includes raptors, non-raptor birds and occasional other stimuli. Records accumulated during a 14-month field study linked each call to an identified eliciting object. Juvenile patterns lay between the broad infant and more selective adult patterns.',
'This relationship concerns the use of a call, not necessarily the acquisition of a new acoustic form. The original authors left the learning process unresolved. Age-related refinement supports experience-sensitive categorization, while controlled changes in experience are needed to identify how social and individual information contribute.')
add('Female calls occupy several acoustic clusters','P15_1A',['P15'],
'An **acoustic cluster** groups calls with similar measured sound properties without first assigning them a predator name. Price and colleagues analyzed recordings from predator encounters and aggressive interactions. Female calls separated into four broad groups with differences in element length and frequency distribution.',
'The source spectrograms display frequency in kHz and time in seconds; representative elements are shown against 0.2 s scales. Some clusters contained repeated short sounds, whereas a terrestrial-predator-associated cluster contained fewer, longer elements. This analysis extended the classic qualitative descriptions.',
'Clustering establishes structure in the recorded repertoire rather than a neural category boundary. A group of acoustically similar sounds can occur in more than one behavioral setting. The number of analytical clusters does not itself establish the number of meanings recognized by a monkey.')
add('Time and frequency contribute different call features','P15_1A',['P15'],
'**Temporal features** describe duration and spacing; **spectral features** describe how energy is distributed across frequencies. Price and colleagues measured both rather than identifying alarm types from one frequency or one duration alone. The acoustic examples retain their original kHz and second scales.',
'Female terrestrial-predator calls had longer individual elements than aerial and snake-associated calls. Reported mean element durations were 107.7 ms for terrestrial encounters, 43.9 ms for aerial encounters and 38.3 ms for snake encounters. These measurements concern elements rather than entire alarm bouts.',
'Multiple features can support discrimination even when no single measure creates a perfect boundary. The analysis describes the recorded calls; it does not identify which feature a listener actually uses. Controlled playback changes would be needed to attribute behavioral discrimination to one feature independently.')
add('Female predator calls remain acoustically distinct','P15_1B',['P15'],
'**Production specificity** is the association between a signal and the situations in which it is produced. Restricting their analysis to predator encounters, Price and colleagues compared female calls recorded during aerial, snake and terrestrial threats. The corresponding acoustic distributions separated strongly.',
'Spectral measurements help distinguish these contexts. Mean peak frequency was 986 Hz for aerial calls, 2840 Hz for snake calls and 2374 Hz for terrestrial calls. Temporal structure also differed, so peak frequency was not the sole basis of classification.',
'The result supports acoustic differences among predator-associated female calls in this data set. It does not establish that those sounds occur only with predators, because aggressive contexts were excluded from this particular comparison. Specificity depends on which alternative eliciting situations are actually examined.')
add('A call element is not the entire alarm bout','P15_1B',['P15'],
'A **call element** is a component within a compound vocalization; a **bout** can contain successive vocalizations. Price and colleagues separated measures of the complete call from spectral measures of its individual elements, avoiding the assumption that every duration describes the same biological unit.',
'Female snake-associated calls contained more short elements than terrestrial-predator calls. Reported mean element numbers were 4.1 for snake calls and 1.4 for terrestrial calls, while their mean element durations were 38.3 ms and 107.7 ms respectively. Different arrangements therefore produced contrasting temporal patterns.',
'These source measurements connect acoustic organization to the eliciting context without claiming a one-to-one translation into a word. A listener could use the pattern jointly with frequency and social information. The recordings alone do not determine whether element count is represented separately by the auditory system.')
add('Aggression overlaps with female alarm acoustics','P15_1C',['P15'],
'**Aggression** comprises antagonistic interactions within or between groups. Price and colleagues added recordings from these situations to the female predator-call analysis. Calls associated with snakes and aerial predators then overlapped with aggressive calls, weakening a simple one-call–one-predator description.',
'Snake-associated chutter-like sounds resembled some intergroup calls. Aerial-associated rraup-like sounds resembled sounds from escalated aggression. Mean peak frequencies during between-group and within-group aggression were 1715 Hz and 1456 Hz, within the broader range occupied by predator-associated calls.',
'Production context cannot always be read directly from acoustic structure. This finding does not eliminate information available to recipients: additional acoustic details and current circumstances can influence their response. It does restrict claims that every familiar alarm form is exclusively a label for one predator class.')
add('Graded variation differs from discrete call types','P15_1C',['P15'],
'**Graded variation** consists of intermediate forms along acoustic dimensions, whereas **discrete categories** have clearer separations. Female chutter-like and rraup-like calls occupied overlapping acoustic space when aggressive contexts were included. The published distribution is based on measured features rather than hand-assigned word equivalents.',
'The original spectrograms preserve 0.2 s time scales and frequency axes in kHz. They reveal different repeated-element patterns whose measured distributions can overlap. Calls from the same broad acoustic neighborhood occurred during snake encounters, aerial encounters and social aggression.',
'An overlapping production distribution does not preclude categorical perception by listeners. Perceptual categorization would require a reception experiment measuring responses across controlled acoustic variation. The study establishes acoustic intergradation and context overlap, while leaving the exact relationship between that continuum and recipients’ decisions unresolved.')
add('Male alarms have their own acoustic organization','P15_2A',['P15'],
'Male and female recordings were analyzed separately because their acoustic structures differed substantially. In East African males, Price and colleagues identified three clusters rather than the four-cluster female solution. The male categories differed in repeated-element pattern and spectral distribution.',
'The male spectrograms retain second and kHz scales, with representative sounds displayed against 0.2 s intervals. One group contained many short high-frequency elements; another contained fewer longer elements; a third had low-frequency components. Their associations with predator contexts were not equally exclusive.',
'Sex-specific acoustic organization cautions against treating a recording from one caller as the universal alarm template. The analysis concerns measured repertoire structure and does not identify the anatomical origin of sex differences. Body characteristics, vocal mechanics and contextual usage remain distinct possible contributors.')
add('Male snake and eagle calls partially overlap','P15_2A',['P15'],
'**Acoustic overlap** occurs when different eliciting contexts produce similar ranges of measured call features. In the male data, some low-frequency calls occurred during both eagle and snake encounters. The published clusters therefore did not correspond perfectly to three mutually exclusive predator categories.',
'Mean male element duration was 76.5 ms for aerial calls, 61.1 ms for snake calls and 112.0 ms for terrestrial calls. Male peak frequencies averaged 1090 Hz, 1639 Hz and 1904 Hz respectively. Duration and frequency jointly described these contrasts.',
'Differences in average values do not make every individual call unambiguous. A listener may integrate several features and additional environmental information. These recordings establish distributions of production, while recipient-specific playback experiments are needed to determine how ambiguity affects defensive behavior in a particular setting.')
add('Spectral bandwidth varies across male alarm contexts','P15_2B',['P15'],
'**Frequency range** describes the span of acoustic frequencies represented in a measured call element. Price and colleagues compared this measure with temporal organization and energy distribution in male alarms. Their recorded calls differed by context across several dimensions rather than one isolated cue.',
'Reported mean frequency ranges were 1832 Hz for aerial calls, 4069 Hz for snake calls and 3794 Hz for terrestrial calls. The original spectrograms retain frequency and time scales, allowing these broad spectral differences to be related to their temporal pattern.',
'A broader range does not by itself mean greater threat intensity or a different semantic category. It is a physical feature of the sound. The study does not establish how auditory neurons weight bandwidth relative to other features, nor whether the recipient’s escape decision depends on this measure alone.')
add('Classifier separation is not a listener experiment','P15_2B',['P15'],
'An **acoustic classifier** assigns recordings to groups using measured features. Price and colleagues evaluated predator-context separation in male calls using acoustic measurements, with checks that reduced the possibility that caller identity alone explained the result. This is an analysis of recordings, not a playback test.',
'The figure represents calls associated with aerial, snake and terrestrial encounters. Source spectrograms have 0.2 s scales and frequency axes in kHz. Terrestrial-associated male calls separated more clearly, while some snake and aerial recordings occupied overlapping portions of acoustic space.',
'A computer’s ability to classify calls establishes available information under the chosen measurements. It does not prove that a monkey extracts the same features or recognizes identical categories. Behavioral responses and neural recordings address different stages between acoustic information and an inferred external event.')
add('Male barks also occur during social conflict','P15_2C',['P15'],
'**Barks** are a male call form associated with terrestrial threats but also with antagonistic interactions. Price and colleagues examined South African recordings from real leopard encounters, leopard-model presentations and social aggression. These contexts produced overlapping acoustic distributions.',
'The source pairs representative waveforms’ spectral patterns with a distribution of acoustic scores. The spectrograms retain a 0.2 s reference scale. Calls to real leopards were more similar to aggressive barks than calls elicited by leopard models were, within the available recordings.',
'A bark therefore does not guarantee that a leopard is present. Recipients can still use it as information about a relevant event or state. The distinction matters for claims of production specificity: an exclusively predator-linked interpretation would omit naturally occurring social uses of the same general call form.')
add('External events and caller state can both shape calls','P15_2C',['P15'],
'**Affective state** refers to an animal’s emotional or motivational condition. **Cognitive appraisal** concerns its evaluation of a situation. Price and colleagues proposed that both could contribute to call structure and use, because acoustically similar male barks occurred with predators and social aggression.',
'The recorded distributions compare real leopard, model leopard and aggressive encounters; accompanying spectrograms preserve a 0.2 s timescale. Acoustic overlap is the measured finding. A shared internal state linking those contexts is a possible explanation, not something directly recorded in the callers.',
'Information about an external event and information about internal state need not be mutually exclusive. The study does not identify a neurotransmitter, receptor or ion channel mediating either contribution. A molecular mechanism cannot be inferred from call similarity or from the recipient’s response alone.')
add('Sound controls isolate features of vocal signals','O15_1C',['O15'],
'**Conspecific vocalizations** are calls produced by members of the listener’s own species. Ortiz-Rios and colleagues compared rhesus macaque calls with environmental sounds and scrambled calls during functional magnetic resonance imaging. These macaque experiments provide comparative neural evidence rather than direct recordings from vervets.',
'The stimuli were arranged into 8 s sequences and presented at approximately 80 dB sound pressure level. Scrambling rearranged 200 ms sound segments across time and frequency while preserving substantial local acoustic structure. Environmental sounds supplied another class of complex natural sounds.',
'Comparing these conditions addresses whether activation reflects hearing complex sound or sensitivity to intact vocal patterns. None of the conditions tested vervet predator meanings. The measured responses concern macaque auditory processing, so a homology claim must remain separate from an identified vervet alarm-decoding circuit.')
add('Sparse MRI sampling separates sound from scanner noise','O15_1AB',['O15'],
'**Functional MRI** measures changes associated with blood oxygenation rather than individual neuronal spikes. Scanner operation itself generates sound. Ortiz-Rios and colleagues used **sparse sampling**, leaving intervals for acoustic stimulation before acquiring an image volume, to reduce interference from scanner noise.',
'Acquisition began 6 s after stimulus onset; each image volume took 2.18 s. Sound conditions alternated with silence trials. One macaque performed an auditory task with eye movements, while another listened during maintained fixation, allowing attention-related differences to remain visible as a limitation.',
'The delayed imaging response can localize sound-sensitive regions but cannot resolve the millisecond timing of a particular alarm decision. A blood-oxygenation contrast also does not identify synaptic sign, transmitter release or receptor activation. Those mechanisms require measurements beyond this imaging preparation.')
add('Sound-sensitive regions span the ascending pathway','O15_2B',['O15'],
'The **ascending auditory pathway** carries sound-related signals through brainstem, thalamic and cortical regions. In awake macaques, Ortiz-Rios and colleagues compared complex sounds with silence and localized activation using anatomical MRI sections. The maps include inferior colliculus, medial geniculate and auditory cortex.',
'The **inferior colliculus** is a midbrain auditory region, and the **medial geniculate nucleus** is the auditory thalamic relay. Functional images used voxels measuring 1.5 × 1.5 × 1.9 mm. Activation at that scale combines signals from many cells and their associated vasculature.',
'These regions responded to several complex-sound categories, not exclusively to meaningful calls. Their participation provides anatomical context for signal reception. The imaging study did not trace a serial synaptic chain from a vervet alarm to an escape response or measure activity in identified defensive motor neurons.')
add('Auditory cortical activation extends beyond primary cortex','O15_2A',['O15'],
'**Primary auditory cortex**, also called A1, is a cortical region receiving substantial ascending auditory input. **Belt** and **parabelt** designate adjoining auditory cortical regions. Ortiz-Rios and colleagues mapped complex-sound activation onto anatomical surfaces and found responses across these auditory territories.',
'The comparison used 8 s sound sequences and silence trials, so widespread activation reflects auditory stimulation before any stronger claim of vocal selectivity. Responses also extended along the superior temporal gyrus, a cortical ridge containing auditory and auditory-associated areas.',
'An anatomical activation map identifies where a measured response occurs. It does not prove that each colored region performs the same computation or that activation propagates in a fixed order. Selectivity for intact calls requires additional comparisons against appropriately matched non-call or scrambled-call controls.')
add('Hemispheric response differences depend on the contrast','O15_2B',['O15'],
'**Hemispheric lateralization** is an unequal contribution or measured response between the two sides of the brain. Ortiz-Rios and colleagues compared auditory activation in both macaque hemispheres using anatomical sections and regional blood-oxygenation responses rather than inferring dominance from one visible activation patch.',
'Both animals had a larger response to complex sounds in the right hemisphere in this preparation. The sounds were calibrated to approximately 80 dB sound pressure level, and silence trials provided the baseline. The observation applied to the tested sound set and imaging conditions.',
'This difference is not evidence that the right hemisphere alone understands alarms or that a vervet’s semantic decisions have the same lateralization. Attention differed between animals, and contrasts can emphasize different components of processing. Regional response magnitude and behavioral necessity are separate empirical questions.')
add('Anterior temporal regions prefer intact calls','O15_3B',['O15'],
'The **superior temporal gyrus** contains auditory-associated cortex; its anterior portion lies toward the front of the temporal lobe. Ortiz-Rios and colleagues compared intact macaque calls with scrambled versions to ask where local acoustic similarity was insufficient to account for the imaging response.',
'Scrambling used 200 ms by one-octave acoustic tiles. An **octave** is a doubling or halving of frequency, here describing the spectral extent of each tile. Intact calls produced stronger responses in anterior temporal regions, including rostrotemporal areas, than these scrambled controls.',
'The result supports sensitivity to the organized vocal pattern beyond some preserved local sound features. It does not identify a neuron representing a predator or prove understanding of a call’s referent. These were macaque vocalizations and regional imaging signals, not semantic tests of vervet alarm categories.')
add('Frontal activation requires careful acoustic controls','O15_3A',['O15'],
'**Ventrolateral prefrontal cortex** is a frontal cortical territory, and **ventral premotor cortex** participates in sensorimotor processing. Macaque imaging contrasts between calls and environmental sounds produced activation in portions of frontal and parietal cortex as well as temporal auditory regions.',
'The environmental sounds were complex natural recordings, but their spectrotemporal patterns differed from calls. **Spectrotemporal structure** combines how acoustic energy varies across frequency and time. The authors’ 200 ms scrambling control preserved more of the calls’ local sound properties than environmental sounds did.',
'Scrambled calls also activated some frontal and parietal regions, limiting a vocal-meaning interpretation of those contrasts. A response to a call can arise from acoustics, task demands or associated processing. Regional activation therefore does not establish a frontal semantic code or a causal contribution to vervet alarm comprehension.')
add('Converging contrasts localize a narrower call preference','O15_4B',['O15'],
'A **conjunction analysis** identifies regions meeting more than one comparison, rather than accepting a result found with only one control. Ortiz-Rios and colleagues combined call-versus-environmental-sound and call-versus-scrambled-call comparisons, then examined convergence across the macaques.',
'The strongest common result involved anterior temporal regions, including lateral rostrotemporal cortex and the rostrotemporal pole. Stimuli were presented as 8 s sequences, with image acquisition beginning after 6 s. The anatomical map localizes the blood-oxygenation response retained across these comparisons.',
'This convergence supports a narrower vocal-processing interpretation than the broader environmental-sound contrast alone. It still does not identify a molecular pathway, spike-timing code or predator representation. Comparative auditory specialization can constrain plausible explanations for communication without establishing the neural implementation of functional reference in wild vervets.')
add('Green monkeys do not copy every vervet response','P14_1',['P14'],
'West African **green monkeys**, _Chlorocebus sabaeus_, are close relatives of vervets but a distinct species in this study. Price and Fischer presented leopard and snake models in Senegal and filmed the first 10 s of each subject’s response to the detected model.',
'Leopard models elicited higher tree climbing than snake models. Standing bipedally occurred in both threat settings rather than being a uniquely snake-directed response. The researchers recorded movement and maximum height, separating refuge selection from posture and generalized inspection.',
'Similar ancestry does not guarantee identical predator-response mappings. The model experiment established behaviors appropriate for interpreting this population’s subsequent playback responses. It does not justify assigning every posture the meaning reported in Amboseli vervets, nor does a model encounter fully reproduce the risk of an attacking predator.')
add('Closely related monkeys use graded predator chirps','P14_2',['P14'],
'A **chirp** is the call form examined in the green-monkey predator experiments. Females and juveniles produced chirps to both leopard and snake models. Price and Fischer constructed paired playback sequences using recordings from the two eliciting conditions rather than treating them as completely different call families.',
'The spectrograms preserve time in seconds and frequency in kHz. Paired sequences were matched for chirp number, inter-call interval and overall sequence duration, with their intervals constrained to naturally occurring values. Recordings were also normalized before experimental broadcasting.',
'These controls reduce explanations based solely on bout length or repeated-call number. Graded differences within chirps remained available to listeners. The preparation does not establish that a single acoustic dimension carries the predator distinction; frequency distribution and element duration varied together in the natural recordings.')
add('Chirp distributions overlap across predator contexts','P14_3',['P14'],
'**Graded acoustic categories** can contain considerable overlap even when their average structures differ. Price and Fischer analyzed green-monkey chirps elicited by leopard and snake models. Duration and an early peak-frequency measure contributed strongly to separating the recordings.',
'Leopard-associated chirps were longer and had a higher early peak frequency than snake-associated chirps. The source analysis measured duration in milliseconds and frequency in Hz. Its score distributions overlapped rather than producing two completely separated groups of calls.',
'The findings support physically detectable variation within one broad call form, not perfect production specificity. Overlap leaves some individual sounds ambiguous. Whether a recipient treats an intermediate chirp as a leopard threat, a snake threat or a reason to inspect depends on reception and decision processes not measured by this acoustic analysis alone.')
add('Control bird calls distinguish alarms from broadcasting','P14_4',['P14'],
'An **experimental control** excludes a competing explanation for an observed response. Price and Fischer broadcast nonpredatory bird calls alongside green-monkey chirp stimuli. Birds’ calls were a control for the playback procedure itself rather than another predator-associated monkey signal.',
'Monkeys responded more often to chirps than to the bird sounds. Playback intensity remained within natural calling levels, 60–85 dB measured at 10 m from the source. A different recording sequence was used for each experiment to avoid repeatedly testing one acoustic exemplar.',
'The contrast supports a response to biologically relevant acoustic information rather than to any sound from the speaker. It does not identify whether the recipient represents a predator, experiences conditioned danger or combines both. Those alternatives concern the interpretation of the signal beyond the procedural control.')
add('Predator priming separates prior evidence from call type','P14_4',['P14'],
'**Priming** supplies relevant information before a later test. Price and Fischer exposed green monkeys to a leopard model, a snake model or no predator model before broadcasting chirps. The calls were played approximately 1 h after the model presentation, once alarm calling had stopped.',
'The experiment independently varied the preceding model and the recorded chirp’s original context. Leopard-associated chirps more often elicited climbing above 2 m than snake-associated chirps. Prior model exposure did not clearly change which immediate response category recipients selected.',
'Acoustic cues therefore strongly influenced the early action in this preparation. The absence of a clear immediate priming effect does not establish that prior knowledge was erased. Information presented an hour earlier can influence later persistence differently from the first movement after a call.')
add('Prior predator evidence changes defensive persistence','P14_4',['P14'],
'**Response persistence** is the time an action or defensive state continues after its initiation. Price and Fischer distinguished immediate tree climbing from remaining in a tree after playback. These measures address different consequences of hearing the same broad alarm form.',
'Subjects stayed longer in trees when leopard-model exposure and leopard-associated chirps both supported terrestrial danger. The published persistence measure records whether a subject stayed more than 200 s. The immediate response measure instead records climbing above 2 m following the broadcast.',
'The evidence is consistent with prior information contributing to sustained risk assessment even where early action mainly follows acoustics. It does not distinguish an updated internal representation from a change in subsequent decision-making. Immediate response and persistence should not be treated as interchangeable measures of meaning attribution.')
add('The same male bark can enter contrasting contexts','D23_1',['D23'],
'South African male vervets produce similar **alarm barks** during terrestrial-predator encounters and between-group conflict. Deshpande and colleagues tested whether recipients used current social circumstances to interpret the sound. The stimuli included one predator-associated and one intergroup-associated bark from the same adult male.',
'Each female recipient heard the same assigned recording in both contexts, with naturalistic amplitude at a speaker distance of 30–50 m. This within-recipient comparison held the stimulus constant while changing the surrounding intergroup situation. The published spectrograms preserve seconds and frequency in Hz.',
'Holding the recording constant separates contextual effects from differences between the sounds used on different occasions. It does not prove that every bark variant is acoustically identical, nor that every receiver uses the same inference. The experiment tests this call and these receivers under specified field conditions.')
add('Ongoing social context differs from earlier priming','D23_2',['D23','P14'],
'An **intergroup encounter** occurs when members of neighboring monkey groups interact. Deshpande and colleagues tested recipients away from the conflict frontline while the encounter was ongoing. Subjects remained at least 30 m from the frontline and were foraging, resting or grooming.',
'The same recipients were tested without an intergroup encounter after at least 2 h without such an event or natural alarm calling. Habitat and approximate group spread were kept similar, and playback came from 30–50 m away. The source’s published field layout specifies these spatial relations.',
'This manipulation supplies immediate contextual information, unlike model exposure approximately 1 h before the green-monkey playbacks. Different timing and call types can explain different outcomes without making the studies contradictory. The design does not experimentally assign whether the natural intergroup encounter begins.')
add('Context alters information seeking toward the caller','D23_3',['D23'],
'**Information seeking** can involve orienting toward a caller to obtain further cues about an alarm’s cause. Deshpande and colleagues measured how long recipients looked toward the speaker after hearing the same male bark with or without an ongoing intergroup encounter.',
'Recipients generally looked toward the speaker longer when no intergroup encounter was occurring. Looking duration was measured in seconds, and the field observations continued for 10 min after playback. During an encounter, the surrounding social activity already supplied a plausible explanation for male barking.',
'The measured effect supports integration of acoustic and contextual information. Interpreting longer looking as uncertainty is a proposed explanation rather than a directly measured mental state. The behavior does not establish that recipients imagined a specific hidden predator, and no predator-specific escape response occurred in this experiment.')
add('Context changes vigilance without forcing escape','D23_4',['D23'],
'**Vigilance** is monitoring the surroundings while maintaining an alert posture. Deshpande and colleagues scored its duration separately from speaker-directed looking, startle and predator-specific escape. Female recipients were more vigilant after barks outside an intergroup encounter than during one.',
'The source plots vigilance in seconds. Some recipients displayed no vigilance during the encounter condition, although all heard the bark. No predator-specific escape response occurred in either condition. Startle was scored as a sudden body movement and was kept separate from the duration measures.',
'The vigilance and looking measures establish altered monitoring of the surroundings and presumed caller. Defensive responses can change in intensity without changing into overt flight. These observations support context-sensitive reception while leaving the underlying neural, affective and representational mechanisms unmeasured.')
add('Young vervets alarm to unfamiliar raptor models','M23_1',['M23','S80'],
'**Social learning** concerns behavioral change supported by information from other individuals. Mohr and colleagues presented unfamiliar raptor models to juvenile vervets aged 1–2 years while monitoring nearby audiences. The juveniles could inspect both the model and the reactions of other monkeys.',
'Juveniles sometimes alarmed, whereas adults did not alarm to these models. Audience members were defined as individuals within 10 m of the subject. The comparison is consistent with more experienced adults judging the unfamiliar models differently from younger animals, as in the classic age-related category refinement.',
'Caller age and alarm production were associated, but the preparation did not independently manipulate lifetime experience. Silence by an adult does not establish indifference or failure to detect the model. The measured developmental difference concerns calling behavior rather than the discovery of an age-specific neural circuit.')
add('Audience patterns do not establish a learning mechanism','M23_2',['M23'],
'An **audience effect** is a change in signaling associated with who is nearby. Mohr and colleagues compared juvenile responses with mothers, siblings or unrelated group members present within 10 m. Other kin were excluded from the mother and sibling conditions to separate these audience categories.',
'The descriptive pattern contained more juvenile calling with siblings than with mothers or unrelated animals. However, the study did not establish an overall audience-composition effect, and audience size was not systematically controlled. Model-directed vigilance by mothers and siblings provided additional social information.',
'These observations motivate explanations involving experience, relatedness or awareness, but they do not demonstrate imitation, teaching or one-trial learning. A difference in immediate calling is distinct from a lasting acquired association. The restricted design therefore supports cautious developmental interpretation rather than a proven mechanism of alarm learning.')
assert len(slides)==44,len(slides)
tk=[('Functional reference','is supported when call production relates to external events and playback elicits appropriate responses without the eliciting stimulus.'),('Classic playback controls','separate acoustic effects from predator visibility; duration, amplitude and caller identity do not alone explain the response categories.'),('Context-sensitive reception','allows the same broad call form to guide different actions or levels of vigilance depending on location, social events and prior evidence.'),('Developmental refinement','narrows broad juvenile threat categories; age-related observations do not by themselves distinguish maturation, personal experience and social learning.'),('Acoustic overlap','means predator-associated calls can resemble aggression calls; information-bearing reception does not require a universal one-call–one-predator dictionary.'),('Neural evidence','locates macaque vocal sensitivity in auditory and anterior temporal regions, while regional imaging does not identify a vervet semantic circuit or molecular mechanism.')]
spec={'lecture':38,'theme':'prussian-fog','content_slides':44,'title_image':photos['vervet'],'slides':slides,'takeaways':{'items':[{'lead':a,'text':b} for a,b in tk],'transcript':[a+' '+b for a,b in tk],'cite':'Seyfarth et al. (1980a, b); Price et al. (2015); Ortiz-Rios et al. (2015); Deshpande et al. (2023)','refs':list(refs.values())}}
(p/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
print('Wrote 44 content slides:',min(len(' '.join(s['body']).split()) for s in slides),'to',max(len(' '.join(s['body']).split()) for s in slides),'words')
