"""NEUR 411 Lecture 40: original primary figures and source-based teaching notes."""
import copy,json
from pathlib import Path
B=Path(__file__).resolve().parent
R={p['id']:p for p in json.loads((B/'research.json').read_text())['sources']}
C={'nagel03':'Nagel et al. (2003)','boyden05':'Boyden et al. (2005)','govorunova15':'Govorunova et al. (2015)','inagaki14':'Inagaki et al. (2014)','cande18':'Cande et al. (2018)','veraszto17':'Verasztó et al. (2017)','bezares18':'Bezares-Calderón et al. (2018)','antinucci19':'Antinucci et al. (2019)','grover20':'Grover et al. (2020)','szuts11':'Szuts et al. (2011)','zhang24':'Snyder et al. (2024)','forli25':'Forli et al. (2025)','montgomery15':'Montgomery et al. (2015)'}
F={}
for n,f in json.loads((B/'figure_sources.json').read_text()).items():
 k=f['paper'];F[n]={'path':f'figures/{n}.png','kind':'article','caption':f"{C[k]}, Fig. {f['figure']}. {f['description']}",'source_url':'https://doi.org/'+R[k]['doi']}
S=[]
def add(title,ids,imgs,body,extra,h=2.7,tall=False):
 ids=ids.split();pars=body.split('||')
 for n in imgs:
  k=json.loads((B/'figure_sources.json').read_text())[n]['paper']
  if k not in ids:ids.append(k)
 sd={'title':title,'body':pars,'cite':'; '.join(C[k] for k in ids),'refs':[R[k]['reference']for k in ids],'transcript':[pars[0],[pars[1],[extra]],*pars[2:]],'figure_width':6.0}
 if len(imgs)==1:sd.update(layout='figure-right',figure=copy.deepcopy(F[imgs[0]]))
 else:
  assert len(imgs)==2
  sd.update(layout='figures-right',figures=[copy.deepcopy(F[n])for n in imgs],primary_figure_height=h)
  if tall:sd.update(figure_arrangement='side-by-side',primary_figure_width=4.2)
 S.append(sd)

add('Optical activation can recruit a specific action','cande18 inagaki14',['cande2','inag3b'],'''**Optogenetics** changes cellular activity by expressing a light-sensitive protein in selected cells. A **descending neuron** carries signals from the brain toward the **ventral nerve cord**, a longitudinal nervous-system structure whose motor networks organize movement. Cande and colleagues expressed the light-gated channel CsChrimson in identified descending-neuron populations of adult flies.||Flies received 15-s pulses of red light separated by 45-s recovery periods. Retinal-fed experimental flies increased occupancy of particular grooming or locomotor behaviors, whereas genetically matched flies without supplemental retinal supplied a stimulation control. **Retinal** is the light-absorbing cofactor required by the channel.||Recruiting a particular action establishes **sufficiency**: activating the tested cells can produce that response under the assay conditions. It does not establish that those cells normally initiate every occurrence of the behavior, or that the artificially imposed activity matches their natural firing pattern.''','The fly can move within its chamber during stimulation. A behavioral change is attributed to the light-sensitive cells only after comparing it with flies that experience the same illumination but lack the supplied cofactor. The published P1–pIP10 arrangement identifies a brain-to-nerve-cord pathway; it is a separate courtship example, not the anatomical identity of the grooming cells.',h=3.1)

add('A microbial channel directly couples light to current','nagel03',['nagel1'],'''**Channelrhodopsin-2**, or ChR2, is a retinal-containing membrane protein from the green alga _Chlamydomonas reinhardtii_. An **ion channel** provides a pathway through which charged particles move across the membrane. Nagel and colleagues expressed ChR2 in frog oocytes and mammalian cells to determine its primary action.||Blue illumination near 450 nm produced currents absent from uninjected oocytes. Under **voltage clamp**, an amplifier holds membrane voltage at a selected value while measuring current. Changing the held voltage changed current magnitude and direction, supporting a passive conductance rather than an ion pump.||A truncated construct containing the first 315 amino acids retained channel function. The findings locate the light-gated conductance within the membrane-spanning portion of the protein. They establish a cellular mechanism in expression systems, rather than a causal role for ChR2 in an animal’s natural behavioral circuit.''','An oocyte is an immature egg cell large enough for controlled electrical recordings. Expressing the same protein in more than one host helps separate its own function from a specialized component of the original algal sensory system. Passive ion movement follows electrical and concentration gradients rather than transporting a fixed ion number per photon.')

add('Ion substitution identifies the channel’s selectivity','nagel03',['nagel1b'],'''**Ion selectivity** describes which charged species can pass through a channel. Nagel and colleagues replaced salts around ChR2-expressing oocytes while measuring the response to the same blue-light stimulation. **Cations** carry positive charge; **anions** carry negative charge.||Photocurrents varied with the available cation. Replacing external chloride with aspartate did not appreciably change the current or its reversal voltage. **Reversal voltage** is the membrane voltage at which the net measured current changes direction. Calcium could also pass through ChR2, whereas magnesium permeability was negligible under the tested conditions.||At pH 9, with **pH** measuring acidity, the small current remaining in a solution containing the bulky cation N-methyl-D-glucamine disappeared, identifying a proton contribution at lower pH. These substitution controls support cation conduction. They do not justify assuming identical currents in neurons with different intracellular ion concentrations or membrane voltages.''','Changing one solution component at a time asks which ion is responsible for the current. Protons are hydrogen ions, and pH expresses their availability. Calcium entry also activated a native oocyte current; suppressing that secondary response with a calcium-binding compound helped isolate the channel’s own calcium permeability.')

add('Excised membranes retain rapid light gating','nagel03',['nagel3'],'''A light-evoked current could arise either from the expressed protein itself or from a signaling pathway that activates another channel. Nagel and colleagues recorded ChR2 in **excised membrane patches**, membrane fragments separated from the intact cell with their internal solution experimentally controlled.||Photocurrents remained after soluble cellular contents were replaced. A 10-ns laser flash triggered channel opening with a rise time near 200 µs or faster. Closing was much slower and depended on intracellular pH, spanning approximately 10–400 ms across the tested conditions.||The persistence and rapid onset support direct channel gating without a required diffusible intracellular messenger. The unequal opening and closing times also mean that light-pulse duration alone does not define the complete electrical response. These kinetics describe ChR2 in this preparation, not every subsequent channelrhodopsin variant.''','An inside-out patch exposes the membrane’s former cytoplasmic surface to the bathing solution. Manipulating that side of the membrane tests whether soluble cytoplasmic components are required and permits independent control of internal acidity. Rapid opening and pH-dependent closing are separate features of the measured response.')

add('Membrane expression enables optical drive of neurons','boyden05',['boyden1'],'''Boyden and colleagues introduced a ChR2 fusion with yellow fluorescent protein into cultured rat neurons using a **lentiviral vector**, a modified virus that delivers an expression construct. The fluorescent tag identified the expressing cells and their membrane-associated processes.||Blue light spanning 450–490 nm generated an average peak inward current near 496 pA, followed by a smaller sustained current near 193 pA. Neurons expressing the fluorescent tag alone did not produce light-evoked responses. These controls separate the channel’s electrical effect from fluorescence labeling and illumination.||Inward current depolarized the neuron, making its internal voltage less negative. Reaching firing threshold triggered an **action potential**, a rapid regenerative voltage change. A **synapse** is a contact that transmits signals between cells. Expression permits intervention without identifying the cell’s natural targets or behavioral function.''','A picoampere is one trillionth of an ampere and expresses the current measured by the recording amplifier. The fluorescent signal locates the introduced protein but does not establish that every labeled process produces an equal photocurrent. The electrical measurement verifies that the expression construct can actually change membrane excitation.')

add('Pulse timing controls spikes with finite reliability','boyden05',['boyden2','boyden1a'],'''An **action potential** is a rapid regenerative change in membrane voltage that carries a neuronal signal. Boyden and colleagues recorded neurons while applying repeated 10–15-ms light pulses, comparing the timing of evoked spikes across repeated stimulation sequences.||The same pulse sequence produced highly repeatable spike patterns, but not every light pulse elicited a spike. In two irregular stimulation protocols, about 76% and 85% of pulses successfully drove spikes. Spike reliability declined at higher rates in tests spanning 5–30 Hz.||Continuous illumination produced a well-timed initial spike followed by less precisely timed activity. Thus, a pulse train defines a controlled input rather than a guaranteed identical spike train in every neuron. Behavioral interpretations require validation of the actual neural response, especially when expression level and firing properties vary between cells.''','Current clamp allows membrane voltage to change while the amplifier records that change. Repeating the identical input distinguishes consistency of response timing from the probability that a response occurs. Precisely timed pulses can still fail to reach firing threshold, so temporal control and complete spike fidelity are different properties.',h=3.3)

add('Anion channels conduct a different class of ions','govorunova15',['gov2','gov3'],'''Govorunova and colleagues expressed light-sensitive proteins from the cryptophyte alga _Guillardia theta_ in mammalian cells. Two proteins, GtACR1 and GtACR2, functioned as **anion channelrhodopsins**, light-gated channels carrying negatively charged ions rather than the positive ions carried by ChR2.||Changing external sodium, potassium or calcium did not shift photocurrent reversal as expected for cation conduction. Replacing chloride with a nonpermeant anion did shift reversal. Currents were measured while membrane voltage varied in 20-mV steps, with ion substitutions providing the selectivity controls.||The chloride dependence supports anion conduction and excludes a simple inference from the sign of one recorded current. GtACRs could produce an inward current with a high-chloride recording solution. Whether the resulting voltage response excites or suppresses a neuron depends on its chloride gradient and starting membrane voltage.''','The patch electrode solution determines much of the intracellular ion composition during a whole-cell recording. A current’s sign is therefore interpreted together with the actual solutions. The ion-substitution measurements distinguish what the channel conducts from whether a particular neuron is inhibited by that conductance.',h=2.1)

add('Optical silencing depends on the chloride gradient','govorunova15 boyden05',['gov4','boyden1a'],'''A **chloride equilibrium potential** is the voltage at which the electrical and concentration forces on chloride balance. Opening an anion channel moves the membrane response toward this voltage; it does not impose a universal hyperpolarizing effect independent of the cell’s ionic conditions.||In cultured rat neurons studied by Govorunova and colleagues, GtACR2 photocurrent reversed near −88 mV. Illumination suppressed current-evoked spikes, including trains up to at least 25 Hz. In the tested ramp protocol, full suppression occurred at a light intensity of 0.005 mW/mm².||Dark-state electrical properties and morphology were retained in expressing neurons. The experiment validates effective silencing under the measured recording conditions. It does not establish the same chloride gradient in every cell compartment or species, and therefore cannot replace direct validation of inhibition in a new behavioral preparation.''','The externally injected current attempts to make the neuron fire while the optical intervention changes its membrane conductance. Suppression during that challenge is stronger evidence of functional inhibition than fluorescence expression alone. The accompanying neuronal morphology comes from the foundational ChR2 study and is not an image of a GtACR2-expressing cell.',h=3.1)

add('Red-shifted activation reaches neurons in intact flies','inagaki14 grover20',['inag1','gro1c'],'''The adult fly’s **cuticle**, its external body covering, limits light reaching internal neurons. Inagaki and colleagues measured light transmission and compared several **opsins**, retinal-binding light-sensitive proteins, in peripheral and central neuronal populations of intact _Drosophila melanogaster_.||The red-activatable channelrhodopsin **ReaChR** supported stimulation with 627-nm light. In gustatory receptor neurons, cells that detect chemical taste cues, 100-ms pulses at 1 Hz produced temporally controlled spiking and proboscis extension, the outward movement of the feeding appendage.||ReaChR also drove central-neuron behavioral responses under conditions where several blue-sensitive variants were ineffective. Cuticle penetration, protein expression and membrane trafficking all contributed to efficacy. Red illumination reduced a visual-stimulation concern, but wavelength choice did not remove the need for light-only controls or physiological validation.''','Trafficking is the movement of an expressed protein to the cellular location where it can act, including the membrane of neuronal processes. A wavelength that activates an isolated neuron well may work poorly through intact tissue. The adult-fly photograph is from the separate Flyception2 imaging preparation, not the ReaChR activation assay.',tall=True)

add('Matched light controls separate activation from sensation','inagaki14',['inag2'],'''Light can affect behavior through the animal’s normal sensory pathways as well as through an introduced opsin. Inagaki and colleagues compared intact flies expressing different opsins with no-opsin controls under the same illumination and behavioral scoring conditions.||ReaChR activation recruited distinct responses depending on the targeted population, including wing extension and side walking. No-opsin controls did not produce these characteristic responses. With 5-ms red-light pulses targeting courtship-related P1 brain neurons, response probability increased with pulse frequency, reaching its fitted midpoint near 38.3 Hz.||A **dose-response relationship** links stimulation strength to response probability, but cannot alone identify a natural neuronal firing rate. At high activation intensities some populations produced paralysis rather than the lower-intensity behavior. Control genotypes and stimulation intensity therefore constrain which neuronal contribution can be inferred from an induced action.''','A control animal sees the light and experiences the chamber without carrying the functional actuator in the tested cells. That comparison tests ordinary sensory responses to illumination. Increasing activation can recruit a different motor outcome, so the existence of a dose-dependent effect is not proof that every dose reproduces natural circuit operation.')

add('Social history changes the effect of P1 activation','inagaki14',['inag4','inag3b'],'''**P1 neurons** are a male-specific group of brain interneurons implicated in courtship control. An interneuron connects neural processing stages rather than directly serving as a muscle’s motor output. Inagaki and colleagues compared ReaChR-driven wing extension after 7 days of single or group housing.||Single-housed males responded at lower red-light intensities than group-housed males. By contrast, activating the descending courtship neurons pIP10 did not reveal the same housing-dependent sensitivity shift. The comparison used matched stimulation methods while changing the animal’s social experience.||Experience therefore modifies the behavioral consequence of activation at P1 or a functionally downstream stage preceding the pIP10-dependent output. The result does not establish a specific transmitter, receptor or intracellular plasticity mechanism. The published circuit arrangement marks proposed functional relationships rather than a complete synaptically verified connection map.''','Wing extension is the measured courtship-associated movement, rather than a claim about a subjective motivational state. The different housing effects at two activation sites constrain where the experience-dependent change could act. They do not prove that all neurons downstream of P1 changed or that pIP10 is the only pathway used by natural courtship.',h=3.0)

add('Intersectional targeting restricts descending-cell drive','cande18 inagaki14',['cande1','inag3b'],'''The **split-GAL4 system** restricts expression by combining two separately expressed parts of a **transcriptional activator**, a protein that turns on gene expression. Only cells where these expression patterns overlap strongly activate the linked actuator gene. Cande and colleagues used this intersectional strategy to target sparse descending-neuron populations.||The actuator CsChrimson converted 617-nm illumination into a timed depolarizing intervention. Experimental and control flies shared the genetic construct, but only experimental flies received supplemental retinal. Repeated 15-s activation epochs tested the behavioral consequences of the genetically targeted population.||A sparse expression pattern increases anatomical specificity, but does not prove that a behavioral phenotype belongs to one cell if several cells express the actuator. Restricted access and physiological efficacy are separate requirements. The published courtship pathway supplies an identified descending example; it is not a replacement for verifying each screened line’s expression pattern.''','A transcriptional activator controls expression of the linked construct rather than directly producing a spike. The genetic intersection determines where the light-sensitive channel is present, while the light pulse determines when it is activated. Controls with the same genotype retain possible expression-related effects while altering whether the channel has its supplied light-absorbing cofactor.',h=3.2)

add('Posture dynamics resolve a broad behavioral repertoire','cande18',['cande1bc'],'''A behavioral response can change without a large change in walking speed. Cande and colleagues recorded freely moving flies at 100 frames/s, aligned their body images and represented time-varying postures in a low-dimensional **behavior space**, a map grouping similar movement patterns.||Different regions contained anterior grooming, wing and abdomen movements, slow postures and locomotion. Occupancy measured how often a fly performed the movements assigned to a region. Comparing occupancy during red-light activation with matched controls distinguished action-specific effects from a general activity increase.||The map is an empirical description of movements sampled in this arena, not a map of neural anatomy. Its temporal sampling cannot resolve arbitrarily fast actions, and the flat chamber limits the available behavioral repertoire. A quantitative classifier therefore supports reproducible measurement while retaining the constraints of the preparation.''','Posture alignment removes differences in overall position and orientation before movements are compared. Similar body dynamics can then be grouped even when the fly occupies different parts of the chamber. The resulting action categories describe what the video captured, rather than an exhaustive catalogue of everything a fly can do.')

add('Descending activation often favors one motor module','cande18 inagaki14',['cande3','inag3b'],'''A **motor module** is a coordinated component of behavior that can be recruited without necessarily producing an entire behavioral sequence. Cande and colleagues asked whether descending-neuron activation concentrated movement into particular regions of their empirically measured behavior space.||During 15-s red-light epochs, many experimental flies showed reduced **behavioral entropy**, a measure of how broadly their activity was distributed across available actions. Matched no-retinal controls did not display the same population-level reduction. Most effective lines predominantly favored one behavioral region.||The results support modular control under these arena and stimulation conditions. They do not establish that each descending neuron has only one function, or that every targeted population is a dedicated command for one natural action. The alternative command interpretation requires more selective testing of normal activity, necessity and context.''','A lower entropy means that behavior becomes concentrated into fewer sampled patterns rather than that the animal necessarily moves less. One fly can walk vigorously while spending nearly all its time in a narrow locomotor pattern. Modular recruitment is therefore evaluated from the distribution of movement, not from speed alone.',h=3.3)

add('The preceding action constrains the activated response','cande18 inagaki14',['cande5','inag3b'],'''Optical activation acts on a circuit that is already participating in behavior. Cande and colleagues related a fly’s movement in the 1.5 s before stimulation to its movement during the first 1.5 s of red-light activation.||For some descending-neuron lines, the action after activation depended strongly on the action before it. **Mutual information** quantified how much knowing the earlier behavioral state predicted the later state. The relationship exceeded the corresponding dependence in matched no-retinal controls for many lines.||The effect supports state-dependent recruitment rather than an invariant mapping from cell activation to action. The measurement identifies a behavioral dependency, not the synaptic mechanism that implements it. Sensory input, the activity of other neurons and the state of local motor networks remain possible contributors to the same context effect.''','The stimulation is identical across trials, but the network is not necessarily in the same condition when it begins. A dependency on the preceding action can occur within a single individual. It therefore need not be attributed solely to genetic differences between flies or to a change in the channel itself.',h=3.4)

add('Ciliary arrests coordinate an entire larval body','veraszto17',['ver1'],'''The marine annelid _Platynereis dumerilii_ swims using **cilia**, microscopic moving projections on specialized cells. At approximately 72 h after fertilization, locomotor cilia form a main band called the **prototroch** and additional bands distributed along the larval trunk.||Verasztó and colleagues combined scanning electron microscopy, high-speed observation and calcium imaging. The different locomotor bands repeatedly stopped beating together and resumed together. Arrests coincided with coordinated increases in calcium-indicator fluorescence across the ciliated fields.||A **calcium indicator** changes fluorescence as intracellular calcium changes, providing an indirect measure of cellular activation. Synchrony connects a distributed effector system to a common functional event. It does not alone identify the neurons causing that event, and the imaging preparation must be distinguished from the freely swimming animal’s complete behavior.''','A kymograph condenses movement along a selected spatial line over time. In this preparation it relates ciliary motion to calcium changes in the same ciliary bands. The anatomical measurements identify where the beating cells lie, while the synchronized recordings establish that their arrests are coordinated across the body.')

add('Serial reconstruction locates ciliomotor connections','veraszto17',['ver2'],'''A **connectome** records identified neural connections within a reconstructed nervous system. Verasztó and colleagues traced neurons and their synaptic contacts through serial transmission electron microscopy of a 3-day-old _Platynereis_ larva, relating them to the whole-body distribution of ciliated cells.||The large MC neuron and paired Loop neurons formed extensive contacts with locomotor ciliary bands. **Cholinergic neurons** use acetylcholine as a transmitter; their identity was supported by molecular labeling and cell morphology. **Axons**, neuronal processes that carry signals toward targets, reached several positions along the body.||The reconstruction constrains how a small set of neurons can coordinate widely separated effectors. A structural synapse does not specify the timing or sign of every functional response. Calcium recordings and selective interventions were therefore needed to determine whether these reconstructed neurons actually participated in ciliary arrests.''','Serial electron microscopy follows the same cellular processes through successive ultrathin sections. A contact can be assigned to an identified presynaptic neuron and a postsynaptic target. The wiring supplies a physical route for coordination, but it does not measure what that route is doing during a particular swimming episode.')

add('Identified ciliomotor cells occupy different phases','veraszto17',['ver6'],'''Verasztó and colleagues imaged identified ciliomotor neurons and the prototroch using GCaMP6s, a genetically encoded calcium-sensitive fluorescent protein. In 2-day-old larvae, cell position and reconstructed morphology linked the recorded cells to the anatomical circuit.||Two catecholaminergic ciliomotor cells, labeled cMNvl and cMNd, increased fluorescence in phase with the ciliary band. The cMNATO cell instead tended to vary oppositely. **Catecholaminergic** identifies a transmitter-related molecular class; it does not by itself specify the functional sign of a recorded cell.||These phase relationships separate neuron populations with different timing in the coordinated rhythm. Calcium fluorescence integrates cellular activity over time and is not a direct millisecond spike recording. Opposite phases therefore support differentiated circuit participation without proving that one cell directly inhibits another or establishing the causal contribution of each transmitter.''','The fluorescence and anatomical identification are combined to avoid assigning a signal to an unknown neighboring cell. A cell that is active at the opposite phase may participate in a competing circuit state, but that possibility remains different from a demonstrated inhibitory synapse. Timing and synaptic action require separate evidence.')

add('Ablation separates rhythm generation from its output','veraszto17',['ver7'],'''**Ablation** removes or destroys a selected cell to test its contribution. Verasztó and colleagues used a pulsed laser to ablate the identified MC neuron, then compared prototroch calcium activity and ciliary arrests before and after the intervention.||MC ablation removed the prominent rhythmic prototroch activity and greatly reduced arrests. The MC calcium cycle had a median period near 71 s in intact imaged preparations. Blocking **nicotinic acetylcholine receptors**, transmitter-activated ion channels, with α-bungarotoxin uncoupled the ciliary response while the MC neuron continued to cycle.||The complementary interventions distinguish the source of rhythmic neuronal activity from cholinergic transmission to the effector. They support MC participation and receptor-dependent output. They do not establish that MC is the sole contributor to every arrest, because residual activity remained and the reconstructed network contained additional cholinergic neurons.''','Removing a neuron changes the circuit itself, whereas blocking a receptor can leave the upstream neuronal rhythm intact. A preserved MC signal with a lost ciliary response localizes a required transmission step downstream of that rhythm. Residual low-rate activity after ablation also limits a claim that no other cell can activate the prototroch.')

add('Water disturbance recruits coordinated larval defense','bezares18',['bez1'],'''A **hydrodynamic stimulus** is a local movement of water that can deform sensory structures. Bezares-Calderón and colleagues tested _Platynereis_ larvae with a vibrating tungsten filament, observing ciliary arrest, body contraction and elevation of paired appendages called **parapodia**.||High-speed recordings at 230–350 frames/s resolved the response. Increasing filament speed favored wider appendage elevation, and placing the filament farther from the head required stronger stimulation. Wide elevation was consistently recruited above approximately 28 µm/ms under the tested arrangement.||The controlled stimulus links local water movement to a coordinated defensive action. Filament speed is the imposed mechanical parameter, not a direct measurement of the water velocity at each receptor. The dependence on distance supports near-field sensing, but behavior alone cannot identify the sensory channel or the neurons transmitting the response.''','The filament is placed near the larva without delivering a direct touch to its body. Fluorescent beads helped characterize the surrounding flow. Ciliary arrest reduces ongoing swimming while elevated appendages change body configuration, so the defensive response combines multiple effectors rather than one isolated reflex.')

add('Collar receptors respond to local water movement','bezares18',['bez2'],'''**Collar-receptor neurons** carry a sensory cilium surrounded by microvilli, small cellular projections that form a collar. Bezares-Calderón and colleagues combined electron microscopy with calcium imaging to identify these sensory cells in the head of _Platynereis_ larvae.||A collar included ten thick microvilli linked to the projecting cilium by fine fibers. A vibrating filament placed about 50 µm anterior to the head increased calcium-indicator fluorescence in identified head collar receptors. A nearby morphologically different sensory neuron supplied a comparison in the same recording.||The anatomical arrangement and stimulus-evoked activity support a mechanosensory input through these cells. They do not directly measure force opening a specific channel. Calcium imaging identifies an activated sensory population, while molecular expression and genetic disruption are needed to test which proteins are required for the behavioral response.''','The projecting cilium and its collar cross the body covering and can interact with surrounding water. Recording neighboring identified cells at the same time helps distinguish a selective response from a global imaging fluctuation. Ultrastructure specifies a candidate mechanical arrangement but does not itself measure channel gating.')

add('Polycystin mutations disrupt startle and protection','bezares18',['bez4','bez3'],'''**Polycystins** are a protein family containing candidate components of mechanosensory signaling. Bezares-Calderón and colleagues detected PKD1-1 and PKD2-1 expression in larval collar-receptor neurons, then generated inherited loss-of-function mutations using targeted genome editing.||Larvae homozygous for either mutation failed to produce normal coordinated startle responses to the vibrating filament. Sensory-cell morphology was retained, arguing against a simple loss of the entire receptor cell. In predator tests, PKD2-1 mutants were captured more readily by predatory copepods, small planktonic crustaceans.||The genetic result establishes a requirement for these proteins in this sensory-to-behavior pathway. It does not establish directly that force gates a PKD1-1/PKD2-1 complex. Impaired detection, altered signal transmission or another channel-related contribution remain possible molecular explanations without direct recordings of mechanically activated current.''','Homozygous mutant larvae carry the disrupted form on both inherited copies of the gene. Expression identifies the candidate sensory location, while the mutation tests whether the protein is required. The predator assay connects the laboratory startle deficit to a consequence during an encounter with a real predator.',h=2.0)

add('Hunting begins with coordinated eye and tail movements','antinucci19',['ant1'],'''Larval zebrafish hunt small moving prey using a coordinated sequence of eye and body movements. **Eye convergence** rotates the eyes toward a common frontal region. A **saccade** is a rapid eye movement; convergent saccades provide a measurable marker of hunting initiation.||Antinucci and colleagues studied larvae 6–7 days after fertilization. During a partially restrained visual assay, small dark moving spots preferentially recruited convergence together with lateral tail movement. Approximately 92% of convergent saccades coincided with tail motion, with an average eye-to-tail delay near 12 ms.||Two-photon calcium imaging measured brain activity while the eyes and tail remained mobile. The preparation links controlled visual input to hunting-related movements, but does not retain the full sensory and mechanical conditions of prey capture. Free-swimming activation and ablation experiments supplied complementary behavioral tests.''','Two-photon imaging uses focused excitation to measure fluorescence in a selected tissue volume. The larva can move its eyes and tail even though part of its body is restrained. Eye convergence distinguishes a hunting-related motor transition from a generic tail movement, so it supports more specific activity–behavior comparisons.')

add('Pretectal populations separate prey input from action','antinucci19',['ant2ab'],'''The **pretectum** is a visual brain region near retinal input sites and the optic tectum. **Retinal ganglion cells** carry output from the eye into the brain; their axons terminate in regions called **arborization fields**. Antinucci and colleagues mapped activity around the AF7 input region.||Calcium responses were compared between prey-like stimulus presentations that did and did not evoke hunting-related convergence. Prey-responsive cells followed visual input, whereas other clusters were more strongly associated with hunting initiation. Their anatomical distributions overlapped near AF7 but differed across the surrounding brain.||The dissociation distinguishes a response to the sensory event from a response associated with the animal’s action. It does not establish causation from calcium activity alone. A neuron active near movement onset could contribute to initiation, receive a related command or respond to the resulting movement; targeted interventions distinguish these possibilities.''','The same visual stimulus can occur on a response trial and a non-response trial. Comparing those trials prevents every stimulus-related signal from being labeled a hunting command. The anatomical mapping also prevents functionally different cells close to the same retinal input site from being treated as one uniform population.')

add('Activating one pretectal cell can recruit hunting','antinucci19',['ant5','ant3'],'''Antinucci and colleagues expressed **CoChR**, a light-gated cation channel, in individual genetically accessible pretectal neurons. Cell morphology identified the targeted neuron, and high-speed video quantified free-swimming responses during repeated 7-s blue-light stimulation periods.||Illumination at 470 nm and 0.44 mW/mm² caused some single-cell preparations to produce eye convergence followed by lateralized swim bouts and sustained hunting-like routines without prey. Responsive preparations had a median response probability near 18% during illumination, compared with zero in the corresponding light-off trials.||Opsin-negative controls did not display hunting in response to the blue light alone. Single-cell activation therefore supports sufficiency for recruitment of a coordinated motor program. The incomplete response probability and absence of prey limit any claim that the intervention reproduces every aspect of a naturally initiated hunt.''','The behavioral sequence is classified from coordinated eye and tail kinematics rather than from one movement alone. The stimulated cell remains embedded in an intact downstream circuit, so sufficiency of its activation does not mean that one neuron executes the entire program without other neurons. The morphology identifies where the stimulated cell projects.',tall=True)

add('Pretectal ablation impairs hunting selectively','antinucci19',['ant6'],'''**Necessity** concerns whether normal performance requires the tested component. Antinucci and colleagues ablated fluorescently identified pretectal cells at 6 days after fertilization, then assessed free-swimming behavior before the intervention and on the following day.||Approximately 90% of the labeled population was removed. Prey consumption, hunting initiation and hunting-sequence duration declined. Average swimming speed, escape responses to looming stimuli and the **optomotor response**, swimming driven by moving visual patterns, were retained. Sham ablations removed nearby thalamic cells instead.||The preserved comparison behaviors argue against a general loss of movement or visual responsiveness. The result supports a contribution to normal hunting initiation and maintenance. It does not establish that every labeled cell has the same function, or that the residual population cannot support some remaining hunting under other conditions.''','A sham intervention controls for a procedure while changing which tissue is damaged. Here nearby-cell ablations and handling-only comparisons helped constrain a general injury explanation. Reimaging verified cell loss, and intact retinal axons argued against destruction of the visual input itself.')

add('Tectal activation can recruit hunting without retinal input','antinucci19',['ant7'],'''The **optic tectum** is a midbrain region participating in visual and motor processing. Antinucci and colleagues stimulated a ChR2-expressing anterior-ventral tectal region, while comparing sighted larvae with mutants lacking retinal ganglion cells because of disrupted **atoh7** function.||Blind larvae retained tectal ChR2 expression despite losing retinal input. Optical stimulation recruited hunting-like behavior more readily in these mutants than in their sighted siblings. Evoked routines retained eye convergence and lateralized tail movements, although response probability and duration differed.||Removing retinal input tests whether ordinary light-driven vision is required for the optically induced action. The result supports recruitment through central circuitry and indicates that retinal activation can interfere with the assay. It does not establish that vision is unnecessary for natural prey hunting or that the stimulated tectal population alone specifies the complete normal decision process.''','Light in a sighted ChR2-expressing animal can both activate the actuator and stimulate normal photoreceptors. A blind sibling separates these two influences more directly than changing light intensity alone. Preserved central expression is required for interpreting that comparison; otherwise a change in actuator expression could explain the behavioral difference.')

add('Tracking optics retain contact between untethered flies','grover20',['gro1'],'''Grover and colleagues developed **Flyception2**, an optical tracking system for recording brain fluorescence in freely moving adult flies. Untethered means that the animal is not mechanically connected to the microscope by a cable; external optics still follow its head.||Three retroreflective glass beads, each about 30 µm in diameter, marked a window over the brain. A tracking loop updated mirror position at 1,000 Hz. **Retroreflection** returns incoming light toward its source, allowing the head to remain identifiable when two flies’ body outlines overlap.||Focus adjustment followed changes in head height during courtship and copulation. The method preserved social contact that had disrupted outline-based tracking. It still required a surgically prepared imaging window and a bounded imaging arena, so freely moving behavior should not be equated with an untouched animal behaving in the wild.''','The tracking signal reports head position, not neural activity. The microscope uses that signal to keep the fluorescence measurement aligned to the moving preparation. The head window changes experimental access, while the absence of a tether permits contact and mounting movements that are difficult to measure in a fixed preparation.')

add('Two-color imaging constrains movement artifacts','grover20',['gro2'],'''A fluorescence change in a moving animal may arise from activity, altered focus or changing tissue orientation. Flyception2 measured calcium-dependent green GCaMP fluorescence and calcium-independent red **tdTomato** fluorescence in the same targeted cells.||The two channels were recorded simultaneously at 50 Hz using excitation at 473 and 561 nm. Their ratio reduced fluctuations shared by both channels. Frames were also filtered for visible tracking beads, sharpness and excessive motion; about 75% of frames in 100-s recordings passed those quality criteria.||These controls improve the attribution of fluorescence changes to cellular calcium. They do not turn fluorescence into a direct spike recording or recover information from excluded frames. Interpretation remains conditional on the analyzed behavioral periods, because rapid movements or occlusion can remove precisely timed parts of an interaction.''','The calcium-independent signal measures changes that can affect both optical channels, such as tissue movement through the field of view. A ratio cannot correct every artifact if the channels respond differently or the tissue leaves focus. Recording exclusions therefore remain part of the biological interpretation, not simply a technical cleanup step.')

add('Courtship-related activity changes during copulation','grover20',['gro2','gro3'],'''Grover and colleagues imaged identified P1 neurons while a male approached, contacted and copulated with a female. Neural fluorescence was synchronized with the distance and angle between the flies, providing a measured relation between activity and the ongoing social interaction.||P1 activity increased during courtship but fell during copulation despite continuing physical contact. After mating, P1 activity could return when the male again approached the female. In a separate targeted population, **mAL neurons**, cells using γ-aminobutyric acid (GABA), a transmitter that can reduce target-cell excitation, remained active across courtship and copulation.||The contrasting activity patterns support behavioral-state-dependent circuit recruitment. They do not establish the causal receptor mechanism of the P1 decrease or prove that mAL activity alone causes it. These recordings complement, rather than replace, experiments directly activating or removing particular neurons.''','The same neuron population can respond differently to contact depending on the behavioral state of the animal. Comparing identified populations prevents all activity during mating from being assigned a common sign or function. GABAergic identity supplies a candidate inhibitory role, but the observed calcium association does not specify which receptor on P1 mediates a particular state change.',h=2.1)

add('Wireless telemetry removes the external recording tether','szuts11',['sz1'],'''**Neural telemetry** transmits recorded electrical signals remotely. Szuts and colleagues built a rat-borne system combining implanted electrodes, a head-mounted amplifier and a radio transmitter carried in a back harness. A short connection remained between the animal’s own boards, but no cable linked the rat to the recording computer.||The electronics could process up to 64 channels sampled at 20 kHz each and send the combined signal to a receiver. Continuous operation lasted approximately 6 h with the larger battery configuration. The arrangement enabled recordings during outdoor movement and travel through tunnels.||Wireless access expands the available movements and environments, but does not remove implant surgery or carried mass. The study validated recordings in rats with this particular payload. Its engineering success cannot be assumed for a small insect or for another animal whose movement is differently constrained by the device.''','An electrode channel measures voltage relative to a reference, not the membrane potential of an isolated identified cell. Amplification makes small signals large enough for transmission and analysis. The headstage and harness are attached to the animal, so removing the external tether changes the mechanics of the experiment without making the apparatus weightless.')

add('Sampling and bandwidth define the observable signal','szuts11',['sz2'],'''**Sampling rate** specifies how often a signal is measured, whereas **bandwidth** specifies the range of frequencies retained by the system. Szuts and colleagues filtered electrode voltages from 80 to 2,300 Hz and sampled each channel at 20 kHz in their recording configuration.||A simultaneous sample-and-hold stage captured the channel voltages before **time-division multiplexing**, placing successive channels onto a shared output. Synchronization markers identified each channel scan so that the original signals could be reconstructed after radio transmission.||High sampling rate does not restore frequency components removed by the filter. The configuration was suitable for extracellular spike analysis, but did not preserve the complete low-frequency signal as measured by other systems. Hardware settings therefore determine which neural events a behavioral experiment can meaningfully relate to movement, sensation or task timing.''','A sample-and-hold circuit captures a value at a specified instant and retains it while that channel is read out. Shared timing reduces ambiguity about whether a difference between channels arose from the circuit or from different acquisition times. The original paper’s circuit panel documents the implemented device, rather than a newly drawn teaching model.')

add('Transmission quality is tested against a wired signal','szuts11',['sz4'],'''Wireless recordings require validation of signal fidelity as well as transmission range. Szuts and colleagues compared the same extracellular waveform before and after radio transmission, then tested whether the reconstructed recordings retained distinguishable spike shapes.||The system introduced less than 4 µV of electrode-referred noise. In line-of-sight tests, recordings at distances up to 60 m retained spike waveforms and separable waveform clusters. Antenna orientation and a known test signal were used to characterize distance-dependent signal quality.||A **sorted unit** is a putative neuron identified from a cluster of similar extracellular waveforms. Retained clustering supports the reliability of this recording chain, but does not establish a neuron’s transmitter or causal behavioral role. Differences in firing rate between separate distance recordings also cannot be assigned to transmission when behavioral state was uncontrolled.''','Electrode-referred noise expresses added uncertainty as an equivalent voltage at the electrode input. Comparing a signal with itself before and after transmission isolates the engineering change more directly than comparing two unrelated behavioral recordings. A stable waveform cluster supports unit separation while leaving its anatomical and molecular identity unresolved.')

add('Wireless recordings retain three-dimensional flight','zhang24',['sny1'],'''Snyder and colleagues recorded the **hippocampus**, a brain region involved in spatial representation, while Egyptian fruit bats flew between reward locations. A lightweight implanted microdrive positioned electrodes in dorsal CA1, a hippocampal subdivision identified by post-recording histology.||Bats spontaneously followed reproducible three-dimensional paths to human experimenters offering fruit. The humans exchanged reward locations every 5 min while their hands remained on fixed platforms. Wireless recording retained flight between sites without an external recording tether.||Repeated paths allowed neural activity to be compared during similar movement toward different experimenters. This controls one source of behavioral variability while preserving self-initiated flight. The reward task still occurred in a prepared laboratory room and included human participants; it should not be described as neural recording during unrestricted wild navigation.''','A microdrive adjusts electrode depth in small steps rather than moving the entire animal or recording apparatus. Histology checks whether the sampled tissue matches the intended brain region. Consistent flight trajectories make it possible to ask whether a change in firing reflects more than a change in the bat’s path.')

add('Neural and positional clocks require synchronization','zhang24',['sny1'],'''Relating a recorded spike to an external event requires a shared time reference. Snyder and colleagues tracked both bats and human experimenters with a **real-time location system**, which estimates the positions of attached tags using fixed room anchors.||Positions were sampled at 100 Hz and synchronized to the neural recordings with an external timing signal. Repeated trajectories were aligned to landing or take-off, allowing comparisons of neuronal discharge at corresponding stages of flights toward different reward providers.||A landing-aligned firing change can be distinguished from firing associated with a different location or route only when spatial and temporal measurements are sufficiently precise. Synchronization establishes the correspondence between measurements; it does not establish that an observed spike caused landing or that a landing event caused the spike through one identified synaptic pathway.''','Time stamps from two independently running instruments can drift even if both report measurements in seconds. A shared synchronization event relates their clocks. The experiment also recorded the humans’ positions, because an external participant can move while the bat’s own trajectory remains similar.')

add('Experimenter identity modulates hippocampal firing','zhang24',['sny1'],'''Snyder and colleagues compared hippocampal firing during flights along closely matched paths toward two different human experimenters. Location exchange separated the identity of the reward provider from one fixed reward site, while stable flight trajectories constrained self-motion differences.||Nearly half of the analyzable neurons, approximately 48%, differed in their discharge according to the experimenter at the landing site. Some cells combined spatial selectivity with experimenter-related modulation. The effect often occurred at one particular take-off or landing location rather than uniformly across every site.||The result supports a neural representation combining the animal’s position with features associated with an external individual. It does not identify the sensory cue carrying that information or prove recognition of human identity independently of every visual, olfactory and learned reward-associated feature.''','Spatial selectivity means that a neuron’s firing depends on where the animal is. Experimenter-related selectivity is an additional measured dependency, not evidence that the spatial information disappears. Exchanging locations reduces the confound between who delivers a reward and where that reward is delivered.')

add('Matched behavior constrains experimenter-related coding','zhang24',['sny2','sny1d'],'''An experimenter-related response could arise indirectly from changes in the animal’s movement, reward or another animal nearby. Snyder and colleagues restricted analyses to comparable trajectories and also excluded flights with a conspecific at take-off or landing. A **conspecific** is another individual of the same species.||Experimenter-dependent firing persisted in over 40% of the analyzable units after that exclusion. During separate trials, a resting bat remained at a stable position while humans repeated fixed paths; about 20% of analyzable units carried information about human position.||These comparisons weaken explanations based solely on the bat’s own movement or a nearby bat. They retain a measured influence of the external participant without identifying one sensory modality or receptor. The evidence remains observational neural coding with controlled behavioral comparisons, rather than a neural intervention establishing necessity for social behavior.''','A stationary animal provides a different comparison from a moving animal on a matched path. Activity changing while the bat remains still can be related to external movement rather than the bat’s own locomotion. The experiment does not selectively remove vision, hearing or olfaction, so their relative contributions remain unresolved.',tall=True)

add('Large ensembles can be recorded during aerial foraging','forli25',['for1'],'''A **neural ensemble** is a population of neurons whose combined activity can represent information. Forli and colleagues used wireless Neuropixels recordings from the dorsal hippocampus of freely flying Egyptian fruit bats engaged in self-paced, rewarded aerial foraging.||The system recorded single-unit activity together with **local field potentials**, extracellular signals reflecting nearby population currents. Flights alternated spontaneously with rest. About 71% of flight-active neurons met the study’s criterion for spatial selectivity across the sampled trajectories.||Population recording allows comparisons of activity sequences that one electrode or one cell cannot provide. The combination of freely chosen flights and repeated routes preserves variability while enabling consistent measurement. It does not remove the laboratory’s reward structure, and spatially selective discharge alone does not establish that those cells are required for choosing a route.''','Neuropixels probes provide many closely spaced recording sites, allowing simultaneous sampling from a large neuronal population. A local field potential differs from a sorted unit because it combines activity across sources rather than isolating one waveform cluster. The two measurements describe related but distinct levels of circuit activity.')

add('Rest events replay compressed flight sequences','forli25',['for2','sny1d'],'''**Replay** is the reactivation of an ordered neuronal sequence related to an earlier behavioral trajectory. Forli and colleagues compared hippocampal place-cell activity during flight with brief population events occurring while the bats rested. **Place cells** are neurons with position-dependent discharge.||Detected replay events had a median duration near 358 ms and could preserve either the forward or reverse ordering of flight-related activity. They coincided with **sharp-wave ripples**, brief coordinated field-potential events, and frequently represented paths remote from the bat’s current resting location.||Sequence comparisons and position decoding support structured reactivation rather than indiscriminate population firing. They do not prove that a specific event causes a memory or predicts the animal’s next route. The recordings measured reactivation; they did not selectively disrupt replay and test the resulting navigation deficit.''','Decoding estimates represented position from the firing of neurons with known spatial tuning. The decoded location can differ from the bat’s actual location during rest. A matching sequence establishes a relation to flight experience, while a causal memory claim would require an intervention tied to a defined behavioral consequence.',tall=True)

add('Flight-related representations track a motor rhythm','forli25',['for3','sny1d'],'''During flight, Forli and colleagues examined how hippocampal population representations changed within ongoing behavior. The recordings did not contain sustained locomotor **theta oscillations**, a rhythmic field-potential pattern classically associated with rodent spatial processing.||Accelerometers instead detected a prominent wing-beat rhythm near 8 Hz. Many place cells fired preferentially at particular wing-beat phases, and decoded position swept ahead of the animal’s current position cyclically. These **representational sweeps** occurred despite the absence of continuous theta in the measured field potential.||The observation supports coupling between a species-specific motor rhythm and population coding. It does not prove that wing beats generate the neural sweeps or that a particular channel or sensory feedback pathway mediates their timing. Correlated rhythms constrain proposed mechanisms while remaining different from experimentally established causal links.''','An accelerometer records movement-related acceleration and supplies an independent measure of wing-beat timing. Phase locking means that spike probability depends on the position within a repeated cycle. A rhythmic relationship can arise through sensory feedback, shared drive or another interaction, and the recording alone does not select among those mechanisms.',tall=True)

add('An internal implant can receive wireless optical power','montgomery15',['mon1'],'''Montgomery and colleagues built fully internal light-delivery implants for mice. A **micro-LED** is a miniature light-emitting diode; it converts electrical power into light near the targeted tissue. A receiving coil and local electronics obtained power from an external radio-frequency apparatus.||The smallest implant weighed about 20 mg and occupied about 10 mm³. An aluminum resonant cavity operating near 1.5 GHz concentrated electromagnetic energy in the mouse, powering a blue LED without an external fiber or battery attached to the animal.||Miniaturization enabled implantation beneath the skin and access to central or peripheral targets. The radio-frequency geometry was optimized for mice in the tested arena. These measurements do not establish equivalent power delivery in a larger animal, during unrestricted outdoor behavior or with an implant placed in any arbitrary tissue configuration.''','Wireless optical stimulation still uses an external power source; it removes the physical cable between that source and the animal. The receiving coil supplies the implant’s circuit, which drives the LED. The arena and receiving coil define the tested power-delivery geometry, so movement-dependent exposure remains a calibration question.')

add('Position, pulse duty and heating constrain stimulation','montgomery15',['mon2'],'''A wireless implant must provide enough light while limiting unwanted heating. Montgomery and colleagues calibrated the LED’s emitted power, pulse fidelity and position-dependent power delivery, using both controlled electrical tests and measurements in a mouse-sized saline preparation.||The device produced pulses as short as 100 µs. At a fixed cavity input, estimated light power density across the tested surface varied from approximately 9.2 to 25.8 mW/mm². Brain-adjacent measurements with 20 mW/mm² illumination remained below a 1 °C temperature rise at duty cycles up to 20%.||**Duty cycle** is the fraction of time that stimulation is on. Higher duty increased heating, with rises exceeding 1 °C near the tested 40% condition. Calibration therefore constrains dose and thermal artifacts; it does not establish identical light exposure or temperature in every tissue and behavioral position.''','A short pulse limits the duration of each exposure, but repeated pulses can still produce substantial average energy delivery. Position changes can also alter received power. Tissue temperature and delivered optical intensity must therefore be evaluated as measurements separate from the intended neuronal targeting.')

add('Wireless cortical stimulation changes turning behavior','montgomery15',['mon3'],'''Montgomery and colleagues implanted a wireless LED near the right **premotor cortex**, a cortical region participating in movement control. ChR2-expressing mice and implanted wild-type controls were tested in the same powered arena while video quantified movement.||During 20-s stimulation epochs, 5-ms pulses at 20 Hz increased circling from approximately 0.40 to 2.5 turns/min in the ChR2 group. Mean normalized locomotor speed increased by about 40%. Wild-type controls did not display the corresponding light-dependent movement changes.||The genotype comparison supports an opsin-dependent behavioral effect of wireless stimulation. It does not establish that natural premotor activity normally produces persistent circling, or that the activated population is necessary for every voluntary turn. The experiment validates untethered intervention while retaining the limits of imposed activation and broad expression.''','The device’s receiver remains beneath the skin while the light source enters the targeted brain region. Wild-type mice experience implantation and the radio-frequency arena without the introduced channel. Circling is quantified as a behavioral outcome rather than inferred solely from the fact that the LED emits light.')

add('Causal claims need matched behavioral controls','montgomery15 antinucci19',['mon5','ant6'],'''A causal neural test must connect a defined intervention to a defined behavioral effect while controlling alternative explanations. Montgomery and colleagues placed wireless LEDs near paw sensory endings expressing ChR2 in **nociceptors**, neurons that detect potentially damaging stimulation.||With 10-ms pulses at 10 Hz, mice reduced time in the powered compartment during a 30-min stimulation period; fluorescent-tag-only controls did not display the same reduction. In a complementary necessity test, Antinucci and colleagues reduced hunting after pretectal ablation while preserving swimming, visual escape and optomotor responses.||Activation supports an opsin-dependent aversive consequence under the tested conditions, while selective ablation supports a contribution to normal hunting. Neither result alone specifies every intervening synapse, transmitter or receptor. A behavioral claim is strongest when perturbation efficacy, anatomical targeting and preserved comparison behaviors are established together.''','Place avoidance is a measured change in where the mouse spends time, not a direct readout of a subjective experience. The nociceptor intervention and pretectal ablation also concern different circuits and different behaviors. Their common evidential requirement is to measure a specific consequence while retaining controls for general sensory or motor disruption.',tall=True)

for sd in S:
 if len(sd.get('figures',[])) == 2 and sd['figures'][1]['path'].endswith('inag3b.png'):
  sd.update(figure_arrangement='side-by-side', primary_figure_width=4.2)
 if sd['title'] == 'Courtship-related activity changes during copulation':
  sd.update(figure_arrangement='side-by-side', primary_figure_width=2.9)

assert len(S)==44,len(S)
for i,s in enumerate(S,2):
 assert len(s['title'])<=62,(i,s['title'])
 assert 3<=len(s['body'])<=5
 assert 90<=len(' '.join(s['body']).split())<=170,(i,len(' '.join(s['body']).split()))
K=[
('Channel mechanism:','Light-gated cation and anion channels alter conductance directly. The ionic gradient and membrane voltage determine the electrical consequence; actuator expression alone does not establish excitation or inhibition.'),
('Sufficiency and necessity:','Optical activation tests whether a targeted population can recruit an action. Ablation or verified silencing tests its contribution to normal performance. Neither intervention automatically identifies the complete natural circuit.'),
('State dependence:','The behavioral effect of neuronal activation depends on stimulation strength, preceding behavior and social history. Identical optical input need not produce an invariant action.'),
('Measurement validity:','Fluorescence requires motion and reference-channel controls. Wireless electrophysiology requires signal-fidelity and timing validation. Neither measurement is a direct causal test of behavioral function.'),
('Comparative evidence:','Annelid startle, zebrafish hunting, fly courtship and bat flight link distinct circuit arrangements to species-specific behavior. Connectomes and activity patterns constrain mechanisms without proving every functional connection.'),
('Behavioral controls:','Light-only and expression controls, anatomical verification, thermal calibration and preserved comparison behaviors limit alternative explanations. Wireless access expands behavior without removing preparation-specific constraints.')]
spec={'lecture':40,'theme':'rosewood-paper','content_slides':44,'title_height':2.7,'title_image':F['animal'],'title_refs':[R['bezares18']['reference']],'slides':S,'takeaways':{'items':[{'lead':a,'text':b}for a,b in K],'cite':'Boyden et al. (2005); Govorunova et al. (2015); Cande et al. (2018); Antinucci et al. (2019); Montgomery et al. (2015)','refs':['References:']+[R[k]['reference']for k in ['boyden05','govorunova15','inagaki14','cande18','veraszto17','bezares18','antinucci19','grover20','szuts11','zhang24','forli25','montgomery15']]}}
(B/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
print('Wrote 44 primary-figure content slides and six exam takeaways')
