"""Write Lecture 79 from verified Givon (2022) and Liu (2025) sources."""
from pathlib import Path
import json,re
D=Path(__file__).resolve().parent
refs=json.loads((D/'references.json').read_text());prov=json.loads((D/'crop_provenance.json').read_text());slides=[]
cites={'givon':'Givon et al. (2022)','liu':'Liu et al. (2025)'}
def figure(n):
 p=prov[n];return {'path':'figures/'+n+'.png','kind':'article','caption':cites[p['paper']]+', Fig. '+p['figure']+'. '+p['description'],'source_url':re.search(r'https://doi.org/\S+',refs[p['paper']])[0]}
def add(k,title,n,*body):
 assert len(body)==3
 slides.append({'title':title,'body':list(body),'transcript':[re.sub(r'\*\*|_', '',p) for p in body],'cite':cites[k],'refs':[refs[k]],'layout':'figure-right','figure_width':5.8,'figure':figure(n)})
add('givon','Swimming actions control terrestrial displacement','g1',
'Goldfish can move a wheeled vehicle through a room while remaining submerged in its water tank. A **fish-operated vehicle**, or FOV, links the animal’s swimming position and orientation to electric motors. The motors move the tank, changing the animal’s location relative to objects outside the water.',
'Givon and colleagues rewarded arrival at a pink target with food. Training therefore joined two operations: selecting a useful swimming action inside the tank and directing the resulting vehicle displacement toward an external destination. The vehicle served as the physical connection between those operations.',
'Liu and colleagues later changed this connection by rotating the direction commanded to the wheels. Vehicle control could then be examined separately from adaptation to a changed action-to-movement relationship. Goal recognition remained useful even when the previously effective steering action became inaccurate.')
# Include both primary references on the comparison slide.
slides[-1]['cite']='Givon et al. (2022); Liu et al. (2025)';slides[-1]['refs']=list(refs.values())
add('liu','The animal stays in a shallow mobile tank','l1a',
'The FOV carries goldfish in a Perspex tank measuring 35 × 35 × 28 cm. Water depth was 15 cm, selected to reduce surface waves during vehicle movement. The animal remains in an aquatic preparation while the surrounding scene changes through terrestrial displacement.',
'The tank sits on a 40 × 40 × 19 cm chassis. A downward-facing camera monitors the fish, while a separate ranging instrument records the vehicle’s relation to the arena. These instruments measure the animal and the apparatus in different physical spaces.',
'Swimming inside the tank changes the control command; motor-driven motion changes the tank’s external position. The preparation preserves ordinary movement in water while adding an unfamiliar consequence to that movement. Learning concerns the relation between a swimming posture and an externally moving platform.')
add('givon','Omni wheels translate the tank without steering it','g1',
'Four electric motors power **omni wheels**, wheels that permit movement in multiple horizontal directions. The platform can translate toward different sides of the arena rather than requiring the entire tank to turn before moving in a new direction.',
'This mechanical arrangement makes fish orientation available as a directional command. A fish near a tank wall and facing outward produces movement toward the corresponding external direction. Changing position or heading can therefore change the vehicle’s displacement without rotating the whole preparation.',
'The animal’s swimming motion and the platform’s motion are physically distinct. The fish supplies a control signal through its behavior, and the electric motors supply the force moving the apparatus. This division permits an experimenter to change the control relationship while leaving the animal’s aquatic movements available.')
add('givon','Computer vision extracts a directional command','g1b',
'**Computer vision** is the extraction of useful information from camera images. The FOV’s downward-facing camera provides images of the fish in its tank. Image segmentation separates the animal’s contour from the surrounding water and tank background.',
'The controller detects fish location and orientation, including a direction derived from the body and tail. These quantities are translated into a command for the wheels. The camera measures swimming behavior rather than recording a neural signal directly from the animal.',
'Location and orientation contribute different information. Location determines whether the fish occupies an active region near a tank boundary, while orientation supplies the intended direction under the programmed rule. Their combination prevents every visible movement of the fish from automatically producing vehicle movement.')
add('givon','Near-wall posture gates vehicle movement','g1',
'A **gated control rule** activates an output only when its required conditions are satisfied. In the FOV, being visible to the camera is insufficient: the fish must be near a tank wall and facing outward for the vehicle to move in the corresponding direction.',
'The same outward heading has a different consequence when the fish is away from the tank boundary. The position requirement creates active and inactive parts of the tank. Vehicle control therefore involves moving into a useful control region as well as selecting a heading.',
'This rule couples swimming position to the availability of steering. The fish can remain in water and move freely, but only selected positions and orientations recruit the motors. Effective operation depends on the animal repeatedly producing the behavioral combination that advances the platform toward the reward.')
add('givon','Obstacle proximity overrides the fish command','g1',
'**LIDAR**, light detection and ranging, measures distances using emitted light and its return from surrounding surfaces. The FOV uses this instrument to monitor obstacles outside the tank, independently of the camera’s measurement of fish behavior.',
'When the platform came within 20 cm of a wall or another obstacle, the controller disallowed further movement toward it. This safety rule overrode the animal-derived command. A fish could continue occupying an active steering posture while the apparatus withheld movement in the blocked direction.',
'Consequently, vehicle displacement combines the swimming command with an external constraint. Near-wall stops are properties of the controller as well as possible changes in behavior. The recorded arena position allows the blocked movement to be distinguished from an animal that has left the active control region.')
add('liu','Fish position and vehicle position are separate records','l1abc',
'The onboard camera records the fish relative to the water tank. The LIDAR records the vehicle relative to the arena. A **coordinate frame** is a reference system used to specify location; these two instruments measure movement in different coordinate frames.',
'Fish posture specifies the input available to the controller, whereas the arena trajectory specifies the output produced by the platform. A fish can swim inside a stationary tank, or maintain a useful posture while the platform moves through the room.',
'Liu’s rotation experiment changes the relation between these records. The animal’s local heading is retained as the input, but the output direction is rotated by software. Comparing local posture with external displacement therefore identifies the programmed perturbation without treating tank-relative swimming as the vehicle’s route.')
add('givon','Vehicle movement builds after a step command','g2',
'A **step command** is an abrupt change from no command to a sustained movement command. Givon and colleagues applied this input to the vehicle and recorded its position over time, measuring the response of the apparatus independently of learning.',
'The platform’s distance increased slowly at first and more rapidly after motion developed. Its speed approached approximately 0.4 m/s in the published recording. The authors described a response time of about 1 second, connecting a steering command with a delayed mechanical consequence.',
'The fish therefore operates a system whose displacement builds over time rather than appearing instantaneously. The calibration assigns this time course to the vehicle itself. During behavioral training, a sustained useful posture allows the motors to produce movement long enough to approach the external target.')
add('givon','Calibration separates motor accuracy from learning','g2',
'The researchers placed an artificial fish model at different locations and orientations to test directional control. Eight headings, separated by 45°, sampled the vehicle’s available directions. The resulting displacement could be compared with the programmed command without relying on a live animal’s choices.',
'Command and movement directions closely agreed in the calibration. Together with the speed measurement, this establishes the apparatus’s directional and temporal response before navigation performance is interpreted. The control test concerns the vehicle’s operation rather than the animal’s experience of the reward.',
'Learning changes which postures the fish produces and how it uses their consequences. Calibration measures what the platform does when those postures are supplied. Separating these operations prevents a more direct route during training from being attributed to an unmeasured improvement in the robot’s mechanical steering.')
add('givon','The target supplies an external visual destination','g1c',
'A pink rectangular board marked the rewarded destination in a 3 × 4 m arena. The board measured 60 × 40 cm and was placed on an arena wall. The goal was external to the water tank rather than an object the fish could reach by swimming across its own enclosure.',
'Arrival was defined by the vehicle touching the target board. At that moment, the experimenter delivered a food pellet into the tank. Vehicle displacement brought the aquatic preparation into contact with the rewarded location while the fish remained submerged.',
'The animal had to direct the platform toward a feature in the surrounding scene. Control of the motors provided a means of approaching that feature, while the food reward connected successful external movement to a consequence inside the tank. The goal and the reward occupied different physical spaces.')
add('liu','Covering the tank removes feedback during return','l1abc',
'A bucket covered the water tank while the experimenter returned the FOV to its starting position. Removing the cover began the next trial. The procedure restricted the fish’s access to the surrounding visual scene during the manually controlled return.',
'In Liu’s experiment, time zero was assigned when the fish first appeared in the camera frame after the cover was removed. The starting event therefore aligned the analyzed trajectory with the resumption of the visible trial rather than with the entire handling sequence.',
'Training joined fish-controlled displacement with visual access to the arena. Covered return separated that movement from the experimenter’s repositioning of the vehicle. Each new trial again required the animal’s posture to generate movement toward the visible target through the currently programmed steering relationship.')
add('givon','Learning replaces wandering with targeted routes','g3',
'At the beginning of training, vehicle trajectories included substantial wandering through the arena. In later high-performance sessions, routes repeatedly approached the rewarded target. The change concerned the external path generated by the fish’s steering behavior.',
'A route records the consequences of many local positions and headings inside the tank. The animal must repeatedly recruit an appropriate command as its relation to the target changes. A more direct route therefore reflects coordinated use of the interface over the course of a trial.',
'The published trajectories retain variation between trials and individuals. Goal-directed control was acquired through experience with the apparatus and reward. The route itself provides a behavioral record of the animal’s successful use of the camera-to-motor mapping in a terrestrial arena.')
add('givon','Changed starting points require new routes','g5',
'Givon and colleagues moved the starting position after the fish had learned to approach the target. A different start changes the required route even though the rewarded board remains in the same place. A fixed replay of the original movement sequence would then lead away from the goal.',
'The fish still approached the target from the changed starting positions. The authors compared route efficiency relative to the direct distance available from each start, rather than treating a longer absolute path from a more distant start as poorer control.',
'**Route efficiency** relates the distance actually traveled to the shortest start-to-target distance. This comparison separates the geometry of the task from excess movement. Successful approaches from different starts connect the learned steering interface to flexible target-directed movement rather than one repeated arena trajectory.')
add('givon','Decoys and relocation distinguish target cues','g5',
'Rectangular decoy boards of other colors were placed around the arena while the pink target retained its rewarded role. Fish continued to approach the correct board. Merely detecting any rectangular object was therefore insufficient to account for the trained choice.',
'When the rewarded target moved to the opposite wall, fish initially visited its old location before reaching the new one. The changed behavior connects the visual target with a learned spatial location, rather than assigning navigation exclusively to the board’s current appearance.',
'The controls separate information about what the target is from information about where it has been rewarded. Changing the starting point preserves the destination, while relocating the board changes that destination. The animal’s route reflects the interaction of visual recognition, learned location and control of the moving platform.')
add('liu','Software rotates the action-to-movement mapping','l1b',
'A **control mapping** specifies how an input action determines an output movement. During baseline training, an outward-facing fish near a tank wall moved the FOV in the corresponding direction. Liu and colleagues then rotated the vehicle command 45° to the right of the fish’s orientation.',
'The tank, arena and rewarded target remained part of the same task. The changed relation was imposed by software between the detected swimming pose and wheel output. A posture that previously advanced the vehicle toward the goal now displaced it in a different direction.',
'Compensation required the fish to produce a different orientation for the same desired external movement. The manipulation therefore separated recognizing a destination from controlling approach to it. Familiarity with the goal could persist while the motor command needed to reach that goal changed.')
add('liu','Camera sampling and control updates have different rates','l1abc',
'Liu’s onboard camera recorded fish posture at 30 frames/s with images of 320 × 240 pixels. The control loop ran at 12 updates/s. Acquisition of an image and updating the wheel command were therefore distinct operations with different rates.',
'A separate overhead camera recorded the arena from about 4 m above. Those recordings were reduced to 30 frames/s at 720 × 480 pixels for comparison with vehicle records. Camera observations of the arena helped validate tracking independently of the onboard view of the fish.',
'These measurements separate detection, command updating and observation of the resulting trajectory. Frame rate describes repeated sampling; the mechanical response time describes how movement develops after a command. The published hardware measurements characterize different stages connecting fish posture to externally observed platform displacement.')
add('liu','Feedback depends on the current steering relationship','l1b',
'**Sensorimotor feedback** is sensory information produced as a consequence of an animal’s movement. In the FOV, a useful posture activates the wheels, and platform displacement changes the animal’s relation to the surrounding target and arena.',
'Rotating the mapping changes that consequence while leaving swimming in the water tank available. Continuing to use the previously effective posture produces an externally misdirected route. Compensation develops as the animal experiences the relationship between its commands and the vehicle’s changed movement.',
'The authors’ internal-model hypothesis proposes that goldfish acquire a predictive relation between posture and external displacement. An **internal model** is a learned representation of how actions generate consequences. Oppositely directed errors after the rotation is removed provide behavioral evidence for persistence of the adapted relationship.')
add('liu','The five stages separate acquisition and readaptation','l1d',
'**Baseline** establishes vehicle operation under the original mapping. **Rotation** introduces a changed command direction. **Washout** restores the original mapping after adaptation, permitting the persistence and subsequent decay of the changed behavior to be examined.',
'The 45° experiment used 15 rotation sessions followed by 10 washout sessions. The same rotation then returned for 15 re-exposure sessions, followed by 10 final sessions with the original mapping. Each session contained six trials.',
'The authors called re-exposure the “savings” stage because it tested whether experience with the perturbation improved later learning. That stage name describes the question being tested. The observed rates and achieved performance must be compared with the first exposure to establish what kind of improvement occurred.')
add('liu','Success counts completed arrivals rather than precision','l2',
'Liu defined success as arrival in the target area, followed by food reward. With six trials in a session, the success measure ranged from no completed arrivals to six. It describes completion of the rewarded task rather than every detail of the route.',
'A fish can reach the goal by a direct path or after substantial extra movement. Both routes contribute a successful arrival. Directional accuracy and traveled distance were therefore recorded separately, allowing task completion to be compared with how the animal achieved it.',
'The rotation changed all three measures during learning. A growing number of arrivals means that more trials end at the rewarded location, while changes in angle and distance describe recovery of target-directed steering. Successful completion and efficient control are related behavioral achievements with different measurements.')
add('liu','Angular error describes start-to-end direction','l2',
'**Angular error** is the angle between the direction from the starting point to the trial endpoint and the direction from the starting point to the target. In Liu’s task, 0° corresponds to an endpoint aligned with the target direction.',
'The measure uses the endpoint of the trajectory rather than the fish’s continuously changing body orientation. It summarizes where the platform finishes relative to the intended direction. Curved routes can therefore share a similar endpoint angular error even when their intermediate movements differ.',
'Route length retains the extra movement lost in that endpoint summary. After rotation, angular error moves toward the target direction as control improves, while distance describes the remaining detours. These complementary measures distinguish recovery of external directional alignment from acquisition of a short approach path.')
add('liu','Failed trials receive an adjusted distance estimate','l2',
'For a successful trial, distance traveled is the measured length of the vehicle route. For an unsuccessful trial, Liu added an estimate of the further movement needed to reach the target, using the endpoint-to-target distance and the fish’s efficiency during that session.',
'This **adjusted distance** avoids treating an early unsuccessful stop as an efficient short route. A trial can end close to its starting point because steering failed, even though the animal still has far to travel to earn a reward.',
'The shortest start-to-target distance was 2.5 m. Adjusted lengths therefore express the measured successful routes or estimated completion cost of unsuccessful ones relative to the same destination. Reported decreases in this measure combine more effective target approach with the penalty assigned to stopping short of the goal.')
add('liu','Baseline training establishes a usable interface','l3ab',
'Goldfish began with the original relation between outward orientation and vehicle direction. Early baseline trials often ended away from the target, while late baseline trajectories generally reached it. The animal first had to acquire effective control before experiencing a changed mapping.',
'Fish advanced to rotation after maintaining good performance across consecutive sessions. The criterion combined successful arrivals, near-target endpoint direction and limited route length. These measures required more than occasional contact with the rewarded location.',
'Adaptation was consequently studied in animals that had already acquired the baseline skill. The baseline stage separated initial learning of the unusual interface from later compensation for rotation. Changes after the perturbation could then be related to an established posture-to-movement mapping rather than the first discovery of vehicle control.')
add('liu','Baseline routes become shorter with experience','l3fjk',
'Across baseline training, Liu’s fitted typical adjusted route length decreased from 6.0 m to 3.2 m. The direct start-to-target distance was 2.5 m. The change expresses a reduction in extra movement while the fish learned to operate the platform.',
'Long routes include detours and, for failed trials, an estimate of the remaining movement needed to complete the task. Shorter adjusted distances therefore indicate more efficient use of the interface rather than simply a shorter period of recording.',
'Late baseline provided a trained comparison for rotation and washout. Recovery toward a similar distance after a changed mapping means that the fish again approaches the same target with limited extra movement. Efficiency is evaluated against the animal’s acquired vehicle skill rather than an assumed ability to steer perfectly from its first trial.')
add('liu','Arrival and endpoint consistency improve together','l3cde',
'Baseline training increased the fitted typical success count from 1.9 to 3.2 arrivals per session. Fish also produced more consistent endpoint directions and shorter adjusted routes. The acquisition of vehicle control therefore changed completion, directional variability and movement efficiency together.',
'Success counts describe whether the target was reached, whereas endpoint direction describes the alignment of the trial’s final displacement. The paper reports greater directional consistency during baseline rather than a large correction of the average angle.',
'This distinction separates variability from directional bias. Routes can become more consistently aligned with the goal even when their average signed direction changes little. The established baseline supplies both reliable target approach and a reference against which the later rotation-induced bias can be measured.')
add('liu','Early rotation disrupts a previously effective route','l4a',
'The first rotated trials altered the route of a fish that had already learned to approach the target. A previously useful tank-relative heading now drove the platform to the right of its former direction. Early paths included detours and endpoints away from the goal.',
'With exposure to the changed mapping, late rotation trajectories again approached the target. The same external destination was reached through a changed relationship between detected swimming posture and vehicle movement, rather than by restoring the software to baseline.',
'The example fish’s early and late routes connect the imposed perturbation with a recovered behavior. The physical preparation remained available throughout the change. Adaptation concerned selecting useful commands under the rotated relationship, so target-directed performance returned while the altered controller was still active.')
add('liu','Directional recovery occurs within the rotated mapping','l4c',
'In the published example fish, fitted endpoint angular error improved from 9.4° to −0.5° during rotation. The rotation remained active during this improvement. The animal therefore recovered an approximately target-aligned final displacement under the changed controller.',
'The external command rotation was 45°, but the measured endpoint error was smaller than that imposed angle. Endpoint direction summarizes the completed trajectory, including the animal’s intervening corrections. It is a behavioral outcome rather than a direct readout of the software parameter.',
'The distinction connects input perturbation with output performance. A known change is imposed between posture and wheels, and the resulting route changes through the fish’s behavior. Approaching 0° means recovery of endpoint alignment even while the platform still requires a posture different from the baseline steering action.')
add('liu','Adaptation reduces excess movement in an example fish','l4d',
'The example fish’s fitted adjusted distance decreased from 6.4 m to 3.7 m during the rotation stage. This improvement occurred as the animal learned to compensate for the changed steering relation. Less extra movement was needed to approach the same rewarded destination.',
'Adjusted distance combines actual trajectory length with estimated completion distance on failed trials. Its reduction therefore captures both shorter successful routes and movement that ends closer to effective completion. Directional error alone would not preserve that information about detours.',
'The vehicle’s mechanical response remains part of the task while behavior changes. The fish uses repeated posture commands to guide a moving platform rather than performing one instantaneous turn. Recovery of route efficiency describes the coordinated consequence of those commands across an entire target-directed trial.')
add('liu','More trials reach the target during 45° adaptation','l5a',
'Across the 45° condition, the fitted typical number of successful arrivals increased from 1.9 to 3.4 per session during adaptation. Each session offered six trials. The changed command relationship initially disrupted task completion, followed by recovery with repeated exposure.',
'The reward location stayed fixed while the required steering action changed. A growing success count therefore reflects acquisition of useful control under the perturbation. The animal could continue recognizing the target even when its original action no longer advanced the platform directly toward it.',
'Late performance approached the trained baseline level. Recovery was expressed through the animal’s behavior while the rotated mapping remained active, rather than through removal of the challenge. Successful arrivals connect compensation for the changed movement consequences with continued access to the food reward.')
add('liu','The 45° condition loses its directional bias','l5b',
'Liu reported a fitted typical endpoint angular error of 11.4° early in the 45° rotation stage and 0.1° later in that stage. The decrease represents recovery of target-aligned displacement during continued exposure to the perturbation.',
'The fish’s body orientation determines the wheel command, but angular error is measured from the arena trajectory’s start and endpoint. A correction in this measure means that the vehicle finishes in a more useful direction, not that the software rotation has become smaller.',
'Adaptation changes the command the animal supplies to an unchanged rotated controller. The target continues to define the desired external direction. Experience therefore restores the relationship between the chosen posture and successful approach by changing behavior within the altered action-to-movement mapping.')
add('liu','Late rotated routes approach trained efficiency','l5c',
'The fitted late adjusted distance in the 45° rotation condition was approximately 3.8 m, compared with 3.2 m at late baseline. Both values refer to approach toward the same target, whose direct distance from the start was 2.5 m.',
'Rotation learning reduced the extra movement associated with the changed control relationship. Success and endpoint direction recovered alongside this reduction. The animal regained a useful route through the arena rather than merely arriving by increasingly long exploratory paths.',
'Comparable late performance can emerge under different steering mappings. Baseline and rotation require different orientations to produce the desired external direction, yet each can support efficient approach after training. The learned behavior depends on the currently experienced relationship between aquatic posture and terrestrial displacement.')
add('liu','Removing rotation exposes an opposite-direction error','l5b',
'An **aftereffect** is a persisting behavioral change expressed after a perturbation is removed. When Liu restored the baseline steering mapping, fish initially made errors in the direction opposite to the earlier rotated error. The changed behavior outlasted the controller setting that had induced it.',
'The paper reports an early negative directional bias of roughly −6° in washout. Under the restored mapping, compensation appropriate for the previous rightward rotation misdirected the vehicle in the opposite direction. Subsequent experience returned performance toward the baseline relation.',
'The authors’ internal-model hypothesis links this persistence to a learned prediction of movement consequences. Compensation is retained briefly when the software no longer requires it. Opposite-direction errors therefore distinguish acquired adaptation from a response that exists only while the external perturbation is present.')
add('liu','Washout relearns the restored command relationship','l4a',
'**Washout** is the reduction of an adapted response after the perturbation is removed. The vehicle again moved in the direction commanded by outward fish orientation, but the behavior carried over from rotation initially produced misdirected routes.',
'Late washout trajectories returned toward effective target approach. The same learning preparation now required reducing a compensation that had been useful in the preceding stage. Experience with the restored consequences brought behavior back toward the trained baseline pattern.',
'Adaptation and washout therefore involve different histories under the same physical apparatus. Baseline establishes useful control without prior rotation, while washout re-establishes it after a learned compensation. The difference between their early behavior identifies the lasting effect of the intervening rotated experience.')
add('liu','A 90° perturbation produces larger directional errors','l6b',
'A separate condition rotated vehicle commands 90° relative to the fish’s orientation. The fitted typical endpoint error began at 57.0° and decreased to 7.3° during training. Goldfish adapted even when the changed movement direction was substantially larger than in the 45° condition.',
'The imposed rotation and endpoint error remain different quantities. The first is specified by the controller; the second includes the behavioral consequences of the fish’s movements throughout the trial. Improvement describes external steering performance under the continued perturbation.',
'The larger rotation challenged the established relation more severely. Compensation nevertheless brought the final displacement closer to the target direction. This condition extends the behavioral adaptation result beyond one perturbation size while retaining the same principle of changing software between detected posture and motor output.')
add('liu','Directional adaptation can coexist with few arrivals','l6a',
'In the 90° condition, fitted target success increased from approximately zero to 1.3 arrivals per session. Endpoint direction improved considerably during the same condition. Directional recovery and task completion therefore need not return to the same level together.',
'Angular error evaluates where a trajectory ends relative to the target direction, while successful arrival requires entering the target area. A vehicle can become better aligned yet still stop short, take an inefficient path or fail to complete the approach within the trial.',
'The larger perturbation separates these behavioral achievements. Improved steering direction changes the animal’s approach, but completed access to the food reward remains relatively infrequent. Measuring success together with angle preserves the difference between compensation for a directional mismatch and reliable completion of the whole task.')
add('liu','The 90° condition retains an efficiency cost','l6c',
'Adjusted distance in the 90° condition decreased from 11.6 m to 4.6 m during adaptation. The direct start-to-target distance was 2.5 m. Training greatly reduced the excess movement while leaving a longer late route than the geometric minimum.',
'This measure includes the estimated remaining cost of unsuccessful trials, so its improvement combines shorter paths with endpoints that permit more effective completion. The decrease accompanied directional compensation under the larger rotated mapping.',
'The three outcomes describe different consequences of adaptation: the endpoint becomes better aligned, excess movement falls, and more trials reach the rewarded destination. Their incomplete recovery under 90° rotation preserves a measurable constraint on performance even though the animal learns a useful correction to the altered steering relationship.')
add('liu','Re-exposure tests the history of a learned perturbation','l7a',
'After washout, Liu reintroduced the same 45° rotation. The animals had already experienced both adaptation and restoration of the baseline mapping. Re-exposure tested how that learning history affected another encounter with the same control change.',
'Early re-exposure again produced less effective trajectories, followed by more target-directed late routes. The software manipulation was repeated rather than replaced with a new angle. The behavioral comparison could therefore distinguish first acquisition from performance after earlier experience.',
'The following final stage removed rotation once more. This second restoration tested continued operation under the baseline relationship after re-exposure. The sequence preserves the external target while changing the history of the posture-to-vehicle mapping, allowing retained performance and learning rate to be examined separately.')
add('liu','Second exposure improves the achieved performance','l7b',
'During re-exposure, fitted typical success increased from 2.4 to 3.7 arrivals per session. The animals again learned useful operation under the 45° rotation. Their starting performance was somewhat better than the corresponding estimate during the first rotation stage.',
'Improved performance at the beginning of an encounter is different from faster improvement during that encounter. Retained experience can change the starting point, the late achieved level or the rate connecting them. These quantities describe distinct consequences of prior learning.',
'The second-exposure routes became effective while the perturbation remained active. Repeated experience supported renewed access to the food reward through the altered steering relationship. Comparison with the first exposure must retain the separate behavioral meanings of initial success, late success and the speed of their change.')
add('liu','Re-exposure again corrects endpoint direction','l7c',
'Fitted endpoint angular error changed from 11.0° to −3.0° during the second rotation exposure. The vehicle’s final displacement again became closely aligned with the target direction as the animal operated under the previously encountered perturbation.',
'The initial error was smaller than a complete uncorrected 45° command mismatch. Its value summarizes the external trajectory after the fish’s intervening movement and correction. The comparison therefore concerns achieved steering performance rather than treating endpoint angle as a direct measure of the imposed rotation.',
'Repeated exposure restored target-directed behavior, but its initial correction rate was slower than on first exposure. Directional performance and the speed of adaptation are separate observations. A fish can begin an encounter in a better state and still change more slowly over the following sessions.')
add('liu','Repeated exposure reduces adjusted route length','l7d',
'The fitted typical adjusted distance decreased from 5.1 m to 3.6 m during re-exposure. The same target and start-to-target geometry were retained. The fish regained a relatively efficient external route while compensating for the repeated 45° mapping.',
'The decrease includes both actual successful route lengths and estimated completion costs for unsuccessful trials. It connects renewed steering skill with reduced excess movement across the session rather than assigning equal efficiency to every trial that earned food.',
'Late re-exposure distance was closer to late baseline than early re-exposure distance. Prior experience did not eliminate the need to adapt again, but useful performance returned under the altered controller. The achieved route and the rate of its recovery supply different information about retention of earlier learning.')
add('liu','Faster relearning is distinct from better performance','l8cd',
'**Savings** conventionally refers to faster relearning after an earlier encounter with a perturbation. Liu compared the initial learning rates of first rotation and re-exposure rather than judging savings only from the performance attained at the end of training.',
'Angular error initially improved by about 6.5° per session during first rotation and 2.4° per session during re-exposure. The second encounter therefore had a slower initial directional correction despite its somewhat improved starting and achieved performance.',
'The authors found no clear classical savings in this whole-body task. Their hypothesis is that better initial performance leaves less improvement available during the second exposure. The observations preserve improved retained performance while separating it from the faster adaptation that the savings prediction required.')
add('liu','Route improvement rate also falls on re-exposure','l8ef',
'Adjusted distance initially improved by approximately 0.9 m per session on first rotation and 0.4 m per session on re-exposure. These rates describe change in the route-length measure, including its correction for unsuccessful trials.',
'A lower starting cost can coexist with a smaller initial rate of change. Re-exposure began with somewhat better performance, while late routes again approached trained efficiency. The history of adaptation therefore affected performance without producing a larger early reduction in distance.',
'Angle and distance provide complementary evidence against faster relearning. One measures start-to-end alignment and the other measures excess movement and estimated completion cost. Their shared pattern prevents retained skill from being equated automatically with an increased rate of adapting to the repeated software perturbation.')
add('liu','Initial and late success answer different questions','l8ab',
'**Asymptotic performance** is the late level approached as learning continues. **Initial performance** describes the state at the beginning of a stage. Liu fitted both quantities separately, preserving the difference between where learning starts and where it eventually settles.',
'Success during re-exposure began somewhat higher and reached a useful late level, but its initial improvement rate was about 0.5 arrivals per session, compared with about 0.6 on first rotation. Improved achieved performance therefore accompanied no faster early rise in successful completion.',
'The separation matters when evaluating the effect of experience. A stronger starting state can reflect retained consequences of previous training, while the later change describes adaptation during the current encounter. Their combination defines the learning trajectory without reducing memory to one final success count.')
add('liu','The trial endpoint reflects an experimental boundary','l2',
'Liu’s trials ended when the vehicle reached the target, reached an arena boundary or exceeded 3 minutes. These conditions define which endpoint enters the angular-error and distance measurements. A completed recording can therefore represent successful arrival or an interrupted approach.',
'The adjusted-distance measure addresses one consequence of that boundary: stopping early does not automatically produce a favorable short distance. An estimate of the remaining route is added when the target has not been reached, based on the session’s measured efficiency.',
'Task completion, endpoint direction and adjusted length retain different information about the same bounded trial. Their combined use connects the controller’s learned operation with an external behavioral goal while accounting for movement that stops before reward. Interpretation follows the measured endpoint and the rule that ended its recording.')
add('liu','Navigation transfer and motor adaptation are separable','l1abc',
'Givon’s task transfers target-directed movement into a terrestrial setting while the fish remains in water. Liu’s task changes the steering relationship after that interface has been learned. The first asks whether an animal can use a novel vehicle; the second asks how acquired control changes under perturbation.',
'The behavioral evidence separates goal choice from effective movement: a familiar destination can remain fixed while a software rotation disrupts approach. Recovery under rotation and opposite-direction errors after removal connect experience with a lasting change in the steering behavior.',
'An internal model is the authors’ hypothesis for that persistent compensation. The vehicle studies measured behavior and apparatus movement rather than recording the responsible neural circuit. Their direct findings are adapted steering, aftereffects and improved performance on re-exposure without faster classical relearning.')
slides[-1]['cite']='Givon et al. (2022); Liu et al. (2025)';slides[-1]['refs']=list(refs.values())
assert len(slides)==44,len(slides)
# Expand the read-aloud transcript with the sources’ measured context, without adding framing.
spec={'lecture':79,'content_slides':44,'theme':'muted-carmine-chalk','title_height':2.7,'title_min_pt':22,'title_image':figure('l1a'),'title_refs':list(refs.values()),'slides':slides,'takeaways':{'items':[
{'lead':'The interface','text':'Near-wall outward orientation activates a camera-controlled vehicle command; the fish remains in water while electric motors move its tank through the arena.'},
{'lead':'Two spaces','text':'Tank-relative fish posture supplies the input, while arena-relative vehicle displacement is the output. A software rotation changes their relationship.'},
{'lead':'Complementary measures','text':'Success measures arrival, angular error measures endpoint alignment, and adjusted distance retains detours and an estimated completion cost for failed trials.'},
{'lead':'Adaptation','text':'Goldfish recover target-directed steering while a rotated mapping remains active; compensation reduces directional error and excess movement.'},
{'lead':'Aftereffects','text':'Removing rotation initially produces an opposite-direction error, consistent with persistence of the acquired compensation and the authors’ internal-model hypothesis.'},
{'lead':'Re-exposure','text':'Performance improves during a second exposure, but initial correction rates are slower. Retained performance and faster classical savings are different outcomes.'}
], 'cite':'Givon et al. (2022); Liu et al. (2025)','refs':list(refs.values())}}
(D/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n');(D/'plan.json').write_text(json.dumps([{'slide':i+2,'claim':x['title'],'source':x['cite'],'figure':x['figure']['caption']} for i,x in enumerate(slides)],ensure_ascii=False,indent=2)+'\n')
print('Wrote',len(slides),'content slides')
