import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
R={
'T63':('Tinbergen (1963)','N. Tinbergen (1963). On aims and methods of Ethology. Zeitschrift für Tierpsychologie 20:410–433.','10.1111/j.1439-0310.1963.tb01161.x'),
'H52':('Hodgkin & Huxley (1952)','A.L. Hodgkin; A.F. Huxley (1952). A quantitative description of membrane current and its application to conduction and excitation in nerve. Journal of Physiology 117(4):500–544.','10.1113/jphysiol.1952.sp004764'),
'H90':('Hodgkin & Huxley (1990)','A.L. Hodgkin; A.F. Huxley (1990). A quantitative description of membrane current and its application to conduction and excitation in nerve. Bulletin of Mathematical Biology 52(1–2):25–71. Reprint of the 1952 article.','10.1016/S0092-8240(05)80004-7'),
'W23':('Cormons & Zeil (2023)','M.J. Cormons; J. Zeil (2023). Digger wasps Microbembex monodonta SAY (Hymenoptera, Crabronidae) rely exclusively on visual cues when pinpointing their nest entrances. PLOS ONE 18(3):e0282144.','10.1371/journal.pone.0282144'),
'F09':('Fehér et al. (2009)','O. Fehér; H. Wang; S. Saar; P.P. Mitra; O. Tchernichovski (2009). De novo establishment of wild-type song culture in the zebra finch. Nature 459(7246):564–568.','10.1038/nature07994'),
'F07':('Haesler et al. (2007)','S. Haesler; C. Rochefort; B. Georgi; P. Licznerski; P. Osten; C. Scharff (2007). Incomplete and inaccurate vocal imitation after knockdown of FoxP2 in songbird basal ganglia nucleus Area X. PLOS Biology 5(12):e321.','10.1371/journal.pbio.0050321'),
'P13':('Poláček et al. (2013)','M. Poláček; M. Griggio; M. Bartíková; H. Hoi (2013). Nest sanitation as the evolutionary background for egg ejection behaviour and the role of motivation for object removal. PLOS ONE 8(11):e78771.','10.1371/journal.pone.0078771'),
'K22':('Barber et al. (2022)','J.R. Barber; D. Plotkin; J.J. Rubin; N.T. Homziak; B.C. Leavell; P.R. Houlihan; K.A. Miner; J.W. Breinholt; B. Quirk-Royal; P.S. Padrón; M. Nunez; A.Y. Kawahara (2022). Anti-bat ultrasound production in moths is globally and phylogenetically widespread. Proceedings of the National Academy of Sciences 119(25):e2117485119.','10.1073/pnas.2117485119')}
def ref(k):return R[k][1]+' https://doi.org/'+R[k][2]
def fig(k,name,num,cap):
 return {'path':f'figures/{name}.png','caption':f'{R[k][0]}, Fig. {num}. {cap}','source_url':'https://doi.org/'+R['H90' if k=='H52' else k][2]}
slides=[]
def add(title,k,name,num,cap,text,extra,also=None,anatomy=None):
 body=text.strip().split('\n\n');assert len(body)==3
 keys=[k]+([also]if also else [])+(['H90']if k=='H52'else[])
 s={'title':title,'layout':'figure-right','body':body,'cite':'; '.join(R[x][0]for x in keys if x!='H90'),'refs':[ref(x)for x in keys],'transcript':[re.sub(r'\*\*|_', '',p)for p in body]+[extra],'figure':fig(k,name,num,cap)}
 if k=='H52':s['transcript'].append('The source PDF is the 1990 reprint of the 1952 paper. Experimental observations and the authors’ calculated predictions remain distinct in the reproduced figures.')
 if anatomy:
  ak,an,anum,ac=anatomy;s.update(layout='figures-right',figure_width=6.0,primary_figure_height=2.7,figures=[s.pop('figure'),fig(ak,an,anum,ac)])
  if ak not in keys:s['refs'].append(ref(ak))
 slides.append(s)
A=('F07','F07_1A','1(A)','Area X in a sagittal brain section; original scale bar 1 mm.')
add('Behavior links sensory information to natural tasks','W23','W23_3','3','Apparatus for testing the cues used to locate a hidden nest.', '''**Neuroethology** studies the nervous mechanisms of animal behavior in the context of the tasks animals perform. The solitary wasp _Microbembex monodonta_ repeatedly returns with food to a nest whose entrance it has covered with sand. Cormons and Zeil investigated how the wasp locates that hidden entrance.

They placed transparent covers over nests to mask possible nonvisual cues while preserving the visible surroundings. Returning wasps attempted to dig over the entrance, even when a 5.9 × 5.9 cm tray sealed the local nest surface.

The behavior therefore depends on information available before the entrance is uncovered. The manipulation supports visual guidance under the tested conditions; it does not identify the neurons that encode the goal or the circuit that commands digging.''','A behavior is an observable action. Its sensory determinants can be tested in an intact animal before the underlying neural implementation is known.')
add('Tinbergen separated four biological questions','K22','K22_1','1','Phylogenetic distribution of moth ultrasound production.', '''In 1963, Tinbergen distinguished **causation**, the processes producing behavior; **ontogeny**, its development within an individual; **survival value**, its consequences for survival; and **evolution**, its history across lineages. These questions concern different evidence rather than competing labels for one explanation.

Barber and colleagues recorded moth responses to bat-call playback and mapped ultrasound production onto a molecular phylogeny, a reconstruction of relationships using genetic evidence. Anti-bat sounds occurred in 52 of 252 tested genera, distributed across multiple branches.

The playback establishes a response to a present stimulus, whereas the phylogeny addresses historical distribution. Neither measurement alone establishes how the behavior develops or how much it improves lifetime reproductive success. A comprehensive account requires additional experiments directed at those questions.''','Tinbergen called for integration of the four questions. Mapping a measured response across related taxa supplies historical evidence without replacing experiments on the immediate response.',also='T63')
add('Causation asks what produces a response','W23','W23_4A','4(A)','Digging locations after repeated landmark shifts.', '''**Causation**, or mechanism, concerns the events and processes that produce an action. Cormons and Zeil allowed returning wasps to encounter three cork landmarks around a hidden nest, then displaced the landmarks by 3.4–6.75 cm while the wasps were away.

Initial digging followed the shifted configuration rather than the unchanged physical burrow. Wasps subsequently corrected their search and entered the nest. Changing the available visual information therefore changed where digging began.

This is a causal manipulation of a sensory cue. It does not establish a particular neural representation or explain the evolutionary advantage of navigation. The immediate location of the response and the long-term consequences of that response are different quantities.''','A cue is information an animal can use to guide behavior. The displacement test changes the cue while leaving the actual goal in place.',also='T63')
add('Ontogeny asks how experience changes behavior','F09','F09_1ab','1(a–e)','Songs of normally tutored and song-deprived zebra finches.', '''**Ontogeny** is the development of an individual’s behavior and its underlying machinery. Fehér and colleagues studied male zebra finches, _Taeniopygia guttata_, deprived of adult male song during development, and compared their adult songs with songs from established colonies.

The song-deprived birds produced prolonged or stuttered syllables and less regular song organization. Birds were kept in sound-isolated chambers from day 30 to day 120 after hatching, controlling access to the adult song models normally available during learning.

The manipulation identifies an effect of developmental experience, rather than an immediate response to hearing a song. Song still developed in the absence of normal tutoring, so the result does not support a simple division into wholly learned and wholly experience-independent behavior.''','A syllable is a recurring acoustic unit of song. Developmental deprivation changes the conditions under which those units are acquired and organized.',also='T63')
add('Function concerns consequences for the animal','K22','K22_2D','2(D)','Moth acoustic response to playback of bat sonar.', '''**Survival value**, often discussed as biological function, concerns how a behavior affects the animal’s survival and reproductive prospects. Barber and colleagues examined moth ultrasound evoked by bat sonar and measured its acoustic properties alongside tests of whether bats would consume the moths.

The emissions were centered near 65 kHz, within the ultrasonic frequencies relevant to bat–moth encounters. Some moths were unpalatable; others were readily consumed. These differences constrain proposals that sounds warn predators of noxious prey or mimic such warnings.

Producing a sound in response to a predator cue does not by itself establish a survival benefit. Palatability and acoustic measurements support specific defensive hypotheses, but lifetime survival or reproductive success was not measured for every sound-producing lineage.''','Ultrasound is sound above the frequency range normally audible to humans. Function must be assessed through consequences, not inferred merely from the circumstances in which a behavior occurs.',also='T63')
add('Evolution asks how behavioral traits arose','K22','K22_1','1','Ultrasound production mapped across lepidopteran lineages.', '''**Evolutionary history** concerns the origin and modification of a trait across generations and lineages. Barber and colleagues placed measured moth responses on a phylogeny of Lepidoptera, the order containing moths and butterflies, and compared the distribution of sound production across related groups.

Anti-bat ultrasound was widespread rather than restricted to one familiar moth group. The authors inferred multiple origins and found preliminary evidence of sonar-jamming capability in at least six subfamilies, using acoustic duty cycle as a candidate indicator.

The historical inference depends on the sampled species, the reconstructed relationships, and the definition of the trait. Similar defensive behavior need not indicate a single common origin, and an inferred origin of possible jamming is not a direct bat-capture experiment for every species.''','A lineage is a sequence of ancestral and descendant populations. Historical reconstruction uses measured traits and relationships among living taxa; it is not a direct observation of ancestral behavior.',also='T63')
add('Proximate explanations include development','F07','F07_1AB','1(A–E)','Area X anatomy and the location of viral infection.', '''**Proximate explanations** address how behavior is produced and how its machinery develops. Haesler and colleagues reduced expression of **FoxP2**, a transcription factor that regulates gene expression, in zebra finch Area X, a basal ganglia nucleus involved in song learning.

Viral injections were made on day 23 after hatching, before tutor exposure beginning on day 30. Adult knockdown birds copied tutor songs less completely and less accurately than control birds. The intervention therefore connects a localized molecular manipulation during development to later vocal behavior.

An explanation can be proximate even when its effects emerge weeks after the manipulation. The experiment establishes a requirement for normal FoxP2 levels under these conditions; it does not establish the evolutionary reason that song learning or FoxP2-dependent regulation arose.''','A nucleus is a defined group of neurons within the brain. Area X is a site of the manipulation, not a claim that one small region alone contains the complete mechanism of song.',also='T63')
add('Ultimate explanations require historical evidence','K22','K22_3','3','Acoustic clustering of moth sounds and corresponding taxa.', '''**Ultimate explanations** address the consequences and evolutionary history of behavior. Barber and colleagues compared acoustic signals from an Ecuadorian moth community and found five clusters of similar sounds, including clusters containing both palatable and unpalatable moths.

**Mimicry** is resemblance between signals associated with different organisms that can alter a receiver’s response. Acoustic similarity and palatability differences are consistent with some palatable moths resembling defended species, but similarity alone does not establish that bats mistake one for another.

Current defensive consequences and historical origins are distinct questions. A signal could acquire a new function after its origin, and several lineages could converge on similar signals. Behavioral tests of the predator and comparative reconstruction are needed to evaluate those possibilities.''','Convergence is the independent evolution of similar traits. Resemblance across species can motivate a historical hypothesis without establishing the history by itself.',also='T63')
add('Early ethology emphasized observation and comparison','W23','W23_4A','4(A)','Landmark displacement and the resulting search locations.', '''Tinbergen’s 1963 historical account connected ethology with the comparative work of Whitman (1898, 1919), Heinroth (1911), Huxley (1914, 1923), and Lorenz (1937). He emphasized description of naturally occurring behavior and the biological questions asked about it, rather than defining ethology exclusively as the study of innate acts.

Cormons and Zeil’s modern landmark experiments extend the approach associated with Tinbergen’s wasp studies: observe repeated nest returns, alter surrounding objects, and measure the resulting search. Their cork displacements of 3.4–6.75 cm shifted the initial digging position.

Natural observation and experimental intervention contribute different evidence. Description establishes the behavioral phenomenon and its context; manipulation tests candidate causes. Neither a historical label nor a convincing natural-history narrative is sufficient to identify the nervous mechanism.''','Tinbergen described a movement from description toward analysis while arguing that observation remained necessary. The 2023 paper explicitly relates its nest-location experiments to his earlier work.',also='T63')
add('Behavioral measurements need explicit definitions','W23','W23_2R','2(R)','Traces left by repeated digging attempts near a hidden nest.', '''An **operational definition** specifies how a concept is measured. Cormons and Zeil defined the location of search through visible digging attempts and recorded their positions relative to the actual burrow. The marks left in the sand provided spatial evidence of where the returning wasp searched.

In the covering experiments, each condition was assessed through repeated digging positions rather than a judgment that the insect appeared confused. The published apparatus included centimeter-scale grids for relating those attempts to the hidden goal.

The measurement describes search position, not perception or memory directly. Inferring a remembered visual goal requires the experimental shifts and masking controls as well as the observed action. An ethological description becomes analytically useful when the recorded variable is specified.''','An ethogram is a systematic description of an animal’s behavioral repertoire. A study can select a narrower action, such as digging, and define its measurable features without describing the entire repertoire.',also='T63')
add('Moving landmarks shifts the initial search','W23','W23_4A','4(A)','Sequential training, landmark shifts, and digging attempts.', '''A **landmark** is a feature of the surroundings that provides positional information. Cormons and Zeil introduced cork stoppers 3.5 cm high around wasp nests and allowed the animals to return and leave before changing the configuration’s position.

Wasps initially dug where the nest should have been relative to the moved objects. They could later correct their search, often after flying around the misleading configuration for two to three minutes. The recorded sequence distinguished the first response from eventual successful entry.

Eventual success does not erase the initial effect of the manipulation. The landmarks influenced the search, but the correction indicates that the wasps had access to other information. A result measured only as success or failure would miss the cue conflict expressed early in the search.''','The true burrow remained fixed. The experiment therefore separated the position specified by the local landmarks from the actual position of the goal.')
add('Local landmarks depend on the wider scene','W23','W23_5AB','5(A–B)','Barrier geometry and the sequence of landmark manipulations.', '''The **visual panorama** is the broader scene surrounding the animal. Cormons and Zeil combined a learned local landmark configuration with a 100 × 60 cm opaque barrier positioned 50 cm behind the nest, blocking much of the distant scene seen on approach.

Without the barrier, shifted landmarks could attract the wasps’ digging. With the barrier present, the insects failed to dig or hover at the configuration’s center even though the learned objects remained available and the wasps reached the nest vicinity.

The response to a local cue therefore depended on the surrounding visual context. These behavioral results are consistent with scene-based localization, but they do not identify a neural image-matching algorithm or establish that every navigating insect weights its panorama in the same way.''','A manipulation of context can change the use of a cue without removing that cue. Keeping the local configuration present makes that distinction experimentally meaningful.')
add('Restoring the panorama restores landmark use','W23','W23_5C','5(C)','Landmark-following responses before, during, and after masking.', '''A **reversal control** tests whether restoring an earlier condition restores behavior. In Cormons and Zeil’s landmark–barrier experiment, wasps followed the shifted cube configuration before the distant view was blocked, but none followed it with the barrier present.

After the barrier was removed, the returning wasps again localized the nest relative to the configuration. The published response counts changed from eight following the initial shift to none with the barrier and nine after removal; the remaining animal did not return for the last condition.

The reversal limits explanations based solely on permanent loss of the learned landmarks or irreversible disturbance. It does not exclude every effect of the barrier, but it supports dependence on visual context rather than simple abandonment of nest-search behavior.''','The response category included digging or hovering at the expected location. Restoration was assessed in animals that returned; failure to return is not the same observation as returning and failing to localize.')
add('Cue masking tests alternatives to visual guidance','W23','W23_6AB','6(A–B)','Search distributions when local nonvisual cues were masked.', '''A **masking control** selectively reduces information that might otherwise explain a response. Cormons and Zeil covered nest entrances with combinations of plexiglass, paper, cloth, and frames, changing access to sand relief, odors, and possible acoustic or vibrational information.

Under conditions including 0.3 cm and 0.6 cm high covers, wasps still searched within a few centimeters of the true entrance. Removing access to several candidate local cues did not produce a corresponding loss of localization accuracy.

The result supports the sufficiency of available visual surroundings for the tested task. It does not mean that all nonvisual senses are irrelevant to wasp behavior or that the covers eliminated every conceivable signal perfectly. The conclusion remains tied to these nest-location conditions.''','Sand relief refers to the small variations in surface shape around a nest. Covering those variations tests whether the animal needs the local surface itself rather than the visible broader surroundings.')
add('An airtight cover preserves nest-directed search','W23','W23_3','3','Transparent tray sealing a nest while retaining its visible context.', '''**Sensory sufficiency** concerns whether an available source of information can support a task when alternatives are reduced. Cormons and Zeil placed a transparent inverted tray over each hidden nest and pushed its walls into the sand to create an essentially airtight local seal.

The tray was 5.9 × 5.9 cm and 3.4 cm high. Returning wasps attempted to dig over the entrance rather than along the tray edges, where access to an escaping odor or air movement would have been more plausible.

The preserved search supports visually guided localization despite the altered local surface. It does not establish the internal format of the visual memory or exclude nonvisual information at longer distances during the preceding journey. Local goal localization and the entire homing route are different experimental targets.''','The transparency preserved access to the visual scene while the sealing manipulation changed physical access to the nest entrance. The control concerns the final local search.')
add('Behavioral causation does not identify a circuit','W23','W23_6H','6(H)','Spatial errors and search spread across masking conditions.', '''A **level of analysis** is the scale at which a mechanism is described, such as the intact animal, a circuit, a neuron, or a membrane. Cormons and Zeil measured the positions and spread of wasp digging attempts under several sensory masking conditions.

Search remained centered near the burrow, with characteristic errors of a few centimeters rather than complete loss of the goal. This establishes a behavioral relationship between available information and action while leaving the sensory representation unrecorded.

A proposed visual-memory comparison is a candidate computational mechanism, not an identified population of neurons. Tinbergen argued that physiological and behavioral studies share causal questions across levels; evidence at one level still does not automatically establish the mechanism at another.''','A circuit is a connected network of neurons. Identifying one requires anatomical or physiological evidence beyond a behavioral result, even when the behavioral experiment is causal.',also='T63')
add('Membrane physiology supplied a causal foundation','H52','H52_1','1','The authors’ equivalent circuit for membrane currents.', '''The **membrane potential** is the electrical potential difference across a cell membrane. In their 1952 study, Hodgkin and Huxley described currents across squid nerve membrane as capacitive current plus ionic components carried principally by sodium and potassium.

**Conductance** specifies how readily current passes through a pathway for a given electrical driving force. Their equivalent circuit separated a membrane capacitance, sodium and potassium conductances, and a small leak component. Voltage-clamp measurements supplied the time-dependent conductances used in the analysis.

The work explained electrical excitation through measurable membrane processes. **Ion channels** are membrane pathways through which ions can cross. The published circuit is a mathematical representation of aggregate membrane behavior; it is not a microscopy image or a determination of the molecular structure of individual channels.''','Capacitance describes charge stored across the membrane. Ionic current and capacitive current are different contributions, and the equivalent circuit keeps those contributions explicit.')
add('Voltage clamp separates imposed voltage from current','H52','H52_11','11','Calculated and recorded membrane currents during voltage clamp.', '''A **voltage clamp** holds membrane voltage near an imposed value while measuring the current needed to maintain it. Hodgkin and Huxley compared recorded squid membrane currents with currents predicted from their separately characterized sodium, potassium, and leak conductances.

At 4°C, step changes in voltage produced characteristic current transients. The original figure places calculated traces beside recorded traces with current-density scales in µA/cm² and time in milliseconds, permitting comparison of magnitude and timing across voltage steps.

Agreement supports the adequacy of the combined conductance description for those records. The calculated curves are predictions of the published model, not additional experimental recordings. Their fit does not establish the physical identity of the molecular structures responsible for each conductance.''','Current density is current per membrane area. Holding voltage under experimental control makes the time course of current measurable without the voltage being allowed to follow an unrestricted spike.')
add('Potassium conductance activates with a delay','H52','H52_2','2(a–b)','Potassium conductance during depolarization and repolarization.', '''**Depolarization** is a change that reduces the membrane’s resting electrical separation; **repolarization** returns it toward the resting state. Hodgkin and Huxley measured potassium conductance during a 25 mV depolarization and after voltage returned to rest.

At 21°C in choline seawater, conductance rose after a delay and then declined after repolarization. The rise and fall had different temporal forms, rather than behaving as an instantaneous resistance controlled only by the present voltage.

This history dependence requires a description of the membrane’s evolving state. The authors used voltage-dependent rate processes to reproduce it. The recorded conductance establishes kinetics of the potassium-carrying system, but the fitted state variable was not a direct observation of molecular channel gates.''','Choline replacement reduced the sodium contribution and aided separation of the ionic components. The measured timing constrains how a potassium conductance can contribute during excitation.')
add('Voltage changes the size and timing of conductance','H52','H52_3','3(A–L)','Potassium conductance at different imposed depolarizations.', '''**Voltage dependence** means that changing membrane potential changes the behavior of a membrane process. Hodgkin and Huxley compared potassium conductance during imposed depolarizations spanning 6 to 109 mV in one squid axon at approximately 6–7°C.

Larger depolarizations produced larger conductance changes with different activation time courses. Experimental points were compared with curves calculated from a common kinetic description, rather than fitting each trace with an unrelated arbitrary shape.

The agreement supports a state-dependent potassium process governed by voltage. It does not mean that these large voltage steps occur unchanged during natural behavior, or that potassium current alone explains an action potential. Sodium current and the changing membrane voltage must also be considered.''','The historical voltage convention in the paper differs from common modern plotting conventions. The imposed depolarization values should be interpreted using the original labels, which are retained in the crop.')
add('Sodium conductance activates and then inactivates','H52','H52_6','6(A–L)','Transient sodium conductance across depolarization levels.', '''**Inactivation** is a decline in a conductance despite continued conditions that initially activated it. Hodgkin and Huxley estimated sodium conductance during maintained depolarization and found a rapid rise followed by a decline, unlike the sustained rise of potassium conductance.

Their records from a squid axon at approximately 6–7°C spanned depolarizations from 6 to 109 mV. The conductance transients changed systematically with voltage, and the calculated curves combined an activation process with a slower inactivation process.

The distinction explains why a depolarizing sodium contribution can be brief even when voltage remains displaced. These are inferred kinetic processes of the sodium-carrying system, rather than measurements of protein structure. The experiment separates transient availability from simple dependence on voltage alone.''','Activation increases the ability of the sodium system to carry current. Inactivation reduces that availability over time, so the same voltage can be associated with different conductances after different histories.')
add('Combined ionic kinetics reproduce spike generation','H52','H52_12','12','Calculated and recorded responses to different brief stimuli.', '''An **action potential** is a transient, regenerative change in membrane voltage. Hodgkin and Huxley combined measured ionic kinetics with membrane capacitance to calculate responses to brief stimuli, then compared those responses with squid membrane recordings.

At 6°C, initial depolarizations of 6 and 7 mV produced different calculated outcomes near threshold, while larger stimuli generated full spikes. Above threshold, different initiating stimuli converged on similar spike trajectories after differing delays.

The result connects small differences in initial state to a qualitatively different electrical response. It supports a regenerative mechanism involving sodium activation and subsequent opposing processes. It does not imply that every neuron has the same threshold or the same complement of ionic currents.''','Regeneration means that a voltage change recruits processes that amplify that change. Delayed potassium activation and sodium inactivation subsequently limit the depolarizing phase.')
add('Propagation requires membrane and longitudinal current','H52','H52_15','15(a–d)','Predicted and recorded propagated action potentials.', '''**Propagation** is the spread of an electrical impulse along a nerve fibre. Hodgkin and Huxley extended their membrane description to include longitudinal current flowing between adjacent portions of the squid axon, allowing a local excitation to recruit the next region.

For the illustrated propagated response at 18.5°C, the calculated waveform was compared with recorded spikes. Their parameter-based calculation gave a speed of 18.8 m/s, compared with an experimentally measured speed of 21.2 m/s in the fibre.

The comparison tests a prediction beyond fitting one stationary membrane trace. It supports the combination of ionic kinetics and electrical coupling for this preparation. The calculation remains an approximation, and it does not by itself specify how a sensory pathway transforms an impulse into a complete behavior.''','A local circuit current links neighboring membrane regions electrically. Propagation is therefore a spatial property of an excitable fibre as well as a temporal property of its membrane conductances.')
add('Recovery from a spike is a measurable state change','H52','H52_20','20','Calculated and recorded responses to a second stimulus.', '''The **refractory period** is the interval after an action potential during which another spike is impossible or requires a stronger stimulus. Hodgkin and Huxley compared responses to stimuli applied at different delays after an initial squid membrane spike.

At 6°C, early second stimuli produced little regenerative activity, whereas later stimuli produced progressively larger responses. Their calculated responses matched the broad recovery pattern in the recorded traces, including altered spike shape during partial recovery.

The mechanism depends on residual potassium conductance and incomplete recovery of sodium availability. Refractoriness therefore reflects the membrane’s recent history rather than a fixed delay imposed by an external clock. The agreement is physiological evidence, not a direct measurement of each molecular channel’s state.''','The absolute refractory interval prevents another full spike. During relative refractoriness, a stronger stimulus can evoke a response while recovery remains incomplete.')
add('Song learning depends on access to a tutor','F09','F09_1ab','1(a–e)','Wild-type and isolate songs with original time and frequency scales.', '''**Vocal learning** is modification of vocal output through experience with sounds. Fehér and colleagues separated young zebra finches from adult male song beginning early in development and compared the resulting isolate songs with the species-typical songs of established colonies.

Normally tutored songs contained repeated sequences of distinct syllables, called **motifs**. Isolate songs often contained prolonged or stuttered units and less regular temporal organization. The spectrograms retain a 200 ms time scale and a frequency range extending to 8 kHz.

Deprivation changed the form of the adult output while leaving the capacity to produce song intact. The comparison identifies a developmental contribution of tutoring, not a claim that every acoustic feature must be copied from experience or that isolate birds lack neural organization.''','A spectrogram represents acoustic frequency over time. Tutor exposure provides a developmental input; it is not simply a stimulus that triggers an immediate song response.')
add('Different song timescales require different measures','F09','F09_1ab','1(a–e)','Frequency modulation, acoustic-state duration, and song rhythm.', '''A **behavioral phenotype** is a measurable form of behavior. Fehér and colleagues characterized song at several timescales: spectral features over 10 ms, persistence of acoustic structure over 10–100 ms, and rhythm over 200–1,000 ms.

Isolate songs had lower frequency modulation, longer persistence of similar acoustic structure, and less organized rhythm than wild-type songs. **Frequency modulation** is change in frequency through time; the duration of an acoustic state describes how long successive spectral patterns remain similar.

These measures distinguish changes within syllables from changes in their larger temporal arrangement. A song can differ at one timescale without differing identically at another. Quantifying several features prevents a single subjective assessment of song quality from replacing the measured developmental phenotype.''','The authors used feature distributions rather than one preferred exemplar. Acoustic-state duration and rhythm are different summaries of temporal organization.')
add('Pupils shorten unusually long tutor syllables','F09','F09_2gh','2(g–j)','Tutor–pupil spectrograms and the relationship of syllable durations.', '''**Biased imitation** is copying that systematically changes a feature rather than reproducing it without directional alteration. Fehér and colleagues paired juveniles with isolate tutors, keeping each pair in a sound-isolated chamber and checking that the adult tutor’s song remained stable.

A tutor syllable averaging 367 ms was copied with an average duration of 243 ms. Across tutor–pupil comparisons, syllables shorter than about 230 ms were copied relatively faithfully, whereas unusually long syllables were shortened.

The pupil therefore acquired material from the tutor while modifying its duration. The result is inconsistent with either exact copying or wholly independent song invention. It establishes a developmental copying bias, but it does not identify the neural rule that causes the shortening.''','Stable adult tutors and controlled one-to-one exposure limit explanations in which the apparent copying bias results only from a changing tutor model.')
add('Copying changes the abundance of repeated syllables','F09','F09_2gh','2(g–j)','Tutor repetition and the more structured pupil song.', '''**Syllable abundance** is the proportion of song occupied by a given syllable type. Fehér and colleagues compared isolate tutors whose songs were dominated by repetitive units with the songs acquired by juveniles exposed to those tutors.

When one syllable dominated the isolate song, its abundance in pupil song fell to approximately 20–30%. The pupils generally retained the tutor’s syllable material while reorganizing repetition into more structured motifs, rather than needing a normal adult song as their only possible template.

The change separates acquisition of syllable identity from reproduction of its frequency of use. It supports constraints on how learned material is organized, but it does not establish that a fixed genetic sequence directly specifies each motif or that all social contexts produce identical learning biases.''','The identity of a learned sound and its abundance are distinct properties. A pupil can copy the former while altering the latter.')
add('Small learning biases accumulate across generations','F09','F09_3bcde','3(a–e)','Song changes along controlled tutoring lineages.', '''A **tutoring generation** is one step in which a learner acquires song and later serves as the model for another learner. Fehér and colleagues established lineages from isolate founders, allowing pupils to become tutors when they reached adulthood at roughly 120–140 days.

Song moved toward the wild-type distribution over three to four learning generations. The accumulating changes included shorter sustained acoustic states and more typical spectral and rhythmic organization, even though each learner began with the altered song of the preceding tutor.

This is transmission of a behavioral phenotype through learning, not evidence of new genetic adaptation within three generations. The controlled lineages separate cultural inheritance from the assumption that resemblance between generations must result from shared DNA alone.''','The tutoring pairs could be genetically unrelated. Their ordered transmission therefore measures a social pathway of inheritance rather than establishing a parent–offspring genetic effect.')
add('Colony transmission also moves songs toward wild type','F09','F09_4','4(a–e)','Relationships and song change in the isolated colony.', '''**Cultural transmission** is passage of behavioral information through social learning. Fehér and colleagues founded an acoustically isolated colony with an isolate male and females, allowing new learners to hear multiple birds and develop within a social group.

Across successive clutches, songs moved toward wild-type characteristics, paralleling the controlled tutor–pupil lineages. Rhythm approached the normal pattern particularly rapidly in the colony, while other features changed through successive generations of learners.

The colony adds evidence that the directional change was not restricted to one-to-one tutoring. Because colony members could choose among models and respond to social partners, it does not isolate every source of the change. Competition, tutor selection, and female feedback remained possible contributors.''','The paper followed the isolated colony for two years. Changes in social learning can accumulate without requiring the experimental introduction of a normal singing adult.')
add('Molecular interventions test a developmental cause','F07','F07_1AB','1(A–E)','Area X and the localized viral infection.', '''**RNA interference** reduces expression of a target gene through short RNA sequences that guide suppression of its messenger RNA. Haesler and colleagues delivered hairpin RNA with a lentiviral vector to reduce FoxP2 expression in zebra finch Area X.

The intervention occurred on day 23 after hatching; each pupil then lived with a tutor from day 30. Viral reporter fluorescence identified the infected region, and adult songs were compared with songs from birds given control constructs.

This experimental sequence tests a molecular contribution to developmental learning rather than a correlation between gene expression and singing. A localized manipulation provides causal evidence, but the resulting behavior depends on interactions with the rest of the vocal-learning system and the tutor experience.''','A viral vector delivers the experimental construct to cells. The reporter identifies infected tissue, whereas the target hairpin changes FoxP2 expression.')
add('Target specificity requires molecular controls','F07','F07_1F','1(F)','Protein measurements after target and control hairpin expression.', '''**Specificity** concerns whether a manipulation acts on its intended target rather than indiscriminately changing related processes. Haesler and colleagues designed two hairpin RNAs directed at different FoxP2 sequences and compared their effects with a nontargeting control.

Both target hairpins reduced FoxP2 protein in cultured cells while leaving FoxP1, its close relative, comparatively unaffected. Protein measurements included an actin loading control, allowing a reduction in the target band to be distinguished from simply loading less material.

The controls support the intended molecular action of the constructs. They do not measure every possible downstream effect or prove that one transcriptional target alone explains vocal learning. The behavioral interpretation also depends on confirming the manipulation in brain tissue.''','A transcription factor can influence many downstream genes. Specific reduction of the factor is therefore not equivalent to identification of one downstream synaptic mechanism.',anatomy=A)
add('Brain-tissue measurements verify the knockdown','F07','F07_1G','1(G)','FoxP2 and reporter labeling in control and knockdown tissue.', '''**Knockdown** is an experimental reduction of gene expression rather than complete deletion of the gene. Haesler and colleagues measured FoxP2 RNA and protein in Area X after viral delivery, using a control injection in the opposite hemisphere for tissue comparisons.

At day 50 after hatching, FoxP2 messenger RNA was reduced by approximately 70% in the infected region. Immunofluorescence also revealed lower FoxP2 labeling in targeted tissue, confirming that the cultured-cell result extended to the brain preparation.

The affected volume was only part of Area X, so the manipulation was not a complete removal of the nucleus. Tissue verification links the later song phenotype to a measured molecular reduction, but it does not identify the full sequence of cellular changes caused by that reduction.''','Messenger RNA is the template used in protein synthesis. Reduced RNA and protein labeling are complementary checks on the intervention, while reporter labeling localizes its delivery.',anatomy=A)
add('FoxP2 reduction impairs completeness of imitation','F07','F07_2','2(A–D)','Tutor songs, pupil songs, and imitation similarity scores.', '''**Imitation completeness** concerns how much of the tutor’s song is represented in the pupil’s learned output. Haesler and colleagues compared adult song after FoxP2 knockdown with songs from pupils receiving a nontargeting hairpin or a control directed at the viral reporter.

Knockdown pupils omitted or imprecisely copied tutor syllables. In comparisons using the same tutors for different treatment groups, mean similarity scores were approximately 61.9 for knockdown pupils and 82.6 for controls, limiting an explanation based only on the tutor’s song.

The result establishes impaired learning under the targeted developmental manipulation. It does not mean that the birds could not sing, nor that incomplete imitation alone specifies whether the deficit arose in model memory, auditory comparison, or adjustment of motor output.''','The similarity score summarizes how much tutor material is matched. It differs from the precision with which an already represented syllable is reproduced.',anatomy=A)
add('Completeness and acoustic accuracy can dissociate','F07','F07_3','3(B)','Pupil imitation accuracy under target and control treatments.', '''**Imitation accuracy** concerns the precision of the acoustic match between pupil and tutor. Haesler and colleagues analyzed song units separately from the broader question of whether a unit was included in the learned song at all.

For pupils sharing tutors, accuracy scores averaged approximately 71.7 after FoxP2 knockdown and 73.8 in controls, while differences in completeness were larger. Syllable duration and acoustic structure also diverged more from the tutor in the knockdown group.

The intervention therefore affected more than the presence or absence of a syllable. A modest change in one summary score can coexist with a larger change in another. Neither measure alone identifies the specific cellular process responsible for the altered learning outcome.''','Different scores answer different behavioral questions. Acoustic entropy, used in the paper, describes spectral noisiness rather than the number of syllables learned.',anatomy=A)
add('Learned song can remain unusually variable','F07','F07_4','4(C–D)','Acoustic consistency and variability of syllable duration.', '''**Performance variability** is the variation among repeated productions of an acquired action. Haesler and colleagues compared multiple renditions of the same syllable in adult zebra finches after developmental FoxP2 knockdown or control treatment.

Knockdown birds produced less consistent acoustic forms and more variable syllable durations. The source recordings used 100 ms scale bars, and variability was quantified separately from differences between the tutor and pupil.

A pupil can therefore acquire a recognizable syllable while failing to stabilize its performance normally. The result separates learning outcome from execution consistency, but it does not establish whether the altered variability originates in a single synapse, a feedback process, or distributed circuit dynamics.''','A rendition is one performance of a syllable. Variation across renditions is measured within the bird, whereas imitation accuracy compares the bird with its tutor.',anatomy=A)
add('Developmental trajectories constrain causal hypotheses','F07','F07_5','5(A–B)','Imitation accuracy and variability across pupil age.', '''A **developmental trajectory** is the measured change of a phenotype through time. Haesler and colleagues recorded songs at days 65, 80, and 90 after hatching, rather than relying only on one adult endpoint after FoxP2 knockdown.

Knockdown pupils were less accurate by day 65 and failed to continue improving after day 80 as controls did. Their variation in imitation accuracy also increased toward adulthood, whereas earlier variability was more similar between treatment groups.

These observations constrain the timing of the deficit and argue against an explanation based simply on an inability to generate variable vocal output. Impaired adjustment toward a memorized tutor model remained a proposed explanation; the study did not directly record the neuronal comparison process or resolve its synaptic mechanism.''','The intervention was followed by a changing learning phenotype. Its time course supplies evidence about development without establishing every intermediate neural step.',anatomy=A)
add('Internal state changes responses to nest objects','P13','P13_1','1','Flat objects differing in size, color, and shape.', '''**Motivation** describes state-dependent readiness to perform an action; it is inferred here from measured removal behavior, not directly recorded as a neural variable. Poláček and colleagues tested tree sparrows, _Passer montanus_, using flat nest objects during egg laying and incubation.

The cardboard objects varied one feature at a time around a normal egg-shaped model approximately 19.4 mm long. Across conditions, most objects were removed within a 60 minute observation period, but the timing depended on object properties and breeding stage.

The task separates the response to an object from the physical difficulty of grasping a real egg. It supports state-dependent object removal, while leaving the hormonal and neural determinants of that state unmeasured. Motivation is therefore a behavioral interpretation rather than an identified transmitter system.''','Flat models make removal physically easier than removal of a rounded egg. They allow feature-dependent response tendencies to be assessed while reducing a motor constraint.')
add('Object size interacts with breeding stage','P13','P13_3','3','Removal time for large, normal, and small objects.', '''**State dependence** means that the effect of a stimulus changes with the animal’s condition. Poláček and colleagues presented tree sparrows with flat egg-like objects approximately 15.0, 19.4, or 23.3 mm long, keeping material and general appearance similar.

During egg laying, larger objects were removed faster than smaller ones, with normal-sized objects intermediate. During incubation, the size ordering was less apparent. The published curves track objects remaining in the nest through the 60 minute observation period.

An object’s dimensions therefore did not determine removal latency independently of breeding stage. The result supports an interaction between stimulus features and internal context. It does not establish whether the underlying change is sensory discrimination, response threshold, or a specific endocrine pathway.''','Latency is the time between a defined event and the response. Here it was measured from the bird’s first entry until it emerged carrying the object.')
add('Color effects need not measure egg recognition','P13','P13_5','5','Removal time for white, normal, and dark objects.', '''**Stimulus discrimination** is differential responding to distinct stimulus properties. Poláček and colleagues compared flat white, normal-colored, and dark egg-shaped objects while holding their dimensions close to the same standard model.

White objects were removed faster than dark objects over the 60 minute observation interval. However, the difference in lightness between a bird’s own clutch and the experimental object did not predict removal latency in the corresponding analysis.

A color effect is therefore not equivalent to evidence that the bird compares each object with a detailed template of its own eggs. The authors considered nest sanitation, including resemblance to waste material, as an explanation. That proposal remained distinct from a demonstrated neural recognition rule.''','Lightness describes how light or dark an object appears. Comparing object color with clutch color tests a more specific recognition hypothesis than merely comparing responses to different colors.')
add('Removal behavior does not establish adaptive history','P13','P13_7','7','Removal of square and egg-shaped objects across breeding stages.', '''An **adaptive explanation** attributes a trait’s evolution to consequences that favored its persistence. Poláček and colleagues examined whether nest sanitation could provide an evolutionary background for removal of parasitic eggs, comparing flat square and egg-shaped objects in tree sparrow nests.

The objects had matching surface area and color, and removal was followed for 60 minutes. Shape alone did not produce a clear overall difference in removal latency. Separate trials with real added eggs frequently resulted in continued incubation rather than ejection.

These findings support limits on treating every removed object as evidence of specialized anti-parasite recognition. Nest sanitation as an ancestral precursor remains a historical hypothesis, not a reconstructed sequence of evolutionary changes. Present-day response mechanisms and past adaptive origins require different evidence.''','Nest sanitation is removal of unwanted material from a nest. A behavior can have consequences relevant to more than one task without proving which consequence originally favored its evolution.')
add('Different effectors can produce similar defensive sounds','K22','K22_2ABCD','2(A–D)','A moth, tegular structures, modified scales, and emitted ultrasound.', '''An **effector** is a structure that produces an action. Barber and colleagues examined the physical mechanisms of moth ultrasound, combining recorded responses with anatomical inspection and manipulations of sound-producing structures.

In _Mittonia hampsoni_, modified scales on the **tegula**, a structure near the forewing base, participate in percussive sound production during wingbeats. Ablation experiments supported this mechanism. The source panels retain animal and structural scales of 1 cm, 0.2 mm, and 50 µm.

Other moths produce ultrasound by rubbing modified scales or by buckling cuticular plates called **tymbals**. Similar acoustic behavior can therefore arise from different structures. Shared defensive sound does not establish shared anatomical machinery or one evolutionary origin.''','Ablation removes or disables a candidate structure. Its effect on sound production supplies stronger mechanistic evidence than anatomy alone, while the original micrographs identify the tested structure.')
add('Acoustic resemblance suggests a warning function','K22','K22_3','3','Clusters of moth signals, taxa, and palatability categories.', '''**Aposematism** is signaling that warns a predator of a defended or otherwise costly prey. Barber and colleagues compared acoustic features of 33 Ecuadorian moth species and used a dimensionality-reduction method to group similar measured signals into five clusters.

Each cluster included at least one genus found to be unpalatable to bats, while most also included readily consumed moths. This pattern is consistent with acoustic warning and mimicry, but the clustering records resemblance among signals rather than a direct measure of predator confusion.

A proposed warning function requires tests of how bats learn and respond to the sounds. Similarity, palatability, and evolutionary relatedness provide complementary evidence, not interchangeable proof. The authors described the mimicry associations as preliminary and left their interaction dynamics unresolved.''','A dimensionality-reduction method summarizes several acoustic measurements in fewer coordinates. The reproduced map is the authors’ published analysis, not a new graph made from their numbers.')
add('A candidate function must remain separate from ancestry','K22','K22_1','1','Trait distribution and candidate sonar-jamming lineages.', '''**Duty cycle** is the fraction of an interval occupied by sound. Barber and colleagues used the approximately 18% duty-cycle criterion drawn from earlier bat–moth work to identify lineages whose measured signals might interfere with processing of returning sonar echoes.

The mapping suggested possible independent origins of jamming in at least six subfamilies. A further high-duty-cycle group lacked ears and could not respond in advance to approaching bats, exposing a limit of classifying function from one acoustic property alone.

**Sonar jamming** is disruption of the predator’s echo processing. High duty cycle is a candidate indicator, not proof of jamming in every tested moth. Functional tests, immediate sensory mechanisms, developmental evidence, and ancestry remain distinct requirements for a complete biological explanation.''','The paper explicitly describes its jamming-origin inference as preliminary. A plausible acoustic capability must be distinguished from the animal’s ability to deploy it at the relevant time.')
assert len(slides)==44,len(slides)
items=[
('Four questions address different evidence.','Mechanism, ontogeny, function, and evolutionary history are complementary accounts of behavior.'),
('Proximate causes include developmental processes.','Immediate sensory and membrane mechanisms and the experience that builds behavior belong to the causal account.'),
('Ultimate explanations require consequences and history.','A useful present-day response does not by itself establish its ancestral function or origin.'),
('Causal claims depend on controls.','Cue shifts, reversals, molecular specificity, tissue verification, and matched tutor comparisons distinguish competing explanations.'),
('Neural mechanisms span levels.','Ionic kinetics explain excitation; localized gene manipulation affects learning; neither alone identifies an entire behavioral circuit.'),
('Learning and inheritance interact.','Tutor experience changes individual song, and directional copying biases can accumulate through cultural transmission without demonstrating new genetic adaptation.')]
spec={'lecture':1,'content_slides':44,'theme':'ink-cherry','title_image':fig('K22','K22_2A','2(A)','Mittonia hampsoni, an ultrasound-producing moth; scale bar 1 cm.'),'slides':slides,'takeaways':{'items':[{'lead':x,'text':y}for x,y in items],'cite':'Tinbergen (1963); Hodgkin & Huxley (1952); Haesler et al. (2007); Fehér et al. (2009); Barber et al. (2022)','refs':[ref(k)for k in ['T63','H52','H90','F07','F09','K22']]}}
(ROOT/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
for i,s in enumerate(slides,2):
 n=len(re.sub(r'\*\*|_','', ' '.join(s['body'])).split())
 assert 90<=n<=170,(i,n)
 assert len(s['title'])<=62,(i,s['title'])
print('Wrote 44 content slides with three full paragraphs each')
