"""Lecture 18: prose and notes grounded in the original papers in papers/.

Figures are unmodified PDF crops recorded in crops.json; no scientific visuals
are constructed here. Bibliographic fields were verified against Crossref and PDFs.
"""
import json,re,unicodedata
from pathlib import Path
HERE=Path(__file__).resolve().parent
RESEARCH=HERE/'sources'
crops=json.loads((HERE/'crops.json').read_text())
REF={}
for key in {c['paper'] for c in crops}:
 d=json.loads((RESEARCH/(key+'-crossref.json')).read_text())
 def person(a):
  g=a.get('given','');initials=g if g.isupper() else ''.join(w[0] for w in g.replace('-',' ').split())
  family=unicodedata.normalize('NFC',a['family']).replace('Koppl','Köppl')
  return family+' '+initials
 authors=', '.join(person(a) for a in d['author']);year=d['published']['date-parts'][0][0]
 title=re.sub('<[^>]+>','',d['title'][0]).replace('owl,Tyto','owl, Tyto');journal=d['container-title'][0].replace('eneuro','eNeuro')
 REF[key]=f"{authors} ({year}). {title}. {journal} {d['volume']}({d['issue']}):{d.get('page',d.get('article-number',''))}. https://doi.org/{d['DOI']}"
slides=[]
def add(title,p1,p2,p3,extra,also=()):
 i=len(slides);c=crops[i];key=c['paper'];body=[p1,p2,p3];plain=[re.sub(r'\*\*|_', '',p) for p in body]
 # Read-aloud teaching notes preserve the experiment and add source-based reasoning.
 transcript=[[plain[0],[extra]],plain[1],plain[2]]
 cite=c['caption'].split(', Fig.')[0]
 refs=[REF[k] for k in [key,*also]]
 for k in also:
  d=json.loads((RESEARCH/(k+'-crossref.json')).read_text());family=unicodedata.normalize('NFC',d['author'][0]['family']);yr=d['published']['date-parts'][0][0]
  cite+='; '+family+(' et al.' if len(d['author'])>2 else ' & '+d['author'][1]['family'] if len(d['author'])==2 else '')+f' ({yr})'
 slides.append({'title':title,'layout':'figure-right','figure_width':5.2,'body':body,'transcript':transcript,'cite':cite,'refs':refs,'figure':{'kind':'article','path':c['out'],'caption':c['caption'],'source_url':c['source_url']}})

add('Owls orient toward sounds without visual guidance',
'The barn owl, **Tyto alba**, is a nocturnal predator whose auditory system converts prey-generated sound into directed head movements. **Azimuth** is horizontal direction; **elevation** is vertical direction. Head turns provide a behavioral measure of the location the owl perceives.',
'Kettler and colleagues recorded head orientation while presenting sounds through earphones. At an interaural delay of 100 µs, broadband noise produced turns toward the corresponding target. A 5-kHz tone could instead elicit turns toward an alternative location in the opposite hemifield.',
'This **phantom source** is a localization illusion, not a second physical loudspeaker. Broadband and 1.5-kHz-wide narrowband stimuli distinguished spectral effects from a change in the imposed delay. The behavior connects auditory timing ambiguity to an observable orienting decision.',
'A head-turn trajectory measures the animal’s response to an auditory percept, rather than neuronal tuning itself. The earphone conditions control the acoustic difference between ears while the bird remains able to orient. The published comparisons include broadband sounds, pure tones, and narrowband noise under the same timing manipulation.')
add('The two ears supply time and level differences',
'**Interaural time difference**, or ITD, is the difference in sound arrival time between ears, measured in microseconds. **Interaural level difference**, or ILD, is the difference in sound pressure level, measured in decibels. Neither cue is a location label at the auditory nerve.',
'Kettler and colleagues used ear-canal probe microphones to measure the head’s acoustic filtering. The frontal ITD map varied chiefly with azimuth; ILD varied strongly with elevation and also contained an azimuthal component. The facial ruff and asymmetric ears contribute to this filtering.',
'Acoustic measurements and playback tests used directions corresponding to delays of 50, 100, and 150 µs. Natural level cues reduced timing ambiguities. The familiar association of ITD with horizontal direction and ILD with vertical direction is therefore a useful specialization, not an absolute separation of behavioral functions.',
'The head-related transfer function describes how the head and external ears change the level and phase of each frequency arriving from a particular direction. Measuring it close to the eardrum includes the filtering actually available to the animal. A small horizontal level component can matter when timing information admits two competing locations.')
add('Midbrain neurons respond to restricted auditory space',
'A **receptive field** is the set of stimulus conditions that changes a neuron’s activity. Knudsen and Konishi mapped auditory receptive fields by moving a loudspeaker around the head of a lightly anesthetized owl in an anechoic chamber, which minimized reflected sound.',
'Noise bursts lasted 100 ms and were delivered 10 dB above each unit’s threshold. Speaker positions were sampled in azimuth and elevation while extracellular spikes were recorded. A smaller **best area** was defined by the positions producing maximal rather than merely detectable responses.',
'Most mapped fields were vertically elongated. Their widths ranged from 7° to 40° in azimuth, with a mean of 25°. A broad response boundary and a smaller best area describe different aspects of selectivity; neither alone is a behavioral localization threshold.',
'An extracellular electrode detects the action potentials of a unit while the experimenter controls speaker position. The published field includes responses collected at different positions, not a spatial image received by the cochlea. The neurons were recorded in darkness, and tests with visual stimuli did not evoke the reported auditory responses.')
add('Midbrain neighbors represent neighboring sound locations',
'Knudsen and Konishi reconstructed electrode tracks histologically and compared recording position with the center of each neuron’s best area. The auditory region was called **MLD**, nucleus mesencephalicus lateralis dorsalis, the avian homolog of the inferior colliculus.',
'Best-area azimuth shifted from approximately 60° contralateral in the posterolateral region to 15° ipsilateral anteromedially. Best-area elevation ranged from about +20° to −90°, with higher directions represented dorsally and lower directions ventrally. Neighboring neurons generally had overlapping receptive fields.',
'Tone bursts, clicks, and noise usually preserved best-area location; changing level from 10 to 30 dB above threshold also preserved its position. The orderly representation supports a computed map of auditory space rather than a simple map of acoustic frequency or overall loudness.',
'Contralateral means on the side opposite the recording hemisphere; ipsilateral means on the same side. Histological lesions identified track endpoints so that receptive-field order could be matched to tissue position. The original report established an orderly physiological map, while later experiments identified the separate computations that supply its coordinates.')
add('Timing and level preferences can vary independently',
'A **tuning curve** relates neuronal response to a controlled stimulus parameter. Takahashi, Moiseff, and Konishi varied ITD while holding ILD fixed, then varied ILD while holding ITD fixed, recording from space-specific midbrain neurons through calibrated earphone stimulation.',
'Changing the level difference over a 20-dB range did not systematically displace the timing preference. Conversely, changes in timing altered response magnitude without systematically displacing the preferred level difference. The positions of the two response peaks were separable.',
'Independence of preferred values does not mean that both cues are irrelevant to firing rate. A neuron can respond strongly only when both are favorable. The experiments separate how each cue is represented from how the two representations jointly determine the output.',
'Earphones allow one binaural cue to change without the acoustically coupled changes produced by moving a real speaker. The critical observation concerns the location of the tuning peak, rather than complete invariance of all spike counts. Holding the other cue fixed tests whether one preference shifts when the other input changes.')
add('Angularis activity is necessary for normal level tuning',
'**Nucleus angularis**, or NA, is a cochlear nucleus receiving auditory-nerve input. Takahashi and colleagues locally injected lidocaine into NA while recording a space-specific neuron in the inferior colliculus. Lidocaine is a local anesthetic that blocks neuronal impulse conduction.',
'After unilateral NA inactivation, the neuron’s ILD response shifted toward the injected side’s altered effective input. In the same preparation, the ITD response peak remained essentially stable. Recovery measurements and an injection-site marker linked the change to a localized, reversible manipulation.',
'The selective alteration supports a level-processing pathway originating in NA. It does not imply that NA alone calculates a binaural level difference: its monaural output must subsequently be compared with information from the other ear. Local inactivation also cannot identify every downstream synapse.',
'When one cochlear nucleus contributes less activity, the downstream circuit receives an unbalanced representation even though the earphone stimulus itself has not changed. The timing curve serves as a within-neuron control against a general collapse of midbrain responsiveness. Histological localization distinguishes an angularis injection from neighboring magnocellularis tissue.')
add('Magnocellularis activity is necessary for normal time tuning',
'**Nucleus magnocellularis**, or NM, is a second cochlear nucleus receiving auditory-nerve input. Takahashi and colleagues injected lidocaine into NM and measured the same two binaural tuning dimensions used in the angularis experiments, separating neural impairment from an acoustic change.',
'NM inactivation altered the ITD tuning of a space-specific neuron, while its preferred ILD remained approximately unchanged. Recordings before injection, during the effect, and after recovery supplied a temporal control. Injection-site histology checked the anatomical locus of the manipulation.',
'The reciprocal effects of NM and NA inactivation form a **double dissociation**: disrupting one pathway selectively changes timing, whereas disrupting the other selectively changes level. This establishes functional separation at the cochlear nuclei without claiming that the final spatial response is generated by only one pathway.',
'A double dissociation is stronger than observing two kinds of tuning in separate neurons. Each intervention is evaluated against both response dimensions. The result constrains the origin of the information reaching the midbrain, while leaving open the precise transformations carried out between the cochlear nuclei and the recorded space-specific cell.')
add('Distinct brainstem nuclei preserve different sound variables',
'The eighth cranial nerve carries auditory information from the cochlea into the brainstem. Carr and Konishi identified NA, NM, and **nucleus laminaris**, or NL, in transverse tissue sections. NL lies in the timing pathway downstream of bilateral NM input.',
'A neurofilament stain distinguished fiber-rich laminaris from neighboring nuclei and the cerebellar peduncle. Histology supplied landmarks for intracellular recording and tracer experiments, preventing recording depth alone from being treated as proof of a particular nucleus.',
'The anatomical separation is compatible with parallel timing and level computations, but staining does not measure what a neuron encodes. Functional assignments require the phase-locking, rate-level, binaural, and inactivation experiments that connect these structures to particular acoustic variables.',
'Auditory-nerve fibers carry both temporal and level information. Parallel nuclei need not receive completely different acoustic signals to emphasize different variables. The relevant distinction is how neurons transform their shared peripheral input. The original micrograph supplies anatomical positions and a scale bar; its labeled nuclei are experimental tissue, not an invented circuit.')
add('Magnocellular spikes retain the phase of acoustic cycles',
'**Phase locking** means that spikes occur preferentially at a particular phase of a repeating sound waveform. Sullivan and Konishi recorded NM neurons during tonal stimulation and grouped spike times into **period histograms**, which align successive stimulus cycles.',
'NM neurons retained phase locking at frequencies up to 9 kHz in that study. The distributions were not identical at every frequency: spikes could occur on different cycles while remaining concentrated near a preferred position within the cycle. Timing information therefore survived without one spike per cycle.',
'NM rate-level functions were comparatively narrow and often changed little above spontaneous discharge. This specialization supports timing transmission to NL. A phase histogram measures temporal alignment; it does not, by itself, establish a neuron’s sensitivity to differences between the two ears.',
'A high spontaneous rate does not prevent a sound from reorganizing spike timing. A neuron can convey more temporal information without greatly increasing its average spike count. The comparison with angularis is functional: magnocellularis emphasizes phase, whereas angularis supplies a more informative rate representation of sound level.')
add('Angularis firing rates represent changes in sound level',
'Sullivan and Konishi measured **rate-level functions**, the relation between stimulus level and spike count, in NA neurons. Compared with NM, NA typically had lower spontaneous discharge and larger increases in firing as the level of a tone rose.',
'Angularis responses commonly changed over more than 20 dB, often 30 dB or more. The **dynamic range** is the range of levels over which the response changes substantially. Different cells showed different slopes and saturation levels, preserving a population representation of level.',
'NA showed little or no phase locking at higher frequencies, although weak locking occurred below about 3.5 kHz. The contrast with NM concerns relative specialization, not perfectly exclusive coding. Monaural level-sensitive discharge provides input for later comparison between ears.',
'The two cochlear nuclei can have similar frequency selectivity while differing substantially in temporal and intensity responses. Frequency tuning therefore cannot substitute for testing rate-level and phase-locking properties. The plotted decibel scale is the original experimental level scale; it should not be relabeled as an absolute environmental sound level.')
add('Auditory-nerve phase locking reaches approximately 10 kHz',
'Köppl recorded single auditory-nerve fibers with calibrated tones and compared their spike timing across frequency and sound level. **Vector strength** quantifies concentration of spike phases: values near one indicate tight phase alignment, whereas values near zero indicate dispersed phases.',
'Auditory-nerve phase locking extended to approximately 10 kHz. Its quality declined with frequency, but the decline included a plateau around 1.5–3 kHz. Phase organization could be detected below the level at which a clear increase in average spike rate appeared.',
'The peripheral temporal code supplies the brainstem with information needed for ITD processing. Detectable locking is not equivalent to equally precise locking at every frequency. Rate threshold and timing sensitivity also describe different response measurements and should not be treated as interchangeable.',
'The study used ear-canal calibration for individual animals, so stimulus level was measured at the auditory input rather than inferred from a speaker setting. Vector strength compares phases across many cycles. A high-frequency neuron need not fire on every cycle to retain information about a preferred stimulus phase.')
add('The NM synapse limits some temporal precision',
'Köppl obtained auditory-nerve and NM recordings in the same animals, permitting a direct comparison of temporal information before and after the first central relay. Tone frequency and level were controlled while saturated phase-locking quality was assessed.',
'Above approximately 1 kHz, NM vector strength was consistently lower than auditory-nerve vector strength. The comparison does not support a universal sharpening of phase locking at this relay. Both populations retained locking well into the frequency range used for owl localization.',
'The additional synaptic transformation can introduce temporal dispersion even in a highly specialized pathway. These recordings identify a functional limitation of transmission; they do not isolate a particular ion-channel subtype or determine whether convergence compensates for the loss at later stages.',
'Saturated phase locking refers to the response after increasing sound level no longer improves timing alignment substantially. Comparisons at appropriate levels avoid attributing a level-dependent improvement to the relay itself. Earlier NM studies remain plotted in the original article, but the same-animal nerve-versus-NM comparison supplies the direct experimental test.')
add('Laminaris receives frequency-matched input from both ears',
'**Tonotopy** is the orderly anatomical representation of acoustic frequency. Carr and Konishi traced NM projections and recorded afferent fibers within NL. Inputs from opposite ears entered corresponding frequency regions rather than mixing all frequencies indiscriminately.',
'Injections into NM regions tuned near 5.5 and 7 kHz labeled different projection territories. Physiological recordings from a single NL penetration found closely matched ipsilateral and contralateral frequency tuning, including fibers encountered at depths of 1320 and 1400 µm.',
'Frequency matching permits comparison of the timing of corresponding waveform components. Comparing unrelated frequencies would not preserve a stable phase relation. Anatomical tracing establishes projection order, while the paired frequency-response measurements establish the functional matching needed by a timing comparator.',
'The best frequency is the frequency producing the strongest response under the measurement conditions. The original normalized curves permit comparison of tuning shape even when absolute spike counts differ. The study also found mismatched fibers near borders, which limits any claim that every axon encountered around NL belongs to the same frequency channel.')
add('NM axons enter laminaris from opposite borders',
'Carr and Konishi injected **horseradish peroxidase**, or HRP, into NM and followed labeled axons through serial brain sections. HRP is a tracer that permits projection pathways to be visualized after a histochemical reaction.',
'An NM neuron sends branches to NL on both sides. Ipsilateral afferents approach the dorsal border, whereas contralateral afferents approach the ventral border. The published reconstruction preserves this opposing arrangement and includes a 1-mm scale bar.',
'Opposing entry directions supply an anatomical basis for position-dependent differences in arrival time. The tracing identifies axonal paths, not conduction speed. A functioning **delay line**, a pathway whose travel time changes with position, also requires physiological evidence of orderly timing differences.',
'The original authors reconstructed three-dimensional arbors across serial sections and adjusted their projection onto the published two-dimensional view. The drawing is their published anatomical result, cropped unchanged from the article. Its geometry should not be interpreted as an exact flattened measurement of every branch length or physical separation.')
add('Input spike timing changes systematically through laminaris',
'Carr and Konishi recorded phase-locked NM afferents at different depths within NL. They stimulated one ear with a tone and measured the mean phase of the resulting intracellularly recorded spikes, testing whether conduction time changed along the projection.',
'At 4 kHz, the tonal period was 250 µs; at 5.5 kHz it was approximately 182 µs. Mean phase changed regularly with depth. In a 7-kHz region, abrupt apparent phase jumps corresponded to crossing into the next stimulus cycle.',
'**Phase wrapping** occurs because phase repeats after a complete cycle even when physical delay continues increasing. The data support orderly neural delays rather than independent random timing at each site. Reading phase alone without recognizing cycle repetition would misidentify these continuous gradients.',
'The physiological measurement concerns the arrival time of afferent spikes, not the external arrival time of sound at the ears. A longer axonal travel path shifts spike phase systematically. At a high enough stimulus frequency, a real delay can span more than one cycle, requiring the authors to track the neighboring cycle.')
add('Opposed delay gradients support binaural coincidence',
'Within a common frequency region, Carr and Konishi found that ipsilateral afferent delay increased with recording depth while contralateral delay decreased. Intracellular recordings distinguished the two input populations during separate stimulation of the ears.',
'Across NL’s approximately 700-µm depth, conduction time changed by about 160 µs for frequencies between 4 and 7.5 kHz. Similar delay ranges across frequency channels support comparison of common external timing differences rather than unrelated phase preferences.',
'At a particular position, an external ITD can compensate for the difference in internal path delays. The two spike trains then arrive together. This spatially ordered compensation explains how a physical time difference can be represented by the location of strongly activated NL neurons.',
'The original Figure 8A contains paired gradients from multiple penetrations. The plotted time axes preserve the authors’ conversion of phase to delay. A coincidence detector responds to arrival times after both external acoustic travel and internal neural conduction have contributed; changing either contribution can change the favored ITD.')
add('Short myelin internodes can contribute to slow conduction',
'A **myelin internode** is the insulated axonal segment between successive nodes where impulse propagation is renewed. Carr and Konishi measured internodal spacing in HRP-labeled NM axons inside and outside NL, comparing anatomy with physiological delay gradients.',
'Internodes within NL were about 60 µm long and more regularly spaced than many segments outside the nucleus. The physiological estimates placed local conduction velocity around 3–5 m/s. Published micrographs identify nodes at branch points and along axon segments.',
'The authors proposed that short internodes help regulate the slow propagation needed for delay lines. The spacing measurements and timing gradients are established observations; the causal contribution of internodal length was not tested by selectively changing myelination while recording conduction speed.',
'Nodes are interruptions of the myelin sheath, and nodal spacing is one anatomical contributor to impulse propagation. The experiment does not establish a particular sodium- or potassium-channel density at each node. Its interpretation combines measured axonal anatomy with measured conduction delays while keeping that mechanistic inference separate from direct intervention.')
add('Laminaris detects bilateral spike coincidence',
'**Coincidence detection** is enhanced firing when two inputs arrive within a short interval. Carr and Konishi recorded NL neurons intracellularly, first stimulating each ear separately and then varying ITD during binaural stimulation.',
'For a neuron tested at 4409 Hz, monaural response phases were approximately 338° and 294°. A favorable delay of 30 µs, with the contralateral ear leading, increased the recorded response to 1107 spikes, compared with 393 and 360 for the separate-ear conditions.',
'The same neuron responded much less at unfavorable delays. The binaural enhancement therefore depended on relative timing rather than simply the presence of two sounds. Across the study, favorable binaural responses were roughly twice monaural responses, consistent with coincidence-sensitive integration.',
'The displayed totals come from the published stimulus-repetition protocol and are not firing rates in spikes per second. Separate-ear histograms supply a prediction of which delay aligns the inputs; the binaural delay curve tests that prediction. Intracellular recording avoids confusing the strong population field potential in NL with a single neuron’s spikes.')
add('A narrow frequency channel represents time ambiguously',
'NL neurons receive frequency-selective, phase-locked inputs. With a tone, the same phase alignment recurs whenever the interaural delay changes by a whole stimulus period. Carr and Konishi measured periodic firing peaks across a range of imposed delays.',
'The delay curves differed in preferred timing and modulation depth, but their repeated maxima were consistent with the frequency of the stimulus. At 4 kHz, the 250-µs period gives repeated opportunities for alignment, including delays beyond the strongest peak near the physiological range.',
'**Phase ambiguity** is this inability of a single narrowband channel to identify one unique ITD from its firing rate. Precise coincidence detection and an unambiguous estimate of sound direction are different computations. Later integration must distinguish the true timing relation from repeated phase matches.',
'The original curves also preserve monaural response markers and spontaneous levels. Responses at unfavorable binaural timing could fall below the monaural level, so the entire curve cannot be explained by simple summation of two independent firing rates. Repeated response peaks reflect waveform periodicity rather than multiple real sound sources.')
add('Collicular arrays conserve timing across frequency channels',
'Wagner, Takahashi, and Konishi recorded neurons while advancing an electrode through the central nucleus of the inferior colliculus, or **ICC**. Individual cells were narrowly frequency tuned and had periodic ITD response curves.',
'One penetration sampled best frequencies from approximately 2100 to 6700 Hz. Despite different peak spacings, its neurons shared an **array-specific ITD** at which their relative responses aligned. Mean interaural phase changed systematically with frequency across the array.',
'An **array** is a group of neurons arranged across frequency laminae with a common timing relation. Convergence from such an array can supply a downstream neuron with agreement across frequencies at one delay, even when each contributing channel remains individually ambiguous.',
'The curves are normalized to each recording’s maximum, so alignment refers to relative response levels rather than identical absolute firing. The study compared single-unit and multi-unit recordings and found closely matching peak positions. A preferred phase for one frequency is insufficient to identify the array-specific ITD without the cross-frequency relation.')
add('Frequency changes systematically along a collicular array',
'An **isofrequency lamina** is a sheet of neurons with similar frequency tuning. Wagner and colleagues used dorsoventral electrode penetrations through ICC to sample multiple laminae and establish the anatomical orientation of the physiological arrays.',
'In a representative penetration, best frequency rose monotonically with depth from approximately 500 Hz to 10 kHz. This organization provided the frequency diversity needed to test whether different channels share a common delay rather than merely a common preferred phase.',
'The recording trajectory crossed frequency laminae; it did not trace one neuron’s dendrite through every channel. The observed tonotopy establishes the organization of the sampled population. Connectivity to the external nucleus requires separate tracer measurements rather than an inference from adjacent recording sites alone.',
'A shared delay produces different preferred phase values at different frequencies, because each waveform has a different period. Sampling a broad frequency range makes that relation testable. Electrode depth supplies an anatomical coordinate, while the measured frequency at each site provides the functional coordinate of the lamina.')
add('Array-specific delays form an ordered central-nucleus map',
'Wagner and colleagues compared ITD-frequency relations across seven penetrations whose positions were reconstructed histologically. Each penetration contained an array, but the slope of its phase-frequency relation differed from slopes in neighboring arrays.',
'Mean interaural phase was plotted against frequencies up to approximately 8 kHz. The different slopes identified different array-specific delays. Their orderly change across ICC established a map of timing preference superimposed on the frequency organization.',
'This representation is not yet the full two-dimensional map of external sound direction. It is a map of a computed binaural timing variable distributed across frequency channels. ILD selectivity and broader integration are needed to produce the restricted spatial receptive fields of the external nucleus.',
'The characteristic delay is the delay associated with a frequency-dependent phase relation. The original authors distinguished a neuron exhibiting such a relation across tests from its ability to signal an unambiguous delay in a single narrowband response. Population organization can preserve the relation even when each cell’s rate curve repeats.')
add('ICx receives inputs with matching timing preferences',
'The **external nucleus of the inferior colliculus**, or ICx, contains space-specific neurons. Wagner and colleagues recorded timing preference at an ICx site, injected HRP there, and located retrogradely labeled neurons in ICC.',
'Labeled somata occupied an array crossing frequency laminae. Nearby physiological measurements in ICC shared the timing preference measured at the injection site. The published example includes a −120-µs array-specific relation and a 1-mm anatomical scale bar.',
'**Retrograde tracing** identifies neurons projecting toward the injection region. Matching tracer distribution with measured tuning supports convergence from an appropriate ICC array to a localized ICx region. It does not establish the synaptic weight or connectivity of every labeled neuron to one particular recorded cell.',
'The experiment combines two independent kinds of evidence: physiological cue tuning and anatomical projection labeling. An injection region can encompass more than one cell, so the result concerns a restricted target region rather than a complete single-cell wiring diagram. The preserved original sections and response curves retain that distinction.')
add('Projection position shifts with the target’s timing preference',
'Wagner and colleagues repeated retrograde labeling at ICx sites with different timing preferences. They counted labeled ICC somata as a function of distance from the posterior end of the colliculus, testing whether projection origins moved systematically.',
'The ICx injection sites preferred delays of 120, 90, and 60 µs with the contralateral ear leading, or 15 µs with the ipsilateral ear leading. The distributions of labeled cells shifted with these target preferences rather than remaining at one fixed ICC position.',
'The covariation supports an ordered transformation from an ICC timing map into the horizontal coordinate of the ICx space map. Cell-count distributions locate projection populations; their height does not directly report synaptic strength, firing rate, or the probability of a behavioral turn.',
'A target with a different preferred timing cue receives input from a differently positioned array. Frequency convergence can therefore preserve one timing relation while passing through the broad set of frequencies represented in that array. This anatomical selectivity is compatible with the physiological absence of strong phase ambiguity for broadband ICx stimulation.')
add('Broadband input suppresses repeated peaks in ICx',
'Takahashi and Konishi compared ICx delay curves evoked by a tone at the neuron’s best frequency with curves evoked by broadband noise. A tone contains a repeated cycle, whereas broadband noise supplies multiple frequency components with different periods.',
'Tonal stimulation commonly produced a principal peak and repeated secondary peaks. Noise greatly reduced the secondary responses while preserving the timing near the principal peak. The comparison was performed within the same neuron, holding recording site constant.',
'Cross-frequency agreement is strongest at the actual delay shared by the broadband components. This supports convergence as part of ambiguity resolution, but spectral convergence alone does not establish every source of suppression. Level controls, response nonlinearities, and later inhibitory manipulations constrain the mechanism more directly.',
'The best frequency describes the channel most effective for that neuron; broadband input recruits additional channels. The authors compared response levels for tones and noise because a weaker tone could otherwise create an apparent difference in selectivity merely by lowering firing. The neural output becomes less ambiguous when independent spectral components agree.')
add('Two-tone stimulation tests cross-frequency convergence',
'Takahashi and Konishi presented two tones individually and together while varying ITD. The tones were selected within a neuron’s frequency-response range, permitting a controlled test of integration rather than comparing one tone with an unrestricted noise spectrum.',
'In the published examples, tones near 7 and 8 kHz generated differently spaced delay peaks. Their joint presentation favored the common principal delay and altered secondary responses. The combined response was compared with the responses to each component alone.',
'This preparation tests whether timing evidence from different frequency channels interacts at a space-specific neuron. It supports a convergence mechanism but does not prove linear addition or identify each presynaptic source. The final selectivity can include inhibitory and spike-generation nonlinearities as well as excitatory agreement.',
'Two tones share a true imposed interaural delay while their repeated phase matches occur at different delays. Component-only conditions supply the control needed to distinguish spectral integration from simply increasing the sound level. The source article analyzes how the joint response compares with the expected combination of the separate component responses.')
add('Secondary peaks are reduced rather than universally absent',
'Takahashi and Konishi quantified the strongest secondary response relative to the principal response during broadband stimulation. The **secondary-to-primary peak ratio** describes residual ambiguity, with a ratio near one indicating similarly strong competing peaks.',
'The published distribution spans approximately zero to one, with many neurons retaining a substantial but smaller secondary response. Broadband selectivity therefore varied across ICx cells rather than forming a perfectly uniform all-or-none solution.',
'Population firing, inhibitory sharpening, and output thresholds can reduce the impact of residual peaks. A low peak ratio is evidence of improved single-cell selectivity; it is not a direct measurement of the probability that an owl will orient toward a phantom source under every listening condition.',
'The principal peak is identified by its relation to the neuron’s characteristic delay, while the secondary peak is a different local maximum. The ratio measures relative response within one neuron and should not be interpreted as a response rate. Neural suppression and behavioral disambiguation are related, but they require different experimental readouts.')
add('VLVp combines excitation from one ear with inhibition',
'**VLVp**, the posterior part of the ventral nucleus of the lateral lemniscus, is an early binaural station in the level pathway. Manley, Köppl, and Konishi recorded its responses while independently changing sound levels at the two ears.',
'Contralateral stimulation excited VLVp cells; ipsilateral stimulation inhibited them. Dorsal, intermediate, and ventral sites differed in inhibitory strength. The published examples include a strongly inhibited dorsal cell at 7.9 kHz and an intermediate cell with approximately 60% inhibition at 8.6 kHz.',
'Varying ILD while holding average binaural level constant separated interaural balance from overall loudness. These largely monotonic response functions supply a graded code for level disparity. They should not be equated with the sharply peaked ILD tuning that emerges at later collicular stages.',
'Monotonic means that response changes mainly in one direction as the cue increases across the tested range. The same binaural difference can be produced at several absolute levels, so testing multiple average levels assesses how robust the response is to source intensity. VLVp contributes an intermediate representation rather than a complete spatial receptive field.')
add('VLVp level thresholds are ordered dorsoventrally',
'Manley and colleagues described a VLVp response by its **half-maximum point**, the ILD at which firing reaches half of the response maximum. Sequential recording sites within a penetration were compared to test for an anatomical order of this response criterion.',
'Dorsal sites had more contralaterally biased half-maximum points; progressively ventral sites shifted toward ipsilateral values. Some cells changed their half-maximum point by 2 dB or less when average binaural level rose by 10 dB, providing a measure of level stability.',
'This is an ordered map of response thresholds along a binaural level axis. It differs from a spatial map of receptive-field centers. A half-maximum point can be well defined for a monotonic curve even when the neuron has no sharply bounded preferred ILD.',
'Average binaural level is the mean of the two ear levels expressed in decibels in this experiment. Opposite changes at the ears vary ILD while preserving that average. The authors grouped cells by their relative position within each penetration, so the ordering is a physiological-anatomical relation rather than a measurement of external elevation in degrees.')
add('Excitatory and inhibitory thresholds shape level sensitivity',
'Manley and colleagues measured monaural excitatory and inhibitory thresholds in VLVp. Inhibition was assessed against an established discharge produced by contralateral stimulation, allowing reductions in spikes to be measured rather than requiring a cell to fire below zero.',
'The difference between excitatory and inhibitory thresholds covaried with the strength of inhibition. Threshold relationships and ILD half-maximum points changed along the dorsoventral recording sequence. The interaction, rather than one ear’s absolute sensitivity alone, shaped the binaural response.',
'This physiology supports an excitation-inhibition comparison as the basis of level sensitivity. It does not identify a unique molecular receptor at every connection. Later pharmacological experiments tested the contribution of GABAergic inhibition and the effects of manipulating the two VLVp populations independently.',
'An inhibitory threshold is meaningful only when activity is available to suppress. Background excitation supplies that activity, so an apparent absence of spikes is not mistaken for proof that an inhibitory input is absent. The difference between the thresholds determines when inhibition begins relative to the growth of excitatory firing.')
add('Both VLVp populations project to collicular level circuits',
'Adolphs injected **PHA-L**, an anterograde tract tracer, into VLVp and examined labeled terminals in the inferior colliculus. **Anterograde tracing** follows projections away from the injected neuronal population toward its targets.',
'Label appeared in the lateral shell of ICC on both sides of the brain. The published tissue sections include the VLVp injection site and 500-µm scale bars. The injection was anatomically separated from the adjacent anterior subdivision, VLVa, in the illustrated preparation.',
'Bilateral connectivity gives the colliculus access to two differently biased level signals. Tracer labeling establishes projection pathways but not whether a terminal is excitatory or inhibitory. Functional manipulations and receptor-sensitive interventions are required to establish the signs and consequences of those connections.',
'The lateral shell is a subdivision of the central inferior colliculus that supplies input to the spatial map. Anatomical localization prevents a timing-pathway injection from being misclassified as a level-pathway experiment. The source photographs preserve the labeled terminals, injection region, and scale bars needed to evaluate that localization.')
add('Increasing VLVp activity can suppress collicular responses',
'Adolphs manipulated VLVp while recording an ICC lateral-shell neuron. **GABA**, gamma-aminobutyric acid, is an inhibitory transmitter; **bicuculline methiodide**, or BMI, blocks GABA-A receptors. Blocking inhibition within VLVp can increase the activity sent to its targets.',
'In the published experiment, a 0.5-µL BMI injection into contralateral VLVp nearly eliminated the lateral-shell response. Responses were measured before injection, 2 and 7 minutes afterward, and during recovery. The response returned toward its original ILD dependence by about 60 minutes.',
'The remote reduction supports an inhibitory influence from that VLVp population onto the collicular circuit. Blocking an inhibitory receptor upstream can decrease downstream firing by disinhibiting an inhibitory projection. Injection spread and network effects limit assignment of the entire effect to one directly connected neuron.',
'Disinhibition means increased activity after an inhibitory influence is removed. The sign of a drug’s effect at its injection site need not match the sign of the effect at a distant recording site. Reversible changes and the time course of recovery help distinguish acute circuit modulation from irreversible tissue damage.')
add('Reversible VLVp inactivation selectively changes ILD tuning',
'Adolphs injected lidocaine into one VLVp and recorded a neuron in contralateral ICx. The earphone stimulus remained controlled while ILD and ITD response curves were tested separately, providing a comparison of level and timing effects in the same downstream cell.',
'At approximately 7 minutes after injection, responses at large ipsilateral ILDs increased and the ILD peak shifted. The original response recovered by about 25 minutes. The neuron’s ITD curve remained nearly unchanged during the same manipulation.',
'The result supports an inhibitory level signal that normally limits responses on one side of the ILD range. Removing that signal broadens or shifts level tuning while sparing the timing preference. Lidocaine reduces activity broadly at the injection site, so it is not a transmitter-specific test.',
'The intact ITD response is a within-cell control against a general loss of auditory responsiveness. Recovery supplies an additional control against permanent damage. The experiment links a brainstem population to a particular dimension of an ICx receptive field, without equating drug-induced tuning shifts with the owl’s immediate orienting behavior.')
add('Opposing inhibitory influences can create a level peak',
'A sharply peaked ILD curve requires reduced firing on both sides of its preferred range. Adolphs tested whether the two VLVp populations supply opposing inhibitory influences by increasing activity in one population with local BMI injection.',
'At about 3 minutes, ICx responses decreased at large ipsilateral ILDs, opposite to the effect of inactivating that VLVp. The ILD response recovered toward its baseline over approximately 50 minutes. The ITD response measured during the experiment remained stable.',
'Combined anatomical and manipulation evidence supports bilateral inhibition as a mechanism for peaked collicular level tuning. The circuit transforms two graded, differently biased inputs into a restricted response range. Exact synaptic weights and the contribution of additional local inhibition were not determined by these injections.',
'The original study used complementary increases and decreases of VLVp activity, rather than relying on a single drug condition. Opposite physiological effects strengthen the interpretation that level tuning depends on the upstream population. Preserved timing sensitivity limits the effect to the level-processing contribution under the tested stimulus conditions.')
add('An ILD spectrum contributes to the vertical receptive field',
'An **ILD spectrum** is the set of level differences across acoustic frequencies at one sound direction. Euston and Takahashi measured head-related transfer functions and used them to deliver virtual sources through earphones, preserving frequency-dependent acoustic filtering.',
'For 100-ms stimuli, they compared normal receptive fields with **ILD-alone fields**, in which ITD was fixed at the neuron’s preferred value while natural ILD spectra varied with location. ILD-alone responses typically formed a horizontal band containing the normal receptive field.',
'An ILD spectrum therefore supplies substantial vertical selectivity, while timing information restricts the horizontal region. The two conditions often had different response maxima. The neuron’s normal preferred direction cannot be inferred simply by selecting the largest ILD-alone response.',
'Virtual acoustic space is an experimental playback method using measured head filtering; the published response maps are recordings from neurons under those conditions. The surrounding inhibitory regions were retained in the authors’ maps. The comparison holds timing favorable to isolate level contributions without moving a real sound source.')
add('Normal spatial tuning need not maximize each ILD',
'Euston and Takahashi measured pure-tone ILD tuning across frequency and compared preferred ILDs with the values occurring at the peaks of normal and ILD-alone receptive fields. They examined bands spanning 3–5, 5–7, and 7–9 kHz.',
'Frequency-specific preferences matched the ILDs at the ILD-alone peak more closely than those at the normal receptive-field peak. A sum of frequency-specific inputs accounted for approximately 56% of the variance in measured ILD-alone fields, leaving substantial unexplained structure.',
'The normal receptive field reflects a balance of inputs rather than independent maximization of every frequency-specific channel. The reported prediction supports a contribution from spectral integration; it does not establish that the computation is purely additive or explain all inhibitory interactions.',
'The regression comparisons separate a neuron’s favorite level difference for a tone from the actual spectral values at a spatial response peak. A direction can be preferred under broadband stimulation without providing the best ILD at every frequency. The remaining prediction error limits a simple account based only on summing measured tonal responses.')
add('ICx membranes integrate timing and level before spikes',
'Peña and Konishi recorded identified ICx neurons intracellularly and labeled them with neurobiotin. A **postsynaptic potential** is a membrane-voltage change caused by synaptic input; it can depolarize toward spike threshold or hyperpolarize away from it.',
'Broadband noise bursts lasted 100 ms and were presented 30 dB above threshold. Testing ITD-ILD pairs produced depolarizing responses near a preferred combination and hyperpolarizing responses outside it. Spike output formed a more restricted excitatory center surrounded by reduced firing.',
'The intracellular measurement distinguishes input integration from the thresholded spike response. Depolarization at an unfavorable cue pair need not produce spikes. Hyperpolarizing responses support inhibition, but the recorded voltage can contain a mixture of excitatory and inhibitory influences rather than a single isolated conductance.',
'The paper verified inhibitory voltage behavior by changing membrane potential, rather than identifying inhibition solely from absent spikes. Neurobiotin labeling connects the physiological recording to an ICx cell with a tectal projection. The figure retains the original 25-µm cellular scale bar and the 1-mm projection scale.')
add('Timing and level interact approximately multiplicatively',
'Peña and Konishi arranged subthreshold membrane responses into a matrix of ITD-ILD combinations. A **multiplicative interaction** means that the effectiveness of one cue depends on the strength of the other, rather than two cue-dependent responses simply being added.',
'After accounting for a constant membrane-voltage offset, a separable multiplicative component described about 96.6% of the response structure in the studied neurons. **Singular value decomposition** separated the measured matrix into ranked components, allowing multiplicative and additive accounts to be compared.',
'Multiplication captured the data better than a simple additive alternative. This describes an experimentally supported computation at the membrane-response level. The analysis does not prove that one particular receptor or dendritic compartment literally performs multiplication, and it does not eliminate smaller contributions from other interactions.',
'An analog conjunction can permit firing only when both timing and level are favorable. The measured response matrix and the authors’ fitted matrix are reproduced directly from the paper, including their original units and axes. The fit is the authors’ published analysis; no response surfaces have been reconstructed for this deck.')
add('Spike generation sharpens spatial selectivity',
'Peña and Konishi compared membrane-potential and spike tuning in the same ICx neurons. The **spike threshold** is the voltage-dependent boundary above which the neuron can generate an action potential; small depolarizations need not cross it.',
'The example retained several subthreshold timing peaks but produced spikes mainly near the dominant timing peak. ILD tuning was also narrower in spike output than in membrane voltage. The original records use milliseconds for the stimulus traces and microseconds for imposed interaural timing.',
'The quality of a multiplicative description was lower for spike output than for subthreshold responses. Additional nonlinear processes therefore intervene between synaptic integration and discharge. Thresholding is consistent with this sharpening, while inhibition can also change the underlying voltage response before spikes occur.',
'A small secondary depolarization can be visible in an intracellular record yet fail to produce any spike output. The disappearance of a firing peak does not prove that the corresponding input has vanished. The experiment separates membrane integration from the output transformation and limits conclusions based only on extracellular spike tuning.')
add('Binaural correlation controls the strength of timing input',
'**Binaural correlation** measures similarity of the fine temporal waveform at the two ears. Peña and Konishi varied correlation while recording intracellular responses, changing timing reliability without simply replacing the level difference with a different spatial cue.',
'Correlation values of zero, 0.25, 0.5, 0.75, and one altered the amplitude of ITD-dependent membrane responses. ILD tuning was comparatively stable. At zero correlation, the timing component became nearly flat even though level-dependent responses could remain.',
'Multiplicative descriptions remained effective across much of the manipulated range. When one input is almost constant, additive and multiplicative alternatives become harder to distinguish. Correlation manipulations therefore test robustness while exposing an identifiability limit of the mathematical description.',
'The same nominal delay becomes unreliable when the two ear signals no longer share matching fine structure. The study changed the temporal relationship independently of the level tuning measurement. A flat timing response under uncorrelated noise does not imply deafness; it indicates loss of evidence for one specific interaural delay.')
add('GABA-A inhibition sharpens collicular timing selectivity',
'Fujita and Konishi applied BMI locally while recording timing-sensitive neurons across auditory nuclei. **GABA-A receptors** are ligand-gated chloride channels. GABA binding changes chloride conductance and can reduce the effectiveness of excitatory input. Antagonist application tests whether this inhibitory transmission contributes to the response curve.',
'In ICC and ICx, BMI broadened tonal ITD tuning and increased responses at unfavorable delays. The lateral-shell example compares tuning before, during, and after application; a 3-kHz tonal condition was followed through recovery. VLVa timing selectivity was comparatively unaffected.',
'GABAergic inhibition therefore sharpens the timing representation at selected collicular stages rather than uniformly creating timing sensitivity everywhere. Local drug application establishes a receptor-sensitive contribution. It does not separately identify every inhibitory source or specify an unmeasured ion-channel subtype.',
'The half-peak width measures the range of delays over which a response remains above half of its peak. A broader curve indicates weaker selectivity even if the maximum response rises. GABA application produced opposite effects, and simultaneous BMI could antagonize those effects, supporting a GABA-receptor-mediated interpretation.')
add('GABAergic inhibition helps suppress false timing peaks',
'Fujita and Konishi compared broadband ICx timing responses before and during local GABA-A receptor blockade. Broadband input normally emphasizes a principal timing peak while suppressing repeated matches inherited from narrowband channels.',
'BMI increased secondary-peak responses and could restore phase ambiguity for noise. The published records include time-dependent increases at delays such as −270 and +120 µs while the principal timing preference remained distinguishable. Recovery measurements tested reversibility after drug application.',
'Cross-frequency convergence and inhibitory suppression jointly support unique broadband timing selectivity. The antagonist result establishes an inhibitory contribution but does not imply that inhibition alone can compute the correct delay without frequency-matched excitation. Drug spread and altered network gain limit a single-synapse interpretation.',
'An increase in all responses can differ from a selective release of secondary peaks. The source compares the secondary-to-primary relation as well as response time courses, helping distinguish these possibilities. Phase ambiguity can therefore reappear when inhibition is weakened even though the excitatory inputs still carry the same physical sound timing.')
add('Glutamate contributions differ across collicular stages',
'**Glutamate** is an excitatory transmitter. Feldman and Knudsen applied AP5, an antagonist of NMDA (N-methyl-D-aspartate) receptors, and CNQX, a non-NMDA glutamate-receptor antagonist, by iontophoresis while recording from ICx and the ICC lateral shell.',
'AP5 removed about 55% of auditory-evoked spikes at ICx multiunit sites and 64% at single units, compared with approximately 19% and 25% in the lateral shell. Combined AP5 and CNQX strongly suppressed responses in both subdivisions, often eliminating them.',
'NMDA-dependent transmission contributes more prominently to ICx responses, while non-NMDA transmission is substantial in both regions. Normalizing AP5 blockade against combined blockade addressed variation in drug efficacy across sites. Spike reduction measures functional contribution, not receptor abundance or a direct percentage of synaptic current.',
'Iontophoresis uses an electrical current to deliver a drug locally. The two-antagonist comparison constrains whether a weak AP5 effect reflects little NMDA contribution or generally ineffective local delivery. NMDA and non-NMDA receptors are distinct glutamate-sensitive ion-channel families. NMDA channels have voltage-dependent magnesium block that can be relieved by depolarization. The ICx responses retained an NMDA contribution across their tested dynamic range, rather than recruiting it only above a separate high-level threshold. Antagonist-sensitive spikes do not constitute a complete molecular census.')
add('NMDA-dependent transmission sustains late ICx responses',
'Feldman and Knudsen analyzed **peristimulus time histograms**, which align repeated spike trains to sound onset. They tested ICx units with transient, sustained, or mixed responses to 50-ms broadband stimuli at their preferred ITD and ILD.',
'AP5 at 25 nA reduced spikes, with a larger effect on late activity in mixed transient-sustained responses. Responses were measured before application, during blockade, and after recovery. CNQX, in contrast, reduced activity more uniformly across the response time course.',
'The temporal difference is consistent with slower NMDA-dependent excitation supplementing faster non-NMDA transmission. It does not directly measure receptor kinetics in voltage clamp. Together with coincidence detection, bilateral inhibition, and cross-frequency convergence, synaptic integration supports the sustained spatial signals available for owl orienting.',
'An iontophoretic current is a drug-delivery setting, not the synaptic current flowing through a neuron. The 50-ms sound duration and the sequence of control, blockade, and recovery remain in the original figure. A slow excitatory postsynaptic current can persist between successive inputs and summate during a sustained spike train. The authors proposed this mechanism for the growing late NMDA contribution. These experiments concern transmission in established spatial circuits; a role in developmental plasticity requires separate evidence.')

assert len(slides)==44
# Notes retain source-based additions and complete references; pictures remain editable assets.
takeaways={'items':[
 {'lead':'Computed spatial maps','text':'ICx receptive-field centers are ordered by sound direction; the map is computed from binaural signals rather than copied from a spatial receptor surface.'},
 {'lead':'Parallel cue pathways','text':'NM preserves timing and NA emphasizes sound level. Selective inactivation dissociates their contributions before the cues converge.'},
 {'lead':'Delay lines and coincidence','text':'Opposed NM conduction gradients and coincidence-sensitive NL neurons transform interaural timing into place-dependent activity.'},
 {'lead':'Convergence and inhibition','text':'Frequency-matched ICC arrays provide cross-frequency agreement, while GABAergic inhibition suppresses competing timing peaks in ICx.'},
 {'lead':'Level tuning and cue combination','text':'Bilateral inhibitory influences create peaked ILD tuning; approximately multiplicative membrane integration combines timing and level selectivity.'},
 {'lead':'Mechanisms have experimental limits','text':'NMDA and non-NMDA antagonists identify transmission contributions. Natural ILDs can also aid horizontal disambiguation, so ITD and ILD are not exclusive behavioral axes.'}
 ],'cite':'Knudsen & Konishi (1978); Carr & Konishi (1990); Adolphs (1993); Peña & Konishi (2001); Kettler et al. (2017)','refs':[REF[k] for k in ['k78','s84','t84','c90-jneuro','w87-jneuro','k88-jneuro','a93','fu91','p01','f94-jneuro','mod17-pdf']]}
spec={'lecture':18,'theme':'steel-sky','content_slides':44,'slides':slides,'takeaways':takeaways}
(HERE/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
(HERE/'references.json').write_text(json.dumps(REF,ensure_ascii=False,indent=2)+'\n')
print('Written',len(slides),'content slides with original article figures.')
for i,s in enumerate(slides,2):
 n=sum(len(re.sub(r'\*\*|_','',p).split()) for p in s['body']);print(i,n,s['title'])
# Original published map as the title asset, with the same source provenance.
spec['title_image']=dict(slides[3]['figure'])
(HERE/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
