"""Lecture 52: original published figures and teaching-first, source-supported paragraphs."""
import json,re,html
from pathlib import Path
base=Path(__file__).resolve().parent
research=json.loads((base/'research.json').read_text());refs={};cites={};dois={}
years={'stereotypy':2016,'selfdirected':2025,'crh':2016,'males':2025,'sampling':2019,'seasonal':2023,'habitat':2021,'activity':2020,'rest':2016,'orphans':2022,'gut':2023,'reintegration':2023,'assessment':2024,'insight':2011,'risk':2019}
for k,y in years.items():
 v=research[k];m=v['crossref'];a=', '.join(' '.join((q.get('given','')+' '+q['family']).split()) for q in m['author']);title=' '.join(html.unescape(re.sub('<[^>]+>','',m['title'][0])).split());pages=m.get('page') or m.get('article-number') or {'crh':'11937','orphans':'639','seasonal':'coad029','assessment':'e18370','insight':'e23251'}.get(k,'');refs[k]=f'{a} ({y}). {title}. {html.unescape(m["container-title"][0])} {m.get("volume","")}: {pages}. https://doi.org/{v["doi"]}';dois[k]=v['doi'];cites[k]=m['author'][0]['family']+' et al.'+f' ({y})'
refs['insight']=refs['insight'].replace('Donald E. Moore,','Donald E. Moore III,')
slides=[]
def figure(k,name,num,desc):return {'kind':'article','path':f'figures/{name}.png','caption':f'{cites[k]}, Fig. {num}. {desc}','source_url':'https://doi.org/'+dois[k]}
def add(title,k,name,num,desc,text,note,extra=None):
 ps=text.strip().split('\n\n');assert len(ps)==3,(title,len(ps));ks=[k]+(extra or []);tr=[re.sub(r'\*\*|_', '',p) for p in ps];tr.append(note)
 slides.append({'title':title,'layout':'figure-left' if len(slides)%4==2 else 'figure-right','body':ps,'figure':figure(k,name,num,desc),'cite':'; '.join(cites[q] for q in ks),'refs':[refs[q] for q in ks],'transcript':tr})
add('Stereotypy redirects the daily behavioral repertoire','stereotypy','stereo_budget','1','Daytime and nighttime active behavior budgets.', '''**Stereotypy** is repetitive, relatively invariant behavior without an apparent immediate goal, such as swaying or repeated pacing. Greco and colleagues measured these patterns in zoo-housed African and Asian elephants alongside feeding, locomotion, social contact and self-maintenance.

Observers recorded behavior during unmanaged periods, separating the elephants’ spontaneous activity from actions requested by caretakers. Daytime and nighttime observations also separated responses to different daily opportunities, rather than treating a short daytime visit as a complete behavioral record.

Stereotypic movement occupies time that could otherwise support a varied behavioral repertoire. Its interpretation depends on when it occurs, the individual’s history and available opportunities. Comparing active-time budgets places repetitive behavior alongside feeding and social activity, linking welfare assessment to the animal’s actual daily experience.''', 'Neuroethics connects decisions about care with the conditions experienced by an animal. Here, behavior supplies an observable starting point for evaluating the consequences of those conditions.')
add('Individuals differ sharply in repetitive movement','stereotypy','stereo_day','5','Individual daytime stereotypic behavior rates.', '''The elephant survey measured **active-time stereotypy**, the proportion of time spent performing repetitive behavior after inactive observations were excluded. The published daytime average was 15.5% of active time; among performers, individual values spanned 0.5–68.1%.

The nighttime average was 24.8%; performers ranged from 1.4–74.2%. The broad distributions mean that a herd average can conceal an individual spending much of its active period in repetitive movement. An elephant’s own record is therefore central to monitoring change.

Daytime and nighttime conditions differed in staff presence, feeding and access arrangements. The study’s individual-level measures connected these lived conditions to behavioral rates. An assessment based on repeated observations can identify whether a management change alters an individual’s repertoire rather than merely changing a group mean.''', 'The reported percentages describe active time, not a percentage of the entire 24-hour day. That denominator matters when comparing an active elephant with one resting for long periods.')
add('Social separation predicts higher stereotypy','stereotypy','stereo_alone','7','Modeled stereotypy risk with time housed separately.', '''**Social separation** was quantified as the proportion of an elephant’s time housed without other elephants. Greco and colleagues found that more separately housed time predicted higher daytime stereotypic behavior rates after accounting for other retained social and life-history variables.

Measuring each elephant’s exposure distinguished its experience from a zoo’s total herd size. A facility can contain several elephants while particular individuals spend substantial periods alone. The relevant biological opportunity is access to compatible partners during the animal’s own day.

The authors hypothesized that restricted social opportunities contribute to repetitive behavior through frustration or altered social experience. The association supports examining separation schedules together with behavior records. Compatible contact supplies opportunities for investigation, touch and interaction that the simple presence of other elephants elsewhere cannot provide.''', 'These were observational comparisons across existing management arrangements. The useful management variable was the individual’s actual exposure to separation, rather than the number of elephants owned by the institution.')
add('Juvenile contact expands social opportunities','stereotypy','stereo_young','8','Modeled stereotypy risk with juvenile contact.', '''Time spent with juvenile elephants predicted lower daytime stereotypic behavior rates in the North American zoo survey. **Juveniles** are young animals beyond the earliest infant stage whose play, exploration and interactions contribute to the social activity of a herd.

The analysis considered juvenile contact together with separate housing, managed activities and transfer history. This distinguished one kind of social exposure from simply placing an animal in any group. Adult social experience can change when a developing calf introduces new patterns of interaction.

The authors proposed play and participation in calf-related activities as potential contributions to the association. Habitat observations in a separate Asian elephant study documented changing proximity and interactions as a calf and juvenile male matured. Social opportunities have biological content determined by partner identity and developmental stage.''', 'The result concerns access to juveniles within existing herds. It supports attention to the composition of social opportunities rather than treating every encounter with another elephant as equivalent.')
add('Transfer history accompanies persistent stereotypy','stereotypy','stereo_transfer','10','Daytime stereotypy risk and inter-zoo transfers.', '''An **inter-zoo transfer** changes an elephant’s location and can also change its social partners, caretakers, feeding arrangements and daily routines. Greco and colleagues counted lifetime transfers and found that more transfers predicted higher stereotypic behavior rates.

Transfer history appeared in both the daytime and nighttime models. It connected an earlier life-history variable with behavior recorded during current housing, while social exposure and management variables described present conditions. The study therefore linked pathology to experience extending beyond one observation period.

The authors hypothesized that separation from familiar partners and adjustment to unfamiliar conditions contribute to the association. Monitoring before and after a move can distinguish an immediate response from a persistent change. Maintaining compatible relationships addresses the social component of a transfer as well as the transport event itself.''', 'A transfer combines several changes. The reported relationship motivates documenting social continuity and later behavior, rather than treating travel distance as the only relevant feature of relocation.')
add('Choice changes access to usable environments','stereotypy','stereo_choice','12','Nighttime stereotypy risk and indoor/outdoor choice.', '''**Indoor/outdoor choice** means that an elephant can move between available areas rather than having its location determined entirely by a closed gate. More time with this choice predicted lower nighttime stereotypic behavior rates in the zoo survey.

The measure described access experienced by an individual, not simply the total area of an exhibit. Open access can allow movement between thermal conditions, resting surfaces and social settings. The association connects a management arrangement with opportunities for self-directed behavior.

Brown and colleagues also associated greater indoor/outdoor choice with lower glucocorticoid measures in species-specific zoo analyses. Behavioral flexibility and endocrine activity provide complementary outcomes for evaluating access. Useful choice depends on both alternatives being available and suitable for the animal at the time it uses them.''', 'The endocrine study measured fecal hormone metabolites over repeated sampling periods. Its agreement with a behavioral association strengthens the rationale for examining access while retaining the different meanings of the two measurements.', ['risk'])
add('Social conflict increases self-directed actions','selfdirected','sdb_events','1(A–B)','Self-directed actions before and after aggression.', '''**Self-directed behavior** includes actions directed toward the elephant’s own body, such as mouth touching, head shaking, dust bathing and curling the trunk inward. Vilela and colleagues compared these actions in captive Asian elephants after aggression and during baseline observations.

The post-conflict context was associated with an estimated 39.8% increase in expected event counts. Comparing a victim’s behavior across contexts linked the response to a recent social event rather than interpreting every self-touch as a sign of distress.

Mouth touching, head shaking, dust bathing and inward trunk curling contributed prominently to the difference. These actions offer a rapid behavioral record after conflict, complementing slower endocrine measures. An observer can connect the initiating interaction with the subsequent pattern of bodily activity over a defined interval.''', 'A self-directed action can occur during ordinary body care. Its value as an indicator comes from systematic change following a social event, compared with the same animal’s ordinary behavior.')
add('Event counts and durations describe different responses','selfdirected','sdb_context','2(A–B)','Context effects on event and state behaviors.', '''Vilela and colleagues separated **event behaviors**, counted as discrete occurrences, from **state behaviors**, recorded by the proportion of time occupied. A brief head shake and a prolonged trunk position therefore contributed different kinds of information.

Post-conflict increases were clearer for counted events than for the overall time spent in state behaviors. The distinction prevented a long-lasting posture from being treated as interchangeable with several short actions and clarified which components responded most strongly to aggression.

Matching the measurement to the action is central to behavioral physiology. Counts capture the repeated initiation of an action; durations capture sustained occupation of a state. Together, they describe how an acute social challenge redistributes behavior rather than reducing the entire response to a single undifferentiated stress score.''', 'A behavioral definition specifies both what is counted and how it is timed. Clear definitions allow observations from different periods to be compared without changing the meaning of the recorded variable.')
add('Orientation toward an aggressor changes the response','selfdirected','sdb_attention','3','Self-directed actions and aggressor-directed trunk time.', '''After conflict, Asian elephants sometimes held the trunk oriented toward the aggressor. Vilela and colleagues quantified the time spent in this orientation and compared it with the rate of self-directed actions during the same post-conflict observations.

Higher self-directed behavior rates accompanied less time with the trunk directed toward the aggressor. This relationship connects two competing components of the response: bodily actions and sustained orientation toward a socially relevant individual.

The authors proposed that attention to the aggressor may suppress or compete with self-directed actions. That is a hypothesis about behavioral organization. Recording both responses preserves the biological sequence of conflict, orientation and subsequent action, providing a richer description than classifying the elephant as either stressed or unstressed.''', 'The observed negative relationship concerns the allocation of behavior in a post-conflict period. It gives the orientation behavior a defined social context and motivates tracking several responses together.')
add('Social history changes baseline behavior','selfdirected','sdb_history','4(A–B)','Individual behavior across changing social conditions.', '''Changes in group composition created different social conditions during the Asian elephant study. The researchers compared each individual’s baseline self-directed actions and stereotypy across these conditions while also recording aggression received from other elephants.

Two individuals increased baseline self-directed behavior when their victimization rates were highest, although the strength of the pattern differed between individuals. An elephant never observed receiving aggression maintained especially low self-directed behavior rates throughout the study.

Baseline behavior can therefore shift with the social environment against which a post-conflict response is judged. Self-directed actions and stereotypy also had different individual patterns. Repeated monitoring preserves this distinction between relatively immediate changes around conflict and persistent repetitive movement associated with a longer behavioral history.''', 'A baseline is a reference period, not an immutable characteristic of an animal. Social conditions can change it, so a useful comparison includes both individual identity and the conditions present during observation.')
add('Mouse CRH neurons coordinate stress responses','crh','pvn_cells','2(c)','Original mouse PVN CRH-neuron fluorescence; 50 µm bar.', '''The **paraventricular nucleus**, or PVN, is a hypothalamic population involved in endocrine stress responses. Füzesi and colleagues targeted mouse neurons producing **corticotropin-releasing hormone**, or CRH, a peptide that initiates pituitary signaling within the hypothalamic–pituitary–adrenal axis.

The pituitary releases adrenocorticotropic hormone, which stimulates adrenal glucocorticoid secretion. The study identified CRH cells with a genetic reporter and expressed light-sensitive proteins selectively within this population, permitting neuronal activity to be manipulated while behavior was recorded.

These mouse experiments separate a defined neuronal population from a general description of stress. The same identified cells contribute to behavioral organization as well as hormonal output. Elephant studies measure downstream hormones and actions; the causal neuronal evidence presented here comes specifically from mice.''', 'The fluorescence image identifies the targeted mouse cells and the location of the experimental manipulation. The species distinction is essential when connecting a causal circuit experiment with noninvasive elephant observations.')
add('Neuronal inhibition redistributes post-stress behavior','crh','pvn_inhibition','2(a–d)','Optical inhibition reduces CRH-neuron firing.', '''Füzesi and colleagues expressed **archaerhodopsin**, a light-driven proton pump, in mouse PVN CRH neurons. Illumination moved positive charge out of the cell, hyperpolarizing its membrane and reducing action-potential firing. Brain-slice recordings verified the physiological effect before behavioral testing.

After footshock, the researchers inhibited these cells during 15 min of observation. Grooming fell from about 181 s in fluorescent-protein controls to 79 s in the inhibition group. Rearing and walking occupied a greater fraction of the remaining behavior.

Selective inhibition changed the allocation of actions after the same stress exposure. The control animals received the light protocol without the inhibitory pump, separating illumination from the targeted physiological manipulation. CRH-neuron activity thus contributes to organizing the post-stress repertoire rather than simply increasing every form of movement.''', 'Hyperpolarization moves membrane voltage away from the level required to trigger action potentials. The behavior comparison connects the verified reduction in firing with a change in grooming and exploration.')
add('Channel activation recruits hormonal and motor outputs','crh','pvn_activation','3(a–e)','Mouse CRH-neuron activation and corticosterone output.', '''**Channelrhodopsin-2** is a light-gated cation channel: blue illumination opens an inward-current pathway that depolarizes neurons. Füzesi and colleagues expressed it in mouse PVN CRH cells and verified that optical stimulation controlled their activity in brain slices.

Activation increased circulating **corticosterone**, the glucocorticoid measured in these mice, 15 min after stimulation began. The mean increase was about 5.33 µg/dL in channel-expressing mice compared with 0.53 µg/dL in fluorescent-protein controls receiving the same illumination.

The activated cells also promoted grooming in a familiar observation chamber without preceding footshock. In a separate footshock experiment, reducing corticosterone synthesis with metyrapone left stress-induced grooming present. Hormonal secretion and rapid behavioral control can therefore emerge as distinct outputs of the same stress-related neuronal population.''', 'Metyrapone interferes with adrenal steroid synthesis. The preserved grooming response provides a specific mechanistic distinction: post-footshock grooming persisted when corticosterone synthesis was inhibited.')
add('PVN projections excite lateral hypothalamic neurons','crh','lh_projection','4(f)','Recorded mouse LH cell and labeled CRH axons; 50 µm bar.', '''The **lateral hypothalamus**, or LH, receives axons from the mouse PVN CRH population. Füzesi and colleagues recorded LH neurons while stimulating these axons, connecting an identified anatomical projection with a measurable synaptic response.

Light pulses elicited inward currents with an average onset latency of about 4.7 ms. Tetrodotoxin, which blocks voltage-gated sodium channels and action potentials, abolished the response. Adding 4-aminopyridine, a potassium-channel blocker that enhances terminal excitation, partially restored it during longer light pulses.

The pharmacological sequence supported a direct excitatory connection from the labeled axons. Responses survived picrotoxin, a GABA receptor antagonist, but were strongly reduced by DNQX, an AMPA/kainate glutamate-receptor antagonist. Glutamatergic synaptic transmission supplies a rapid route from stress-related PVN activity to hypothalamic behavioral control.''', 'The anatomical image contains the recorded cell and labeled incoming fibers. Sodium-channel block followed by restored terminal release is a standard way to distinguish a direct connection from a response requiring an intervening spiking neuron.')
add('Environmental context gates stress-related actions','crh','pvn_context','6(a–f)','Optically evoked mouse grooming in different contexts.', '''The same CRH-neuron activation produced different amounts of mouse grooming in different environments. Füzesi and colleagues used identical 10-Hz stimulation for 5 min in a familiar chamber, a novel environment and the chamber associated with footshock.

Grooming increased during activation in both unfamiliar settings, but the response was smaller in the footshock chamber. In the novel environment, channel-expressing mice groomed for about 85 s compared with 9 s in controls; in the footshock chamber the corresponding values were about 40 and 6 s.

Neuronal activity interacts with the behavioral opportunities and threat cues supplied by the environment. Stress-related action is consequently context dependent even when stimulation is held constant. This experimentally controlled comparison explains why the location and recent social circumstances of an elephant matter when interpreting a repeated action.''', 'The mouse results provide a causal example of contextual gating. The elephant comparisons concern naturally changing environments, where the relevant information must be recorded rather than imposed through an experimental light protocol.')
add('Fecal metabolites integrate earlier adrenal activity','males','male_fgm','3','Hormone metabolites before and 48 h after interaction.', '''**Fecal glucocorticoid metabolites**, or fGCMs, are products of glucocorticoid metabolism excreted in dung. They provide a noninvasive measure of earlier adrenal activity, integrating secretion and passage through the digestive system rather than recording the instant of observation.

López Pérez and colleagues sampled Asian male elephants before social introductions and 48 h afterward. Pairing samples with a defined interaction period connected the delayed physiological record with observed affiliative and aggressive behavior during the introduction.

Individual concentrations varied substantially, and the before–after comparisons did not reveal an overall increase for each male. Behavioral adjustments during introductions can therefore coexist with relatively stable delayed hormone measurements. Sampling schedules and an individual reference record determine which temporal component of the response is captured.''', 'The same hormone label does not guarantee interchangeable measurements across studies. Assay antibodies, extraction methods, wet or dry mass, and sampling intervals determine what a reported concentration means.')
add('Festival conditions alter adrenal measurements','sampling','festival','3','Metabolites during rehearsal and the festival procession.', '''Kumar and colleagues collected dung from Asian elephants in Indian facilities, including animals participating in the Dussehra festival. Rehearsal and the final procession provided distinct working contexts that could be linked with noninvasive glucocorticoid measurements.

Elephants on the festival procession day had higher metabolite concentrations than those sampled during rehearsal and at Mysore Zoo. Across the Dussehra observations, more working hours and greater carried weight accompanied higher concentrations, connecting the physiological response with features of the activity.

The same study examined body condition, age, sex and origin because these characteristics influenced the measurement within facilities. A context-specific record can distinguish the demands of a particular event from an animal’s ordinary range. Repeated measures around predictable activities support adjustments to workload and recovery opportunities.''', 'The study compared specific conditions rather than assigning all human-associated activities the same biological meaning. Recording workload alongside samples makes the event-related endocrine pattern interpretable.')
add('Seasonality shifts the endocrine reference range','seasonal','seasonal_markers','2(A–C)','Seasonal hormone, immune-cell and body-weight patterns.', '''In semi-captive Asian elephants in Myanmar, Ukonaho and colleagues measured fecal cortisol metabolites across cold, hot and monsoon seasons. **Seasonality** changes food availability, weather and energetic demands, supplying a physiological context for interpreting adrenal activity.

Predicted concentrations were approximately 101 ng/g in the cold season, 86 ng/g in the hot season and 81 ng/g during monsoon. The cold-to-monsoon decline was about 20%, despite the expectation that the hottest conditions might produce the greatest endocrine response.

Repeated sampling allowed seasonal patterns to be separated from individual identity and sampling location. The elephants were not performing work tasks during sampling. A reference range tied to season preserves naturally occurring variation, so an assessment compares a management-related change with the environmental conditions present at the time.''', 'The study treated season as a biological exposure rather than background noise. Food availability and temperature can influence the same endocrine measurements used in a welfare assessment.')
add('Immune-cell ratios complement hormone measurements','seasonal','seasonal_markers','2(A–C)','Seasonal changes in multiple physiological measures.', '''A **heterophil-to-lymphocyte ratio** compares two classes of circulating white blood cells and supplies another measure associated with physiological stress. Ukonaho and colleagues counted these cells in blood smears alongside hormone, body-weight and oxidative-balance measurements.

The ratio averaged approximately 1.16 in the cold season, 0.94 in the hot season and 1.00 during monsoon. Fecal cortisol metabolites were lowest during monsoon, whereas the immune-cell ratio was lowest in the hot season. The two measures followed related but distinct seasonal patterns.

The oxidative markers also lacked the same seasonal response, and body weight declined in the hot season. Several measurements therefore describe different components of the elephant’s adjustment. Integrating endocrine, immune and nutritional information gives a physiological account of changing conditions instead of treating one marker as the entire stress response.''', 'Heterophils and lymphocytes are cell populations, whereas fecal metabolites are chemical products of hormone processing. Their distinct response patterns arise from measuring different biological processes.')
add('Habitat complexity creates functional opportunities','habitat','habitat_map','2','Original map of the expanded elephant habitat.', '''**Environmental complexity** includes the distribution and variety of resources an elephant can use, not just enclosure area. Glaeser and colleagues followed Asian elephants across an older habitat, construction and a new habitat with more distributed feeding, pools and manipulable features.

The new setting expanded opportunities to choose indoor or outdoor areas and to seek food at different locations. Most months allowed more than 20 h of outdoor access per day, while individuals actually chose roughly 6–20 h outside according to their own activity and conditions.

Available space and used space are different biological quantities. Distributed resources link movement to a goal, such as locating browse or reaching an overhead feeder. The resulting choices provide a mechanism by which habitat design changes sensory investigation, locomotion, foraging and social contact during the elephant’s day.''', 'A habitat map locates the resources and routes that structure behavior. Its instructional value is the relationship between resource distribution and the actions required to obtain or use those resources.')
add('GPS tracks reveal goal-directed habitat use','habitat','habitat_gps','4(a–d)','Published GPS tracks across seasons and individuals.', '''Glaeser and colleagues fitted elephants with GPS bracelets to record outdoor movement. **GPS tracking** estimates successive locations, allowing routes and distances to be compared with the placement of food, pools, dirt mounds and other habitat resources.

The recorded elephants used the full outdoor habitat rather than consistently remaining within one small preferred area. Tracks across seasons documented access to different resources under contrasting weather conditions, connecting enclosure design with the places actually visited by each elephant.

The movement record was combined with direct observations of behavior. Distributed and varied food sources encouraged searching across the habitat, while larger pools added water-related activity. Measuring routes together with their behavioral context distinguishes functional exploration from simply assuming that every additional meter represents a favorable change.''', 'GPS recorded outdoor locations; movement within the indoor habitat was additional. Combining location data with observed actions gives the route a biological meaning and identifies what the elephant was doing while moving.')
add('More usable habitat changes walking individually','habitat','habitat_walk','3','Walking distances before and after habitat expansion.', '''After habitat expansion, one adult female’s mean daily outdoor walking distance increased from 7.6 to 15.4 km. A second female already walked longer distances and changed from 17.3 to 17.6 km per day. Glaeser and colleagues therefore documented markedly different individual responses.

Removing estimated locomotor stereotypy from the distance record retained the first female’s increase, from 7.3 to 14.7 km. That comparison separated added functional movement from repeated pacing that could inflate a distance total without expanding the behavioral repertoire.

An intervention can change the opportunities most relevant to one individual while producing a smaller distance change in another. Resource access, prior movement and the form of locomotion determine the interpretation. Tracking each elephant before and after habitat change preserves these differences instead of judging success solely by a herd-wide walking target.''', 'The numerical comparison uses outdoor GPS measurements from both habitats. Stereotypic locomotion was considered separately because repeated movement along one route has a different functional context from movement among resources.')
add('Construction and adaptation alter adrenal patterns','habitat','habitat_fgm','5(a–d)','Individual fecal hormone distributions across habitat phases.', '''The habitat study collected repeated fecal glucocorticoid measurements before, during and after construction. Each phase combined physical changes with different routines and opportunities, allowing physiological patterns to be compared within the same Asian elephants.

Several individuals had their highest concentrations and greatest variability during construction, followed by lower values in the new habitat. One adult female retained relatively elevated concentrations after the move, although her values declined immediately after introductions to new habitat areas.

Individual time courses reveal adaptation that a single pre–post sample would miss. Construction, introduction and established use of a habitat are distinct exposures. Linking endocrine records with behavior and resource use captures the transition from a changing environment to an environment the elephant can actively explore and use.''', 'A higher concentration during a transition can reflect increased adrenal activity during adjustment. The subsequent trajectory and accompanying behavior supply the context for evaluating that response.')
add('Resource changes redistribute the activity budget','habitat','habitat_budget','6(a–f)','Behavior budgets in the previous and expanded habitats.', '''An **activity budget** records how an animal allocates time among defined actions. Glaeser and colleagues compared feeding, locomotion, exploration, social behavior and repetitive activity across the previous and new Asian elephant habitats.

The new habitat increased food-seeking opportunities through diverse feeding locations and devices. Repetitive behavior persisted at low rates in two females, with a decrease in frequency in one and a changed bout pattern in the other. The authors connected these patterns with independent foraging opportunities.

A changed budget describes the replacement of one pattern with other available actions. Seeking food recruits movement, trunk investigation and manipulation, whereas a predictable delivery point can concentrate anticipation near one location. Resource design therefore links the sensory and motor components of feeding with the time structure of daily behavior.''', 'The authors proposed a contribution from feeding anticipation in one female. Tracking when repetitive movement occurs and when independent food seeking begins helps distinguish anticipation from a uniformly expressed repetitive pattern.')
add('Social access permits proximity and separation choices','habitat','habitat_near','7','Proximity to herdmates across habitat conditions.', '''**Social proximity** records whether an elephant is near another individual, whereas interaction records what the animals do together. The expanded-habitat study measured both, preserving the distinction between occupying nearby space and engaging in social behavior.

Overall proximity declined in the new habitat while social interactions were sustained or increased. The calf and juvenile male also changed their nearest-neighbor patterns as they matured, linking the spatial record with development and partner identity.

Usable social space permits approaching a partner for interaction and moving away for another activity. Close spacing at all times is therefore different from access to compatible company. Combining proximity with the kind of interaction and developmental history explains how a complex habitat can support both affiliation and independent behavior.''', 'Social opportunity includes the ability to disengage. The paired measurements prevent an increase in distance between animals from automatically being interpreted as a loss of social access.')
add('Affiliation and dominance organize a shared habitat','habitat','habitat_social','9','Functional social interaction types across habitats.', '''**Affiliative behavior** consists of nonaggressive social actions, while **agonistic behavior** includes interactions that establish or challenge dominance. Glaeser and colleagues classified the functions of observed interactions rather than counting every encounter as the same social event.

Affiliative interactions predominated in both habitats. A maturing juvenile male changed his interaction pattern, including more dominance-related actions, while an adult female increased affiliation and reduced agonistic interactions with some partners in the new setting.

These patterns connect the social environment with changing developmental roles. A shared resource can be used cooperatively, accessed in parallel or contested. Identifying the partners and function of an interaction reveals whether habitat opportunities support ordinary social organization or repeatedly expose an individual to unwanted conflict.''', 'Dominance-related behavior can regulate relationships without escalating to severe aggression. An ethogram that distinguishes function allows changes in group composition to be interpreted in the context of normal development.')
add('Distributed feeding engages movement and manipulation','habitat','habitat_resources','10','Interactions with feeding resources and habitat features.', '''Interactions with food-delivery resources comprised 31.5% of recorded resource interactions in the previous habitat and 83.0% in the new habitat. Overhead and timed feeders required Asian elephants to locate food and manipulate resources instead of relying on one delivery point.

Elephants pushed or moved logs and stumps beneath overhead feeders and stood on them to increase reach. Food access thus linked sensory investigation with problem solving and whole-body movement, using the trunk and other motor actions within a practical foraging sequence.

Shared resource interactions increased from 10.5% to 22.9%. Feeding opportunities consequently changed both individual activity and the social setting of resource use. The intervention’s functional content was the behavior made possible by the resources, including searching, reaching, moving objects and feeding near compatible partners.''', 'The percentages refer to recorded resource interactions, not all hours of the day. Their change identifies which resources became central to activity and how frequently resource use occurred in a social context.')
add('Continuous cameras extend the behavioral record','activity','cameras','1','Original monitoring-camera locations in the habitat.', '''Fazio and colleagues used closed-circuit cameras, camera traps and direct observation software to monitor zoo-housed Asian elephants. Cameras covered indoor and outdoor areas, extending observation into periods when staff and visitors were absent.

Thirty-minute focal observations were compared with interval sampling across 24 h. **Focal sampling** follows a particular animal for a defined period; **interval sampling** records behavior at repeated scheduled points. The two methods supplied different temporal coverage of the same herd.

Monitoring connected each action with location, time and social partners. This made nighttime rest, indoor stereotypy and preferred resting areas observable alongside daytime feeding. A care decision based on the resulting record can address conditions present during the full daily cycle rather than relying only on behavior visible during staffed hours.''', 'Camera placement determines which spaces and actions are observable. The published habitat map documents this coverage and provides the spatial context for interpreting the recorded behavior.')
add('Sampling methods preserve different behavioral details','activity','cameras_compare','3(a–b)','Stereotypy and sleep measured by two observation methods.', '''The camera study compared combined stereotypy and sleep measures from 30-min focal observations with 24-h interval sampling. Its **sleep category** combined standing rest and recumbence as operationally recorded behaviors rather than recording brain activity directly.

Average stereotypy occupied about 10.6% of focal observations and 9.8% of interval observations. The corresponding sleep-category values were about 19.3% and 18.2%. Both methods retained important individual differences in these combined categories.

Feeding was observed more frequently during focal sampling, whereas walking was more frequent in the interval record. Sampling design therefore changes which portions of a behavioral sequence are represented. Comparing methods identifies dependable broad patterns while preserving the additional detail supplied by following one animal continuously.''', 'These percentages are proportions of recorded observations. The operational sleep category describes observable rest behavior; an electroencephalographic sleep stage was not measured in this study.')
add('Daily schedules shape stereotypy and rest','activity','cameras_daily','5(a–d)','Hourly feeding, walking, sleep and stereotypy.', '''Hourly camera records separated daytime activity from nighttime rest in the Asian elephant herd. Feeding occurred mainly between 07:00 and 20:00, while the operational sleep category was concentrated between 20:00 and 06:00.

Stereotypic behavior was least common during much of the period from 15:00 to 05:00, encompassing afternoon feeding and sleep. A midday increase coincided with staff lunch breaks and anticipation of later care activities, connecting repetitive movement with the daily timing of expected events.

Behavioral pathology has a temporal setting. Changing food availability or predictable routines can affect particular hours even if a daily average changes little. An hourly record preserves the relation among feeding, staff presence, rest and repetitive movement so that interventions can target the conditions surrounding the action.''', 'Anticipation was an interpretation based on the alignment between behavior and the care schedule. The directly recorded finding was a repeated hourly pattern of activity across observations.')
add('Preferred resting places identify usable space','activity','sleep_locations','9(b)','Original recumbence-location heat map.', '''Fazio and colleagues linked recumbence observations with specific areas of the elephant habitat. **Recumbence** means lying down, distinguishing a body position from standing rest and enabling preferred resting locations to be mapped.

The bull elephant used a restricted set of resting locations, including an indoor suite and particular outdoor areas. Both the 24-h record and the focal-observation heat map identified these preferences, connecting the same behavior with the spatial environment using different sampling methods.

Preferred locations reveal which portions of available space actually support rest. The herd also used adjacent, largely separate resting areas rather than occupying every area equally. Preserving access to these locations supports the animal’s own spatial choices, while monitoring changes can identify when a previously used resting site becomes less usable.''', 'The colors in the heat map are the authors’ original representation of observed location frequency. The map is a published figure, not a new reconstruction of the spatial data.')
add('Species differ in recumbent rest duration','rest','rest_species','1','Individual daily recumbence in African and Asian elephants.', '''Holdgate and colleagues used leg-mounted accelerometers to measure recumbence in zoo elephants. **Accelerometry** records changes in movement and orientation, allowing lying posture to be identified over periods that include nighttime.

African elephants averaged 2.1 h of recumbence per day, whereas Asian elephants averaged 3.2 h. Both species averaged about 3.1 nighttime bouts, but African bouts lasted roughly 39 min compared with 66 min in Asian elephants.

The species difference arose substantially through bout duration rather than a greater number of bouts. Recording both frequency and duration preserves that organization of rest. Individual daily records further reveal whether an elephant rests in short episodes, long episodes or very little recumbence under the current housing conditions.''', 'A posture measurement describes recumbent rest. Standing rest can occur outside those bouts, so the recumbence total is interpreted together with other behavioral measures rather than equated with all sleep.')
add('Rest patterns vary within the same individual','rest','rest_individual','2(a–b)','Five-day standing and recumbence sequences.', '''Repeated accelerometer measurements recorded the sequence of standing and lying over several days. Holdgate and colleagues found elephants that lay down little throughout the recording period and others that omitted recumbence on only one or two days.

Seven animals were classified as highly non-recumbent because total lying time was less than 1 h across five days. Other individuals showed intermittent non-recumbence. These patterns describe different temporal organizations that would be obscured by a single average daily duration.

Day-by-day records can relate a changed rest pattern to flooring, outdoor access, social arrangements or health. A repeated absence of lying and a single non-recumbent night prompt different questions about the animal’s opportunity to rest. Continuous observation therefore preserves the behavioral history needed to identify a meaningful change.''', 'The published examples happen to include a non-recumbent day in both species. They provide individual sequences rather than a claim that every elephant follows the same five-day rhythm.')
add('Resting surfaces influence recumbent opportunity','rest','rest_daily','3','Hourly recumbence profiles across elephant species.', '''Recumbence in the zoo study rose after 20:00 and peaked near 04:00, linking lying behavior with nighttime housing. Holdgate and colleagues then examined how experienced substrates and outdoor access were associated with the amount of rest.

African elephants spending any time on entirely hard concrete or stone aggregate substrates were recumbent about 0.6 h less per day. Asian elephants spending time on entirely soft grass, sand or rubber substrates were recumbent about 1.1 h more per day.

The surface supporting the body is therefore a functional part of the resting environment. Assessing nighttime access alongside the hourly profile identifies whether suitable surfaces are available when the animal normally lies down. Species-specific associations also support monitoring the elephant’s actual response rather than imposing one identical rest target on every individual.''', 'These flooring relationships came from multivariable observational analyses. The recorded daily rhythm explains why substrate availability during the nighttime period is biologically relevant.')
add('Male introductions can support predominantly affiliation','males','male_social','1','Behavioral rates during staged male introductions.', '''López Pérez and colleagues introduced Asian male elephants through limited tactile contact before full physical interaction. **Limited contact** allowed interaction across a barrier, providing a staged transition before animals shared unrestricted space.

Affiliative behavior predominated during both phases. Aggression was initially absent in the limited-contact phase and remained relatively infrequent; during full introductions it declined over time. Submissive behavior also remained uncommon across the recorded periods.

The sequence documents social opportunities beyond permanent separate housing of males. Staging the introductions allowed caretakers to observe how relationships developed before increasing physical access. Behavioral records of affiliation, aggression and submission supplied information about the actual social consequences of each phase rather than assuming compatibility from sex alone.''', 'The introduction procedure was carried out in a semi-captive facility in Lao PDR. Monitoring individual interactions was part of evaluating the consequences of increasingly direct social access.')
add('Individuals follow different socialization trajectories','males','male_individual','2','Individual affiliation and aggression across introduction days.', '''Although affiliation predominated in the male group, individual trajectories differed. López Pérez and colleagues recorded which male initiated each action and how rates changed across days of limited and full-contact introductions.

Several males reduced affiliation as the introductions progressed, while others increased it during full physical contact. Two males never initiated aggression during the study. The group pattern therefore contained distinct responses that mattered for evaluating particular relationships.

Repeated individual observation can guide the timing and partners of social access. A decreasing interaction rate may accompany an established relationship rather than worsening welfare, while repeated unwanted aggression has a different meaning. The function, recipient and timing of an action preserve the social biology underlying the numerical rate.''', 'A rate alone omits partner identity and interaction function. The published individual plots allow social adjustment to be followed without treating every male as an interchangeable member of the group.')
add('Androgen measurements add reproductive context','males','male_androgen','4','Fecal androgen measures before and after social interaction.', '''**Androgens** are steroid hormones involved in male reproductive physiology. López Pérez and colleagues measured fecal androgen metabolites alongside glucocorticoid metabolites to examine social introductions within the males’ endocrine context.

Most males retained comparable androgen concentrations before and 48 h after introductions, while one showed a decrease. Concentrations varied substantially among individuals, and age also influenced the pattern of androgen change during full-contact introductions.

Reproductive physiology and social behavior must be interpreted together. A male’s affiliation, aggression and hormone record supply different information about the interaction period. Tracking them jointly retains individual reproductive context while allowing care decisions to respond to directly observed behavior and the development of compatible social relationships.''', 'Fecal androgen metabolites and fecal glucocorticoid metabolites measure different endocrine systems. Their paired collection does not turn them into interchangeable indicators of welfare or aggression.')
add('Age mates accompany lower glucocorticoid levels','orphans','orphan_social','2','Social and environmental predictors in wild young elephants.', '''Parker and colleagues monitored wild young African elephants, including orphans and nonorphans, using repeated dung samples and known family composition. **Social support** was examined through available age mates and adult female caregivers rather than inferred from group membership alone.

More age mates accompanied lower average glucocorticoid metabolite concentrations. Orphan status itself showed no simple relationship with the measured concentrations, while individuals joining non-natal groups had lower average values than those remaining with their natal family.

The social context surrounding loss is biologically informative. Peer access can coexist with opportunities for affiliation and shared activity, and family history changes what a group represents for an individual. These field observations support considering partner composition when managing young elephants whose normal developmental relationships have been interrupted.''', 'The non-natal-group result describes the measured hormone pattern in this field sample. The authors discussed possible changes in stress-axis regulation, so low hormone values alone are not assigned a single emotional meaning.')
add('Resource conditions shape wild endocrine variation','orphans','orphan_season','3','Vegetation conditions and individual hormone time courses.', '''The wild orphan study measured vegetation with a **normalized difference vegetation index**, a satellite-based measure of landscape greenness used as a proxy for plant productivity. It linked changing resource conditions with repeated glucocorticoid measurements from known elephants.

Greener landscapes accompanied lower metabolite concentrations, whereas more patchily distributed vegetation accompanied higher concentrations. Individual hormone time courses followed environmental changes even among elephants in the same family group.

Food conditions therefore influence an endocrine measure also associated with social experience. Captive assessments likewise benefit from recording seasonal resources, diet and individual sampling history. A physiological measurement becomes informative through its relationship with the biological conditions experienced before the dung sample was collected.''', 'The study separated relatively stable individual characteristics from variables changing at each sample. Resource availability belonged to the time-varying level, making it possible to follow environmental changes within an individual record.')
add('Dietary restriction accompanies microbial diversity loss','gut','gut_diversity','1(A–D)','Gut microbial diversity across elephant lifestyles.', '''Zhang and colleagues compared Asian elephants across completely captive, semi-captive, semi-wild and wild lifestyles. They sampled fecal bacterial communities using **16S rRNA gene sequencing**, which identifies bacterial groups from a conserved ribosomal gene.

Completely captive elephants received three principal food types, whereas wild elephants foraged approximately 112 plant species. Bacterial richness, diversity and evenness generally increased toward the wild end of the lifestyle gradient, connecting diet and living conditions with the intestinal ecosystem.

A varied foraging environment supplies different substrates to microbes as well as different sensory and motor opportunities to the elephant. Microbial **richness** concerns the number of detected groups, while **evenness** describes how balanced their abundances are. Both contribute to explaining why a restricted diet can produce a different community structure.''', 'Diet, environment and lifestyle covaried in this comparison. The study provides direct elephant microbiome evidence, while the proposed links from microbiota to neural state require a different kind of experiment.')
add('Captivity changes the composition of the gut community','gut','gut_composition','3(A–B)','Bacterial phylum and family composition across lifestyles.', '''The elephant microbiome study compared bacterial composition as well as diversity. **Community composition** identifies which microbial groups are present and their relative abundances, distinguishing a change in the number of groups from a change in their identities.

The completely captive and more free-foraging lifestyles differed in families associated with the intestinal community. Ruminococcaceae showed a decreasing trend from wild to completely captive conditions, while other groups were associated with the high-fiber captive diets.

The elephant’s diet and microbial habitat form a connected biological system. Changing food variety can change the resources available to bacteria even when the total amount of food is adequate. Evaluating nutritional management therefore includes forage composition and diversity alongside body condition and observed feeding behavior.''', 'The bars are relative abundances: a larger share for one group can accompany a smaller share for another. They describe community structure rather than an absolute count of every bacterium in the intestine.')
add('Microbial functional genes vary with lifestyle','gut','gut_function','6(A–C)','Published bacterial heat map and functional-gene measures.', '''Zhang and colleagues examined bacterial groups associated with **butyrate**, a short-chain fatty acid produced during microbial fermentation. They also measured the relative expression of a gene encoding butyryl-CoA:acetate CoA transferase, an enzyme involved in butyrate production.

The gene-expression pattern differed across lifestyles, with higher levels in semi-captive and semi-wild elephants than in completely captive and wild groups. The functional comparison therefore did not follow a simple ordering in which every measured feature increased with freedom from captivity.

Gene expression links the community record with a specific microbial process, adding information beyond taxonomy. The study’s authors proposed physiological consequences of altered fermentation. The measured elephant findings concern bacteria and functional genes; a microbiome-driven neural mechanism remains a hypothesis rather than an observed cause of stereotypy.''', 'The authors used a ribosomal gene as an internal reference for the expression measurements. Butyrate production is a microbial biochemical process, and its proposed downstream effects are distinct from the measured expression pattern.')
add('Reintegration produces a changing physiological trajectory','reintegration','release_phases','2(a–c)','Stress-related measures across phases of release.', '''Pretorius and colleagues followed African elephants through a transition from captive safari use to free living. The phases included ending rides, stabling, holding in a boma, initial release and later adaptation, allowing physiological and behavioral changes to be followed over time.

Temporal gland secretion and group-level disturbance-related behavior increased during initial release. Glucocorticoid metabolite concentrations rose later in the first year and declined by the third year toward pre-release levels. The indicators responded on different temporal scales.

Adaptation is a trajectory rather than a single moment. Measuring several phases captures initial disturbance and subsequent adjustment while preserving the delayed endocrine response. An intervention directed at welfare can therefore be evaluated through the sequence of outcomes experienced by the elephants, including the conditions supporting their longer-term transition.''', 'The field study tracked the same group through changing conditions. Its phased record is especially useful because immediate behavioral responses and delayed fecal measures do not necessarily reach their peaks together.')
add('Welfare decisions depend on several lived outcomes','reintegration','release_change','1(a–c)','Physiological and stereotypy changes following release.', '''Stereotypic behavior occurred during the ridden and stable phases of the African elephant reintegration study but ceased during subsequent phases. Average glucocorticoid values before and three months after release were comparable, while temporal gland secretion increased after release.

These outcomes capture different consequences of the same transition: repetitive movement disappeared, immediate arousal-related secretion changed and the broader endocrine trajectory developed over a longer period. Combining them connects management decisions with specific behavioral and physiological experiences.

An evidence-based neuroethical assessment weighs these lived outcomes together with nutrition, health, usable environment and social opportunities. The elephant welfare assessment developed by Ghimire and colleagues combined animal-based and resource-based measures. Such an approach directs intervention toward identifiable conditions and follows whether the elephant’s opportunities and observed state improve.''', 'Neuroethics applies biological evidence to decisions about an animal’s treatment. The ethical recommendation is to evaluate consequences with several relevant measures while keeping the animal’s individual experience central.', ['assessment'])
assert len(slides)==44,len(slides)
# Original anatomy remains visible beside the synaptic pharmacology.
old=slides[13].pop('figure');slides[13]['layout']='figures-right';slides[13]['primary_figure_height']=2.6;slides[13]['figures']=[old,figure('crh','lh_receptors','4(h–j)','Original LH recordings and glutamate-receptor blockade.')]
old=slides[11].pop('figure');slides[11]['layout']='figures-right';slides[11]['primary_figure_height']=2.4;slides[11]['figures']=[old,figure('crh','pvn_groom','2(f–h)','Grooming changes during CRH-neuron inhibition.')]
items=[('Stereotypy has an individual history.','Repeated movement depends on current opportunities, social exposure and prior transfers; record its timing and functional context.'),('Stress coordinates several outputs.','Mouse CRH neurons control endocrine and behavioral responses through distinct routes, including rapid glutamatergic hypothalamic transmission.'),('Endocrine measurements have a time scale.','Fecal metabolites integrate earlier secretion and are interpreted with season, sampling method and each elephant’s reference record.'),('Usable choice changes experience.','Distributed feeding, compatible social access and suitable resting surfaces support different actions and individual decisions.'),('Multiple outcomes describe adaptation.','Activity, recumbence, hormone patterns and social behavior can change differently during a habitat intervention or reintegration.'),('Neuroethical care follows lived outcomes.','Evaluate behavioral opportunities, nutrition, health and social conditions together, and follow each elephant’s response to an intervention.')]
spec={'lecture':52,'theme':'denim-ice','content_slides':44,'title_height':3.2,'title_image':figure('insight','title_elephant','1(B)','Asian elephant Kandula using a platform in the original study.'),'title_refs':[refs['insight']],'slides':slides,'takeaways':{'cite':'Greco et al. (2016); Füzesi et al. (2016); Pretorius et al. (2023)','refs':[refs[k] for k in years if any(refs[k] in s['refs'] for s in slides)],'items':[{'lead':a,'text':b} for a,b in items]}}
(base/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n');(base/'references.json').write_text(json.dumps(refs,indent=2,ensure_ascii=False)+'\n')
print('44 content slides; word range',min(len(' '.join(s['body']).split()) for s in slides),max(len(' '.join(s['body']).split()) for s in slides))
