import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
R={
'WK72':('Wine & Krasne (1972)','J. J. Wine; F. B. Krasne (1972). The Organization of Escape Behaviour in the Crayfish. Journal of Experimental Biology 56(1):1–18','10.1242/jeb.56.1.1'),
'E98':('Edwards et al. (1998)','D. H. Edwards; S.-R. Yeh; F. B. Krasne (1998). Neuronal coincidence detection by voltage-sensitive electrical synapses. Proceedings of the National Academy of Sciences USA 95(12):7145–7150','10.1073/pnas.95.12.7145'),
'H02':('Herberholz et al. (2002)','J. Herberholz; B. L. Antonsen; D. H. Edwards (2002). A lateral excitatory network in the escape circuit of crayfish. Journal of Neuroscience 22(20):9078–9085','10.1523/JNEUROSCI.22-20-09078.2002'),
'H11':('Herberholz et al. (2011)','J. Herberholz; S. H. Mishra; D. Uma; M. W. Germann; D. H. Edwards; K. Potter (2011). Non-invasive imaging of neuroanatomical structures and neural activation with high-resolution MRI. Frontiers in Behavioral Neuroscience 5:16','10.3389/fnbeh.2011.00016'),
'V97':('Vu et al. (1997)','E. T. Vu; A. Berkowitz; F. B. Krasne (1997). Postexcitatory inhibition of the crayfish lateral giant neuron: a mechanism for sensory temporal filtering. Journal of Neuroscience 17(22):8867–8879','10.1523/JNEUROSCI.17-22-08867.1997'),
'M18':('Swierzbinski & Herberholz (2018)','M. E. Swierzbinski; J. Herberholz (2018). Effects of ethanol on sensory inputs to the medial giant interneurons of crayfish. Frontiers in Physiology 9:448','10.3389/fphys.2018.00448'),
'F91':('Fraser & Heitler (1991)','K. Fraser; W. J. Heitler (1991). Photoinactivation of the crayfish segmental giant neuron reveals a direct giant-fiber to fast-flexor connection with a chemical component. Journal of Neuroscience 11(1):59–71','10.1523/JNEUROSCI.11-01-00059.1991'),
'E91':('Edwards et al. (1991)','D. H. Edwards; W. J. Heitler; E. M. Leise; R. A. Fricke (1991). Postsynaptic modulation of rectifying electrical synaptic inputs to the LG escape command neuron in crayfish. Journal of Neuroscience 11(7):2117–2129','10.1523/JNEUROSCI.11-07-02117.1991')}
def ref(k):return R[k][1]+'. https://doi.org/'+R[k][2]
def fig(k,name,n,cap):return {'path':'figures/'+name+'.png','caption':R[k][0]+', Fig. '+n+'. '+cap,'source_url':'https://doi.org/'+R[k][2]}
slides=[]
def add(title,k,name,n,cap,text,extra,anatomy=None):
 body=text.strip().split('\n\n');assert len(body)==3,(title,len(body));assert len(title)<=62,title
 s={'title':title,'layout':'figure-right','body':body,'transcript':[re.sub(r'\*\*|_', '',p)for p in body]+[extra],'cite':R[k][0],'refs':[ref(k)],'figure':fig(k,name,n,cap)}
 if anatomy:
  a=fig(*anatomy);s.update(layout='figures-right',figure_width=6.0,primary_figure_height=3.2,figures=[s.pop('figure'),a]);ak=anatomy[0]
  if ak!=k:s['refs'].append(ref(ak));s['cite']+='; '+R[ak][0]
 slides.append(s)
LG=('H02','H02_2B','2(B)','LG dendritic contacts with primary afferents; original 10 μm scale.')
MG=('M18','M18_1A','1(A)','Published anatomical arrangement of antenna II input and the MG neuron.')
add('Two giant pathways produce different escape trajectories','WK72','WK72_5','5','Original tracings of filmed lateral- and medial-giant tail flips.', '''A **tail flip** is a rapid abdominal flexion that propels a crayfish through water. Wine and Krasne studied _Procambarus clarkii_ with chronically implanted electrodes and high-speed film. The **lateral giant**, or LG, and **medial giant**, or MG, are large interneurons that recruit different escape movements.

An abdominal tap commonly activated LG and produced forward pitching with upward displacement. An anterior stimulus commonly activated MG and produced a backward dart. The published movement sequences retain frames approximately 10 ms apart, allowing the two trajectories to be compared with recorded giant-fiber activity.

The response depends on which circuit is recruited, rather than abdominal flexion having one obligatory direction. These experiments connected neural signals with freely moving behavior; they did not identify every synapse contributing to each appendage movement.''','An interneuron links other neurons within the nervous system. LG and MG are interneurons rather than the motor neurons whose axons directly leave the nervous system to innervate muscles.')
add('Implanted recordings identify the active giant pathway','WK72','WK72_2','2','Simultaneous connective and abdominal recordings of giant-fiber activity.', '''Wine and Krasne implanted pairs of 0.5 mm silver-ball electrodes near the nerve cord of crayfish 6–8 cm long. An **extracellular recording** measures voltage outside neurons and can detect passing action potentials. The animals subsequently moved freely while their escape responses were recorded.

Recordings from the anterior connectives and second abdominal segment separated descending MG activity from ascending LG activity. Spike polarity, relative amplitude, propagation direction, and escape trajectory provided converging identification criteria. Direct stimulation of visually identified giant fibers after behavioral testing checked the interpretation of the earlier records.

Giant spikes preceded major abdominal muscle potentials by about 2 ms. This timing supports a rapid neural-to-motor sequence, but an extracellular muscle potential is not itself the onset of body displacement. Ambiguous records were not treated as definitive evidence of pathway identity.''','An action potential is a regenerative electrical signal propagated along a neuronal membrane. The implanted leads allowed the investigators to relate such signals to behavior without assuming that every tail flip used a giant neuron.')
add('Abruptness recruits giants more reliably than intensity','WK72','WK72_4','4','Original distributions of giant-spike and nongiant muscle-response latency.', '''A **phasic stimulus** changes abruptly rather than remaining sustained or rising gradually. Wine and Krasne compared abdominal taps with pinches whose pressure rose over 0.5–1 s. Stimuli were separated by five minutes, and tap strength was adjusted to make overall response probability comparable to pinching.

The two stimulus types produced similar frequencies of tail flips, yet taps usually recruited giant activity whereas pinches usually did not. Freely moving crayfish could respond to very light taps. For LG responses, the median latency from mechanical contact to the first giant spike was 7 ms.

These findings associate giant recruitment with stimulus timing, rather than a simple requirement for damaging intensity. The latency graph compares giant spikes with first major muscle potentials for nongiant responses, so its response markers are related but not identical.''','Latency means the elapsed time between a defined stimulus event and a defined response event. The paper used a microphone on the stimulating rod to mark contact; it did not measure neuronal latency from an inferred subjective perception.')
add('The initiating flip and later swimming use different paths','WK72','WK72_3','3(A,B)','Giant-mediated initial responses followed by nongiant swimming.', '''**Nongiant escape** is a tail flip produced without detected activity in either giant-fiber pathway. Wine and Krasne recorded sequences in which an anterior tap triggered an MG spike or an abdominal tap triggered an LG spike. Subsequent flexions generally occurred without corresponding giant spikes.

The implanted cord recordings retained both the large initial neural event and later muscle activity. In one sequence, swimming resumed after a 350 ms pause with a nongiant first flip. A sequence of similar-looking flexions therefore need not be a sequence of giant-mediated reflexes.

The giant circuits primarily initiated rapid escape in these observations, while nongiant circuits supported repeated swimming. Occasional giant activity during swimming could accompany a new collision or stimulus; the recordings do not establish absolute silence of giants during every possible swimming sequence.''','The slower, larger voltage swings are muscle potentials. Distinguishing them from the narrow giant spikes prevents a motor recording from being mistaken for renewed giant-neuron firing.')
add('Nongiant swimming permits varied abdominal movements','WK72','WK72_6','6','Filmed truncated tail flip during a swimming sequence.', '''A **truncated tail flip** stops before completing full flexion or re-extension. Wine and Krasne filmed nongiant swimming and observed truncated movements, changes of direction, and flexions resembling either giant-mediated trajectory. Their published sequence contains tracings separated by about 10 ms.

Cord recordings associated most successive swimming flexions with nongiant activity. Nongiant responses to gradual stimulation had much longer latencies than giant-mediated responses, when a meaningful onset could be assigned. Some nongiant flips occurred without an immediately preceding abrupt stimulus.

This flexibility supports parallel motor-control pathways beyond the giants. The authors proposed that longer latency permits more sensory guidance, but their behavioral observations did not directly measure every guidance signal. Longer latency and variable trajectory do not establish conscious choice or eliminate the possibility of stereotyped components.''','The paper uses spontaneous to describe a response without an obvious immediate change in the environment. That operational description does not establish absence of internal or previously sustained external causes.')
add('Cord lesions separate nongiant initiation from local escape','WK72','WK72_8','8','Published locations of nerve-cord transections.', '''A **transection** severs a neural pathway to test whether signals crossing it are required for a response. Wine and Krasne cut the crayfish nerve cord at several levels and tested responses to taps, gradual caudal stimuli, and swimming. They spared nearby arteries during the operations.

Cuts below the suboesophageal ganglion complex abolished ordinary nongiant responses to gradual caudal stimulation and sustained swimming, while local giant-mediated responses to abdominal taps persisted. Cutting above that complex could leave nongiant responsiveness available. Some caudal nongiant responses returned after approximately a week following lower cuts.

The pattern supports an important initiating or facilitating contribution from anterior ganglia. Recovery and segmental responsiveness prevent a claim that all nongiant tail flips require one exclusive command site. Lesions identify pathway dependence but cannot alone distinguish initiation from tonic facilitation.''','A ganglion is a concentration of neuronal cell bodies and neuropil. Neuropil contains the interwoven neuronal processes and synapses where much of the local circuit interaction occurs.')
add('Medial giants originate anteriorly and descend the cord','WK72','WK72_1','1','Receptive fields and giant-axon cross sections.', '''The paired MG neurons originate in the brain, cross the midline, and continue along the ventral nerve cord to the final abdominal ganglion. **Decussation** means crossing from one side of the nervous system to the other. Wine and Krasne related this anatomy to anterior receptive fields and descending recorded activity.

MG axons can reach approximately 200 μm in diameter in the connectives surrounding the oesophagus, tapering in the abdomen. Rostral taps and sufficiently rapid approaching visual objects activated MG in free animals. Gradual anterior stimuli more often recruited nongiant responses.

Anatomical position and propagation direction support the identification of an anterior escape pathway. They do not establish that every anterior sensory modality uses the same synapse. Modern antenna II recordings isolate one sensory route, whereas the intact-animal stimuli often contained several physical components.''','A receptive field is the part of the sensory surface or stimulus space capable of affecting a neuron. The anatomical arrangement in the modern MG paper concerns antenna II inputs; additional sensory pathways are explicitly omitted from that source diagram.',MG)
add('Lateral giants combine segmental neurons and local inputs','WK72','WK72_1','1','Giant-axon organization and posterior receptive fields.', '''The paired LG pathways contain serial neuronal segments associated with abdominal ganglia. Their dorsal giant axons are connected to ventral cell bodies and dendritic branches receiving local sensory input. Electrical coupling across segmental and contralateral junctions coordinates activity within the escape pathway.

Wine and Krasne reported LG diameters up to about 200 μm in the abdomen, with smaller diameters anteriorly. Abdominal taps recruited ascending activity and an upward-pitching response. Herberholz and colleagues later imaged the LG dendrites and their afferent contacts in the terminal abdominal ganglion.

A posterior stimulus can therefore gain access to a distributed giant pathway through local synaptic inputs. The large axon is only one part of the circuit. Its diameter does not specify which sensory inputs reach threshold or which segmental motor connections generate the movement.''','A dendrite is a neuronal process that receives and distributes synaptic input. The color micrograph is an original confocal image of LG dendritic contacts, rather than a newly drawn representation of the segmental pathway.',LG)
add('The intact ventral cord contains repeated ganglia','H11','H11_2D','2(D)','Sagittal manganese-enhanced MRI of the ventral nerve cord.', '''Herberholz and colleagues used **magnetic resonance imaging**, or MRI, to examine the nervous system without dissecting away the animal’s surrounding tissues. Juvenile crayfish were injected with manganese chloride, allowed to move, and then held motionless in narrow imaging tubes.

A three-dimensional acquisition at 78 μm resolution in each dimension resolved the ventral nerve cord and individual thoracic and abdominal ganglia. The sagittal section retains the animal’s curled abdomen and the cord’s course through it. Manganese increased contrast between tissues and exposed anatomical features poorly separated in conventional scans.

Repeated ganglia provide the anatomical setting for segmental giant and motor circuitry. The scan does not resolve every neuronal connection or identify active LG spikes. Anatomical visibility and activity measurement are separate properties of the imaging method.''','Sagittal sections cut along the animal’s front-to-back axis. The reported scan lasted four hours and thirty-three minutes, so its spatial detail must not be confused with millisecond temporal resolution.')
add('Tracer size distinguishes the filled neuron from partners','H02','H02_2A','2(A)','LG and dye-coupled neurons in the terminal ganglion.', '''Herberholz and colleagues pressure-injected LG with two fluorescent tracers. Large dextran-linked Texas Red remained predominantly within the injected neuron, whereas low-molecular-weight **Neurobiotin** could pass into electrically coupled cells. Fluorescent detection distinguished LG from its coupled partners.

The original confocal projection contains the major LG dendrite and primary afferent axons extending into the ganglionic nerves. Superposition of red and green signals produces yellow within the filled LG, while other coupled cells appear green. The figure retains its original 50 μm scale bar.

**Dye coupling** supports an intercellular pathway permeable to the tracer. It does not by itself measure synaptic current direction, conductance, or effectiveness at firing threshold. The investigators therefore combined the anatomy with paired electrical recordings rather than treating fluorescence as proof of every functional connection.''','A primary afferent carries sensory information from a receptor toward the central nervous system. The published fluorescence colors are preserved exactly; they are labels of tracer distribution, not colors assigned to natural tissue.')
add('Fine LG dendrites contact primary afferent terminals','H02','H02_2B','2(B)','Fine dendritic processes surrounding afferent axons.', '''The terminal ganglion receives sensory axons from touch-sensitive hairs and stretch receptors of the tail fan. Herberholz and colleagues traced these inputs into distinct parts of the LG dendritic tree. Input from different nerves was spatially segregated rather than uniformly mixed across every branch.

High-resolution confocal images revealed thin, vine-like LG processes wrapping around afferent axons. The original panel retains a 10 μm scale bar. These contacts occur near distal endings of the major LG dendritic branches, where sensory input enters the command neuron.

The anatomical arrangement creates a local substrate for synaptic interaction between afferents and LG. Contact in a projection is not enough to identify each membrane junction or its molecular channel. Functional recordings and tracer passage provide additional evidence for electrical coupling at these sites.''','Distal means farther along a dendritic branch from the main axon or cell body. Because a confocal projection combines optical sections, apparent overlap must be interpreted with attention to separation in the depth dimension.')
add('Neighboring afferents form a dye-coupled network','H02','H02_3AB','3(A,B)','A filled afferent and its coupled neighbors beside LG.', '''Herberholz and colleagues injected Neurobiotin into one primary afferent while filling LG separately with Texas Red. This preparation distinguished passage among sensory axons from tracer introduced directly into LG. The afferent labeling extended to neighboring sensory axons through central contacts.

Individual injected afferents were coupled to between one and twelve other afferents. Most labeled partners entered through the same sensory nerve, although some connections crossed between nerves. The enlarged published panel separates the afferent-coupling site from the nearby contact with LG.

The distribution supports a local sensory network capable of interaction before signals reach the command neuron. Dye passage alone does not establish that an unstimulated neighbor fires. The subsequent current-injection experiments tested whether this anatomical connectivity can transmit electrical excitation.''','Lateral excitation means excitation spreading between neurons at a similar stage of processing. It differs from the common sensory arrangement of lateral inhibition, in which neighboring activity suppresses rather than recruits a response.')
add('Paired recordings establish electrical afferent coupling','H02','H02_3CD','3(C,D)','Afferent-to-LG transmission and interactions between sensory axons.', '''An **excitatory postsynaptic potential**, or EPSP, is a synaptic voltage change that promotes neuronal excitation. Herberholz and colleagues recorded a small, brief LG EPSP when an individual afferent fired after intracellular current injection. They also recorded simultaneously from pairs of afferent axons.

Depolarizing one afferent produced a smaller depolarization and corresponding EPSPs in its neighbor. Applying current to the other cell produced reciprocal effects. LG did not fire during these paired-afferent tests, excluding an LG spike as the required intermediary event.

The transfer of sustained voltage as well as spike-related signals supports electrical coupling among sensory terminals. These observations establish functional communication beyond dye passage. They do not identify the protein composition of the junctions or prove that every afferent pair has identical coupling strength.''','Depolarization is a shift of membrane voltage in the positive direction relative to its resting value. An electrical synapse permits current flow through intercellular channels instead of requiring transmitter release at every signal transfer.',LG)
add('Sensory stimulation can recruit an unstimulated afferent','H02','H02_4','4(A,B)','Increasing nerve shocks recruit sensory EPSPs and afferent spikes.', '''Herberholz and colleagues increased the strength of sensory-nerve shocks while recording a particular afferent and LG. Below the recorded afferent’s direct stimulation threshold, smaller shocks already evoked EPSPs in that cell. The source therefore distinguished direct axonal stimulation from recruitment through other neurons.

As shock strength increased, the afferent EPSP rose in discrete steps. A recruited spike appeared before the stronger shock that directly activated the recorded axon, and its appearance coincided with additional LG excitation. Direct activation shortened the latency of the recorded afferent spike.

The experiment supports sensory amplification through a lateral network: activated afferents can enlist additional inputs. It does not convert shock voltage into a calibrated natural touch intensity. Electrode position and individual axonal thresholds affect which afferents the shock recruits first.''','Threshold is the stimulus or membrane condition at which a defined response first appears. A direct nerve-shock threshold differs from the threshold at which an afferent fires after receiving an EPSP from its neighbors.',LG)
add('LG depolarization enhances sensory-afferent recruitment','H02','H02_5','5(A,B)','Opposite effects of LG depolarization and hyperpolarization.', '''Herberholz and colleagues held sensory stimulation constant while injecting current into LG. A sensory EPSP that normally remained below firing threshold in an afferent became suprathreshold when LG was depolarized. The imposed LG shift was approximately 10–20 mV at its initial segment.

The effect cannot be explained solely by adding voltage at the command neuron’s spike-generating membrane. It changed whether a presynaptic sensory axon fired. Current could spread from LG toward coupled afferent terminals, supplementing excitation arriving from neighboring sensory neurons.

This supports a feedback interaction between the developing LG response and recruitment of its own inputs. It does not establish the natural source of every equivalent depolarization in an intact animal. The causal manipulation was intracellular current injection in an exposed neural preparation.''','Presynaptic and postsynaptic describe the conventional direction of information flow at a connection. Electrical junctions can also pass current opposite that direction, so the postsynaptic cell can influence neurons supplying its input.',LG)
add('LG hyperpolarization suppresses recruited sensory spikes','H02','H02_5','5(B)','Reduction of afferent recruitment during LG hyperpolarization.', '''**Hyperpolarization** shifts membrane voltage in the negative direction relative to its resting level. Herberholz and colleagues injected hyperpolarizing current into LG while presenting the same sensory-nerve stimulus. A previously suprathreshold afferent EPSP then failed to evoke its recruited spike.

This opposite manipulation complements the depolarization test. The stimulus delivered to the nerve did not need to be weakened to reduce sensory recruitment. LG membrane state altered the excitatory interaction between sensory axons and the command neuron through the electrically coupled circuit.

The result supports a distributed control of escape excitability rather than a threshold determined only at the final command cell. It does not imply that every LG hyperpolarization has an identical behavioral consequence. Which afferents are near threshold and how strongly they are coupled remain relevant.''','The figure includes both current polarities from the original publication. The comparison retains the same sensory preparation and tests the effect of changing LG voltage rather than changing the external stimulus.',LG)
add('Command-neuron voltage also changes interneuron recruitment','H02','H02_6','6(A,B)','LG voltage shifts alter the firing of interneuron A.', '''A **first-order mechanosensory interneuron** receives input from primary sensory afferents and can transmit excitation onward to LG. Herberholz and colleagues recorded interneuron A while altering LG voltage by current injection. They compared identical nerve stimuli at rest and during imposed voltage shifts.

LG depolarization made normally subthreshold interneuron responses generate spikes. Hyperpolarization could suppress a previously evoked spike. The interactions could arise through enhanced afferent recruitment and through current flowing directly from LG toward electrically coupled interneurons.

The sensory-to-command pathway therefore contains interconnected stages rather than a strictly one-way sequence. These results support feedback-sensitive recruitment but do not isolate the exact contribution of each route in every preparation. Both afferent-network excitation and direct electrical communication must be considered when explaining the recorded effect.''','Interneuron A is an identified sensory interneuron with a known morphology and response pattern. Its recruitment adds the indirect afferent-to-interneuron-to-LG route to the direct afferent-to-LG route.',LG)
add('Voltage clamp separates added current from voltage bias','H02','H02_7','7(A,B)','LG voltage and synaptic-current responses during depolarization.', '''A **voltage clamp** holds a neuron near a commanded membrane voltage while recording the current required to maintain it. Herberholz and colleagues compared LG responses to the same nerve stimulus during current injection and under two-electrode voltage clamp. This separated changes in voltage from changes in synaptic input.

LG depolarization enlarged the later, interneuron-mediated EPSP component and could bring LG to spike threshold. Under voltage clamp, the corresponding excitatory synaptic current also increased. The added response therefore included recruitment of input rather than merely a shifted starting voltage.

The result supports amplification within the coupled network. It must be distinguished from the effect of depolarization on an already active individual rectifying junction, which can reduce that junction’s input. Aggregate network recruitment and unitary synaptic transfer are different experimental measurements.''','The alpha component includes the direct afferent pathway; the beta component includes first-order interneuron input. The source uses these labels for compound LG responses, not for two different LG neurons.',LG)
add('Unitary electrical input depends on postsynaptic voltage','E91','E91_3','3(A–D)','Interneuron A transmission and voltage-dependent LG responses.', '''A **unitary synaptic response** is the response associated with firing of a defined presynaptic neuron. Edwards and colleagues activated interneuron A while recording LG and imposed positive or negative shifts in LG voltage. This controlled presynaptic source differs from stimulating an entire sensory network.

Hyperpolarizing LG enlarged both the EPSP and measured excitatory synaptic current; depolarizing LG reduced them. At rest, the EPSP peaked within approximately 1 ms and decayed over the following 20 ms. The authors related these changes to voltage-sensitive electrical transmission.

The result supports a **rectifying junction**, whose conductance depends on the voltage difference across the connection. It does not contradict enhanced network recruitment during LG depolarization: one experiment measures a fixed unitary input, while the other allows additional afferents and interneurons to become active.''','Conductance describes how readily current passes through a membrane or junction. A rectifying electrical synapse is not a fixed resistor: the relative voltages of its two cells influence the amount and direction of current.',LG)
add('Rectification permits selective reverse electrical transfer','E91','E91_4','4(A–C)','Reverse transfer from LG to interneuron A.', '''**Orthodromic** transmission follows the usual sensory-to-command direction, while **antidromic** transmission proceeds in the reverse direction. Edwards and colleagues recorded interneuron A while shifting LG voltage or evoking an LG action potential. They tested electrical communication in both directions across the same connection.

Steady hyperpolarization of LG spread into interneuron A, whereas steady LG depolarization transferred much less effectively. An LG spike produced an antidromic synaptic potential whose amplitude changed when the interneuron was depolarized or hyperpolarized. These observations support voltage-dependent coupling rather than absolute one-way isolation.

Rectification therefore biases transmission without preventing all reverse influence. The measured membrane effects do not identify the junctional channel proteins. Their interpretation concerns physiological properties of the connection and must remain separate from an untested molecular explanation of its asymmetry.''','The paper controlled LG voltage with separate current-injection and recording electrodes. This reduces confusion between a true change in neuronal membrane potential and a voltage drop across the electrode itself.',LG)
add('LG detects coincidence on a submillisecond scale','E98','E98_3B','3(B)','LG EPSP amplitude as a function of sensory-input delay.', '''**Coincidence detection** is preferential responsiveness to inputs arriving at nearly the same time. Edwards and colleagues stimulated two sensory nerves of the terminal ganglion in isolated juvenile crayfish preparations. Each nerve evoked a subthreshold LG EPSP, and paired shocks were presented with systematically varied delays.

Changing the relative delay from about 100 μs on one side of coincidence to about 100 μs on the other changed peak EPSP amplitude markedly. Across preparations, separating inputs by 0.1 ms reduced the normalized response relative to coincidence. The compound response was especially sensitive near zero relative delay.

The experiment establishes very precise timing sensitivity in sensory input to LG. It does not measure the timing of natural receptor spikes during every predator encounter. Nerve shocks synchronize recruited axons and provide a controlled test of the central integration mechanism.''','The Greek μ in the original article denotes microseconds. One hundred microseconds is 0.1 ms, rather than the 100 ms that can appear in faulty text extraction from this PDF.',LG)
add('The direct afferent pathway retains coincidence selectivity','E98','E98_4','4(A–C)','Timing sensitivity of full, alpha-only, and picrotoxin-treated responses.', '''Edwards and colleagues asked whether precise timing sensitivity required excitation through sensory interneurons. They isolated the early **alpha component**, dominated by direct afferent-to-LG electrical input, either by weakening the nerve stimuli or by blocking nicotinic transmission with mecamylamine.

**Acetylcholine** is the transmitter implicated at the afferent-to-interneuron chemical synapses; a **nicotinic receptor** is an acetylcholine-gated ion channel. Mecamylamine reduced this chemical route. Even after the indirect pathway was suppressed, the alpha response remained largest for coincident inputs and declined with increasing delay.

The result supports coincidence selectivity within the direct electrical pathway. It does not imply that chemical sensory synapses are irrelevant to escape in the intact animal. They normally contribute additional excitation, while the pharmacological comparison isolates a specific mechanism of temporal integration.''','The source reports 50 μM mecamylamine in the pharmacological isolation test. That concentration blocks nicotinic transmission in this preparation; the experiment does not establish that every crayfish chemical synapse is cholinergic.',LG)
add('Fast coincidence selectivity survives inhibition blockade','E98','E98_4','4(C)','Coincidence sensitivity during picrotoxin superfusion.', '''**Picrotoxin** blocks the inhibitory channel mechanisms tested in these crayfish preparations. Edwards and colleagues applied 10 μM picrotoxin while comparing paired nerve inputs at different delays. They tested whether delayed inhibition could account for the very narrow coincidence peak.

Coincidence sensitivity remained and was sharper during picrotoxin treatment. Delays of 50 μs produced a measurable decrease from the coincident response, and larger delays exceeded that reduction. This timing is much shorter than the several milliseconds needed for the delayed feed-forward inhibition examined in separate experiments.

The result argues against that inhibitory pathway being necessary for the fastest selectivity. It does not eliminate inhibition’s contribution to later sensory filtering. The drug comparison distinguishes mechanisms acting on different timescales rather than establishing that the escape pathway lacks inhibitory synapses.''','Feed-forward inhibition occurs when sensory excitation also recruits an inhibitory pathway to the target neuron. It can curtail later excitation even when the first fractions of a millisecond are filtered by electrical-junction properties.',LG)
add('Opened electrical junctions can reduce late excitation','E98','E98_3B','3(B)','Measured timing sensitivity used to test the rectifying-junction account.', '''Edwards and colleagues proposed two interacting consequences of rectifying electrical input. An early LG depolarization reduces the voltage difference that would open a later junction. Junctions already opened by the first afferent volley can also conduct current away from the postsynaptic neuron as those afferents repolarize.

Their computational comparisons reproduced reduced summation for short input delays with voltage-sensitive junctions. The experimental nerve-pair data confirmed sharp coincidence sensitivity, including a decrease for 0.1 ms separation. **Shunting** means diverting current through an available conductance so that it contributes less to the desired voltage response.

The model supplies a mechanistic account consistent with the recordings, not a direct measurement of every individual gap-junction current in vivo. Its assumed channel kinetics must remain distinguishable from the physiological evidence for timing-dependent EPSP reduction.''','Repolarization is the return of a depolarized membrane toward its resting voltage. An open electrical connection can change its current direction as the voltage difference reverses; rectification does not prevent this while the junction remains conductive.',LG)
add('Sensory excitation is followed by delayed LG inhibition','V97','V97_2','2(A,B)','Picrotoxin changes the late portion of a root-evoked LG response.', '''**Postexcitatory inhibition**, or PEI, is inhibition that follows the early excitation evoked by sensory input. Vu and colleagues recorded LG in isolated crayfish abdomens and stimulated sensory roots. They compared the compound response before and during picrotoxin application.

The alpha and initial beta peaks changed relatively little at the tested dose, while the later falling response was enlarged or prolonged. The effect emerged after the early excitatory components, consistent with delayed inhibitory action. The experimental preparation excluded movement by cutting motor roots.

This supports a sensory-evoked inhibitory process that limits later LG excitation. Drug-induced enlargement alone does not establish its exact cellular location, because disinhibition could also affect upstream sensory neurons. The study therefore tested responses to defined input and injected currents within LG itself.''','The original paper reports the effective picrotoxin range as 7–10 μM. Inhibitory pharmacology is interpreted together with the current-injection controls, rather than using one altered waveform to assign a complete circuit.',LG)
add('A defined test EPSP is attenuated after sensory excitation','V97','V97_3','3(A,B)','Reduction of an interneuron A test EPSP at different delays.', '''Vu and colleagues evoked a defined electrical EPSP by directly stimulating interneuron A. They compared this test response alone with the same response delivered during a sensory-root-evoked LG potential. The selected sensory root did not itself fire interneuron A in the tested ganglia.

The test EPSP was strongly reduced after the beta peak of the compound response. At an 8 ms delay from the root shock, its average reduction was approximately 47%. Because the experiment directly controlled the presynaptic test spike, failure to recruit that interneuron was not a sufficient explanation.

The result supports attenuation at or near the postsynaptic integration stage. It does not assign all attenuation to PEI: electrical-junction voltage dependence and presynaptic shunting can also reduce the test EPSP. Further pharmacological and conductance measurements separated these contributions.''','The experiment avoids refractoriness of the test interneuron caused by the initial root stimulus. A refractory interval is a period after a spike when a neuron cannot fire again normally; here the test spike was separately evoked.',LG)
add('Picrotoxin removes much of the delayed EPSP attenuation','V97','V97_5','5(A,B)','Test-EPSP attenuation before and during picrotoxin treatment.', '''Vu and colleagues repeated the interneuron A test during picrotoxin exposure. The test spike was timed so its LG EPSP occurred 8 ms after a sensory-root stimulus. The control comparison retained the same type of defined presynaptic input and compound LG response.

Picrotoxin reduced the average attenuation from approximately 47% to approximately 18%. This pharmacological release supports a substantial inhibitory contribution to the reduction after the early excitatory peak. The tested drug concentration did not alter LG’s resting voltage or resting input resistance appreciably.

The remaining attenuation prevents attributing the whole effect to one inhibitory mechanism. Voltage-sensitive electrical transmission and other concurrent conductances can still reduce an EPSP. Partial, slow washout also limits a simple assumption that drug effects are immediately reversible under every recording condition.''','An antagonist reduces the action of a receptor or channel-mediated process. Picrotoxin acts on inhibitory channel function in this experiment; attenuation remaining during its application requires an explanation beyond complete removal of one GABAergic component.',LG)
add('Delayed inhibition increases a shunting conductance','V97','V97_6','6(A,B)','Reduced attenuation of injected-current responses during picrotoxin.', '''**Input resistance** is the voltage response produced by an injected current, expressed relative to that current. A smaller response to the same current indicates that more current can escape through membrane conductance. Vu and colleagues measured this property during the sensory-evoked LG potential.

Current injected into one LG or its electrically coupled counterpart produced less voltage during the late response. Picrotoxin removed much of that reduction, particularly after the beta peak. The result supports an inhibitory conductance increase rather than simply withdrawal of an excitatory input.

**GABA**, gamma-aminobutyric acid, is the inhibitory transmitter implicated by the anatomy and pharmacology. GABA-associated chloride conductance can shunt excitation even when its reversal potential produces some depolarization. Thus the direction of a voltage change alone does not determine whether its net effect promotes firing.''','A reversal potential is the membrane voltage at which the net current through a particular conductance changes direction. The study found the PEI reversal level more positive than rest but below spike threshold, consistent with depolarizing inhibition.',LG)
add('Dendritic inhibition is partly specific to input location','V97','V97_11','11(A–E)','Comparison of repeated same-root and different-root stimuli.', '''Vu and colleagues compared pairs of sensory-root shocks separated by 8 ms. The second shock was delivered either to the same root or to a different root in the same ganglion. These roots supply partly distinct dendritic regions, allowing a test of spatial specificity.

The second compound response was attenuated more strongly in the same-root condition. Both local PEI and reduced chemical sensory transmission could contribute. Cadmium-containing saline suppressed the chemical component, providing a control for attenuation caused by its fatigue rather than by inhibition alone.

The results support a partly localized dendritic inhibitory process, rather than uniform suppression of all LG input. They do not establish one identified inhibitory neuron for each receptor. The paper proposed alternative local arrangements of inhibitory neurons, which remain different from directly observed anatomical wiring.''','Distal dendritic inhibition can suppress sensory input where it enters LG. Recurrent inhibition near the spike-generating region has a different spatial effect, so the two inhibitory processes should not be treated as identical.',LG)
add('Photoinactivation removes a segmental giant relay','F91','F91_1','1(A–C)','Recordings before and during dye-mediated segmental-giant inactivation.', '''The **segmental giant**, or SG, is a relay neuron through which giant-fiber activity excites many fast-flexor motor neurons. Fraser and Heitler filled SG with Lucifer Yellow and illuminated it to disrupt its function. This **photoinactivation** allowed them to test pathways normally obscured by the relay’s strong output.

As illumination continued, SG spikes broadened, developed long depolarized plateaus, and eventually failed. Giant-fiber stimulation no longer produced the normal strong fast-flexor response through the affected SG. Some residual input persisted, suggesting an additional connection rather than complete dependence on one relay.

Selective disruption supplies causal evidence about SG’s contribution. The evolving plateau can temporarily alter other electrically coupled cells, so intermediate stages are not equivalent to a clean instantaneous deletion. The study checked SG responsiveness before interpreting the residual motor input.''','A motor neuron carries its axon out of the central nervous system toward an effector. SG has unusual motor-neuron-like anatomy but functions as an internal relay; the fast-flexor cells provide motor output to abdominal muscles.')
add('Bilateral relay removal exposes direct giant-fiber input','F91','F91_2','2(A–C)','Residual LG-to-fast-flexor responses after bilateral SG inactivation.', '''Fraser and Heitler photoinactivated SG on both sides of an abdominal ganglion. Removing only one SG would leave a contralateral route capable of exciting the recorded fast-flexor motor neuron. Bilateral manipulation therefore controlled an important parallel pathway.

After both SGs failed, LG stimulation still evoked a smaller fast-flexor EPSP. Injected current into LG could also spread to the motor neuron, especially for hyperpolarizing current, supporting an electrical component. The remaining response had a much shorter route than the usual giant-fiber-to-SG-to-motor-neuron pathway.

The experiment supports direct input beyond the dominant relay route. It does not imply that this small pathway alone normally produces a full escape. The intact circuit combines direct motor-giant activation, SG-mediated recruitment, and additional fast-flexor input; selectively removing SG reveals only part of that organization.''','The motor giant, MoG, is a specialized abdominal flexor motor neuron with a powerful electrical input from the giant fibers. It is distinct from SG and from the broader group of nongiant fast-flexor motor neurons.')
add('LG and MG differ in their residual fast-flexor outputs','F91','F91_4','4(A,B)','Comparisons of LG and MG input after SG removal.', '''Fraser and Heitler compared LG and MG responses in fast-flexor neurons after bilateral SG photoinactivation. Both giants normally recruit the relay, so intact recordings can obscure differences in their direct output. The experiment compared the pathways under the same relay-removal condition.

In anterior abdominal ganglia, LG retained appreciable direct excitatory input to fast-flexor neurons, whereas MG produced little or no comparable effect. The residual LG input declined toward posterior ganglia. These segmental differences parallel the distinct motor consequences of activating the two giant systems.

The result supports unequal output connectivity beneath the shared SG pathway. It does not reconstruct the circuit’s evolutionary history from physiology alone. The authors proposed an ancestral interpretation, but the measured evidence is the spatial distribution of residual synaptic effects in the manipulated living circuit.''','A monosynaptic pathway crosses one synaptic connection; a disynaptic pathway crosses two. SG photoinactivation separates the dominant disynaptic relay contribution from a smaller direct connection, rather than proving that every remaining signal has one universal amplitude.')
add('Cadmium separates chemical from electrical motor input','F91','F91_9','9(A,B)','Residual LG-to-fast-flexor response during cadmium exposure.', '''A **chemical synapse** releases a transmitter that acts on receptors of another cell, rather than transferring current directly through a junction. Fraser and Heitler tested the residual LG-to-fast-flexor input with cadmium after removing SG. Cadmium interferes with calcium-dependent transmitter release but can also affect other cellular properties.

At millimolar cadmium concentrations, the residual fast-flexor EPSP decreased while the obligatory electrical giant-fiber-to-motor-giant spike transmission persisted. The authors also checked antidromic fast-flexor spikes, which were not comparably lost. These controls distinguish reduced chemical input from complete failure of axonal conduction.

The findings support a chemical component alongside electrical coupling. They do not identify the released transmitter or its receptor subtype. Cadmium’s effects on spike duration and other membrane currents also require control, so pharmacology alone is not a complete molecular identification.''','The source tested cadmium at 2–2.5 mM in the relevant preparations. Calcium-dependent release is a mechanistic class; the paper does not establish which calcium-channel subtype provides the presynaptic calcium entry.')
add('Cooling resolves components with different synaptic delays','F91','F91_10','10(A–C)','Residual motor EPSPs at 20°C, 7°C, and with cadmium.', '''Fraser and Heitler cooled preparations with both SGs photoinactivated from approximately 20°C to approximately 7°C. Cooling changes spike shape and slows processes associated with chemical transmission. LG and a fast-flexor neuron were recorded together to relate the residual motor response to presynaptic activity.

At low temperature, an early EPSP component remained close to the LG spike, while a later component became more visibly separated. Adding cadmium removed the later component while leaving the early response. This combination supports distinct electrical and chemical contributions to the direct connection.

The inference rests on converging timing and pharmacological evidence, not on delay alone. Cooling affects several membrane processes and increased LG spike duration. The experiment does not establish that the cold response waveform occurs during ordinary escape in the freely behaving animal.''','Temperature is an experimental manipulation here. The short-latency component is consistent with electrical transmission, while the longer-latency cadmium-sensitive component supports transmitter-mediated input; neither component is newly redrawn in the deck.')
add('Antenna stimulation isolates measurable MG input','M18','M18_1B','1(B)','Antenna II-evoked connective activity and intracellular MG potentials.', '''Swierzbinski and Herberholz surgically exposed the crayfish brain and recorded MG while stimulating one antenna II nerve. An extracellular hook electrode monitored connective activity, and a sharp intracellular electrode measured MG voltage. This preparation isolated a defined anterior sensory route.

The authors quantified an early MG potential at 3 ms and a later potential at 6 ms after the stimulus artifact. Most single-nerve stimuli produced subthreshold potentials, even when their amplitude had saturated. The electrode stimulus was kept below the level that directly activated MG without synaptic transmission.

These recordings establish experimentally separable phases of MG input. The late potential contains interacting excitation and inhibition rather than an isolated pure inhibitory voltage. Failure to fire in the reduced preparation does not mean that the intact MG circuit cannot respond rapidly to anterior threats.''','A stimulus artifact is the recorded electrical disturbance produced directly by the applied shock. The 3 ms and 6 ms measurements are delays from that artifact, not independent measurements of the first natural antenna movement.',MG)
add('Repeated saline trials control for recording drift','M18','M18_2B','2(B)','Early and late MG potentials during repeated saline stimulation.', '''A **baseline control** measures the preparation without the tested drug, allowing changes over time to be distinguished from treatment effects. Swierzbinski and Herberholz stimulated the antenna II nerve every 90 s while continuously superfusing the exposed MG preparation with normal crayfish saline.

After a ten-minute baseline, responses were followed for another 90 minutes. The early and late potentials fluctuated but did not undergo the major sustained increase seen with ethanol. The original published traces retain their color coding for successive recording times.

This control supports attributing the ethanol-associated enhancement to treatment rather than ordinary repeated stimulation alone. It does not prove that saline preparations are perfectly invariant or that each pharmacological condition has the same background drift. The comparison concerns the behavior of this reduced neural preparation over its recorded interval.''','Superfusion continually replaces the solution bathing the tissue. The study kept flow at 5 ml per minute, making solution exchange a controlled part of the experiment rather than an unspecified exposure.',MG)
add('Ethanol enhances the early MG sensory potential','M18','M18_3','3','MG potential amplitudes before, during, and after ethanol exposure.', '''Swierzbinski and Herberholz superfused MG preparations with 100 mM **ethanol**, the alcohol molecule tested here, after a saline baseline. Antenna II stimuli remained 90 s apart. Early and late MG potentials were measured separately to avoid treating the compound response as a single uniform signal.

The early potential rose to roughly one-and-a-half times its baseline amplitude during ethanol exposure. Enhancement remained after 60 minutes of saline washout. The late component varied and did not provide comparably strong evidence for a sustained enhancement.

The effect supports increased excitability of an anterior sensory pathway under this treatment. It does not identify a single ethanol-binding receptor or establish a behavioral escape rate in these pinned preparations. A larger subthreshold potential and an increased probability of natural escape are related hypotheses, not the same measurement.''','The source reports an early response of approximately 157% of baseline after 60 minutes of ethanol and approximately 156% after 60 minutes of washout. These values describe normalized potential amplitude, not percentage of animals escaping.',MG)
add('Inhibitory-channel blockade changes MG sensory responses','M18','M18_4B','4(B)','Early and late MG potentials during picrotoxin and washout.', '''Swierzbinski and Herberholz applied 25 μM picrotoxin to test inhibitory-channel contributions to MG input. An **antagonist** reduces a receptor-associated process; this drug interferes with inhibitory ion-channel function. The experiment compared early and late sensory potentials with their saline baseline.

The early MG potential increased during the 30-minute treatment. Changes of the later potential during application were more variable. Higher picrotoxin concentrations could produce repeated MG spikes arising late in the compound response, so the investigators used the lower dose for their main comparisons.

The findings support inhibitory regulation of the MG sensory pathway. They do not assign every drug effect directly to channels on MG: upstream sensory neurons can also be affected. The late suppression during washout further cautions against treating the drug response as a simple, immediately reversible removal of one synapse.''','GABAergic means mediated by GABA. The paper interprets its pharmacology in that framework, but receptor subunit composition and the precise cellular locations of all affected receptors were not directly identified.',MG)
add('Muscimol produces delayed suppression during washout','M18','M18_4C','4(C)','MG potentials during muscimol exposure and saline washout.', '''**Muscimol** is an agonist of ionotropic GABA receptors; an agonist activates a receptor-associated response. An **ionotropic receptor** directly gates an ion channel. Swierzbinski and Herberholz applied 25 μM muscimol for 30 minutes while repeatedly measuring antenna II-evoked MG potentials.

Potential amplitudes changed relatively little during treatment but declined during subsequent saline washout. The late potential reached approximately 32% of baseline after 60 minutes of washout. Separate measurements of MG input resistance changed only modestly during muscimol exposure, despite the later decline of sensory potentials.

The delayed response supports a more complex pharmacological interaction than immediate postsynaptic shunting alone. It does not establish the molecular origin of the persistent suppression. Direct receptor activation, upstream effects, and processes continuing after solution exchange must remain distinguishable from measured MG voltage changes.''','The study measured input resistance with a second intracellular electrode and current steps from −40 to 40 nA. This tested MG membrane responsiveness, while the sensory potential also depended on the pathways supplying MG.',MG)
add('Drug order alters the apparent ethanol response','M18','M18_5','5','MG responses to muscimol followed by ethanol.', '''Swierzbinski and Herberholz exposed MG preparations to muscimol before applying ethanol. The sequence included a saline baseline, 30 minutes of 25 μM muscimol, 30 minutes of 100 mM ethanol, and 60 minutes of saline washout. Early and late sensory potentials were measured throughout.

Unlike ethanol alone, ethanol following muscimol did not produce a clear additional enhancement relative to baseline. The large washout suppression observed after muscimol alone was also absent in this sequential condition. The treatment history therefore altered both apparent facilitation and delayed suppression.

These interactions support state-dependent pharmacological modulation of sensory input. They do not prove that ethanol acts at exactly the same receptor-binding site as muscimol. The measurements concern compound synaptic potentials, and several sites within the anterior pathway could contribute to the history-dependent response.''','Comparing treatment sequences distinguishes interaction from a claim that two drugs merely add independent effects. The source did not identify a unique biochemical pathway sufficient to account for the observed interaction.',MG)
add('Manganese imaging links sensory stimulation to brain uptake','H11','H11_3AB','3(A,B)','Axial brain sections after antenna II stimulation and manganese injection.', '''**Manganese-enhanced MRI**, or MEMRI, uses manganese ions to increase tissue contrast and mark activity-associated uptake. Manganese can enter depolarized cells through voltage-gated calcium channels. Such channels open in response to membrane voltage and normally provide a route for calcium entry.

Herberholz and colleagues injected 40 μl of 25 mM manganese chloride and stimulated the antenna II nerve at 4 Hz. T1-weighted brain images at 31 μm in-plane resolution contained greater uptake on the stimulated side, including the antenna II nerve and accessory-lobe region.

The result relates controlled sensory stimulation to regional manganese accumulation. It does not identify the firing of a particular MG neuron or resolve individual spikes. The marker accumulates over an extended stimulation period, so its biological timescale differs from the millisecond escape recordings.''','The published sections retain 1 mm scale bars and the original directional arrows. Manganese entry is used as an activity-related marker; these scans do not identify a calcium-channel subtype or a synapse-specific tracer transfer rate.')
add('Unstimulated imaging controls constrain activity inference','H11','H11_4','4','Original stimulated and unstimulated brain-image stacks.', '''Herberholz and colleagues compared stimulated and unstimulated animals receiving the same manganese dose. They examined both T1- and T2-weighted images, which emphasize different tissue-dependent magnetic relaxation properties. Regions of interest were held consistent across selected slices within each animal.

The stimulated animal’s T1-weighted images had greater intensity on the stimulated side, while the unstimulated control had more similar values across sides. T2-weighted images provided strong anatomical contrast but made the side difference less discrete. The comparison extended across a 400 μm axial region.

The control supports stimulation-associated uptake rather than assuming all visible contrast represents neural activity. It does not remove every potential anatomical or physiological source of between-animal variation. Imaging protocol, manganese exposure, anatomical position, and the regional comparison all affect what can be inferred.''','T1 and T2 are different magnetic relaxation measures, not two neural pathways. An image with stronger overall contrast can be less informative about a subtle activity-associated difference between the two sides of the brain.')
add('Cord stimulation permits regional imaging of escape activity','H11','H11_5','5(A–C)','Cord, ganglion, and enlarged neuropil after repeated escape stimulation.', '''Herberholz and colleagues injected a modest manganese dose and stimulated the ventral nerve cord to elicit LG-mediated tail flips. The protocol used 60 shocks over 20 minutes, each evoking an escape response. Imaging followed the stimulation period rather than occurring during individual flips.

Manganese-enhanced sections resolved abdominal ganglia and associated nerve roots. Enlarged regions distinguished brighter ganglionic areas from surrounding tissue, with the published figures preserving 500 μm and 100 μm scale bars. The result extends activity-associated imaging beyond the anterior sensory preparation.

This provides a regional anatomical record associated with repeated escape-circuit activation. It does not establish which individual neuron accumulated the marker or which synapse transmitted each response. Intracellular electrophysiology supplies cellular timing and causal tests that this integrated imaging measurement cannot replace.''','The injected dose was 10 μl of 50 mM manganese chloride. The investigators used a T1-weighted scan with 78 μm in-plane resolution for the cord overview and higher spatial detail in the enlarged ganglion acquisition.')
add('Escape speed and flexibility arise from parallel circuits','WK72','WK72_5','5','Distinct filmed LG and MG escape movements.', '''Wine and Krasne connected abrupt stimulus location with the giant circuit recruited and the resulting movement. Posterior taps commonly evoked LG-mediated upward pitching; anterior stimuli commonly evoked MG-mediated backward escape. More gradual stimuli generally recruited slower, more variable nongiant responses.

Controlled nerve-pair recordings later established timing selectivity at 0.1 ms input separation, while relay photoinactivation exposed differing LG and MG motor outputs. These experiments address separate stages: sensory integration determines recruitment, and output connectivity determines the muscle pattern once a pathway is active.

Speed and flexibility therefore depend on interacting parallel pathways rather than on giant-axon diameter alone. The rapid giant response is not the only escape available, and the presence of a tail flip is not sufficient to identify its neural cause. Pathway-specific recording or manipulation is required.''','A command neuron is a neuron whose activity can initiate a defined motor program in the studied circuit. This functional term does not imply that the cell alone evaluates every sensory input, controls all later swimming, or determines the animal’s behavior independently of state.')
slides[-1]['refs'] += [ref('E98'), ref('F91')]
slides[-1]['cite'] += '; Edwards et al. (1998); Fraser & Heitler (1991)'
for slide in slides:
 if 'figures' in slide and slide['figures'][1]['path'].endswith('M18_1A.png'):
  slide['primary_figure_height']=2.4
assert len(slides)==44,len(slides)
for s in slides:
 words=len(re.sub(r'\*\*|_','', ' '.join(s['body'])).split())
 assert 90<=words<=170,(s['title'],words)
take={'cite':'Wine & Krasne (1972); Edwards et al. (1998); Vu et al. (1997); Fraser & Heitler (1991)','refs':[ref(k)for k in ['WK72','E98','V97','F91','H02','M18']], 'items':[
{'lead':'Stimulus timing and location.','text':'Abrupt posterior stimuli recruit LG-mediated upward pitching, while anterior stimuli can recruit MG-mediated backward escape; intensity alone does not determine the pathway.'},
{'lead':'Parallel escape systems.','text':'Nongiant circuits mediate slower, flexible responses and most successive swimming flips, so a tail flip does not by itself establish giant-neuron activity.'},
{'lead':'Electrical integration.','text':'Voltage-sensitive rectifying junctions support submillisecond coincidence selectivity, while lateral afferent coupling and reverse current from LG can recruit additional sensory input.'},
{'lead':'Delayed inhibition.','text':'Sensory-evoked GABAergic shunting curtails later LG excitation and is partly localized to dendritic input regions; inhibition can be depolarizing yet reduce firing.'},
{'lead':'Output connectivity.','text':'Motor-giant and segmental-giant pathways recruit abdominal flexion; removing SG exposes unequal residual LG and MG fast-flexor connections and a chemical component.'},
{'lead':'Mechanistic evidence.','text':'Defined inputs, voltage control, pharmacology, and selective relay disruption test different causal stages; proposed channel or evolutionary explanations must remain separate from measured effects.'}]}
spec={'lecture':4,'theme':'deep-sea','content_slides':44,'title_image':fig('H11','H11_1B','1(B)','Juvenile Procambarus clarkii used in the imaging study.'),'slides':slides,'takeaways':take}
(ROOT/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
print('Wrote 44 content slides; paragraph and word counts verified.')
