import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
R={
'T48':('Tinbergen (1948)','N. Tinbergen (1948). Social Releasers and the Experimental Method Required for Their Study. The Wilson Bulletin 60(1):6–51. Digitized article; repository DOI','10.5281/zenodo.16185673'),
'LT38':('Lorenz & Tinbergen (1938)','K. Lorenz; N. Tinbergen (1938). Taxis und Instinkthandlung in der Eirollbewegung der Graugans. I. Zeitschrift für Tierpsychologie 2(1):1–29. Archive edition identifies 1938; Crossref indexes this DOI under 1939','10.1111/j.1439-0310.1939.tb01558.x'),
'J21':('James & Bell (2021)','N. James; A. Bell (2021). Minimally invasive brain injections for viral-mediated transgenesis: New tools for behavioral genetics in sticklebacks. PLOS ONE 16(5):e0251653','10.1371/journal.pone.0251653'),
'B17':('Bukhari et al. (2017)','S.A. Bukhari; M.C. Saul; C.H. Seward; H. Zhang; M. Bensky; N. James; S.D. Zhao; S. Chandrasekaran; L. Stubbs; A.M. Bell (2017). Temporal dynamics of neurogenomic plasticity in response to social interactions in male threespined sticklebacks. PLOS Genetics 13(7):e1006840','10.1371/journal.pgen.1006840')}
def ref(k):return R[k][1]+'. https://doi.org/'+R[k][2]
def figure(k,name,num,caption):return {'path':f'figures/{name}.png','caption':f'{R[k][0]}, Fig. {num}. {caption}','source_url':'https://doi.org/'+R[k][2]}
slides=[]
def add(title,k,name,num,caption,text,extra,brain=False):
 body=text.strip().split('\n\n');assert len(body)==3,(title,len(body));assert len(title)<=62,title
 s={'title':title,'layout':'figure-right','body':body,'transcript':[re.sub(r'\*\*|_', '',p)for p in body]+[extra],'cite':R[k][0],'refs':[ref(k)],'figure':figure(k,name,num,caption)}
 if k=='LT38':s['transcript'].append('The supplied Konrad Lorenz archive edition preserves the article photographs and printed page breaks, and identifies the work as 1938. The publisher DOI is indexed with 1939 metadata. Behavioral observations and the authors’ proposed central coordination are distinct types of evidence.')
 if k=='T48':s['transcript'].append('The figure is reproduced directly from Tinbergen’s 1948 article, which reports and reviews the classic stimulus experiments. The DOI identifies its digitized repository record, not an original journal DOI.')
 if brain:
  s.update(layout='figures-right',figure_width=6.0,primary_figure_height=2.7,figures=[s.pop('figure'),figure('J21','J21_2C','2(C)','Dorsal brain anatomy; original scale bar 2 mm.')])
  if k!='J21':s['refs'].append(ref('J21'));s['cite']+='; '+R['J21'][0]
 slides.append(s)
add('Breeding sticklebacks defend a nest territory','T48','T48_3','3','A male threatening its reflection with a unilateral ventral-spine display.', '''The three-spined stickleback, _Gasterosteus aculeatus_, changes its social behavior during breeding. A male establishes a territory, builds a nest, attacks competitors, and leads receptive females toward the nest entrance. Tinbergen studied these actions in territorial fish and tested the stimuli that release them.

A **releaser** is a stimulus characteristic that elicits a particular behavioral response under appropriate conditions. Breeding males develop a red throat and belly, and other fish respond to this coloration in model presentations. Threatening posture supplies additional information during territorial encounters.

Territorial defense is therefore a relationship between a stimulus, the animal’s condition, and its surroundings. An aggressive movement cannot be explained solely by the appearance of the opponent. Tinbergen’s model and posture controls separated these contributions without identifying the neurons that implement the response.''','A territory is an area defended against intruders. The experiment concerns breeding territorial fish, rather than every possible encounter between sticklebacks.')
add('A sign stimulus can outweigh realistic body form','T48','T48_2','2','Red-ventral R models and a neutral N model used in stimulus tests.', '''A **sign stimulus** is a restricted feature or combination of features that can release a behavioral response. Tinbergen compared models with red ventral surfaces, called the R series, with neutral-colored models, called the N series. Both series included realistic dead fish and simplified shapes.

Models were introduced into occupied territories for a fixed presentation period, in irregular order with intervals between presentations. Territorial males attacked red-bellied models more strongly than neutral ones. A realistic fish-shaped object without red could be less effective than an otherwise crude red-bellied model.

The result supports selective responsiveness to ventral coloration under these test conditions. It does not establish that fish recognize only one feature in all social situations. Shape, posture, territorial location, and the type of response must be tested separately rather than inferred from the attack comparison.''','The original printed models are reproduced unchanged; their red surfaces are described in the article but the figure itself is monochrome.')
add('Stimulus models separate features from whole animals','T48','T48_2','2','Contrasting model form and ventral coloration.', '''A **stimulus model** is an experimentally controlled object presented in place of a natural stimulus. Tinbergen used dead sticklebacks and simplified objects to vary form and ventral coloration. This method reduced the uncontrolled movements and interactions that occur when two live fish encounter each other.

Red-bellied models released strong attacks despite their different outlines. Neutral models were much less effective even when their form closely resembled a fish. Irregular presentation order and intervals reduced a simple explanation based on which model was always encountered first.

The comparison tests which properties are sufficient to release attack in a territorial male. It does not establish complete equivalence between a dummy and a live rival, or measure the animal’s subjective categorization. The effective feature is defined through the recorded behavior and the alternatives retained in the experiment.''','A simplified stimulus can be scientifically informative because it preserves a candidate feature while removing other properties of the natural object.')
add('The same red feature has context-dependent effects','T48','T48_2','2','Models used to compare responses to red and neutral ventral surfaces.', '''Tinbergen described different responses to a red-bellied fish depending on the observer’s territorial position. A male within its own territory attacked a red-bellied model. A male outside its territory could instead retreat from the same conspicuous feature.

The model comparisons were conducted in occupied territories and in territories whose owners had been removed. Red models elicited attack from owners and deterred entry by neighboring males. Neutral models exerted much less influence in these tests.

A sign stimulus does not carry an obligatory motor command independent of context. Its effect depends on the relationship between the observer and the defended area. These observations support context-sensitive release of behavior, but they do not identify the internal signals that distinguish territorial ownership from being an intruder.''','Stimulus identity and behavioral consequence are separate variables. Red coloration can influence more than one action, and territorial position changes which action occurs.')
add('Red models discourage entry into a vacant territory','T48','T48_2','2','Red and neutral models presented after the territory owner was removed.', '''Tinbergen tested the deterrent effect of a model by removing a territory owner and observing a neighboring male. Without an owner, a neighbor normally attempted to enter the vacated area. The investigator could therefore measure intrusion rather than attack by the absent resident.

A red-bellied R model delayed the neighboring male’s intrusion appreciably. Neutral N models had scarcely any influence. This comparison retained the physical model in the territory while changing the candidate signal, rather than comparing a model with an entirely empty space.

The result extends the effect of red coloration beyond attacks by territorial owners. It supports a deterrent role during these encounters, but it does not measure recognition of individual rivals or the long-term outcome of natural contests. Delayed entry and attack intensity are different behavioral measurements.''','The owner-removal procedure changes the social situation. Its interpretation rests on the neighbor’s behavior, not on an assumed response by a fish that was no longer present.')
add('Threat posture contributes beyond belly coloration','T48','T48_3','3','Head-down threat posture and ventral-spine display at a mirror.', '''A **threat display** is a behavioral signal directed toward a competitor during an antagonistic encounter. Male sticklebacks can stand nearly vertically, with the head downward and the broad side facing the rival, and thrust the snout toward the substrate. A ventral spine may be erected on the side facing the opponent.

Tinbergen alternated models between this threatening posture and a horizontal swimming position. Threatening models exerted greater influence in both owner-attack and neighbor-intrusion tests, whether their ventral surface was red or neutral.

Posture thus contributes information that coloration alone does not supply. The effect does not establish a single independent posture detector in the brain. It also does not make red coloration irrelevant; the model comparisons indicate that multiple stimulus characteristics can influence the same encounter.''','The photographed fish is responding to its mirror image. The accompanying model experiments, rather than the photograph alone, establish the tested effect of posture.')
add('Tube confinement tests the effect of threat movement','T48','T48_4A','4(A)','Horizontal and upright tube conditions used to constrain the territory owner.', '''A **posture control** changes the animal’s available movement while preserving its presence as a social stimulus. Tinbergen removed a territorial male and returned it confined in a glass tube before the neighbor entered. Tube width determined whether the resident could perform its threatening movement.

A wide tube allowed the resident to adopt the threat posture. A narrow tube constrained it to a horizontal position. The neighboring male was more intimidated when the owner could perform the threat movement than when it remained in the constrained neutral posture.

This manipulation supports a contribution of movement and posture in a live social stimulus. It complements model tests, but confinement can also affect other aspects of the resident’s behavior. The experiment therefore does not isolate a particular muscle command or prove that posture is the only difference perceived by the neighbor.''','The original drawing records the experimental constraint. The causal comparison concerns the permitted posture of the same type of territorial stimulus.')
add('Posture can switch attack to courtship leading','T48','T48_4B','4(B)','Relative postures of the courting male and receptive female.', '''**Courtship leading** is the male’s movement that guides a receptive female toward the nest opening. Tinbergen tested the female’s upright readiness posture using simplified models. A model presented in an appropriate head-up position could elicit leading even when its other characteristics were unlike a normal female stickleback.

The same model could release fighting when presented head downward and leading when presented head upward. Dead fish of another species could also be effective when positioned like a receptive female. The manipulated orientation therefore altered the kind of action released.

The result supports sensitivity to configuration and posture rather than perfect recognition of an entire natural object. It does not establish that all courtship behavior is insensitive to species identity. The response being measured was the particular leading movement under the conditions of the presentation.''','Leading toward the nest and attacking a rival are different actions. A single experimental object can evoke either action when its presentation is changed.')
add('A swollen abdomen is effective in courtship tests','T48','T48_5','5(A–C)','A non-stickleback fish model, a normal-abdomen fish, and a swollen-abdomen dummy.', '''A **gravid** female contains developed eggs and consequently has a swollen abdomen. Tinbergen compared the response to a neutral dead stickleback with the response to a simplified model bearing a swollen abdomen. These presentations tested a feature associated with female reproductive condition.

Males courted the swollen-abdomen dummy, whereas a realistic dead fish with an ordinary abdomen had little effect. Excessive feeding could also enlarge a live male’s abdomen enough to elicit courtship from another male. The feature affected the response despite the stimulus animal’s sex.

These observations concern cue effectiveness in courtship, not an infallible assessment of fertility. The features effective for leading differ from those effective for fighting. The reduced importance of shape in the attack experiment cannot be generalized to every response in the breeding sequence.''','The comparison distinguishes form relevant to courtship from general resemblance to a fish. A stimulus that is adequate for one action may be inadequate for another.')
add('Isolation tests prior social experience','T48','T48_4B','4(B)','Courtship postures associated with the stimulus tests on an isolated male.', '''Tinbergen tested a male reared in isolation after it had built a nest, before it had encountered another stickleback. Red ventral coloration, threatening posture, a female-like upright posture, and a swollen abdomen elicited the corresponding responses reported for normally housed males.

The isolation treatment excluded prior encounters with other sticklebacks as a necessary source of these particular stimulus-response relationships. Nest building provided an observable indication that the male was in the relevant reproductive condition. The models supplied controlled social stimuli during the first test encounters.

An **innate** response, in this experimental sense, does not require the excluded social experience to appear. Isolation does not remove every developmental input or establish complete independence from maturation and nonsocial experience. The result supports a specific experience-independent capacity rather than a universal absence of learning.''','Development under isolation still includes growth and interaction with the physical environment. The claim is limited to the social experience excluded by the preparation.')
add('Egg retrieval contains a repeatable movement sequence','LT38','LT38_1','1(a–f)','Photographic sequence of orientation, contact, inward rolling, and lateral corrections.', '''A **fixed action pattern** is a relatively stereotyped movement sequence released under appropriate stimulus and internal conditions. Lorenz and Tinbergen investigated egg retrieval in nesting graylag geese, _Anser anser_, including birds with domestic-goose ancestry and checks on wild-type birds.

A goose extended its neck toward an egg outside the nest, contacted it with the bill, reached over its far side, and drew the head and neck inward. The egg was pushed toward the nest while side-to-side corrections prevented it from slipping away.

The authors separated the recurring inward sequence from contact-dependent lateral adjustments. Their experiment concerns components of retrieval rather than an entirely feedback-free act. The preparation also limits generalization: domestic ancestry, nest materials, and the individual’s previous experience could affect the responses obtained.''','The photographs preserve the original movement phases. A repeatable sequence and adaptive corrections can coexist within one functionally integrated act.')
add('An outside egg does not trigger instant retrieval','LT38','LT38_1ab','1(a–b)','Neck extension followed by initial contact with the egg.', '''The goose’s initial response to an egg outside the nest often developed gradually. Lorenz and Tinbergen observed brief looks toward the egg, increasingly sustained fixation, and small incomplete head movements before full neck extension. The extended posture could persist for many seconds before the bird rose.

**Appetitive behavior** is activity that brings an animal into a situation in which a more specific action can occur. The goose approached cautiously and initially tried to reach the egg while remaining close to the nest. Contact with the egg followed this visually directed approach.

The presence of a suitable object was therefore insufficient to predict immediate completion of the movement. The observations support separation of approach, initiation, and execution. They do not establish a measured accumulation of neural excitation or a specific duration that every goose must wait before retrieval.''','The reported delay is an observation of behavior, not a direct measurement of a neural threshold. The paper provides no universal latency for the response.')
add('Visual approach and tactile acceptance are separable','LT38','LT38_1ab','1(a–b)','Visual orientation followed by a bill-contact test.', '''Lorenz and Tinbergen found that smooth objects with a roughly continuous outline could elicit the goose’s initial neck extension. Once the bill reached the object, a light contact tested its surface. The characteristics sufficient for visual approach were therefore broader than those sufficient for continued retrieval.

A rounded rubber toy and a balloon inflated to goose-egg size attracted approach but were abandoned after gentle contact. A hard-boiled, peeled duck egg was instead eaten after this contact test. These contrasting outcomes changed with the surface properties encountered by the bill.

**Tactile information** is sensory information obtained through contact. The observations support successive visual and tactile contributions to response selection. They do not identify the receptor cells that detect hardness or the neurons that choose between rolling, rejection, and feeding.''','A sign stimulus may be a combination encountered over time. Initial attraction to an object does not prove that the entire ensuing action has already been selected.')
add('Protruding edges redirect rolling into nibbling','LT38','LT38_3','3','A goose nibbling the exposed edges of an artificial egg.', '''The goose could begin to roll an object and then change its behavior when an exposed rim or protruding attachment became available. Lorenz and Tinbergen presented an open wooden cube, a wooden toy with attached features, and a cardboard egg with paper fringes around its seam.

The cube was rolled until its opening faced upward, after which the bird nibbled the exposed rim. Small attachments on the toy and fringes on the cardboard egg also elicited nibbling. Ordinary right-angled edges of a closed cube did not necessarily interrupt retrieval.

A **response switch** is a change from one action to another as stimulus information changes. These tests support feature-dependent selection during the encounter, rather than an irreversible choice at first sight. The proposed relation to removal of broken eggs is distinct from identification of its neural mechanism.''','A rim associated with an otherwise egg-like object was effective. The paper does not claim that every edge encountered anywhere releases the same nibbling response.')
add('Egg-like shape is not required for every retrieval phase','LT38','LT38_5','5','Retrieval of a light wooden cube rather than a natural egg.', '''Lorenz and Tinbergen reported a broad range of objects capable of attracting approach and retrieval early in their experiments. A wooden cube could be pushed toward the nest, and cylinders were also accepted under some conditions. Object color had no reported decisive effect in their goose preparation.

The cube differed markedly from a natural egg in outline and movement on the substrate. Its acceptance therefore contradicted an explanation requiring complete resemblance to a goose egg. Very large and very small objects introduced additional mechanical constraints, so failure at a size extreme was difficult to assign solely to perception.

Stimulus selectivity must be evaluated for the animal and action being tested. The importance of red coloration in stickleback encounters does not imply an equivalent color rule for goose retrieval. These tests also do not establish that object recognition remains unchanged throughout incubation.''','Object acceptance is measured behaviorally. Mechanical inability to move an object and failure to accept it as a stimulus are different explanations for an unsuccessful trial.')
add('Inward rolling and lateral guidance differ in control','LT38','LT38_1ef','1(e–f)','Lateral bill corrections that maintain the egg beneath the bill.', '''The **sagittal plane** divides the body into left and right portions. During retrieval, the goose’s inward head-and-neck movement occurred approximately in this midline plane. Lateral movements shifted the bill from side to side as the egg threatened to leave its supporting surface.

Lorenz and Tinbergen observed larger lateral corrections when the egg deviated more strongly, particularly while moving up the nest rim. The direction and extent of those corrections varied with the egg’s displacement. The inward movement was much more stereotyped in their observations.

A **taxis** is an orientation response guided by current sensory information. The authors interpreted lateral guidance as contact-controlled taxis accompanying a centrally coordinated inward sequence. This behavioral decomposition supports different control relationships, but it does not identify two anatomically separate neural circuits.''','The distinction concerns how components depend on sensory input. It does not require that the components operate independently in the intact animal.')
add('Loss of the egg can spare the inward movement','LT38','LT38_4cd','4(c–d)','Escape of an oversized object followed by continued empty movement.', '''When an egg slipped from the bill, the inward head-and-neck movement could continue even though the object was no longer being transported. Lorenz and Tinbergen also recorded empty continuation after an oversized artificial egg escaped suddenly from between bill and breast.

The lateral balancing movements disappeared when there was no object to stabilize. The head instead continued along approximately the body’s midline. Thus, removing the transported object changed one component of the response while sparing another for the remaining movement.

**Open-loop execution** describes movement that can continue without the tested ongoing feedback. This result supports relative independence of the inward sequence from current egg contact. It does not establish independence from every sensory input, nor guarantee successful egg retrieval after the initiating stimulus is lost.''','Continuation without the object is evidence about execution. It does not imply that initiation occurs without an appropriate stimulus or internal condition.')
add('Cylinder trials reveal a sensory-mechanical confound','LT38','LT38_1ef','1(e–f)','The natural lateral corrections whose dependence was tested with substitute objects.', '''A **confound** is an additional difference that can contribute to an experimental outcome. Lorenz and Tinbergen initially tried to reduce lateral instability by presenting a plaster cylinder on a smooth wooden board. The altered object and surface were intended to simplify the egg’s movement.

The unfamiliar board disturbed the goose, and the cylinder was often contacted away from its center. It could consequently deviate sideways rather than roll straight. When it did deviate, the compensatory bill movement differed in timing from the corrections accompanying a normal egg.

The cylinder did not provide a clean removal of lateral feedback. Its deviations nevertheless linked the direction of bill correction to the object’s movement. The authors’ account distinguishes an informative observation from a fully controlled exclusion of alternative influences.''','The image is the original natural-retrieval reference, not a picture of the cylinder apparatus. The cylinder trial and its limitations are described in the article’s text.')
add('A sliding cube removes the need for lateral corrections','LT38','LT38_5','5','A light cube pushed toward the nest without ordinary lateral balancing.', '''Lorenz and Tinbergen used a small light wooden cube as a more stable substitute for an egg. Unlike an egg, it remained on the substrate without preferential sideways rolling. It could also rest on a broad face against the two sides of the lower bill.

The goose pushed the cube directly toward the nest without the ordinary side-to-side balancing movements. The inward retrieval component remained available while the unstable object trajectory that normally elicited lateral correction was removed.

This is a **component-removal test**: the experimental stimulus reduces one demand while preserving another. The result supports contact-dependent correction rather than an obligatory lateral movement built into every retrieval. It does not establish that the remaining inward movement is unaffected by all tactile or postural signals.''','The cube changed the mechanical demand for balancing. The retained inward movement and absent lateral corrections are the relevant contrasting observations.')
add('An oversized object can cause mechanical failure','LT38','LT38_4ab','4(a–b)','Initial contact and jamming during retrieval of an oversized cardboard egg.', '''Lorenz and Tinbergen presented a large cardboard egg that demanded a different neck curvature from a natural egg. The bill initially approached at an unfavorable angle and slipped, so the investigators sometimes assisted the beginning of the movement. The object then became trapped between bill and breast.

The goose did not reliably replace the usual neck flexion with a new transport strategy. Some attempts stalled and ended with the bird upright, without the nest-settling movement that ordinarily followed successful retrieval. The object could be attractive yet mechanically incompatible with execution.

**Motor flexibility** is the capacity to change movement in response to altered demands. These trials support limited adjustment of the tested inward sequence. They do not establish that geese lack flexible behavior generally, and initial assistance prevents treating every phase as an unassisted response.''','The experimental problem was the relation between body movement and object dimensions. Attraction to the object and successful transport were measured as separate outcomes.')
add('Object escape separates continuation from success','LT38','LT38_4cd','4(c–d)','Sudden object escape and subsequent empty inward movement.', '''In some oversized-object trials, the cardboard egg escaped sideways rather than remaining trapped. The original film sequence records a lateral response while contact was being lost, followed four film frames later by clear continuation of the inward movement without the object.

The goose’s head subsequently reached the clutch, where the bird moved the eggs and settled. The artificial egg remained outside the nest. Completion of the recurring movement therefore did not imply that the intended external result had been achieved.

A **motor sequence** and its behavioral outcome are different measurements. The observation supports persistence after removal of the transported object, while leaving the surrounding sensory environment intact. Four frames describe the reported film interval; the paper does not supply a frame rate that would justify converting it to milliseconds.''','No time conversion is inferred from the film frames. The article’s observations concern movement persistence and the object’s location after the trial.')
add('Object weight tests the limits of force adjustment','LT38','LT38_5','5','A light cube whose transport was compared with heavier substitutes.', '''Lorenz and Tinbergen compared retrieval of objects lighter and heavier than a goose egg. A very light cube could be lifted toward the breast late in the movement. Objects only somewhat too heavy for retrieval could prevent effective transport despite the goose’s strong neck in other activities.

The authors observed relatively little adjustment of the force used in this particular action. They proposed that coordinated muscle activity was tuned to ordinary egg retrieval rather than scaled freely to every resistance. They also considered a small contact-dependent influence on muscle tone.

**Muscle tone** is sustained muscle activity contributing to posture and resistance. These are proposed physiological explanations of observed movement, not direct muscle recordings. The study did not measure motor-neuron firing, muscle forces in newtons, or the ion channels responsible for activation.''','The photograph documents the light-object condition. The distinction between measured behavior and an unmeasured muscle mechanism prevents assigning stronger physiological conclusions to the result.')
add('Nest geometry can change the outcome of a fixed movement','LT38','LT38_1cd','1(c–d)','Inward rolling toward the nest and lifting of the transported egg.', '''Lorenz and Tinbergen found that retrieval was usually suited to a goose positioned near the nest rim. The final inward movement helped carry an egg over that rim. Their experimental nest, made with pine needles, was lower and less steep than nests they described from natural settings.

When an egg was unusually close, the goose could remain farther back relative to the clutch. The upward component then occurred after the object had already crossed the rim. Eggs were sometimes lifted and balanced for several seconds before falling onto the clutch, occasionally damaging eggs.

The functional outcome depends on the relation between a recurring movement and the environment. A stereotyped action can be effective under its usual geometry and unsuccessful under altered geometry. These observations do not establish absence of all compensation or identify the neural representation of nest position.''','The experimental nest materials and egg placement mattered to performance. Success in a normal configuration cannot be assumed for every artificial arrangement.')
add('Repeated retrieval reduces readiness to execute','LT38','LT38_6abc','6(a–c)','Orientation and an alternative nest-material movement after repeated retrieval.', '''Lorenz and Tinbergen repeatedly presented eggs outside the nest and observed a rapid reduction in the ordinary rolling response. The bird could still look toward an egg and extend its neck after full retrieval had become difficult to elicit. Orientation and execution therefore did not decline together.

**Response-specific fatigue** describes a reduction in the availability of a particular action after repeated performance. The authors distinguished this from loss of responsiveness to the object. Eggs were presented more frequently than they would normally leave the nest under natural conditions.

The retained approach supports separation of stimulus attraction from readiness to execute the inward sequence. It does not identify a depleted transmitter, an exhausted muscle, or a particular inhibitory circuit. Those physiological explanations would require measurements beyond the observed behavioral change.''','The term fatigue refers to the action’s reduced availability in this experiment. It is not evidence that the entire animal was physically exhausted.')
add('An alternative action can follow failed egg retrieval','LT38','LT38_6abc','6(a–c)','Neck extension followed by the nest-material placing movement.', '''After repeated retrieval, the goose sometimes extended its neck toward a real egg but followed with the movement normally used to place nest material behind itself. Lorenz and Tinbergen interpreted this as substitution of another available action when the usual rolling sequence could not be completed.

A **displacement action** is an action appearing in a context where its ordinary function does not fit the immediate situation. The nest-material movement did not reliably transport the egg as the normal inward rolling movement would. The visible stimulus remained effective in attracting attention.

The observation establishes an alternative behavioral sequence after reduced retrieval readiness. The authors proposed competing or unavailable actions as explanations, but did not record neural competition. A description of substitution must remain distinct from a demonstrated physiological mechanism of action selection.''','The photographic sequence documents the alternative movement. Claims about frustration or the goose’s intentions are interpretations, rather than directly measured properties of the trial.')
add('Experience can narrow acceptance of substitute objects','LT38','LT38_6de','6(d–e)','Avoidance of an artificial egg after changes in response readiness.', '''Early in the experiments, the goose accepted many substitute objects. Around the middle of incubation, after a pause of several days, it stopped responding to previously effective substitutes. Even a small intact hen’s egg failed to release retrieval, whereas real goose eggs remained effective.

The continued response to goose eggs argued against a general disappearance of the rolling action. Lorenz and Tinbergen attributed the narrower object acceptance to individual experience, while acknowledging limits of their preparation. Acceptance was assessed through behavior rather than through a measured perceptual representation.

**Stimulus selectivity** is the restricted range of properties that elicit a response. It can change despite a recurring motor pattern. The observations challenge an interpretation in which every aspect of an innate action is immune to experience, but they do not isolate the particular learned cue or its neural storage.''','The photographed avoidance belongs to the changed-response observations. The evidence for increased selectivity includes preserved retrieval of real goose eggs and rejection of formerly accepted substitutes.')
add('Hatching changes the response to exposed shell edges','LT38','LT38_3','3','Edge nibbling, the response that changed near hatching.', '''Lorenz and Tinbergen observed destructive nibbling when externally incubated, beginning-to-hatch eggs were placed under their experimental goose. The exposed shell margins elicited vigorous biting. The investigators removed these eggs before the chicks were harmed further.

Two days later, when the goose’s own chicks began to hatch, the response to exposed shell margins had disappeared. The bird attended to and gently contacted the hatching eggs without the earlier biting, even when openings were presented directly.

**State-dependent response selection** means that the same stimulus property can have a different effect as the animal’s condition changes. The authors proposed that sounds from hatching eggs might contribute to this transition, but did not experimentally establish that explanation. The two-day contrast is not a controlled isolation of auditory, hormonal, or experiential causes.''','The source photograph records the earlier edge-nibbling action. The later response change is reported in the text; no invented diagram or substitute photograph represents it.')
add('Stimulus tests do not identify a release circuit','J21','J21_2','2(A–C)','Brain visibility through the skull and dissected dorsal brain anatomy.', '''A **neural circuit** is a connected set of neurons whose activity contributes to processing information or producing behavior. The classic stimulus experiments identified behavioral relationships, but did not record the circuits that respond to red coloration, posture, or egg contact.

James and Bell developed direct brain injections in adult sticklebacks to test candidate molecular influences on territorial aggression. The diencephalon, a central forebrain region, was visible through the thin skull and could be targeted for delivery. The paper also documents the telencephalon, the anterior forebrain, in the dissected preparation.

A molecular intervention can change responsiveness without identifying a complete sensory-to-motor pathway. The authors measured aggression and respiration after candidate-gene delivery. Their results do not locate a dedicated red-stimulus detector, demonstrate a specific synaptic connection, or explain the goose’s inward rolling mechanism.''','Brain anatomy provides access to experimental targets. It does not by itself establish which neurons mediate the response to a particular stimulus feature.')
add('Direct brain access permits controlled delivery','J21','J21_1','1','The published surgical rig for supported brain injections.', '''James and Bell used a supported preparation in which anesthetized sticklebacks received water flow over the gills while the head was stabilized. This permitted delivery through the skull without an open craniotomy. Saline and control constructs provided comparisons for the effects of the procedure itself.

A fine needle with an outer diameter of 0.210 mm delivered approximately 300 nL per injection. Delivery at multiple depths increased the spread of expression, while bilateral delivery totaled approximately 600 nL. The experiment therefore manipulated both what was delivered and how broadly it reached brain tissue.

Controlled access makes molecular tests possible in behaviorally characterized adult fish. It does not guarantee delivery to one neuronal type or one nucleus. The resulting behavioral change must be interpreted alongside tissue verification, recovery measurements, and the control treatments.''','The photograph is the authors’ apparatus figure, reproduced directly. The delivery method supports an experiment on behavior rather than constituting evidence of an identified aggression circuit.')
add('Histology verifies the spatial extent of expression','J21','J21_3AB','3(A–B)','Restricted expression after one injection and broader expression after delivery at multiple depths.', '''**Histology** is the examination of tissue structure, including labeled cells within a region. James and Bell used fluorescent reporter proteins to verify expression after viral delivery. A single injection could produce a local signal, while injections at multiple depths produced broader expression in a hemisphere.

**Viral-mediated transgenesis** uses a viral vector to deliver a gene construct into cells. The replication-deficient vector carried a chosen payload and promoter. Fluorescence was absent in saline-injected controls, distinguishing reporter expression from the untreated tissue’s background signal.

The tissue measurements verify delivery and distribution of expression. They do not establish that every labeled cell contributes to aggression or that all relevant cells were transfected. Broad expression also limits a claim that the behavioral effect originates in one uniquely identified anatomical site.''','Fluorescence labels expression rather than neuronal firing. A successful tissue-delivery measurement and a functional circuit measurement are different experiments.')
add('Promoter choice determines the intervention window','J21','J21_3EFG','3(E–G)','Fluorescent expression at two, three, and four weeks; scale bars retained.', '''A **promoter** is a DNA regulatory sequence that influences transcription of an associated gene. James and Bell compared promoter choices in their delivery system. The short-term mCMV construct produced detectable expression between four and seven days, whereas hCMV supported expression over a longer period.

With the long-term construct, fluorescence was weak initially and became strong around days 13–14. The displayed tissue preparations retain the two-, three-, and four-week labels. Territorial behavior was measured at 14 and 16 days after injection, within the verified expression window.

A delayed molecular intervention differs from an immediately presented sign stimulus. Aligning behavior with the expression window supports a test of altered responsiveness. Reporter fluorescence does not quantify the concentration of every delivered protein or establish the moment when a particular neuron changes its activity.''','Expression timing was verified independently of the behavioral trials. The study did not use fluorescence intensity as a direct reading of aggression.')
add('Peptide manipulation tests an internal influence','J21','J21_3CD','3(C–D)','Transfected cells in the diencephalon with fluorescence and scale bars intact.', '''A **neuropeptide** is a peptide signal that can influence neural function. James and Bell selected arginine vasopressin, AVP, as a candidate related to aggression, alongside the fish peptide vasotocin. Their viral construct encoded human AVP; it was not a selective manipulation of the fish’s native vasotocin gene.

The construct was delivered broadly into the stickleback diencephalon. The investigators compared territorial responses before and after expression and included a fluorescent-protein control. Their experimental question concerned whether altered peptide-related signaling could change aggression in the same fish.

A **receptor** is a protein that responds to a signaling molecule and initiates cellular effects. The manipulation did not identify which receptor population, synapse, or ion channel mediated the behavioral change. Broad and potentially ectopic expression prevents equating the intervention with the normal location or magnitude of endogenous signaling.''','Ectopic expression means expression in locations where it would not ordinarily occur. The authors explicitly discuss this limitation for their broad peptide manipulation.',brain=True)
add('Acute vasotocin increases respiration during recovery','J21','J21_7','7','Respiration following vasotocin versus saline injection, with time axes intact.', '''James and Bell injected exogenous vasotocin directly into the brain and compared recovery with saline-injected controls. **Exogenous** means supplied experimentally from outside the organism. Respiration was measured as opercular movements, the movements of the gill covers associated with breathing.

The vasotocin group developed higher respiration within 15 minutes, and the difference persisted for more than two hours. The greatest separation occurred around 45–90 minutes after injection. The saline group provided a comparison for recovery after the same type of brain-injection procedure.

The result establishes a physiological effect of administered peptide in this preparation. It does not make respiration equivalent to aggression or directly measure receptor activation. Acute peptide delivery and delayed expression of an AVP construct also differ in timing, distribution, and likely concentration.''','The physiological outcome is measured breathing, not a recording of neuronal discharge. The plotted respiration count corresponds to a 20-second observation interval.',brain=True)
add('AVP expression increases charging within individuals','J21','J21_8','8','Paired baseline and post-transfection charge counts for EYFP, AVP, and MAOA.', '''James and Bell tested territorial aggression before and after delivery of the AVP construct. A **charge** was a lunge directed toward a smaller male intruder confined in a glass flask. The investigators counted responses during five minutes after the focal male first oriented toward the intruder.

Mean charges in the AVP group increased from 9.7 at baseline to 18.8 after transfection. The fluorescent-protein control did not exhibit a corresponding consistent increase. Behavioral scoring was blind to treatment, and the same focal fish contributed measurements before and after intervention.

This paired result supports an influence of the candidate manipulation on aggression. It does not establish a uniform increase in every fish or a robust separation of the treatment groups by their final scores alone. The article reports substantial individual variation and distinguishes paired change from between-group comparison.''','The numbers are average counts over the five-minute trials, averaged across the two observations in each condition. They are not rates recorded continuously over days.',brain=True)
add('Monoamine oxidase changes transmitter availability','J21','J21_3CD','3(C–D)','Transfected brain cells, the tissue context for candidate-gene delivery.', '''**Monoamine oxidase** is an enzyme that metabolizes several monoamine neurotransmitters, including serotonin, dopamine, and norepinephrine. A **neurotransmitter** is a chemical signal used in communication involving neurons. Enzymatic metabolism can change how much active transmitter remains available for signaling.

James and Bell delivered a mouse MAOA construct to sticklebacks. Teleost fishes possess one monoamine oxidase gene rather than the two MAO genes found in mammals. The experiment consequently tested a supplied mammalian enzyme construct in fish, not a selective increase of an independently identified fish MAOA subtype.

A proposed sequence links increased enzyme expression to altered transmitter availability and changed neuronal responsiveness. The study measured territorial behavior and respiration, but did not quantify downstream transmitter concentrations or receptor currents. The biochemical explanation is therefore supported by enzyme function and the intervention, while its detailed neural mediation remains unresolved.''','The figure verifies transfected cells rather than depicting enzyme chemistry. No new biochemical pathway diagram has been created.',brain=True)
add('MAOA alters both aggression and respiration','J21','J21_9','9','Paired respiration measurements in opercular beats per 20 seconds.', '''James and Bell found that MAOA-transfected fish increased their mean territorial charges from 12.1 to 19.1 during the five-minute test. Individual changes varied more than in the AVP group. The increase was assessed relative to the same fish’s baseline behavior.

Respiration changed in the opposite direction: the MAOA group decreased from 40.8 to 38.1 opercular beats per 20 seconds. The AVP and fluorescent-protein control groups did not exhibit the same consistent decline. Thus, more charging did not simply track higher resting respiration across these interventions.

The joint behavioral and physiological result supports an effect of the supplied enzyme construct. Reduced serotonin or norepinephrine availability was a proposed mechanism, not a directly measured intermediate. The study did not establish a specific receptor-to-ion-channel pathway linking enzyme activity to the increased charges.''','An ion channel is a membrane protein through which ions move. The experiment did not record channel currents or determine which channels participate in this behavioral effect.',brain=True)
add('Paired trials distinguish change from individual variation','J21','J21_4','4','The authors’ baseline, injection, and post-transfection trial timeline.', '''A **within-individual comparison** assesses change in the same animal across experimental conditions. James and Bell measured each focal male twice before injection and twice after expression. Nearly every fish faced the same intruder throughout these four territorial challenges.

The candidate-gene groups increased charging relative to their own baselines, whereas the fluorescent-protein control did not exhibit a consistent increase. Final charge counts overlapped substantially between groups. Blind behavioral scoring reduced the possibility that knowledge of the injected construct influenced recorded responses.

The comparison supports a conclusion about longitudinal change rather than complete separation of aggressive and nonaggressive groups. Controls for injection and reporter expression strengthen that conclusion, but do not identify the exact molecular intermediate. Repeated exposure to an intruder also remains part of the experimental context.''','Baseline trials occurred before delivery and the later trials during the verified expression window. The published timeline is reproduced rather than reconstructed from the reported dates.',brain=True)
add('Recovery time and gene-expression time are different','J21','J21_5','5','Respiration during recovery after direct brain injection.', '''James and Bell monitored physiological recovery after brain injection rather than assuming that an animal’s behavior was immediately unaffected. Respiration peaked around one hour after surgery, returned near baseline by three hours, and remained stable over the subsequent observations.

Normal swimming and use of the water column returned rapidly in successful preparations. Saline-injected fish did not exhibit a consistent increase in later aggression. Candidate-gene behavior was tested much later, at 14 and 16 days, when reporter measurements supported strong expression.

The **time course** of a manipulation includes distinct procedural and biological effects. Acute recovery from injection is not the same process as development of transgene expression. The controls reduce a simple explanation based on surgery alone, but they do not resolve every lasting cellular effect of broad delivery.''','The plotted physiological recovery concerns hours, whereas the behavioral gene-manipulation window concerns days. The two scales must not be treated as interchangeable.',brain=True)
add('A brief intrusion permits a controlled molecular test','B17','J21_2C','2(C)','Dorsal brain anatomy in James and Bell (2021); original scale bar 2 mm.', '''Bukhari and colleagues studied nesting male sticklebacks maintained at 18°C in separate tanks, visually isolated from neighbors. Experimental males encountered a smaller unrelated male confined in a flask. Controls received an empty flask at the same time, separating the social challenge from insertion of the object.

The flask remained for five minutes. Brain tissue was collected at 30, 60, or 120 minutes measured from its introduction. The investigators separately analyzed the telencephalon and diencephalon using RNA sequencing, which estimates the abundance of RNA transcripts in a tissue sample.

This design tests molecular consequences of a brief social encounter under controlled conditions. It does not measure the neurons that initially detect an intruder. The first molecular sample was collected long after the immediate behavioral response could begin.''','The clock starts at flask introduction, not at removal five minutes later. Empty-flask controls retain handling and presentation while excluding the confined conspecific.',brain=True)
add('A social challenge produces successive transcript waves','B17','B17_2B','2(B,D)','Temporal expression patterns and functional associations of telencephalic gene clusters.', '''**Gene expression** includes production of RNA from DNA. Bukhari and colleagues compared transcript abundance after an intruder presentation with abundance after an empty-flask control. The number and direction of changed transcripts varied across the 30-, 60-, and 120-minute samples.

The greatest overall transcriptomic response occurred at 60 minutes. Expression was generally reduced at the earlier time points, whereas many diencephalic transcripts increased at 120 minutes. Genes changing at one time point overlapped only partly with those changing at another.

The social encounter therefore produced a dynamic molecular response rather than one fixed signature. These measurements establish RNA-abundance differences, not immediate changes in protein concentration or neuronal firing. The later transcript waves were not proven to cause the preceding attacks.''','Up-regulation and down-regulation are comparisons with the matched control condition. A transcript’s abundance and a neuron’s electrical output are different measurements.',brain=True)
add('The two brain regions can respond in opposite directions','B17','B17_1F','1(F)','Opposite-direction transcript responses between regions at 120 minutes.', '''Bukhari and colleagues analyzed the telencephalon and diencephalon separately rather than pooling the entire brain. Transcript responses in the two regions were strongly aligned at 30 and 60 minutes. The later sample contained a subset with opposite response directions.

At 120 minutes, these discordant genes increased in diencephalon but decreased in telencephalon. A whole-brain average could consequently obscure a localized response by combining increases with decreases. Regional sampling preserved the distinction between those molecular changes.

**Regional specificity** means that an effect depends on where it is measured. The result supports location-dependent responses to the same social event, but each sample still contained many cell types. It does not assign the discordant response to a single neuronal population or demonstrate communication between the regions.''','The scatterplots compare the two tissue regions at corresponding times. Their associations are not anatomical connections or recordings of synaptic transmission.',brain=True)
add('Regulatory networks propose coordinated gene control','B17','B17_3','3','The published inferred network of transcription factors and gene clusters.', '''A **transcription factor** is a protein that influences transcription by interacting with regulatory DNA and other components of gene control. Bukhari and colleagues inferred a transcriptional regulatory network and compared predicted targets with groups of genes sharing temporal response patterns.

Some candidate regulators and their proposed targets changed in similar sequences across 30, 60, and 120 minutes. For example, the expression of irf8 and cebpb tracked groups with little early change, reduced expression at 60 minutes, and increased expression at 120 minutes.

The relationships support hypotheses about coordinated regulation after a territorial challenge. The network is a published computational inference, not a directly reconstructed circuit of connected neurons. The study did not perturb each regulator or prove that every displayed edge represents a causal effect in the challenged fish.''','The source network is reproduced unchanged. Its nodes concern gene regulation; they must not be interpreted as neurons or as measured synaptic pathways.',brain=True)
add('Chromatin-associated changes persist after the encounter','B17','B17_4D','4(D)','Published chromatin-mark tracks near the Pparg locus.', '''**Chromatin** is DNA together with associated proteins that organize and regulate access to the genetic material. Bukhari and colleagues measured H3K27 acetylation, a chemical modification of a histone protein used as a marker of active regulatory chromatin. The measurements came from diencephalon after challenge or control presentations.

They compared 30- and 120-minute samples and found stronger later changes near many genes. At the Pparg locus, increased regulatory marking at 120 minutes accompanied increased transcript abundance. Other loci had distinct temporal patterns rather than one common response.

This relationship links a brief encounter with changes in gene regulation lasting well beyond the five-minute presentation. The histone mark is a proxy for regulatory state, not a direct measure of every aspect of physical DNA accessibility. Associated RNA changes do not alone establish causal direction.''','The original locus tracks preserve time labels, genomic context, and comparison conditions. No tracks have been re-plotted or reconstructed.',brain=True)
add('Stereotyped acts coexist with a changing internal state','B17','B17_2B','2(B,D)','Telencephalic temporal gene-expression patterns and functional associations.', '''Bukhari and colleagues grouped genes by their response over 30, 60, and 120 minutes. Some groups peaked early and declined, while others reached their largest changes later. The social challenge therefore influenced several molecular processes on different time scales after the visible encounter ended.

The authors proposed roles in recovery, future responsiveness, and social memory. Genes associated with learning-related functions appeared among later responses. These were hypotheses based on expression and chromatin measurements; the experiment did not directly test retention of the intruder’s identity or the location of the encounter.

A recurring motor action can be released within an internal state that changes with experience and recent stimulation. Molecular plasticity does not erase the classic observations of stereotyped movement, and stereotypy does not establish an unchanging brain. The measured time-dependent responses constrain both interpretations.''','Memory formation and changed future behavior remain proposed consequences in this study. The tested outcomes were molecular responses to the controlled challenge.',brain=True)
# The protocol slide uses primary brain anatomy; the source of the image is
# distinct from the study of the molecular time course.
slides[38]['figure']=figure('J21','J21_2C','2(C)','Dorsal brain anatomy; original scale bar 2 mm.')
slides[38].pop('figures',None);slides[38]['layout']='figure-right'
slides[41]['figure']=slides[41].pop('figures')[0];slides[41]['layout']='figure-right'
for sl in slides:
 if sl.get('figures') and any(Path(f['path']).stem in ['J21_3CD','J21_7','J21_8','J21_9','J21_5','B17_1F'] for f in sl['figures']):
  sl['primary_figure_height']=3.2
assert len(slides)==44,len(slides)
for s in slides:
 words=len(' '.join(s['body']).split());assert 90<=words<=170,(s['title'],words)
items=[
('Sign stimuli are selective cues.','Restricted features can release particular actions, but their effects depend on posture, territorial context, reproductive condition, and the response measured.'),
('Fixed patterns and feedback coexist.','Goose retrieval combines a stereotyped inward movement with lateral corrections dependent on contact and the object’s deviations.'),
('Continuation is not successful retrieval.','The inward movement can persist after object loss; completion of a motor sequence does not prove that the egg reached the nest.'),
('State and experience alter release.','Repeated retrieval reduces execution readiness, experience narrows object acceptance, and response selection changes near hatching.'),
('Interventions require matched controls.','Candidate-gene delivery changes aggression within individuals, but broad expression and overlapping final scores limit localization and generalization.'),
('Molecular responses have distinct time scales.','A five-minute challenge changes RNA and chromatin-associated marks over 30–120 minutes; these measurements do not directly establish a release circuit or memory.')]
spec={'lecture':2,'content_slides':44,'theme':'denim-ivory','title_image':figure('LT38','LT38_1a','1(a)','A graylag goose extending its neck toward an egg outside the nest.'),'slides':slides,'takeaways':{'items':[{'lead':l,'text':t}for l,t in items],'cite':'; '.join(R[k][0]for k in R),'refs':[ref(k)for k in R]}}
(ROOT/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n');print('Wrote',len(slides),'content slides')
