"""Lecture 60: teaching prose anchored to original seahorse experiments."""
from pathlib import Path
import json,re
D=Path(__file__).parent
meta=json.loads((D/'reference_metadata.json').read_text())
keys=['brain','juvenile','feeding','pairing','kisspeptin','vasotocin','photo']
R={};C={};U={}
for k in keys:
 m=meta[k];authors=', '.join(x.get('given','')+' '+x['family'] for x in m['author']);year=m['published']['date-parts'][0][0]
 pages=m.get('page') or m.get('article-number','');pages='e53734, 1–11' if k=='brain' else pages
 R[k]=f"{authors} ({year}). {m['title'][0]}. {m['container-title'][0]} {m.get('volume','')}: {pages}. https://doi.org/{m['DOI']}"
 C[k]=m['author'][0]['family']+' et al. ('+str(year)+')';U[k]='https://doi.org/'+m['DOI']
F={}
def fig(key,p,num,desc):F[key]={'path':f'figures/{key}.png','kind':'article','caption':C[p]+f', Fig. {num}. '+desc,'source_url':U[p]}
for k,p,n,d in [
('animal','photo','2H','Longsnout seahorse under natural white light.'),
('j1','juvenile','1A–D','Searching, locking, capturing, and swallowing in a newborn.'),('j1a','juvenile','1A','A newborn searches for Artemia.'),('j1b','juvenile','1B','Visual locking before a strike.'),('j1c','juvenile','1C','Rapid capture with the snout.'),('j1d','juvenile','1D','Swallowing after prey capture.'),
('retina','juvenile','4A–F','Retinal structure from 1 to 30 days after birth.'),('retina_ab','juvenile','4A–B','Newborn eye and labeled retinal layers.'),('retina_cf','juvenile','4C–F','Eye growth from 3 to 30 days after birth.'),('snout','juvenile','3A–F','Cartilage and bone during snout development.'),('snout_abc','juvenile','3A–C','Snout skeleton at 2, 5, and 7 days after birth.'),('snout_def','juvenile','3D–F','Snout skeleton at 10, 14, and 24 days after birth.'),('gut','juvenile','5A–K','Intestinal development after birth.'),('gut_gh','juvenile','5G–H','Intestinal loops and wall layers at 10 days after birth.'),
('b13','brain','13','Sagittal brain histology with the five major divisions.'),('b7','brain','4','Gross brain anatomy with a prominent optic tectum.'),('b20','brain','20','Five histologically identified tectal layers.'),('b14','brain','14','Olfactory tissue in the snout.'),('b15','brain','15','Olfactory epithelium with ciliated sensory cells.'),('b21','brain','21','Epithalamus, thalamus, and hypothalamus.'),('b25','brain','25','Periventricular hypothalamic cell population.'),('b26','brain','26','Tuberal hypothalamic cell population.'),('b27','brain','27','Neural and glandular regions of the pituitary.'),('b30','brain','30','Cerebellum behind the optic tectum.'),('b31','brain','31','Molecular, Purkinje-cell, and granular cerebellar layers.'),('b32','brain','32','Sagittal brain section extending into the medulla.'),('b35','brain','35','Spinal cord cross-section and central canal.'),('b36','brain','36','Hindbrain tissue bordering the fourth ventricle.'),('b39','brain','39','Compact brain organization at 1 day after birth.'),('b44','brain','44','Tectal capillaries at 6 days after birth.'),('b47','brain','47','Tectal vessels at 14 days after birth.'),('b48','brain','48','Developing cerebellar Purkinje cells at 14 days.'),('b50','brain','50','Vascularized tectum with five layers at 35 days.'),('b51','brain','51','Cerebellar Purkinje cells at 35 days.'),
('f1a','feeding','1a','Approach speeds for successful and failed feeding attempts.'),('f1b','feeding','1b','Copepod response distances to approaches and strikes.'),('f1c','feeding','1c','Copepod escape velocities during approaches and strikes.'),('f2b','feeding','2b','Successful feeding sequence recorded by holography.'),('f3cd','feeding','3c–d','Particle motions around successful and failed approaches.'),('f4','feeding','4a–c','Flow deformation at different approach speeds.'),('f5','feeding','5a–c','Flow deformation around different seahorse head postures.'),('f6','feeding','6a–b','Flow deformation around a stickleback head.'),
('m2','pairing','2','Partner and stranger interactions differ in luminance change.'),('m3','pairing','3','Exploratory expression profiles of paired and unpaired groups.'),('m4','pairing','4A,D,G','Overlap between seahorse and prairie-vole expression rankings.'),('k5','kisspeptin','5','Kiss2 and GPR54-2 transcript distribution.'),('k6a','kisspeptin','6A–B','Kiss2 expression and testis histology during sexual development.'),('k6b','kisspeptin','6B(a–d)','Testis histology from immaturity to maturity.'),('k7','kisspeptin','7','Kiss2 and receptor expression across pregnancy stages.'),('k8','kisspeptin','8','Endocrine transcript responses at 3 and 6 hours after Kiss2-10.'),('k9','kisspeptin','9','Serum testosterone after Kiss2-10 administration.'),('v4bc','vasotocin','4B–C','Vasotocin transcripts in the preoptic area.'),('v4ef','vasotocin','4E–F','Isotocin transcripts in the preoptic area.'),('v5a','vasotocin','5A','Circulating estrogen and testosterone after vasotocin.'),('v5b','vasotocin','5B(a–c)','Normally released and prematurely released young.'),('v6','vasotocin','6','Pituitary and brood-pouch transcript responses to vasotocin.')]:fig(k,p,n,d)
S=[]
def slide(title,ps,ks,body,extra):
 paras=body.split('|');assert len(paras)==3
 sl={'layout':'figure-right' if len(ks)==1 else 'figures-right','title':title,'body':paras,'cite':'; '.join(C[p] for p in ps),'refs':[R[p] for p in ps],'transcript':[[re.sub(r'\*\*|_', '',paras[0]),[extra]],* [re.sub(r'\*\*|_', '',x) for x in paras[1:]]]}
 if len(ks)==1:sl['figure']=F[ks[0]]
 else:sl['figures']=[F[k] for k in ks];sl['primary_figure_height']=2.25
 S.append(sl)
slide('Newborn seahorses already capture live prey',['juvenile'],['j1'],
'Newborn lined seahorses, _Hippocampus erectus_, capture live **Artemia**, small crustaceans used as food, immediately after leaving the male. Their feeding behavior already combines visual search, target tracking, rapid head rotation, and ingestion. Feeding competence therefore begins before the feeding skeleton reaches its later degree of ossification.|Sun and colleagues recorded animals from 1 to 30 days after parturition, meaning birth. Newborns were about 9.2 mm tall and successfully captured prey in about 77% of feeding attempts under the study conditions.|Across development, body growth increased capture reach and food intake. Early independence depends on functional sensory and motor coordination together with continued maturation of the snout and digestive tract.',
'The study combined high-speed recordings with histology of the eyes, snout, and intestine rather than inferring feeding ability from body size alone.')
slide('Prey capture combines four coordinated actions',['juvenile'],['j1'],
'**Pivot feeding** brings the mouth toward prey by rotating the head upward, followed by suction into the tubular snout. In newborn lined seahorses, this behavior formed a sequence of searching, locking, capturing, and swallowing. Each action changes the relationship between the animal and its target.|During searching, the eyes moved independently. During locking, the seahorse swam and turned to keep the prey ahead of its head. Capture began when the target entered the available capture distance, with head rotation and mouth opening taking less than 4 ms.|Swallowing restored the cranial and hyoid apparatus toward rest while ingested water and fragments exited through the gill opening. Fast acquisition and slower recovery are distinct components of the same feeding sequence.',
'The hyoid apparatus is the skeletal assembly beneath the mouth that participates in expansion and recovery during suction feeding.')
slide('Independent eye movements precede target tracking',['juvenile'],['j1a','retina_ab'],
'The two eyes of juvenile lined seahorses moved independently during prey search. After prey entered the visual field, the animal changed its swimming and turning so that the target remained in front of the head. These observations separate broad searching movements from target-directed tracking.|The newborn eye already contained an organized retina, the neural tissue that receives light. Rod and cone photoreceptors were present, together with a pigmented outer region and recognizable internal layers. The sensory tissue was therefore developed when independent feeding began.|Target tracking and the final strike operated on different time scales. Swimming maintained alignment before the brief capture movement, which could then bring the small terminal mouth to a nearby crustacean.',
'Sun and colleagues observed eye and body movements behaviorally; their recordings did not measure the activity of individual visual neurons.')
slide('Photoreceptors are present at birth',['juvenile'],['retina_ab'],
'**Photoreceptors** are retinal cells specialized to receive light. Histological sections of newborn lined seahorses contained both rods and cones between the pigment layer and the outer nuclear layer. The pigment layer and organized retinal tissue were already recognizable on the first day after birth.|Sun and colleagues used 4 µm tissue sections stained with hematoxylin and eosin. Their labeled sections distinguish photoreceptor tissue, nuclear layers, the ganglion-cell region, lens, and other ocular structures. This preparation describes tissue organization rather than directly measuring visual resolution.|The same newborn animals performed successful visual prey capture. Retinal differentiation and feeding competence therefore coexist at release, while later growth enlarges an already organized eye.',
'Visual acuity means the ability to distinguish fine spatial detail; this study used histology and feeding observations rather than a behavioral acuity threshold.')
slide('Eye growth preserves the early retinal organization',['juvenile'],['retina_cf'],
'From 3 to 30 days after birth, juvenile lined seahorse eyes increased in diameter as the animals grew. Sun and colleagues reported no major rearrangement of the retinal histology during this period. Growth enlarged the organ while preserving its recognizable internal organization.|The retina was therefore unlike a sensory system that acquires its basic tissue layers only after feeding begins. At birth, the animal already combined an organized eye with successful capture; later increases in capture performance occurred while the existing retinal architecture remained recognizable.|Feeding development involved several tissues at once. Eye enlargement accompanied snout growth, increasing attack distance, and maturation of the digestive tract, so behavioral improvement belonged to the developing animal as a whole.',
'The histological comparison included newborns and animals at several postnatal ages, with the latest illustrated eye sections taken at 30 days.')
slide('The seahorse brain retains five major divisions',['brain'],['b13'],
'The brain of _Hippocampus barbouri_ contains the **telencephalon**, forebrain tissue including the cerebral hemispheres; the diencephalon; the mesencephalon or midbrain; the metencephalon; and the myelencephalon. Senarat and colleagues identified these divisions in sagittal histological sections, which cut along the head-to-tail axis.|The diencephalon contains the hypothalamus, while the midbrain contains the optic tectum. The metencephalon includes the cerebellum, and the myelencephalon includes the medulla, which continues toward the spinal cord. The unusual external body shape therefore accompanies a recognizable teleost brain arrangement.|The study compared tissue organization from 1 to 35 days after birth. Early sections were compact, whereas later sections distinguished the regional and cellular features of these divisions.',
'Teleosts are the major group of ray-finned bony fishes; the named divisions describe anatomical regions rather than individual behavioral modules.')
slide('The optic tectum is a prominent brain region',['brain'],['b7','b13'],
'The **optic tectum**, a midbrain region associated with visual orientation and multisensory processing in fishes, was the most prominent gross brain region in the examined _Hippocampus barbouri_. It lay between the anterior cerebral hemispheres and the posterior cerebellum.|Senarat and colleagues combined dissections, photographs, measurements, and stained tissue sections. In their 35-day animals, the tectum measured about 1,220 µm in length, compared with a cerebellar length of about 714 µm. These measurements describe regional anatomy in that developmental sample.|The authors proposed that the prominent tectum relates to visually guided feeding on mobile prey. This is an anatomical hypothesis connecting brain organization to behavior, rather than a recorded seahorse visual-neuron response.',
'The dissection and histological preparations provide complementary views: external position and internal tissue organization.')
slide('The tectum contains five histological layers',['brain'],['b20'],
'**Laminar organization** means that neural tissue is arranged in layers with different cellular and fiber composition. Senarat and colleagues recognized five layers in the seahorse optic tectum: stratum marginale, stratum opticum, stratum album centrale, stratum griseum centrale, and stratum periventriculare.|These layers extend from the outer tectal surface toward the ventricular region. Their differences in neuronal density and fiber organization divide the tissue into distinct anatomical compartments. The published micrographs preserve this organization at a scale of tens of micrometers.|The five-layer pattern was clear by 35 days after birth. Earlier tissue was less differentiated, so the layered tectum emerged during postnatal brain development while the animal continued growing.',
'The layer names describe marginal, optic, central white, central gray, and periventricular tissue; no seahorse synaptic connection map was measured in this study.')
slide('Tectal vascularization increases during development',['brain'],['b44','b50'],
'**Capillaries** are small blood vessels supplying tissues. In _Hippocampus barbouri_, tectal capillaries became more apparent at 6 days after birth, and small vessels were conspicuous by 14 days. At 35 days, the tectum was highly vascularized and its five layers were distinguishable.|Senarat and colleagues followed these changes in stained sections. Vascular development occurred together with regional differentiation, linking the growth of neural tissue to the organization of its blood supply. The two features progressed within the same developmental sequence.|The authors hypothesized that increasing brain differentiation supports developing predatory ability. The age-dependent vascular and tissue changes provide an anatomical description of maturation, while prey-capture timing requires the separate behavioral evidence.',
'The youngest brain sections were densely packed and lacked the clear substructures that were visible in later animals.')
slide('The cerebellum has three distinct cellular layers',['brain'],['b30','b31'],
'The **cerebellum** lies behind the optic tectum in the seahorse brain. In 35-day _Hippocampus barbouri_, it contained an outer molecular layer, a Purkinje-cell layer, and an inner granular layer. This organization separates dendritic tissue from identifiable neuronal populations.|The molecular layer contained many dendritic fibers. **Dendrites** are neuronal processes that receive synaptic input. Synapses are junctions through which neurons communicate. The middle layer contained conspicuous Purkinje cells, while the granular layer contained densely arranged smaller principal neurons. Senarat and colleagues identified these regions using light microscopy.|Cerebellar differentiation continued after birth rather than appearing fully mature in the youngest animals. Increasing prominence of Purkinje cells and their dendrites accompanied the emergence of the layered tissue organization.',
'The study documents cerebellar anatomy; it did not record cerebellar firing during eye movements or feeding.')
slide('Purkinje cells become conspicuous after birth',['brain'],['b48','b51'],
'**Purkinje cells** are the large neurons occupying the middle layer of the cerebellar cortex. They were difficult to identify in the earliest _Hippocampus barbouri_ sections, became apparent by 14 days after birth, and were prominent by 35 days.|The later cells possessed dendrites extending into the molecular layer, where the study described abundant dendritic fibers. Development therefore involved the emergence of recognizable neuronal shape as well as separation of the three cerebellar layers.|This cellular sequence occurred while tectal layers and blood vessels also became more distinct. Different neural regions matured over overlapping postnatal intervals, producing a more differentiated brain rather than a single abrupt anatomical transition.',
'The 14-day and 35-day sections distinguish increasing cellular prominence within the same named cerebellar layers.')
slide('Olfactory tissue occupies the anterior snout',['brain'],['b14','b15'],
'**Olfactory epithelium** is sensory tissue associated with chemical detection. In _Hippocampus barbouri_, Senarat and colleagues identified olfactory tissue in the anterior snout, surrounding a cavity and containing ciliated sensory cells. The cilia were conspicuous in the higher-magnification sections.|The olfactory tract connected the anterior olfactory region with the forebrain. A **tract** is a bundle of nerve fibers linking regions. Gross and histological preparations therefore located both the peripheral sensory tissue and its connection toward the cerebral hemispheres.|Vision dominates the published prey-tracking observations, but the seahorse head also contains a distinct chemical-sensory apparatus. These sensory structures occupy different anatomical locations and can contribute different kinds of information during interactions with the environment.',
'The published captions use olfactory-bulb terminology for some anterior tissue; the ciliated sensory epithelium is identified explicitly in the higher-magnification panel.')
slide('The diencephalon includes endocrine-associated tissue',['brain'],['b21'],
'The **diencephalon** lies beneath the midbrain and contains the epithalamus, thalamus, and hypothalamus. Senarat and colleagues distinguished these regions in stained _Hippocampus barbouri_ sections. The hypothalamus was the dominant portion of this division in their anatomical description.|The three diencephalic regions occupied distinct positions beneath the midbrain. The thalamus lay between the epithalamus and hypothalamus and contained neuronal cell bodies, supporting glial cells, and nerve fibers. **Glial cells** are non-neuronal cells that support neural tissue; they were recognizable alongside neurons in several brain regions.|The hypothalamus contained neurosecretory cell populations and was anatomically associated with the pituitary. This regional arrangement places hormone-related tissue within the same brain that contains the visual and motor-associated structures.',
'The hypothalamic relationship with the pituitary supplies anatomical context for the later seahorse peptide-administration experiments.')
slide('Hypothalamic and pituitary tissues are differentiated',['brain'],['b25','b27'],
'**Neurosecretory cells** are neural cells specialized to produce secreted signaling molecules. Senarat and colleagues described such cell populations in the seahorse hypothalamus, including periventricular and lateral tuberal regions. These locations differed from the layered optic tectum and cerebellum.|The pituitary contained a neural region, the **neurohypophysis**, and a glandular region, the adenohypophysis. Histological sections distinguished their tissue organization, providing an anatomical basis for separating neural hormone-associated tissue from glandular endocrine tissue.|During development, pituitary glandular tissue became conspicuous by 14 days after birth. Neural, vascular, and endocrine-associated structures therefore differentiated over overlapping intervals, while later reproductive experiments examined how peptide signals altered pituitary gene expression.',
'The source uses an inconsistent spelling for the glandular pituitary region; adenohypophysis is the standard anatomical term.')
slide('The hindbrain continues into the spinal cord',['brain'],['b32','b35'],
'The **medulla oblongata** is the posterior brain region that continues toward the spinal cord. In _Hippocampus barbouri_, the medulla contained neurons and glial cells, with the fourth ventricle bordering part of the tissue. Senarat and colleagues followed this continuity in sagittal sections.|The spinal cord extended through the vertebral column. Cross-sections contained central neural tissue and a central canal, the fluid-containing channel continuous with the brain ventricles. The canal boundary included ependymal cells, which line these internal fluid spaces.|The brain and spinal cord form a continuous central nervous system. Within spinal tissue, neurons and glial cells occupied the region surrounding the central canal, extending cellular organization along the brain-to-body axis.',
'The micrographs identify the central canal and surrounding tissue directly; locomotor responses were not tested by lesions or neural recording.')
slide('Neural maturation and feeding competence differ',['brain','juvenile'],['b39','retina_ab'],
'Newborn _Hippocampus barbouri_ brains appeared compact, with relatively indistinct substructures, in Senarat and colleagues’ sections. By contrast, Sun and colleagues observed organized retinas and successful prey capture on the first day after birth in lined seahorses, _Hippocampus erectus_.|These findings concern different species and different measurements. **Behavioral competence** means successful performance of an action, whereas histological differentiation describes the visibility and organization of tissue features. A functional behavior can occur while anatomical maturation continues.|The brain study’s proposed onset of predatory development at 6–14 days is therefore a species-specific anatomical hypothesis. Direct newborn feeding observations establish early competence in the lined seahorse and identify continued development as improvement of an existing behavior.',
'The species difference changes the conclusion: the histological timetable should not be presented as a universal onset of seahorse feeding.')
slide('The newborn feeding skeleton is largely cartilaginous',['juvenile'],['snout_abc'],
'**Cartilage** forms much of the early feeding skeleton in juvenile lined seahorses. Sun and colleagues stained cartilage blue and mineralized bone red, allowing the snout skeleton to be followed across postnatal ages. Jaw and associated elements were predominantly cartilaginous during the first three days.|The labeled elements include the maxilla and dentary of the jaws, and the hyoid and ceratohyal beneath them. Their coordinated movement participates in the expansion associated with suction feeding. Newborns performed successful strikes while these structures remained incompletely ossified.|By about 7 days, several snout elements displayed obvious mineralization. Feeding competence therefore preceded the later skeletal condition, while postnatal ossification changed the anatomical apparatus supporting repeated prey capture.',
'Ossification is the formation of bone, including mineralization of skeletal tissue; the stain distinguishes tissue condition rather than muscle activity.')
slide('Snout ossification accompanies improved capture',['juvenile'],['snout_def'],
'**Ossification** progressively replaces or supplements the early cartilaginous condition with bone. In lined seahorses, jaw and associated snout elements were ossified by approximately 14 days after birth, while the later snout skeleton became fully mineralized by about 30 days.|Sun and colleagues observed a change in the developmental trajectory of feeding around 10–14 days. Capture success increased, snout expansion became less pronounced, and growth and food intake changed during the same interval. The histological and behavioral measurements therefore identify a shared developmental transition.|The mouth still captured prey through a brief coordinated strike. Maturation altered the dimensions and tissue properties of the feeding apparatus while preserving pivot feeding as the animal’s basic acquisition strategy.',
'The abstract describes an approximately 10-day transition, while the detailed results place completion of jaw-element ossification at about 14 days.')
slide('Growth extends the reach of a feeding strike',['juvenile'],['snout','j1c'],
'**Attack distance** was defined by Sun and colleagues as the maximum distance traveled by the snout tip during capture. In lined seahorses, this distance increased from about 1.14 mm on the first day after birth to 3.18 mm by day 30.|Snout length increased from approximately 0.78 mm to 3.75 mm over the same interval. A longer feeding apparatus accompanied a larger capture reach, while body height increased from about 9.2 mm to 43.2 mm. Growth therefore changed the spatial scale of prey acquisition.|Capture success rose from about 77% in newborns to about 92% at day 30 under the study conditions. Increasing reach and success developed within an already functional visually guided feeding sequence.',
'The reported attack distance is snout-tip displacement; it should not be confused with the initial mouth-to-prey separation measured in the dwarf-seahorse hydrodynamic study.')
slide('Snout expansion declines as the skeleton matures',['juvenile'],['snout_abc','snout_def'],
'**Feeding caliber** is the maximum snout width reached during suction feeding. Sun and colleagues compared this width with the resting snout width to describe expansion. Newborn lined seahorses expanded to about 216% of their resting width, whereas the value was about 106% by day 14.|The increasingly mineralized skeleton accompanied a less expandable snout. At later ages, feeding caliber and resting width became similar, even though absolute snout dimensions and capture reach increased. Growth therefore changed both size and the proportional deformation during feeding.|The early flexible snout allowed newborns to take comparatively large prey. Later animals retained rapid suction feeding with a larger, more ossified apparatus and a smaller relative change in width.',
'The early flexibility is an interpretation discussed by the authors, supported by the paired kinematic and skeletal-staining observations.')
slide('The intestine matures while daily intake rises',['juvenile'],['gut_gh'],
'Newborn lined seahorses had a short, relatively straight intestine with a thin mucosal layer. **Mucosa** is the inner tissue lining the digestive lumen. During the first postnatal days, folds and loops developed, increasing the complexity of the organ that receives captured food.|By about 10 days after birth, three intestinal loops were visible and the muscular wall was thicker. Sun and colleagues documented these changes with stained sections, alongside the increasing food intake measured in the feeding experiment.|Daily intake rose from about 1.2 mg per seahorse at birth to 46.3 mg by day 30. Relative intake decreased from about 43% of body mass per day in newborns to approximately 17–22% in later juveniles.',
'The species lacks a typical stomach in the source description, so the intestinal tract bears much of the digestive role.')
slide('A slow predator can approach evasive copepods',['feeding'],['f2b'],
'Dwarf seahorses, _Hippocampus zosterae_, capture **copepods**, small swimming crustaceans that detect disturbances in the surrounding water. Gemmell and colleagues studied approaches to _Acartia tonsa_ using high-speed holography, a method that reconstructs positions and particle movement within a three-dimensional sample volume.|About 84% of approaches brought the copepod within roughly 1 mm without triggering escape. Once prey entered capture range, capture succeeded about 94% of the time. Successful feeding therefore combined an undetected approach with an exceptionally rapid final strike.|The approach and strike solve different problems. Slow positioning limits the warning available to the prey, while head rotation rapidly closes the remaining short distance.',
'The experiments used dwarf seahorses approximately 2.5 cm long and copepods with body lengths around 0.8–1.1 mm.')
slide('Successful approaches were slower than failed ones',['feeding'],['f1a'],
'Approach speed differed between successful and failed dwarf-seahorse feeding attempts. Gemmell and colleagues measured successful approaches at about 8.4 mm/s and unsuccessful approaches at about 14.1 mm/s. These values describe the movement before the final pivot-feeding strike.|A moving head deforms the surrounding water. **Hydrodynamic disturbance** is the resulting change in water motion that a mechanosensitive prey animal can detect. Faster approaches increased the disturbance near the region where the copepod would eventually be captured.|The seahorse’s short-range strike therefore depended on careful preceding positioning. Rapid final acquisition was compatible with a slower approach, because minimizing the prey’s warning and minimizing the final capture time require different movement patterns.',
'The speed comparison concerns observed feeding outcomes; the flume measurements separately tested how imposed flow speed changed disturbance around preserved heads.')
slide('The final strike outruns a copepod response',['feeding'],['f2b','f1b'],
'High-speed recordings at 2,000 frames/s resolved the final dwarf-seahorse strike. The mouth covered the remaining distance to the copepod in less than 1 ms. The source contrasts this interval with copepod escape-response latencies of approximately 2–4 ms reported in earlier work.|**Response latency** is the time between detection of a stimulus and the beginning of a response. A strike completed before that interval expires can acquire the prey before an effective escape movement develops. The advantage depends on beginning within the very short capture range.|Nearby copepods could respond to the disturbance produced by a completed strike. The captured target and surrounding animals therefore encountered different timing relationships between detection, escape, and the rapidly moving mouth.',
'The paper observed no strikes at initial prey distances exceeding 1.4 mm; the exceptional speed is a close-range advantage.')
slide('A quiet water region lies above the snout',['feeding'],['f3cd'],
'**Particle tracking** follows small suspended tracers to estimate local water movement. Gemmell and colleagues used live diatoms as tracers during dwarf-seahorse approaches and reconstructed their positions holographically. Water motion above the snout was lower than in adjacent regions.|Within the measured capture region, water velocities did not exceed about 0.8 mm/s, whereas neighboring regions reached about 4.1 mm/s. The prey could occupy a comparatively quiet zone even though the moving predator disturbed water elsewhere around its head.|This spatial pattern connects head form with prey detection. The mouth rotates toward the zone during capture, so the location with reduced warning also lies within the range reached by pivot feeding.',
'The quiet region occurred during both successful and failed approaches; disturbance magnitude and target position still affected the outcome.')
slide('Increasing flow erodes the quiet capture zone',['feeding'],['f4'],
'Gemmell and colleagues placed preserved dwarf-seahorse heads in a flow chamber and measured water movement with **particle image velocimetry**, which estimates velocity from displacement of illuminated particles. Imposed flow represented the relative movement occurring during an approach.|**Deformation rate**, measured in s⁻¹, describes how rapidly nearby water is strained. At 4 mm/s, almost none of the capture zone exceeded the approximately 0.5 s⁻¹ detection threshold discussed for _Acartia tonsa_. At 10 mm/s part of the zone exceeded it, and at 20 mm/s much more did.|The head’s geometry preserved a relatively quiet region, but the absolute disturbance increased with approach speed. The flow experiment therefore explains why a favorable head shape still benefits from a slow approach.',
'The preserved-head preparation isolates effects of geometry and posture without active swimming or a live prey animal changing position.')
slide('Head posture changes the disturbance reaching prey',['feeding'],['f5'],
'**Posture** determines which surfaces of the seahorse head meet the incoming water. Gemmell and colleagues varied head angle in a flow chamber while measuring deformation around preserved dwarf seahorses. The naturally observed posture produced the lowest disturbance within the capture region.|Live approaches also maintained a consistent relationship between head and target. The angle from the top of the head through the snout tip toward the copepod averaged about 124°, and head rotation during the approach remained small.|Geometry and behavior therefore work together before the strike. The narrow snout creates a favorable flow distribution, and the animal maintains an orientation that places its target within the quiet portion of that distribution.',
'The source separates approach posture from the large, rapid head rotation used during the capture phase.')
slide('A stickleback head produces a different flow field',['feeding'],['f6','f5'],
'The three-spined stickleback, _Gasterosteus aculeatus_, lacks the seahorse’s elongated tubular snout. Gemmell and colleagues used preserved sticklebacks as a morphological comparison in the same flow measurements. Their heads produced a relatively uniform bow wave with strong deformation directly ahead of the mouth.|A **bow wave** is the water disturbance generated in front of an advancing object. Changing stickleback head posture did little to reduce deformation at the short distances used for seahorse strikes. The comparison separates a general consequence of moving through water from the distinctive seahorse geometry.|Different feeding anatomies therefore create different sensory conditions for prey. The seahorse places its capture region within a low-disturbance zone, whereas the stickleback’s frontal region remains comparatively exposed to deformation.',
'The comparison concerns hydrodynamic geometry, not a direct comparison of live stickleback and seahorse capture success.')
slide('Pairing changes the context of visual interaction',['pairing'],['m2'],
'Mederos and colleagues paired male and female lined seahorses for 5 days, then tested interactions with the familiar partner and an opposite-sex stranger. The animals occupied separate sections of a test tank, allowing their brightness changes to be analyzed during proximity to either individual.|**Luminance** describes brightness in a visual channel rather than hue, the kind of color perceived. The researchers calibrated video images and evaluated changes in abdominal luminance using a seahorse visual model. Partner interactions produced larger and more correlated changes than stranger interactions.|The measured social response was context-dependent brightening. Familiarity with a specific individual altered visual interaction even when both available animals were potential opposite-sex social partners.',
'The article distinguishes social monogamy, meaning pair living, from an affective pair bond assessed through partner preference, separation distress, and social buffering.')
slide('Male brightening exceeds the female response',['pairing'],['m2'],
'Males produced most of the luminance-change events observed during mutual partner proximity. In tests with a male as the focal animal, his abdominal luminance increased by about 20% during partner interactions, while his female partner increased by about 7%.|The same focal males brightened by about 14% during interactions with stranger females. Females used as stranger stimulus animals changed far less. **Sex-dependent signaling** therefore involved both the identity of the receiver and differences between male and female responses.|When the female was focal, her familiar male partner showed a particularly large brightness response, averaging about 38%. The interaction is asymmetric: both animals can change luminance, but the male carries much of the observed visual display.',
'The numerical values are percent changes from each animal’s baseline luminance, not the fraction of the body surface changing color.')
slide('Partner luminance changes can be coordinated',['pairing'],['m2'],
'**Behavioral synchrony** occurs when interacting animals coordinate their actions in time. Mederos and colleagues recorded partner-associated luminance changes in lined seahorses, including occasions when a male’s brightening was followed by a female response after a short delay.|The mean delay in those coordinated events was approximately 13 s. Most luminance changes were performed by the male alone, so coordinated brightening was one component of the interaction rather than the only display pattern. Partner identity also altered the magnitude of the response.|The authors hypothesized that abdominal brightening may contribute to communication between pair mates. The measured phenomenon combines temporal coordination with partner-associated brightness changes, linking a visible body response to the social context.',
'The article treats color change as a candidate communication mechanism; it did not experimentally prevent a display to test its necessity for maintaining a pair.')
slide('Visual modeling uses the receiver’s cone sensitivities',['pairing','juvenile'],['retina_ab','m2'],
'A **visual model** estimates how an animal’s photoreceptors respond to reflected light. Mederos and colleagues used published sensitivities from _Hippocampus subelongatus_ to analyze lined-seahorse displays. The source values included cone sensitivity peaks at 467, 522, 537, and 560 nm.|**Spectral sensitivity** describes response across light wavelengths. The model assigned the 537 nm channel to brightness and used calibrated images to estimate light captured by the different cone classes. This separates the receiver’s modeled luminance from a human judgment that a seahorse looks brighter.|Using sensitivities from another species is a model assumption, because equivalent measurements were unavailable for the lined seahorse. The resulting analysis specifically concerns brightness changes estimated under that assumption.',
'The model assumes that lined-seahorse photoreceptor sensitivities resemble those of a related species from a similar shallow, vegetated habitat; this assumption governs the brightness estimate.')
slide('Pairing studies sampled whole-brain gene expression',['pairing','brain'],['m3','b13'],
'After behavioral testing, Mederos and colleagues extracted **RNA**, the molecules carrying gene transcripts, from individual whole brains. RNA sequencing estimated the abundance of thousands of transcripts in paired males, paired females, and unpaired males. Whole-brain sampling combines contributions from multiple regions and cell types.|The exploratory profiles included metabolic, hormonal, and cilia-associated processes. **Cilia** are small cellular projections implicated in sensing and signaling. The authors proposed that pairing-related metabolic differences might accompany social activity, neural activity, preparation for pregnancy, or several of these processes.|Individual gene differences did not survive the study’s correction for testing many genes. These expression patterns are therefore exploratory candidates, while the behavioral observations directly describe the partner-associated luminance response.',
'The study used each brain separately rather than pooling brains, preserving individual expression profiles while sacrificing regional localization.')
slide('Receptor transcripts suggest candidate social pathways',['pairing','brain'],['m3','b13'],
'A **receptor** is a protein that receives a signal and changes cellular activity. Mederos and colleagues examined transcripts for nonapeptide, dopamine, serotonin, and opioid receptor systems previously associated with social behavior in vertebrates. Their data describe RNA abundance rather than receptor activation.|Exploratory normalized profiles placed oxytocin-receptor transcripts relatively higher in paired females and serotonin-receptor Htr4 transcripts relatively higher in paired males. **Nonapeptides** are peptides of nine amino acids; fish isotocin is related to mammalian oxytocin. These comparisons identify candidate signaling systems for future seahorse experiments.|The social role of those receptors remains a hypothesis because the study did not manipulate them. The experimentally measured phenotype was partner-related brightening, which provides a behavior to test against specific receptor interventions.',
'No ligand binding, receptor blockade, or neuronal firing experiment was included, so transcript associations should not be taught as demonstrated receptor control of seahorse pair formation.')
slide('Cross-species gene rankings share endocrine themes',['pairing','brain'],['m4','b13'],
'**Orthologous genes** are corresponding genes inherited from a shared ancestor. Mederos and colleagues compared ranked expression changes in seahorse whole brains with published prairie-vole brain datasets. The comparison searched for coordinated overlap rather than requiring identical changes in every individual gene.|Shared expression themes included metabolic processes and reproductive hormone-associated genes. The authors found overlap between paired male seahorses and paired male voles, even though the sampled neural tissue differed between species. These similarities connect reproduction and social state at the level of gene-expression patterns.|The overlap supports a hypothesis of shared molecular components across distinct reproductive systems. Seahorse male pregnancy and mammalian pair-associated physiology remain different biological contexts in which related endocrine genes can participate.',
'The vole datasets sampled medial preoptic and nucleus accumbens tissue, whereas the seahorse samples were whole brains; matching rankings therefore do not identify homologous seahorse neural circuits.')
slide('Kisspeptin signaling is concentrated in the brain',['kisspeptin','brain'],['k5','b25'],
'**Kisspeptin** is a peptide signal associated with reproductive regulation. Zhang and colleagues identified a kiss2 gene and its receptor gene, GPR54-2, in lined seahorses. Their tissue measurements found kiss2 transcripts in several locations, including brain and gonadal tissue.|GPR54-2 transcripts were concentrated in the brain and close to the detection limit in peripheral tissues. Within the brain, both ligand and receptor transcripts were especially abundant in the hypothalamic region. The complementary distribution places a peptide-producing system and a potential responding system in reproductive neural tissue.|Female brains contained higher transcript levels than male brains in the reported comparison. Sex and reproductive state therefore influence the molecular organization of the same named kisspeptin signaling system.',
'A ligand is a signaling molecule that binds a receptor; tissue transcript abundance identifies candidate sites of synthesis and response rather than directly measuring peptide release.')
slide('Brain Kiss2 rises near the onset of puberty',['kisspeptin'],['k6a'],
'**Puberty** is the developmental transition toward reproductive competence. Zhang and colleagues followed male lined seahorses from immature animals at 3 months through early puberty at 4 months, advanced puberty at 5 months, and maturity at 6 months. Testis histology distinguished these developmental stages.|Brain kiss2 transcript abundance was highest around early puberty, while testis kiss2 showed no comparable developmental change. The difference places the stage-associated molecular signal primarily in the brain within the tissues examined.|The gonads continued maturing as the animals aged. Brain transcript change and testicular differentiation therefore describe complementary parts of reproductive development, with the kisspeptin system positioned as a candidate regulator of the transition rather than merely a marker of adult body size.',
'The study aligned endocrine transcript measurements with gonadal histology rather than assigning developmental stage from chronological age alone.')
slide('Pregnancy reduces Kiss2-associated transcripts',['kisspeptin','brain'],['k7','b25'],
'Zhang and colleagues compared male lined seahorses before pregnancy, during pregnancy, and after birth. **Pregnancy** in seahorses is the period of paternal incubation following egg transfer and fertilization. Brain and testis kiss2 transcripts decreased during that stage and returned toward preceding levels after birth.|Brain GPR54-2 transcripts also decreased during pregnancy. Ligand and receptor expression therefore changed together across the reproductive cycle in the sampled tissues. The same peptide system associated with puberty was reorganized during an adult reproductive state.|The authors hypothesized that reduced reproductive signaling during pregnancy relates to the temporary reproductive cycle. The observed return after birth identifies molecular reversibility rather than a permanent loss of the kisspeptin system.',
'The measured stages were designated pre-pregnant, pregnant, and post-parturition; transcript changes should not be equated with measured peptide concentrations.')
slide('Kiss2 administration changes pituitary gene expression',['kisspeptin','brain'],['k8','b27'],
'Zhang and colleagues administered **Kiss2-10**, the mature ten-amino-acid peptide, to sexually mature male lined seahorses. They then measured brain and pituitary transcripts at 3 and 6 hours, comparing peptide-treated animals with saline-treated controls. This intervention tested physiological responsiveness to the identified signal.|Pituitary FSHβ transcripts increased at 3 hours, and both FSHβ and LHβ increased at 6 hours. **Gonadotropins** are pituitary hormones regulating the gonads; FSH and LH are follicle-stimulating and luteinizing hormone. Their beta-subunit transcripts identify components of those hormones.|The measured salmon-type gonadotropin-releasing hormone, sGnRH, and GPR54-2 transcripts did not increase. Pituitary gene responses can therefore occur without a parallel increase in these particular upstream transcripts over the sampled interval.',
'The unchanged upstream RNA measurements do not rule out changes in peptide release or existing receptor signaling; the experiment measured transcript abundance.')
slide('Kiss2 administration raises circulating testosterone',['kisspeptin'],['k9','k6b'],
'**Testosterone** is a steroid hormone associated with reproductive physiology. Following Kiss2-10 administration, Zhang and colleagues collected blood from male lined seahorses at 3 and 6 hours and measured serum testosterone with an immunoassay. The saline-treated group provided the injection comparison.|Testosterone was elevated at 6 hours after peptide treatment. The same experimental series found increased pituitary gonadotropin transcripts, connecting the administered peptide to changes at more than one level of reproductive physiology.|The observations support endocrine responsiveness of mature males to Kiss2-10. A circulating hormone response and a tissue transcript response are different measurements, and their coordinated changes connect the identified peptide system to the reproductive axis.',
'An immunoassay estimates hormone concentration using antibody-based detection; the paper measured serum testosterone rather than testosterone synthesis directly in the testis.')
slide('Vasotocin and isotocin occupy preoptic tissue',['vasotocin'],['v4bc','v4ef'],
'**Vasotocin** and **isotocin** are nine-amino-acid peptide hormones related to mammalian vasopressin and oxytocin. Zhang and colleagues cloned their precursors in lined seahorses and used in situ hybridization, a method detecting selected RNA sequences within tissue, to locate cells expressing the genes.|Both transcript signals occurred in the **preoptic area**, hypothalamic tissue associated with reproductive regulation. Vasotocin labeling was concentrated centrally, whereas isotocin labeling was more peripheral within the examined area. The preparations localized signaling-molecule transcripts to identifiable neural tissue.|The study also used a sense-probe control to assess nonspecific labeling. Transcript localization and the later vasotocin intervention supply complementary anatomical and physiological evidence for a seahorse neuroendocrine system.',
'Antisense probes bind the target transcript; the corresponding sense probe provides a control for labeling unrelated to that specific RNA sequence.')
slide('Vasotocin triggers premature release of young',['vasotocin'],['v5b'],
'**Parturition** is the release of offspring at the end of pregnancy. Zhang and colleagues injected pregnant lined seahorse males with vasotocin at 50 or 500 ng/g body mass and compared them with saline-injected controls. Treated males performed repeated body-swinging movements associated with birth.|The released young were premature: they were shorter and retained larger yolk sacs than normally released animals. **Yolk** is stored embryonic nutrition, and persistence of a large yolk sac identifies incomplete development at the time of release.|The peptide intervention therefore affected the timing of a reproductive behavior, not simply a molecular marker. Male seahorse birth combines bodily movement with an endocrine state that can be experimentally shifted by vasotocin administration.',
'The photographs compare normally released young with young released after the lower and higher vasotocin doses; the dose units are amount per body mass.')
slide('Vasotocin changes reproductive endocrine state',['vasotocin','brain'],['v5a','b27'],
'Six hours after vasotocin administration, pregnant lined seahorses had increased circulating estrogen, while testosterone remained similar to the control condition. **Estrogen** is a steroid hormone participating in reproductive regulation. Zhang and colleagues measured the circulating hormones separately from tissue transcripts.|Pituitary FSHβ and LHβ transcripts increased, while prolactin transcripts decreased. **Prolactin** is a pituitary hormone discussed in the source in relation to incubation physiology. Vasotocin therefore shifted several components of the reproductive endocrine state alongside the observed birth behavior.|The authors proposed a reproductive-axis mechanism linking neuropeptide action, gonadotropin regulation, and estrogen-associated responses. The combined intervention and endocrine measurements identify a coordinated response rather than requiring every hormone to change in the same direction.',
'The paper measured transcript responses and serum steroids; a complete sequence of intervening cellular events was not recorded.')
slide('Pregnancy and birth involve distinct peptide responses',['kisspeptin','vasotocin'],['k7','v5b'],
'Male seahorse reproduction includes transitions into pregnancy and into birth, with different peptide-associated responses. Zhang and colleagues found reduced Kiss2 and receptor transcripts during pregnancy, followed by recovery after parturition. A separate vasotocin experiment shifted pregnant males toward premature release.|**Reproductive state** therefore changes both the molecular background and the response to a supplied signal. Kiss2 measurements describe stage-associated regulation, whereas vasotocin administration directly changes the timing of bodily birth behavior. The experimental designs address different parts of the cycle.|The released offspring begin visually guided feeding while their own sensory, neural, and skeletal systems continue developing. Parental endocrine timing and offspring developmental readiness meet at birth, linking adult reproductive control to juvenile behavioral independence.',
'The two peptide studies should not be presented as a single proven linear pathway; they tested separate components of the male reproductive cycle.')
assert len(S)==44,len(S)
spec={'lecture':60,'theme':'quiet-ocean-paper','content_slides':44,'title_height':3.2,'title_image':F['animal'],'title_refs':[R['photo']],'slides':S,'takeaways':{'cite':'; '.join(C[k] for k in keys[:-1]),'refs':[R[k] for k in keys[:-1]],'items':[
{'lead':'Early sensory competence','text':'Newborn lined seahorses capture live prey while retinal organization is already recognizable and snout ossification continues.'},
{'lead':'Layered neural organization','text':'The prominent optic tectum and three-layered cerebellum differentiate during postnatal development.'},
{'lead':'Approach and strike','text':'A slow approach and quiet water region limit prey warning; a close-range pivot strike can reach prey in less than 1 ms.'},
{'lead':'Partner-associated brightening','text':'Lined seahorses change abdominal luminance more strongly during familiar partner interactions, with most display events performed by males.'},
{'lead':'Kisspeptin endocrine responsiveness','text':'Kiss2-10 administration increases pituitary gonadotropin transcripts and later circulating testosterone in mature males.'},
{'lead':'Neuroendocrine birth timing','text':'Vasotocin administration induces premature offspring release and changes estrogen and pituitary transcript responses in pregnant males.'}]}}
(D/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
(D/'REFERENCES.md').write_text('# Verified sources\n\n'+'\n\n'.join(R.values())+'\n')
for i,sl in enumerate(S,2):
 n=len(re.sub(r'\*\*|_', '', ' '.join(sl['body'])).split())
 print(i,n,sl['title'])
