"""Lecture 25; all images are original published PDF crops."""
import json,re
from pathlib import Path
H=Path(__file__).resolve().parent;F=json.loads((H/'figure-sources.json').read_text());REF={}
for k in {x['paper']for x in F.values()}|{'kinematic01'}:
 d=json.loads((H/'sources'/f'{k}-crossref.json').read_text())
 def person(a):return a['family']+' '+''.join(w[0]for w in a.get('given','').replace('-',' ').split())
 page=d.get('page')or d.get('article-number')or {'ir13':'e60551','single20':'649','diversity12':'e34843','plume20':'7961'}.get(k,'')
 if k=='sampling11':page='3138–3153'
 REF[k]=f"{', '.join(person(a)for a in d['author'])} ({d['published']['date-parts'][0][0]}). {re.sub('<[^>]+>','',d['title'][0]).rstrip('.')}. {d['container-title'][0]} {d['volume']}"+(f"({d['issue']})"if d.get('issue')else '')+f":{page}. https://doi.org/{d['DOI']}"
def short(k):
 d=json.loads((H/'sources'/f'{k}-crossref.json').read_text());a=d['author'];return a[0]['family']+(' & '+a[1]['family']if len(a)==2 else ' et al.'if len(a)>2 else '')+f" ({d['published']['date-parts'][0][0]})"
def fig(n):x=F[n];return {k:x[k]for k in ('caption','source_url')}|{'kind':'article','path':x['out']}
slides=[]
def add(title,f,a,b,c,note,anatomy=None,also=()):
 names=[f]+([anatomy]if anatomy else []);ks=list(dict.fromkeys([F[n]['paper']for n in names]+list(also)));body=[a,b,c]
 s={'title':title,'layout':'figure-right','figure_width':5.65,'body':body,'transcript':[[re.sub(r'\*\*|_','',a),[note]],re.sub(r'\*\*|_','',b),re.sub(r'\*\*|_','',c)],'cite':'; '.join(short(k)for k in ks),'refs':[REF[k]for k in ks],'figure':fig(f)}
 if anatomy:
  s.pop('figure');s.update(layout='figures-right',figure_width=5.9,primary_figure_height=3.2,figures=[fig(f),fig(anatomy)])
  if f in ('currents','oscillations','burstperiod','irheat'):
   s.update(figure_arrangement='side-by-side',primary_figure_width=3.9)
 slides.append(s)

add('Food odor organizes source-directed walking','paths',
'**Chemoreception** is the detection of chemicals by sensory cells. Clawed lobsters, _Homarus americanus_, use dissolved food odors while walking across the seabed. Moore, Scholz and Atema compared paths toward mussel extract with paths recorded during otherwise equivalent raw-seawater delivery.',
'Odor-search paths contained pauses, sideways movement and backward steps while still progressing toward the source. Mean walking speed was 5.94 cm/s during odor trials, compared with 10.81 cm/s in controls. Faster movement therefore did not necessarily indicate better source-directed searching.',
'The trajectories demonstrate that chemical stimulation reorganizes locomotion under flowing-water conditions. Only motivated, successful approaches were included in the detailed analysis, so these measurements do not estimate the success probability of all lobsters. They also do not identify the neurons that select each correction.',
'A source-search path is the sequence of positions occupied by the animal. Its length, direction and speed are distinct variables; a slower path can be more useful if it remains associated with the odor plume.')
add('A flume separates chemical input from water flow','arena',
'A **flume** is a channel that supplies controlled flowing water. Moore and colleagues tested lobsters in a 250 × 90 × 20 cm arena with a current of 1.0 cm/s. A reference grid and overhead video allowed position and heading to be measured.',
'Mussel extract at 0.5 g/L was delivered at 50 mL/min from a source 9 cm above the bottom. Control trials substituted raw seawater while retaining delivery conditions. Rostrum positions were digitized once per second, providing a common spatial and temporal reference for comparisons.',
'These controls attribute behavioral differences to the presence of the food extract rather than the existence of current or a delivery tube alone. The extract is a mixture, not an identified receptor ligand. Its source concentration also differs from the fluctuating concentration reaching the animal downstream.',
'The rostrum is the anterior projection used as a positional landmark. Turbulent dilution and the animal’s movement mean the chemical concentration at a receptor cannot be inferred directly from the source solution.')
add('Speed and heading change during the approach','approach',
'**Heading angle** describes the direction of the lobster’s body relative to upstream. Moore and colleagues grouped recorded behavior by distance from the source. This analysis asks whether the approach is uniform or changes as chemical and mechanical conditions change.',
'From 240 to 110 cm away, mean speed increased from 2.3 to 7.8 cm/s while heading decreased from 98.8° to about 20°. Between 110 and 40 cm, speed remained near 7 cm/s. Within the final 40 cm, speed fell toward 4.7 cm/s and heading increased toward 37°.',
'These transitions establish distinct movement regimes during successful searching. They are consistent with changing sensory guidance near the source, but distance covaries with plume structure and concentration. The experiment therefore does not establish a dedicated neuronal distance code or prove that one chemical gradient causes every transition.',
'A heading near zero is upstream; a larger angle can accompany lateral sampling. The last approach need not be the fastest because close-range localization can involve slowing and repositioning.')
add('Recorded turns do not reveal a fixed casting program','angles',
'**Turning angle** is the change in movement direction between successive path segments. Moore and colleagues compared heading and turn distributions in odor-search trials. A stereotyped alternating search program would predict consistently organized counterturns rather than the observed broad variation among paths.',
'Experimental headings were centered around 0–10°, and turns around 10–20°. Individual animals followed variable paths across repeated trials. Odor stimulation supported an upstream bias without producing a single characteristic path that every lobster repeated at fixed intervals.',
'The findings weaken a simple invariant counterturn account for this preparation. They do not exclude central motor programs altogether: sensory feedback could modify an internally generated movement sequence. The data also leave open how bilateral antennular input and water-flow information contribute to the observed directional corrections.',
'An absence of one stereotyped trajectory is different from an absence of neural organization. Feedback control can produce variable trajectories even when the same circuit is used on every trial.')
add('Close-range searching recruits walking-leg raking','paths',
'Moore and colleagues measured **leg raking**, repeated movements that bring walking-leg sensory surfaces into contact with the local environment. They compared raking rates at several distances from the odor source, testing whether close-range searching involves more than antennular sampling.',
'Raking averaged 3.4 events per 5 s within 7 cm of the source, 2.6 at 7–15 cm, and 1.15 at 15–22 cm. Beyond 22 cm it averaged only 0.1 per 5 s. Most recorded raking therefore occurred near the source.',
'The change supports recruitment of near-substrate sampling during final localization. A switch from antennular guidance to leg-based guidance was the authors’ interpretation, rather than a selective-lesion result in this study. Increased raking could also accompany contact exploration or feeding preparation, so its sensory cause requires separate tests.',
'The same recorded paths provide spatial context for the independent raking measurements. The figure does not plot raking frequency, and its trajectories should not be mistaken for a direct readout of leg-receptor activity.')
add('Two antennular pathways can guide spiny lobsters','sensorybody',
'The Caribbean spiny lobster, _Panulirus argus_, differs from the clawed lobster used in the earlier flume study. Its antennules carry **aesthetascs**, specialized olfactory hairs, together with non-aesthetasc sensilla containing other chemical and mechanical sensory neurons. These populations offer potentially overlapping information.',
'Horner, Weissburg and Derby tested 48–74 mm carapace-length animals in a 5,000-L flume with flow near 5 cm/s. Shrimp extract at 3 or 0.3 g/L supplied high- and low-odor treatments; seawater supplied a chemical control. Selective manipulations targeted different sensory populations on both antennules.',
'The experiment asks whether one pathway is indispensable for food-source localization under realistic flow. A preserved response after removing one population can show that the remaining pathway is sufficient in this assay. It cannot establish that the populations are identical or redundant in every natural behavior.',
'A sensillum is a cuticular sensory structure. Aesthetasc and non-aesthetasc pathways are anatomical categories, not merely strong and weak versions of one measured receptor response.')
add('Selective lesions require distinct procedural controls','flume04',
'Horner and colleagues used several interventions because sensory hairs can contain different neuron types. Shaving removed about 99.8% of aesthetascs. Removing and sealing non-aesthetasc sensilla targeted another pathway, while a 15-min distilled-water treatment temporarily impaired antennular chemosensitivity.',
'The source was positioned 2 m upstream of release. High and low shrimp concentrations were compared with seawater, and animals were offered shrimp afterward to check feeding motivation. Some manipulations also affected mechanoreceptors, an important qualification when interpreting a failure to orient.',
'The combination separates chemical guidance from complete loss of appetite more effectively than a lesion alone. Distilled-water treatment is reversible over approximately 24 h, but is not a molecularly selective receptor knockout. The conclusions concern the sensory populations affected by each treatment and the particular flow assay.',
'A behavioral lesion experiment requires both confirmation of sensory removal and a control for non-sensory impairment. Feeding after the trial helps assess motivation but does not prove that every aspect of locomotor function was unchanged.',anatomy='aesthetasc')
add('Either pathway can preserve food-source finding','success',
'Horner and colleagues measured the proportion of lobsters reaching the odor source after selective bilateral sensory manipulation. Intact animals found the high-odor source in 68% of trials and the low-odor source in 45%; no intact animal located a seawater source.',
'After aesthetasc removal, success remained 77% for high odor and 69% for low odor. Removing non-aesthetasc chemo-mechanosensory sensilla also preserved source finding, at 64% and 45%. In contrast, eliminating antennular chemoreceptor input broadly produced very poor localization.',
'Either retained antennular chemical pathway can therefore support this food-search task. The results do not show that aesthetascs are unnecessary for all olfactory functions or that increased percentages demonstrate an improvement caused by removal. Variable success and the different effects of each manipulation must be interpreted within the tested preparation.',
'Necessity and sufficiency are different claims. Preserved behavior after one pathway is removed argues against its unique necessity here; it does not remove the possibility that it normally contributes useful information.',anatomy='aesthetasc')
add('Successful searching can still become less efficient','performance',
'**Net-to-gross displacement ratio**, or NGDR, is straight-line displacement divided by total path length. A value closer to one indicates a straighter route. Horner and colleagues measured this variable separately from eventual source-finding success, together with arrival time, speed and heading.',
'At high odor concentration, mean NGDR was 0.82 in controls, compared with 0.63 after aesthetasc removal and 0.62 after non-aesthetasc chemo-mechanosensory removal. Mean arrival times across treatment groups were at most 96 s for high odor and 176 s for low odor.',
'Remaining sensory pathways can preserve arrival while losing efficient progress. Those times are group means, not upper limits for every animal. The altered routes show a contribution to search performance but do not identify whether the missing information concerned concentration, timing, flow direction or the reliability of bilateral comparisons.',
'Arrival and path straightness measure different properties. A lobster that eventually succeeds can still expend more walking distance, encounter more interruptions or require more opportunities to correct its direction.',anatomy='aesthetasc')
add('Turbulence produces patchy dissolved odor input','plumes',
'An **odor plume** is the distribution of odor-bearing water transported downstream from a source. Reidenbach and Koehl visualized plumes using **planar laser-induced fluorescence**, or PLIF: a thin laser sheet excites dissolved dye, and calibrated camera intensity estimates local concentration.',
'Their 25-m flume produced fine odor filaments separated by cleaner water. Images were recorded at 60 frames/s, yielding 16.7-ms temporal resolution. Measurements at different lateral positions showed a denser central plume and sparser encounters toward its edge.',
'The images establish the physical input available to a sensory appendage, rather than recording receptor activation. Fluorescent dye is a transport tracer and need not bind lobster odor receptors. A smooth time-averaged concentration field therefore conceals the intermittent encounters and gaps that a moving animal actually samples.',
'PLIF provides chemical-transport information in a plane. It does not measure every location in a three-dimensional plume at once, and the concentration represented by color is calibrated dye concentration.')
add('Antennular length changes the sampled chemical pattern','sampler',
'Reidenbach and Koehl placed virtual sampling lines within measured PLIF images to represent the aesthetasc-bearing portion of an antennule. Lobster and blue-crab geometries were compared at the same 8-cm height. This approach separates appendage geometry from differences in chemical receptor sensitivity.',
'The lobster sampler flicked at 2 Hz and moved at 6 cm/s during the downstroke. The crab sampler was only 2 mm long and flicked at 3 Hz. Lobster geometry intercepted odor during more flicks and sampled higher peak concentrations than crab geometry.',
'Longer sampling structures can encounter more filaments, while faster sampling can partly compensate for shorter length. These are measurements extracted from real plume images using specified sampling assumptions. They do not show that an intact lobster consciously compares every point along its antennule or implements the authors’ analysis algorithm.',
'A virtual sampler is an analysis of physical measurements, not a recording of a receptor neuron. Its value is to isolate which aspects of the input depend on appendage size and motion.')
add('Discrete sniffing changes the gaps between encounters','gaps',
'An **odor-free gap** is an interval without an encounter above the chosen detection threshold. Reidenbach and Koehl compared continuous concentration measurements with concentrations encountered by virtual flicking antennules. The comparison tests whether intermittent movement changes the timing of available chemical information.',
'Almost all gaps in continuously measured concentration were shorter than 500 ms throughout the sampled plume. Flicking antennules instead experienced longer gaps, and their gaps increased as downstream distance to the source decreased. Sampling schedule altered the input statistics before neural processing occurred.',
'The counterintuitive distance relationship shows why encounter frequency cannot be treated as a universal distance ruler. The result depends on plume transport, threshold and flicking geometry. It identifies available temporal cues but does not establish that a lobster uses this particular gap statistic to choose a turn.',
'A sensor can miss a passing filament between samples. Therefore, an odor-free interval in the sampled record need not mean there was no odor-bearing water anywhere near the animal.')
add('Antennules and legs encounter different gradients','doseposition',
'Near the seabed, transport and mixing differ from conditions several centimeters above it. Reidenbach and Koehl compared chemical samples at antennular height with samples near walking-leg height. The same source can therefore generate different concentration patterns for different sensory surfaces.',
'Mean sampled concentrations near the bed increased toward the source, whereas mean concentrations sampled higher by flicking antennules decreased toward it in this preparation. Variance was also lower near the bed. Measurements covered downstream positions from approximately 1 to 2.5 m.',
'Close-range leg sampling and distant antennular sampling need not provide interchangeable information. These physical results make the increase in leg raking during Homarus approaches plausible, but they do not causally explain those earlier animals’ movements. The behavioral and transport measurements involve different species and experimental arrangements.',
'A boundary layer is the region near a surface where flow is influenced by that surface. Sensory location within it changes chemical exposure even when the animal’s distance to the food source is unchanged.',also=('search91',))
add('Aesthetasc arrays organize the olfactory interface','hairanatomy',
'**Aesthetascs** are thin-walled sensory hairs bearing the outer dendrites of olfactory receptor neurons. On a Panulirus lateral antennular flagellum, they occur in repeated rows bordered by larger guard hairs. The scanning electron micrographs reveal a structured array rather than a uniformly exposed sensory surface.',
'Reidenbach, George and Koehl measured biological geometry before constructing physical models. Representative aesthetasc diameter was 22 µm, length about 720 µm, and spacing about 60 µm. The hairs are arranged at an offset angle, allowing appendage orientation to influence the water entering their gaps.',
'Chemical detection requires molecules to reach this sensory interface before membrane receptors can respond. Microscopy establishes dimensions and arrangement, not channel opening or neural firing. Guard-hair function must therefore be tested through flow measurements rather than inferred solely from the presence of a protective-looking structure.',
'An outer dendrite is the distal sensory portion of a neuron extending into the hair. The hair’s cuticle and fluid environment are part of the path between transported chemicals and neuronal membrane receptors.')
add('Scaled physical models isolate hair-array hydrodynamics','hairmodel',
'A **dynamically scaled model** reproduces the important balance of fluid forces despite using enlarged structures and a different fluid. Reidenbach and colleagues built glass-rod hair arrays in mineral oil and matched the **Reynolds number**, the ratio of inertial to viscous effects relevant to flow.',
'Biological dimensions and flicking motions constrained the model geometry. **Particle-image velocimetry**, or PIV, tracked suspended particles between images to measure fluid velocity around and between hairs. The investigators varied orientation, speed and guard-hair presence while retaining the remaining preparation.',
'These controlled changes identify mechanical causes of water exchange that are difficult to measure inside a living hair array. The model contains no sensory neurons and measures no ligand binding. Its results establish physical delivery conditions that can influence olfaction, rather than a complete explanation of receptor transduction or behavior.',
'Matching Reynolds number preserves the relative influence of inertia and viscosity. It does not automatically reproduce every chemical property, molecular diffusion rate or feature of a living appendage.',anatomy='aesthetasc')
add('The fast downstroke replaces water between hairs','downflow',
'An antennular flick consists of a fast downward movement followed by a slower return. In the scaled-model study, PIV measured water velocity inside the hair array during the downstroke. The published color map reports velocity rather than chemical concentration or sensory-neuron activity.',
'During the fast movement, water penetrated the aesthetasc gaps and replaced the previously retained sample. Measured profiles were comparatively uniform across the array. Separate high-speed recordings placed downstroke motion near an aesthetasc Reynolds number of 2, compared with about 0.5 during return.',
'The sensory organ therefore controls exposure mechanically before a receptor opens. Fresh water entering the gaps can deliver new odor molecules, but a flow map alone cannot establish which molecules bind or how many spikes are emitted. Reynolds-number estimates describe the biological movement studied, not a universal threshold for all crustacean hairs.',
'The reference frame matters: water flowing relative to a moving hair is the delivery variable. An ambient current and the appendage’s own movement can both contribute to that relative motion.',anatomy='aesthetasc',also=('kinematic01',))
add('The slow return retains a chemical sample','returnflow',
'**Leakiness** describes the extent to which water passes through a hair array rather than around it. Reidenbach and colleagues compared measured downstroke and return-stroke flow. The slower return reduced penetration, allowing the captured water to remain near the aesthetasc surfaces.',
'Return motion was approximately one-quarter of downstroke speed, yet water between hairs moved about 25 times more slowly. The nonlinear change shows that reducing appendage speed can alter array permeability much more than it alters the movement of the appendage itself.',
'Retention creates time for molecular diffusion toward the sensory surface. The authors estimated that diffusion over 0.5 s could span about 32 µm; this is a physical calculation, not measured ligand uptake by neurons. The experiment establishes a sampling mechanism without proving which concentration history an individual receptor experiences.',
'Diffusion is random molecular motion that redistributes solute down local concentration differences. Retaining water near a hair increases available contact time, but does not guarantee that all retained molecules reach the membrane.',anatomy='aesthetasc')
add('Hair orientation and guard hairs alter delivery','orientation',
'The shape and orientation of an aesthetasc array determine how incident water moves through it. Reidenbach and colleagues compared the observed zigzag orientation, offset by about 32°, with a zero-degree arrangement. They also measured arrays with and without surrounding guard hairs.',
'The observed orientation produced relatively uniform water penetration during the flick. Guard-hair removal changed the spatial velocity profile, revealing a hydrodynamic contribution beyond a possible protective role. The controlled physical model isolated these geometry effects without altering neuronal excitability.',
'The findings link anatomical arrangement to the distribution of a fresh sensory sample. They do not show that guard hairs detect food or that a particular flow profile automatically improves behavioral success. Sensory performance depends on subsequent diffusion, receptor activation and central interpretation, none of which was measured in the model.',
'The source’s colored velocity map is a measurement from the original physical model. Its bright regions show faster relative flow, not stronger neural activity or more receptor expression.',anatomy='guards')
add('Published video directly reveals lobster sniffing','sniffphoto',
'Koehl and colleagues programmed a mechanical lobster to flick real Panulirus antennules in a fluorescent dye plume. This preparation retained the biological hair array while controlling movement. Dye released from a benthic source 1 m upstream represented chemicals carried from a food source.',
'The original high-speed frames show approximately 1-mm-thick dye parcels entering the array during the rapid downstroke. During the slower return, dye remained trapped between hairs while the surrounding plume continued moving. A later downstroke shed that sample and captured another.',
'The observation directly supports discrete water sampling rather than uninterrupted exposure to ambient concentration. Fluorescent dye visualizes transported water and solute; it does not record food-odor receptor binding. The mechanically moved preparation also omits feedback by which an intact animal adjusts where and when to flick.',
'The image sequence contains successive frames, not a diagram created for this lecture. Tracking the same dye feature distinguishes exchange with the surrounding plume from simple movement of the appendage.')
add('A captured sample preserves spatial information briefly','sniffmap',
'Koehl and colleagues measured concentration along the aesthetasc-bearing section of the antennule through successive video frames. Their published **spatiotemporal map** places position on one axis and time on the other, with color representing measured dye concentration at each position.',
'The pattern changed during rapid downstrokes but remained comparatively stable during slower return and stationary intervals. Dye could spread along the antennule during acquisition, so the captured pattern was not an exact unchanged slice of the original plume. Sampling both retains and filters information.',
'This physical filtering precedes neuronal transduction. A spatially nonuniform retained sample could stimulate different sensory endings differently, but the paper did not record those cells or prove that the brain reconstructs the original spatial pattern. Mechanical retention therefore constrains the input without establishing a particular downstream code.',
'A horizontal streak in the published map means concentration at one position remained similar over time. It should not be interpreted as a sustained spike train or a labeled sensory axon.')
add('Ionotropic-receptor genes occur in olfactory neurons','irlocal',
'**Ionotropic receptors**, or IRs, are chemosensory proteins related to ionotropic glutamate receptors, a family of ligand-gated membrane channels. Corey and colleagues identified candidate IR sequences in Panulirus olfactory tissue and used in situ hybridization to locate their RNA within sensory cells.',
'IR25a and IR93a signals occurred broadly in olfactory receptor neurons. Antisense probes detect complementary target RNA; sense probes supplied negative controls for nonspecific staining. IR8a and another candidate showed more restricted expression, suggesting common components alongside more variable receptor populations.',
'The findings support an IR-based molecular architecture in lobster olfaction. Sequence similarity and cellular expression do not establish the ligand of a candidate receptor, its ion selectivity or the exact subunit composition of a native channel. Those properties require functional tests beyond staining for receptor RNA.',
'An ionotropic glutamate receptor detects glutamate in its established synaptic role. A related chemosensory IR need not recognize glutamate merely because it shares part of that receptor’s sequence and predicted structure.')
add('Receptor protein reaches the sensory dendrites','dendrites',
'RNA expression alone does not show where the resulting protein acts. Corey and colleagues used an antibody against IR25a to test its localization. Cross-sections through distal aesthetasc hairs supplied anatomical access to the outer dendrites, where transported odorants first approach olfactory neurons.',
'IR25a immunofluorescence occurred within the dendritic profiles. Sections stained without the primary antibody supplied a background control, and an antibody recognizing an Ih-channel protein provided a separate neuronal comparison. Western blots also detected a band near the predicted IR25a molecular mass of approximately 100 kDa.',
'The convergence of biochemical detection and dendritic staining places a candidate receptor component at a plausible transduction site. It does not demonstrate that every stained molecule forms an active surface channel. Antibody specificity, membrane localization and direct odor-evoked current are distinct evidentiary questions.',
'A kilodalton is a unit of molecular mass. Western-band size supports protein identity, while the section image addresses its anatomical location; neither alone measures an ion channel opening.')
add('Neighboring sensory cells differ in chemical selectivity','ligands',
'Corey and colleagues loaded sensory-cell clusters with a calcium-sensitive dye and applied different chemical stimuli. **Calcium imaging** reports changes in intracellular calcium through changing fluorescence. It can reveal many cells simultaneously, complementing measurements made from one neuron at a time.',
'The stimulus set included food extract, arginine and glutamate at 1 mM for the amino-acid tests. Neighboring cells showed different response profiles across the panel. A published heat map summarizes this heterogeneity rather than assigning one shared response to the whole cluster.',
'The responses establish chemical selectivity at the cellular level despite broad expression of common IR components. They do not identify which variable IR recognizes each ligand or prove that fluorescence amplitude equals membrane current. The association between expression and physiology motivates receptor tests but is not itself receptor deorphanization.',
'Deorphanization means identifying the activating ligand of a receptor whose ligand was unknown. Responding to arginine in an intact cell does not prove that any particular expressed receptor is the arginine-binding protein.',anatomy='somata')
add('Single-cell sequencing resolves receptor coexpression','singlecell',
'Whole-organ sequencing combines RNA from sensory neurons, support cells and other tissue. Kozma and colleagues instead collected individual fluorescently identified olfactory sensory neurons for **single-cell transcriptomics**, sequencing the expressed RNA of each cell. This separates within-cell coexpression from differences between cell populations.',
'All seven analyzed single-cell transcriptomes contained IR25a and IR93a. They also contained variable tuning-IR transcripts, while IR8a and IR76b were not detected in those cells. The photographed collection pipette documents the cellular preparation used for sampling.',
'The result supports shared receptor components with cell-specific combinations of additional candidates. Seven cells cannot exhaust the entire sensory population, and a failure to detect an RNA need not mean the gene is absent from every neuron. Transcript detection also does not establish protein abundance or channel assembly.',
'A transcriptome is the set of RNA molecules detected in a sample. Sequencing depth and amplification affect which low-abundance transcripts are recovered, especially when the starting material is one cell.')
add('A neuron can express many candidate tuning receptors','irheat',
'**Tuning IRs** are variable receptor candidates proposed to contribute ligand selectivity alongside more widely expressed components. Kozma and colleagues compared their abundance across single olfactory sensory neurons. The original heat map displays receptor identity by row and cellular sample by column.',
'Each analyzed neuron contained 9–53 tuning-IR transcripts, often with only one or a few expressed at high abundance. This arrangement differs from a simple rule in which every sensory neuron expresses exactly one ligand-selective receptor. Shared coreceptors do not eliminate molecular diversity between cells.',
'The data constrain candidate combinations but do not show that all detected IRs enter the same membrane complex. Low-abundance transcripts could have different functions or reflect technical sampling. Receptor composition, surface delivery and ligand specificity require additional protein-localization and functional experiments.',
'A heat-map color is a transformed expression measurement from the original paper. A stronger color does not establish a proportionally larger odor-evoked current because translation and channel regulation intervene.',anatomy='singlecell')
add('Gene expression does not establish odor recognition','cellgenes',
'Kozma and colleagues also examined **G-protein-coupled receptors**, or GPCRs, and **transient receptor potential** channels, or TRP channels, in sensory neurons. GPCRs can regulate intracellular signaling, whereas TRP proteins form ion channels with diverse sensory and cellular functions.',
'Individual cells expressed 12–17 GPCR candidates and overlapping sets of TRP-channel genes. The published summary includes common proteins and additional variable candidates. These transcript inventories reveal potential molecular machinery alongside the IR family rather than one fully resolved odor-transduction pathway.',
'Expression of a GPCR in an olfactory neuron does not prove that it binds a food odor; it may receive modulatory input. Likewise, a TRP transcript does not establish the channel carrying the primary receptor current. Connecting genes to mechanism requires ligand responses, channel properties and perturbations in identified cells.',
'A G protein links some activated receptors to intracellular enzymes or channels. Molecular presence indicates that a pathway could exist, but causal function must be tested rather than assigned from a protein-family name.',anatomy='singlecell')
add('Controlled odor delivery separates input from response','stimulus',
'Bobkov and colleagues recorded Panulirus sensory neurons in a semi-intact antennular preparation. Odor reached the outer dendrites while the cell bodies remained accessible to electrodes and imaging. Separate fluid compartments limited direct stimulation of somata and allowed repeated inputs to the sensory surface.',
'A fluorescent tracer characterized stimulus timing, while calcium imaging and loose-patch recordings measured responses. Food extract was tested at concentrations up to 0.5 mg/mL. Increasing pulse duration increased the effective delivered stimulus, but did not create a perfectly independent change in concentration alone.',
'These calibrations establish when chemical input arrived relative to cellular activity. They also expose an important experimental limitation: pulse duration, onset kinetics and effective dose can covary. Apparent concentration dependence must therefore be interpreted using the actual delivery waveform, rather than only the solution concentration stated at the source.',
'A loose-patch electrode detects spikes without tightly controlling membrane voltage. It records output timing, while stimulus calibration independently measures the physical input that produces that output.',anatomy='somata')
add('Peripheral neurons can be excited or inhibited by odor','currents',
'Bobkov and colleagues found tonic excitation, phasic–tonic excitation and inhibition among olfactory receptor neurons exposed to food extract. **Tonic** responses persist during stimulation; **phasic** responses emphasize its beginning. Inhibitory responses reduce activity relative to the cell’s unstimulated state.',
'Whole-cell voltage-clamp recordings near −70 to −60 mV measured inward or outward odor-evoked currents alongside firing patterns. Excitatory current could persist or adapt rapidly, while some cells showed inhibitory currents. Thus, diversity was already present in the receptor input, before central synaptic processing.',
'The observations reject an account in which all peripheral cells transmit the same excitation and the brain creates every inhibitory response. They do not resolve the molecular channel responsible for every current class. A current’s direction depends on holding voltage and ionic driving force, not simply the behavioral meaning of an odor.',
'Voltage clamp holds membrane voltage near a chosen level and measures compensating current. A current trace therefore reveals membrane conductance changes more directly than a spike train, but requires ionic tests to identify the ions involved.',anatomy='somata')
add('Calcium signals and spikes have different time courses','calcium',
'Calcium-sensitive fluorescence is often used as a proxy for neuronal activity, but it is not an action potential. Bobkov and colleagues recorded spikes and calcium simultaneously in identified lobster sensory neurons. The comparison tested how reliably a slower optical signal represents rapid electrical output.',
'Tonic, phasic–tonic and inhibitory neurons showed corresponding but differently filtered fluorescence changes. Calcium generally changed more slowly than the spike pattern. An inhibitory optical response could accompany reduced firing, while excitation increased firing and then accumulated a calcium signal.',
'The relationship supports calcium imaging for identifying response classes while limiting interpretations of precise encounter timing. Dye kinetics, intracellular buffering and calcium removal all intervene between spikes and fluorescence. A broad calcium peak cannot be assigned the same duration as the odor pulse or the underlying burst of spikes.',
'Calcium can enter through voltage-dependent channels and can also be released from intracellular stores. This simultaneous-recording experiment relates fluorescence to activity without proving the contribution of each calcium source.',anatomy='somata')
add('Some olfactory neurons burst without odor stimulation','oscillations',
'A **burst** is a cluster of spikes separated from another cluster by a quieter interval. Bobkov and colleagues observed intrinsically bursting olfactory receptor neurons in the absence of presented odor. Their spontaneous output therefore contains temporal structure before environmental stimulation is added.',
'Simultaneous recordings showed repeated electrical bursts followed by slower calcium oscillations. Across cells, optical oscillation frequencies ranged from approximately 0.015 to 0.9 Hz, with an average near 0.16 Hz. Different cells consequently supplied different intrinsic temporal reference scales.',
'These observations establish spontaneous peripheral timing, not a synchronized clock shared by the whole antennule. They also do not identify every ion channel producing the oscillation. An odor-evoked burst must be distinguished from a spontaneous burst when evaluating whether a cell has detected a new encounter.',
'Intrinsic means generated by the neuron’s own dynamics under the recording conditions. It does not mean the neuron is unaffected by chemical stimulation, modulators or the ionic composition of the preparation.',anatomy='somata')
add('Adjacent receptor neurons need not share an oscillator','neighbors',
'Bobkov and colleagues imaged many sensory somata within the same antennular cluster and compared their calcium time series. **Correlation** measures the degree to which two signals vary together. Pairwise comparisons tested whether nearby bursting cells behaved as one tightly synchronized peripheral network.',
'Most recorded pairs were weakly correlated and exhibited different oscillatory timing. A small number of highly similar records could arise from overlapping optical sampling, which required caution before attributing them to cellular coupling. The colored micrograph identifies the individual regions used for analysis.',
'The result supports substantial independence among nearby sensory-cell oscillations in this preparation. It does not exclude all interactions or establish independence after signals converge centrally. Optical separation and imaging resolution constrain a negative result, so lack of correlation should not be expanded into proof that no communication is possible.',
'Independent oscillators can provide diverse temporal sensitivities. A population may become more informative by combining their outputs centrally even when neighboring peripheral cells do not synchronize with one another.')
add('Cyclic nucleotides can support peripheral inhibition','cyclic',
'A **second messenger** is an intracellular molecule whose concentration changes after signaling begins. Michel and Ache tested cyclic nucleotides in lobster sensory neurons that were excited by food extract but inhibited by proline. Whole-cell recordings were made at a holding voltage of −60 mV.',
'Proline produced a small outward current in this cell class. The phosphodiesterase inhibitor IBMX at 1 mM and membrane-permeant cyclic-nucleotide analogs could mimic an outward response. These manipulations link intracellular cyclic-nucleotide accumulation to a conductance associated with peripheral inhibition.',
'The interpretation builds on an odor-evoked potassium conductance characterized in this receptor-cell system. Pharmacological mimicry does not identify the odor-binding receptor or prove that one nucleotide is the exclusive physiological signal. Drug actions and analog selectivity require comparison with cells lacking the same proline-inhibitory phenotype.',
'A phosphodiesterase normally breaks down cyclic nucleotides. Blocking it can raise intracellular signaling levels, but its inhibitor is a pathway probe rather than an odor-specific receptor ligand.',anatomy='somata')
add('Enzyme activation probes a candidate inhibitory pathway','forskolin',
'**Adenylyl cyclase** synthesizes cyclic AMP, or cAMP. Michel and Ache applied forskolin, an activator of this enzyme, to test whether increasing its activity could reproduce proline-associated inhibition. Saline application provided a comparison for the mechanical delivery of solution.',
'Forskolin at 50 µM evoked an outward current in proline-inhibited neurons, and IBMX enhanced related responses by reducing nucleotide breakdown. Cells excited by food extract but not inhibited by proline supplied a contrasting response class, helping separate a general toxic effect from pathway-dependent sensitivity.',
'The results support cyclic-nucleotide participation in inhibitory transduction. They do not prove a complete receptor-to-enzyme sequence in an intact searching lobster or identify a GPCR that initiates it. Modern IR expression and earlier biochemical signaling findings must therefore be evaluated together without forcing them into one experimentally complete pathway.',
'Opening a potassium conductance can stabilize or shift voltage toward the potassium equilibrium potential. The behavioral meaning depends on which sensory neuron is inhibited, not on potassium flow alone.',anatomy='somata',also=('ir13',))
add('Odor rapidly changes dendritic second messengers','secondtime',
'Boekhoff and colleagues isolated membranes enriched from the outer dendrites of Panulirus olfactory hairs. A **quench-flow assay** mixes membrane material with stimulus and rapidly stops the reaction, allowing biochemical changes over milliseconds to be measured independently of spike output.',
'Food extract produced transient increases in cAMP and **inositol 1,4,5-trisphosphate**, or IP3, peaking within approximately 50 ms. IP3 is a signaling molecule produced from membrane phosphoinositides. The timing is fast enough to participate in early sensory transduction rather than only a delayed behavioral response.',
'The assay establishes rapid odor-associated biochemical signaling in pooled dendritic material. It does not demonstrate that both messengers rise in every individual neuron, or that a measured rise directly opens a particular channel. Pooling, biochemical enrichment and separation from the intact organ limit cell-specific circuit interpretations.',
'A rapid biochemical response can be compatible with a causal transduction role without proving it. Necessity would require selectively disrupting that response while preserving other cellular functions and measuring sensory output.',anatomy='dendrites')
add('Ligand concentration changes messenger recruitment','secondligands',
'Boekhoff and colleagues compared taurine and proline because individual ligands can excite one lobster sensory neuron yet inhibit another. At 1 µM, taurine preferentially elevated IP3 and proline preferentially elevated cAMP in isolated dendritic membranes. The published plots show these distinct low-dose time courses.',
'At 100 µM, both ligands elevated both signals while retaining different preferences. Taurine produced peak IP3 near 630 pmol/mg and cAMP near 280 pmol/mg; proline produced cAMP near 720 pmol/mg and IP3 near 220 pmol/mg.',
'The concentration dependence argues against assigning each ligand an exclusively fixed messenger pathway. Picomoles per milligram normalize the measured messenger quantity to membrane protein, not to one neuron. The data do not identify which receptor proteins or cell combinations generated the pooled signal, leaving several mechanistic explanations open.',
'The illustrated low-dose figure and the stated higher-dose values answer complementary questions. The higher-dose measurements come from Figure 4 of the same paper, rather than a numerical extrapolation from the displayed traces.',anatomy='dendrites')
add('Bursting neurons supply diverse temporal reference scales','burstperiod',
'Park and colleagues recorded bursting olfactory receptor neurons and quantified the intervals between spontaneous bursts. A **quasiperiodic oscillator** repeats approximately, with variability rather than a perfectly fixed period. Such intrinsic activity offers a possible reference against which incoming odor encounters can be registered.',
'The recorded cells displayed different mean burst intervals and within-cell variation. Some repeated over a few seconds, whereas others had substantially longer intervals. The original figure compares electrical records and interval distributions, establishing diversity in measured cellular timing before a population decoder is proposed.',
'An intrinsic period is a property of the recorded cell under these conditions, not a direct measurement of plume encounter rate. The diversity may support multiple temporal sensitivities, but its usefulness for navigation requires input-dependent responses and downstream interpretation. Recording spontaneous bursts alone cannot demonstrate a working distance or direction estimate.',
'A quasiperiodic cell is not a stopwatch with a perfectly reproducible tick. Trial-to-trial variability must be incorporated when evaluating how much information its response carries.',anatomy='somata')
add('Odor-response probability depends on bursting phase','burstphase',
'**Phase** describes where a neuron lies within its recurring burst cycle. Park and colleagues delivered comparable odor pulses at different times after the previous spontaneous burst. This manipulation tests whether the same chemical input has different effects depending on the cell’s current state.',
'In an example cell, burst probability was about 50% when odor arrived 3 s after the preceding burst and approached 100% at 6 s. The same intensity therefore did not guarantee the same output. Recordings also showed odor-related changes in electrical activity and burst timing.',
'The result establishes history-dependent sensory responsiveness. It does not mean every bursting neuron has a 3- or 6-s threshold, nor that nonresponse proves chemical absence. A population with different periods could jointly report encounter timing, but behavioral use of that information remains a further hypothesis.',
'A refractory or low-responsiveness phase can conceal an encounter in one cell. Other cells at different phases could respond, making population activity more informative than a single-neuron yes-or-no response.',anatomy='somata')
add('A published decoder tests the timing-code hypothesis','burstdecode',
'Park and colleagues fitted oscillator-response models using experimentally measured properties of bursting neurons, then combined 2,000 synthetic neurons into a population. A **decoder** is an analysis rule that estimates an input from output activity. It tests whether measured response rules could carry temporal information.',
'The model estimated intervals among presented events, including inputs at 10, 12, 35, 40 and 43 s. Combining cells with different intrinsic periods improved access to the time since a previous encounter. The displayed curves are the authors’ published synthetic-population results.',
'The study demonstrates coding feasibility under its model assumptions, not simultaneous recordings from 2,000 real neurons or a lobster’s actual decision rule. Successful model decoding cannot establish behavioral necessity. Selective disruption of bursting and measurement of plume tracking would be needed to connect the proposed code causally to searching.',
'A computationally available signal is not automatically read out by the animal. The model motivates a behavioral prediction, while its parameters and idealized decoder define the limits of that prediction.',anatomy='somata')
add('Central transmission can suppress repeated afferent input','paired',
'An **afferent** neuron carries sensory input toward the brain. Wachowiak and Cohen electrically stimulated the lobster antennular nerve and recorded voltage-sensitive dye signals in the nerve and olfactory lobe. The published anatomy identifies the central region receiving these sensory axons.',
'Two 2-ms shocks separated by approximately 300–400 ms produced a smaller second response in the olfactory lobe, while the nerve response was less affected. Calcium-free, high-magnesium saline reduced synaptic transmission, helping separate incoming axonal signals from activity generated by the local network.',
'The comparison locates suppression beyond peripheral conduction in the tested preparation. Electrical shocks synchronize afferents differently from natural odor, and a population optical signal does not identify each synapse. The result establishes central modulation of incoming information without demonstrating a particular turn command or source-search strategy.',
'The olfactory lobe is a primary central processing region, not the sensory hair itself. Paired-pulse suppression compares the second response with the first while controlling the delivered electrical stimulus.')
add('GABA and histamine inhibit lobster afferent transmission','drugs',
'**GABA**, gamma-aminobutyric acid, and **histamine** can act as neurotransmitters. Wachowiak and Cohen applied them while measuring lobster afferent voltage signals. Calcium-free conditions reduced network transmission, allowing drug effects on incoming sensory processes to be distinguished from ordinary downstream synaptic activity.',
'At 100 µM, histamine reduced the measured response by about 82% and GABA by about 45%. At 30 µM, histamine still reduced it by about 61%, whereas GABA had little effect. Responses recovered during washout, arguing against irreversible damage as the main explanation.',
'These dose-dependent effects support distinct inhibitory sensitivities of lobster afferent transmission. The study did not measure odor-search behavior or identify every receptor subunit. The authors proposed **shunting inhibition**: ligand-gated conductance lowers membrane resistance, reducing terminal spike amplitude or propagation. They did not distinguish these alternatives or directly measure presynaptic calcium entry in the lobster.',
'Presynaptic means acting on the input side of a synapse. Opening a shunting conductance allows current to leak across the membrane, reducing local voltage changes. A weaker spike can then reduce transmitter release; the channel’s exact molecular composition and natural behavioral recruitment were not measured here.',anatomy='brain')
add('Antagonists distinguish two inhibitory receptor actions','separate',
'A **receptor antagonist** reduces activation of a receptor by its ligand. Wachowiak and Cohen used picrotoxin to test GABA-sensitive inhibition and cimetidine to test histamine-sensitive inhibition in lobster olfactory afferents. The pharmacological comparisons followed control recordings from the same preparation.',
'Picrotoxin at 100 µM blocked the GABA effect, whereas histamine inhibition persisted. Cimetidine at 5 mM reduced the histamine effect without producing the same blockade of GABA. The separation argues that the transmitters do not act through one indistinguishable receptor mechanism.',
'The findings constrain receptor classes and the locus of modulation, but these drugs are not perfectly selective molecular labels at every concentration. An isolated nerve segment was comparatively unaffected, supporting a central-terminal locus. Exact channel subunits and natural release during a lobster’s food search were not established.',
'Histamine used as a central transmitter must be distinguished from histamine delivered as an odorant to sensory dendrites in other experiments. Site of application and the recorded response determine which role is being tested.',anatomy='brain')
add('Joint odor and flow sampling offers direction cues','flux',
'**Odor flux** combines chemical concentration with the motion carrying that chemical. Pravin and Reidenbach measured flow and fluorescent concentration in a flume, then developed a three-dimensional fluid model constrained by those measurements. This addresses direction information unavailable from concentration alone.',
'The authors’ published model showed transverse chemical transport toward the plume center on opposite sides of the plume. Useful differences emerged over averaging intervals of approximately 0.5 s. The displayed colored traces are their modeled transverse flux, not trajectories or neural recordings from lobsters.',
'Joint chemical and mechanical sensing could therefore provide a directional cue, but the study establishes physical availability rather than biological implementation. No lobster neuron was shown multiplying velocity by concentration, and no selective behavioral test demonstrated this calculation. The proposed mechanism should remain distinct from established source-search and lesion results.',
'Transverse means across the main flow direction. A concentration reading can signal presence, while correlated fluctuations in flow can additionally indicate where odor-bearing water is being transported.',also=('search04',))
add('Plume intermittency supplies a different spatial statistic','intermittency',
'**Intermittency** describes the temporal discontinuity of odor. Michaelis and colleagues quantified it as the count of concentration spikes crossing a threshold within a time window. Michaelis and colleagues used a turbulent-plume model validated against laboratory fluorescence and velocity measurements. They compared intermittency with concentration as potential information for aquatic odor-source tracking.',
'The model covered a 5 × 0.5 × 0.15 m domain with mean flow near 0.02 m/s. Intermittency profiles depended on cross-stream position and the observation window. At plume edges, bilateral differences in encounter frequency could remain informative when instantaneous concentration was unreliable.',
'These results propose a statistic that complements a mean concentration reading. The published profiles are model-derived and threshold dependent, not direct measurements of lobster navigation commands. Physical validation strengthens the plume representation but does not validate every assumption about sensory thresholds, memory windows or bilateral neural comparisons.',
'A threshold defines an encounter when concentration crosses from below to above it. Its choice can change encounter counts, so an intermittency code requires a biologically plausible detector as well as a physically realistic plume.')
add('Search combines sampling, neural timing and context','samplefreq',
'Michaelis and colleagues compared modeled intermittency estimates at different sampling frequencies and tested simulated search rules. The original figure shows how a finite observation window and sample schedule affect the estimated chemical statistic. This makes sampling strategy part of the navigation hypothesis rather than a passive detail.',
'Their results support temporal encounter information alongside concentration under specified plume conditions. Earlier measurements show why those conditions matter: flicking changes encounter gaps, bursting neurons respond according to recent history, and removing one antennular pathway can preserve arrival while reducing path straightness.',
'Together, the studies connect physical acquisition, peripheral coding and source-directed behavior without establishing every intervening synapse. A complete account must distinguish measured fluid patterns, recorded neuronal responses and actual animal trajectories. Neither a successful model search nor receptor expression alone proves the mechanism that a lobster uses in nature.',
'The strongest next test would manipulate a specific timing mechanism while preserving chemical detection, then measure path efficiency under controlled plume statistics. That experiment would link a proposed neural code to its behavioral consequence.',also=('sampling11','burst14','search04'))

assert len(slides)==44,len(slides)
for i,s in enumerate(slides,2):
 assert len(s['title'])<=62,(i,len(s['title']))
 w=len(re.sub(r'\*\*|_','',' '.join(s['body'])).split());assert 90<=w<=170,(i,w)
spec={'lecture':25,'theme':'powder-oxblood','content_slides':44,'title_image':fig('animal'),'slides':slides,'takeaways':{'items':[
{'lead':'Behavior changes during approach','text':'Food odor changes walking speed, heading and close-range raking; successful paths do not follow one invariant turning program.'},
{'lead':'Sensory pathways overlap conditionally','text':'Either antennular chemical pathway can preserve source finding in Panulirus, while selective loss can reduce path efficiency.'},
{'lead':'Sniffing filters input mechanically','text':'Fast flicks replace water between aesthetascs; slow returns retain it, changing the timing and spatial pattern reaching receptors.'},
{'lead':'Expression does not establish receptor function','text':'IR localization and single-cell coexpression identify candidate machinery, but ligand specificity, channel composition and causal function require further tests.'},
{'lead':'Timing begins in the periphery','text':'Excitation, inhibition and intrinsic bursting occur in sensory neurons; phase-dependent responses can carry encounter-history information.'},
{'lead':'Navigation requires linked evidence','text':'Central inhibition changes transmission, while plume and decoding models propose usable cues; their behavioral necessity remains to be demonstrated.'}
],'cite':'Moore et al. (1991); Horner et al. (2004); Koehl et al. (2001); Corey et al. (2013); Kozma et al. (2020); Park et al. (2014)','refs':[REF[k]for k in ['search91','search04','sniff01','flick08','ir13','single20','diversity12','cyclic92','dual94','burst14','inhibit99','flow13','plume20']]}}
(H/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n');(H/'references.json').write_text(json.dumps(REF,indent=2,ensure_ascii=False)+'\n')
print('44 content slides; words',min(len(' '.join(s['body']).split())for s in slides),max(len(' '.join(s['body']).split())for s in slides))
