"""Build the Cassiopea special-topic lecture from verified primary studies."""
from pathlib import Path
import copy
import json

B = Path(__file__).resolve().parent
R = {s['id']: s for s in json.loads((B / 'research.json').read_text())['sources']}
C = {'amplatz': 'Amplatz et al. (2024)', 'abrams': 'Abrams et al. (2025)',
     'nath': 'Nath et al. (2017)', 'mayer': 'Mayer (1915)',
     'mayer16': 'Mayer (1916)', 'cary': 'Cary (1915)',
     'nakanishi': 'Nakanishi et al. (2009)', 'muffett': 'Muffett et al. (2025)',
     'lyndby': 'Lyndby et al. (2023)', 'anuszczyk': 'Anuszczyk et al. (2025)',
     'steinworth': 'Steinworth & Martindale (2025)'}
I = json.loads((B / 'figure_sources.json').read_text())
F = {name: {'path': f'figures/{name}.png', 'kind': 'article',
            'caption': f"{C[f['paper']]}, Fig. {f['figure']}. {f['description']}",
            'source_url': 'https://doi.org/' + R[f['paper']]['doi']}
     for name, f in I.items()}
S = []


def add(title, papers, images, body, teaching, height=2.15):
    ids = papers.split()
    for name in images:
        if I[name]['paper'] not in ids:
            ids.append(I[name]['paper'])
    paragraphs = body.split('||')
    assert len(paragraphs) == 3
    slide = {'title': title, 'body': paragraphs,
             'cite': '; '.join(C[k] for k in ids),
             'refs': [R[k]['reference'] for k in ids],
             'transcript': [paragraphs[0], [paragraphs[1], [teaching]], paragraphs[2]],
             'figure_width': 6.0}
    if len(images) == 1:
        slide.update(layout='figure-right', figure=copy.deepcopy(F[images[0]]))
    else:
        assert len(images) == 2
        slide.update(layout='figures-right', figures=[copy.deepcopy(F[n]) for n in images],
                     primary_figure_height=height)
    S.append(slide)


add('Cassiopea contracts its bell while remaining in place', 'nath', ['bell','pulse'],
'''_Cassiopea_ is an upside-down **scyphozoan**, a jellyfish belonging to the class Scyphozoa. Its **bell** is the contractile body disc; the oral arms face upward while the bell rests on a surface. Nath and colleagues recorded this stationary pulsing behavior across repeated 12-h light and dark periods.||Bell relaxation and contraction changed the average brightness of an infrared video region. Peaks in the resulting signal supplied pulse times and the **inter-pulse interval**, the elapsed time between successive contractions. Typical ongoing pulsation was approximately one contraction per second, although individual rates varied.||A continuously contracting animal can remain in the same location. This motor rhythm therefore requires measurements of contractions rather than displacement alone. The video signal quantifies behavioral output; it does not identify the neurons that initiate a pulse or directly measure their electrical activity.''',
'The oral surface contains the mouth and oral arms; the opposite surface is aboral. In this preparation the animal is not required to swim through a tank. The investigators can follow the same individual for days without equating stillness of its position with absence of motor activity.')

add('The bell contains distinct tissue compartments', 'lyndby', ['oct1'],
'''The **subumbrella** is the oral-facing bell surface; the **exumbrella** is its opposite surface. Between tissue layers lies **mesoglea**, the extracellular material that forms much of the bell. Lyndby and colleagues examined juvenile _Cassiopea_ using **optical coherence tomography**, or OCT, which resolves tissue structure through reflected near-infrared light.||A whole-medusa scan covered 7 × 7 × 2.8 mm. Successive sections separated the bell covering, internal canals and oral structures without requiring the intact animal to be sectioned. Signal strength differed among tissues, and strongly scattering structures were distinguishable from surrounding material.||These measurements establish spatial relationships among bell compartments. OCT brightness represents optical scattering, rather than neuronal firing or a neuron-specific label. Consequently, a canal or tissue boundary can be localized by OCT, while identifying the associated nerve cells requires additional anatomical markers.''',
'The gastrovascular canals are passages connected to the digestive cavity. They must be distinguished from neuronal processes even when both extend radially. OCT preserves the three-dimensional tissue arrangement, but its signal alone cannot determine whether a particular bright structure is neural.')

add('Circular and radial muscle fibers occupy different regions', 'muffett', ['muscle'],
'''An **ephyra** is the young medusa released from a scyphozoan polyp. Muffett and colleagues mapped the bell musculature of _Cassiopea xamachana_ ephyrae with **phalloidin**, a probe that binds filamentous actin, the protein polymer enriched in muscle contractile structures. Their anatomical preparations included ephyrae approximately 5 mm in diameter.||A broad **coronal muscle band** surrounded the oral-arm bases and extended toward the bell rim. Closely arranged circular fibers occurred at its inner and outer edges. Between these edges, fibers followed an undulating pattern; within the **lappets**, marginal bell lobes, the musculature became radially oriented.||The spatial arrangement supplies an anatomical basis for coordinated bell deformation. Actin labeling identifies fiber organization, but it does not record which fibers become active first or establish their synaptic inputs. Muscle geometry and neural control are separate measured properties.''',
'Circular fibers run around the oral–aboral axis, whereas radial fibers extend toward the bell margin. The authors compared intact muscle organization with tissue undergoing repair after bisection. The fluorophore is part of the published staining experiment; the source image has not been recolored.')

add('Different life stages have different motor structures', 'steinworth amplatz', ['life'],
'''_Cassiopea xamachana_ alternates between a sexually reproducing medusa and a sessile **polyp**, a tentacle-bearing form attached by its aboral end. Fertilized eggs produce a ciliated **planula larva**. **Strobilation** transforms a polyp region into an ephyra, whereas a **planuloid bud** is an asexually produced swimming propagule.||Steinworth and Martindale documented these stages at common photographic scale, with a 1-mm reference and a separate larval inset. Amplatz and colleagues found that settlement-to-polyp metamorphosis took about 3 days at 20–22°C under their culture conditions; detached planuloid buds developed into polyps over approximately 3–6 days.||A larval ciliary system, a polyp neuromuscular system and a medusa bell-control system are different preparations. Results from one stage cannot automatically identify the circuit of another. Developmental anatomy establishes when structures appear and how their positions change.''',
'A planula follows sexual reproduction, while a planuloid is produced from polyp tissue without fertilization. Both can swim with cilia and settle, but their inherited tissue arrangements differ. The ephyra is already a medusa stage and should not be confused with either swimming propagule.')

add('Larval neurites form a basiepithelial plexus', 'amplatz', ['planula_net'],
'''A **neurite** is a neuronal process that carries signals away from or toward the cell body. In _Cassiopea_ planulae, Amplatz and colleagues used antibody labeling and **confocal microscopy**, which collects optical sections through fluorescent specimens, to localize neurites and candidate sensory cells.||Antibodies against FMRFamide produced **FMRFamide-like immunoreactivity**: binding consistent with a related peptide antigen, rather than chemical identification of an exact peptide. Labeled processes formed a **basiepithelial plexus**, a neural meshwork near the base of the surface tissue. Longitudinal bundles extended across more than three quarters of the larval length.||Primary- and secondary-antibody omission controls tested background binding. The distribution establishes a spatially organized larval network, but antibody labeling does not measure peptide release, synaptic strength or spike propagation. The exact transmitter identity remains distinct from the observed immunoreactivity.''',
'FMRFamide is a short neuropeptide; the antibody may recognize related molecules that share its antigenic features. Basiepithelial describes the position of the meshwork beneath the outer portions of epithelial cells. A long labeled process need not be a single axon traced from one known cell.')

add('Larval sensory-cell bodies are spatially polarized', 'amplatz', ['planula_cells'],
'''A **sensory neuron** receives information through a specialized cell region and relays it through neuronal processes. In early _Cassiopea_ planulae, FMRFamide-like cell bodies occupied the superficial **ectoderm**, the outer embryonic tissue layer, predominantly in the aboral half. Their processes extended inward toward the basal neural meshwork.||Amplatz and colleagues compared peptide-like labeling with tyrosinated α-tubulin labeling. **Tubulin** is a structural component of microtubules and also occurs in cilia and other nonneuronal structures. The larval preparations contained both basal labeled neurites and thin tubulin-positive fibers throughout the ectoderm.||Omission controls revealed nonspecific secondary-antibody binding near the aboral tip, so that region could not establish the presence or absence of an apical neural organ. The supported result is a polarized distribution outside that ambiguous region, rather than a complete census of every larval sensory cell.''',
'The mouth-bearing pole is oral, and the opposite pole is aboral. A spatially polarized sensory population differs from an evenly distributed set of cell bodies, even when its processes extend widely. Antibody background at one pole prevents a stronger claim about the entire surface.')

add('Settlement remodels the larval nervous system', 'amplatz', ['planula_degen'],
'''During **metamorphosis**, a larva changes its body organization as it becomes a polyp. Amplatz and colleagues followed _Cassiopea_ settlement through a hood-shaped stage, mouth formation and stalk elongation, using the same peptide-like and tubulin-like neural markers across developmental stages.||Long FMRFamide-like neurites in the oral half diminished first. Labeled cell bodies subsequently became less numerous and irregularly shaped, and scattered labeled fragments remained during stalk formation. The aborally concentrated larval labeling was no longer detectable by the tentacle stage; polyp metamorphosis required approximately 3 days at 20–22°C.||The changing distribution supports extensive neural reorganization rather than simple enlargement of an unchanged larval net. **Apoptosis**, regulated cell death, was proposed as an explanation for disappearing cells, but a specific cell-death assay was not performed. Loss of immunoreactivity alone cannot distinguish cell death from altered marker expression.''',
'Fragments with peptide-like labeling occurred in the endoderm, the inner tissue layer. Their identity as remnants of dying neurons was proposed from appearance and timing. The authors explicitly distinguished that interpretation from a direct experimental demonstration of apoptosis.')

add('Polyp neurites concentrate around the oral disc', 'amplatz', ['polyp_ring'],
'''The **hypostome** is the raised oral region bearing the polyp mouth. Amplatz and colleagues examined _Cassiopea_ polyps after tentacle formation and found a new concentration of FMRFamide-like neurites around the **oral disc**, the surface from which the tentacles arise.||In late tentacle stages, labeled processes spanned the oral disc and hypostome. The densest concentration formed a loose **oral nerve ring**, a circumferential arrangement below the tentacle bases. Continued polyp growth elaborated the network, rather than preserving the earlier aboral larval concentration.||The same labeling protocol across stages links the spatial change to development. A ring-shaped anatomical concentration does not establish a single central controller or a direction of information flow. In these preparations, peptide-like neurites were clear, while corresponding immunoreactive cell bodies were not consistently identifiable.''',
'The term nerve ring describes a concentration of neural processes, not a vertebrate-like brain. The transition from larva to polyp changes which end of the animal contains the dominant labeled neural concentration. Cell bodies can remain difficult to identify even when their processes are readily labeled.')

add('Polyp tentacles contain branching ectodermal neurites', 'amplatz', ['polyp_tentacle'],
'''Polyp tentacles extend the oral disc into the surrounding water. In developing _Cassiopea_ polyps, Amplatz and colleagues localized FMRFamide-like neural processes within the tentacle ectoderm using optical sections through the tentacle wall, rather than treating the entire tentacle as a single structure.||The labeled processes branched around the ectoderm and were continuous with the broader oral-region network. The adjacent **endoderm** contained large, vacuolated discoidal cells arranged in a single axial row. These inner cells differed in position and morphology from the fine neural processes in the outer tissue.||Comparing tissue layers prevents assignment of every tentacle signal to the same cell class. The branching ectodermal network establishes anatomical innervation, but the observations do not identify a specific sensory stimulus, transmitter receptor or muscle response generated by each branch.''',
'An epithelial layer is a sheet of cells covering a surface or lining a cavity. In a tentacle, ectodermal processes and endodermal cells can overlap in a projected image. Optical sectioning provides depth information that helps separate these structures without inferring unmeasured physiological connections.')

add('Septal neurites accompany four muscle bands', 'amplatz', ['polyp_septal'],
'''The polyp **stalk** links the expanded **calyx**, or body cup, to the attachment region. Amplatz and colleagues detected four prominent **septal muscle bands**, longitudinal structures extending through this body axis, and compared actin labeling with tubulin-like labeling in developing _Cassiopea_ polyps.||Distinct tubulin-like **septal neurites** ran alongside the four bands from the foot and stalk toward the tentacle bases. Each band was accompanied by several processes with branches. Additional thin longitudinal processes were distributed across the outer stalk and calyx.||Spatial correspondence supports a differentiated neuromuscular arrangement within the polyp. It does not establish that every adjacent neurite directly synapses onto the neighboring muscle or that one neuron controls an entire band. The comparison with actin staining separates candidate neural fibers from contractile structures.''',
'Septal in this context refers to the longitudinal internal arrangement associated with the four muscle bands. Fine solitary body processes coexist with the more prominent septal strands. Anatomical adjacency constrains possible motor pathways but cannot substitute for a recording or selective perturbation.')

add('Tubulin labeling can include nonneuronal structures', 'amplatz', ['stain_compare','bud_fibers'],
'''A **cell marker** is a molecular feature used to recognize a cell or structure. Its usefulness depends on specificity. Amplatz and colleagues compared phalloidin-labeled actin with tyrosinated tubulin-like labeling in the same _Cassiopea_ polyp regions, including tentacles and developing bud sites.||Tentacle tubulin labeling closely resembled muscle labeling and also included **nematocytes**, stinging cells, and cilia. At bud-forming sites, some fine tubulin-positive fibers lacked the corresponding phalloidin signal and could be distinguished from muscles. Antibody-omission controls also identified intrinsic background and secondary-antibody binding.||Tubulin fluorescence alone therefore cannot define a complete neuronal population. Combining tissue location, cell morphology, actin comparison and omission controls narrows the interpretation. Absence of a clearly separable neural signal in the tentacle does not establish absence of nerves there.''',
'A cilium contains microtubules, so a tubulin antibody can label it strongly even though it is not a neuronal process. The same molecular stain has different interpretive limitations in different tissue regions. A negative result is meaningful only within the detection and specificity limits of the preparation.')

add('Asexual buds inherit a different neural starting pattern', 'amplatz', ['planuloid','serotonin'],
'''A _Cassiopea_ **planuloid bud** forms from an adult polyp and separates as a swimming propagule. Amplatz and colleagues followed its neural development with tubulin-like and serotonin-like antibody labeling, then compared the stages with those of sexually produced planula larvae.||Early detached buds already contained four septal muscle strands and associated tubulin-like neuronal strands. These processes extended orally, branched and later connected near the stalk–calyx boundary. By the young-polyp stage, the principal neural arrangements resembled those of planula-derived polyps; detached-bud development took approximately 3–6 days at 20–22°C.||The two routes reach similar polyp anatomy from different starting tissue organizations. **Serotonin-like immunoreactivity** also occurred in endodermal cells without visible neurites, so it did not establish that every labeled cell was neuronal or released serotonin as a transmitter.''',
'Serotonin is a signaling molecule, but antibody recognition alone is not a direct chemical assay or release measurement. The large discoidal tentacle cells are an example in which signal and neuronal identity cannot be equated. Asexual development retains structures that are not present in the same form in early sexual larvae.')

add('Rhopalia are distributed around the medusa margin', 'abrams nath', ['rhop_margin','oct_rhop'],
'''A **rhopalium** is a marginal sensory structure containing neural tissue associated with bell-rhythm control. In _Cassiopea_ medusae, multiple rhopalia are radially spaced around the bell rim. Their distribution combines a widespread control architecture with localized concentrations of neurons.||Abrams and colleagues examined the marginal organs directly and sampled rhopalial tissue separately from the remaining bell. Lyndby and colleagues resolved rhopalia in intact medusae approximately 1 and 4 cm in diameter with OCT. A canal extended to each organ's base and into the neighboring marginal tissue.||These observations identify repeated sensory–neural sites rather than one head-localized brain. The presence of several organs does not mean they fire independently during every bell pulse. Anatomical distribution establishes their locations; coordination and rhythm generation require functional tests.''',
'Ganglia are local concentrations of neuronal cell bodies and processes. A distributed nervous system can contain ganglia without having one dominant central brain. The OCT canal is a gastrovascular passage, not a neuronal axon, and its function must be distinguished from the adjacent nervous tissue.')

add('A rhopalium contains three anatomical segments', 'abrams', ['rhop_three','rhop_rna'],
'''Abrams and colleagues divided the _Cassiopea_ rhopalium into **terminal**, **intermediate** and **basal** segments. The terminal end projects away from the bell; the basal region connects the organ to the medusa. Their bright-field and gene-expression preparations preserved the relation among these regions.||A dark **lithocyst**, the statolith-containing balance structure, occupied the terminal region. Pigmented tissue associated with a **spot ocellus**, a simple light-sensitive organ, lay near the terminal–intermediate boundary. The **radial canal** approached the organ from its basal side, while chrnal-E expression occupied rhopalial neural regions.||The 50-µm reference scale permits comparison of localized tissue compartments without treating the whole organ as one cell. Gross segment boundaries do not locate every pacemaker neuron. The published ganglion-group diagram was adapted from _Aurelia_, so that detailed comparative map is not a complete Cassiopea cell census.''',
'A statolith is a dense body whose mechanical loading can contribute to sensing orientation. The lithocyst contains this material, whereas an ocellus is associated with light detection. Distinguishing those structures prevents a pigmented or strongly scattering region from being assigned to the wrong sensory function.')

add('Rhopalial canals connect organs with bell tissues', 'lyndby', ['oct_rhop','oct_canal'],
'''Lyndby and colleagues used noninvasive OCT to examine _Cassiopea_ rhopalia and their neighboring bell tissue. Serial sections localized the rhopalial canal, its branches and the strongly scattering sensory organ while preserving the organ's attachment to the bell margin.||In medusae approximately 1 cm in diameter, the canal extended to the rhopalial base and split toward marginal tissues. Sections also distinguished dense scattering granules from clusters of algal symbionts. **Symbionts** are organisms living in a close biological association with a host; these intracellular algae support Cassiopea photosymbiosis.||The measured anatomy places sensory and neural structures within a canal-connected, optically heterogeneous margin. OCT does not identify a synapse or distinguish sensory from pacemaker cells by itself. Strong scattering is a tissue property, rather than evidence that the rhopalium is electrically active at that moment.''',
'The term photosymbiosis describes a partnership involving photosynthetic organisms. Tissue around a rhopalial canal contains components with very different scattering strengths. Their optical distinction is useful for morphology but cannot be treated as a neuron-specific contrast mechanism.')

add('Comparative rhopalia contain mechanosensory cells', 'nakanishi', ['naka3gh','naka4'],
'''Nakanishi and colleagues examined rhopalia of _Aurelia_ sp.1, another scyphozoan, with confocal and electron microscopy. Its **touch plate** is a sensory region associated with the lithocyst. **Mechanosensation** detects physical displacement or force; these structures are candidates for sensing orientation through mechanical loading.||Touch-plate cells had apical cilia and actin-rich rings consistent with associated **stereocilia**, microvillar projections containing actin. Electron microscopy also resolved stereocilia in oral rhopalial cells. Neuronal processes from the touch-plate region joined a tubulin- and taurine-reactive network extending toward the motor net.||The measurements identify sensory specializations and candidate pathways in Aurelia. They do not measure force-gated currents or identify the responsible mechanotransduction channel. Similar organs in Cassiopea justify a comparative anatomical question, while the detailed ultrastructural findings remain species-specific.''',
'A cilium contains microtubules, whereas a stereocilium is an actin-rich projection despite the similar name. Taurine is a small amino-sulfonic molecule used here as an immunochemical marker. Its immunoreactivity does not itself establish the transmitter released by a sensory cell.')

add('Comparative ocelli connect to rhopalial neurites', 'nakanishi abrams', ['naka3i','rhop_three'],
'''An **ocellus** is a simple photoreceptive structure. Nakanishi and colleagues identified a pigment-cup ocellus on the oral side and a pigment-spot ocellus on the aboral side of _Aurelia_ rhopalia, using optical sections that separated pigment-bearing layers from labeled sensory processes.||The cup organ contained ciliated sensory cells facing a pigment-cell layer. Their basal processes joined the FMRFamide-reactive rhopalial network. In the spot organ, labeled pigmented cells also extended processes toward that network. Cassiopea bright-field anatomy independently localized pigmented spot-ocellus tissue near its terminal rhopalial region.||Anatomy supports sensory access to local neural networks. It does not establish visual acuity, an image-forming retina or the sign of a light response. The Aurelia cellular connections are comparative evidence; the Cassiopea pigment location alone cannot establish identical cellular wiring.''',
'The terms oral and aboral specify opposite sides of a rhopalium as well as of the bell. A pigment cup and a pigment spot have different cellular arrangements. Neither structure should be assigned the lens-based visual capabilities of a box jellyfish without separate evidence.')

add('Two comparative nerve nets have distinct distributions', 'nakanishi', ['naka2ab','naka2cd'],
'''A **nerve net** is an interconnected arrangement of neuronal processes distributed through tissue. Nakanishi and colleagues distinguished a **motor nerve net**, or MNN, and a **diffuse nerve net**, or DNN, in _Aurelia_ ephyrae by combining antibody labeling with actin-labeled muscle anatomy.||Thick, strongly tubulin-reactive motor-net processes spread through the subumbrella and connected with rhopalia. FMRFamide-reactive diffuse-net fibers were finer and associated with both subumbrellar and exumbrellar surfaces. In the same specimens, the two labeling patterns followed different paths near the rhopalial base.||Multiple spatial patterns contradict a description of a nerve net as one anatomically uniform sheet. Marker-defined pathways constrain possible functions, but anatomy alone cannot measure conduction speed or assign every behavioral response to one net. This detailed separation was measured in Aurelia, rather than directly mapped throughout adult Cassiopea.''',
'The motor net is associated with swimming-muscle control in this scyphozoan preparation. Diffuse refers to the distribution of the second network, not a claim that it has no organization. Comparing the two in the same tissue helps separate distinct processes from variation in imaging conditions.')

add('Motor-net processes extend between radial regions', 'nakanishi', ['naka2gh','naka2cd'],
'''The comparative _Aurelia_ motor net contains thick neuronal processes spanning the subumbrellar surface between rhopalia and muscle-bearing bell regions. Nakanishi and colleagues labeled these processes with tyrosinated tubulin and taurine antibodies while phalloidin identified the surrounding muscle fibers.||The labeled motor-net neurons were predominantly **bipolar**, with two principal processes extending from the cell body. Thick projections from the rhopalial base continued into this net, providing an anatomical route between local sensory–neural tissue and the distributed bell musculature.||**Connectivity** means a physical or functional relation between circuit components, but light-microscopic continuity is not a complete synaptic reconstruction. A process crossing another process does not establish a synapse, the specialized junction through which cells communicate. The source constrains circuit geometry without resolving every connection or its direction.''',
'A bipolar neuron is identified by its overall morphology, not by an assumption that its two processes have equal function. The synaptic direction of signaling cannot be read from a projected crossing. Motor-net anatomy and bell-wide propagation experiments address complementary aspects of coordination.')

add('Diffuse-net neurons have branching processes', 'nakanishi', ['naka2ef','naka3gh'],
'''In _Aurelia_ ephyrae, FMRFamide-reactive diffuse-net neurons were largely **multipolar**, with several branching processes instead of the two prominent extensions typical of the motor-net cells. Nakanishi and colleagues resolved their morphology within the same bell and rhopalial preparations.||Fine labeled processes lay near **cnidocytes**, stinging cells with a discharge apparatus, and extended from rhopalial tissue toward the surrounding net. Their distribution differed from that of the thicker motor-net processes. Cells and tissue depth were distinguished with tubulin labeling and nuclear markers.||Close association supports candidate sensory and effector pathways, but it does not establish direct control of cnidocyte discharge in this experiment. Neither peptide identity nor signaling direction follows from immunoreactivity alone. The contrasting morphologies establish differentiated network components in the comparative scyphozoan preparation.''',
'A cnidocyte contains a nematocyst, the specialized capsule used in discharge. Its position beside a neurite is an anatomical observation, while a required role of that neurite in discharge would require a functional experiment. Branching morphology does not imply that every branch connects to the same cell type.')

add('Rhopalial processes join different peripheral networks', 'nakanishi', ['naka3de','naka3gh'],
'''Nakanishi and colleagues traced marker-defined neuronal processes through _Aurelia_ rhopalia using confocal sections. The basal segment contained dense ectodermal neural tissue around a canal; neural processes extended longitudinally through the intermediate region and crossed between its two sides.||Tubulin- and taurine-reactive fibers left the basal region toward the motor net. FMRFamide-reactive fibers preferentially left lateral basal regions toward the diffuse net. Other GLWamide-reactive cells, recognized by an antibody against a different neuropeptide family, had processes confined to the rhopalium.||Distinct exits and internal distributions support differentiated sensory–neural organization within each organ. They do not establish the exact cells that generate the pacemaker rhythm. Local neuropeptide immunoreactivity also cannot specify whether a given connection excites, inhibits or modulates its target.''',
'A commissure-like structure is a set of processes crossing between the two sides of an organ. Such crossings occur even within a radially arranged animal. The small rhopalium contains internal organization, while some of its processes enter larger bell-wide networks and others remain local.')

add('Neural development precedes coordinated beating', 'nakanishi', ['naka5ghi','naka6late'],
'''Nakanishi and colleagues examined successive _Aurelia_ developmental stages while the future ephyrae remained attached to the strobilating polyp. A **prephyra** is one of these developing medusa units before liberation. Sensory structures, neural markers and beating behavior appeared in an ordered sequence.||Statolith formation began early. By the prephyra III stage, rhopalar arms contracted together spontaneously, and labeled rhopalial processes connected with the motor net. Ocellar differentiation occurred later than the initial mechanosensory structures and the onset of coordinated beating.||The temporal association places motor-network differentiation near emergence of the rhythm, without identifying a single oscillator cell. These comparisons concern fixed developmental stages and observed contractions, rather than recordings from every candidate neuron. Their timing in Aurelia cannot be assigned unchanged to Cassiopea development.''',
'A developmental sequence can separate structures that appear before and after a behavior emerges. Early coordinated beating does not require that every later sensory organ be fully mature. An anatomical sequence supports candidate mechanisms, but a selective perturbation is needed to establish a required cell class.')

add('Isolated rhopalia generate measurable electrical activity', 'abrams', ['recording','rhop_three'],
'''Abrams and colleagues isolated adjacent rhopalia from Cassiopea medusae with bell diameters of 3–5 cm. A **suction electrode** holds tissue against a recording tip and detects extracellular electrical signals. The preparation separated activity in these organs from the mechanical movement of the intact bell.||Rhopalia were maintained in filtered artificial seawater at 28°C. Baseline recordings preceded drug application, with electrical signals sampled every 0.08 ms. The **interspike interval**, or ISI, is the elapsed time between detected electrical events and provides a measure of their rhythm.||Activity persisting in the isolated preparation localizes a rhythm-generating capability to rhopalial tissue. Extracellular recordings do not identify the membrane potential of one neuron, every participating cell or the exact output reaching the muscle. The organ-level evidence complements, rather than replaces, cell-specific circuit mapping.''',
'An extracellular signal is detected outside cells, so its amplitude depends on electrode coupling and amplification. It must not be read as the transmembrane voltage of a single neuron. Recording isolated rhopalia asks where rhythmic activity can persist after separation from the bell.')

add('A receptor antagonist slows rhopalial electrical events', 'abrams', ['dtc','recording'],
'''Abrams and colleagues applied **tubocurarine**, a competitive antagonist of nicotinic acetylcholine receptors, to isolated Cassiopea rhopalia. An **antagonist** reduces receptor activation; competition means that binding interferes with access of an activating ligand to a receptor-associated site.||The Results and Figure 3 report 500 and 600 μM tubocurarine treatments. Both increased the interspike interval relative to the preceding baseline, with the higher concentration producing a larger slowing. Comparing each preparation before and after treatment controls some differences in baseline rhythmic activity.||The response supports sensitivity of rhopalial activity to this pharmacological class. It does not identify a single receptor subtype or establish acetylcholine as the endogenous transmitter. Drug action on additional targets remains possible; a receptor-specific genetic perturbation addresses a different level of causation.''',
'The concentrations shown follow the Results and Figure 3; the Methods list different tubocurarine doses. The published inconsistency should be retained in evaluating reproducibility. A longer interspike interval means slower electrical-event production, without necessarily implying failure of signal propagation through the intact bell.')

add('A receptor agonist accelerates rhopalial electrical events', 'abrams', ['nicotine','rhop_three'],
'''An **agonist** activates a receptor or promotes its activated state. Abrams and colleagues applied nicotine, an agonist of nicotinic acetylcholine receptors in established systems, to the same type of isolated Cassiopea rhopalial preparation used for antagonist experiments.||Nicotine at 50 and 75 μM decreased the interspike interval relative to baseline, with the higher concentration producing the larger reduction. The complementary agonist and antagonist responses associate receptor pharmacology with the rate of electrical-event generation in a localized neural organ.||A shorter interval establishes an acceleration under these experimental conditions. It does not demonstrate direct nicotine binding to a particular Cassiopea receptor protein. Opposite responses to two drugs strengthen a mechanistic hypothesis while leaving receptor identity, endogenous ligand and individual pacemaker-cell contributions unresolved.''',
'A concentration in micromolar units is the amount of drug per liter of bath expressed in millionths of a mole. Concentration-dependent responses are useful mechanistic evidence but are not sufficient to identify the molecular binding target. Pharmacology and gene-specific manipulations supply complementary controls.')

add('A candidate receptor resembles a ligand-gated channel', 'abrams', ['receptor','rhop_rna'],
'''Abrams and colleagues identified **Chrnal-E**, one of several Cassiopea proteins related to nicotinic acetylcholine-receptor alpha subunits. A **ligand-gated ion channel** couples binding of a chemical ligand to opening of a pore through which ions cross the cell membrane.||Sequence comparisons identified a conserved **Cys-loop**, a cysteine-associated loop characteristic of this receptor family, and candidate ligand-binding features. Published structural predictions also showed a charged vestibule resembling that of human alpha-7 receptors. The figure presents predictions based on protein sequence, rather than a measured membrane current.||An open cation-permeable pore could change neuronal excitability by allowing charge to enter or leave a cell according to electrochemical gradients. Calcium permeability and the endogenous ligand were not established for Chrnal-E. The study did not demonstrate acetylcholine synthesis in Cassiopea, so classical cholinergic transmission remains unconfirmed.''',
'The electrochemical gradient combines concentration and electrical forces acting on an ion. Calcium entry could influence intracellular signaling as well as voltage, but the predicted vestibule does not measure calcium permeability. Receptor-family similarity should not be converted into a confirmed transmitter pathway.')

add('Candidate receptor RNA localizes to rhopalia', 'abrams', ['rhop_rna','rhop_rna_quant'],
'''Abrams and colleagues used **in situ hybridization**, a method that detects a selected RNA sequence within tissue, to localize chrnal-E expression. Its labeled signal was concentrated in the neural region of Cassiopea rhopalia rather than distributed uniformly through the entire bell.||Both control and sleep-deprived animals contained rhopalia with stronger and weaker labeling. Sleep deprivation increased the labeled expression area in the measured preparations. Tissue localization linked a candidate receptor gene to organs already implicated in rhythm generation and sensory processing.||RNA localization identifies cells or tissue regions containing the transcript. It does not measure the amount of functional receptor protein at a membrane or identify all expressing cell types. Differences among rhopalia also caution against assuming that every marginal organ has an identical molecular state.''',
'A transcript is an RNA copy produced from a gene. In situ hybridization and quantitative RNA measurements can support an expression change while leaving translation, receptor assembly and membrane placement unresolved. The histological signal is not an electrical recording of pacemaker activity.')

add('RNA interference reduces a selected receptor transcript', 'abrams', ['rnai','rhop_three'],
'''**RNA interference**, or RNAi, uses double-stranded RNA to reduce expression of a matching gene. Abrams and colleagues fed Cassiopea material carrying a 387-base-pair chrnal-E sequence to test the behavioral contribution of this candidate receptor gene.||Animals received the RNAi treatment for two weeks before tissue-expression measurements. An empty-vector treatment controlled for the feeding and delivery procedure, while a separate minicollagen-targeting treatment tested whether another RNAi sequence produced the same phenotype. In situ labeling and quantitative RNA assays supported reduced chrnal-E expression.||These controls strengthen the association between the targeted sequence and its molecular effect. Knockdown reduces expression rather than guaranteeing complete elimination in every cell. The manipulation therefore tests gene contribution at the organism and tissue levels without identifying the current carried by an individual receptor.''',
'A base pair is a unit of double-stranded nucleic-acid sequence. A vector is a carrier used to deliver or express a sequence. An empty-vector control shares the delivery procedure but lacks the targeted insert; a second target helps distinguish gene-specific effects from a general response to RNAi.')

add('Receptor knockdown redistributes daily sleep', 'abrams', ['rnai_behavior'],
'''Abrams and colleagues measured Cassiopea activity after chrnal-E RNAi and the corresponding control treatments. Their behavioral classification used prolonged pulse intervals together with arousal testing to distinguish a sleep-associated state from continuously active pulsing.||After two weeks of treatment, chrnal-E knockdown increased daytime sleep and reduced nighttime sleep. Empty-vector and minicollagen treatments supplied procedural and alternative-target comparisons. The phenotype was a redistribution of sleep across the daily cycle rather than evidence that all movement was abolished.||Gene perturbation links the candidate receptor to temporal regulation of behavioral state. It does not establish that Chrnal-E alone generates the sleep rhythm, or that every effect acts directly within pacemaker neurons. Developmental, sensory and network-level contributions remain possible within the targeted animals.''',
'A daily redistribution is different from an increase at every time point. The interpretation must preserve both the daytime and nighttime findings. Molecular localization, isolated-organ physiology and behavioral perturbation converge on rhopalial involvement while each measures a different level of the mechanism.')

add('Bell-pulse timing changes between day and night', 'nath', ['daynight'],
'''Nath and colleagues monitored Cassiopea under 12-hour light and 12-hour dark cycles, using video intensity changes to detect bell contractions. Animals were maintained at 26–28°C in seawater of 30–34 parts per thousand salinity, permitting repeated observation without handling each pulse.||Mean activity was 1,155 pulses per 20 minutes during the day and 781 pulses per 20 minutes at night, a reduction of approximately 32%. Night recordings included longer interpulse intervals and extended pauses. An **interpulse interval** is the time separating two detected bell contractions.||These measurements establish reversible daily changes in motor output. Reduced pulse rate alone is insufficient to identify sleep, because feeding, temperature or tissue impairment could also slow contractions. The study therefore combined activity measurements with tests of responsiveness and recovery after prolonged disturbance.''',
'An interpulse interval concerns whole-animal contractions, whereas an interspike interval concerns recorded electrical events. The two should not be treated as identical measurements. The video assay provides a noninvasive behavioral readout, without identifying the cellular source of each pulse.')

add('Nighttime quiescence includes a reversible arousal delay', 'nath abrams', ['arousal','rhop_margin'],
'''To test **arousal**, the transition from quiescence to responsive activity, Nath and colleagues briefly supported Cassiopea above the bottom and then removed the support. The drop elicited contractions that returned the animals toward their normal resting position.||The first pulse occurred after about 2.1 seconds during the day and 5.9 seconds at night. When the drop was repeated within 30 seconds, the day–night difference disappeared. The repeated stimulus therefore tested whether the slower initial response reflected an inability to contract.||The delay followed by rapid recovery supports a reversible change in behavioral state. It does not identify which sensory cells detect the drop or which rhopalium initiates the first contraction. The test distinguishes quiescence from permanent motor failure while leaving the intervening cellular pathway to be resolved.''',
'Reversibility is central to interpreting a sleep-like state. If a second stimulus evokes a prompt response, the animal retains the machinery required for contraction. The assay measures the complete sensory-to-motor response and cannot assign its latency to one synapse or ion channel.')

add('Nighttime disturbance produces compensatory quiescence', 'nath', ['deprivation'],
'''Nath and colleagues tested **sleep homeostasis**, the compensatory regulation of sleep after its disruption, by delivering water pulses for 10 seconds every 20 minutes. The stimulation interrupted nighttime quiescence for either 6 or 12 hours while video recorded the resulting activity.||Following the 6-hour treatment, pulse activity was about 12% lower during the early subsequent day; after 12 hours of disturbance, daytime activity was about 17% lower. Delivering comparable disturbance during the day did not produce the same subsequent reduction.||The timing control argues against a simple explanation based on mechanical exertion alone. Compensatory quiescence supports a homeostatically regulated sleep-like state, but pulse counts do not locate its cellular regulator. The study did not directly measure a molecular sleep-pressure signal or its action on a particular pacemaker cell.''',
'Homeostasis describes regulated compensation rather than a fixed activity level. Disturbing animals during their usual quiescent period and active period tests whether the consequence depends on behavioral timing. A rebound in quiescence is evidence about state regulation, not a direct measurement of fatigue in an individual muscle fiber.')

add('Feeding reverses quiescence without explaining its rhythm', 'nath', ['feeding','pulse'],
'''Cassiopea contractions contribute to feeding and fluid movement, so Nath and colleagues tested whether food availability explained the daily pulse rhythm. Feeding transiently increased pulse rate, and a day–night activity difference remained during three days without feeding.||Providing food at night reversed reduced activity, showing that quiescent animals retained a capacity to increase contractions in response to an ecologically relevant stimulus. The researchers also compared activity under constant darkness and constant light after prior light–dark entrainment.||Cycling that persisted in constant darkness was consistent with an endogenous timing contribution, whereas constant light disrupted the pattern. These results separate food-induced activation from the broader daily state change. They do not identify a circadian clock gene or prove that the same clock resides in every rhopalium.''',
'Entrainment is the alignment of an endogenous rhythm with a recurring environmental cue. Circadian refers to an approximately daily endogenous rhythm. Persistence without a light–dark cycle supports an internal timing contribution, while the behavioral experiment alone does not specify its molecular oscillator.')

add('External stimulation competes with endogenous rhythms', 'anuszczyk abrams', ['external_traces','rhop_margin'],
'''Anuszczyk and colleagues stimulated the subumbrellar tissue of adult Cassiopea xamachana using implanted electrodes and a lightweight controller. **Entrainment** here means contractions adopting the timing of an externally imposed pulse train, rather than the alignment of a daily clock.||During field trials, 0.5-Hz stimulation accompanied contractions near 1 Hz in intact Cassiopea. Contractions also continued after the external train stopped. The apparatus marked delivered electrical pulses with an LED so video could compare stimulation times with contraction events.||The intact rhythm was therefore not determined simply by the external command frequency. Endogenous activity can interfere with an imposed motor rhythm. This experiment measures the combined output of the animal and controller; it does not record competing signals from each rhopalium or establish a complete pacemaker-resetting rule.''',
'Hertz means events per second. The intact animal can produce contractions between externally commanded events. Continued pulsing after the controller stops distinguishes an endogenous source from complete dependence on electrical stimulation, although it does not identify which particular marginal organ dominates.')

add('Rhopalia removal improves control of pulse timing', 'anuszczyk', ['external_frequency','external_traces'],
'''Anuszczyk and colleagues removed all rhopalia through small cuts at the bell margin, then tested external stimulation within two days to limit the opportunity for regeneration. This **ablation** physically removes a structure and asks whether its presence contributes to a measured function.||After removal, Cassiopea xamachana contracted at approximately 0.47 Hz during 0.5-Hz stimulation and stopped pulsing when stimulation ended. Intact animals maintained additional contractions. Externally evoked contractions demonstrated that bell tissue retained a functional path from stimulation to muscle movement after surgery.||The comparison strongly associates rhopalia with the endogenous activity that resists external timing control. Surgical injury is broader than a selective manipulation of one cell type. The result separates loss of spontaneous drive from total muscle paralysis without resolving the complete neural pathway activated by the electrodes.''',
'Ablation tests necessity at the level of the removed structure. Preserved externally evoked contractions are an important functional control: removing the organs does not eliminate all capacity for bell movement. The experiment still cannot separate every neural and mechanical consequence of the marginal cuts.')

add('Bell contractions have a finite following frequency', 'anuszczyk muffett', ['external_range','muscle_d'],
'''Anuszczyk and colleagues varied electrical-stimulation frequency in laboratory Cassiopea andromeda and the box jellyfish Alatina alata. These laboratory trials used a different Cassiopea species from the field trials, an important boundary when comparing performance across experiments.||Cassiopea andromeda did not follow stimulation above approximately 1.67 Hz, whereas Alatina followed rates up to 2.5 Hz. Removing rhopalia improved correspondence between imposed and observed frequencies within the tested range. Increasing input frequency therefore did not guarantee a proportional increase in completed contractions.||The upper following rate constrains the integrated neuromuscular system under these conditions. It could reflect excitation, muscle recovery or bell mechanics, which this assay did not isolate. The phalloidin-labeled Cassiopea musculature provides anatomical context rather than proof of the specific limiting process.''',
'Following frequency measures successful whole-bell responses to repeated commands. It is not automatically the maximum firing rate of a neuron. Different muscle arrangements and bell mechanics can contribute to species differences, so the comparison should not be reduced to one presumed channel property.')

add('Stimulus-to-contraction latency combines several processes', 'anuszczyk muffett', ['external_delay','muscle'],
'''Anuszczyk and colleagues measured the time from delivered stimulation to the onset of contraction in video recordings. This **response latency** includes events between electrode activation and a visually detectable change in bell shape, rather than directly measuring nerve conduction alone.||Cassiopea xamachana began contracting after approximately 0.16 seconds, compared with 0.41 seconds in Aurelia aurita and 0.17 seconds in Alatina alata. Comparable stimulation and video detection linked input timing to the beginning of mechanical output across the tested animals.||Differences constrain the complete response pathway, including neural recruitment, excitation of muscle and tissue deformation. They cannot be converted into axonal conduction velocities without measured propagation distances and isolated neural timing. Anatomical muscle images identify the effector tissue but do not apportion the measured delay among these processes.''',
'A conduction velocity requires distance divided by the travel time of a propagating signal. A latency measured from stimulation to movement includes additional stages, such as muscle activation and the development of force. These measurements answer related but distinct questions.')

add('A closed conducting path can sustain a traveling wave', 'mayer cary muffett', ['cary_regen','muscle'],
'''Mayer and Cary studied strips and ring-like preparations of Cassiopea subumbrellar tissue after removing marginal sense organs. The tissue could remain quiescent without rhopalia yet conduct an electrically initiated contraction along a connected path through the bell tissue.||In suitable closed circuits, an initiated wave continued circulating and produced repeated contractions without an intact marginal pacemaker. Cary used electrically activated circuit preparations to compare regeneration in active and inactive regions. The preparation separated wave initiation from continued travel along a circuit.||This **reentry** mechanism is repeated circulation of activity through a connected pathway. It shows that ongoing rhythmic contractions need not always imply a retained pacemaker organ. It does not establish reentry as the normal source of intact Cassiopea rhythms, nor does the historical preparation resolve individual synaptic connections.''',
'A pacemaker supplies recurring initiation; a reentrant path can repeat activity because a previously initiated wave returns to excitable tissue. These are different mechanisms for repetitive output. The regeneration curves illustrate the circuit-activation comparison, while muscle anatomy identifies tissue present in the conducting preparation.')

add('Ion-dilution experiments require matched chemical controls', 'mayer mayer16 muffett', ['mayer_ions','muscle'],
'''Mayer changed the seawater surrounding Cassiopea conducting preparations to test the dependence of wave propagation on ionic conditions. Dilution changes several variables together, including ion concentration, osmotic conditions and electrical conductivity of the extracellular fluid.||Experiments compared water dilution with dextrose and magnesium-salt treatments intended to separate these factors. The later study also controlled acidity: at 50% seawater concentration, propagation speed was about 54% of its value in normal seawater under the reported alkaline conditions.||Dependence on bath composition demonstrates that propagation is sensitive to the chemical environment. It does not identify the channels or synapses responsible. Mayer's initial adsorption-based explanation was explicitly revised in the 1916 paper after acidity and temperature effects were recognized; that earlier model should not be treated as an established modern mechanism.''',
'Osmotic conditions affect water movement across cell membranes, while extracellular conductivity describes how readily the bath carries electrical current. Both can change during dilution. Historical experiments establish useful dependencies, but their proposed molecular explanation must be distinguished from the measured result.')

add('Temperature strongly affects wave propagation', 'mayer16 muffett', ['mayer_temp','muscle'],
'''Mayer measured propagation in Cassiopea conducting tissue at different temperatures and compared the result with electrical conductivity of the surrounding seawater. These paired measurements tested whether changes in the extracellular medium alone could explain the tissue response.||Taking 29°C as 100%, propagation speed was approximately 71% at 23°C and 118% at 33°C. Bath conductivity changed less over the same temperature range. The nerve–muscle preparation therefore had a temperature dependence exceeding that of the external fluid.||The difference argues against explaining propagation entirely through bulk seawater conductivity. Temperature can influence membrane proteins, synaptic processes and muscle excitation, but the experiment did not isolate those components. The reported propagation measure should not be assigned to a specific modern ion channel without further physiological evidence.''',
'Normalizing a measurement expresses it relative to a reference condition; it does not supply an absolute speed unless the reference speed is known. The published graph retains its original axes. Greater temperature sensitivity of the tissue supports an additional biological process beyond a change in the conducting bath.')

add('Equal bath conductivity does not ensure equal propagation', 'mayer mayer16 abrams', ['mayer_ions','recording'],
'''Mayer compared diluted seawater preparations with solutions containing magnesium salts or dextrose. The manipulations tested whether reduced propagation could be attributed solely to dilution of the bath, rather than to a change in the physiological requirements of the conducting tissue.||A 0.415-M magnesium-chloride dilution series could maintain substantial extracellular conductivity while tissue propagation declined. Dextrose-based comparisons also altered the relation between osmotic support and ionic composition. The observed tissue response therefore could not be inferred from a single bulk property of the surrounding solution.||These controls establish a physiological dependence on ionic conditions without resolving the molecular conductance. Modern rhopalial pharmacology addresses another question: regulation of local event generation. Neither result permits the untested conclusion that one receptor accounts for all wave propagation across the bell.''',
'Molar concentration gives moles of solute per liter. Magnesium manipulations can alter several cellular processes, so they are not equivalent to selectively blocking a named ion channel. Local rhythm generation and propagation through distributed tissue need separate experiments and separate causal claims.')

add('Marginal organs affect regeneration beyond pulse count', 'cary abrams', ['cary_regen','rhop_three'],
'''Cary compared two halves of the same Cassiopea bell, retaining rhopalia on one half and removing them from the other. Removing a comparable amount of tissue between organs on the retained side supplied a wound control while the two halves shared the same seawater environment.||On the first day, tissue regeneration was about 1.53 times faster on the side retaining sense organs. A separate electrically activated circuit preparation produced more contractions yet less regeneration than the rhopalia-retaining region. Comparable activity therefore did not reproduce the full organ-associated effect.||The result associates marginal sense organs with recovery beyond their contribution to pulse number alone. It does not identify a secreted trophic factor, a transmitter or a specific regenerative neuron. The historical controls reduce simple explanations based on tissue loss and movement while leaving the cellular mechanism unresolved.''',
'A trophic effect supports growth or maintenance of tissue. The result reported by Cary is evidence for an organ-associated contribution, not proof of a named trophic substance. Using paired regions from the same animal reduces some differences among animals, while the tissue-removal control addresses the injury itself.')

add('Actin-rich tissue reorganizes near an ephyra wound', 'muffett', ['wound','muscle'],
'''Muffett and colleagues bisected 5-mm Cassiopea xamachana ephyrae and examined muscle-associated actin at 0, 24, 48 and 72 hours after injury. Fluorescent **phalloidin**, a molecule binding filamentous actin, revealed the contractile tissue surrounding the cut margin.||At 24 hours, phalloidin signal was stronger near the injury than in the surrounding tissue. The authors observed actin-rich structures along the wound region as fragments changed shape. The micrographs preserve 1-mm overview and 50-μm detail scale bars, distinguishing organ-scale remodeling from local tissue organization.||The staining supports early reorganization of actin-rich tissue during recovery. Increased signal is not a direct count of new muscle cells, and it does not demonstrate neural regeneration. Relating the new geometry to pacemaker coordination requires functional recordings in addition to the anatomical measurements.''',
'Filamentous actin is a polymerized form of actin found in muscle and other cell structures. A stronger fluorescent signal can reflect organization or amount of labeled material, so it should not automatically be read as cell proliferation. These images examine the effector tissue after injury.')

add('Halved ephyrae recover with fewer marginal organs', 'muffett', ['regen','muscle'],
'''Muffett and colleagues followed Cassiopea xamachana ephyrae bisected at several ages after release. The cut divided both bell and manubrium, while uncut animals underwent comparable photography and handling. Repeated images tracked wound closure, growth and the eventual geometry of each fragment.||The mean wound angle decreased from approximately 195° to 146.5° during the first 24 hours. Over about two weeks, fragments became smaller functional ephyrae that pulsed and fed, retaining fewer rhopalia and oral arms than the original animal. Recovery did not require restoration of the original organ count.||The outcome demonstrates substantial functional tolerance to loss and remodeling in this life stage. It does not establish unchanged pulse coordination or complete reconstruction of the original neural network. Distributed bell tissue and surviving marginal organs provide a framework for recovery, while the precise contributions of each remain experimentally separable.''',
'A manubrium is the central oral structure extending from the subumbrella. Wound closure, restoration of symmetry and restoration of neural function are distinct outcomes. Pulsing and feeding demonstrate meaningful recovery, while dedicated neural measurements would be needed to establish restored circuit organization.')

# Full-height columns preserve readable labels on portrait panels.
for number, width in {2:3.0, 14:3.6, 16:3.0, 24:3.6, 35:4.2,
                      36:3.0, 38:3.8, 39:3.6, 40:3.7, 41:3.7,
                      42:3.7, 43:3.7, 45:3.8}.items():
    slide=S[number-2]
    slide.update(figure_arrangement='side-by-side',primary_figure_width=width)
for number in (25,26):
    slide=S[number-2]
    slide['figure']=slide.pop('figures')[0]
    slide['layout']='figure-right'
assert len(S) == 44
takeaways = [
 '**Distributed organization:** Cassiopea has stage-specific neural and muscular architectures; detailed motor- and diffuse-net maps from Aurelia provide comparative evidence rather than a complete Cassiopea circuit.',
 '**Localized rhythmic drive:** Isolated rhopalia retain electrical activity, and rhopalia removal permits externally controlled contractions, separating endogenous initiation from preserved motor capacity.',
 '**Generation and propagation:** A pacemaker can initiate repeated activity, whereas a closed conducting path can sustain reentry; repeated bell movement alone does not distinguish these mechanisms.',
 '**Bounded molecular causation:** Nicotine, tubocurarine and chrnal-E RNAi connect receptor-related mechanisms to rhythm and behavioral state, without establishing an endogenous acetylcholine transmitter pathway.',
 '**State-dependent output:** Day–night pulse changes, reversible arousal delays and compensatory quiescence support regulated sleep-like behavior rather than simple muscle failure.',
 '**Recovery with altered anatomy:** Rhopalia influence regeneration, and halved ephyrae regain pulsing and feeding with fewer marginal organs; functional recovery does not imply restoration of every original connection.'
]
spec = {'lecture':46, 'theme':'harbor-blue-white', 'content_slides':44,
        'title_height':2.7, 'title_image':F['animal'],
        'title_refs':[R['abrams']['reference']], 'slides':S,
        'takeaways':{'items':[{'lead':t.split('**')[1], 'text':t.split('**')[2].strip()} for t in takeaways],
                     'cite':'Amplatz et al. (2024); Abrams et al. (2025); Nath et al. (2017); Mayer (1916); Muffett et al. (2025)',
                     'refs':['References:']+[s['reference'] for s in R.values()]}}
(B/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
(B/'plan.json').write_text(json.dumps({'lecture':46,'slides':[{'slide':i+2,'title':s['title'],'citations':s['cite']} for i,s in enumerate(S)]},ensure_ascii=False,indent=2)+'\n')
print('Wrote 44 primary-study content slides plus title and takeaways.')
