"""Lecture 29: primary experiments, original figure panels and teaching notes."""
import json,re
from pathlib import Path
H=Path(__file__).resolve().parent;ROOT=H.parents[1]
R=json.loads((H/'references.json').read_text());F=json.loads((H/'figure-sources.json').read_text())
C={k:re.sub(r', Fig\..*','',v['caption'])for k,v in F.items()}
C={p:next(C[k]for k,v in F.items()if v['paper']==p)for p in R}
S=[]
def fig(k):
 x=F[k];return dict(path=x['out'],caption=x['caption'],source_url=x['source_url'],kind='article',original_color=x['original_color'])
def add(title,body,images,papers,note,side=False):
 ps=body.strip().split('\n\n');assert len(ps)==3,title
 ks=[images]if isinstance(images,str)else images
 refs=list(dict.fromkeys(papers+[F[k]['paper']for k in ks]))
 transcript=[[re.sub(r'\*\*|_', '',p),[]]for p in ps];transcript[0][1]=[note]
 d=dict(layout='figure-right'if len(ks)==1 else'figures-right',title=title,body=ps,transcript=transcript,cite='; '.join(C[k]for k in papers),refs=[R[k]for k in refs],figure_width=5.65)
 if len(ks)==1:d['figure']=fig(ks[0])
 else:
  d['figures']=[fig(k)for k in ks];d['primary_figure_height']=2.35
  if side:d['figure_arrangement']='side-by-side';d['primary_figure_width']=3.85
 S.append(d)
add('A waggle run encodes a resource vector', '''Foragers of _Apis mellifera_ communicate a resource location through the **waggle dance**, repeated movements on the comb that contain a straight abdominal-wagging run and alternating return loops. A **vector** specifies a direction and a distance from an origin; here the origin is the hive.

Dong and colleagues filmed individually marked bees visiting a feeder 150 m away. The angle of the waggle run on a vertical comb encoded the food direction relative to the sun, while its duration encoded distance. Attending bees followed the dancer at close range.

The signal concerns a location outside the hive, rather than merely the dancer’s immediate position. Video measurements establish its spatial and temporal structure; successful communication additionally requires that followers obtain the signal and subsequently choose an appropriate flight. These are distinct experimental questions.''','dance',['learning23'],'The return loops bring the dancer back to the start of another waggle run. The loop itself is not a second advertised destination.')
add('Gravity supplies the reference inside the dark hive', '''A dancer on a vertical comb uses the upward direction as the reference for the sun. The waggle-run angle relative to vertical represents the resource direction relative to the sun outside. This transformation allows direction to be communicated where the sun itself is unavailable.

Dong and colleagues recorded dance angles on the crowded, uneven comb surface. They measured divergence among repeated waggle runs rather than assuming that every run conveyed an identical angle. Bees without experienced dancers produced larger directional divergence in their first dances.

Directional encoding therefore has both a reference system and a motor-precision component. A follower must translate the comb-relative angle into a flight direction using celestial information. The video experiment measures the dancer’s output; it does not identify a gravity receptor or the neurons that perform the coordinate transformation.''','dance',['learning23'],'Sunward is encoded upward on a vertical comb. The absolute flight bearing also depends on the sun’s current position, so a fixed resource can require changing dance angles during the day.')
add('A familiar compass bearing survives hive relocation', '''Von Frisch and Lindauer trained marked foragers to a feeding location and then moved the hive into an unfamiliar landscape. In their 1952 displacement experiment, the training feeder was 180 m away in a direction 30° north of west. The bees had learned this route during the afternoon.

The following morning, equally familiar scented food dishes were available in four directions in the new landscape. Arriving bees were captured immediately, preventing successful visitors from returning and recruiting nestmates. Searches favored the previously trained compass direction despite the changed terrestrial surroundings.

The result supports compensation for the sun’s movement between afternoon training and morning flight. Across related tests, cloudy conditions could prevent correct orientation when both direct sun and polarized skylight were unavailable. Landmarks and celestial cues can compete; the experiment does not imply that terrestrial information is normally ignored.''','classic',['frisch54'],'The four dishes controlled food identity and odor across directions. Capturing arrivals separated an individual’s remembered route from recruitment by another successful bee.')
add('Recruits initially fly the direction advertised in dances', '''Riley and colleagues tracked bees that had followed dances advertising an unscented feeder 200 m east of the hive. A **harmonic radar** detects a small transponder carried by the bee, allowing a trajectory to be measured outside the observation hive.

Recruits released at the hive generally flew an initially straight, eastward route. Their straight-flight sections averaged 206 m before searching began. Radar positions were acquired every 3 s, permitting a separation between directed travel and more tortuous search behavior.

The recruits had not previously visited the advertised feeder. The unscented feeding site and the experimental wind direction reduced the possibility of direct odor guidance from the destination. The trajectory supports acquisition of a flight vector from the dance, although radar cannot reveal which sensory components a follower used while attending the dancer.''','radar',['riley05'],'The transponder marks the bee’s location, not a neural signal. The initial straight segment and later search were behaviorally defined from the recorded flight.')
add('Displaced recruits retain a hive-centered flight vector', '''Riley and colleagues captured dance followers at the hive and released them 200–250 m southwest of it. This manipulation preserved the communicated instruction but changed the point from which the recruit began its flight. The real feeder was no longer 200 m east of the release point.

Displaced bees nevertheless began with an eastward straight flight, averaging 188 m before search. They did not immediately choose the new bearing from the release point toward the actual feeder. The flight instruction therefore retained its direction and approximate distance after displacement.

An **origin-dependent vector** is useful from its specified origin but leads to a different endpoint when executed elsewhere. This result separates a decoded movement instruction from immediate correction to a world location. It does not exclude later use of familiar landscape information, particularly in environments richer in recognizable landmarks.''','radar',['riley05'],'Transport changed the origin without changing the dance. The predicted endpoint for the displaced vector differs from the actual food site.')
add('The dance narrows search without pinpointing the feeder', '''The straight flights of hive-released recruits ended near the advertised feeder on average, but individual endpoints differed by tens of meters. Riley and colleagues then tracked looping searches, some lasting up to 20 min and extending as far as 200 m from the feeding site.

Only two tracked recruits found the unscented feeder. A mean endpoint close to the food location therefore did not imply reliable arrival by every bee. Directional variation increased near the end of the vector flight as directed travel gave way to search.

Dance information supplies an approximate search area. Local visual or odor cues can be needed to resolve the final destination, but the unscented-feeder experiment did not manipulate every possible terminal cue. Spatial scatter and terminal failure distinguish successful long-range information transfer from precise source recognition.''','direction',['riley05'],'A group average can be close to the feeder even when many individual bees miss it. The search phase is a genuine component of recruitment rather than an error-free continuation of the initial vector.')
add('Recruits compensate for drift during crosswind flight', '''Riley and colleagues measured flight tracks together with wind velocity to distinguish movement over the ground from movement through the air. A bee exposed to a crosswind must direct its body partly into the wind if it is to maintain the advertised ground track.

In one recorded flight, ground speed was 6.8 m/s while a 3.3 m/s wind acted from a different direction. The reconstructed air velocity was 5.2 m/s. The bee’s air heading differed from its ground-track direction by approximately 28°, counteracting wind drift.

The resulting displacement followed the eastward instruction rather than the uncorrected wind-displaced heading. This establishes active compensation during recruitment flight. The wind-and-radar measurements do not isolate the visual or other feedback signals that determine the correction, and a single trajectory is not a universal wind-response calibration.''','wind',['riley05'],'Ground velocity combines the bee’s movement through air with air movement over the ground. Distinguishing those quantities prevents heading from being confused with destination direction.')
add('A narrow tunnel magnifies retinal image motion', '''**Optic flow** is the movement of environmental images across the retina during self-motion. Nearby surfaces produce more angular image displacement than distant surfaces for the same translational travel. A narrow textured tunnel therefore increases optic flow without requiring a long physical flight.

Srinivasan and colleagues trained honeybees through a tunnel 6.4 m long, 11 cm wide and 20 cm high. Random black-and-white texture covered the walls and floor; a mesh ceiling allowed a view of the sky. The feeder was positioned 6 m into the tunnel.

Returning bees produced waggle dances after this short passage even when an equally short outdoor journey normally elicited round dances. The preparation separates physical distance from visual motion experienced en route. It supports a visual odometer, a mechanism estimating distance traveled, rather than an exclusively energy-based distance measure.''','tunnel',['optic00'],'The tunnel dimensions matter because proximity changes angular image speed. The feeder location and tunnel texture were controlled independently.')
add('Axial stripes remove the tunnel’s distance inflation', '''Srinivasan and colleagues kept the feeder at the same physical location while replacing random tunnel texture with stripes parallel to flight. **Axial stripes** change little along the flight axis, reducing the visual motion normally generated by forward travel.

A 35 m outdoor journey followed by 6 m through random texture produced waggle dances in 90% of recorded dances. With axial stripes at the same total distance of 41 m, 86.7% of dances were round dances. Without the tunnel, a feeder at 35 m elicited predominantly round dances.

Physical journey length cannot explain the difference between the two 41 m preparations. The texture control identifies optic flow as the relevant variable under these conditions. It does not establish that all visual patterns are equally effective or that energetic state never affects other aspects of dancing.''','tunnel',['optic00'],'Parallel stripes and random texture impose different visual motion while preserving the target location. The comparison addresses distance estimation rather than reward quality.')
add('Outdoor dances calibrate the duration–distance relation', '''Srinivasan and colleagues moved outdoor feeders between 60 and 350 m and measured the duration of each waggle phase on return to the hive. Over this range, mean waggle duration increased approximately linearly with feeder distance.

The reported calibration increased by 1.88 ms of waggle duration per meter of outdoor travel. It provided a reference for interpreting the unusually long dances produced after textured-tunnel flights. The calibration was measured independently of the tunnel manipulation.

A **calibration** relates a measured signal to a known quantity under specified conditions. It is not necessarily a universal conversion applicable to every landscape or colony. The outdoor measurements establish the relation for the tested routes and distances; they do not identify the neurons integrating optic flow or storing the resulting distance estimate.''','calibration',['optic00'],'Duration is the measured motor output. The experimental outdoor calibration gives it a distance interpretation without treating a tunnel flight as an ordinary outdoor flight.')
add('Six tunnel meters can signal a much longer journey', '''Srinivasan and colleagues used the outdoor calibration to interpret dances following textured-tunnel passages. A 41 m journey containing 6 m inside the tunnel produced a mean waggle duration of 528.8 ms, corresponding to approximately 230 m in the outdoor calibration.

A second arrangement placed the tunnel nearer the hive, producing only 12 m of total travel. Its mean duration was 441.2 ms, corresponding to approximately 184 m outdoors. Both preparations generated a disproportionately large distance signal despite their different outdoor approach lengths.

The close textured surfaces amplified the visually measured journey. The comparison rejects a simple account in which waggle duration reports physical meters independently of visual surroundings. These inferred outdoor distances are values from the authors’ calibration, not direct measurements of a bee’s subjective experience.''','calibration',['optic00'],'The two tunnel conditions were mapped onto the published outdoor relation. They establish a visual dependence of the signal, without requiring a verbal attribution of perceived meters to the bee.')
add('Followers search at the distance encoded by tunnel dances', '''Esch and colleagues trained dancers to fly 3 m outdoors and then through an 8 m textured tunnel toward the south. Although the actual feeder was only 11 m from the hive, returning bees produced waggle runs averaging 358 ms.

The local outdoor calibration associated this duration with approximately 72 m. Newly recruited bees searched predominantly at a control station 70 m south of the hive rather than at the tunnel feeder. Control stations offered neither food reward nor an added scent.

For the first 30 min, the tunnel was closed: dancers did not advertise the tunnel journey and recruits did not arrive at the stations. Opening it initiated dancing and subsequent recruitment. This links the visually inflated distance signal to followers’ search behavior, rather than merely to a change in the dancer’s movements.''','opticrecruit',['optic01'],'Bees arriving at control stations were captured so their own return dances could not create additional recruitment to the station. The search behavior tests decoding independently of the dancer’s physical flight length.')
add('Outdoor calibration differs between flight routes', '''Esch and colleagues measured outdoor dance durations separately for southern and northwestern routes. A given waggle duration corresponded to different physical distances on the two routes, even though both involved ordinary outdoor flight.

For example, 270 ms corresponded to about 52 m using the southern relation but about 157 m using the northwestern relation. The northwestern landscape generated less distance signal per physical meter than the southern landscape. A single route-independent conversion would therefore misread the dance.

The relevant quantity is accumulated visual motion shaped by the route. Terrain and viewing geometry can change the relation between optic flow and physical distance. The calibration experiment does not identify the exact contribution of every landmark, but it establishes that the environmental dependence matters when comparing advertised and searched distances.''','opticoutdoor',['optic01'],'The published graph distinguishes southern squares from northwestern triangles. Duration can carry a reliable route-specific instruction even when physical meters differ between routes.')
add('Northwestern recruits use their route’s visual calibration', '''Esch and colleagues repeated the tunnel recruitment test with a northwestern approach: 3 m outdoors followed by 6 m through the tunnel. The actual feeder was 9 m away, and returning dancers produced waggle runs averaging 270 ms.

Recruit searches peaked near 140 m along the northwestern route. The northwestern outdoor calibration predicted approximately 157 m, whereas applying the southern calibration would predict only about 52 m. Recruits therefore searched where a route-appropriate visual-distance interpretation placed the destination.

Stations were unrewarded, and closing the tunnel before each experiment prevented the relevant dances and recruitment. The result connects dance decoding with followers’ own visual navigation. It does not establish a permanently fixed distance dictionary: the conversion depends on the visual conditions encountered by the navigating bees.''','opticrecruit',['optic01'],'The tunnel-distance instruction can be shared because dancer and follower navigate comparable visual terrain. The physical feeder distance and the searched distance remain experimentally distinct.')
add('Natural water crossings alter the distance signal', '''Tautz and colleagues moved feeders along two routes, each 580 m long. One route crossed land, water and then an island; the other remained over land. Marked foragers were trained to follow the moving food source, including a feeder carried by boat.

For each position, returning dances were filmed and waggle-run duration measured. The experiment tested whether the tunnel-defined visual odometer also depended on natural terrain. Both routes increased physical distance without the artificial proximity of tunnel walls.

Water-crossing bees continued to signal increasing distance, but the rate of increase differed across route segments. Recruits were scarce while the feeder was over water and reappeared on the island. Recruitment success and distance encoding are related but distinct outcomes, and the habitat change can affect both.''','terrainmap',['terrain04'],'Maintaining trained bees at the boat feeder allowed distance signals to be measured even when spontaneous recruitment onto the water was uncommon.')
add('Waggle duration accumulates more slowly over water', '''On the land–water–island route, Tautz and colleagues measured a waggle-duration increase of 1.970 ms/m over the first land segment, 0.546 ms/m over water and 2.243 ms/m over the island. Equal increments of physical travel therefore contributed unequally to the dance signal.

Segment-specific relations captured the change more closely than a single constant slope across the whole route. An all-land comparison route lacked a corresponding water-associated flattening. The control separated a specific terrain transition from a general dependence on increasing feeder distance.

A visual odometer need not stop working over water; it can accumulate less effective image motion there. These behavioral measurements constrain the distance signal’s input dependence. They do not directly record retinal motion neurons or prove that low contrast alone accounts for the entire water effect.''','terrainwater',['terrain04'],'The units are milliseconds of additional waggle duration per physical meter. A flatter slope means less signal increment, not necessarily a lower flight speed.')
add('Image contrast constrains natural visual odometry', '''**Visual contrast** measures differences in image intensity that make spatial structure detectable. Tautz and colleagues photographed land and water scenes along the experimental routes and analyzed intensity variation in defined image windows.

Mean contrast was greater over land than over water. The low-contrast water segment coincided with slower accumulation of waggle duration, whereas the terrestrial segments supported larger increases. The original scene photographs retain the investigators’ measurement windows.

Contrast provides a plausible connection between natural image structure and effective optic flow. A correlation across route segments does not isolate contrast from flight height, viewing direction or surface texture. The controlled tunnel-texture experiments supply a separate intervention on visual motion, while the field measurements establish ecological dependence under ordinary foraging conditions.''',['terrainphotos','landphoto'],['terrain04','optic00'],'Low contrast can weaken motion signals even when the animal continues moving. The photographs document the actual terrain; they are not a reconstructed visual stimulus.')
add('Bees can learn the orientation of polarized light', '''**Polarized light** has a preferred orientation of its electric-field oscillation, called the **e-vector**. Sakura and colleagues tested whether restrained honeybees could discriminate two e-vector directions presented from above without having to complete a navigational journey.

One direction was paired with sucrose; the perpendicular direction was not rewarded. The **proboscis extension response**, extension of the feeding mouthparts, supplied a behavioral readout of association. During ultraviolet-light conditioning, responses increased to the rewarded direction while remaining low to the other.

The test establishes learned discrimination of polarization orientation independently of free-flight steering. Head-fixed bees could also learn, supporting detection without repeated active head scanning. It does not measure an internal compass bearing or establish how this sensory discrimination is converted into the direction advertised in a dance.''',['pollearn','DRA'],['pol12'],'Rewarded and unrewarded directions differed by 90°. The dorsal-rim anatomy is from Zeller and colleagues; it identifies the sensory entry region investigated with occlusion in Sakura’s behavioral preparation.',True)
add('Polarization learning depends on ultraviolet stimulation', '''Sakura and colleagues repeated polarization conditioning with ultraviolet light near 350 nm, blue light near 442 nm and green light near 546 nm. Each preparation used a rewarded e-vector and a perpendicular unrewarded e-vector.

Bees acquired the discrimination under ultraviolet stimulation but did not acquire it under the tested blue or green conditions. The wavelength comparison controlled the form of the associative task while changing the available spectral input. Ordinary responsiveness to sucrose was assessed separately.

The result is consistent with ultraviolet-sensitive polarization input rather than a wavelength-independent task solution. It does not mean that blue and green receptors are unimportant in other visual behaviors. Nor does this behavioral experiment identify an individual phototransduction ion channel or trace a complete polarization-processing circuit.''',['polwave','DRA'],['pol12'],'The three wavelength conditions isolate spectral dependence. The source anatomy places dorsal-rim inputs in the dorsal medulla, but wavelength-dependent learning itself was measured behaviorally.',True)
add('Occluding the dorsal rim removes e-vector learning', '''The **dorsal rim area** is a specialized region near the upper edge of the compound eye associated with skylight polarization detection. Sakura and colleagues painted either this region or the rest of the eye before ultraviolet polarization conditioning.

Bees with the dorsal rim covered did not learn the rewarded e-vector. Bees with the extradorsal-rim region covered retained discrimination, despite having much of the eye occluded. This complementary control links the behavioral effect to the specialized region rather than simply to reduced exposed eye area.

The experiment supports a necessary dorsal-rim contribution under these conditions. Zeller and colleagues traced input from this region into a specialized dorsal-medulla compartment. The occlusion and tracing results converge on a sensory pathway, but neither establishes every receptor subtype or the downstream synapses required for dance navigation.''',['polpaint','DRA'],['pol12','tmn15'],'The extradorsal-rim condition leaves the candidate polarization-sensitive region available. This is a stronger localization control than covering the whole eye.',True)
add('Polarized illumination can label a learned flight route', '''Kraft and colleagues trained bees in a four-tunnel maze with one entrance and three possible exits. Each tunnel was 125 cm long, 11 cm wide and 18 cm high. Polarizing filters above the tunnels specified illumination parallel or perpendicular to the flight axis.

The rewarded exit carried the same relative polarization orientation as the entrance. Incorrect exits offered no reward; during tests, choices were measured without reward. A diffuser prevented a direct view of the sun and obscured overhead landmarks.

The preparation asks whether a bee can associate a route with a particular relationship between body axis and e-vector. It does not require an absolute geographical compass solution. Moving the illumination pattern among exits then tests the contribution of polarization against a learned preference for turning or going straight.''','mazept',['route11'],'The original preparation drawing comes from the primary article. Relative polarization means orientation with respect to the tunnel axis, rather than a compass direction written on the maze.')
add('Route choices combine polarization with learned turns', '''In Kraft and colleagues’ straight-ahead training condition, bees chose the rewarded tunnel on 67% of tests with the original illumination arrangement. Moving the rewarded polarization to the left exit raised left choices from 15% to 28%, but straight-ahead choices remained at 51%.

In the right-turn training condition, bees chose the rewarded right exit on 74% of tests. When its polarization was moved to the straight-ahead exit, straight-ahead choices reached 56%. Three exits gave a random-choice level of approximately 33%.

The cue relocation changed behavior, but it did not erase the learned route preference uniformly across training conditions. Polarization and motor-route memory can both influence choice. The experiment supports learned use of relative e-vector information without claiming that this cue exclusively determines every route decision.''','mazechoices',['route11'],'The two training conditions are separate preparations. Their different transfer patterns argue against treating all choices as a pure readout of one sensory cue.')
add('Polarization orientation changes the direction danced', '''Evangelista and colleagues trained bees through a 12 m textured tunnel covered by ultraviolet-transmitting polarizers and a diffuser. The diffuser removed a direct view of the sun and overhead landmarks, leaving the artificial polarization pattern as the celestial cue.

With transverse polarization, waggle runs clustered along a vertical axis on the comb. With axial polarization, they clustered along a horizontal axis. The reported mean axes were approximately 91.7° and 1.3° relative to horizontal, respectively.

A single e-vector has a 180° ambiguity: the same axis can represent opposite travel directions. Bees advertised both alternatives rather than a unique direction. The experiment links polarized flight input to the communicated direction while distinguishing an axis of possible headings from a fully disambiguated sun-referenced bearing.''',['poltrans','polaxial'],['pol14'],'The polarizer orientation changed while tunnel direction remained fixed. The original article contains the preparation images and measured dance distributions; no direction plots have been reconstructed.')
add('A polarization switch changes the communicated journey', '''Evangelista and colleagues also changed the polarization axis halfway along the tunnel. The first 6 m and the second 6 m provided perpendicular e-vector orientations, although the physical tunnel itself remained straight.

After the two-segment journey, bees advertised diagonal directions consistent with interpreting a turn between the segments. Their mean waggle duration was shorter than after a tunnel with one uniform polarization axis. The authors related this reduced distance signal to an inferred two-leg displacement.

The intervention alters the sensory compass instruction without inserting an actual corner. It supports combination of directional input with a distance estimate when generating the dance. The inferred trajectory depends on ambiguity in the artificial sky cue, and the study did not directly record neural vector accumulation or identify a central-complex calculation.''','polswitch',['pol14'],'The source figure includes the authors’ stimulus arrangement and measured durations. The suggested two-leg geometry is an interpretation of the behavior, not a directly observed physical turn.')
add('Partial solar experience supports a coarse compass', '''**Solar azimuth** is the sun’s horizontal bearing; an **ephemeris** describes its changing position over the day. Dyer and Dickinson reared bees in an incubator and allowed them to fly outside only during the late afternoon.

On a cloudy test day, these bees flew for the first time during morning and early afternoon. Their dances indicated a morning solar estimate approximately 180° from the evening azimuth they had previously experienced. Around local noon, they switched toward the familiar evening direction.

The bees therefore supplied an approximate morning reference without having directly experienced that portion of the sun’s course. The step-like pattern supports a general expectation of daily solar movement refined by experience. It differs from exact memorization of every hourly sun position and leaves the implementing neuronal computation unresolved.''','solarpartial',['solar94'],'Cloud cover removed direct celestial information during the test. Direction was inferred from dances relative to a known food route, not from an electrode measurement of a sun representation.')
add('Full-day experience refines the learned solar course', '''Dyer and Dickinson compared experience-restricted bees with bees that had previously flown throughout the day. Both groups were tested under a cloudy sky, so current direct sight of the sun could not explain the difference in their dance orientations.

Fully experienced bees’ solar estimates followed the continuously changing local sun course more closely. Bees with afternoon-only experience instead used the coarse morning–afternoon pattern. The comparison separates a broad expectation about solar movement from its more precise local calibration.

The sun’s horizontal bearing changes at a variable rate with time, latitude and season; a universal constant angular-rate correction is insufficient. Experience improves the temporal reference used for navigation. The design supports learned calibration but does not isolate whether particular visual scenes, flight directions or training times supplied each component of that learning.''','solarcontrol',['solar94'],'The actual daily course was known independently from astronomical position. Shared cloud cover controls the availability of immediate celestial cues across the two experience conditions.')
add('Clock disruption shifts sun-compass flight bearings', '''A **circadian clock** is an internal timing system with an approximately daily cycle. Cheeseman and colleagues used 2% isoflurane anesthesia to perturb this timing system and tested subsequent sun-compass homing.

In the Southern Hemisphere, bees trained to a feeder 100 m from the hive were transported 6 km into unfamiliar terrain. Six-hour anesthesia produced an approximately 87° anticlockwise shift in vanishing bearing relative to a 30-min anesthetic control. A vanishing bearing is the direction at which a departing bee leaves the observer’s view.

A time error predicts a directional error because solar bearing depends on time of day. The shifted orientation supports this relationship, but extended anesthesia can also affect general performance. The short-anesthetic control and independent clock measurements are needed to distinguish a timing disturbance from nonspecific drug effects.''','clockbearing',['clock12'],'The comparison was between long and short anesthesia, rather than between treatment and an unhandled animal alone. Vanishing bearing samples initial orientation and does not establish eventual homing success.')
add('The opposite hemisphere reverses the directional error', '''Cheeseman and colleagues repeated the navigation test in the Northern Hemisphere using harmonic radar. Bees trained to a feeder 300 m from the hive were displaced 500 m before release, allowing the initial homeward vector flight to be separated from later correction.

Six-hour anesthesia shifted the initial vector approximately 58° clockwise relative to the 30-min control. Unanesthetized catch-and-release bees provided another handling comparison. The direction of the error was opposite to the Southern Hemisphere result, as expected from the different solar course.

The hemisphere comparison links the behavioral error to sun-compass timing rather than to a fixed tendency to turn left or right after treatment. Individual variation and possible secondary cues remain. The measured trajectory establishes an altered initial compass instruction, without locating its neural implementation.''','clockradar',['clock12'],'A compass error tied to solar movement can reverse sign across hemispheres. A fixed lateral motor bias would not predict that reversal.')
add('Anesthesia changes molecular-clock phase', '''Cheeseman and colleagues measured hive activity under constant dim light, removing ordinary day–night transitions as the immediate cause of a shifted rhythm. Daytime six-hour anesthesia delayed daily activity and altered rhythmic gene expression in sampled bee brains.

The reported phase delays were 4.9 h for mammalian-type **cryptochrome** messenger RNA and 4.3 h for **period** messenger RNA. Messenger RNA is the transcript used to produce a gene’s protein. The sampled hive’s activity phase shifted by 5.3 h, while **clock** expression remained broadly constitutive.

Six-hour anesthesia during subjective night did not produce the same delay. This time-dependent effect supports disturbance of the circadian oscillator rather than a literal six-hour pause in all behavior. Whole-brain expression cannot specify the cells delivering time information to a compass pathway or identify the relevant anesthetic receptor.''','clockgenes',['clock12'],'Cryptochrome and period expression were sampled across the daily cycle rather than at a single post-treatment time. A phase shift changes when the rhythm peaks, not simply whether a gene is expressed.')
add('Dorsal-rim afferents reach a specialized medulla region', '''Zeller and colleagues injected fluorescent tracers into the dorsal rim of the honeybee eye and labeled surrounding neuropil. **Neuropil** is tissue containing interwoven neuronal branches and synapses. The medulla is a visual-processing region within the optic lobe.

Dorsal-rim input reached a distinct dorsal-medulla compartment called the **MEDRA**. Complementary injections into other pathway regions and synapsin labeling distinguished this compartment from neighboring medulla. The published micrographs preserve anatomical orientation and micrometer scale bars.

This tracing identifies an entry pathway for polarization-associated visual input. It does not by itself measure e-vector tuning or prove that every labeled connection is required for dance orientation. Anatomical localization and Sakura’s regional-occlusion experiment address different links between sensory specialization and behavior.''','DRA',['tmn15','pol12'],'Afferents are neurons carrying input into a processing region. Tracer transport identifies projection geometry, while synapsin staining supplies a reference for the surrounding synaptic tissue.')
add('Transmedulla neurons relay dorsal visual input medially', '''Zeller and colleagues traced **transmedulla neurons**, cells whose branches cross the medulla from the dorsal-rim-associated input compartment toward more medial brain regions. Dye injections from different locations provided complementary views of their branching pattern.

These neurons arborized in the MEDRA and extended through a defined medulla layer. Their medial projections reached the lower-unit complex of the **anterior optic tubercle**, a visual-processing center outside the optic lobe. Fine terminal morphology distinguished plausible input and output portions of the pathway.

The ordered projection provides an anatomical route from specialized eye input toward central compass circuitry. Morphology supports this direction of information flow but cannot replace physiological measurements of transmission. The study did not identify a transmitter for every transmedulla cell or directly establish its role in correcting a dance angle for time of day.''',['TMN','AOTU'],['tmn15'],'The anterior optic tubercle is divided into compartments. The lower-unit complex is associated with this traced pathway, so the term does not refer to every tubercle neuron indiscriminately.')
add('PDF-positive fibers are candidate timing inputs', '''**Pigment-dispersing factor**, or **PDF**, is a neuropeptide associated with circadian signaling in insects. Zeller and colleagues combined PDF immunostaining with tracer labeling of transmedulla neurons to ask where potential timing input could meet the honeybee sky-compass pathway.

PDF-positive fibers occupied the same medulla layer as parts of the traced neurons. At higher magnification, labeled puncta lay in close proximity along their passage through the medulla. The two labels did not colocalize, and PDF labeling was not found within the MEDRA itself.

The result identifies neighboring neuronal populations and a candidate site for modulation. Close proximity does not establish peptide release, a postsynaptic PDF receptor or a functional synapse. Circadian compass correction is therefore a proposed role of this contact region rather than a demonstrated action of PDF on these neurons.''','PDF',['tmn15'],'Immunoreactivity means that an antibody recognizes a target in the preparation. It supports the presence of the labeled substance, but a nearby labeled bouton is not equivalent to a confirmed connection.')
add('Serotonin and GABA lie near compass-pathway branches', '''Zeller and colleagues combined transmedulla tracer labeling with antibodies against **serotonin**, a monoamine signaling molecule, and **GABA**, gamma-aminobutyric acid. GABA commonly contributes inhibitory signaling, but its action at a particular connection requires receptor and physiological evidence.

Serotonin-positive puncta overlapped the dorsal portion of the relevant medulla layer but not the MEDRA. GABA-positive fibers lay near transmedulla branches throughout their length, including the MEDRA. In both preparations, tracer and transmitter labels marked different populations rather than the same cells.

These spatial relationships support candidate modulatory and local processing interactions. They do not establish whether serotonin increases or decreases compass-pathway excitability or whether a particular GABA receptor or chloride conductance mediates an effect. The necessary receptor identity, synaptic direction and time-dependent physiology remain unmeasured in this anatomical study.''',['serotonin','medullaGABA'],['tmn15'],'Different distributions imply different possible access to the traced pathway. Assigning an excitatory or inhibitory effect solely from proximity would go beyond the experiment.')
add('Tubercle outputs reach bulbs and the central body', '''Held and colleagues traced the honeybee sky-compass network using dye injections, neuropil labeling and single-cell preparations. **TuLAL1 neurons** project from the anterior optic tubercle toward paired synaptic regions called the lateral and medial **bulbs**.

A second class, **TL neurons**, connects these bulbs with the lower division of the **central body**, part of the central complex. The labeled branches establish two parallel anatomical routes from tubercle outputs toward central-brain circuitry associated with directional processing.

The bulbs provide a defined interface rather than an undifferentiated relay. The study identifies its neurons and terminal organization, but it does not directly record a honeybee heading code or demonstrate the conversion of that code into a waggle-run angle. Functional interpretations must remain separate from the measured projection anatomy.''','bulbpath',['micro16'],'The pathway nomenclature names the projection classes used by the authors. The original article’s anatomical drawing is included unchanged; no circuit has been newly drawn for this deck.')
add('Bulb microglomeruli organize convergent synaptic tissue', '''A **microglomerulus** is a compact synaptic complex in which a large presynaptic terminal contacts several smaller postsynaptic processes. Held and colleagues stained honeybee bulb tissue for **synapsin**, associated with presynaptic machinery, and filamentous actin, prominent in postsynaptic regions.

Confocal images revealed separated microglomerular complexes in the lateral and medial bulbs. Traced TuLAL1 terminals occupied the presynaptic cores, while postsynaptic processes from TL neurons contacted them. Complementary labeling linked cell projections to the local terminal organization.

The stains identify an anatomical arrangement for distributing tubercle signals among downstream neurons. Confocal proximity alone cannot resolve every membrane contact, so the authors also used electron microscopy. These structures are a measured substrate for parallel processing, without establishing what exact directional information each complex carries during flight or dancing.''','bulbconfocal',['micro16'],'Synapsin and actin are markers, not themselves a transmitter identity. Their different distributions help separate terminal compartments before synaptic membrane structure is examined.')
add('Electron microscopy resolves bulb synaptic contacts', '''Held and colleagues used transmission electron microscopy to examine honeybee bulb complexes at membrane resolution. Large TuLAL1 terminals contained vesicles and multiple presynaptic specializations facing smaller profiles. **Vesicles** are membrane-bound structures that store releasable signaling molecules.

The authors identified **dyadic** and **tetradic** contacts, where one presynaptic specialization faced two or four postsynaptic profiles. GABA immunostaining associated downstream TL neurons with an inhibitory transmitter phenotype. These observations constrain connectivity more directly than a light-microscopy overlap.

Synaptic morphology establishes physical contacts, and transmitter staining supports a candidate sign of downstream signaling. Neither observation identifies all postsynaptic receptors or the activity-dependent effect on a navigation computation. A GABA-associated projection is not sufficient evidence for a specific chloride-channel mechanism at every terminal in the network.''',['bulbTEM','bulbGABA'],['micro16'],'Dyadic and tetradic count the postsynaptic profiles at a single specialization. They do not imply that the entire presynaptic neuron has only two or four targets.',True)
add('Electric fields can mechanically deflect bee antennae', '''Greggers and colleagues recorded electric fields around dancing bees and measured antennal movements during controlled electrical stimulation. Charged bodies can exert forces on nearby charged structures; detecting such a force does not require a dedicated electric-field receptor.

An isolated wing oscillating at 40 Hz, 2 mm from the head, evoked larger flagellar movements when charge was preserved rather than discharged. Laser Doppler measurements quantified these movements. **Johnston’s organ**, a mechanosensory organ in the antennal pedicel, responded to field-induced movement. The flagellum is the distal antennal segment, and the pedicel is its supporting joint region.

The resulting sequence is an electric force, antennal displacement and activation of movement-sensitive sensory neurons. This supports a mechanical route for field detection. It does not establish that electric fields are necessary for natural dance decoding or identify the mechanotransduction channel converting movement into receptor current.''',['fieldmechanism','JOpath'],['fields13'],'A moving flagellum can stimulate the same mechanical sensory apparatus through different physical causes. The published anatomical panel locates the organ and the afferent route into the brain.')
add('Antennal interventions reduce learned field responses', '''Greggers and colleagues paired an electric-field stimulus with sucrose and tested the conditioned proboscis extension response. Uncharged material or an inactive stimulus source served as the unrewarded comparison. Bees learned both constant fields and modulated stimulation at 60 Hz.

After learning, removing antennae eliminated the learned field response. Wax treatments that restricted antennal joints strongly reduced it; coating surfaces while retaining movement produced a less marked reduction. Learned responses to electric cues were also retained after 24 h.

The intervention pattern supports a contribution from antennal mechanoreception, including receptors associated with both joints. It does not isolate Johnston’s organ as the sole sensor or exclude every contribution from antennal surface hairs. The conditioning demonstrates a usable cue under controlled conditions, rather than its exclusive or necessary role in a crowded hive.''',['fieldlearn','JOpath'],['fields13'],'Treating bees after conditioning separates sensory access at test from initial acquisition. Surface coating and joint restriction are different interventions and should not be treated as identical controls.',True)
add('DL-Int-1 is GABA-positive and inhibited by pulse trains', '''Ai and colleagues recorded intracellularly from identified honeybee interneurons while a mechanical stimulator vibrated the antennal flagellum. **DL-Int-1** branches in the dorsal lobe and related mechanosensory tissue. Dye filling and anti-GABA staining associated this cell type with a GABAergic phenotype.

The stimulus carrier was 265 Hz, within the wing-vibration range relevant to waggle dancing. Pulse trains with durations up to 16 ms and intervals up to 33 ms suppressed DL-Int-1 firing below its spontaneous level. Longer 100 ms intervals allowed intermittent spikes during the train.

This response distinguishes closely spaced vibration pulses from more widely spaced events. Antibody controls supported label specificity, but GABA staining does not prove a particular inhibitory connection to another named neuron. The cellular recording establishes temporal filtering without identifying the receptor or ion channel that generates the observed inhibitory potentials.''',['DL1trace','DL1anatomy'],['vibration17'],'Intracellular recording measures voltage changes and spikes in the same identified neuron. Suppression of this GABA-positive cell is different from evidence that its output inhibits a specific downstream cell.',True)
add('DL-Int-2 remains excited during dance-like vibration', '''Ai and colleagues found a different response in **DL-Int-2**, another identified interneuron in the primary mechanosensory processing region. Its soma did not coincide with the anti-GABA labeling observed for DL-Int-1; this negative label does not by itself identify its transmitter.

At a 265 Hz carrier, trains with 16 ms pulses and 33 ms intervals evoked an initial excitation followed by maintained excitation. In contrast, DL-Int-1 was suppressed during comparable short-interval stimulation. **Tonic** activity is sustained activity during a stimulus, whereas **phasic** activity is concentrated near a change such as onset.

The contrasting responses could allow pulse-train duration to influence downstream signaling. A proposed inhibitory relationship between the two cell types was supported by modeling and morphology, not by direct synaptic measurement. The recorded excitation must therefore be distinguished from a proven circuit for decoding advertised distance.''',['DL2trace','DL2anatomy'],['vibration17'],'The stimulus envelope and the carrier are different quantities. A 265 Hz vibration inside repeated pulses is not equivalent to a 265 Hz rate of whole waggle runs.',True)
add('Mechanosensory responses change as workers mature', '''Kumaraswamy and colleagues compared DL-Int-1 in newly emerged workers aged 1–3 days with foragers older than 10 days. The preparation combined intracellular recording with dye-filled morphology, allowing cell identity to be retained across the age comparison.

Gross arborization extent was similar between groups, but branch density differed in selected regions. Foragers’ responses showed a stronger contrast between spontaneous activity and vibration-evoked inhibition, giving the stimulus a more distinct temporal signature. The original reconstructions and response distributions document different levels of analysis.

Maturation can change signal processing without replacing a neuron’s overall projection pattern. Age and experience were not independently manipulated, however, so the differences cannot be assigned exclusively to dance learning. The comparison establishes developmental association rather than the cellular cause of an acquired navigational skill.''',['maturetrace','matureneuron'],['mature19'],'Young bees had been maintained in cages, while foragers had natural behavioral experience. That group difference limits any claim that age alone or dance experience alone caused the response changes.',True)
add('Experienced dancers improve novices’ directional precision', '''Dong and colleagues created colonies of newly emerged workers with no experienced dancers and compared them with mixed-age colonies. Individually marked bees first danced for a feeder 150 m away; the same bees were tested again 20 days later.

Bees that could not follow experienced dancers before their first dance produced larger waggle-angle divergence and more disordered movements. Their directional precision improved by the later test. First dances in mixed-age colonies were already more precise, separating early social exposure from the act of merely performing a dance.

The result supports social contributions to dance development alongside an inherited behavioral pattern. Later improvement could reflect age, flight practice, following experience or their combination. Colony composition changes several experiences together, so the study does not isolate a single teaching interaction or a synaptic learning rule.''','socialdirection',['learning23'],'Directional divergence measures variation among waggle runs, not necessarily a systematic bias in the average advertised compass bearing. Those two kinds of error have different consequences for followers.')
add('Early social experience leaves a lasting distance bias', '''In Dong and colleagues’ 150 m feeder preparation, naive first dancers produced longer waggle runs and more waggles per run than first dancers from mixed-age colonies. The altered timing advertised a greater distance despite the common food location.

Twenty days later, the previously naive bees still produced the elevated distance signal. Their return-flight times had improved, and their directional precision had recovered, but the distance difference remained. The persistence separates distance calibration from changes that become more normal with later foraging experience.

Social experience therefore influences different components of the dance differently. Persistence through the measured adult interval supports a lasting calibration effect; it is not a longitudinal measurement of every future dance throughout a bee’s life. The experiment does not identify the sensory or neural mechanism storing that early calibration.''','socialdistance',['learning23'],'The feeder remained at the same distance for the group comparison. An improved return flight and a persistently long dance signal cannot be collapsed into one general measure of experience.')
add('Landscape knowledge can modify the recruit’s later search', '''Wang and colleagues tracked dance followers released either at the hive or at displaced sites within an explored landscape. The recruits had never visited the advertised food source. Harmonic radar sampled flight positions every 3 s.

Both groups first flew approximately the communicated vector. During later search, displaced recruits directed more behavior toward the real feeder location than toward the virtual endpoint obtained by executing that vector from the wrong origin. Search could therefore incorporate landscape knowledge acquired before the recruitment event.

The authors interpreted this behavior as inference of source location using map-like spatial knowledge. It does not directly record a neural map, and familiar visual guidance must be distinguished from a purely metric representation. The contrast with Riley’s sparse-terrain experiment emphasizes the separate contributions of initial vector flight and subsequent search.''',['mapsearch','maproute'],['decode23','riley05'],'The virtual endpoint is a predicted destination from an origin-dependent instruction, not a second feeder presented to the bee. The real and virtual alternatives distinguish later source-directed search from continuing the displaced vector.',True)
assert len(S)==44,len(S)
tk=[
 ('Dance vectors','Waggle-run angle specifies direction relative to the sun; duration specifies a visually calibrated distance from the hive. Vector flight and terminal source search are distinct.'),
 ('Visual odometry','Optic flow changes dance duration and recruit search distance. Tunnel texture and natural terrain prevent a universal conversion from duration to physical meters.'),
 ('Time compensation','Bees refine the local solar course through experience. Circadian phase disruption causes sun-compass errors whose direction depends on hemisphere.'),
 ('Compass pathways','Ultraviolet-sensitive dorsal-rim input reaches the medulla, optic tubercle, bulbs and central body. Tracing establishes anatomy; candidate timing contacts require functional tests.'),
 ('Dance-signal processing','Antennal movement activates mechanosensory pathways. Identified interneurons filter vibration pulse trains, but their proposed inhibitory connections and distance-decoding role are not fully established.'),
 ('Experience and search','Early social experience affects dance precision and lasting distance calibration. Familiar landscape knowledge can influence later search without replacing the initial dance vector.')]
refs=list(R.values());spec=dict(lecture=29,theme='oyster-carmine',content_slides=44,title_image=fig('dance'),title_refs=[R['learning23'],R['riley05']],slides=S,takeaways=dict(cite='Riley et al. (2005); Dong et al. (2023); Srinivasan et al. (2000); Zeller et al. (2015)',refs=refs,items=[dict(lead=l,text=t)for l,t in tk]))
(H/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
for i,s in enumerate(S,2):
 w=len(' '.join(s['body']).split());print(i,w,len(s['title']),s['title'])
