"""Teaching-first Lecture 62, based on the archived primary sources."""
from pathlib import Path
import json,re
D=Path(__file__).resolve().parent;R=D.parents[1];refs=json.loads((D/'research/refs.json').read_text());slides=[]
figdef={
'carnivore':('c','1(a–b)','Natural home range, infant mortality and pacing across carnivores.'),
'window1':('w','1','The penguin encounter habitat and viewing areas.'),'window2':('w','2(a–b)','Glass viewing windows and the visitor pathway.'),'window3':('w','3','The opaque barrier used in the window-covering experiment.'),'window6':('w','6(a–b)','Penguin visibility across habitat areas with the window uncovered and covered.'),
'barrier':('p','2','The physical barrier that increased visitor viewing distance.'),'sign':('p','3','The signs used to regulate visitor behavior.'),'penguins':('p','4(a–d)','Penguins and the habitat areas sampled by the cameras.'),
'control1':('b','1(A–B)','Dorsal raphe tracer deposit and labeled prefrontal neurons.'),'control2':('b','2(A–C)','Prefrontal activation following controllable or uncontrollable stress.'),'control3':('b','3(A–C)','Prefrontal activation after prior experience with stressor control.'),
'king1':('k','1(a–b)','The previous and redesigned king-penguin habitats.'),'king2':('k','2','A king penguin wearing a flipper-mounted time–depth recorder.'),'king3':('k','3','Hourly swimming activity in the two habitats.'),'king4':('k','4','Time spent in different water-depth categories.'),'king5':('k','5','Behavioral time budgets in the two habitats.'),'king6':('k','6','Individual differences in swimming time.'),'king7':('k','7','Rates of social and maintenance behaviors.'),'king8':('k','8','Individual proximity to other penguins.'),'king9':('k','9','Individual proximity to other penguin species.'),
'social2':('s','2','Affiliative, agonistic and displacement interactions in two elephant groups.'),'social3':('s','3','Types of affiliative contact in the two groups.'),'social4':('s','4','Types of agonistic interaction in the two groups.'),'social5':('s','5(a–b)','Directed affiliative relationships among individual elephants.'),'social6':('s','6(a–b)','Directed agonistic relationships among individual elephants.'),'social7':('s','7(a–b)','Non-contact displacement among individual elephants.'),
'habit2':('h','2','The expanded outdoor elephant habitat.'),'habit3':('h','3','Daily walking distances before and after the habitat transition.'),'habit4':('h','4(c–d)','An elephant’s GPS locations in warm and cool seasons.'),'habit5':('h','5(a–d)','Individual glucocorticoid metabolite concentrations across habitat phases.'),'habit6':('h','6(a–f)','Individual and combined elephant activity budgets.'),'habit7':('h','7','Proximity to herdmates in the previous and new habitats.'),'habit8':('h','8(a–e)','Individual social interactions with particular herdmates.'),'habit9':('h','9','The functional composition of elephant social behavior.'),'habit10':('h','10','Interactions with food resources, enrichment objects and habitat features.')}
def fig(k):
 p,n,t=figdef[k];v=refs[p];return {'path':'figures/'+k+'.png','kind':'article','caption':f"{v['author']} et al. ({v['year']}), Fig. {n}. {t}" if p!='c' else f"Clubb & Mason (2003), Fig. {n}. {t}",'source_url':'https://doi.org/'+v['doi']}
def add(title,keys,source,text,note=None):
 body=text.split(' || ');assert len(body)==3
 rr=list(dict.fromkeys(list(source)+[figdef[k][0] for k in keys]));x={'title':title,'body':body,'transcript':[re.sub(r'\*\*|(?<!\w)_(?=\w)|(?<=\w)_(?!\w)','',p) for p in body], 'cite':'; '.join(('Clubb & Mason' if k=='c' else refs[k]['author']+' et al.')+f" ({refs[k]['year']})" for k in rr),'refs':[refs[k]['ref'] for k in rr]}
 if note:x['transcript'].append(note)
 if len(keys)==1:x.update(layout='figure-right',figure=fig(keys[0]))
 else:x.update(layout='figures-right',figures=[fig(k) for k in keys],primary_figure_height=2.45)
 slides.append(x)
add('Natural ranging predicts vulnerability in captivity',['carnivore'],'c',
'**Sensory ecology** concerns the information an animal encounters while carrying out its natural activities. Clubb and Mason compared carnivores whose wild lifestyles differ in home-range size and daily travel, then related those differences to behavior and infant survival in captivity. || A **home range** is the area an individual ordinarily uses. Species with larger natural ranges tended to have more stereotypic pacing and greater captive infant mortality. The comparison included body size and evolutionary relatedness rather than treating every species as an independent equivalent. || These relationships connect captive outcomes to species-specific behavioral needs. Providing food and preventing injury can leave ranging motivations unsatisfied, so welfare assessment also requires evidence about the activities an animal is organized to perform.')
add('Pacing is a specific repetitive behavioral phenotype',['carnivore'],'c',
'**Stereotypy** is repetitive, relatively invariant behavior without an obvious immediate goal. In the carnivore comparison, pacing was selected because it was the dominant reported stereotypy and could be compared more consistently than a mixture of unrelated repetitive movements. || Pacing accounted for 97% of reported carnivore stereotypies in the source dataset. Repeated walking along a fixed route differs from flexible exploration because its sequence remains constrained instead of changing with available resources and information. || The species comparison linked this repetitive phenotype to larger natural home ranges. An enclosure assessment therefore distinguishes the form of locomotion from its amount: extensive pacing and extensive purposeful travel represent different behavioral outcomes.')
add('Captive infant survival tracks natural home range',['carnivore'],'c',
'Clubb and Mason examined **infant mortality**, the proportion of young dying early in life, as an outcome separate from pacing. Naturally wide-ranging carnivore species had higher infant mortality in captivity, even when body-size differences were included in the comparison. || The relationship with natural ranging was specific to the captive outcomes examined. Wild infant mortality did not covary with captive infant mortality, and natural range size did not predict infant mortality in the wild in the available comparisons. || This contrast links reproductive outcomes to conditions of management rather than simply labeling a species inherently unsuccessful. Behavioral opportunities and maternal conditions become part of the biological explanation for differences in captive survival.')
add('More normal activity does not explain increased pacing',['carnivore'],'c',
'Wide-ranging carnivores did not simply perform more normal activity in captivity. The association between natural range size and stereotypic pacing persisted when the analysis considered total stereotypy, husbandry conditions and the amount of ordinary captive activity. || **Behavioral motivation** refers to processes that organize an animal’s pursuit of particular activities or outcomes. Clubb and Mason proposed that restrictions on ranging contribute to the captive problems of species whose natural lives involve extensive movement. This is a hypothesis connecting ecological specialization to captive behavior. || The distinction guides observation: flexible locomotion, exploration and repetitive route tracing should be coded separately. An increase in movement can accompany either improved opportunities or increased repetitive behavior, depending on what the animal actually does.')
add('Species-specific needs change enclosure evaluation',['carnivore'],'c',
'A habitat’s area is only one component of its biological value. Clubb and Mason found that species’ natural ranging patterns predicted captive outcomes while variation in feeding regimes and enclosure characteristics did not explain away the cross-species relationships. || **Comparative analysis** examines differences among species while accounting for shared ancestry and other relevant traits. Here, the same managed conditions can constrain species differently because their behavioral repertoires evolved around different patterns of travel and resource use. || The authors recommended substantial improvement or reconsideration of keeping naturally wide-ranging carnivores. That recommendation is a welfare judgment informed by the measured relationships; the empirical finding is the association between natural ranging and captive pacing or infant mortality.')
add('Visitor distance changes penguin defensive behavior',['barrier'],'p',
'Little penguins responded differently when visitors were absent, held farther away, or allowed normal close viewing. Chiew and colleagues used a physical barrier to add 2 m of separation between visitors and the viewing edge, changing the conditions of contact. || **Vigilance** is sustained monitoring of potential threats; **huddling** is close grouping with other penguins. Across increasing visitor proximity, vigilance rose from 3% to 22% and huddling from 25% to 69% under unregulated visitor behavior. || Penguins also spent less time close to the visitor edges and less time surface swimming. A change in visitor access therefore reorganized several components of behavior together, including spatial avoidance, monitoring and participation in aquatic activity.')
add('Close viewing displaces penguins from the pool edges',['penguins'],'p',
'**Avoidance** is movement or spatial distribution that reduces contact with a potentially threatening stimulus. In the little-penguin experiment, the proportion of birds within 1 m of the two visitor sides fell sharply as visitor viewing became closer. || Surface swimming fell from 39% with the exhibit closed to 9% with normal close viewing and unregulated visitor behavior. The same animals could still use the pool, but their distribution and activity changed with the visitors’ access conditions. || The physical barrier also reduced looming over the enclosure, contact with water and sudden visitor movements. Distance regulation consequently changed a bundle of sensory events rather than only the geometric distance between a person and a penguin.')
add('Physical barriers regulate contact more effectively',['barrier','sign'],'p',
'Chiew and colleagues compared two management approaches: increasing viewing distance with a barrier and attempting to regulate behavior with signs and uniformed personnel. Both interventions targeted visitor contact, but they changed the exposure conditions differently. || The 2 m barrier reduced several visitor actions, including leaning over the enclosure and touching its water. Signs and personnel produced less consistent changes in visitor behavior. Penguins huddled less when behavior was regulated, while several other defensive measures remained unchanged. || A barrier operates by physically limiting opportunities for close contact. Signage operates through human compliance. These distinct mechanisms help explain why two interventions aimed at the same welfare problem can have different behavioral consequences.')
add('Behavior can change without a hormone shift',['barrier','penguins'],'p',
'**Fecal glucocorticoid metabolites** are breakdown products of glucocorticoid hormones measured after their passage through digestion and excretion. They provide a time-integrated endocrine measure, whereas video observations record behavior during particular exposure conditions. || Visitor proximity changed little-penguin vigilance, huddling, swimming and spatial avoidance, but the treatments did not produce a detected change in fecal glucocorticoid metabolites. The behavioral response was therefore the sensitive measured outcome in this experiment. || This result changes welfare interpretation: an unchanged fecal hormone measure does not cancel the observed avoidance. Behavioral and endocrine measures sample different biological processes and time windows, so assessment retains the animal’s changed use of its habitat.')
add('Covering a window changes the sensory encounter',['window2','window3'],'w',
'At Taronga Zoo, Chiew and colleagues covered one of four viewing windows with an opaque barrier. The experiment altered visual contact at a specific location while leaving the wider encounter habitat available to the same little-penguin group. || When covered, the window attracted fewer visitors and fewer potentially threatening actions such as banging, loud vocalizations and sudden movements. The manipulation therefore reduced several correlated sources of stimulation associated with close viewing. || More penguins were visible and preening in the water near the covered window, while fewer were vigilant there. **Preening** is maintenance of the feathers with the bill; its return to the affected location accompanied reduced defensive monitoring.')
add('Retreat areas alter penguins’ spatial choices',['window1','window6'],'w',
'The Taronga penguins preferred a corner area that was not visible to visitors, whether the main viewing window was covered or uncovered. This distribution identifies a persistent pattern of space use rather than only an immediate reaction to the experimental treatment. || Covering the main window increased visibility near that window but did not eliminate the preference for the corner. A habitat can therefore contain both an experimentally modifiable exposure area and a consistently preferred retreat area. || **Choice** in habitat use requires accessible alternatives with different exposure conditions. Preserving a retreat gives penguins an opportunity to reduce visitor contact through their own movement, instead of depending entirely on changes imposed by staff.')
add('Visitor exposure depends on habitat geometry',['window2','window6'],'wp',
'The window-covering experiment concentrated on a narrow encounter section with several viewing windows. The proximity experiment manipulated an open viewing edge with a physical separation barrier. These settings offered visitors different routes for visual, tactile and movement-related contact. || Penguins in both experiments altered defensive behavior or use of space when close contact was reduced. The location of a viewing edge matters because an animal’s ordinary swimming route can repeatedly bring it within the visitor’s sensory field. || **Sensory exposure** is the stimulation actually reaching an animal in its occupied location. Evaluation therefore connects visitor behavior with the animal’s position and activity, rather than using total visitor attendance as a complete description of the encounter.')
add('Control isolates a property of the stressor',['control2','control1'],'b',
'In Baratta and colleagues’ rat experiment, one animal could terminate tail shock by turning a wheel. Its yoked partner received the same shocks but could not determine when they ended. **Yoking** matches the physical exposure while changing the relation between behavior and outcome. || **Controllability** means that an animal’s action changes the aversive event. The comparison separates having control from simply receiving less stimulation, because the escapable and inescapable conditions share the shock sequence. || The researchers examined neurons linking the ventral medial prefrontal cortex to the dorsal raphe nucleus. This projection provides an experimentally accessible circuit in which stressor control can alter neuronal recruitment despite matched physical exposure.')
add('Tracing identifies the prefrontal projection',['control1'],'b',
'**Retrograde tracing** labels neurons according to where their axons terminate. Baratta and colleagues deposited fluorogold in the rat dorsal raphe nucleus, then identified labeled cell bodies in the prelimbic and infralimbic regions of ventral medial prefrontal cortex. || The **dorsal raphe nucleus** is a brainstem region containing many serotonin-releasing neurons. The **prelimbic** and **infralimbic** regions are adjoining prefrontal areas with projections to this region. Their connection permits cortical processes to influence brainstem stress-related signaling. || Combining fluorogold labeling with Fos staining identified which projection neurons had been recruited during stress. The anatomical label specifies the connection, while the activity-related label distinguishes the subset responding under a particular exposure condition.')
add('Projection-specific activity reveals control sensitivity',['control2','control1'],'b',
'**Fos** is an activity-related protein whose expression can mark neuronal recruitment over a longer interval than an individual electrical spike. Baratta and colleagues measured Fos in prefrontal neurons after escapable shock, inescapable shock or home-cage conditions. || Both stress conditions increased overall prefrontal Fos expression. The distinguishing result was in the prelimbic neurons labeled by the dorsal raphe tracer: a greater proportion expressed Fos after controllable than uncontrollable stress. || **Projection specificity** means that a response differs in neurons selected by their target. Counting all activated cells together would obscure this distinction. Behavioral control recruited the connected prelimbic population more strongly even though the total stress-related activation was similar between conditions.')
add('Excitatory cortical input can recruit inhibition',['control1','control2'],'b',
'Baratta and colleagues discussed a hypothesis in which the prefrontal projection reduces serotonergic activity by recruiting local inhibitory cells in the dorsal raphe. **Serotonin**, also called 5-HT, is a neurotransmitter released by many neurons in this brainstem region. || **Glutamate** is the excitatory transmitter used by the cortical projection. **GABA**, gamma-aminobutyric acid, is an inhibitory transmitter released by local neurons. The proposed sequence is cortical excitation of GABA neurons followed by inhibition of serotonin neurons. || A **GABA-A receptor** is a receptor that directly gates an ion channel when GABA binds. Its activation mediates the inhibitory step described in the paper’s circuit account. An excitatory connection can therefore produce net inhibition when an intervening neuron reverses the sign of the effect.')
add('Prior control changes recruitment one week later',['control3','control1'],'b',
'Baratta and colleagues tested whether the circuit’s response depended on previous experience. Rats first received controllable or uncontrollable shock; seven days later, both groups encountered an uncontrollable stressor before their prefrontal projection neurons were examined. || Animals with prior control recruited a greater proportion of dorsal-raphe-projecting prelimbic neurons during the later uncontrollable exposure. The initial experience therefore changed how the connected cortical population responded to a subsequent event. || **Plasticity** is an experience-dependent change in a biological system’s response. Here, the measured adaptation was altered recruitment of a particular projection population. Its seven-day persistence connects the history of behavioral control to later stress-related neuronal activation.')
add('Related elephant groups differ in social contact',['social2','social3'],'s',
'Harvey and colleagues compared two groups of adult female Asian elephants. One group consisted entirely of related individuals; in the other, only two animals were related. The researchers recorded directed social interactions among known individuals. || **Affiliative behavior** is friendly social contact, including trunk touches, rubbing and other non-aggressive interactions. The all-related group engaged in more affiliative interactions and fewer agonistic interactions than the less-related group. **Agonistic behavior** concerns conflict, threat or competition. || Social housing therefore has a qualitative dimension beyond group size. Relationships among particular animals influence the balance of friendly and conflict-related contact experienced within a group, so merely counting companions does not describe the social environment.')
add('Affiliation has multiple behavioral forms',['social3'],'s',
'Asian elephants exchanged several forms of friendly contact in Harvey and colleagues’ observations. Trunk contact, rubbing, leaning and following were recorded separately, allowing social interaction to be described by its form as well as its overall frequency. || The all-related group had more affiliative contact overall, but the distribution among different forms also mattered. A **behavioral repertoire** is the set of distinct actions an animal performs; a social repertoire includes different ways of approaching, touching and remaining with others. || Recording these forms preserves the biological content of a relationship. A group with frequent mutual contact differs from a group whose members merely occupy the same enclosure, even if both satisfy an identical numerical housing recommendation.')
add('Social relationships have direction and identity',['social5'],'s',
'A **directed social network** records who initiates an interaction and who receives it. In the elephant study, individuals were represented separately and connections were weighted by the frequency of affiliative interactions between each pair. || **Dyadic** interactions occur between two individuals. Summing all friendly contacts into a group total loses the distinction between broadly distributed affiliation and contact concentrated in a few dyads. The networks preserved differences in initiator, recipient and strength of association. || Particular relationships can consequently be monitored through group changes. A compatible social environment depends on the connections animals actually form, including asymmetric patterns of contact, rather than assuming every member relates equally to every other member.')
add('Displacement can resolve conflict without attack',['social7'],'s',
'**Non-contact displacement** occurs when one animal gives way to another without a physical attack. Harvey and colleagues distinguished this response from overt agonistic acts, allowing avoidance of escalation to be examined as its own social process. || The related elephant group had more non-contact displacement, including daughters giving way to mothers and aunts. This pattern was consistent with an established family-based rank system, in which a familiar partner’s approach can be sufficient to produce movement. || A displacement event therefore has to be interpreted within the relationship. In a stable hierarchy, yielding can reduce overt conflict; an assessment that counts every movement away as equivalent would discard the difference between orderly spacing and repeated aggressive exclusion.')
add('Group compatibility requires individual observation',['social4','social6'],'s',
'Harvey and colleagues recorded pushes, bites, trunk swings and other agonistic actions separately from affiliation. Their directed networks also identified which elephants initiated conflict and which received it, rather than treating the group as a single average animal. || The less-related group exhibited more agonistic behavior. The study compared existing groups, so relatedness was embedded in each group’s history and conditions rather than assigned experimentally. This design fact changes how strongly relatedness itself can be identified as the cause. || Management can still act on the measured relationships: preserve familiar compatible associations, monitor recipients of repeated conflict, and distinguish friendly contact from simple proximity. Individual social observations supply the relevant evidence for evaluating a particular group.')
add('A habitat transition changes several opportunities',['habit2'],'h',
'Glaeser and colleagues followed Asian elephants during a four-year transition to a more complex Oregon Zoo habitat. The redesign aimed to increase activity, foraging opportunities and social choice, and the study followed behavior, movement and hormone measures across phases. || **Environmental complexity** includes the distribution and variety of resources and the routes available for reaching them. The new habitat provided multiple areas, food-delivery resources and opportunities to associate with or separate from particular herdmates. || Evaluation continued through construction and acclimation instead of ending when the building opened. **Acclimation** is adjustment to new conditions; measuring this period connects a habitat intervention with the animal’s actual subsequent use of the resources and space.')
add('Walking increased in the redesigned elephant habitat',['habit3'],'h',
'Glaeser and colleagues used GPS records to measure daily elephant walking in the previous and new habitats. **GPS**, the Global Positioning System, provides successive locations from which travel distance and use of outdoor areas can be characterized. || The elephants walked farther in the redesigned environment, with average distances exceeding 15 km per day in the new habitat. Individual responses differed, so the study retained each animal’s movement profile instead of only combining the whole group. || Increased walking accompanied changes in resource distribution and opportunities for foraging. Movement emerged from what the habitat allowed animals to do and where resources were located, connecting enclosure design to purposeful activity across the day.')
add('Resource distribution can organize daily movement',['habit3','habit10'],'hg',
'In the Oregon habitat, food was distributed with less spatial and temporal predictability. **Foraging** includes searching for and obtaining food, so its opportunities depend on where food appears and the actions required to reach or extract it. || In a separate North American zoo-elephant study, Holdgate and colleagues measured an average outdoor walking distance of 5.3 km per day. Temporally unpredictable feeding was associated with 1.29 km more daily walking than predictable feeding. || These findings link movement with feeding organization across two study designs. Dispersing food and varying its delivery can recruit travel as part of acquiring resources, rather than relying on extra space alone to produce greater activity.')
add('Space use reveals access to the whole habitat',['habit4'],'h',
'GPS location records in the new Oregon elephant habitat covered the available outdoor areas rather than remaining concentrated in only a few locations. Animals used pools, mounds, feeders and areas near public viewing in different combinations. || **Space use** describes the distribution of an animal’s locations through time. It differs from distance traveled: two animals can cover similar distances while one repeatedly uses a narrow route and the other reaches many parts of a habitat. || Representative warm- and cool-season records documented continued use of the broader environment. The distribution of locations linked access to actual movement, adding information about habitat function beyond a map of its boundaries or a single total-area measurement.')
add('Endocrine responses vary across transition phases',['habit5'],'h',
'Glaeser and colleagues measured fecal glucocorticoid metabolites before construction, during construction and in the new elephant habitat. These hormone breakdown products were reported as concentrations in nanograms per gram of feces, linking the assay to a defined biological sample. || **Longitudinal sampling** follows the same individual repeatedly. The hormone patterns differed among elephants and across phases rather than following one uniform response to every environmental change. Individual histories remained visible in the time-resolved records. || Glucocorticoid signaling participates in physiological responses to changing demands. Interpreting the measured concentrations alongside behavior and life events preserves this adaptive role and avoids reducing every hormonal increase to a single description of environmental quality.')
add('Individual baselines anchor physiological interpretation',['habit5'],'h',
'A **baseline** is a reference pattern measured before the condition of interest. In the elephant habitat study, repeated samples from the previous habitat provided an individual reference against which construction and later occupancy could be compared. || The authors examined both typical metabolite concentrations and their variation over time. A shift in the distribution of an individual’s values is different from a one-time high sample, especially when social changes, reproductive development or other events occur during observation. || Following each elephant through the transition connected endocrine changes with its own experience. The biological comparison is the individual across conditions, which complements a group-level description of increased walking or changes in social contact.')
add('Activity budgets identify what occupies the day',['habit6'],'h',
'An **activity budget** divides observation time among categories such as feeding, locomotion, resting and social behavior. Glaeser and colleagues compared these categories in the previous and new elephant habitats, both for individuals and for the group. || The elephants became more active in the redesigned environment. Recording categories retained the difference between spending more time acquiring food, traveling, interacting socially or engaging in other activities instead of collapsing all change into a single activity score. || Time devoted to one category constrains the time available for others during the same observation period. A habitat intervention therefore reorganizes daily behavior, and evaluating the resulting repertoire requires the composition of activity as well as its overall amount.')
add('Proximity and active interaction are different measures',['habit7','habit8'],'h',
'**Proximity** means being physically near another animal. In the Oregon elephant study, proximity to herdmates and active social interaction were measured separately, because two elephants could remain near each other without exchanging any recorded social action. || In the new habitat, individuals had greater autonomy in selecting social partners. Their proximity patterns and partner-specific interactions changed as the environment offered more ways to associate or separate while remaining within the managed group. || An animal’s ability to regulate distance is part of its social environment. Measuring both proximity and active interaction distinguishes simple co-location from contact chosen with particular partners, preserving a behavioral dimension of social choice.')
add('Social choice changes partner-specific interactions',['habit8'],'h',
'Glaeser and colleagues retained the identity of each elephant’s social partners in their analysis. Interactions with one herdmate could rise while contact with another fell, even when the individual’s total social activity changed relatively little. || **Partner-specific behavior** is directed toward particular individuals rather than toward the group indiscriminately. The new habitat’s opportunities for separation and movement allowed these patterns to emerge within a setting where several social relationships remained available. || Group averages can consequently hide reorganized associations. Monitoring individual partners records how a habitat changes access to companions, including the balance among adult females, a calf and developing males, rather than only whether social behavior occurs.')
add('Friendly contact dominates the observed social repertoire',['habit9'],'h',
'In the Oregon elephant observations, affiliative behavior formed the majority of social interactions across individuals, ranging from 72% to 91%. This distribution identifies the kinds of contact occurring in the herd rather than only the frequency of encounters. || **Functional classification** groups actions according to their social role, such as affiliation, agonism or dominance and submission. These categories retain whether contact involves friendly engagement, conflict or adjustment to rank relationships. || A compatible herd can include some conflict while remaining predominantly affiliative. Evaluating the relative composition of interactions alongside partner identity and opportunities for spacing provides a more precise description than labeling every social event either beneficial or harmful.')
add('Enrichment value depends on animals’ engagement',['habit10'],'h',
'**Environmental enrichment** is a change intended to provide biologically relevant opportunities for behavior. In the Oregon study, recorded resource interactions were divided among food-delivery resources, enrichment objects and permanent habitat features. || Food seeking and feeding occupied a larger share of resource engagement in the new habitat. The proportion involving enrichment objects fell while engagement with food-delivery resources rose, so the animals’ use of the environment changed even though multiple resource types remained available. || Counting installed objects would miss this redistribution. Enrichment assessment follows what animals do with a resource, including the searching, manipulation or travel it recruits, and compares that behavior with the functions the intervention was intended to support.')
add('Walking distance is not a complete welfare score',['habit3'],'hg',
'Holdgate and colleagues examined daily walking alongside foot health, joint health, body condition and stereotypic behavior in zoo elephants. Outdoor distance traveled was associated with feeding diversity and social grouping, but it was not associated with those measured welfare outcomes. || This finding changes the meaning of increased movement. A distance in kilometers describes locomotion, not a direct score of physical health or emotional state. The Oregon habitat’s longer walking distances therefore belong alongside its behavioral and physiological observations. || **Multiple indicators** sample different aspects of an animal’s life. Movement, social interaction, repetitive behavior and health measures jointly describe habitat outcomes while preserving the biological meaning of each measurement.')
add('King penguins use expanded aquatic opportunities',['king3','king2'],'k',
'Fuller and colleagues studied king penguins moved between their previous habitat and a redesigned conservation center. The new environment offered more aquatic space and complexity, and the researchers combined behavioral observation with flipper-mounted time–depth recorders. || A **time–depth recorder** measures when an animal enters water and the depth of its movement. These data captured aquatic activity that observers at viewing windows could miss, extending measurement beyond behavior visible from the public side. || King penguins spent more time swimming in the redesigned habitat. The change connected the provision of aquatic opportunities to their actual use, rather than treating greater pool dimensions as sufficient evidence of a behavioral benefit.')
add('Greater depth changes the penguins’ aquatic repertoire',['king4','king2'],'k',
'The redesigned king-penguin habitat offered deeper water than the previous enclosure. Fuller and colleagues separated recorder measurements into depth categories, allowing surface use to be distinguished from movement through deeper parts of the pool. || Penguins spent more time at greater depths in the redesigned environment. **Three-dimensional habitat use** includes vertical position as well as movement across the surface, so aquatic activity cannot be completely described by time in water alone. || The depth records connected habitat design with access to a different swimming repertoire. Providing vertical space changed the range of aquatic positions the birds actually occupied, preserving a biologically relevant component of a diving species’ environment.')
add('Daily timing shapes aquatic habitat use',['king3','king2'],'k',
'Fuller and colleagues used the time–depth records to examine swimming across the hours of the day. The comparison retained temporal patterns rather than reporting only a single percentage of time swimming for each habitat. || **Daily activity pattern** describes when behavior occurs within a day. Swimming varied with hour and habitat, with the redesigned environment supporting greater aquatic activity across the measured daytime pattern. The same pool can consequently have different behavioral value at different times. || Continuous instruments complement scheduled observations because an observer’s sampling window can omit activity at other hours. Evaluating access across the day links management schedules with the periods when the animals actually use aquatic opportunities.')
add('Individual penguins differ in their response to redesign',['king6','king2'],'k',
'The king-penguin study retained individual swimming percentages in the two habitats. Some animals changed their aquatic activity much more than others, rather than responding as a uniform group to the redesigned space. || **Individual variation** includes consistent differences in how animals use the same available environment. Recording each bird separately prevents a large response by one animal from being interpreted as the experience of every member of the group. || The intervention also changed social behavior and proximity, creating several potential dimensions of response. Repeated individual observations connect a habitat change with the particular repertoire of each animal while preserving the collective pattern of increased swimming.')
add('More space permits social separation as well as contact',['king8','king9'],'k',
'Fuller and colleagues measured proximity within 0.5 m of other penguins. King penguins spent less time near penguins of other species in the redesigned environment and more time alone, alongside changes in positive social behavior and aggression. || **Social spacing** is the regulation of distance between individuals. Expanded habitat opportunities can allow contact at some times and separation at others, so improved social conditions need not take the form of animals remaining continuously close together. || Species identity also mattered in the mixed-species exhibit. Distinguishing proximity to other king penguins from proximity to other species preserved the actual social exposure experienced by the focal birds, rather than treating every neighbor as equivalent.')
add('Behavioral diversity accompanies reduced aggression',['king5','king7'],'k',
'In the redesigned king-penguin habitat, Fuller and colleagues recorded increased swimming and positive social behavior together with reduced aggression. Their observations separated behavioral states, which occupy time, from events, which occur as discrete actions. || **Allopreening** is feather maintenance directed toward another bird. It was one of the social events recorded alongside displays, bathing and agonistic actions. Recording these behaviors separately retained the difference between friendly contact and conflict within the group. || The combined repertoire connects aquatic opportunities with social outcomes. Greater swimming, more positive contact and reduced aggression describe several measured responses to the redesigned environment, extending assessment beyond one activity or one proximity measure.')
add('Nighttime conditions contribute to elephant welfare',['habit7','habit6'],'eh',
'Greco and colleagues observed zoo-elephant stereotypy during both daytime and nighttime periods. Repetitive behavior occupied 15.5% of daytime observations and 24.8% of nighttime observations, identifying management periods that differed in the measured behavioral outcome. || At night, larger social groups and access to both indoor and outdoor areas were associated with lower stereotypy. **Indoor–outdoor access** gives animals alternative environmental conditions and routes rather than fixing their location within one housing area. || Welfare assessment therefore includes the periods when visitors are absent and public observation is limited. Access to companions and alternative spaces remains biologically relevant across the full management day, including hours outside the zoo’s public opening schedule.')
add('Management histories remain part of present behavior',['social5','habit8'],'es',
'Greco and colleagues found that histories of transfers between zoos were associated with greater elephant stereotypy. Current housing separately from companions was also associated with more daytime repetitive behavior, while time with juveniles was associated with less. || A **life-history event** is a major experience such as a transfer or change in social companions. Present behavior reflects these accumulated experiences as well as the resources visible in the current enclosure, so an animal’s management record belongs in its welfare assessment. || Harvey and colleagues’ partner-specific observations preserve another part of this history: social relationships have identities and directions. Group changes affect particular established connections, not merely the total number of elephants available as potential companions.')
add('Welfare recommendations combine evidence and judgment',['carnivore','habit3'],'ch',
'**Neuroethics** examines moral questions involving nervous systems, behavior and the conditions that affect animals’ experiences. Clubb and Mason’s recommendation to improve or reconsider keeping naturally wide-ranging carnivores was informed by their measured pacing and infant-mortality relationships. || A **normative judgment** concerns what ought to be done. The data establish relationships among conditions and outcomes; the judgment assigns significance to those outcomes when deciding whether a practice is acceptable or requires change. || The Oregon elephant study supplies evidence that redesign can alter movement, resource use and social opportunities. Ethical evaluation can compare such measured improvements with the needs identified for a species, while retaining responsibility for animals whose opportunities remain restricted.')
add('Animal responses determine whether an intervention works',['habit10','king6'],'hk',
'An intervention is evaluated by its consequences for animals, not only by its intended purpose. The Oregon elephants shifted their resource engagement toward food-delivery opportunities, while king penguins showed individual differences in swimming after habitat redesign. || **Outcome-based assessment** compares measured behavior or physiology before and after a change, using the study’s relevant comparison conditions. It can identify a useful opportunity, a weak response or a benefit that applies to some individuals more than others. || Neuroethical decisions can use these outcomes to revise management: preserve opportunities animals use, address persistent avoidance or conflict, and continue monitoring across time. These are proposed decision principles grounded in the studies’ observed responses and explicitly tied to the animals’ behavioral needs.')
assert len(slides)==44,len(slides)
take=[('Species-specific needs','Natural ranging, aquatic behavior and social relationships help predict which managed conditions animals can use effectively.'),('Sensory exposure','Visitor distance and viewing barriers can change penguin vigilance, avoidance and swimming.'),('Neural control','In rats, controllable stress preferentially recruits dorsal-raphe-projecting prelimbic neurons, and prior control changes later recruitment.'),('Social choice','Companion identity, affiliation, conflict and opportunities for spacing describe social housing more precisely than group size alone.'),('Enrichment outcomes','Measure how animals use resources and space; more objects or more walking alone is not a complete welfare outcome.'),('Neuroethical reasoning','Connect measured animal outcomes to explicitly stated welfare judgments, keeping the species and experimental preparation identifiable.')]
spec={'lecture':62,'theme':'harbor-ink-pearl','content_slides':44,'title_height':4.0,'title_image':fig('king2'),'title_refs':[refs['k']['ref']],'slides':slides,'takeaways':{'items':[{'lead':a,'text':b} for a,b in take],'cite':'Clubb & Mason (2003); Baratta et al. (2009); Chiew et al. (2019, 2020); Harvey et al. (2018); Glaeser et al. (2021); Fuller et al. (2023)','refs':[refs[k]['ref'] for k in ['c','b','p','w','s','h','k']]}}
(D/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2))
print('44 teaching slides written')
