#!/usr/bin/env python3
"""Lecture 12: verified studies, original publication crops, and teaching notes."""
import json,re
from pathlib import Path
BASE=Path(__file__).resolve().parent
R=json.loads((BASE/'research.json').read_text())['sources']
AUTH={'land69a':'Land','land69b':'Land','land71':'Land','devoe75':'DeVoe','nagata12':'Nagata et al.','zurek15':'Zurek et al.','zurek10':'Zurek et al.','zn12b':'Zurek & Nelson','jakob18':'Jakob et al.','steinhoff20':'Steinhoff et al.','menda14':'Menda et al.'}
YEAR={k:str(v['year']['date-parts'][0][0])for k,v in R.items()}
YEAR.update(land69a='1969a',land69b='1969b')
C=json.loads((BASE/'crops.json').read_text())['crops']
SL=[]
def ref(k):return R[k]['original_reference']
def fig(n,d,p=''):
 k=C[n][0];num=re.search(r'_f(\d+)',n)[1]
 return {'path':f'figures/{n}.png','kind':'article','caption':f'{AUTH[k]} ({YEAR[k]}), Fig. {num}'+(f'({p})'if p else '')+'. '+d,'source_url':'https://doi.org/'+R[k]['doi']}
def add(title,k,fs,body,notes,**kw):
 ks=[k]if isinstance(k,str)else list(k)
 for f in fs:
  fk=C[Path(f['path']).stem][0]
  if fk not in ks:ks.append(fk)
 ps=[x.strip()for x in body.split('|||')];ns=[x.strip()for x in notes.split('|||')]
 assert len(ps)==3 and len(title)<=62,(title,len(title))
 d={'title':title,'body':ps,'transcript':ns,'cite':'; '.join(f'{AUTH[x]} ({YEAR[x]})'for x in ks),'refs':[ref(x)for x in ks],'layout':'figure-right'if len(fs)==1 else 'figures-right','figure_width':5.7}
 if len(fs)==1:d['figure']=fs[0]
 else:d.update(figures=fs,primary_figure_height=2.65)
 d.update(kw);SL.append(d)

add('Lateral eyes can guide stalking and attacks','zurek10',[fig('z10_f1','Controlled display arrangement for isolated lateral vision.')],
"""Jumping spiders are salticid arachnids that approach prey before launching a directed jump. **Stalking** is the controlled approach preceding attack; **orientation** is a body turn toward a visual target. These actions can depend on different eye pairs. ||| Zurek and colleagues covered every eye except the **anterior lateral eyes**, the frontmost lateral pair, in _Servaea vestita_. Spiders encountered a live fly on a sloping ramp, initially approximately 25 cm away. The manipulation isolated visual information available through that pair. ||| Spiders retaining only anterior lateral vision could orient, stalk and attack. Performance was limited, and some individuals did not pursue the fly. The result establishes that these eyes can support parts of predation; it does not establish that the principal eyes are dispensable for normal hunting.""",
"""Salticids hunt through a sequence of visually guided actions. Turning toward a potential target brings it nearer the forward viewing direction, whereas stalking changes the distance between predator and prey. An attack requires an additional commitment to jump. ||| Opaque dental silicone covered the other eye pairs. A moving live fly supplied a natural target, and the ramp controlled its position relative to the spider. The eye manipulation therefore concerns the available visual input rather than an invented classification of hunting behavior. ||| An isolated eye pair supporting an action is evidence of sufficiency under the test conditions. It does not establish normal performance after removing the principal eyes, or prove that an intact spider relies exclusively on lateral vision.""")
add('Controlled dots isolate visually evoked orientation','zurek10',[fig('z10_f2','Orientation probability across size, speed and contrast.')],
"""A **visual field** is the region of space accessible to an eye. To measure target detection within the anterior lateral field, Zurek and colleagues positioned _Servaea vestita_ on a freely rotating 15-mm polystyrene ball while the spider remained fixed between two display screens. ||| The screens were 150 mm away and separated by 120°. Dark dots varied in angular diameter, speed and contrast against a gray background. **Angular size** specifies an object's extent at the eye in degrees, independently of its physical size. ||| A 4° dot moving at 9°/s with 40% contrast elicited orientation frequently, whereas a blank gray screen rarely did. The ball registered attempted turns without moving the spider through the scene. These responses measure detection and orientation, not recognition of a particular prey species.""",
"""The controlled dot removes the changing shape and irregular movement of a live fly. A blank screen provides a comparison for turns that occur without a visible moving target. ||| The animal's feet rotate the lightweight ball, so an orientation response can be recorded while stimulus position remains under experimental control. The display covers known directions relative to the anterior lateral eyes. ||| Degrees describe the target as viewed from the spider. A four-degree dot can be produced by different physical objects at different distances, so angular size is the relevant variable for comparing this visual stimulus with the receptor array.""")
add('Orientation depends jointly on size and speed','zurek10',[fig('z10_f2','Size and speed interact at each tested contrast.')],
"""**Contrast** is the luminance difference between a target and its background relative to the background luminance in this experiment. Zurek and colleagues varied contrast alongside dot diameter, rather than treating every visible object as an equally effective stimulus. ||| Dots ranged from 0.5° to 8°, with speeds spanning 1–81°/s. Orientation depended on the combination of these variables: targets near 2–4° at stronger contrast were especially effective, but the favorable speed changed with target size and contrast. ||| Weak contrast reduced responses, and the smallest dot was not simply the best stimulus because it resembled distant prey. The measured response map constrains explanations of anterior lateral detection. It does not supply a single acuity threshold or a neural mechanism for multiplying size, contrast and motion signals.""",
"""Contrast changes the strength of the visual signal while angular diameter changes how much of the retina the target occupies. Speed changes how rapidly that signal crosses successive receptors. ||| Testing these variables together reveals relationships that a single moving-dot condition would miss. A stimulus that is effective at one contrast can become much less effective at another, even when it moves at the same speed. ||| An orientation probability is the output of sensory detection, response selection and motor execution. Its dependence on size and speed does not identify the tuning of a particular interneuron, and rare responses at weak contrast are not a reliable universal visibility threshold.""")
add('Hunger alters the probability of turning toward a target','zurek10',[fig('z10_f3','Feeding state and sex affect orientation.'),fig('z10_f2','The controlled target conditions used in the behavioral assay.')],
"""**Internal state** includes physiological conditions such as hunger that influence behavioral responses to the same sensory input. Zurek and colleagues compared _Servaea vestita_ one day after feeding with spiders tested seven days after feeding. ||| Eye availability and moving-dot presentation were controlled while feeding history changed. Hungry spiders oriented more often, and females generally responded more frequently than males. The measured variable was the probability of a turn, not a direct receptor voltage or brain firing rate. ||| Hunger therefore changes the relationship between a visual target and an overt action. The experiment does not localize that change to photoreceptors, visual interneurons or motor circuits. Lower response probability in a recently fed spider cannot by itself be interpreted as failure to detect the target.""",
"""The sensory stimulus can remain unchanged while its behavioral consequence varies with feeding state. That distinction matters because an absent turn can reflect a decision not to pursue rather than an invisible target. ||| The experiment compared a short interval after feeding with a longer deprivation interval. Both sexes were examined, allowing state dependence to be distinguished from an overall difference in responsiveness between males and females. ||| The assay supplies a behavioral measure. Establishing where hunger acts would require activity measurements or interventions in the relevant pathway; the turning data alone do not identify a transmitter or receptor responsible for the effect.""")
add('Principal eyes magnify a restricted visual field','land69a',[fig('a69_f1','Principal and anterior lateral eye optics.'),fig('z15_f1bc','Principal-eye aperture and retinal filter in Habronattus.','B, C')],
"""The **principal eyes**, also called anterior median eyes, are the large forward-facing pair. Their long optical tubes produce a magnified retinal image over a restricted field. Land compared their optical organization with the broader viewing arrangement of the anterior lateral eyes. ||| In _Phidippus_ and _Metaphidippus_, the principal-eye lens remains fixed in the body while the retinal tube can move behind it. Moving that tube changes which direction is sampled by the small high-resolution receptor array. ||| A broad lateral field and a restricted principal field provide different spatial access to a target. The colored retinal preparation from _Habronattus_ identifies a comparable principal-eye structure in another genus. Its red filter is a specialization of that lineage and should not be assigned to Land's species.""",
"""The principal eye separates the position of the external lens from the position of the retina. The lens is fixed in the carapace, but the long retinal assembly can move, changing the direction sampled through the lens. ||| Long focal length enlarges the image at the retina. The advantage is fine angular sampling; the accompanying restricted field makes accurate alignment with a target necessary. ||| The modern Habronattus section supplies colored anatomical evidence of a principal-eye retina, but the studies involve different genera. Its filter identifies a specialized structure rather than a general property of every salticid principal eye.""")
add('Four retinal layers occupy different optical depths','land69a',[fig('a69_f3','Layered principal-eye retina and its cellular organization.')],
"""A **photoreceptor** is a sensory cell whose light-sensitive region converts absorbed light into an electrical response. Land's principal-eye sections revealed four receptor layers at different distances from the lens, numbered from the deepest layer, L1, toward L4 nearer the incoming light. ||| L1 and L2 extend across the boomerang-shaped retina; L3 and L4 occupy more restricted central regions. Receptor segments in L1–L3 are largely aligned with incident light, whereas L4 contains differently oriented, more ovoid segments. ||| The retina is therefore a three-dimensional receptor arrangement rather than a single flat screen. Histological depth identifies possible differences in optical focus and light sampling. Anatomy alone does not establish a layer's wavelength sensitivity, response kinetics or contribution to a specific hunting decision.""",
"""Layer numbers refer to their depth in the principal-eye tube, not four successive brain stations. Light can pass through the more anterior receptor regions before reaching deeper ones. ||| Land used sections of several orientations to distinguish the layers and the shapes of the receptor segments. The central restriction of the upper layers means that different parts of the retina do not contain an identical stack of receptors. ||| Receptor shape and placement constrain which light can be absorbed, but a histological section does not measure an electrical response. Assigning a pigment or spectral class to a particular layer requires additional physiological or molecular evidence.""")
add('Dense receptor spacing supports fine angular sampling','land69a',[fig('a69_f5','Receptor mosaics in the principal-eye layers.'),fig('n12_f1c','Four retinal layers in Hasarius adansoni.','C')],
"""A **receptor mosaic** is the spatial arrangement of sensory cells sampling an image. Land measured especially dense packing in the principal-eye retinal region aligned with the highest-resolution viewing direction. ||| Minimum receptor separation was approximately 1.7 µm, corresponding to about 11 arcmin in the studied eyes. An **arcminute** is one sixtieth of a degree. These measurements link microscopic spacing to the angular separation of neighboring image samples. ||| Fine sampling permits small spatial differences to reach separate receptor positions, but receptor spacing alone does not prove behavioral discrimination at that limit. Optical blur, neural pooling and viewing conditions can change effective acuity. The colored section identifies the corresponding layered organ in _Hasarius_, without implying that its spacing equals Land's measured value.""",
"""A microscopic distance becomes an angular sampling interval through the eye's optical magnification. Land related the receptor mosaic to the image produced by the lens instead of treating receptor diameter as a behavioral acuity measurement. ||| Eleven arcminutes is the reported finest separation in the studied preparation. It is not a universal threshold for every salticid species or every part of the visual field. ||| The colored Hasarius section locates the layers anatomically. Its inclusion does not transfer a numerical measurement between species; optical measurements and behavioral tests remain distinct kinds of evidence.""")
add('Layer position changes where an image is in focus','land69a',[fig('a69_f12','Image positions for different object distances.')],
"""**Focus** is the optical condition in which rays from an object form a comparatively sharp image at a receptor plane. A layered retina places different receptor populations at different image distances, so an object need not be equally sharp in every layer. ||| Land combined retinal anatomy with optical measurements. For blue-green light, the best image approached L2, while deeper L1 could receive a focused image from an object at approximately 2 cm under the reported optical conditions. ||| These relationships make retinal depth relevant to viewing distance. They do not prove that the spider actively accommodates its lens or consciously selects a layer. Land's proposed spectral assignments to the layers were hypotheses; later measurements of receptor sensitivity and pigment localization must determine which wavelengths actually activate each population.""",
"""The principal eye contains several receptor depths behind a fixed optical system. A change in object distance moves the sharp image plane relative to those layers even when the lens itself does not change shape. ||| Land related the sectioned retina to optical observations. The approximate two-centimeter near focus concerns a reported combination of wavelength and layer, rather than a universal preferred hunting distance. ||| An optical prediction and a pigment measurement answer different questions. Later work can retain the layered geometry while revising an early proposal that a specific layer contains receptors tuned to a particular color.""")
add('Receptor projections preserve layered organization','land69a',[fig('a69_f2','Retinal layers and axonal endings in the first optic glomerulus.'),fig('s20_f1','Principal-eye neuropils in Marpissa muscosa.','a–f')],
"""An **axon** is the neuronal process carrying signals away from a cell's sensory region. A **neuropil** is a dense region of neuronal processes where synaptic interactions commonly occur. Land traced principal-eye receptor fibers toward a first visual neuropil, historically termed the optic glomerulus. ||| Fibers arising from different retinal layers appeared to end in different regions of that neuropil. The result supports organized input rather than complete mixing immediately after light detection. It is based on anatomical tracing, not recordings of synaptic transmission. ||| Modern labeled sections in _Marpissa muscosa_ identify AM1 and AM2, the first- and second-order principal-eye neuropils. They provide anatomical landmarks for a comparable pathway, while leaving the exact correspondence between Land's layer-specific endings and modern neuronal cell types unresolved.""",
"""Photoreceptor axons carry the output of the retinal cells into the brain. Land's tracing associated different retinal depths with different terminal regions, suggesting that the layered inputs retain some anatomical separation. ||| A neuropil is defined by its processes and connections rather than by a sheet of cell bodies. Histological proximity does not establish the sign, strength or timing of a synaptic response. ||| In Marpissa, modern labeling distinguishes two principal-eye processing regions. Those landmarks do not identify every receptor's postsynaptic partner, and the different species and methods prevent a direct assignment of a traced fiber to a functional channel.""")
add('Wavelength changes the focal plane of the same eye','nagata12',[fig('n12_f1','Principal-eye anatomy, jump accuracy and the published optical account.','A–D')],
"""**Chromatic aberration** is a wavelength-dependent difference in optical focus. Nagata and colleagues investigated this property in the principal eyes of _Hasarius adansoni_, whose retina contains receptors at four depths behind the lens. ||| Green and red light form their sharpest images at different positions. A layer receiving a blurred green image can receive a different amount of blur from the same object under red illumination, even when the object has not moved. ||| The authors proposed that this wavelength-dependent **defocus**, the departure from a sharp image, could bias distance estimation. Retinal anatomy and optical calculations support the availability of such a cue. Establishing its behavioral use requires altering illumination and measuring the resulting jump, rather than inferring depth perception from a section alone.""",
"""Chromatic aberration is an optical effect rather than a claim about conscious color perception. The wavelength of incident light changes the image plane relative to the receptor layers. ||| Hasarius has a layered principal retina. The same target at the same physical distance can therefore generate a different pattern of focus across the layers under red and green light. ||| Nagata's account links this difference to a predicted error in perceived distance. The anatomical arrangement makes the proposal possible, but the behavioral manipulation supplies the evidence that the optical cue influences jumping.""")
add('Intracellular recordings resolve receptor voltage','devoe75',[fig('d75_f1','Responses to calibrated flashes in individual photoreceptors.'),fig('n12_f1c','The layered principal-eye organ in Hasarius.','C')],
"""An **intracellular recording** measures voltage with an electrode inside a cell. DeVoe recorded principal-eye photoreceptors in _Phidippus regius_ while presenting light flashes of selected wavelengths, linking light stimulation directly to receptor electrical activity. ||| The tested flashes lasted 100 ms. Responses were primarily graded depolarizations: the membrane voltage became less negative by an amount depending on the stimulus, rather than producing an all-or-none behavioral turn. The recording calibration included a 5-mV voltage reference. ||| Wavelength and intensity were varied to compare receptor sensitivity. The recordings did not identify the exact retinal layer of each impaled cell. The colored _Hasarius_ section locates the same type of layered organ, but cannot retrospectively assign a _Phidippus_ recording to one of its layers.""",
"""A light-sensitive receptor can encode stimulus strength through the amplitude of a graded voltage change. Depolarization names the direction of that change and does not, by itself, establish that the cell generates action potentials. ||| DeVoe used calibrated flashes and compared wavelength-dependent responses in individual cells. Electrical calibration expresses the recording in millivolts, while the flash duration expresses the time over which the receptor was stimulated. ||| The modern anatomical inset concerns Hasarius, and the physiology concerns Phidippus regius. A section makes the layered organization explicit, but only an independently localized recording could determine which layer contained a particular recorded receptor.""")
add('Ultraviolet receptors strongly favor short wavelengths','devoe75',[fig('d75_f2','Ultraviolet, green and dual-peaked spectral sensitivity.'),fig('n12_f2','Pigment spectra and layer localization in Hasarius.','A–C')],
"""**Spectral sensitivity** specifies how effectively different wavelengths evoke a response after stimulus intensity is accounted for. DeVoe found principal-eye cells in _Phidippus regius_ with maximum sensitivity near 370 nm, within the ultraviolet range. ||| These cells were more than four logarithmic units less sensitive at wavelengths beyond approximately 460 nm. A logarithmic sensitivity axis represents multiplicative changes, so the decline identifies strong spectral selectivity rather than a small difference in response amplitude. ||| The receptor class supplies a physiological channel for ultraviolet information. It does not establish ultraviolet color discrimination by the intact spider. Later pigment localization in _Hasarius_ places an ultraviolet-sensitive pigment in upper retinal layers, but that molecular result cannot identify the unlocalized cells in DeVoe's earlier recordings.""",
"""The sensitivity measurement compares the light required to evoke a specified electrical response. It therefore separates wavelength preference from an arbitrary difference in how bright the experimenter made each flash. ||| The ultraviolet class responds most effectively near 370 nanometers and loses sensitivity steeply toward longer wavelengths. A large separation on the logarithmic axis represents a large intensity difference. ||| A receptor channel is an input to perception, not proof of a perceptual ability. Behavioral color discrimination requires comparing wavelengths while controlling brightness, and the layer assignment in another species supplies complementary evidence rather than a direct localization of DeVoe's electrode.""")
add('Green receptors have a distinct sensitivity peak','devoe75',[fig('d75_f2','Green sensitivity peaks near 532 nm.'),fig('n12_f2','Rh1 pigment absorption and principal-eye localization.','A–C')],
"""DeVoe also recorded a green-sensitive principal-eye receptor class in _Phidippus regius_. Its spectral sensitivity peaked near 532 nm and followed the expected shape of a visual-pigment sensitivity curve over much of the measured range. ||| A **visual pigment** is a light-absorbing molecular complex containing an opsin protein. An **opsin** is the protein component that contributes to wavelength selectivity. Nagata and colleagues later purified the _Hasarius_ pigment Rh1 and measured an absorption maximum near 535 nm. ||| Receptor voltage sensitivity and purified-pigment absorption are complementary measurements. Their similar green peaks support a pigment-based contribution to green responses. The experiments involve different species and do not identify every molecular step between photon absorption, membrane current and the recorded voltage change.""",
"""The green receptor class differs from the ultraviolet class in the wavelength requiring the least light for a response. That distinction is physiological, because it comes from voltage measurements in individual cells. ||| A purified pigment's absorption spectrum identifies a molecular property. It does not measure the complete gain or kinetics of an intact photoreceptor, where absorption must influence membrane conductance before voltage changes. ||| The close green peaks in Phidippus physiology and Hasarius pigment measurements are consistent with related spectral channels. The evidence does not justify naming an unmeasured ion channel or transferring every cellular property between the species.""")
add('Dual-peaked cells differ in response timing','devoe75',[fig('d75_f1','Responses of ultraviolet, green and ultraviolet–green cells.'),fig('d75_f2','Dual-peaked sensitivity differs from the separate receptor classes.')],
"""Some _Phidippus regius_ cells responded strongly to both ultraviolet and green stimulation. Their spectral sensitivity had peaks near 370 nm and 525 nm, with relative ultraviolet-to-green sensitivity varying widely among the recorded cells. ||| In these **dual-peaked receptors**, ultraviolet responses were slower than green responses elicited from the same cell. The comparison held cell identity constant while changing wavelength, separating a difference within one receptor from a difference between two independently recorded populations. ||| The observed timing constrains accounts of signal generation in these cells. It does not establish two separately wired brain channels from that one receptor, or identify the molecular interaction responsible for the slower ultraviolet component. DeVoe also could not assign these cells to a particular retinal layer.""",
"""A dual-peaked sensitivity curve means that two separated wavelength regions can effectively activate the recorded cell. It does not mean the experiment recorded two cells simultaneously. ||| Ultraviolet and green flashes produced responses with different time courses in the same receptor. This within-cell comparison makes the kinetic difference distinct from the spectral differences between the ultraviolet-only and green-sensitive classes. ||| The data leave the cellular explanation unresolved. An electrical recording identifies the response and its timing, but not automatically the pigment distribution, the responsible conductance or the cell's postsynaptic targets.""")
add('Green pigment occupies both deeper retinal layers','nagata12',[fig('n12_f2','Rh1 in L1/L2 and ultraviolet-sensitive Rh3 in L3/L4.','A–C')],
"""**Immunolabeling** uses antibodies to identify the location of a molecular target in tissue. Nagata and colleagues combined principal-eye pigment expression measurements with antibody labeling in _Hasarius adansoni_ to connect spectral identity with retinal depth. ||| Green-sensitive Rh1 was present through L1 and L2, while ultraviolet-sensitive Rh3 occurred in L3 and L4. The blue-sensitive pigment Rh2 was not detected in the principal-eye expression assay under the tested conditions. Rh1's purified absorption peak was approximately 535 nm. ||| L2 therefore contains green-sensitive receptors even though green images are not sharply focused there. This arrangement makes green-image blur biologically available. Absence from one expression assay does not prove a pigment is absent under every condition, and molecular localization does not by itself establish how downstream neurons use the layers.""",
"""An antibody signal identifies where a protein is detected in the sectioned retina. Measuring expression and purified absorption supplies additional evidence about the identity and spectral properties of that protein. ||| The green-sensitive pigment spans the two deeper layers rather than occupying only the layer with the sharpest green image. The upper layers instead contain the detected ultraviolet-sensitive pigment. ||| The result revises a simple assignment of one color to one depth. A green-sensitive receptor can receive a blurred green image, allowing optical sharpness to carry information independently of the pigment's wavelength preference.""")
add('One principal eye can support accurate prey jumps','nagata12',[fig('n12_f1','Eye occlusion and measured jump distance.','A–D')],
"""**Stereopsis** estimates depth from differences between the views of two eyes. Nagata and colleagues tested whether two principal-eye views were necessary for accurate prey-directed jumps in _Hasarius adansoni_. ||| They covered both anterior lateral eyes and one principal eye, leaving a single principal eye available. Spiders still jumped accurately toward prey over the tested distances. Hunting observations also found no movement that would supply the proposed motion-parallax cue before these jumps. ||| **Motion parallax** is image displacement related to movement of the observer through space. Accurate performance with one principal eye weakens a requirement for binocular comparison in this preparation. The result does not, on its own, identify defocus as the remaining cue or exclude every possible monocular distance signal.""",
"""Removing one principal-eye view prevents the usual comparison between two principal images. Covering the anterior lateral eyes also restricts an alternative visual contribution during the test. ||| Jump distance remained closely related to prey distance. The behavior therefore does not require the two-eye geometry assumed by a stereoscopic explanation under these conditions. ||| The authors additionally examined whether the spider moved before jumping in a way that could generate useful motion parallax. These observations narrow the plausible cues, but a manipulation of image focus or wavelength is required to test the specific defocus account.""")
add('Red illumination makes prey jumps too short','nagata12',[fig('n12_f3bc','Measured jump distances under green and red light.','B, C')],
"""Nagata and colleagues compared _Hasarius adansoni_ jumping under approximately 520-nm green light and 630-nm red light. Wavelength changed the eye's optical focus while the experimenters measured the actual spider-to-prey distance and the ensuing jump. ||| Under green illumination, the average jump-to-target-distance ratio was approximately 1.0. Under the initial red condition it was approximately 0.90: spiders usually jumped short of the target. The recorded distances extended across the centimeter-scale hunting range. ||| A wavelength-dependent motor error supports a visual distance estimate affected by chromatic defocus. The result does not establish a red-sensitive receptor class or a preference for red prey. Green-sensitive Rh1 can absorb red light less efficiently, while the red light forms its image at a different optical depth.""",
"""The target distance was measured separately from jump distance. A ratio near one corresponds to a jump reaching the target; a ratio near 0.90 corresponds to an undershoot relative to that same target distance. ||| Red illumination changes optical focus as well as pigment stimulation. The observed shortening agrees with the direction predicted if the spider interprets increased blur using a relationship appropriate to green light. ||| Responding under red illumination is not the same as possessing a red-peaking pigment. A pigment's sensitivity extends beyond its peak, so sufficient long-wavelength light can still activate green-sensitive receptors.""")
add('A brighter red control preserves the distance error','nagata12',[fig('n12_f3bc','A sixfold red-light increase does not remove undershooting.','B, C')],
"""Changing wavelength also changes the effectiveness of light at activating a visual pigment. Nagata and colleagues adjusted the initial green and red conditions to stimulate purified Rh1 with comparable efficiency, then increased the red intensity sixfold as an additional control. ||| The jump-to-target-distance ratio remained approximately 0.89 under the brighter red condition, close to the approximately 0.90 ratio in the initial red condition. Greater red intensity therefore did not restore the green-light accuracy. ||| This control argues against reduced photon capture as a sufficient explanation of the short jumps. It supports a wavelength-dependent optical contribution. It does not identify the downstream computation, and intensity matching for purified Rh1 is not a complete measurement of every receptor's activity in the intact animal.""",
"""A dimmer effective stimulus could impair behavior even without a change in optical depth information. The pigment-based adjustment and the brighter-red condition address that alternative explanation. ||| Increasing red intensity sixfold left the direction and approximate magnitude of the error intact. The result makes a simple reduction in effective brightness inadequate to account for the wavelength effect. ||| The control has a defined scope. Purified-pigment efficiency constrains photon absorption, while the intact receptor's voltage, adaptation and downstream gain were not directly measured during these jumps.""")
add('Defocused images provide a candidate distance signal','nagata12',[fig('n12_f1','Retinal depths and the authors’ proposed defocus mechanism.','A–D'),fig('n12_f3bc','Published optical predictions alongside jump measurements.','B, C')],
"""An image's blur changes with object distance when its receptor layer lies away from the sharp-image plane. Nagata and colleagues proposed that the amount of green-image defocus in L2 supplies an absolute distance cue in _Hasarius adansoni_. ||| Red light has a longer focal length in the measured optical system. Its additional blur would be interpreted as a closer target if the spider applies a green-calibrated relationship. The authors' optical predictions agreed with the direction of the observed red-light undershooting. ||| Comparing a sharper L1 image with a defocused L2 image was proposed as one possible implementation. The study explicitly lacked neural evidence for such a comparison. The anatomical layers, wavelength manipulation and jump measurements support the cue, while the comparing cells, synapses and ion channels remain unidentified.""",
"""Blur depends on both object distance and the position of the receptor layer relative to focus. A fixed optical system can therefore convert distance into a measurable property of the retinal image. ||| The red-light prediction uses the same layered geometry but a different focal length. Under a green-calibrated interpretation, greater defocus produces an underestimate of prey distance and a shorter jump. ||| The original paper supplies the optical curves. Agreement with those curves does not determine whether two layers are compared, which neurons perform a comparison, or what receptor and channel mechanisms generate their responses.""")
add('A retinal filter shifts green sensitivity toward red','zurek15',[fig('z15_f1bc','A localized red filter in the principal retina.','B, C'),fig('z15_f1ghi','Measured spectra and predicted filtered sensitivity.','G–I')],
"""A **spectral filter** changes which wavelengths reach a receptor by absorbing some more strongly than others. Zurek and colleagues identified a red, long-pass filter in part of the principal-eye retina of _Habronattus pyrrithrix_. A long-pass filter preferentially transmits longer wavelengths. ||| The species has measured pigment peaks near 377 nm and 530 nm. Combining the green pigment's sensitivity with the measured filter transmission predicts a shifted sensitivity peak near 626 nm in filtered receptors, without requiring a third red-peaking opsin. ||| The filter supplies a physical route to an additional spectral channel. The predicted red curve is an author-published calculation from measured optical properties, not a directly recorded red-cell response. This specialization should not be assigned to every jumping-spider genus.""",
"""The filter acts before photon absorption by the pigment. Removing more short-wavelength light changes the effective sensitivity of an otherwise green-sensitive receptor. ||| The paper measured pigment properties and the filter's spectral transmission. The published predicted curve combines those measurements and reaches its peak near 626 nanometers. ||| An additional effective spectral channel can arise without an additional opsin class. The prediction concerns the filtered receptor population and does not establish behavioral color discrimination or a directly measured downstream red channel.""")
add('The filter covers a restricted high-acuity region','zurek15',[fig('z15_f1de','Layered retina and the restricted red-filter region.','D, E')],
"""The red filter of _Habronattus pyrrithrix_ is localized rather than spread across the entire principal retina. Unstained tissue sections retained the filter's native color, allowing its position to be compared with the receptor layers. ||| The colored region lies in a restricted central portion associated with L1 receptors. The published horizontal and coronal preparations used 14-µm sections; the layered retinal panels include 20-µm scale bars. This spatial arrangement permits filtered and unfiltered receptor populations within the same eye. ||| Filter localization makes spectral sampling depend on target alignment with a small retinal region. The authors found the feature in both sexes and other sampled _Habronattus_ species, while sampled _Salticus_ and _Phidippus_ lacked it. These comparisons identify a lineage-associated specialization rather than a universal salticid design.""",
"""An unstained section retains the pigment's natural red appearance, so the color is part of the tissue rather than an added label. The section geometry locates that filter relative to the tiered receptor arrangement. ||| Because the filter covers only part of the retina, not every principal-eye receptor receives the same spectrum. A target's position relative to that region can change which filtered and unfiltered signals are available. ||| The taxonomic comparison limits generalization. The sampled Habronattus species share the feature, while the sampled representatives of other genera do not, so the mechanism cannot simply be transferred to Phidippus physiology or Hasarius defocus experiments.""")
add('Filtering trades photon capture for spectral separation','zurek15',[fig('z15_f1ghi','Filter absorbance, transmission and predicted receptor channels.','G–I')],
"""**Trichromacy** requires three functionally distinguishable spectral channels, rather than three differently colored structures. Zurek and colleagues proposed ultraviolet, unfiltered green and filtered red channels for _Habronattus pyrrithrix_ from pigment and filter measurements. ||| The predicted green and red sensitivities separate because the filter removes much of the light otherwise absorbed by the green pigment. The same absorption that shifts sensitivity also reduces available photons, creating a potential cost under dim illumination. ||| The paper establishes the optical mechanism and its spectral potential. It does not directly measure three downstream opponent channels or demonstrate brightness-controlled discrimination among all relevant colors. **Spectral opponency**, comparison between wavelength channels, would require additional neural evidence before assigning a particular color computation to the brain.""",
"""A third effective receptor sensitivity can be produced by filtering an existing pigment class. Trichromatic potential therefore does not require three different opsin proteins in this case. ||| Absorbing short wavelengths improves spectral separation but leaves fewer photons available to the filtered receptors. The proposed low-light cost follows from those optical properties; the paper does not measure a complete behavioral sensitivity limit under every illumination. ||| Color perception additionally requires the animal to use differences between channels. Optical sensitivity curves alone do not identify an opponent neuron or prove a specific perceptual discrimination.""")
add('Six muscles reposition the principal-eye retina','land69b',[fig('b69_f2','Six principal-eye muscles around the movable retinal tube.')],
"""The principal-eye retina is moved by muscles attached to its optical tube. Land's dissections in _Metaphidippus_ identified six muscles associated with each principal eye, providing a mechanical basis for internal eye movements behind a fixed external lens. ||| Four muscles displace the retinal assembly in horizontal or vertical directions. Two thinner bands curve around the tube and can rotate it about its viewing axis. **Torsion** is this rotation around the optical axis, distinct from shifting the direction of gaze. ||| The muscle arrangement makes translation and rotation physically possible. Attachment geometry does not determine the precise activation sequence during tracking, and the dissections do not identify the transmitter or postsynaptic receptor at the neuromuscular junction. Behavioral movement records are needed to associate this anatomy with particular responses.""",
"""The large anterior lens remains fixed while the retina changes position inside the eye. Muscles acting on the tube can therefore move the sampled image without a conspicuous rotation of the external eye. ||| Four displacing muscles and two wrapping bands supply different mechanical actions. Rotating the retina changes the orientation of its receptor rows relative to a target, whereas horizontal displacement changes the direction sampled. ||| Land established the muscle anatomy directly. The mechanical arrangement supports possible actions but does not reveal motor firing patterns, synaptic chemistry or the exact force contributed by each muscle during a recorded scan.""")
add('Six motor axons connect to the eye muscles','land69b',[fig('b69_f4','Oculomotor axons and their muscle terminations.')],
"""A **motor axon** carries neuronal output to a muscle. Land traced an oculomotor nerve containing six axons toward the six principal-eye muscles, linking the movable retinal tube to a dedicated motor supply. ||| Histological tracing associated each axon with one muscle. The nerve and muscle arrangement separates the anatomical route for controlling retinal displacement from the photoreceptor fibers carrying sensory input toward the first optic glomerulus. ||| A one-to-one anatomical association between axons and muscles does not establish a six-command coding scheme for gaze. The study did not record these axons during scanning or identify their transmitter, receptor or membrane conductances. Sensory-triggered eye movements therefore require additional, unmeasured circuitry between visual input and this motor output.""",
"""Sensory axons carry information inward from the retina, while motor axons deliver commands to the muscles that move it. Land distinguished these routes anatomically rather than treating every fiber beside the eye as a sensory fiber. ||| Six axons could be traced to the six muscles. That organization identifies the final motor supply but leaves the origin of each movement command unresolved. ||| To establish motor coding, the axons would need to be recorded or manipulated during an eye movement. Anatomical tracing alone cannot identify how a target's position becomes a muscle activation pattern, or which molecular receptors mediate the resulting contraction.""")
add('Ophthalmoscopy measures motion of the internal retina','land69b',[fig('b69_f1','Ophthalmoscopic recording apparatus.','a, b'),fig('b69_f2','The movable retinal tube and muscle attachments.')],
"""**Ophthalmoscopy** views structures inside an eye through its own optics. Land adapted this method to observe the principal-eye retina while a restrained spider viewed controlled targets, making internal motion measurable despite the fixed external lens. ||| The retinal field was followed relative to a reference, and position was recorded over time. Calibration related record displacement to angular movement; horizontal traces included a 10° reference and time marks, allowing movement amplitude and duration to be compared. ||| The method recorded retinal position, not receptor voltage or motor-neuron spikes. Restraint and the apparatus also differed from free hunting. Nevertheless, separate target and movement records distinguished spontaneous activity, rapid repositioning, tracking and scanning within the same anatomical organ.""",
"""The spider's own lens provides optical access to its internal retina. Following the retinal field through that lens allows the experimenter to record motion that is otherwise difficult to see externally. ||| A calibrated position trace preserves the time course of movement. Its angular reference concerns displacement of the sampled visual field, while the time marks identify how quickly that displacement occurs. ||| These are motor-output measurements. They establish the movements and their stimulus relationships without measuring the sensory or motor neurons responsible for generating them.""")
add('Spontaneous shifts differ from visual saccades','land69b',[fig('b69_f7','Spontaneous movements and stimulus-evoked saccades.','a, b')],
"""A **saccade** is a rapid shift that repositions a visual sampling region. Land observed principal-eye movements both without an effective target and after small target displacements, distinguishing ongoing motor activity from visually evoked repositioning. ||| Spontaneous activity included irregular shifts and periods of rapid movement. It persisted when the visual field was blank and could occur after eyes were covered. Small stimulus movements instead evoked abrupt retinal shifts toward the target followed by a slower return. ||| Persistence without ordinary visual input supports an internally generated component of eye movement. The targeted responses establish visual influence on repositioning, but neither result identifies the central generator or the error signal. A spontaneous shift and a visually evoked saccade should not be treated as the same stimulus-dependent process.""",
"""Land compared the eye's activity under different visual conditions rather than assuming that every movement followed an external object. Blank fields and eye covering tested whether a visible target was required. ||| Target displacement produced an abrupt directed movement, while spontaneous records were more variable and could continue without such stimulation. The slow return following a target-evoked shift also differs from a sustained tracking response. ||| These observations distinguish response classes from their motor traces. They do not identify the neurons that generate spontaneous activity or determine whether every observed shift has the same central origin.""")
add('Moving targets can recruit retinal tracking','land69b',[fig('b69_f7','Spontaneous and target-directed retinal shifts.','a, b'),fig('b69_f8','Horizontal and torsional components of eye movement.','a, b')],
"""**Tracking** maintains a visual target near a sampled retinal region as its position changes. Land distinguished target-linked principal-eye tracking from spontaneous movement and the repeated scans performed over a relatively stationary object. ||| Target movements could evoke retinal repositioning when visible to the principal eyes or the anterior lateral eyes. This observation connects a broad-field sensory input to movement of the restricted principal-eye retina without requiring the entire spider to turn. ||| A visually guided change in retinal position establishes functional coordination between sensory input and the eye motor system. It does not identify the intervening neurons, prove a continuous velocity-matching controller or establish that principal and lateral inputs make identical contributions. Later eye masking can test the dependence on each input more directly.""",
"""Retinal tracking concerns movement inside the principal eye, while body orientation moves the whole animal. Both can change where a target falls in the visual field, but they are different motor outputs. ||| Land could elicit directed shifts through stimulation visible to different eye pairs. That result indicates that principal-eye motor control is not restricted to information initially detected by the principal retina itself. ||| The intervening circuit was not recorded. Eye-specific manipulations are required to distinguish which pair supplies target information under a particular tracking task, and a position response alone does not establish perfect matching of target speed.""")
add('Scanning combines horizontal movement with torsion','land69b',[fig('b69_f8','Published records separating scan translation and torsion.','a, b')],
"""**Scanning** is repeated retinal movement over a target rather than a single shift toward it. Land recorded horizontal oscillations together with a slower rotation of the principal-eye retina about its optical axis during target examination. ||| Horizontal scans typically had periods of approximately 1–2 s. Torsional excursions extended through roughly 50° and developed over approximately 5–15 s. The distinct time scales allow receptor rows to sweep across a target while their orientation changes more slowly. ||| These movements alter the spatial samples delivered by a small retinal array. Their timing supports an active sampling strategy, but it does not establish what features a downstream neuron extracts. The electrical responses of individual receptors or feature-selective interneurons were not measured in these movement records.""",
"""Horizontal scanning changes the sampled location, while torsion changes the orientation of the sampling array. Land recorded both components separately rather than compressing the behavior into one undifferentiated eye movement. ||| The horizontal cycles recur more rapidly than the large torsional excursion. A target can therefore be swept repeatedly at one orientation before the receptor rows reach a substantially different orientation. ||| This motor pattern constrains proposed visual computations. Establishing an edge detector, however, would require evidence about neuronal responses to defined contours, not just a record of retinal motion.""")
add('Target width changes scan amplitude','land69b',[fig('b69_f9','Scanning during targets of five angular widths.'),fig('b69_f12','Published courtship and prey stimuli discussed in Land’s hypothesis.','a, b')],
"""Land varied target width while measuring principal-eye scanning. The published records include targets 1.4°, 4.1°, 7.0°, 9.2° and 12.3° wide, separating the size of the visual object from the retina's movement response. ||| For targets narrower than about 10°, horizontal scan amplitude was close to target width, with a minimum excursion near 2° even for a much smaller target. Wider targets were not always swept completely. Torsional excursion changed less systematically with width. ||| Land proposed that changing receptor-row orientation could aid contour analysis during these scans. That proposal drew on stimulus shapes known to alter behavior, but no line-selective neuron was recorded. Width-dependent scanning is measured evidence; feature extraction by a particular detector remains a mechanistic hypothesis.""",
"""Target width changes the amount of visual space occupied by the object. The scans expanded for many larger targets, but a lower movement limit meant that very small targets did not produce proportionately tiny scans. ||| The horizontal and torsional components did not simply scale together. Their different dependence on target width supports distinct contributions to sampling rather than one fixed eye-motion pattern. ||| Land's contour-analysis account is a proposed use of this sampling geometry. The reproduced stimulus forms belong to the published article; they support the historical reasoning but do not constitute recordings of the proposed detector.""")
add('Lateral eyes guide sequential body saccades','zn12b',[fig('zn12_f2','Saccade characteristics across horizontal target position.')],
"""Zurek and Nelson isolated anterior lateral vision in _Servaea vestita_ by covering the other eye pairs. A 4° dot moving at 9°/s elicited body turns measured while the spider remained fixed above a rotating ball. ||| Orientation consisted of a sequence of saccades rather than one smooth turn. The first response usually began after the entire dot entered the visible field. Near lateral target positions of 25–30°, the response rate reached approximately three saccades per second under this stimulus condition. ||| Body saccades redirect the animal toward a moving target and can place it nearer the principal-eye field. Their timing differs from Land's slower internal scans. The result establishes the anterior lateral contribution to a defined orienting task, not a complete model of free-moving prey interception.""",
"""The assay isolates lateral visual input and records the spider's attempted body rotations. It therefore differs from an ophthalmoscopic measurement of motion inside a principal eye. ||| A series of discrete turns follows the moving dot. The onset relationship to the dot's trailing edge indicates that target entry into the field matters, while the rate varies across target position. ||| The measured maximum rate is tied to a four-degree dot moving at nine degrees per second. It should not be assigned to every natural target or interpreted as a fixed frequency of the eye muscles.""")
add('Larger orienting saccades are executed faster','zn12b',[fig('zn12_f3','Magnitude, speed and duration vary with target position.','a–d')],
"""The **angular error** in an orienting task is the separation between the target direction and the animal's forward axis. Zurek and Nelson related body-saccade magnitude, velocity and duration to target position in lateral-eye-isolated _Servaea vestita_. ||| Targets farther to the side elicited larger and faster saccades. At positions beyond approximately 20°, the turns increasingly undershot the target direction. Higher speed partly limited the additional duration required for a larger movement, although it did not remove all duration differences. ||| A sequence of undershooting movements can progressively center a moving target. These relationships constrain motor control without proving a specific error-correcting neural circuit. The records are attempted body rotations on a ball and do not measure the forces or trajectories of an unrestricted spider.""",
"""Saccade magnitude is the angle turned, velocity is its rate in degrees per second, and duration is the time occupied by that movement. The three variables describe different aspects of the same motor action. ||| Larger target eccentricities produced larger movements that were also faster. This relationship reduces how much longer a large turn takes, but the turns still increasingly fall short of the target at more lateral positions. ||| Repeated saccades can reduce the remaining error. The behavioral relationship does not identify the comparator neurons, and ball rotations should not be mistaken for an unconstrained locomotor trajectory.""")
add('A rotating ring removes feedback from the body turn','land71',[fig('l71_f2a','Apparatus holding the body while the feet rotate a ring.','a')],
"""**Visual feedback** is information about the consequences of an action returning through vision. Land tested orienting turns in _Metaphidippus_ while holding the spider's body fixed and allowing its feet to rotate a lightweight ring. ||| A moving spot in the surrounding drum triggered attempted turning. The ring rotated beneath the feet, but the spider's eyes did not turn relative to the visual surround. Target movement and ring position were measured separately with calibrated recording devices. ||| This arrangement removed the retinal image motion normally produced by the animal's body rotation. A response could therefore be tested without the usual visual reduction of target error. The apparatus isolates feedback from that turn; it does not eliminate every possible sensory signal from the feet or body.""",
"""In a freely turning spider, the target shifts across the retina as the body rotates toward it. That change can provide a signal for correcting or stopping the movement. ||| Land held the body still while the feet moved the ring. The attempted turn was recorded, but it did not create the normal change in target direction relative to the eyes. ||| Separate stimulus and ring traces make the distinction measurable. The design specifically removes visual consequences of body rotation, while other signals associated with movement or contact can remain available.""")
add('Complete turns approximate the initial target angle','land71',[fig('l71_f5','Attempted turn magnitude versus target angle.')],
"""An **open-loop movement** proceeds without correction from the usual feedback about its ongoing effect. Land compared attempted ring turns with the target's angular position while the spider's body remained fixed. ||| Many responses were complete turns whose magnitude closely approximated the initial target angle. Other responses were much smaller partial turns and did not align the forward axis with the target if interpreted as ordinary body rotations. Both occurred in the same preparation. ||| Accurate complete turns support a motor command based on the target position available before movement. They do not prove that natural turns never use visual feedback. The coexistence of complete and partial responses also prevents every movement from being interpreted as a perfectly specified orienting command.""",
"""A complete turn is defined by its relation to the target direction, not simply by being a large movement. Target angle varies, so the expected complete movement also varies. ||| Many recorded turns closely matched that angle despite the absence of the usual retinal consequences of body rotation. Smaller responses formed a separate class that often left a substantial target error. ||| The preparation establishes that accurate turning can proceed without that feedback. It does not establish that feedback is absent or unhelpful during unrestricted orientation, where the eyes and body actually move through the environment.""")
add('Turning in darkness excludes another visual correction','land71',[fig('l71_f7','Complete-turn errors and partial-turn magnitudes.','a, b'),fig('l71_f2a','The ring preparation used for feedback controls.','a')],
"""The fixed-body ring assay still allowed a spider to see the ring or its feet, potentially providing indirect visual information about its movement. Land addressed this remaining route by extinguishing illumination immediately after target motion ceased. ||| The stimulus normally moved 5° over 200 ms. After the light was switched off, spiders turned in darkness, and complete-turn accuracy remained comparable to the illuminated condition. Visual observation of the ring or feet was therefore not necessary for those accurate responses. ||| The control strengthens an open-loop account of the tested turns. It does not remove nonvisual feedback or identify the neural representation of target angle. Complete and partial movements remained behaviorally distinct, and habituation could alter which response was selected.""",
"""A fixed body removes retinal motion caused by the turn but does not automatically prevent the animal from seeing its feet move. Switching the light off addresses that separate visual route. ||| The spider received the target information before darkness and completed its attempted turn afterward. Accurate complete responses under those conditions support a command that can persist after the visual stimulus is no longer available. ||| The experiment does not eliminate touch or internal movement signals. It also leaves the command's neural location unresolved, so behavioral accuracy cannot identify a particular comparator cell or motor transmitter.""")
add('Lateral-eye masking disrupts principal-eye tracking','jakob18',[fig('j18_f1','Principal-eye movements with anterior lateral eyes available or masked.','A–E')],
"""Jakob and colleagues measured the internal principal-eye movements of restrained _Phidippus audax_ with an eye tracker. Moving disks were presented before and after the anterior lateral eyes were covered, testing whether the lateral pair guides the principal retina. ||| Disk diameters were 3°, 4° and 5°, with speeds of 2.77, 7.60 and 15.13°/s. Principal retinas followed moving targets when the lateral eyes were available. Covering that pair disrupted the target-linked movements under the same general stimulus conditions. ||| The manipulation supports a causal contribution of anterior lateral input to principal-eye tracking. It does not identify the connecting neurons or prove that all principal-eye movements require lateral vision. The measured motor output is internal retinal motion, rather than the body saccades in the _Servaea_ ball assays.""",
"""Eye tracking records the position and orientation of the principal retinas while the spider's body remains restrained. Changing lateral-eye availability tests a sensory contribution to that internal motor output. ||| Several target sizes and speeds reduce dependence on one particular moving-dot condition. The mask affected the relationship between target motion and retinal motion. ||| The result supplies stronger evidence about input dependence than observing coordination alone. It still leaves the intervening circuit unresolved and must be distinguished from an experiment that measures whole-body orientation.""")
add('Masking leaves stationary-target examination available','jakob18',[fig('j18_f1','Moving-disk tracking and stationary-target retinal trajectories.','A–E')],
"""A movement deficit can arise from sensory loss or from damage to the motor apparatus. Jakob and colleagues compared moving-target tracking with examination of stationary cricket and oval stimuli after anterior lateral masking in _Phidippus audax_. ||| Principal-eye scanning persisted for stationary targets even when the moving-disk tracking relationship was disrupted. The retina could still move, so the mask did not simply abolish every principal-eye motor action. Cricket and oval stimuli also recruited different degrees of target examination. ||| Preserved scanning narrows the interpretation toward loss of a guiding visual contribution rather than complete motor failure. It does not exclude subtler effects of masking, and the comparison does not establish which principal-eye feature signals distinguish a cricket from an oval.""",
"""A stationary target can be examined by moving the principal retina across it. That movement remains possible without lateral-eye guidance of a moving target, so scanning and tracking have different sensory dependencies. ||| The stationary cricket and oval conditions test residual retinal mobility and target examination. They are a behavioral control for a broad loss of the motor output. ||| The control does not identify the visual features driving the remaining scans. Different stimulus shapes can change examination while the neurons responsible for that distinction remain unrecorded.""")
add('Retinal position and torsion are separate readouts','jakob18',[fig('j18_f1','Distance, angle and stimulus-relative measures of retinal movement.','A–E')],
"""Jakob and colleagues quantified more than one aspect of principal-eye movement. Retinal separation and position describe where the sampled regions move, while retinal angle describes torsion, the rotation of the sampling array about the viewing axis. ||| The moving-target position traces were reported in the eye tracker's pixel coordinates. Stationary cricket stimuli elicited more examination and torsional movement than oval stimuli when lateral vision was available. These measures concern internal retinal behavior in restrained _Phidippus audax_. ||| Pixel displacement must not be relabeled as an angle without calibration. Distinct positional and torsional readouts also prevent every increase in eye movement from being called improved tracking. The data establish stimulus-dependent motor patterns while leaving the principal-eye feature representation and the underlying control signals unresolved.""",
"""Two retinas can change their relative distance without rotating by the same amount. Conversely, a retina can change its torsional angle while sampling near the same target location. The eye tracker distinguishes these components. ||| The published position axis uses pixels, which are coordinates in the recording system. Angular units are used for the presented target, but they cannot simply be transferred to every eye-position trace. ||| Greater torsion during cricket examination is a measured response difference. It does not prove that a specific contour detector recognizes prey or that every larger retinal movement improves target localization.""")
add('Principal-eye routes connect to the arcuate body','steinhoff20',[fig('s20_f1','AM1, AM2 and connecting processes to the arcuate body.','a–f')],
"""The **arcuate body** is an unpaired brain neuropil associated with visual pathways. Steinhoff and colleagues mapped the brain of _Marpissa muscosa_ using tissue sections, three-dimensional imaging and molecular labeling of neuronal processes. ||| Principal-eye input reaches AM1, the first-order principal-eye neuropil. A thick tract connects AM1 with AM2, and a thinner tract links AM2 to the arcuate body. Antibodies against **synapsin**, a presynaptic protein, marked neuropils; **tubulin**, a structural protein, marked neuronal processes. ||| This anatomy supplies candidate routes from retinal signals toward central visual processing. Presynaptic-protein labeling and visible connecting processes do not establish every synapse, response sign or computation. The preparation maps _Marpissa_ anatomy rather than recording the functional identity of the cells sampled in another species.""",
"""First-order and second-order refer to successive anatomical processing regions reached from the retina. The principal pathway contains a clear connection from AM1 to AM2 and another connection toward the arcuate body. ||| Synapsin labeling identifies regions rich in presynaptic machinery, while tubulin labeling makes processes and tracts easier to trace. Their combined signals provide more information than either label alone. ||| A tract establishes an anatomical route but not the activity transmitted along it. The study does not determine whether a particular connection excites or inhibits its target, nor whether it compares retinal layers for depth estimation.""")
add('Secondary-eye inputs reach shared and distinct neuropils','steinhoff20',[fig('s20_f6','Anterior lateral, posterior lateral and posterior median routes.','a–d'),fig('s20_f11','The authors’ published summary of visual pathways.','a, b')],
"""The **posterior lateral eyes** provide another lateral visual input, while the smaller **posterior median eyes** form a distinct pair. In _Marpissa muscosa_, Steinhoff and colleagues traced these secondary-eye routes rather than assuming they all share one motion pathway. ||| Anterior lateral and posterior lateral inputs reach separate first-order neuropils, AL1 and PL1, then a shared second-order region, AL2/PL2. Connections continue toward the **mushroom body**, a paired brain structure, through its stalk-like peduncle. Additional processes reach the neighboring region L2. ||| Posterior median input instead reaches PM1 and a tract apparently ending near the arcuate body, without an identified second-order visual neuropil. **Convergence** is the arrival of multiple inputs at a processing region. This architecture permits both separation and convergence. It does not establish the exact integration computed in L2, the mushroom body or the arcuate body.""",
"""A shared second-order neuropil can receive information that arrived through two different first-order regions. In Marpissa, the anterior and posterior lateral routes converge anatomically in AL2/PL2. ||| The mushroom-body peduncle and neighboring L2 have connections with this secondary-eye pathway. The posterior median route differs, making a blanket assignment of all secondary eyes to one identical circuit inaccurate. ||| The published pathway summary is the authors' diagram, retained without reconstruction. Anatomical convergence is compatible with information integration but does not measure a nonlinear response or identify the behavior controlled by each connected region.""",
figure_arrangement='side-by-side',primary_figure_width=3.3)
add('Small brain openings permit extracellular recordings','menda14',[fig('m14_f1','Recording approach, arcuate-body anatomy and spike separation.','A–D')],
"""An **extracellular recording** detects electrical signals near neurons without placing the electrode inside a cell. Menda and colleagues developed stable brain recordings in _Phidippus audax_ by advancing a glass-insulated tungsten electrode through a small cuticular opening. ||| Openings of approximately 100–200 µm reduced the fluid loss that complicates access to a pressurized spider body. Visual stimulation could be paired with recordings lasting hours. Electrode positions were in or near the arcuate body, with anatomical labeling used to locate the recording region. ||| A **spike**, or action potential, is a brief neuronal electrical event. **Spike sorting** separates candidate units by waveform features in the extracellular signal. It supports analysis of individual response patterns but does not identify a cell's anatomy or transmitter. The restrained preparation records central visual activity without measuring the complete neural sequence during an unrestricted predatory jump.""",
"""A spider's body pressure makes a large opening particularly disruptive. A small puncture permits access while reducing fluid loss, allowing repeated visual stimulation during a stable recording. ||| Extracellular spikes are detected outside the cells. Waveform-based sorting can distinguish candidate units, but the sorted unit is not automatically a named anatomical neuron. ||| The recording region lies in or near the arcuate body. That location relates the physiology to central visual anatomy without proving that every sampled unit belongs to the same pathway or performs the same visual computation.""")
add('Central units respond to particular moving trajectories','menda14',[fig('m14_f2','Repeated target trajectories, firing-rate traces and spike rasters.','A–C'),fig('m14_f1a','The brain region approached by the recording electrode.','A')],
"""Menda and colleagues presented a small prey-like moving target while recording central units in _Phidippus audax_. A **spike raster** records action-potential times across repeated presentations, allowing temporal response consistency to be assessed. ||| The 1.5° target followed controlled trajectories at a display update rate of 29 frames/s. Repeated presentations evoked activity associated with particular parts of the sequence. Target position, velocity and direction were known independently of the recorded spikes. ||| Simple descriptions based on position or motion alone did not fully predict every response. The results support complex visual selectivity in central units, but not a uniquely defined prey-recognition circuit. A repeated response to one trajectory does not establish invariance across all target shapes, speeds or spatial positions.""",
"""Repeated trajectories allow a response to be distinguished from unrelated fluctuations in firing. The target sequence is controlled while the spike times are measured independently. ||| Position, velocity and direction describe different properties of the target. A unit can depend on more than one of them, so a response that exceeds a simple model does not automatically identify a new named computation. ||| The anatomy identifies the approached central region. The extracellular unit's complete morphology remains unknown, and its trajectory dependence does not establish that it selectively responds to natural prey in every behavioral context.""")
add('An intact fly image exceeds a scrambled stimulus','menda14',[fig('m14_f3','Natural and scrambled stimuli with central-unit responses.','A–D'),fig('m14_f1a','Arcuate-body anatomy near the recording site.','A')],
"""Menda and colleagues compared fly, spider and scrambled-fly images at controlled visual positions. **Scrambling** rearranged image parts while preserving elements of the original stimulus, testing whether responses depended on their organization rather than simply the presence of dark features. ||| In the published example unit, a dorsal fly image evoked a median 14.9 spikes/s, a lateral fly image 10.0 spikes/s and the scrambled fly 5.9 spikes/s. Responses also varied with position; images were tested at horizontal offsets of 5°, 15° and 25° on either side. ||| Greater activity for an intact prey configuration supports sensitivity to spatial organization. These values describe a particular recorded unit, not every spider neuron. The assay does not establish conscious recognition, identify an innate fly detector or prove that the same response directly commands an attack.""",
"""An intact and a scrambled stimulus can share many local image elements while differing in their arrangement. The comparison therefore addresses configuration sensitivity more directly than a contrast between a fly image and a blank field. ||| The example unit responded more strongly to the intact dorsal fly than to the scrambled stimulus. Its response also depended on position, so category preference cannot be separated completely from spatial tuning. ||| The firing rates belong to the published unit. They should not be generalized to a universal prey-detection cell, and the experiment did not record a motor command that could establish direct control of jumping.""")
add('One receptive field requires both eye systems','menda14',[fig('m14_f4','Eye occlusion changes the measured spatiotemporal receptive field.','A–D'),fig('m14_f1a','Anatomical context of the central recording.','A')],
"""A **spatiotemporal receptive field** describes how stimulation at different positions and times relates to a neuron's response. Menda and colleagues estimated this relationship using rapidly changing checker patterns while selectively covering principal or lateral eyes in _Phidippus audax_. ||| For one recorded unit, an organized receptive field emerged with both systems available but was not recovered with either system alone. The response-related pattern occupied a temporal interval approximately 80–160 ms before the measured spikes. Internal-pattern controls reduced a display-related correlation. ||| The dependence supports nonlinear convergence of principal and secondary visual inputs at or before this unit. It does not identify the synapses, receptor types or exact number of processing stages. The functional result in _Phidippus_ complements, but cannot be directly equated with, the anatomical pathways mapped in _Marpissa_.""",
"""The checker stimulus varies many positions over time, and its preceding pattern is related to recorded spike times. The resulting receptive field contains both a spatial arrangement and a time dependence. ||| Removing one eye system changed whether a structured field could be recovered. A unit requiring both inputs is not adequately explained by a simple independent response from either one alone under the tested conditions. ||| The eighty-to-one-hundred-sixty-millisecond interval constrains timing without counting synapses. Combining this physiology with anatomy from another species supplies a comparative account, not an identified cellular circuit.""")
add('Histamine labels sensory axons and terminals','steinhoff20',[fig('s20_f8','Histamine immunoreactivity in secondary-eye axons and terminals.','a–c'),fig('s20_f6','First-order neuropils receiving those sensory inputs.','a–d')],
"""A **neurotransmitter** is a chemical released by a neuron to influence another cell. Steinhoff and colleagues used histamine antibodies to examine sensory axons and their terminal regions in _Marpissa muscosa_, linking a candidate transmitter to mapped visual anatomy. ||| Histamine immunoreactivity was prominent in secondary-eye axons and first-order terminal regions, including AL1, PL1 and PM1. **Immunoreactivity** means that the tissue binds an antibody recognizing the target; it is evidence of molecular presence at those locations. ||| The labeling supports a histaminergic photoreceptor pathway but does not measure release during light stimulation. It also does not establish the postsynaptic histamine receptor, its ion selectivity or whether the resulting current excites or inhibits a particular target. Those cellular steps must remain unresolved in this mapped spider circuit.""",
"""The candidate transmitter is localized in the processes carrying sensory information into the brain. Its presence in terminal regions is consistent with a chemical role in transmission from photoreceptors. ||| Antibody labeling measures molecular recognition in tissue. It does not measure transmitter release, receptor activation or membrane current during a visual stimulus. ||| Connecting the chemical label to a complete mechanism would require identifying the postsynaptic receptor and measuring its effect on neuronal activity. A receptor or ion channel known from another animal cannot be assigned to these spider synapses without direct evidence.""")

# Tall recordings retain their height; each additional image has its own credit.
for i in [6,10]:
 s=SL[i]
 if s['layout']=='figures-right':s.update(figure_arrangement='side-by-side',primary_figure_width=4.05)
# Enlarge primary evidence and anatomy after reviewing every exported slide.
SL[24].update(figure_arrangement='side-by-side',primary_figure_width=3.15)
for i,k,description,panel in [
 (28,'b69_f9','Scanning during targets of five angular widths.',''),
 (38,'s20_f6','Anterior lateral, posterior lateral and posterior median routes.','a–d'),
 (42,'m14_f4','Eye occlusion changes the measured spatiotemporal receptive field.','A–D')]:
 s=SL[i];s.pop('figures');s.update(layout='figure-right',figure=fig(k,description,panel))
 for key in ['figure_arrangement','primary_figure_width','primary_figure_height']:s.pop(key,None)
SL[8]['primary_figure_height']=1.65
SL[40]['primary_figure_height']=2.1
SL[41]['primary_figure_height']=2.7
SL[43]['primary_figure_height']=1.85
TK={'items':[
 {'lead':'Complementary eye systems','text':'Lateral eyes support detection and orientation; movable principal retinas provide restricted, fine-scale visual sampling.'},
 {'lead':'Layered principal retina','text':'Four receptor depths separate optical sampling; pigment identity, focus and receptor spacing are distinct properties.'},
 {'lead':'Defocus-based depth','text':'Hasarius can jump accurately with one principal eye; red-light undershooting and intensity controls support a distance cue from image blur.'},
 {'lead':'Spectral specialization','text':'Ultraviolet and green channels occur in principal eyes; Habronattus filtering predicts an additional red-shifted channel without a third opsin.'},
 {'lead':'Active visual sampling','text':'Body saccades, retinal tracking and scanning are distinct motor outputs; lateral input guides principal-eye tracking.'},
 {'lead':'Central integration and limits','text':'Mapped pathways and eye-dependent receptive fields support visual convergence, while the comparing cells, postsynaptic receptors and ion channels remain unresolved.'}
], 'cite':'Land (1969a, 1969b, 1971); Nagata et al. (2012); Zurek et al. (2015); Jakob et al. (2018); Menda et al. (2014); Steinhoff et al. (2020)', 'refs':[ref(k)for k in R], 'transcript':[
'Lateral-eye detection and principal-eye sampling contribute different operations to predation. Eye-isolation experiments establish particular capacities and dependencies without assigning every hunting action to one pair.',
'The layered retina separates receptor location from spectral sensitivity and optical sharpness. Anatomical spacing constrains sampling, while physiological and pigment measurements determine the available spectral inputs.',
'Hasarius jump errors under red light agree with an image-defocus account. Brightness controls weaken a photon-capture explanation, but the study does not identify a neuronal comparison between layers.',
'Habronattus adds a restricted retinal filter that shifts the effective sensitivity of green-pigment receptors. The published predicted channel is distinct from a directly recorded opponent pathway or a complete behavioral demonstration of trichromacy.',
'Principal retinas move through saccades, tracking and scans. Body orientation is a separate output, and masking experiments establish a lateral contribution to tracking while preserving some stationary-target examination.',
'Central recordings establish complex visual responses and eye-dependent convergence. Anatomical tracts and histamine labeling supply routes and molecular candidates, while the unmeasured synaptic and ion-channel steps remain open scientific questions.'
]}
assert len(SL)==44,len(SL)
D={'lecture':12,'content_slides':44,'theme':'pewter-pale-blue','title_refs':[ref('zurek15')], 'title_image':fig('z15_f1a','Habronattus pyrrithrix, a jumping spider studied for retinal spectral filtering.','A'),'slides':SL,'takeaways':TK}
(BASE/'lecture.json').write_text(json.dumps(D,indent=2,ensure_ascii=False)+'\n')
for i,s in enumerate(SL,2):print(i,sum(len(re.sub(r'[*_]','',p).split())for p in s['body']),s['title'])
