"""Rebuild the lecture specification from verified primary sources and original PDF crops."""
import json,re
from pathlib import Path
base=Path(__file__).resolve().parent
sources=json.loads((base/'sources/available-pdfs.json').read_text())
refs={q['key']:q['full_reference'] for q in sources}
refs['brain14']='Herculano-Houzel S, Avelino-de-Souza K, Neves K, Porfírio J, Messeder D, Mattos Feijó L, Maldonado J, Manger PR (2014). The elephant brain in numbers. Frontiers in Neuroanatomy 8:46. https://doi.org/10.3389/fnana.2014.00046'
refs['trigeminal24']=refs['trigeminal24'].replace('eLife reviewed preprint .','eLife reviewed preprint 94142, version 3 (16 August 2024).')
refs['hearing82']=refs['hearing82'].replace('localization..','localization.')
cites={'brain14':'Herculano-Houzel et al. (2014)','brain25':'Shah et al. (2025)','trigeminal24':'Reveyaz et al. (2024)','motor22':'Kaufmann et al. (2022)','foot07':'Bouley et al. (2007)','hearing82':'Heffner & Heffner (1982)','bone26':'O’Connell-Rodwell et al. (2026)','playback06':'O’Connell-Rodwell et al. (2006)','alarm07':'O’Connell-Rodwell et al. (2007)','noise21':'Mortimer et al. (2021)','seismic21':'Reinwald et al. (2021)','rumble26':'Limberger et al. (2026)'}
dois={q['key']:q['doi'] for q in sources}
slides=[]
def fig(k,name,num,desc):
 return {'path':f'figures/{name}.png','kind':'article','caption':f'{cites[k].replace(" et al."," et al.").replace(" (", " (").replace(")", "),",1)} Fig. {num}. {desc}','source_url':'https://doi.org/'+dois[k]}
def add(title,k,name,num,desc,body,extra):
 ps=body.strip().split('\n\n');assert 3<=len(ps)<=5
 transcript=[[re.sub(r'\*\*|_', '',p),[extra[i]]] if i<len(extra) else re.sub(r'\*\*|_', '',p) for i,p in enumerate(ps)]
 slides.append({'layout':'figure-right' if len(slides)%4!=2 else 'figure-left','title':title,'body':ps,'figure':fig(k,name,num,desc),'cite':cites[k],'refs':[refs[k]],'transcript':transcript})
add('Rumbles travel through both air and ground','rumble26','rumble_signals','2(A–F)','Paired rumble recordings and frequency spectra.', '''Elephant **rumbles** are low-frequency vocalizations with energy that can propagate as airborne pressure changes and as ground motion. Limberger and colleagues recorded African savanna elephants with a co-located infrasound sensor and three-component seismometer during a month of zoo monitoring.

A **spectrogram** represents frequency content over time. Corresponding rumbles appeared in both recording channels, commonly with fundamentals around 10–25 Hz and harmonics above 25 Hz. Individual rumble events lasted approximately 1–8 s in this dataset.

Footfalls produced strong seismic transients without equivalent infrasonic events. Matching the channels therefore distinguished vocal activity from locomotion more reliably than either channel alone; recordable ground energy does not establish how far elephants can perceive it.''', ['Infrasound refers to airborne sound below 20 Hz, whereas seismic vibration refers to motion of the substrate, regardless of whether its frequency is infrasonic.','A harmonic is a frequency component at an integer multiple of the fundamental; the recording channels differed in their noise and frequency-dependent propagation.','The recordings came from a zoo enclosure, so their daily activity patterns cannot be assumed to match those of free-ranging elephants.'])
add('Brain mass differs across species and sex','brain25','brains_photo','1(A–D)','Adult and newborn elephant brains with scale bars.', '''Shah and colleagues compared postmortem brains from Asian elephants, _Elephas maximus_, and African savanna elephants, _Loxodonta africana_. They combined documented specimens with earlier brain-weight records, retaining species, sex and age information rather than treating all elephants as one anatomical category.

Adult female Asian brains averaged 5,346 g, compared with 4,417 g in African females. African male brains averaged 5,603 g. The Asian female brains were larger despite the species having a smaller average female body mass.

Newborn brains averaged 1,806 g across the two species, approximately one-third of the pooled adult value. The substantial postnatal increase describes anatomical development; neither brain mass nor these cross-sectional comparisons measure learning capacity, auditory performance or intelligence directly.''', ['Brain extraction quality varied, which is why specimen provenance matters when comparing very large brains.','Sex comparisons require separate groups because African male and female body sizes differ substantially.','Cross-sectional specimens from different ages do not track the growth of the same individual through time.'])
add('MRI separates cortical gray and white matter','brain25','brain_mri','2(A–E)','MRI sections and the segmented cortical boundaries.', '''**Magnetic resonance imaging**, or MRI, distinguishes tissues through their physical responses to magnetic fields and radiofrequency stimulation. Shah and colleagues acquired T1- and T2-weighted scans of postmortem elephant brains and segmented the outer cortical surface and the gray–white matter boundary.

**Gray matter** contains neuronal cell bodies and local processes; **white matter** is dominated by axons and their myelin sheaths. Comparing both MRI contrasts helped the investigators recognize boundaries despite artifacts and reconstruct cortical tissue volumes.

Asian elephants had a larger cortical gray-matter proportion than African savanna elephants in the available specimens. Segmentation measures tissue geometry, not synaptic connectivity or regional neural activity. The comparison therefore establishes a species difference in brain organization without assigning that difference to a particular sensory computation.''', ['Segmentation means assigning a tissue label to each image volume element, rather than counting neurons directly.','The same specimen can be examined in horizontal and coronal planes, which helps distinguish a genuine boundary from an imaging artifact.','Differences in preservation and the available specimen collection limit population-wide generalization.'])
add('Brain size does not specify cortical neuron number','brain14','brain_scale','1(A)','Regional brain mass plotted against neuron number.', '''Herculano-Houzel and colleagues partitioned a fixed African elephant hemisphere into anatomically identified regions and used the **isotropic fractionator**, a tissue-processing method that estimates cell numbers from suspended nuclei. Whole-brain estimates doubled the counts from the analyzed hemisphere.

The cerebral cortex contained approximately 5.6 billion neurons, while the complete brain estimate was about 257 billion. A large cortex can contain fewer neurons per unit tissue than a smaller cortex; neuron number and tissue mass are therefore distinct anatomical measurements.

The elephant cortical estimate followed the scaling relationship of other afrotherian mammals rather than the primate relationship. The preparation supplied detailed regional counts but destroyed local tissue architecture during counting, so it did not identify functional auditory circuits, synapses or individual neuronal response properties.''', ['A nucleus is the cell compartment containing DNA; counting nuclei permits estimation of cell populations after tissue dissociation.','The counts refer to an analyzed adult male African elephant, and the whole-brain calculation assumes broadly comparable hemispheres.','Afrotheria is the mammalian evolutionary group that includes elephants; different mammalian groups have different mass-to-neuron relationships.'])
add('Most counted neurons reside in the cerebellum','brain14','brain_cerebellar','5','Cerebellar versus cortical neuron counts across mammals.', '''The **cerebellum** is a hindbrain structure associated with movement coordination and sensory–motor processing. Regional cell counting in the African elephant yielded approximately 250.7 billion cerebellar neurons, about 97.5% of the estimated total brain neurons.

The ratio was roughly 45 cerebellar neurons for every cortical neuron, substantially above the approximately four-to-one relationship described for many other sampled mammals. Thus, the exceptionally high elephant whole-brain count largely reflects cerebellar organization rather than a corresponding excess of cortical neurons.

The authors proposed contributions from trunk control and other sensory specializations, including low-frequency communication. These are functional hypotheses derived from anatomical scaling. The count did not test cerebellar activity during trunk contact, rumble perception or seismic-playback responses.''', ['Regional counting prevents an abundant cell population in one structure from being mistaken for a uniform enlargement of all neural systems.','A neuron count does not give the number of synapses or the temporal response properties of those neurons.','Assigning the cerebellar excess to a behavior would require evidence connecting activity or disruption of that structure to the behavior.'])
add('Cerebellar proportion also varies between species','brain25','brain_cb_mri','4(A–D)','Cerebellar MRI anatomy and relative tissue weights.', '''Shah and colleagues delineated the cerebellum in MRI volumes and compared cerebellar size with total brain size. The method separated an absolute tissue measurement from a **relative proportion**, the fraction of the complete brain occupied by that region.

Asian elephant cerebella averaged 19.1% of brain weight, whereas African savanna cerebella averaged 22.3%. The species differed in proportional allocation even though the available absolute cerebellar weights were comparable.

The finding complements regional neuron counts: a large cerebellar fraction and a high cerebellar neuron count describe related but different features. MRI does not identify cell populations, and proportional anatomy does not prove superior motor control or seismic sensitivity. Comparisons also remain limited by preservation differences and the available species, sex and age distribution.''', ['A larger total brain can reduce a region’s proportional share without requiring that region to become absolutely smaller.','The analyzed collection included Asian and African savanna elephants, not African forest elephants.','A functional interpretation must account for both the tissue denominator and the specific neurons being compared.'])
add('The ventral brainstem contains a trunk candidate','trigeminal24','trig_gross','1(A–J)','Brainstem protrusions and metabolically stained tissue.', '''Reveyaz and colleagues studied fixed elephant brainstems to identify a candidate central representation of trunk touch. The **trigeminal system**, associated with cranial nerve V, conveys somatic sensation from the face and trunk rather than motor commands to trunk muscles.

Paired protrusions approximately 1 cm behind the pons contained intensely cytochrome-oxidase-reactive tissue. **Cytochrome oxidase** is a mitochondrial enzyme whose histochemical activity indicates local energy metabolism; the proposed trunk module was also densely vascularized.

Earlier anatomical descriptions called these protrusions the inferior olive. The new study proposed a trigeminal identity using several converging anatomical tests. This assignment remains explicitly putative: staining can locate a specialized tissue compartment, but it does not record touch-evoked responses or establish its receptive fields.''', ['The pons is a major brainstem region; a module is a proposed anatomical subdivision within a nucleus.','The candidate module contained about twice the blood-vessel density of the surrounding brainstem tissue.','The source is the peer-reviewed eLife reviewed preprint, version 3; its assessment retained uncertainty about some nuclear boundaries.'])
add('Fiber anatomy distinguishes olive from trigeminal tissue','trigeminal24','trig_tract','2(A–F)','Peripherin-labeled olivo-cerebellar fibers and nuclei.', '''The **inferior olive** supplies climbing fibers to the cerebellum in mammals. Reveyaz and colleagues used antibodies against **peripherin**, a neuronal structural protein, to delineate the elephant olivo-cerebellar pathway and test whether the prominent ventral bumps belonged to it.

The labeled pathway connected the cerebellum with a separate dorsolateral nucleus that had a folded cellular architecture characteristic of an olive. It did not provide the expected climbing-fiber connection to the ventral protrusions assigned as trigeminal tissue.

This anatomical control supports separating a candidate trunk sensory representation from an olivo-cerebellar structure. The argument depends on pathway labeling and comparative morphology, not on the bump’s external position alone. It still does not establish which tactile stimuli activate individual neurons or how their activity reaches higher sensory centers.''', ['An antibody label identifies tissue containing a target protein; it is not equivalent to measuring signals transmitted through the labeled axons.','Climbing fibers are named for their characteristic cerebellar projections, which make the olivo-cerebellar connection an informative identity test.','The anatomical reassignment corrects the assumption that a similarly positioned protrusion must have the same identity in different mammals.'])
add('Trigeminal modules repeat along the brainstem','trigeminal24','trig_serial','3(A–F)','Serial trigeminal modules in coronal and horizontal sections.', '''Serial sections permitted Reveyaz and colleagues to compare candidate trunk modules along the anterior–posterior axis of the brainstem. A **nucleus** is a centrally located group of neurons; repeated nuclei can process related peripheral inputs at different anatomical levels.

The proposed **principal trigeminal nucleus**, abbreviated Pr5, was the most anterior and largest trunk representation. Smaller posterior modules were assigned to the spinal trigeminal subdivisions pars oralis, pars interpolaris and pars caudalis using comparative organization and tissue boundaries.

Nissl staining, which labels cell-body-associated material, helped distinguish cellular regions from surrounding fiber tracts. The repeated architecture supports an organized brainstem sensory system. Individual module identities and peripheral assignments remain anatomical proposals, because invasive sensory mapping and pathway tracing were not available in living elephants.''', ['Anterior means toward the front of the head, whereas posterior means toward the spinal cord.','Pr5 and the spinal trigeminal subdivisions are separate proposed processing regions, rather than four subdivisions of one peripheral nerve.','The source’s anatomy does not justify claiming specific excitatory or inhibitory synaptic connections between these modules.'])
add('Trunk-module cells align with myelinated bundles','trigeminal24','trig_cells','4(A–J)','Cell morphologies, dendritic orientations and nuclear stains.', '''Golgi staining revealed neuronal processes within the candidate trigeminal trunk module. **Dendrites** are neuronal branches receiving inputs; **myelin** is an insulating sheath around many axons. The principal neuronal dendritic trees tended to elongate along the local axon-bundle orientation.

After alignment to the bundles, the measured dendritic trees were approximately twice as long along the bundle axis as across it. NeuN labeling identified neurons, while DAPI labeled DNA-containing nuclei, allowing neuronal and non-neuronal populations to be distinguished.

The broader tissue analysis estimated roughly 108 non-neuronal cells per neuron. This unusually sparse neuronal organization cautions against equating module volume with neuron abundance. Morphological categories and alignment do not reveal neurotransmitter identity, synaptic partners or the activity patterns used for tactile discrimination.''', ['NeuN is a commonly used neuronal nuclear marker; DAPI stains DNA and therefore labels many cell types.','Golgi staining samples cellular morphology rather than labeling every neuron uniformly.','The authors classified several cell types by appearance and used putative labels where identification was incomplete.'])
add('Myelin stripes correspond to trunk folds','trigeminal24','trig_folds','5(A–F)','Original myelin staining, fold map and trunk photographs.', '''The candidate trunk module contained prominent stripes visible in fresh tissue and confirmed with fluorescent myelin staining. Reveyaz and colleagues compared the number, orientation and arrangement of those stripes with the folds of the same elephant’s trunk.

They counted 65 dorsally ending stripes alongside 64 dorsal trunk folds, with similar correspondences for other stripe and fold classes. The proposed map allocated much more neural distance to distal trunk regions: the reported trunk-to-neural length ratio changed from about 1,000:1 proximally to 5:1 at the finger.

**Sensory magnification** means disproportionate neural space devoted to a peripheral region. Here it is inferred from anatomical correspondence, not measured receptive fields. Section angle affected stripe visibility, and the authors proposed that some stripe axons separate fold-related domains rather than acting as ordinary local connections.''', ['Proximal refers to the trunk nearer its attachment, and distal refers to the tip.','The ratio describes peripheral length compared with corresponding neural-map length; its lower value at the tip implies greater representation per unit trunk length.','The map should not be treated as a proven functional equivalent of an electrophysiologically mapped tactile fovea.'])
add('Species-specific trunk use matches candidate maps','trigeminal24','trig_species','7(A–I)','Asian and African trunk modules and wrapping regions.', '''Asian elephants commonly wrap the trunk around objects, whereas African savanna elephants can pinch with two opposing tip fingers. Reveyaz and colleagues compared brainstem tissue organization with these differences in peripheral anatomy and object manipulation.

The candidate principal trunk module contained approximately 640,000 neurons in Asian elephants and 740,000 in African elephants. Asian modules had enlarged representations assigned to regions involved in wrapping, while finger-related regions differed with the species’ tip morphology.

The relationship is consistent with sensory specialization for different manipulative strategies. It remains a comparison of postmortem anatomy and observed morphology, rather than a causal manipulation of trunk use. The proposed peripheral assignments do not establish which neurons detect ground contact or whether these trigeminal modules mediate seismic communication.''', ['A larger representation of a wrapping region does not require a larger representation of every part of the trunk.','The anatomical correspondences are strongest when they are checked against tissue boundaries, cell distributions and the matching peripheral morphology together.','Trunk sensation and foot sensation originate in different peripheral territories, so evidence about the trunk cannot be directly assigned to the feet.'])
add('Facial nuclei provide a separate motor organization','motor22','motor_nucleus','1(A–F)','Nissl-stained facial nucleus and published subdivisions.', '''Kaufmann and colleagues examined fixed brainstems and facial nerves to characterize elephant facial motor control. The **facial nucleus** contains cranial nerve VII motor neurons, anatomically distinct from the trigeminal sensory nuclei associated with trunk sensation.

Nissl-stained sections supported approximately 54,000 facial-nucleus neurons in Asian elephants and 63,000 in African elephants. The estimates were checked using different counting approaches and, where possible, against facial-nerve axon counts.

The nucleus contained unusually elongated dorsal and lateral subdivisions, proposed to innervate trunk muscles. The correspondence follows comparative motor organization, large neuron populations and matching peripheral anatomy. These fixed-tissue observations identify candidate motor representations without measuring muscle activation or proving the specific commands issued during trunk handling or listening postures.''', ['A motor neuron sends output through an axon to a muscle; a sensory pathway carries information from receptors toward central processing.','The subdivision assignment is a proposed muscle map derived from comparative anatomy and peripheral nerve counts.','Peripheral axon counts provide a separate anatomical check on central cell counts, although they do not identify each neuron’s target muscle.'])
add('Larger African ears have larger motor allocations','motor22','motor_ears','3(A–D)','Ear photographs, auricular nerve and medial facial neurons.', '''The **auricularis branch** of the facial nerve supplies ear musculature. Kaufmann and colleagues compared ear size, this motor nerve branch and the medial facial subnucleus in Asian and African savanna elephants.

African elephants had larger ears, a thicker auricularis branch and more medial-subnucleus neurons. Reported mean counts were approximately 12,000 neurons in African elephants and 7,500 in Asian elephants. Nerve-axon counts and comparative mammalian anatomy supported assigning this region to ear motor control.

The agreement links an enlarged peripheral structure with increased central motor allocation. Ear positioning can influence how sound reaches the animal, but this anatomical study did not test sound-localization performance. It also did not show that these motor neurons close the ear canal or selectively enhance ground-vibration reception.''', ['The medial subnucleus is a subdivision of the facial motor nucleus, not an auditory relay nucleus.','The study separates species differences in peripheral musculature from assumptions based only on whole-brain size.','A proposed role for ear posture in hearing requires behavioral or mechanical evidence beyond the cell counts.'])
add('Distal motor neurons are exceptionally large','motor22','motor_gradient','4(A–E)','Trunk, facial cell-size gradients and stained motor neurons.', '''Kaufmann and colleagues reconstructed neuron positions in dorsal and lateral facial subdivisions and measured cell-body size along their elongated axes. **Somata** are neuronal cell bodies; their size can vary independently of the number of neurons in a region.

Cells became larger toward the putative distal trunk representation, with some estimated volumes near 100,000 µm³. The corresponding gradients were much weaker or absent in the comparison mammalian facial nuclei analyzed in the study.

The authors proposed that these large cells support long axons and demanding control of distal trunk musculature. The interpretation is anatomically plausible but was not tested by conduction-velocity measurements, neuromuscular recordings or manipulations of individual motor units. Large somata alone do not establish faster sensory detection or more precise temporal coding.''', ['A motor unit is a motor neuron and the muscle fibers it supplies; this study did not reconstruct complete individual elephant motor units.','The position-to-trunk assignment rests on the proposed organization of the nucleus rather than direct stimulation of each neuron.','The gradients describe specialized organization within the nucleus and cannot be inferred from a whole-brain average neuron size.'])
add('Trunk tips have candidate motor foveae','motor22','motor_tips','6(A–H)','Tip anatomy, grasping photographs and motor-cell distributions.', '''African elephant trunk tips have dorsal and ventral fingers used for pinching, while Asian elephant tips have a single dorsal finger and often wrap around objects. Kaufmann and colleagues related these peripheral differences to cell distributions in the facial motor nucleus.

**Motor fovea** denotes a proposed concentration of neural resources for a particularly dexterous effector. The dorsal subdivision contained concentrations of large neurons in both species, while the lateral subdivision had a marked distal concentration in African elephants.

The published anatomy is consistent with distinct finger-control demands. It does not identify individual finger muscles by direct stimulation, and the correspondence is not a measured map of task-related firing. Sensory magnification in the trigeminal system and motor specialization in the facial system are complementary hypotheses supported by different anatomical preparations.''', ['Pinching involves opposing peripheral structures, whereas wrapping involves bending a larger length of trunk around an object.','The authors inferred motor organization using cell positions and morphology, rather than recording a complete circuit during grasping.','The term fovea is used here by functional analogy and does not imply that the elephant has a retinal-like tissue structure in the trunk.'])
add('Feet combine load-bearing tissues and sensory structures','foot07','foot_gross','1(A–B)','Asian forefoot and hindfoot specimens used for histology.', '''Bouley and colleagues examined preserved Asian elephant feet to locate structures that might detect ground vibration. The forefoot had a rounder external profile than the hindfoot, and both contained substantial supporting tissues between the skin and skeletal elements.

The researchers sampled sagittal slices through different digits, concentrating on tissue approximately 6 cm above the sole. A **digital cushion** is the specialized soft supporting tissue beneath the digits; its distal portion and the overlying dermis were analyzed separately.

The preparation linked microscopic receptor locations to the foot’s gross geometry rather than assuming uniform sensation across the sole. Preserved tissue establishes the location of candidate receptors, but its mechanical properties differ from a loaded living foot. Vibration transfer under different postures was therefore a hypothesis, not a direct measurement.''', ['The dermis is the connective-tissue layer below the epidermis; the thick sole surface was removed where needed to permit histological preparation.','Sampling several foot slices allowed regional distributions to be considered rather than relying on one attractive microscopic field.','The forefoot and hindfoot specimens had different preservation histories, which limits precise mechanical comparisons.'])
add('Histological sampling localizes candidate receptors','foot07','foot_sections','2(A–C)','Foot slice, sampling outlines and corpuscle locations.', '''Bouley and colleagues divided the distal foot tissue into proximal and distal rows, then processed it into paraffin sections stained with **hematoxylin and eosin**, or H&E. This stain differentiates cellular and connective-tissue components for light microscopy.

They identified Pacinian corpuscles by a central nerve process, concentric surrounding lamellae and a distinct outer capsule. Traced receptor profiles were overlaid on the original foot slice, preserving the relationship between microscopic observations and anterior, middle and posterior positions.

**Density** was expressed as corpuscle profiles per mm² of sectioned tissue. More profiles occurred in the distal than proximal row. These are section-based anatomical measurements, not a complete count of all living receptors or a measurement of their vibration thresholds. Tissue processing also produced shrinkage that affects absolute dimensions.''', ['The identification criteria distinguish a candidate encapsulated receptor from a general nerve bundle or blood vessel.','A two-dimensional section can intersect one structure at several different levels, so profile density is not automatically equivalent to whole-foot receptor abundance.','Relating histology to an intact foot slice preserves spatial information that would be lost if specimens were pooled.'])
add('Pacinian corpuscles surround a central neurite','foot07','foot_corpuscle','3(A–D)','H&E corpuscle with central neurite, lamellae and capsule.', '''A **Pacinian corpuscle** is an encapsulated mechanoreceptor composed of a nerve ending surrounded by concentric lamellae. A **mechanoreceptor** responds to mechanical deformation; the elephant foot sections contained recognizable central neurites, interlamellar spaces and an external connective-tissue capsule.

The published H&E micrograph includes a 0.1 mm scale bar, placing these structures at a tissue scale appropriate for local deformation. The central **neurite** is the neuronal process, while the surrounding lamellae are non-neuronal components of the receptor organ.

Pacinian morphology makes vibration sensing a credible candidate function. Nevertheless, the elephant study did not record receptor potentials or action potentials. It did not identify the molecular transduction channel, demonstrate a 20–40 Hz best frequency or determine whether these receptors are necessary for seismic-playback responses.''', ['Rapid adaptation in Pacinian receptors refers to preferential responses to changes in deformation rather than indefinitely sustained force; the elephant tissue study did not test this property physiologically.','Mechanical deformation must ultimately affect a sensory nerve ending before it can become a neural signal, but the responsible elephant membrane proteins were not measured here.','An anatomical receptor identification and a behavioral response require separate physiological evidence to be linked into one established pathway.'])
add('Many foot corpuscles occur in clusters','foot07','foot_cluster','4(A–D)','Serial H&E sections through a corpuscle cluster.', '''Serial H&E sections permitted Bouley and colleagues to follow corpuscles through adjacent tissue planes rather than interpreting each profile in isolation. Individual organs appeared, changed outline and disappeared as the cutting plane passed through a cluster.

Approximately 80% of the observed corpuscles occurred in clusters, commonly containing three or four organs and occasionally as many as 18. A reconstructed serial sequence spanned 400 µm of tissue, preserving the changing relation between adjacent encapsulated structures.

Clustering concentrates candidate mechanoreceptive elements in localized tissue compartments. It does not establish that those receptors share an axon, converge on one central neuron or have identical frequency tuning. The study’s serial anatomy helps distinguish neighboring organs from repeated intersections of a single irregularly shaped structure.''', ['Serial sectioning means examining consecutively cut tissue slices in their original order.','The sequence was made from 4 µm sections, providing continuity at a finer scale than the dimensions of many entire corpuscles.','The relation between clustered receptors and mechanical sensitivity would require deformation measurements and recordings from the associated nerves.'])
add('Three-dimensional anatomy resolves receptor boundaries','foot07','foot_3d','5(A–C)','The article’s original reconstruction of traced corpuscles.', '''Bouley and colleagues reconstructed an encapsulated receptor cluster from traced serial histological sections. The original article’s three-dimensional rendering retained separate contours for individual Pacinian corpuscles, allowing structures that overlapped in a single section to be distinguished.

The reconstruction revealed complex shape changes and branching profiles rather than a set of identical spherical organs. Complete structures could be followed from their first appearance to their disappearance, whereas incompletely sampled structures could not supply reliable total volumes.

This method clarifies organ geometry and the limitations of two-dimensional profile counts. The published reconstruction is an anatomical result, not a simulation of receptor activity. It contains no measured ground-to-nerve transfer function, so the arrangement cannot yet be converted into a demonstrated seismic detection threshold or a proven neural coding scheme.''', ['Tracing successive sections identifies how separate receptor organs occupy the same tissue cluster.','A profile that splits in one section does not by itself prove two separate receptors, because one irregular three-dimensional organ can produce multiple intersections.','The identification of complete organs is essential when estimating their volumes from serial tissue slices.'])
add('Receptor distribution supports a posture hypothesis','foot07','foot_posture','6(A–B)','Original photographs of leaning and ground-contact postures.', '''Bouley and colleagues found corpuscle distributions concentrated near the anterior and posterior foot regions. The traced profiles placed about 52% of forefoot corpuscles anteriorly and 47% of hindfoot corpuscles posteriorly, rather than distributing them evenly through the sampled tissue.

The authors related this anatomy to leaning and weight-shifting postures observed during seismic-playback responses. Greater contact or loading at receptor-rich regions might improve transfer of substrate vibration to the receptor organs.

This **coupling hypothesis** links a possible change in mechanical input to a possible change in sensation. Neither local pressure nor receptor firing was recorded during the postures. Freezing might also reduce self-generated movement noise, and bone conduction remains an alternative route. Behavioral posture alone cannot isolate the mechanism of ground-signal detection.''', ['The regional percentages refer to anatomically traced profiles, not to the percentage of sensory axons activated during a posture.','The table and abstract provide slightly different rounded regional summaries; the teaching text uses approximate values rather than implying precision beyond the sampling.','Ground contact can change several physical factors at once, so it is not a selective manipulation of Pacinian receptors.'])
add('An operant task measures auditory detection','hearing82','hearing_task','1','Original elephant response panel and loudspeaker arrangement.', '''Heffner and Heffner measured hearing in a young Asian elephant using an **operant task**, in which an animal learns a response through its consequences. The elephant pressed a central button to initiate a trial, then selected a response associated with the presented sound.

Fruit-flavored sugar solution reinforced correct choices. Loudspeakers and response buttons permitted controlled tests of sound detection, frequency discrimination and left–right localization within the same preparation. Sound pressure was calibrated rather than inferred from the speaker setting.

The procedure converts an animal’s report into a repeatable psychophysical measurement. Training, motivation, ambient noise and response rules can influence observed thresholds, so the results describe behavioral performance under the tested conditions. A threshold is not a direct measurement of cochlear hair-cell sensitivity or a species-wide constant.''', ['Psychophysics measures the relation between a controlled physical stimulus and the animal’s behavioral response.','The experiment used a seven-year-old female elephant; repeated testing of one trained animal provides detailed performance measurements without establishing population variability.','Speaker placement and level calibration are required because room acoustics can alter the actual stimulus reaching the ears.'])
add('The audiogram extends into infrasound','hearing82','hearing_audiogram','2','Measured hearing thresholds and background sound levels.', '''An **audiogram** plots the sound level needed for detection against frequency. Heffner and Heffner obtained similar curves with the speaker directed toward the left and right ears, checking for gross asymmetry and sound-field problems.

The elephant detected 16 Hz at 65 dB sound-pressure level; the low-frequency limit at 60 dB was estimated as 17 Hz. Best measured sensitivity occurred around 1 kHz at 8 dB. The 60 dB high-frequency limit was approximately 10.5 kHz.

**Sound-pressure level**, or SPL, expresses acoustic pressure relative to a standard reference, here 20 µPa. Background noise lay near thresholds over part of the intermediate-frequency range, so the animal’s true sensitivity there may have been better than the measured curve. An audible frequency range does not establish the detection range of distant natural calls.''', ['The animal could detect 12 kHz at 72 dB but did not respond to 14 kHz at 90 dB, emphasizing that hearing limits depend on the chosen level.','Directing the source toward each ear reduced the risk that head shadowing would falsely eliminate high-frequency hearing.','A seismic velocity level uses a different physical reference and cannot be read as equivalent to an airborne SPL value.'])
add('Frequency discrimination is strongest at low frequencies','hearing82','hearing_discrimination','4','Frequency-difference thresholds across test frequencies.', '''Heffner and Heffner presented alternating tones and rewarded choices based on whether their frequencies differed. A **frequency difference limen** is the smallest discriminable frequency change under a specified behavioral criterion, rather than the lowest frequency an animal can hear.

At 250 and 500 Hz, the elephant detected fractional changes around 0.005 under the 75%-correct criterion. Discrimination became poorer around 1 kHz and declined further at higher test frequencies. The tones were presented well above detection threshold, with level variation reducing simple loudness cues.

This separation of detection from discrimination matters for communication: hearing a rumble does not guarantee that all frequency contours can be resolved. The study measured differences between controlled tones, not recognition of individual elephants, alarm meaning or discrimination of complete naturally propagated seismic calls.''', ['A fractional difference of 0.005 denotes a 0.5% frequency change; the value is a discrimination criterion reported by the original study.','The investigators varied stimulus intensity to prevent the elephant from solving the task using a consistent unintended intensity difference.','Alternative behavioral criteria produced different limens, so a threshold value must retain its operational definition.'])
add('Brief broadband sounds can be localized precisely','hearing82','hearing_noise','5','Localization performance for clicks and brief noise bursts.', '''Heffner and Heffner tested left–right localization with single clicks and 100 ms bursts of broadband noise. **Azimuth** is horizontal direction; varying the angular separation between the speakers measured how well the elephant distinguished nearby source positions.

The animal localized widely separated sources accurately, with broadband thresholds around 1°. Fast-onset noise with a 0.1 ms rise time supported better small-angle performance than noise with a 50 ms rise time or a single click.

Brief sounds reduced opportunities for head scanning or tracking a continuing source. The result therefore supports precise localization from available auditory cues rather than movement toward a sustained sound. It does not identify the responsible brainstem neurons, nor does a broadband threshold predict equally accurate localization of low-frequency tonal rumbles or ground vibrations.''', ['Broadband noise contains many frequencies, whereas a pure tone is dominated by one frequency.','The stimulus duration and onset shape were controlled, because temporal information can affect localization independently of source direction.','The approximately one-degree value refers to this trained animal and these stimulus conditions, not a guaranteed performance value for every elephant.'])
add('Tone localization depends on frequency','hearing82','hearing_tones','6','Localization performance for three frequency groups.', '''Heffner and Heffner tested brief pure tones from 125 Hz to 8 kHz at different source separations. Presenting audible stimuli well above threshold helped separate difficulty locating a sound from failure to detect its presence.

Localization was strongest at 125 and 250 Hz, intermediate at 500 Hz through 2 kHz, and poor at 4 and 8 kHz. Even at large separations, tonal performance was less complete than the nearly perfect performance obtained with broadband sounds.

The frequency dependence is consistent with different **binaural cues**, information derived by comparing inputs to the two ears. Low-frequency timing and phase differences can support direction judgments, while higher-frequency intensity differences may contribute. The behavioral pattern constrains possible mechanisms but does not establish a mapped elephant neural circuit or identify its neurotransmitters.''', ['Binaural means involving both ears; a monaural measure instead concerns information available from one ear alone.','The tested tones were selected above the measured auditory threshold, so poor directional performance at high frequencies cannot simply be equated with inaudibility.','The comparison uses a single controlled behavioral preparation, reducing differences caused by unrelated task procedures.'])
add('Phase ambiguity limits a timing-only account','hearing82','hearing_phase','7','Tone localization at 60° across frequency.', '''An **interaural time difference** is the difference in arrival time between the two ears. For a repeating tone, the corresponding **phase difference** specifies the relative position within its oscillation cycle; phase becomes ambiguous when different delays correspond to the same repeating pattern.

Heffner and Heffner tested tones at 60° separation and 40 dB above detection threshold. Performance remained relatively good around 500 Hz through 2 kHz, beyond the range where a simple unambiguous phase comparison was expected to suffice for the elephant’s large head.

The authors therefore proposed contributions from interaural intensity differences in addition to timing. This inference explains why one cue cannot account for the full behavioral function. It is a psychophysical constraint, not a direct recording of coincidence detectors, phase-locking neurons or excitatory–inhibitory comparisons in the elephant brainstem.''', ['The two ears receive the same periodic waveform at different times, but the waveform’s repetition can obscure how many complete cycles separate the inputs.','Interaural intensity difference means unequal sound levels at the ears, often associated with frequency-dependent head shadowing.','The experiment inferred useful cue types from stimulus conditions; it did not independently impose each cue through earphones.'])
add('High-frequency noise outperforms high-frequency tones','hearing82','hearing_filter','8','Localization of filtered narrow-band noise.', '''Heffner and Heffner replaced pure tones with filtered noise bands to test whether poor high-frequency localization reflected a general inability to use high-frequency sound. **Narrow-band noise** contains a restricted range of frequencies while retaining temporal and spectral variation.

The elephant localized bands centered at 4 and 8 kHz substantially better than corresponding pure tones. The filtered bands were localized with accuracy comparable to broadband noise; additional testing of high-pass noise above 8 kHz yielded a threshold around 0.7°.

The result indicates that stimulus structure, not simply the frequency of maximum energy, determines localization performance. Additional temporal or spectral information can support a direction judgment when a single tone is insufficient. The study did not determine which specific neural representation extracts those features, and high-frequency noise performance does not establish a mechanism for seismic rumble localization.''', ['Filter bandwidth changes the range of frequency components available for localization even when the band’s center frequency remains fixed.','The authors rechecked hearing sensitivity at 4 and 8 kHz, which helped exclude a change in audibility as the explanation for the comparison.','A cue inferred from noise performance must still be separated from the animal’s actual responses to natural calls.'])
add('Bone conduction can move ossicles relative to the skull','bone26','bone_setup','1(A–B)','Published vibrometry apparatus and middle-ear landmarks.', '''**Bone conduction** is transmission to the inner ear through vibration of skull tissues rather than solely through airborne pressure at the eardrum. O’Connell-Rodwell and colleagues mechanically stimulated cadaveric elephant and human temporal bones and measured motion with three-dimensional laser Doppler vibrometry.

The **ossicles** are the malleus, incus and stapes of the middle ear. Measurements at the umbo, stapes and cochlear promontory distinguished ossicular movement from movement of the surrounding bony reference over 12–11,000 Hz.

Relative stapes motion can contribute to cochlear stimulation when skull vibration and ossicular inertia differ. The preparation directly measured mechanics, but it lacked living neural responses, an intact weight-bearing body and behavioral detection. It therefore supports one component of a candidate seismic-hearing route without proving transmission from the feet to auditory perception.''', ['The umbo is the central eardrum–malleus attachment region; the promontory provides a nearby bony reference for common skull motion.','Doppler vibrometry measures motion through the frequency shift of reflected laser light, rather than through neural electrodes.','A mechanical pathway into the cochlea and a tactile receptor pathway in the skin are alternative candidate routes that the playback experiments did not separate.'])
add('Differential velocity separates local from shared motion','bone26','bone_elephant','2(A, C)','Elephant umbo and stapes differential velocity and phase.', '''O’Connell-Rodwell and colleagues projected three-dimensional velocities along the stapes piston direction, the direction relevant to its motion into and out of the inner-ear entrance. Comparing ossicular velocity with promontory velocity reduced the influence of motion shared by the entire specimen.

**Differential velocity** describes that relative motion normalized to the bony reference. Both magnitude and phase were measured, because a large displacement of the specimen does not necessarily imply substantial motion between the ossicles and cochlear capsule.

The normalized response changed systematically with frequency and differed between measurement sites. The study screened specimens for visible middle-ear pathology and maintained controlled mechanical stimulation. Cadaver preservation, open surgical access and varied elephant ages limit extension to intact hearing, particularly when estimating a perceptual threshold from a mechanical transfer measurement.''', ['The stapes piston direction is a mechanical axis, not a neural conduction pathway.','Phase specifies relative timing within an oscillation; magnitude specifies the size of the measured response.','Specimens from different species and ages were not sufficient to isolate age-specific or species-specific contributions to variability.'])
add('Elephant bone-conduction resonance is lower','bone26','bone_resonance','3(A–B)','Comparative umbo and stapes velocity magnitudes.', '''A **resonance** is a frequency range where the mechanical system has a characteristic enhanced response. O’Connell-Rodwell and colleagues compared normalized ossicular motion in elephant and human temporal-bone preparations under bone-conduction stimulation.

The measured bone-conduction resonance was approximately 400 Hz in elephants and 1,200 Hz in humans. Below the respective resonances, elephant stapes differential-velocity magnitudes were around three to four times greater than human values.

The authors linked the lower resonance to elephant middle-ear mass and its distribution. This provides direct comparative mechanical evidence consistent with low-frequency specialization. It does not mean that elephants perceive a sound as three to four times louder, and it does not establish a corresponding multiple in communication distance; perception also depends on cochlear and neural processing and environmental transmission.''', ['Both species were examined using the same type of velocity measurement and a local bony reference.','The mechanical comparison concerns normalized relative motion rather than the animal’s absolute behavioral hearing threshold.','The authors compared the measurements with a mechanical simulation, separating the observed response from the model prediction.'])
add('Low-frequency motion plateaus below about 200 Hz','bone26','bone_lowfreq','3(A–D)','Measured stapes magnitude and phase in elephants and humans.', '''The bone-conduction study followed relative ossicular motion into frequencies below the main resonance. Above approximately 200 Hz but below resonance, the differential-velocity magnitude decreased at roughly 12 dB per octave as stimulus frequency fell.

Below approximately 200 Hz, the measured stapes response plateaued in both elephant and human preparations rather than continuing that decline. Phase measurements supplied complementary information about the timing of the mechanical response in this low-frequency region.

The finding favors better low-frequency mechanical transmission than a simple continuation of the higher-frequency trend would predict. The authors also proposed enhancement through elephant ear-canal occlusion. That muscle-dependent mechanism was not demonstrated in living animals here, and neither the plateau nor the proposal identifies the sensory route actually used during ground-borne alarm responses.''', ['An octave is a twofold frequency interval, so the reported rate describes the change in measured response across successive frequency ranges.','Magnitude and phase must be interpreted together because relative motion can change even when the entire skull remains strongly driven.','Closing an ear canal can change mechanical conditions, but the cadaver experiments do not establish voluntary use of this effect during seismic listening.'])
add('A buried source isolates ground-borne stimulation','playback06','playback_setup','2(a)','Original waterhole layout and buried shaker position.', '''O’Connell-Rodwell and colleagues played seismic replicas of alarm calls to wild African elephant breeding herds at Mushara waterhole in Etosha National Park. Buried mechanical shakers delivered the signal to the ground, approximately 30 m from the waterhole.

A **geophone** measures ground motion, while a microphone measures airborne pressure. Near and remote sensors monitored the two media, permitting the investigators to check whether a response attributed to ground vibration could instead be caused by sound radiated into the air.

The trial included a 5 min observation period and a 3 min playback phase containing repeated 15 s signals. Observers recorded spacing, vigilance and time at the waterhole. This field preparation tested the sufficiency of ground-delivered information for a response, rather than requiring the researchers to assume an anatomical detection route.''', ['Breeding herds include adults and younger family members whose grouping can change during defensive responses.','The shaker delivered ground motion without requiring a live calling elephant to be present at the source.','Observer coding of body orientation was performed without knowledge of the experiment’s timing and purpose, reducing interpretation bias.'])
add('Microphone controls check airborne leakage','playback06','playback_controls','4(a–b)','Ground and airborne spectral measurements during playback.', '''In the seismic-playback study, stimulation strength had to balance ground detectability against unintended airborne radiation. High-level calibration signals could couple to the air, so the behavioral trials used a lower level with concurrent microphone monitoring.

Near-source geophones recorded increased energy in the 40–60 Hz region during playback, while the microphones did not detect a corresponding signal in that frequency band. The investigators also used signal-matching analyses to assess possible airborne contamination.

This control narrows the interpretation to a response elicited by ground-delivered stimulation under the tested conditions. Estimated levels at elephant positions depended on attenuation and background activity, so they were not direct measurements at every foot. The study established neither an absolute seismic threshold nor a maximum communication range across different soils.''', ['Attenuation is the reduction of signal strength with propagation distance and material losses.','A source can be mechanically coupled to soil and still radiate airborne sound, making a microphone control necessary.','Seismic velocity is measured in motion units, while airborne pressure is measured in pascals; their decibel references cannot be interchanged.'])
add('Seismic alarm playback changes herd behavior','playback06','playback_response','3','Spacing, vigilance and waterhole duration after playback.', '''Seismic alarm-call playback caused elephant breeding herds to form tighter groups and leave the waterhole sooner than comparison herds without the stimulus. The experiment measured these behavioral endpoints separately from individual scanning or freezing events.

Orientation also became nonrandom after playback, with many elephants facing approximately perpendicular to the source direction. Vigilant behaviors increased, but that change was less securely established than the changes in spacing and waterhole duration.

The response is consistent with detecting biologically relevant ground-borne information and organizing a defensive group response. It does not prove that recipients decoded a particular alarm meaning, and orientation is not a measured localization threshold. The approximately 30 m delivery geometry also cannot establish proposed kilometer-scale natural seismic communication distances.''', ['Grouping more tightly can reduce separation between adults and vulnerable younger animals during a possible threat.','The source’s behavioral evidence concerns observed outcomes and should not be converted into an unmeasured neural firing rate.','The authors explicitly distinguished detection from demonstrating discrimination of meaning, motivating subsequent comparisons among different call types.'])
add('Call comparisons test more than vibration detection','alarm07','alarm_stimuli','1(A–C)','Original unfamiliar, familiar and warble stimulus spectra.', '''O’Connell-Rodwell and colleagues compared seismic alarm rumbles recorded from the local Etosha population with unfamiliar alarm rumbles from Amboseli. Controls included no stimulation and artificial warble tones with broadly comparable low-frequency content and duration.

Alarm stimuli were bandpass filtered from 10 Hz to approximately 50–60 Hz, retaining the fundamental and second harmonic. The warble control varied around 30 Hz by 3 Hz at a 1 Hz modulation rate during 3 s tones.

These contrasts ask whether all low-frequency ground stimulation produces the same response. Randomized trial order and behavior scoring without knowledge of trial type reduced predictable observation effects. Call category, caller familiarity and detailed frequency modulation were not independently matched, so a response difference cannot be attributed uniquely to recognition of a familiar individual.''', ['A bandpass filter retains a specified frequency interval while reducing energy outside it.','The artificial warble is an experimental control in the original study, not an image or sound generated for this lecture.','Familiar and unfamiliar recordings came from different populations, so population-specific call structure remains a possible contribution.'])
add('Signal matching confirms a ground stimulus','alarm07','alarm_controls','2(a)','Paired microphone and geophone matched-filter output.', '''The familiar-call experiment monitored a microphone and geophone during each seismic playback. A **matched filter** compares a recording with the known stimulus pattern, allowing a weak copy of the stimulus to be distinguished from unrelated background noise.

The stimulus-aligned peak appeared in the geophone record without a corresponding microphone peak above the study’s contamination criterion. Trials with evidence of sufficient airborne coupling were excluded before the behavioral comparison.

The paired measurements strengthen the case that observed responses were triggered by a ground-delivered signal rather than its ordinary airborne counterpart. They do not eliminate every possible unrecorded acoustic signal at each animal’s ears, and they do not distinguish foot mechanoreception from bone-conducted input. Physical stimulus isolation and neural pathway identification are separate experimental questions.''', ['The filter was checked against each trial’s background noise rather than one assumed constant noise environment.','A peak is informative only when its timing and pattern match the stimulus, since unrelated animal movement also produces ground transients.','The source calibrated a leakage criterion using an assumed comparable auditory reference; an elephant seismic threshold was not directly measured.'])
add('Familiar alarms elicit stronger defensive responses','alarm07','alarm_response','3','Vigilance and herd-spacing changes for familiar calls.', '''The familiar alarm-call treatment produced increased vigilance and reduced herd spacing after playback. Published spacing estimates changed from approximately 0.91 to 0.36 body lengths, linking a ground-delivered signal to a coordinated tightening of the group.

The joint behavioral change was established for familiar calls, whereas the control and unfamiliar-call treatments did not produce an equally secure overall effect. That comparison supports differential responses to different biological seismic signals, rather than indiscriminate reaction to any ground vibration.

The outcome does not establish a neural representation of caller identity. Familiar calls also differed in their frequency modulation, and the experiments did not independently manipulate familiarity and urgency. The behavior is therefore consistent with recognition or graded threat assessment, while the basis of the discrimination remains unresolved.''', ['A body length is a spacing unit tied to animal size; it communicates group organization without implying meter-level precision for every individual.','Vigilance included behaviors such as freezing, scanning and lifting a foot rather than a single uniquely diagnostic sensory act.','A weaker response to an unfamiliar call does not mean that the signal was inaudible or that elephants cannot learn its relevance.'])
add('Frequency contours leave recognition unresolved','alarm07','alarm_contours','4','Published familiar and unfamiliar rumble frequency contours.', '''The alarm-call investigators extracted frequency contours to compare the structures of familiar, unfamiliar and control stimuli. A **frequency contour** describes how a call’s dominant frequency changes over its duration, rather than only reporting its average frequency.

Familiar alarm rumbles had a larger frequency range and greater modulation than the unfamiliar examples. The warble control had lower frequency and a smaller, more regular modulation pattern, despite occupying a broadly similar low-frequency domain.

These acoustic differences provide alternative explanations for the behavioral contrast: recipients may respond to caller familiarity, to stronger threat-related modulation or to both. Establishing identity recognition would require matched or systematically manipulated call features. The existing experiments demonstrate discrimination of the supplied stimuli without isolating the exact sensory feature or neural computation responsible.''', ['The original contours compare the second harmonic of the alarm calls with the fundamental of the warble control, so those plotted components are not equivalent harmonics.','Modulation is variation over time; two signals can share an average frequency while having different temporal contours.','The paper’s reported alternatives should remain alternatives rather than becoming an asserted memory or recognition circuit.'])
add('Seismic noise can act as an environmental cue','noise21','noise_stimuli','1(a–d)','Original elephant, white-noise and combined playback tracks.', '''Mortimer and colleagues tested seismic information beyond elephant alarm communication in wild African elephants in Kenya. A **cue** provides usable environmental information without necessarily being produced to communicate; a **signal** is associated with communication between sender and receiver.

The treatments were recorded elephant-generated vibration, artificial white noise and their combination. Each 6 min track contained 2 min of silence, 2 min of treatment and 2 min of silence, separating baseline, stimulation and subsequent behavior.

Recorded ground and airborne channels checked the delivered stimulus. Repeated elephant segments and noise controls tested whether vibration type affected the response rather than vibration presence alone. White noise is a simplified human-generated stimulus, so responses cannot automatically be generalized to every road, railway or construction vibration.''', ['White noise here describes the study’s broad-frequency experimental noise, not a naturally recorded truck or train.','The buried source delivered the tracks mechanically, and geophone recordings checked their propagation through the substrate.','A mixture changes both temporal continuity and source composition, so it is not a perfectly selective manipulation of perceived risk.'])
add('Human-generated components promote retreat','noise21','noise_retreat','2(b–c)','Distance moved across playback and control periods.', '''Mortimer and colleagues observed movement away from the trial location during treatments containing human-generated seismic noise. The combined elephant-plus-noise treatment produced a particularly strong retreat pattern, while elephant-only vibrations produced less movement away.

The buried source began about 17 m from the focal elephant on average. Movement coding was capped at 2 m per 30 s interval, so the plotted response expresses a standardized movement measure rather than exact cumulative travel distance.

The treatment differences support detection and discrimination of ground-borne noise with behavioral consequences consistent with risk avoidance. They do not establish that the elephants recognized a specific human activity. Movement after the stimulus also need not represent direct localization of the buried source, because departure can reflect a more general decision to leave the area.''', ['Repeated silent periods distinguish behavior during stimulation from behavior before and after it.','Spacing repeat treatments by at least five days reduced repeated-exposure effects on the same family group.','Distance coding limits very rapid departures, so the graph should not be read as an uncapped estimate of every meter traveled.'])
add('Freezing and scanning accompany noise responses','noise21','noise_vigilance','3(a–b)','Head-scanning and freezing time budgets.', '''The seismic-noise experiments separately measured head scanning and freezing, which are behavior categories rather than direct recordings of sensory processing. **Freezing** denotes a temporary cessation of movement; scanning involves changes in head orientation.

Treatments containing human-generated noise increased these behaviors during the playback period compared with relevant silent periods. The joint changes in movement, scanning and freezing provide a richer description of the response than retreat alone.

Freezing could reduce self-generated ground noise, while scanning could alter available directional information. Those proposed functions were not isolated experimentally. The findings establish context-dependent behavior following seismic stimulation, not a demonstrated receptor channel, a brainstem computation or a uniquely seismic listening posture. Noise can be both a source of interference and a cue about possible environmental risk.''', ['A time budget measures how much of an observation interval is assigned to a behavioral category.','The reported behaviors were measured under the same playback timing, linking them to a controlled change in the environment.','Human disturbance can change both received information and decisions about remaining at a site, and the experiment did not selectively separate those consequences.'])
add('Seismic recordings support precise source estimates','seismic21','seismic_locations','7(a–b)','Original acoustic and seismic source-location estimates.', '''Reinwald and colleagues recorded wild elephant rumbles with synchronized acoustic and seismic stations surrounding a Kenyan waterhole. **Time difference of arrival** compares when the same event reaches separate sensors; source estimates used those delays and a propagation model.

Stations were up to 360 m apart. Reported mean localization residuals were about 4.45 m for the probabilistic seismic method and 5.18 m for its acoustic counterpart; combining both channels increased the residual to about 11.59 m in this dataset.

A residual measures agreement with the model’s timing constraints, not an independently measured position error for every elephant. Camera confirmation was available for one event. The results support conservation monitoring and spatial information in the recordings, but they do not show that elephants implement the algorithm or measure their own seismic localization accuracy.''', ['Different propagation speeds and frequency filtering affect how the same rumble is represented in air and ground.','The method selected events with adequate signal at all stations, so its performance does not establish equal accuracy for weak or noisy rumbles.','An instrument localization algorithm can quantify available physical information without identifying the neural computations used by an animal.'])
assert len(slides)==44
# Give the developmental measurement its corresponding original quantitative panel.
slides[1]['primary_figure_height']=1.9
slides[1]['layout']='figures-right';slides[1]['figures']=[slides[1].pop('figure'),fig('brain25','brains_mass','1(E–F)','Brain weights and neonatal-to-adult brain proportions.')]
for idx in [3,4]:
 oldfigure=slides[idx].pop('figure')
 anatomy=fig('brain25','brain_mri' if idx==3 else 'brain_cb_mri','2(A–E)' if idx==3 else '4(A–D)','Cortical tissue boundaries.' if idx==3 else 'Cerebellar anatomy and proportions.')
 slides[idx]['layout']='figures-right'
 slides[idx]['primary_figure_height']=2.1
 slides[idx]['figures']=[anatomy,oldfigure]
 slides[idx]['cite']+='; '+cites['brain25']
 slides[idx]['refs'].append(refs['brain25'])
take=[('Brain organization.','Brain mass, regional volume and neuron number are different measurements; most counted elephant neurons are cerebellar.'),('Sensory and motor maps.','Trigeminal trunk maps and facial motor subdivisions are specialized anatomical proposals, not complete functional circuit maps.'),('Low-frequency hearing.','A trained Asian elephant detected 16 Hz at 65 dB SPL and localized brief broadband sources around one degree.'),('Candidate seismic routes.','Foot Pacinian corpuscles and bone conduction supply anatomical and mechanical support, but their necessity for seismic behavior remains untested.'),('Controlled playback.','Ground-delivered alarm and noise stimuli change behavior; microphone controls are essential for excluding airborne leakage.'),('Discrimination and inference.','Different call and noise responses do not by themselves isolate caller recognition, threat meaning or a specific neural computation.')]
usedkeys=['brain14','brain25','trigeminal24','motor22','foot07','hearing82','bone26','playback06','alarm07','noise21','seismic21']
spec={'lecture':48,'theme':'atlantic-ink-pearl','content_slides':44,'title_height':3.65,'title_refs':[refs['motor22']],'title_image':fig('motor22','title_elephants','3(A)','Asian and African elephants in the original study.'),'slides':slides,'takeaways':{'cite':'Heffner & Heffner (1982); Bouley et al. (2007); Mortimer et al. (2021)','refs':[refs[k] for k in usedkeys],'items':[{'lead':a,'text':b} for a,b in take]}}
(base/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
print('44 content slides written; words:',min(len(' '.join(s['body']).split()) for s in slides),max(len(' '.join(s['body']).split()) for s in slides))
