from pathlib import Path
import json,re
root=Path(__file__).resolve().parent
R=json.loads((root/'references.json').read_text())
C={'L':'Liu & Wang (2003)','A':'Aragona et al. (2003)','M':'Amadei et al. (2017)','B':'Berendzen et al. (2023)','R':'Loth et al. (2025)'}
F={}
def fig(k,r,num,desc):F[k]={'path':'figures/'+k+'.png','kind':'article','caption':C[r].replace(' et al.','')+', Fig. '+num+'. '+desc,'source_url':R[r].split()[-1]}
for a in [('l1','L','1','D2-type agonist preference and receptor-blockade conditions'),('l2','L','2','Oxytocin infusion and antagonist treatments'),('l3','L','3','Accumbens injection sites and the published anatomical reference'),('l4','L','4','Local quinpirole dose responses and receptor blockade'),('l5','L','5','Local oxytocin dose responses and receptor-selective blockade'),('a1','A','1(A–B)','Male partner preference after dopamine drug treatments'),('a2','A','2(A–D)','Dopamine-related staining in male vole accumbens'),('a3','A','3(A–C)','Sampled regions and dopamine metabolite measurements'),('a4','A','4(A–B)','Local dopamine antagonism and agonism'),('m1','M','1(a–g)','Affiliation trajectories and behavior-dependent coherence'),('m2','M','2(a–i)','Cross-frequency coupling during social interactions'),('m3','M','3(a–o)','Coupling changes and subsequent huddling latency'),('m4','M','4(a–e)','Pathway targeting, synaptic responses, and preference'),('m4ab','M','4(a–b)','Prefrontal expression and accumbens projection terminals'),('m4c','M','4(c)','Light-evoked excitatory current and AMPA blockade'),('m4de','M','4(d–e)','Stimulation controls and partner preference'),('b1','B','1(A–C)','Published CRISPR preparation and receptor-null alleles'),('b2','B','2(A–E)','Receptor-binding validation and anatomical controls'),('b3','B','3(A–H)','Partner preference and attacks in receptor-null animals'),('r1','R','1(A–F)','Accumbens receptor transcripts and species comparisons'),('r1a','R','1(A)','Prairie vole accumbens receptor-transcript fluorescence'),('r2','R','2(A–C)','Receptor co-expression classes across accumbens regions'),('r3','R','3(A–I)','Pairing, partner preference, and receptor co-expression'),('r3d','R','3(D)','Transcript co-labeling in naïve and paired prairie voles'),('r4','R','4(A–C)','Cell-class proportions before and after pairing'),('r5','R','5(A–D)','Receptor transcripts across molecular cell classes')]:fig(*a)
P={'path':'photos/prairie_vole.png','kind':'web','caption':'Photo: Prairie vole (Microtus ochrogaster).','credit':'Nastacia Goodwin','license':'CC BY-SA 4.0','source_url':'https://commons.wikimedia.org/wiki/File:Prairie_Vole_Nastacia_Goodwin_CC_BY-SA.png'}
S=[]
def add(title,k,r,text,anatomy=None,extra=None):
 b=text.strip().split('\n\n');refs=[R[r]];fs=[F[k]]
 if anatomy:
  fs.append(F[anatomy]);a='R' if anatomy.startswith('r') else 'M'
  if R[a] not in refs:refs.append(R[a])
 s={'title':title,'layout':'figures-right' if anatomy else 'figure-right','body':b,'cite':C[r],'refs':refs,'transcript':[[re.sub(r'\*\*|_', '',p),[extra]] if i==0 and extra else re.sub(r'\*\*|_', '',p) for i,p in enumerate(b)]}
 if anatomy:s['figures']=fs
 else:s['figure']=fs[0]
 S.append(s)
add('Partner preference measures selective social contact','b3','B','''A **partner preference** is greater affiliative contact with a familiar mating partner than with an unfamiliar animal. Prairie voles, _Microtus ochrogaster_, are studied because adults can form enduring selective attachments after living with a mate.

The laboratory assay gives the test animal access to its partner and an opposite-sex stranger. Researchers measure **huddling**, sustained side-by-side body contact, rather than assuming that entering a social chamber establishes an attachment.

Berendzen and colleagues measured preference after seven days of cohabitation using two apparatus designs. Preference provides an operational measure of selectivity, but one test does not establish every feature of a lifelong pair bond, mating exclusivity, or the animal’s subjective experience.''',extra='Selective contact must be compared with contact toward another available animal; total social contact alone does not identify a partner preference.')
add('The familiar partner is compared with a stranger','b3','B','''The **partner** is the individual previously housed with the subject, while the **stranger** is a previously unfamiliar potential mate. Both are present during the preference test, allowing selective affiliation to be separated from a general willingness to approach others.

Berendzen and colleagues used a branched apparatus and a linear apparatus with two partitions. Subjects could move between the stimulus animals, and investigators recorded time spent huddling with each rather than measuring only spatial proximity.

A consistent preference across different apparatus arrangements reduces dependence on one particular arena geometry. The assay still combines recognition, motivation, locomotion, and contact behavior, so changes in preference require additional controls before they can be assigned to one sensory or neural process.''')
add('Cohabitation duration changes the experimental question','l1','L','''**Cohabitation** means living together during a defined exposure period. Liu and Wang paired sexually naïve female prairie voles with males for six hours without mating, then measured partner and stranger contact during a three-hour preference test.

Control females did not acquire a clear partner preference under this short nonmating condition. Pharmacological treatments could therefore be tested for their ability to enable a selective preference when the usual control exposure was insufficient.

This design asks whether a manipulation facilitates preference formation, rather than whether it erases an established long-term bond. Its six-hour exposure must not be treated as equivalent to the seven-day pairing used in the later genetic study, because time and sociosexual experience differ.''')
add('Prairie and meadow voles differ in selective affiliation','r3','R','''The meadow vole, _Microtus pennsylvanicus_, provides a closely related species comparison. Loth and colleagues used the same general partner-versus-stranger framework to compare social behavior and accumbens receptor expression across prairie and meadow voles.

Paired prairie voles spent more time huddling with their partner than with a novel animal. Meadow voles in the tested conditions did not display the same selective partner preference, despite having opportunities for social contact.

The comparison concerns the measured pattern of selective affiliation, not an absence of social behavior in meadow voles. Species differences in receptor transcripts are correlates of this behavioral contrast; a molecular difference cannot alone establish which cells cause the species difference or whether every wild individual follows the laboratory pattern.''')
add('Preference is not simply increased social activity','r3','R','''A test animal may spend considerable time in social chambers without preferentially contacting one individual. Loth and colleagues therefore measured social-chamber occupancy separately from huddling with the partner and stranger.

Prairie voles showed partner-selective huddling, whereas differences in social-chamber time also depended on sex and species. The two measurements capture related but distinct aspects of behavior: social approach and selective affiliative contact.

This distinction prevents an increase in general approach from being mislabeled as stronger attachment. Drug and circuit studies likewise need movement or exposure controls, because a subject that explores less, encounters one stimulus more often, or changes its overall activity may produce altered contact time without a selective change in bonding.''')
add('The accumbens is a localized target within the forebrain','l3','L','''The **nucleus accumbens** is a forebrain region implicated in reward-related learning and social affiliation. Liu and Wang targeted it with bilateral microinjections to test whether oxytocin and dopamine effects could be localized rather than attributed to the entire brain.

They injected 200 nanoliters per side and verified placement in histological sections after behavioral testing. Most successful injection sites were in the accumbens shell, a subdivision distinguished from the adjacent core in the published anatomical reference.

Regional targeting narrows the anatomical interpretation, but an injection still reaches a tissue volume containing multiple cell types and connections. It does not identify a single receptor-bearing neuron or prove that the compound remains confined to every boundary of the intended region.''')
add('Dopamine-related proteins label accumbens innervation','a2','A','''**Dopamine** is a neurotransmitter involved in modulation of neural activity. Aragona and colleagues examined male vole accumbens tissue using staining for tyrosine hydroxylase and the dopamine transporter, proteins associated with dopamine synthesis and handling.

The **dopamine transporter** participates in uptake of extracellular dopamine, while **tyrosine hydroxylase** contributes to catecholamine synthesis. Staining was especially prominent in rostral accumbens regions, providing anatomical evidence for a dopamine-associated neural substrate at the behavioral injection sites.

Protein staining establishes the distribution of labeled tissue, not the moment-to-moment release of dopamine during mating. Tyrosine hydroxylase is not exclusively a dopamine marker, so the complementary transporter staining strengthens the interpretation without turning the images into a direct measurement of transmitter release.''')
add('Accumbens receptor transcripts can share a cell','r1','R','''A **transcript** is an RNA copy produced from a gene. Loth and colleagues used multiplex fluorescent in situ hybridization to detect oxytocin-receptor transcripts, Oxtr, alongside dopamine-receptor transcripts, Drd1 and Drd2, in accumbens tissue.

The method labels different transcript targets in separate fluorescent channels while DAPI identifies nuclei. The published preparation includes low-magnification tissue views and higher-magnification views with scale bars of 200 and 50 micrometers, respectively.

Detection within a cell supports possible receptor co-expression, but RNA is not a direct assay of membrane receptor protein or receptor activity. The anatomical overlap supplies a candidate cellular basis for interactions; it does not establish that oxytocin and dopamine signals were simultaneously active during a particular social encounter.''')
add('Receptor expression varies across accumbens subdivisions','r1','R','''The accumbens contains a core and medial and lateral shell subdivisions. Loth and colleagues quantified receptor-transcript-positive cells separately in these regions rather than treating the entire accumbens as one homogeneous population.

Prairie voles had more Oxtr-positive cells than meadow voles across all three subdivisions. Meadow voles had more Drd2-positive cells, while the proportion of Drd1-positive cells did not differ consistently between the species.

A regional population difference can reflect the number of expressing cells rather than a uniform change in every neuron. These maps therefore refine earlier tissue-level receptor comparisons, but they cannot assign a behavioral function to a subdivision without an intervention that tests the relevant cells or connections.''')
add('Co-expression prevents a simple D1-versus-D2 dichotomy','r2','R','''**Co-expression** means that a cell contains more than one measured transcript. Loth and colleagues classified accumbens cells into mutually exclusive combinations of Oxtr, Drd1, and Drd2, including cells expressing both dopamine-receptor transcripts.

Oxtr occurred in Drd1-positive, Drd2-positive, and Drd1-plus-Drd2 populations. Prairie voles showed enrichment of several Oxtr co-expressing combinations, particularly in the lateral shell, rather than restricting oxytocin-receptor transcripts to one dopamine-receptor class.

The result prevents a tissue-level D1-versus-D2 distinction from being interpreted as two completely separate cellular pathways. Transcript combinations identify candidate signal-convergence sites, but they do not measure how receptor activation changes membrane potential or establish which combination is responsible for forming a partner preference.''')
add('Dopamine blockade prevents male partner preference','a1','A','''An **antagonist** interferes with receptor activation. Aragona and colleagues administered the dopamine antagonist haloperidol to male prairie voles before a 24-hour mating and cohabitation period, then measured selective contact in a preference test.

Control males developed greater contact with their partner than with the stranger. Haloperidol-treated males did not show the same preference, although the investigators did not find corresponding disruption of mating or general locomotor activity in the tested conditions.

The intervention supports dopamine-receptor involvement in preference formation during this exposure window. Because the drug was administered before pairing and was not restricted to one molecular receptor subtype, the result does not isolate recognition, reinforcement, or later preference expression as the only affected process.''',anatomy='r1a')
add('Dopamine agonism can facilitate preference without mating','a1','A','''An **agonist** activates a receptor-associated response. Aragona and colleagues administered apomorphine, a dopamine agonist, to male prairie voles before six hours of cohabitation in which mating did not occur.

A low dose promoted selective contact with the familiar partner, whereas the tested higher dose did not produce the same preference. The behavioral effect therefore depended on dose rather than increasing monotonically with stronger drug exposure.

Facilitation under a normally insufficient exposure supports a role for dopamine signaling in acquiring selective affiliation. It does not establish that any dopamine increase creates a bond, nor does a nonselective agonist identify the exact receptor subtype or endogenous pattern of neural activity that normally carries the effect.''',anatomy='r1a')
add('Mating-related dopamine turnover is an indirect measure','a3','A','''**Dopamine turnover** describes metabolism of dopamine and can be estimated from the relationship between dopamine and its metabolites in tissue. Aragona and colleagues compared accumbens samples from control, nonmated, and mated male voles.

The reported accumbens turnover estimate was approximately 33 percent higher after mating, but the study did not establish that difference as a reliable group effect. The authors treated it as suggestive of altered dopamine activity rather than a definitive release measurement.

A tissue sample integrates chemical content over a region and sampling interval. It cannot reveal the timing of an individual dopamine transient, identify the active terminal, or distinguish every process affecting synthesis, release, uptake, and metabolism; the behavioral receptor manipulations provide a different kind of evidence.''',anatomy='r1a')
add('Local dopamine blockade narrows the anatomical claim','a4','A','''Aragona and colleagues injected haloperidol directly into the male nucleus accumbens before mating-associated cohabitation. The local treatment used four nanograms per side, allowing receptor blockade to be assessed at a specific forebrain target.

Vehicle-treated males developed a partner preference, whereas males receiving the local antagonist did not. Measures of mating and movement did not account for the loss of selective contact under the tested conditions.

This result localizes an important component of the systemic drug effect to accumbens tissue. It remains a regional pharmacological intervention: drug diffusion and the presence of multiple dopamine-receptor classes prevent the experiment from identifying one neuron type or proving that only one accumbens subdivision contributes to formation.''',anatomy='r1a')
add('Local agonist facilitation depends on dose and site','a4','A','''Aragona and colleagues injected apomorphine into the male accumbens before six hours of nonmating cohabitation. A dose of 0.04 nanograms per side facilitated partner preference, whereas four nanograms did not produce the same effect.

The low accumbens dose also failed to facilitate preference when delivered into the caudate putamen, a neighboring dopamine-associated striatal region. Regional placement therefore mattered in addition to the amount of agonist delivered.

The comparison supports anatomical specificity rather than a general motor or whole-brain dopamine explanation. It does not establish a universal optimal dopamine level, because an injected agonist differs from endogenous transmitter release and may recruit receptor populations differently as dose and tissue distribution change.''',anatomy='r1a')
add('D2-type activation facilitates female partner preference','l1','L','''Liu and Wang tested the D2-type agonist **quinpirole** in female prairie voles. They administered five micrograms systemically before six hours of cohabitation without mating, followed by a three-hour partner preference test.

Control females divided contact more evenly between partner and stranger, whereas quinpirole-treated females preferentially contacted the familiar male. Co-administration of the D2-type antagonist eticlopride prevented the agonist-induced preference.

The receptor-family comparison supports D2-type involvement in facilitation under this short exposure condition. D2-type pharmacology includes related receptor subtypes, so the experiment must not be treated as a molecularly exclusive test of Drd2 protein or a measurement of how a single identified accumbens neuron responds during social contact.''',anatomy='r1a')
add('Oxytocin blockade interrupts dopamine-induced preference','l1','L','''**Oxytocin** is a neuropeptide, a signaling molecule composed of a short amino-acid chain. Liu and Wang combined systemic quinpirole with central delivery of an oxytocin-receptor antagonist to test whether dopamine-induced preference depended on another signaling system.

Quinpirole alone facilitated preference after six hours without mating. Adding the oxytocin antagonist prevented that preference, even though cage-entry frequency did not differ in a way that explained the selective-contact result.

The experiment establishes a pharmacological dependence between the two systems within the tested time window. It does not show that dopamine physically binds an oxytocin receptor, identify the location of the interaction, or establish whether the receptor signals converge within one cell rather than across a connected network.''',anatomy='r1a')
add('Central oxytocin infusion facilitates female preference','l2','L','''Liu and Wang infused oxytocin into the lateral ventricle with an osmotic minipump. The solution contained one nanogram per microliter and flowed at 0.5 microliters per hour, providing sustained central exposure rather than a brief regional injection.

After six hours of cohabitation without mating, oxytocin-treated females spent more side-by-side contact time with the familiar partner than with the stranger. Vehicle-infused controls did not develop the same selective preference under that exposure.

The result supports central oxytocin-sensitive facilitation of partner preference, but ventricular infusion cannot assign the effect to a specific nucleus. Its anatomical interpretation therefore differs from the later accumbens microinjections, and its concentration must not be read as a direct measurement of natural oxytocin release.''')
add('D2-type blockade prevents oxytocin-induced preference','l2','L','''Liu and Wang combined central oxytocin infusion with the D2-type antagonist eticlopride. This tested the reverse dependency from the earlier experiment: whether oxytocin-induced preference still emerged when D2-type signaling was blocked.

Oxytocin alone facilitated selective contact after six hours of nonmating cohabitation. Co-infusion of eticlopride at ten nanograms per microliter prevented that preference, as did co-infusion of the oxytocin-receptor antagonist.

Reciprocal blockade supports interaction rather than two completely independent routes to the same behavior. It still does not establish the ordering of intracellular events, prove that both receptors are on one neuron, or demonstrate that lifelong elimination of a receptor must have the same effect as acute antagonist exposure.''',anatomy='r1a')
add('Histology places the interaction near accumbens shell','l3','L','''Liu and Wang localized the interaction with bilateral accumbens microinjections. Histological verification placed most injection sites within the shell, alongside an anatomical reference distinguishing shell, core, and the neighboring caudate putamen.

Each side received 200 nanoliters, and placement was checked after behavior rather than assumed from the planned stereotaxic coordinates. Animals with misplaced cannulae were excluded from the regional analysis.

Verification connects a behavioral intervention to the tissue actually reached by the injection. It does not provide a microscopic map of drug concentration, exclude every contribution from adjacent tissue, or establish that the shell contains one uniform population of oxytocin- and dopamine-responsive cells; newer transcript maps reveal substantial cellular diversity.''',anatomy='r1a')
add('Accumbens quinpirole has a threshold-dependent effect','l4','L','''Liu and Wang injected quinpirole directly into female accumbens tissue before six hours of nonmating cohabitation. Doses of 0.001 and 0.01 nanograms per side did not produce a clear partner preference.

Higher doses of 0.1 and one nanogram per side facilitated selective contact with the familiar male. This dose comparison connected local D2-type agonism with a behavioral effect at concentrations ineffective in the lower-dose conditions.

The result supports regional pharmacological facilitation and a dependence on treatment strength. It does not measure endogenous dopamine concentration, define a natural physiological threshold, or demonstrate that progressively increasing D2-type activation will continually strengthen an established bond beyond the tested range.''',anatomy='r1a')
add('Local oxytocin blockade prevents quinpirole facilitation','l4','L','''Liu and Wang combined one nanogram of accumbens quinpirole with ten nanograms of oxytocin-receptor antagonist per side. The combination tested whether the earlier central-blockade interaction could be reproduced within the regional injection target.

Quinpirole alone facilitated partner preference, whereas concurrent local oxytocin-receptor blockade prevented it. Local eticlopride also prevented the quinpirole-induced preference, providing a receptor-family control for the agonist effect.

The interaction therefore has an important accumbens component under these experimental conditions. Neither antagonist result identifies a molecular receptor complex or a single convergence neuron; local tissue contains interconnected populations, and receptor dependence can arise through network interactions as well as co-expression within one cell.''',anatomy='r1a')
add('A neighboring dopamine-rich region does not substitute','l4','L','''Liu and Wang delivered one nanogram of quinpirole into the caudate putamen as a regional comparison. This structure is adjacent to the accumbens and contains dopamine-related signaling systems, but it is not the same injection target.

The caudate-putamen treatment did not facilitate partner preference after six hours of nonmating cohabitation. The corresponding accumbens dose did, supporting a difference between the regions rather than a response to any nearby striatal agonist injection.

A negative site control narrows the anatomical claim but does not prove that the comparison region has no role in social behavior. It establishes failure of this specific treatment, dose, and exposure schedule to reproduce the measured preference, rather than absence of every possible contribution to affiliation.''',anatomy='r1a')
add('Local oxytocin facilitation is not monotonic with dose','l5','L','''Liu and Wang injected oxytocin directly into the female accumbens before six hours of nonmating cohabitation. One nanogram per side facilitated partner preference, whereas 0.1 and ten nanograms did not produce the same selective-contact result.

The effective intermediate dose prevents the experiment from being interpreted as a simple relationship in which more oxytocin always produces more attachment. Vehicle controls also failed to develop preference under the short nonmating exposure.

The dose response establishes sensitivity to treatment amount without identifying the reason that the higher dose was ineffective. Different receptor recruitment, spatial spread, or network effects remain possible explanations, but this experiment did not measure those mechanisms and cannot justify selecting one as the established cause.''',anatomy='r1a')
add('D2-type and D1-type blockade have different outcomes','l5','L','''Liu and Wang combined the effective one-nanogram accumbens oxytocin dose with receptor-directed antagonists. They compared D2-type blockade with eticlopride against D1-type blockade with SCH 23390, each at ten nanograms per side.

Eticlopride prevented oxytocin-induced preference, whereas SCH 23390 did not prevent selective partner contact under these conditions. Oxytocin-receptor blockade also prevented the effect, establishing a receptor-selective pattern within the same behavioral preparation.

The contrast supports a D2-type contribution to this form of oxytocin facilitation. It does not establish that D1-type receptors are irrelevant to every phase of bonding, nor does it make drug-family specificity equivalent to deletion of one gene or identification of a single receptor-bearing cell.''',anatomy='r1a')
add('A second site control constrains oxytocin localization','l5','L','''Liu and Wang administered one nanogram of oxytocin into the cingulate cortex as a regional control. This comparison region contains oxytocin receptors but differs from the accumbens target used for the effective treatment.

Cingulate administration did not facilitate partner preference after six hours without mating. The corresponding accumbens treatment did, providing evidence that the presence of oxytocin receptors alone is insufficient to predict the behavioral outcome of an injection.

The comparison supports anatomical organization of the oxytocin-sensitive effect. It does not eliminate the cortex from the broader attachment network: a particular local oxytocin injection can fail while cortical projections still participate in social learning or modulation of accumbens activity under different experimental conditions.''',anatomy='r1a')
add('Movement controls constrain the drug interpretation','l4','L','''A preference score can change if a drug reduces exploration or prevents the subject from reaching one stimulus. Liu and Wang therefore measured cage-entry frequency during the three-hour partner preference test alongside side-by-side contact.

They did not find treatment-related entry-frequency differences that explained the partner-preference outcomes. Video review also confirmed the absence of mating during the six-hour exposure used for pharmacologically facilitated preference formation.

These controls separate the measured preference from coarse changes in locomotion or accidental mating exposure. They do not establish that every sensory, motivational, or motor variable was identical across groups; the justified conclusion is that the recorded movement and mating measures did not account for the observed selectivity.''',anatomy='r1a')
add('Reciprocal blockade supports functional convergence','l5','L','''The female pharmacology experiments establish reciprocal dependence: oxytocin antagonism prevents D2-type agonist facilitation, and D2-type antagonism prevents oxytocin facilitation. Local accumbens treatments reproduce both directions of that interaction.

Newer cellular maps locate Oxtr transcripts in several dopamine-receptor classes, including cells containing both Drd1 and Drd2. This anatomy supplies possible convergence sites without proving that those cells mediated the earlier pharmacological results.

The established finding is an interaction between receptor-sensitive processes during short-term preference formation. A particular intracellular pathway, receptor complex, or synaptic sequence remains untested by these experiments, and the later genetic findings require the necessity claim to remain tied to the acute treatment conditions.''',anatomy='r1a')
add('Recording population activity during social interaction','m1','M','**Local field potentials** are extracellular voltage signals reflecting activity in nearby neural populations. Amadei and colleagues recorded simultaneously from medial prefrontal cortex and nucleus accumbens while female prairie voles interacted with a male during six hours of cohabitation.\n\nVideo scoring identified mating, huddling, and self-grooming. Histological placement divided recordings into accumbens hits and nearby non-hits, allowing behavioral associations to be compared with an anatomical control rather than assuming every electrode sampled the intended circuit.\n\nHuddling latency varied across females, providing a quantitative measure of how quickly sustained affiliation emerged. Field recordings describe coordinated population activity; they do not identify which individual neurons released oxytocin or dopamine, and the observed signal cannot be assigned to one receptor class.',anatomy='m4ab')
add('Mating increases low-frequency coherence','m1','M','**Coherence** measures how consistently two signals maintain a frequency-specific relationship. During mating, prefrontal and accumbens field potentials displayed greater low-frequency coherence near five hertz than during huddling or self-grooming in the recorded females.\n\nSelf-grooming supplied a behavior with movement but without the same social interaction. Nevertheless, mating-related coherence was also observed in recordings outside the targeted accumbens region, making anatomical comparison essential to interpreting the effect.\n\nThe measured change establishes behavior-dependent coordination, but coherence alone does not distinguish direct communication from common inputs. Its occurrence at non-hit sites limits its specificity as a bonding mechanism; a more selective relationship between circuit activity and subsequent affiliation was sought through cross-frequency analysis.',anatomy='m4ab')
add('Slow prefrontal phase relates to fast accumbens activity','m2','M','**Phase–amplitude coupling** describes a relationship between the phase of a slower oscillation and the amplitude of a faster signal. Amadei and colleagues examined whether prefrontal oscillatory phase organized accumbens gamma activity during social interaction.\n\nThe principal relationship involved approximately five to six hertz prefrontal phase and eighty to eighty-four hertz accumbens amplitude. A net-modulation measure compared coupling in this direction with the reverse relationship between accumbens phase and prefrontal amplitude.\n\nTargeted recordings showed behavioral modulation that was less evident at non-hit sites. The direction of this statistical relationship suggests functional organization, but it does not demonstrate a monosynaptic connection, establish which transmitter carries the signal, or exclude a third region coordinating both recorded populations.',anatomy='m4ab')
add('Coupling predicts the latency to sustained affiliation','m3','M','Amadei and colleagues related each female’s net-modulation measure to the time at which sustained huddling emerged. Stronger average coupling during nonhuddling periods was associated with a shorter subsequent huddling latency within the six-hour recording session.\n\nThe relationship was evaluated across the full recording and the first sixty minutes, with baseline and non-hit recordings supplying comparisons. Coupling measured during huddling itself did not provide the same predictive relationship as activity measured outside the affiliative behavior.\n\nThis temporal association helps separate a candidate antecedent signal from activity that merely accompanies body contact. It remains correlational: females could differ in motivation, prior experience, or another unmeasured circuit property that influences both coupling and how rapidly they begin to huddle.',anatomy='m4ab')
add('Mating-related changes precede later huddling','m3','M','Within-session analysis asked whether coupling changed around mating and whether that change predicted subsequent affiliation. Net modulation was estimated in one-minute moving windows advanced in steps of one tenth of a minute during the recorded social encounters.\n\nChanges after mating, including the approximately two-minute interval after the event, were related to later huddling latency after accounting for baseline coupling. Comparable self-grooming events and non-hit recordings did not show the same pattern, supplying behavioral and anatomical comparisons.\n\nThe result links a defined sociosexual event to a later behavioral transition rather than only comparing session averages. It does not establish that mating necessarily produces attachment through this signal, nor that the coupling change is required; an experimental manipulation is needed to address causal sufficiency.',anatomy='m4ab')
add('Light evokes excitatory pathway transmission','m4c','M','**Optogenetics** uses a light-sensitive protein to influence neural activity. Amadei and colleagues expressed channelrhodopsin-2 in prefrontal neurons and illuminated their projection terminals in accumbens, linking a specified pathway to a controllable experimental input.\n\nChannelrhodopsin-2 is a light-gated ion channel: illumination opens the channel, depolarizes expressing membranes, and can drive terminal transmitter release. In brain slices, five-hertz light pulses evoked inward excitatory postsynaptic currents, measured in picoamperes.\n\nDNQX, an antagonist of AMPA-type glutamate receptors, suppressed these currents. AMPA receptors are glutamate-gated cation channels that support excitatory transmission. This control supports an excitatory glutamatergic projection, while the slice response alone does not show that its natural activity produces a partner preference in an intact animal.',anatomy='m4ab')
add('Stimulation is contingent on a social encounter','m4de','M','To test behavioral sufficiency, females encountered a caged male during approximately two and a half to three hours of exposure. The barrier prevented mating while permitting social interaction, separating stimulation-assisted preference from the usual mating-associated experience.\n\nFive- or six-hertz trains of five-millisecond light pulses were delivered when the female entered the social zone. Stimulation was available for up to one hour from the first social-zone entry, making pathway activation contingent on contact with the particular male.\n\nControl females expressed EYFP, a fluorescent reporter without the light-gated channel, and received the corresponding illumination procedure. Comparable stimulation durations and zone occupancy reduce exposure-based explanations. The manipulation still combines neural activation with social experience, so it cannot be interpreted as attachment induced in the absence of a partner.',anatomy='m4ab')
add('Pathway activation biases later partner preference','m4de','M','The following day, females were tested for three hours with the previously encountered male and a stranger. Channelrhodopsin-expressing subjects showed greater partner-directed affiliation than the fluorescent-reporter controls after the socially contingent stimulation procedure.\n\nThe published data show partner-over-stranger huddling in eighty-three percent of the stimulated group and thirty-six percent of controls. These percentages describe the tested samples; the group comparison and the individual paired contact measurements are presented in the original figure.\n\nThe experiment supports sufficiency of this patterned pathway activation to bias preference under the specified social conditions. It does not establish necessity, prove that natural coupling is generated by the same imposed pattern, or identify an obligatory oxytocin–dopamine mechanism for the behavioral effect.',anatomy='m4ab')
add('Pairing preserves broad receptor cell classes','r4','R','Loth and colleagues compared sexually naïve and paired voles using the same multiplex transcript-labeling strategy. Behavioral testing established partner preference in paired prairie voles before tissue analyses examined accumbens core and shell subdivisions.\n\nCell classes were defined by the presence or absence of Drd1, Drd2, and Oxtr transcripts. Across the tested groups, pairing did not produce a broad redistribution of the receptor-positive classes, despite the behavioral difference between naïve and paired animals.\n\nAn unchanged proportion of labeled cells does not mean that receptor signaling or synaptic physiology was unchanged. Cell counts, transcript abundance within each cell, membrane receptor protein, and transmitter release are different measurements. This result constrains claims about wholesale changes in cell-class composition rather than excluding experience-dependent molecular plasticity.',anatomy='r1a')
add('Oxtr transcripts are enriched in double-positive cells','r3d','R','Cells containing both Drd1 and Drd2 transcripts are described as double-positive dopamine-receptor cells. Loth and colleagues quantified Oxtr labeling within these classes rather than assuming dopamine receptor populations were mutually exclusive.\n\nAn RNA **punctum** is a localized fluorescent signal associated with a detected transcript target. Oxtr puncta were enriched in double-positive cells in both naïve and paired prairie voles, supplying a cellular candidate for interaction between oxytocin-sensitive and dopamine-sensitive processes.\n\nThe fluorescence preserves the published channel colors and spatial scale. Transcript co-labeling does not measure receptor binding, prove simultaneous activation, or establish a receptor complex. Connecting this candidate population to attachment would require a manipulation that isolates the cells and tests behavior while controlling general activity and social exposure.',anatomy='r1a')
add('Molecular cell classes refine the anatomical question','r5','R','**Single-nucleus RNA sequencing** samples RNA from isolated nuclei and groups cells according to expression profiles. Loth and colleagues compared receptor expression across molecularly identified accumbens cell classes rather than relying only on region-level averages.\n\nThe analysis distinguished fifteen primary cell types, including medium spiny neurons and interneuron populations. A **medium spiny neuron** is a principal striatal projection neuron; the molecular classes provide a finer map of candidate receptor-bearing populations within accumbens tissue.\n\nReceptor transcripts were distributed across multiple classes, preventing a simple identification of one universal oxytocin-responsive bonding cell. Molecular clustering is an anatomical and descriptive tool. It does not establish which population is recruited during mating, which cells receive a particular social signal, or which class is necessary for partner preference.',anatomy=None)
add('Detection methods yield different receptor estimates','r5','R','The same receptor can appear rare or common depending on the measurement method. Loth and colleagues found Oxtr labeling in approximately thirty-four to thirty-eight percent of cells by fluorescent in situ hybridization, but in approximately one percent by single-nucleus sequencing.\n\n**Dropout** is failure to detect a transcript that is present, especially when its abundance is low. Drd1 and Drd2 transcript levels were approximately ten to twenty times higher than several less abundant receptor targets, making detection sensitivity a substantial interpretive issue.\n\nThe discrepancy does not establish that the tissue contains two incompatible biological populations. It emphasizes that a sequencing-negative nucleus need not lack the receptor gene’s expression. Neither RNA method directly establishes membrane receptor abundance, and a negative transcript measurement must not be treated as proof that a cell cannot respond to oxytocin.',anatomy=None)
add('Independent receptor-null alleles test a genetic claim','b1','B','Berendzen and colleagues used CRISPR-based gene editing to disrupt Oxtr in prairie voles. **CRISPR** employs a guide RNA and a DNA-cutting enzyme to target a genomic sequence; repair can create mutations that prevent production of a functional receptor.\n\nThree independently generated lines carried different disruptive alleles, including a one-base insertion and a larger deletion. Outcrossing to wild-type animals and comparing independent lines reduced dependence on a single founder mutation or one shared unintended genetic change.\n\nA **null allele** is an allele that lacks normal gene function. The genetic approach asks whether animals developing without functional oxytocin receptors can form a measured partner preference. Its lifelong perturbation differs from administering a receptor antagonist to an otherwise developed adult during a short social exposure.',anatomy=None)
add('Binding assays verify loss of detectable receptor','b2','B','A **radioligand** is a radioactively labeled molecule used to measure binding sites in tissue. Berendzen and colleagues used iodine-125-labeled OVTA to examine oxytocin-receptor binding in wild-type and receptor-null vole brains.\n\nNull animals lacked the detectable binding seen in wild-type prefrontal cortex, accumbens, and central amygdala across the independent lines and both sexes. Adjacent acetylcholinesterase-stained sections supplied an anatomical comparison, while the original plots report binding density in arbitrary units.\n\nThis validation makes preserved behavior more informative than an unverified gene-editing claim. It supports loss of detectable receptor binding under the assay conditions, rather than measuring every possible downstream adaptation. The comparison also illustrates why RNA co-labeling and ligand binding answer different questions about receptor-bearing tissue.',anatomy=None)
add('Receptor-null animals retain selective partner huddling','b3','B','After seven days of cohabitation, male and female receptor-null prairie voles showed selective huddling with their partner. Berendzen and colleagues tested independent mutant lines in both branched and linear preference apparatuses.\n\nThe partner-versus-stranger comparison was retained, and the published individual data show the selective affiliation rather than only total contact time. Aggressive behavior was also measured; preservation of huddling preference should not be interpreted as proof that every social response was identical in mutants and controls.\n\nThe result demonstrates that detectable oxytocin-receptor function is not universally required for this preference outcome under seven-day pairing conditions. It does not establish that oxytocin has no influence in typical animals, that preference forms at the same rate, or that acute receptor blockade during six-hour exposure must have no effect.',anatomy=None)
add('Acute blockade and lifelong loss test different conditions','b3','B','The acute female pharmacology experiments used six-hour nonmating exposure, while the receptor-null study used seven-day cohabitation. One interfered with receptor-sensitive processes during a defined adult interval; the other tested animals that developed without normal receptor function.\n\nDevelopmental compensation, alternative signaling routes, different exposure durations, and pharmacological specificity are possible explanations for the contrasting outcomes. The genetic study does not establish which explanation resolves the discrepancy, and the earlier antagonist experiments do not exclude adaptation across development.\n\nThe defensible account is therefore conditional: accumbens oxytocin-sensitive and D2-type-sensitive processes interact in the short-exposure pharmacological paradigm, while receptor-null voles can express preference after longer pairing. A complete mechanism must explain both findings rather than treating one experimental design as a universal definition of attachment.',anatomy=None)

assert len(S)==44,len(S)
items=[('Selective affiliation:','Partner preference compares partner-directed huddling with stranger contact; social approach alone is insufficient.'),('Conditional receptor interaction:','Acute accumbens oxytocin and D2-type manipulations interact during short nonmating exposure.'),('Candidate cellular convergence:','Receptor transcript co-expression identifies possible interaction sites without proving receptor activity or behavioral causation.'),('Circuit sufficiency:','Socially contingent prefrontal–accumbens activation biases preference; coupling correlations alone establish neither necessity nor direct transmission.'),('Genetic qualification:','Oxytocin-receptor-null voles retain preference after seven-day pairing, limiting universal necessity claims.'),('Measurement and context:','Exposure duration, controls, receptor-family specificity, and RNA detection sensitivity determine the justified inference.')]
spec={'lecture':50,'theme':'harbor-blue-paper','content_slides':44,'title_image':P,'title_refs':[R['B']],'title_height':3.2,'slides':S,'takeaways':{'items':[{'lead':a,'text':b} for a,b in items],'cite':'Liu & Wang (2003); Amadei et al. (2017); Berendzen et al. (2023); Loth et al. (2025)','refs':list(R.values())}}
(root/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
(root/'references.json').write_text(json.dumps(R,indent=2,ensure_ascii=False)+'\n')
