"""Teaching-first Lecture 58, using original published PDF figures."""
import json,re
from pathlib import Path
b=Path(__file__).resolve().parent
refs=json.loads((b/'references.json').read_text());research=json.loads((b/'research.json').read_text())
years={'classic':2006,'kappa':2012,'interact':2016,'vasopressin':2009,'oxytocin':2022,'dopamine':2024,'motherhood':2023,'septum':2022,'transcript':2022,'separation':2023}
cites={k:research[k]['crossref']['author'][0]['family']+' et al. ('+str(y)+')' for k,y in years.items()}
slides=[]
def fig(k,n,f,desc):return dict(kind='article',path='figures/'+n+'.png',caption=cites[k]+', Fig. '+f+'. '+desc,source_url='https://doi.org/'+research[k]['doi'])
def add(title,k,n,f,desc,text,note=''):
 ps=text.strip().split('\n\n');assert len(ps)==3,(title,len(ps));assert '—' not in text
 slides.append(dict(title=title,layout='figure-left' if len(slides)%4==2 else 'figure-right',body=ps,figure=fig(k,n,f,desc),cite=cites[k],refs=[refs[k]],transcript=[re.sub(r'\*\*|_', '',p) for p in ps]+([note] if note else [])))
add('Established partners receive a different social response','classic','classic_aggression','5(a,b)','Aggression and affiliation toward partner and stranger.', '''A prairie vole **pair bond** is a durable, selective relationship with a particular mating partner. Aragona and colleagues compared male voles housed with male siblings with males that had lived with a female for two weeks. A female intruder was then introduced into the resident’s cage.

Bonded males attacked unfamiliar females but remained affiliative toward their own partners. **Affiliation** included approaching and huddling, or sustained side-by-side bodily contact. Sexually naive males investigated unfamiliar females without the intense aggression expressed by bonded residents.

**Selective aggression** therefore means that the response depends on the identity of the encountered animal. The same bonded male can accept his partner and reject another potential mate. This behavioral transformation links an established social relationship with the exclusion of unfamiliar animals.''')
add('Partner choice and stranger rejection are distinct','classic','classic_preference','1(a,b)','Partner-contact time after shell or core injections.', '''The **partner preference test** measures how a vole distributes contact between a familiar partner and an unfamiliar animal. Both stimulus animals are tethered in separate compartments, while the subject moves freely. Contact is recorded during a three-hour session rather than inferred from a single approach.

Aragona and colleagues used six hours of cohabitation without mating as a condition that ordinarily produced no partner preference. In contrast, 24 hours with mating produced preferential partner contact. The familiar animal’s identity becomes associated with a selective affiliative response.

A preference test measures affiliation, whereas a resident-intruder test measures responses to an animal entering the home cage. Testing both behaviors distinguishes attraction to the partner from rejection of strangers, two complementary components of maintaining a selective relationship.''')
add('Dopamine acts within a specific accumbens subregion','classic','classic_anatomy','2(a–d)','Histological locations of accumbens injections.', '''The **nucleus accumbens**, a ventral striatal structure involved in motivated behavior, contains distinguishable core and shell territories. Aragona and colleagues placed small injections into different territories and verified their locations in brain sections, connecting each pharmacological manipulation to its anatomical target.

The D2-like receptor agonist **quinpirole** induced partner preferences when delivered into the rostral shell. The effective dose included 0.04 ng. Delivery into the core or a more caudal shell location did not produce the same selective affiliation after six hours of nonmating cohabitation.

Rostral means toward the front of the brain; caudal means toward the rear. The anatomical comparison localizes dopamine-dependent preference formation within a heterogeneous structure. Dopamine’s behavioral effect depends on where its receptors are activated, rather than simply on a brain-wide increase in the transmitter.''')
add('D1 and D2 activation have opposing behavioral effects','classic','classic_receptors','3(a,b)','Opposing receptor manipulations during preference formation.', '''Dopamine receptors are membrane proteins that translate dopamine binding into intracellular signaling. **D1-like** and **D2-like** receptors belong to different receptor families. In this preparation, activating D2-like receptors promoted selective partner contact, while activating D1-like receptors opposed that response.

Quinpirole-induced preference was prevented by coadministration of the D1-like agonist SKF 38393 or the D2-like antagonist eticlopride. An **agonist** activates a receptor; an **antagonist** blocks its activation. Blocking D1-like receptors while stimulating D2-like receptors preserved a robust preference.

D1-like activation also blocked the preference normally produced by 24 hours of mating, while mating bouts remained comparable between groups. The receptor manipulation therefore changed the affiliative outcome of social experience. Formation of a preference depends on the balance between receptor systems within the rostral shell.''')
add('Extended pairing increases D1 receptor binding','classic','classic_binding','4(a–c)','Receptor autoradiography after two weeks of pairing.', '''After two weeks of cohabitation resulting in pregnancy, male prairie voles had approximately 60% greater D1-like receptor binding in the nucleus accumbens than sexually naive controls. **Receptor autoradiography** uses a radiolabeled ligand to locate and quantify binding sites in tissue sections.

The increase occurred in accumbens core and shell, while the comparison region, the caudate putamen, lacked the same increase. D2-like binding remained similar between groups. Exposure to a female for only 24 hours, with or without mating, did not produce the two-week D1-like binding pattern.

A partner preference can therefore appear before this longer-term receptor reorganization. The later increase supplies a biological change associated with established bonds and stranger rejection. Individual binding values also varied, so the population-level change contains differences among bonded animals rather than an identical response in every male.''')
add('D1 blockade suppresses stranger-directed aggression','classic','classic_aggression','5(a,b)','Receptor blockade during a resident-intruder test.', '''Aragona and colleagues injected receptor antagonists into the nucleus accumbens of males already bonded for two weeks. They then introduced an unfamiliar female during a resident-intruder test. This timing tested the expression of established stranger rejection, rather than the initial acquisition of a preference.

D1-like receptor blockade abolished the high aggression normally directed toward the stranger. D2-like blockade left selective aggression intact. The investigators also measured open-field movement and social investigation, and the reduced aggression was not explained by a general loss of locomotor activity.

The maintenance-associated response therefore depends on active D1-like signaling when the stranger is encountered. Combined with the binding increase, the intervention connects social experience, receptor reorganization and an observable defensive behavior. A receptor system that opposes initial preference formation later supports rejection of alternative social partners.''')
add('Kappa receptors contribute to social defense','kappa','kappa_photo','2(A–D)','Published photographs of aggression and affiliation.', '''**Kappa-opioid receptors**, abbreviated KORs, respond to the endogenous opioid peptide dynorphin. Resendez and colleagues tested their contribution to aggressive rejection in bonded prairie voles. The study scored attacks and affiliative contact separately during encounters with unfamiliar animals.

Aggression includes biting and lunging, whereas affiliation includes sustained side-by-side contact. Both male and female bonded voles expressed stranger-directed aggression, providing a basis for testing whether opioid signaling contributed to maintenance in both sexes rather than only in males.

Opioid receptor subtypes have different behavioral functions. The study compared kappa and mu receptor manipulations rather than treating all opioid signaling as equivalent. This distinction connects a specific receptor system with the aversive component of an established relationship while preserving affiliation as a separately measured social behavior.''')
add('Shell KOR blockade reduces aggression in both sexes','kappa','kappa_behavior','7(A–H)','Site-specific kappa blockade and social behavior.', '''Resendez and colleagues administered **nor-binaltorphimine**, a kappa-opioid receptor antagonist, into striatal subregions of pair-bonded prairie voles. Artificial cerebrospinal fluid supplied the local vehicle control. Subjects then encountered a same-sex unfamiliar intruder in a ten-minute behavioral test.

Blocking KORs in the nucleus accumbens shell reduced attack behavior in both males and females. The same intervention did not produce an equivalent reduction at all comparison sites. Affiliation and locomotion were measured alongside aggression, helping identify the behavioral function affected by the receptor blockade.

The shell thus participates in a receptor-specific mechanism of stranger rejection. In females, core KOR blockade instead increased aggression, emphasizing that neighboring territories can have different effects. Pair-bond defense is organized by the anatomical location and receptor subtype of the manipulated signal.''')
add('Anatomical controls distinguish shell from nearby sites','kappa','kappa_sites','6(A–G)','Verified positions of shell, core and pallidal injections.', '''A local infusion can alter behavior only if the relevant neural tissue receives the drug. Resendez and colleagues reconstructed injection locations in sections and compared shell placements with placements in the accumbens core and other striatal or pallidal regions.

The shell is anatomically distinguishable from the core and the ventral pallidum. Histological localization placed the effective aggression-reducing injections within shell tissue, whereas injections into adjacent territories produced different behavioral outcomes.

Anatomical verification strengthens the connection between KOR activation and a localized maintenance-associated response. The distinction is particularly consequential because core blockade had a different effect in females. A regional circuit account must preserve these site differences instead of assigning one behavioral function to the entire accumbens.''')
add('KOR activation can assign a negative social value','interact','interact_aversion','1(a–e)','Social pairing with local KOR activation.', '''Resendez and colleagues paired sexually naive males with a female for one hour, too briefly to create a reliable partner preference in vehicle controls. Before pairing, experimental males received 1 μg of the KOR agonist U50,488 within the nucleus accumbens shell.

During the later social-choice test, agonist-treated males avoided the female encountered during receptor activation and preferred the unfamiliar female. They also spent less time in the familiar female’s compartment. Total contact with the two females remained similar to that of controls.

The intervention changed how social contact was distributed rather than eliminating social motivation. **Valence** describes the positive or negative value assigned to a stimulus. The authors’ hypothesis is that KOR-dependent negative social valuation contributes to rejection of animals outside an established bond.''')
add('Bonding increases dopamine and dynorphin transcripts','interact','interact_genes','2(a–d)','Regional dopamine and opioid gene expression.', '''**Messenger RNA**, or mRNA, carries a gene’s information toward protein production. Resendez and colleagues used quantitative reverse-transcription measurements to compare dopamine and opioid-related transcripts after two weeks of opposite-sex cohabitation with those in sibling-housed voles.

In the ventral striatum, both bonded males and females had higher expression of **Drd1**, the gene encoding a D1 receptor, and **Pdyn**, the gene encoding the dynorphin precursor. The comparison separated ventral from dorsal striatal tissue, retaining the anatomical organization of the molecular change.

These coordinated changes supply a molecular association between dopamine receptor signaling and the endogenous ligand for KORs. Higher Drd1 and Pdyn expression associates the bonded state with both dopamine reception and production of the peptide that activates KORs.''')
add('KOR binding changes differently in males and females','interact','interact_binding','3(a–d)','Original striatal KOR autoradiographs and binding values.', '''The investigators measured kappa-opioid receptor binding after comparing the genes associated with bonding. Autoradiography sampled striatal territories in sibling-housed and pair-bonded males and females, allowing molecular expression and receptor-binding patterns to be assessed separately.

Bonded males had lower KOR binding in portions of the accumbens shell than nonpaired males. Females did not exhibit the same bonding-associated reduction. Before bonding, males had higher binding in several ventral striatal territories; after pairing, those sex differences were reduced.

Increasing dynorphin-related transcription can therefore accompany a decrease in measured receptor binding. Receptor number, ligand production and physiological sensitivity are different features of a signaling system. Bonded males can have fewer measured binding sites while expressing stronger KOR-mediated suppression of dopamine release.''')
add('Dopamine release depends on stimulation and location','interact','interact_dynamics','4(a–i)','Original voltammetric maps and striatal release measurements.', '''**Fast-scan cyclic voltammetry** detects rapid dopamine concentration changes with a carbon-fiber electrode. Resendez and colleagues applied electrical stimulation to prairie vole brain slices and compared responses in dorsal striatum, accumbens core and accumbens shell.

A single stimulus pulse produced the largest dopamine release in dorsal striatum and smaller release in the ventral territories. A 20-pulse stimulation increased release more strongly relative to the single-pulse response in the shell than in the dorsal region.

The relative amplification connects the shell’s dopamine signal with the temporal pattern of neural input. Brief isolated activation and burst-like stimulation need not recruit the same amount of transmitter. This physiological organization supplies a way for changing activity to alter receptor recruitment within a behaviorally relevant subregion.''')
add('Bonding enhances evoked dopamine release in the shell','interact','interact_release','5(a–h)','Dopamine release in nonpaired and pair-bonded slices.', '''After two weeks of pairing, the investigators compared electrically evoked dopamine release in bonded and nonpaired animals. Identical stimulation and recording procedures separated changes associated with social history from changes caused by using different physiological preparations.

A single stimulus pulse produced greater dopamine release in the accumbens shell of bonded males and females. The average increase was 34% in males and 99% in females. The dorsal striatum and accumbens core did not exhibit the corresponding bonding-associated increase.

The release change adds a physiological component to the increase in D1-related transcription. More dopamine becomes available within the territory whose receptors regulate selective aggression. Females had a larger relative release increase, although transmitter dynamics and attack intensity followed different sex-specific patterns.''')
add('Reproductive status modifies male defensive responses','interact','interact_reproduction','6(a–h)','Fecundity, selective aggression and shell dopamine release.', '''**Fecundity** refers to reproductive output or potential. Resendez and colleagues classified paired animals by the progress of pregnancy after two weeks of cohabitation, using offspring weight to estimate the timing of mating and fertilization relative to the start of pairing.

Males from pairs with earlier-established pregnancies displayed more aggression than males from pairs with delayed pregnancies. The same reproductive classification did not produce an equivalent difference in females. Dopamine release in the male accumbens shell also varied with the pair’s reproductive condition.

For males, greater shell dopamine release accompanied greater attack frequency. These relationships connect established reproductive investment with defensive behavior and a candidate physiological mechanism. The female results retain a different organization: bonding-related dopamine changes occurred without the same dependence on pregnancy timing.''')
add('KOR activation feeds back onto dopamine release','interact','interact_feedback','7(a–j)','KOR agonist effects on evoked shell dopamine.', '''The interaction between dopamine and opioid signaling was tested directly in brain slices. The investigators applied the KOR agonist BRL 5237 while measuring electrically evoked dopamine release in the nucleus accumbens shell with fast-scan cyclic voltammetry.

KOR activation reduced dopamine release in nonpaired animals. After bonding, this inhibitory modulation became stronger in males, while females did not show the same change. Concentration-response measurements therefore distinguished receptor sensitivity from the amount of receptor binding measured in tissue sections.

A reduction in male KOR binding can coexist with stronger functional inhibition of dopamine release. Binding and physiological suppression therefore describe different properties of the receptor system. This feedback supplies an additional route by which the dopamine–dynorphin system adjusts transmitter availability within the shell after bonding.''')
add('KOR stimulation restores attacks during D1 blockade','interact','interact_male','9(b,d,e)','Male injection sites, attacks and attack latency.', '''The investigators combined receptor manipulations in males already bonded for two weeks. A D1-like antagonist within the accumbens shell reduced attack frequency and increased the delay before attacking an unfamiliar intruder, reproducing the maintenance-associated role of D1 signaling.

When a KOR agonist was administered together with the D1-like antagonist, attack frequency and latency returned toward the control pattern. Activating KORs could therefore restore aggression even while the upstream dopamine receptor manipulation suppressed D1-like signaling.

This pharmacological rescue supports the authors’ hypothesis that D1-dependent social defense recruits downstream dynorphin/KOR signaling. A rescue experiment tests pathway organization by restoring a candidate downstream function during upstream blockade. The reciprocal manipulation left aggression suppressed when KORs were blocked, even with concurrent D1-like activation.''')
add('D1 stimulation cannot bypass blocked KOR signaling','interact','interact_female','9(c,f,g)','Female injection sites and combined receptor manipulations.', '''The reciprocal combination tested whether D1-like activation could restore aggression when KORs were blocked. Resendez and colleagues infused a D1-like agonist together with a KOR antagonist into the accumbens shell of bonded animals before the intruder encounter.

That combination left attack frequency reduced and attack latency increased relative to paired controls. The overall rescue pattern was shared by males and females: KOR activation bypassed D1 blockade, whereas D1 activation did not bypass KOR blockade. Affiliation and locomotor behavior remained comparable across the manipulation groups.

The direction of rescue places KOR signaling downstream in the proposed functional pathway. Dopamine and dynorphin therefore contribute through an organized interaction rather than two interchangeable signals. Shared pathway organization can support selective aggression in both sexes despite their different receptor-binding and release adaptations.''')
add('Stranger encounters recruit hypothalamic vasopressin','vasopressin','vaso_binding','2(A–D)','V1a and oxytocin receptor binding in original brain sections.', '''**Arginine vasopressin**, or AVP, is a neuropeptide that modulates social responses through membrane receptors. Gobrogge and colleagues examined the **anterior hypothalamus**, a forebrain region implicated in aggression, in males that had lived with a female partner for two weeks.

During a resident-intruder encounter, bonded males were aggressive toward an unfamiliar female but affiliative toward their partner. Microdialysis sampled extracellular fluid from the anterior hypothalamus, and an immunological assay measured vasopressin in those samples.

The first ten minutes of stranger interaction were accompanied by greater vasopressin release than partner interaction. Across the hour-long encounter, vasopressin concentrations increased with aggression and decreased with affiliation. The local peptide signal therefore tracked the identity-dependent social response expressed by the resident.''')
add('Local vasopressin stimulation promotes aggression','vasopressin','vaso_release','1(A–H)','Microdialysis results and local receptor interventions.', '''Gobrogge and colleagues tested vasopressin’s action by infusing it directly into the anterior hypothalamus of sexually naive males. Each side received a 200 nL injection, while vehicle-treated animals provided a control for the procedure and fluid delivery.

A dose of 500 ng per side induced aggression toward a novel female, whereas 5 ng per side did not produce that increase. Coadministration of a V1a receptor antagonist blocked the peptide-induced aggression. Misplaced injections supplied an anatomical comparison and were ineffective.

**V1a receptors** are a vasopressin-sensitive receptor subtype. The paired agonist and antagonist experiments connect the local peptide effect to this receptor rather than to injection alone. Artificially recruiting the pathway can generate an aggressive response in males without the preceding two-week bonding experience.''')
add('V1a blockade shifts bonded males toward affiliation','vasopressin','vaso_release','1(G,H)','Aggression and affiliation during V1a receptor blockade.', '''To test the pathway during an established bond, the investigators infused a V1a antagonist into the anterior hypothalamus of males paired for two weeks. The males then encountered an unfamiliar female during a ten-minute resident-intruder test.

The 5 μg-per-side antagonist treatment reduced aggression and increased affiliative contact compared with vehicle controls. Incorrectly located infusions lacked the same behavioral effect. Both the drug and its anatomical delivery site were therefore consequential for the observed response.

Blocking vasopressin signaling changed the resident’s choice of social action toward the stranger. This complements the sufficiency experiment in naive males: the peptide can recruit aggression, and its receptor activation contributes to aggression in bonded residents. The familiar partner remains the reference for the normal selective affiliative response.''')
add('Bonding reorganizes hypothalamic V1a receptor binding','vasopressin','vaso_binding','2(A–D)','Region- and receptor-specific changes after pairing.', '''The bonding-associated increase in receptor binding was measured using radiolabeled ligands on brain sections. Gobrogge and colleagues compared sexually naive males with males paired for two weeks, quantifying several regions within the same receptor-mapping preparation.

Bonded males had greater V1a receptor binding in the anterior hypothalamus and medial preoptic area. The lateral septum, bed nucleus of the stria terminalis and amygdala lacked corresponding V1a increases. Oxytocin receptor binding in the anterior hypothalamus also remained similar between groups.

The reorganization is thus specific to both receptor type and anatomical territory. It supplies more V1a binding sites in a region where local signaling regulates aggression. Social experience can adjust the capacity of a neuropeptide pathway alongside the encounter-dependent release of its ligand.''')
add('Increasing hypothalamic V1a expression raises aggression','vasopressin','vaso_gene','3(A–E)','Viral receptor expression, receptor maps and aggression.', '''Gobrogge and colleagues used an **adeno-associated viral vector**, a gene-delivery vehicle, to increase V1a receptor expression in the anterior hypothalamus of sexually naive males. A vector carrying the control gene lacZ separated the effect of receptor expression from the delivery procedure.

Three weeks later, males receiving the V1a construct displayed greater aggression toward an unfamiliar female. Autoradiography confirmed increased receptor binding in the anterior hypothalamus, while the lateral septum lacked the same expression increase. The manipulation connected a localized molecular change with an altered social response.

Receptor upregulation can therefore contribute functionally to the aggression associated with bonding. The accumbens dopamine–opioid findings and the hypothalamic vasopressin findings identify different local components of stranger rejection; these experiments did not map a direct synaptic connection between the two sites.''')
add('Social experience changes oxytocin’s synaptic action','oxytocin','oxy_spontaneous','1(A–G)','Whole-cell recordings in virgin and paired female voles.', '''Borie and colleagues recorded **medium spiny neurons**, the principal projection neurons of the nucleus accumbens, in brain slices from female prairie voles. Ovariectomized females lived with a female littermate or with a male for 24 hours, and recordings were made 48 hours later.

The oxytocin receptor agonist **TGOT** was applied at 100 nM for ten minutes. It reduced the amplitude of spontaneous excitatory postsynaptic currents in virgin females but not in paired females. Electrically evoked excitatory currents instead became more strongly potentiated after pairing.

An **excitatory postsynaptic current** is ionic current generated when excitatory input activates receptors on the receiving cell. The same receptor agonist had different effects depending on social experience and the input being measured. Pairing changed neuromodulatory action rather than simply raising baseline neuronal excitability.''')
add('Synaptic potentiation varies with partner preference','oxytocin','oxy_preference','2(A–G)','Social preference and glutamatergic field responses.', '''Borie and colleagues measured females’ proximity to two males enclosed under cups, restricting direct contact. Females tested before and after cohabitation developed a preference for the cohabiting male, connecting the slice experiments with a measured selective social response.

**Field recordings** measure electrical responses from a local neuronal population. The excitatory response was blocked by DNQX, an antagonist of AMPA/kainate glutamate receptors. These receptors support excitatory ion flow when activated by glutamate, identifying the recorded response as glutamatergic transmission.

TGOT increased evoked field-response amplitude in paired females. Among paired females preferring their partner, stronger preference accompanied greater potentiation. Social experience and selective affiliation were therefore associated with the physiological effect of activating oxytocin receptors in the accumbens core.''')
add('Paired-pulse responses implicate transmitter release','oxytocin','oxy_genome','3(A–I)','Paired-pulse physiology and local receptor knockdown.', '''Borie and colleagues delivered pairs of electrical stimuli while measuring excitatory responses. The **paired-pulse ratio** compares the second response with the first and provides information about the probability of transmitter release from the presynaptic terminal.

In paired females, stronger TGOT-induced potentiation accompanied a smaller paired-pulse ratio. The pattern is consistent with increased glutamate release on the first pulse. Virgin females lacked the same systematic relationship, matching their different response to oxytocin receptor activation.

The investigators also used CRISPR-Cas9-mediated receptor knockdown in accumbens cells. **Knockdown** reduces expression of a selected molecular target. Lower local oxytocin receptor binding was accompanied by reduced TGOT potentiation, connecting receptors on accumbens cells with an effect expressed through presynaptic release dynamics.''')
add('Oxytocin potentiation requires cannabinoid signaling','oxytocin','oxy_cb1','4(A–G)','CB1 antagonism and agonism during field recordings.', '''**Endocannabinoids** are locally produced lipid signals that can carry information from a postsynaptic cell back toward presynaptic terminals. Borie and colleagues tested whether cannabinoid receptor signaling participates in the pairing-dependent effect of oxytocin receptor activation.

The CB1 receptor antagonist AM4113, applied at 1 μM, prevented TGOT-induced potentiation in slices from paired females. It also removed the relationship between potentiation and the paired-pulse change. Separate slices from the same animals supplied physiological comparison conditions.

The oxytocin receptor can signal through Gq and phospholipase C, a pathway capable of promoting endocannabinoid production. The authors’ hypothesis is that this retrograde signaling connects receptors on accumbens cells with presynaptic modulation. The blockade experiment identifies CB1 activation as required for the measured potentiation.''')
add('Pairing couples two available signaling systems','oxytocin','oxy_cb1','4(D–G)','Direct CB1 stimulation and comparison with TGOT.', '''Direct activation of CB1 receptors with the agonist **ACEA** potentiated electrically evoked excitatory responses in virgin females as well as paired females. The cannabinoid-dependent physiological effect was therefore available before the pairing-dependent oxytocin effect appeared.

In virgin females, ACEA potentiation was accompanied by a paired-pulse change consistent with altered presynaptic release. Its magnitude was comparable to the TGOT-associated potentiation measured in paired females. These interventions distinguished the capacity of the cannabinoid pathway from its coupling to oxytocin receptors.

The social-experience change is consequently interpreted as a new functional linkage between existing systems. Oxytocin receptor activation gains access to cannabinoid-dependent potentiation after pairing. This mechanism explains how the same neuromodulator can produce different synaptic outcomes as the animal’s social history changes.''')
add('CB1 blockade increases defensive rejection of partners','oxytocin','oxy_behavior','5(A–G)','Partner preference and intruder responses after CB1 blockade.', '''Borie and colleagues infused AM4113 into the accumbens core of paired females and measured social responses. A novel male entered the female’s home cage for ten minutes, followed by her partner for another ten minutes. Observers scored affiliation and aggressive or defensive actions blind to treatment.

CB1 blockade approximately doubled the time spent in a defensive upright posture when the partner was present. Stranger-directed rejection remained similar between treatment groups. Overall rearing behavior was comparable, distinguishing the defensive posture from a general increase in standing movements.

Both groups retained proximity-based partner preference. Partner acceptance during direct interaction and partner-directed proximity can therefore change separately. Accumbens cannabinoid signaling contributes to the quality of interaction with the bonded male, complementing the mechanisms that direct aggressive rejection toward unfamiliar animals.''')
add('Dopamine blockade reduces partner-contact preference','dopamine','dopamine_preference','1(A–H)','Systemic antagonism during established partner preferences.', '''Pierce and colleagues examined dopamine’s contribution after prairie voles had already formed partner preferences. Systemic antagonists of D1-like or D2-like receptors were given before testing established social contact, extending the analysis beyond initial bond formation.

Both receptor manipulations reduced partner-contact preference under the tested conditions. Their effects on movement differed: D1-like blockade increased locomotion, whereas D2-like blockade reduced velocity and distance traveled. Behavioral interpretation therefore required the social and motor measurements together.

The finding complements the earlier local shell experiments without equating the preparations. A systemic intervention reaches multiple sites and can influence several behavioral processes. Established partner-contact preference involves ongoing dopamine signaling, while local studies identify particular receptor functions within particular accumbens territories.''')
add('Dopamine supports effort to gain social access','dopamine','dopamine_work','2(A–N)','Lever pressing, barrier climbing and receptor blockade.', '''An **operant task** makes a consequence depend on an animal’s action. Pierce and colleagues trained bonded voles to press a lever that opened a door and briefly provided access to their partner or an unfamiliar animal. Lever pressing measured work performed to obtain contact.

A low systemic dose of the D1/D2 antagonist flupenthixol reduced pressing and delayed social access for both stimulus animals. A higher-effort schedule also revealed reduced performance. The measured consequence was reduced willingness to perform the instrumental action, rather than only altered huddling after access.

A barrier-climbing test similarly assessed effort to reach the partner. D1-like blockade reduced climbing attempts, while D2-like blockade did not produce the same effect. Dopamine receptor systems can regulate components of partner seeking differently across the actions required to obtain social contact.''')
add('A fluorescent sensor records dopamine during seeking','dopamine','dopamine_sensor','3(A–K)','GRABDA sensor placement and social operant recording.', '''Pierce and colleagues expressed **GRABDA**, a fluorescent dopamine sensor, in the nucleus accumbens and implanted an optical fiber. Dopamine binding changes the sensor’s fluorescence, allowing transmitter-associated signals to be recorded while the animal performs the social-access task.

Histological sections confirmed sensor expression and optical placement. The task separated lever presentation, lever pressing, door opening and entry into the social chamber. Recording these events individually distinguished anticipatory and action-related signals from signals during the encounter itself.

Across six days of social-access training, lever pressing increased and task performance improved. Dopamine signals around lever presentation and pressing changed with learning. The technique therefore connected real-time accumbens dopamine dynamics with an animal’s acquisition and execution of actions that produce social contact.''')
add('Partner access evokes a larger dopamine response','dopamine','dopamine_partner','4(A–H)','Partner- and novel-directed seeking signals before separation.', '''Proficient voles worked for access to both their established partner and an unfamiliar animal. Pierce and colleagues compared dopamine fluorescence within the same subjects during partner and novel-animal trials, preserving the animal’s individual sensor expression and recording conditions.

Lever pressing and door opening were associated with larger dopamine responses in partner trials. The preference in the transmitter signal emerged even though the voles did not consistently perform more lever presses for the partner. Partner-enhanced signaling therefore contained information beyond the count of completed actions.

The established partner’s identity influenced the dopamine dynamics accompanying social access. This result connects bond selectivity with moment-to-moment neural signaling, complementing the receptor and slice-release changes observed after cohabitation. Neural selectivity and overt instrumental performance are related measurements with distinguishable patterns.''')
add('Prolonged separation erases partner-enhanced dopamine','dopamine','dopamine_social','5(A–M)','Social behavior and dopamine before and after separation.', '''Pierce and colleagues separated bonded pairs for four weeks and then retested their social-access behavior and dopamine responses. This interval was long enough for the previously bonded animals to adapt to partner loss and potentially form another relationship.

After separation, partner and novel-animal trials no longer differed in the dopamine responses that had previously favored the partner. The change reflected diminished partner-associated signals rather than an equivalent increase during novel-animal trials. Animals still performed the learned operant task.

Direct partner contact and huddling had also evoked greater dopamine responses before separation, and those neural distinctions disappeared afterward. Some behavioral familiarity remained. The former partner’s enhanced motivational signal can therefore erode while the animal retains aspects of social recognition and the ability to seek contact.''')
add('Septal activation separates affiliation from preference','septum','septum_design','1(a,b)','Published lateral-septum manipulation and test timeline.', '''The **lateral septum** is a forebrain structure involved in social behavior. Sailer and colleagues expressed the excitatory designer receptor hM3Dq there and activated it using Compound 21, abbreviated C21. The published anatomical design identifies the intended neural territory.

A **DREADD** is a designer receptor activated by a chosen ligand. Receptor-expressing animals receiving saline and sham-operated animals receiving C21 supplied controls for receptor activation and drug exposure. C21 was administered at 3 mg/kg, 30 minutes before behavioral assessments.

Septal activation promoted social approach in sexually naive males but did not alter the subsequently measured partner preference. Increasing contact-oriented behavior and establishing a selective preference are thus separable outcomes. The experiment tested how a localized change in neural activity influences several components of social behavior.''')
add('Septal activation reduces post-bonding aggression','septum','septum_behavior','4(a–f)','Aggressive and affiliative actions before and after bonding.', '''Sailer and colleagues repeated intruder testing after male prairie voles had paired with females. Subjects with activated lateral-septum hM3Dq receptors were compared with receptor-plus-saline and sham-plus-C21 controls, preserving the distinction between neural activation and drug administration.

After bonding, septal activation reduced attacks, chasing and total aggressive behavior. Huddling and other social actions were measured separately, and the intervention promoted prosocial responses during the encounter rather than merely changing the aggregate amount of recorded behavior.

Partner preference remained intact in the study’s separate preference test. A bond’s selective affiliation can therefore persist when an intervention reduces its associated stranger rejection. These findings connect lateral-septum activity with the regulation of social action while retaining preference and aggression as distinct behavioral outputs.''')
add('Accumbens inhibition weakens established partner contact','motherhood','mother_inhibit','1(A–C)','Inhibitory DREADD effects before and after parturition.', '''Forero and colleagues expressed inhibitory hM4Di designer receptors in the accumbens core of female prairie voles. Receptor activation was tested before and after birth, using C21 and saline on counterbalanced test days within the same animals.

C21 activation reduced side-by-side contact with the established male partner both before and after parturition, the birth of offspring. After birth, inhibition also disrupted the usual preference for partner over stranger contact. Contact with the unfamiliar male did not increase correspondingly.

The intervention therefore weakened the affiliative expression of an existing bond through reduced partner engagement. Its stronger consequence after birth connected neural activity with reproductive state. Maintaining partner-directed affiliation depends on accumbens function while the female’s social demands change during the transition to motherhood.''')
add('Changing accumbens activity can disrupt affiliation','motherhood','mother_excite','2(A–C)','Excitatory DREADD effects on established partner contact.', '''Forero and colleagues also expressed the excitatory hM3Dq receptor in female accumbens core neurons. Activating this receptor with C21 supplied a manipulation opposite in direction to inhibitory hM4Di, with saline sessions providing the within-subject comparison.

With accumbens excitation, females lacked a significant partner-over-stranger preference before and after birth. Excitation did not significantly reduce partner-contact duration in either period. In saline sessions, preference was present before birth but absent afterward, when partner contact was reduced.

Inhibition reduced partner contact, whereas excitation changed the detectable preference without a significant reduction in partner-contact time. Contact duration and the partner-versus-stranger comparison describe different behavioral outcomes. Sham-surgery animals given C21 controlled for drug exposure, and the before-birth versus after-birth tests separated reproductive state from receptor manipulation.''')
add('Birth changes affiliation beyond elapsed cohabitation','motherhood','mother_vasectomy','4(A–C)','Partner contact when pregnancy was prevented.', '''To distinguish motherhood from the passage of time, Forero and colleagues paired females with vasectomized males or sham-operated fertile males. Vasectomy prevented pregnancy while preserving the opportunity for social cohabitation and mating-related interaction with the male.

Females paired with vasectomized males retained strong partner-contact preference at both two and four weeks. Females paired with sham-operated males also preferred their partners but reduced partner-contact duration after birth. The comparison distinguished offspring-associated changes from an inevitable decline during longer cohabitation.

The transition to parenthood changes the expression of an established relationship. Reduced partner contact can occur alongside a retained preference rather than replacement of the partner by a stranger. The reproductive manipulation connects changing social allocation with the presence of offspring and the female’s new parental state.''')
add('Bonding changes gene expression by time and sex','transcript','transcript_genes','2(A–F)','Accumbens gene-expression comparisons across bonding stages.', '''A **transcriptome** is the collection of RNA transcripts expressed in sampled tissue. Duclot and colleagues sequenced accumbens RNA from males and females after 24 hours or three weeks of opposite-sex cohabitation, using same-sex littermate housing as a comparison condition.

Early and later cohabitation produced different expression patterns, and males and females retained different sexually biased transcriptomes. The comparison therefore sampled both the development of a preference and the longer-term social state associated with maintenance, rather than one undifferentiated bonding condition.

Functional gene groups involved in neurotransmission, protein turnover and cellular metabolism changed with social experience. The molecular organization of a bonded brain includes multiple interacting processes. Sex and duration of pairing influence those processes, complementing the localized dopamine, opioid and neuropeptide mechanisms measured experimentally.''')
add('Mitochondrial regulation changes with social experience','transcript','transcript_mito','6(A–F)','Mitochondrial regulatory proteins across cohabitation conditions.', '''**Mitochondria** supply cellular energy and undergo fusion and fission, the joining and division of mitochondrial structures. Duclot and colleagues combined accumbens transcriptomic analysis with measurements of proteins associated with mitochondrial dynamics in prairie voles.

Cohabitation altered the molecular balance of mitochondrial regulation differently in males and females. In males, the results included a shift toward fission-related regulation. The study assessed protein markers alongside the broader RNA patterns, retaining molecular measurements distinct from behavioral preference scores.

The authors’ hypothesis is that metabolic and mitochondrial adjustments support experience-dependent neuronal remodeling. Synaptic signaling, protein turnover and structural plasticity require cellular resources. The maintenance-associated transcriptome therefore includes the cell’s capacity to sustain and reorganize neural function as well as receptors directly involved in social behavior.''')
add('Partner preference can persist through long separation','separation','separation_behavior','1(A–E)','Huddling preferences before and after partner separation.', '''Sadino and colleagues first housed males in opposite-sex or same-sex pairs for two weeks. They then compared animals that remained paired with animals separated for two days or four weeks, moving separated partners to another room to eliminate ongoing sensory contact.

During partner preference testing, males continued to favor familiar partners after separation, including the long interval. Huddling duration and contact with the stranger were measured separately. Preference persistence was therefore recorded even while other molecular features of the bonded state changed.

A retained contact preference is one component of the relationship’s history. Familiar-partner recognition and the neural state supporting current selective motivation can have different time courses. After prolonged separation, familiar-partner contact can remain selective even as partner-enhanced dopamine and bonding-associated gene expression decline.''')
add('Long separation erodes the accumbens bonding signature','separation','separation_erosion','3(A–K)','Bond-associated transcription before and after separation.', '''Sadino and colleagues sequenced nucleus accumbens RNA to compare pair-bond-associated expression patterns after short and long separation. Same-sex pairs provided a social-housing comparison, while opposite-sex pairs that remained together identified a persistent bonding-associated pattern.

The accumbens signature remained largely concordant after two days of separation but eroded after four weeks. Genes linked with glial processes, extracellular matrix organization, synapse organization and vesicle docking contributed to the changing signature. These are components of tissue organization and communication among cells.

The authors’ hypothesis is that this molecular reorganization contributes to adaptation after partner loss. Continued cohabitation maintains a stable expression state, whereas extended separation permits a different state to emerge. Behavioral preference can persist over an interval in which parts of the bonding-associated transcriptional pattern are already changing.''')
add('Neuron-specific RNA reveals several responses to loss','separation','separation_neurons','4(A–G)','Neuron-enriched transcripts and separation-related clusters.', '''Sadino and colleagues developed **translating ribosome affinity purification** for prairie voles. Tagged ribosomal proteins were expressed in neurons, and the tagged complexes were isolated to enrich RNA being translated in those cells, separating neuronal expression from prominent glial contributions.

The neuron-enriched results contained distinct temporal patterns. One cluster rose during bonding and short separation, then declined after long separation. Another increased after acute loss and contained genes associated with dopamine and learning. A third increased primarily after prolonged separation and involved cellular metabolism.

Pair-bond maintenance and adaptation to loss therefore involve several coordinated cellular processes with different time courses. Partner-directed behavior, receptor-dependent social defense and cell-specific molecular changes provide complementary biological measurements. Their combination explains how a relationship can remain recognizable while the neural state supporting its current motivational value is reorganized.''')
assert len(slides)==44,len(slides)
for index in [19,20]:
 old=slides[index].pop('figure');slides[index]['layout']='figures-right';slides[index]['primary_figure_height']=2.6
 slides[index]['figures']=[fig('vasopressin','vaso_binding','2(A–D)','Hypothalamic receptor-binding anatomy.'),old]
for index in [36,37]:
 old=slides[index].pop('figure');slides[index]['layout']='figures-right';slides[index]['primary_figure_height']=2.6
 slides[index]['figures']=[old,fig('classic','classic_anatomy_top','2(a,b)','Rostral accumbens core and shell landmarks.')]
 slides[index]['refs'].append(refs['classic']);slides[index]['cite']+='; '+cites['classic']
slides[32]['figure']['caption']=slides[32]['figure']['caption'].replace('4(A–H)','4(A–N)')

for index in [4,5,7,10,14,23,24,26,27,29,30,33,39,40,42,43]:
 if 'figure' in slides[index]:
  old=slides[index].pop('figure');slides[index]['layout']='figures-right';slides[index]['primary_figure_height']=3.0
  slides[index]['figures']=[old,fig('classic','classic_anatomy_top','2(a,b)','Rostral accumbens core and shell landmarks.')]
  if refs['classic'] not in slides[index]['refs']:slides[index]['refs'].append(refs['classic']);slides[index]['cite']+='; '+cites['classic']
for index in [3,4,5,7,13,14,17,21,28,33,38,41]:
 ps=slides[index]['body'];slides[index]['body']=[ps[1],ps[0],ps[2]]
 slides[index]['transcript']=[re.sub(r'\*\*|_', '',p) for p in slides[index]['body']]
items=[('Selectivity has several behavioral components.','Partner-contact preference, effort to gain contact and aggression toward strangers are measured separately and can change independently.'),('Dopamine function changes with bonding.','Accumbens D2-like signaling supports preference formation; later D1-like plasticity and dopamine release contribute to maintenance-associated social responses.'),('Dopamine and opioids interact directionally.','KOR stimulation rescues aggression during D1 blockade, supporting a downstream dynorphin/KOR component of stranger rejection.'),('Hypothalamic vasopressin supports social defense.','Local V1a activation promotes aggression, while antagonism and receptor-expression manipulations link the pathway to bonded males’ stranger rejection.'),('Partner acceptance has a synaptic mechanism.','Pairing couples oxytocin receptor activation to CB1-dependent potentiation; CB1 blockade increases defensive responses toward partners without eliminating proximity preference.'),('Maintenance remains biologically flexible.','Motherhood alters affiliation, and prolonged separation erodes partner-enhanced dopamine and bonding-associated transcription even while aspects of familiar-partner preference persist.')]
spec=dict(lecture=58,theme='storm-chalk',content_slides=44,title_height=3.8,title_image=fig('kappa','title_pair','2(C)','Affiliative contact between prairie voles.'),title_refs=[refs['kappa']],slides=slides,takeaways={'cite':'; '.join(cites[k] for k in ['classic','interact','oxytocin','separation']),'items':[{'lead':a,'text':z} for a,z in items],'refs':[refs[k] for k in ['classic','interact','vasopressin','oxytocin','dopamine','motherhood','separation']]})
(b/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n')
print('44 content slides; words:',min(len(' '.join(s['body']).split()) for s in slides),max(len(' '.join(s['body']).split()) for s in slides))
