from pathlib import Path
import json,re
BASE=Path(__file__).resolve().parent
R={s['id']:s for s in json.loads((BASE/'research.json').read_text())['sources']}
slides=[]
def add(title,key,fig,desc,a,b,c,extra=None):
 s=R[key];body=[a,b,c];refs=[s['reference']];cite=s['authors'][0].split()[0]+(' et al.' if len(s['authors'])>2 else ' & '+s['authors'][1].split()[0] if len(s['authors'])==2 else '')+f" ({s['year']})"
 # Display names preserve compound surnames.
 names={'ear26':'De Vreese et al.','vascular12':'Costidis & Rommel','voice23':'Madsen et al.','cortex23':'Graïc et al.'}
 cite=names.get(key,cite.split(' (')[0])+f" ({s['year']})"
 figure={'path':f'figures/{key}_{fig}.png','caption':cite.replace(' (',' (').replace(')',f'), Fig. {re.match(r"\d+",fig)[0]}'+('('+re.sub(r'^\d+','',fig).replace('_','–')+')' if re.sub(r'^\d+','',fig) else '')+'. '+desc,1),'source_url':'https://doi.org/'+s['doi'],'kind':'article'}
 d={'layout':'figure-right','title':title,'body':body,'cite':cite,'refs':refs,'transcript':[re.sub(r'\*\*|_', '',p) for p in body],'figure':figure}
 if extra:
  k,f=extra;e=R[k];name=names.get(k,e['authors'][0].split()[0]+' et al.');cap=name+f" ({e['year']}), Fig. "+re.match(r'\d+',f)[0]+'. Original anatomy of the structure discussed.'
  d.pop('figure');d['layout']='figures-right';d['figures']=[figure,{'path':f'figures/{k}_{f}.png','caption':cap,'source_url':'https://doi.org/'+e['doi'],'kind':'article'}];d['refs'].append(e['reference']);d['cite']+='; '+name+f" ({e['year']})"
 if key=='buzz14' and fig in ('1A','1B'):
  d['figure']['caption']=cite+', Fig. 1('+('A–C' if fig=='1A' else 'D–F')+'). '+desc
 slides.append(d)
add('Returning echoes guide prey interception','buzz14','1B','Bottlenose dolphin clicks and echoes during fish capture.',
'**Echolocation** is active sensing: an animal emits sound and uses returning echoes to detect objects. **Biosonar** denotes this biological sonar system. Wisniewska and colleagues attached acoustic recording tags to a bottlenose dolphin, _Tursiops truncatus_, and a false killer whale, _Pseudorca crassidens_, while they approached and captured fish.',
'The tags recorded outgoing clicks, prey echoes and body acceleration during the same capture attempts. Video and conspicuous capture-associated movements provided independent timing information. An **echogram** arranges successive echo recordings by emission time and echo delay, preserving the changing acoustic relationship between predator and prey.',
'Just before interception, both animals produced rapid, low-output **buzzes**, or closely spaced click sequences. Rates reached 250–500 clicks per second. These recordings link acoustic sampling to actual prey capture; they do not identify individual neurons that transform echoes into steering commands.')
add('Echo timing changes as a dolphin closes on a target','pursuit19','3','Recorded click timing and estimated target range during approach.',
'**Echo delay** is the interval between an emitted click and its reflected return. **Two-way travel time** is the time sound takes to reach a target and return. Ladegaard and colleagues studied trained bottlenose dolphins swimming toward a submerged target from initial distances as great as 400 m.',
'Animal-borne acoustic tags and a target-mounted recorder measured clicks during free movement. At close range, echoes recorded by the tag provided an independent estimate of target distance. Synchronizing the two recorders allowed emitted clicks and target recordings to be assigned to the same approach.',
'Click timing changed with distance, but the animals did not use one universal timing rule. One dolphin retained intervals longer than target echo delay below roughly 100 m; the other frequently clicked before the preceding echo returned. Successful tracking therefore cannot require waiting for every echo before every new click.')
add('The nasal complex contains paired sound sources','voice23','1AB','Published anatomy and instruments for nasal sound production.',
'Dolphin clicks originate in the nasal complex above the skull rather than in the larynx. **Phonic lips** are paired soft-tissue structures within the nasal passages that generate sound when pressurized air drives their motion. Air spaces and specialized fatty tissues surround these sources and influence sound transmission through the head.',
'Madsen and colleagues combined endoscopy, pressure measurements and sound recordings in trained dolphins and porpoises. **Endoscopy** uses a small camera to examine an internal cavity. Catheters measured nasal pressure while hydrophones recorded sound, linking anatomical position to pressure changes and acoustic output.',
'The experiments located echolocation sound generation near the phonic lips and associated it with their rapid motion. Anatomy alone would only identify candidate sources. Simultaneously recorded tissue motion, pressure and sound provide stronger evidence about which structures operate during an emitted click.')
add('Pressurized air drives phonic-lip motion','voice23','1C_I','Nasal pressure, endoscopy and motion aligned with emitted clicks.',
'**Pneumatic sound production** means that airflow and pressure supply the energy that moves sound-producing tissue. In the live-animal experiments of Madsen and colleagues, pressure beneath the phonic lips increased during clicking. Mean operating pressures were approximately 5.70 kPa in the measured dolphins and 3.91 kPa in the porpoises.',
'High-speed endoscopy sampled tissue motion while hydrophones recorded click onset. In dolphins, nasal-plug motion could precede the acoustic transient; the published recordings compare timing across anatomical landmarks and species. The pressure measurements distinguish a powered nasal source from sound created merely by passive movement of water around the head.',
'The combined data support airflow-driven vibration of the phonic-lip apparatus. They do not imply that one recorded pressure value determines every click frequency or amplitude. Tissue tension, source geometry and surrounding structures can also affect output, and their independent contributions require separate experimental tests.')
add('A single right-side source produces dynamic clicks','madsen13','2AB','On-animal and far-field recordings localize bottlenose dolphin clicks.',
'Madsen and colleagues tested whether dolphins require simultaneous activation of two phonic-lip pairs to produce a complex click. Suction-cup hydrophones were placed on either side of the blowhole while additional hydrophones recorded sound ahead of and beside the animal. Comparing arrival times localized the active source.',
'The studied bottlenose dolphins clicked with the right phonic-lip pair and whistled with the left. Source energy could change over five orders of magnitude, and click centroid frequency varied over more than two octaves. **Centroid frequency** is the energy-weighted center of a sound spectrum; an **octave** is a doubling of frequency.',
'Large acoustic changes therefore occurred without evidence for coordinated bilateral click generation. Waveform differences between viewing angles could arise from sound propagation through the head. The observations reject a requirement for two simultaneous click sources in these animals, while leaving detailed control of pressure and tissue tension unresolved.')
add('Phonic-lip vibration has distinct operating regimes','voice23','3B_C','Original anatomy and dolphin click, burst-pulse and whistle recordings.',
'A **vocal register** is a regime of sound-producing tissue vibration with characteristic timing and waveform. Madsen and colleagues compared odontocete sounds with mammalian register patterns. Dolphin recordings included isolated echolocation clicks, burst-pulse sounds and tonal whistles, each with a different combination of repetition rate and acoustic structure.',
'High-speed experiments on excised porpoise nasal tissue established that pneumatic excitation can generate clicks without an intact nervous system. The authors interpreted click production as a vocal-fry-like regime involving rapid tissue closure. This excised preparation was porpoise tissue; it was not a direct physiological manipulation of a living dolphin.',
'The proposed register interpretation connects tissue mechanics to acoustic diversity. It does not equate dolphin communication with human speech or establish identical neural control. Live-animal recordings document sound types, whereas isolated-tissue experiments test physical source operation under controlled airflow and pressure.')
add('The melon and air spaces shape sound transmission','cranial04','2','CT reconstruction relates the melon to cranial air spaces.',
'The **melon** is the specialized fatty organ in the forehead through which outgoing echolocation sound propagates. Houser and colleagues used computed tomography, or **CT**, to distinguish skull, fatty tissues and air spaces in living bottlenose dolphins. CT reconstructs internal structure from differences in X-ray attenuation.',
'The reconstructions positioned the melon in relation to the nasal sound-production apparatus and identified asymmetric, connected air spaces. Measured cranial air-space volumes ranged from approximately 267 to 381 mL. Air adjacent to solid and fluid-filled structures provides a strong acoustic boundary because these materials transmit sound differently.',
'The anatomy supports a role for the melon and surrounding boundaries in directing outgoing sound. The scans did not measure the emitted beam while experimentally changing individual tissue properties. Claims about acoustic focusing therefore combine established tissue geometry with a physical interpretation that requires functional measurements.')
add('Tracer uptake is not an echolocation activity map','cranial04','6','Published SPECT distribution of tracer uptake in the melon.',
'Houser and colleagues combined CT with **SPECT**, single-photon emission computed tomography, and **PET**, positron emission tomography. SPECT measured uptake of a technetium-labeled tracer; PET measured uptake of a glucose-related tracer. The animals were examined under quiet conditions, rather than during a controlled active echolocation task.',
'The SPECT tracer accumulated strongly in the melon and posterior mandibular fat. Uptake in the melon exceeded that in neighboring blubber by more than fourfold. The PET examination instead recorded strong brain uptake and comparatively little melon uptake, separating the two tracer distributions.',
'Tracer chemistry matters: a lipid-soluble compound can accumulate in fat without providing a simple quantitative measure of blood flow. These results establish anatomical differences in tracer uptake. Thermoregulation of acoustic fats was proposed, but the study did not directly measure a blood-flow-induced change in the outgoing sonar beam.')
add('Mandibular fats connect sound reception to the ear','cranford10','2','Ventral anatomy of the bottlenose dolphin sound-reception pathway.',
'**Mandibular acoustic fats** are specialized fatty tissues associated with the lower jaw and ear region. Cranford and colleagues combined CT reconstructions with anatomical dissection to examine how these fats contact the **tympanoperiotic complex**, the connected middle-ear and inner-ear bones of toothed whales.',
'The bottlenose dolphin reconstructions distinguish the jaw bones from extensive fat bodies along the posterior mandible. Their organization differs from the external-ear pathway typical of terrestrial mammals. Sound can propagate through tissues surrounding the jaw toward the ear apparatus rather than depending on a large open external ear canal.',
'The anatomical continuity provides a physical route for incoming sound but does not establish that every part of the fat contributes equally at every frequency. The study examined structure and included computational mechanics. It did not selectively block each fat branch while measuring a living dolphin’s detection of prey echoes.')
add('Reception fats contact more than one ear surface','cranford10','6','Labeled bottlenose dolphin tympanoperiotic complex and landmarks.',
'Cranford and colleagues found that the mandibular fat body divides near the ear apparatus, with distinct contacts on the tympanoperiotic complex. The **tympanic bone** surrounds the middle-ear cavity, whereas the **periotic bone** houses the inner ear. The arrangement provides more than a single attachment point for transmitted acoustic energy.',
'CT distinguished these contacts and neighboring bony landmarks; dissections checked the spatial relationships in actual tissue. Comparative specimens allowed the authors to evaluate whether the bifurcated arrangement occurred across different toothed-whale lineages rather than representing an isolated bottlenose-dolphin feature.',
'The observations constrain proposed reception mechanisms because a model must respect the separate tissue contacts. They do not determine the contribution of each route to directional hearing in vivo. The authors’ mechanical interpretations concern how incoming energy could excite the ear; anatomical contact itself is not a recording of neural activation.')
add('Middle-ear geometry constrains vibration pathways','cranford10','8','Tympanic bone and ossicles reconstructed from dolphin CT.',
'The **ossicles** are the small middle-ear bones that couple mechanical vibration to the inner ear. Cranford and colleagues reconstructed the bottlenose dolphin tympanic bone and associated ossicles from high-resolution scans. Their relationship to the surrounding bone differs substantially from the familiar external-eardrum arrangement of terrestrial mammals.',
'The same investigation used finite-element analysis, a numerical method that estimates mechanical behavior from geometry and material properties. Published simulations predicted multiple modes of ear-bone vibration. These are results of the authors’ model, not direct measurements of the vibration experienced by a freely hunting dolphin.',
'The original CT anatomy establishes where the bones contact one another and where mechanical energy might enter. Model behavior depends on assumed tissue properties and boundary conditions. Neither the reconstruction nor the simulation identifies the frequency tuning of an individual auditory neuron or proves the behaviorally dominant sound-entry route.')
add('Venous plexuses surround acoustic tissues','vascular12','11','Cross-sections of bottlenose dolphin intramandibular fat vasculature.',
'A **venous plexus** is an interconnected network of veins. Costidis and Rommel examined bottlenose dolphin head tissues using vascular injection, dissection and imaging. Injected material made the vessels visible within and around mandibular acoustic fat bodies, allowing their distribution to be compared with the ear-adjacent air-sinus system.',
'The intramandibular fat contained extensive branching vessels rather than being uniformly poorly vascularized. Cross-sections revealed vascular networks throughout much of the fat, with locally different vessel densities. Dissection and imaging provided complementary evidence that the vessels belonged to an organized anatomical network.',
'The results make the acoustic apparatus relevant to diving physiology as well as hearing. Proposed roles included responses to changing pressure and possible pathways for gas exchange. The study did not measure dynamic perfusion during a dive or experimentally establish that these veins regulate echo sensitivity or sonar beam shape.')
add('The external ear contains a sensory nerve network','ear26','8A_F','Original confocal sections through a lamellar corpuscle.',
'De Vreese and colleagues examined the peripheral ear using dissection, iodine-enhanced micro-CT, histology and confocal microscopy. **Histology** examines thin tissue sections; **confocal microscopy** separates optical sections of fluorescently labeled material. Their observations included the external ear canal of striped dolphins, not just the inner-ear auditory apparatus.',
'The canal contained **lamellar corpuscles**, sensory structures in which layers of supporting tissue surround nerve fibers. Consecutive 5 µm sections revealed axons and shared surrounding sheaths, called **perineuria**. Corpuscles and nerve bundles formed a continuous network associated with blood vessels rather than a set of completely isolated endings.',
'This anatomy suggests mechanosensory or pressure-related functions, but the study did not record the corpuscles’ responses. These peripheral sensory fibers must not be identified as the cochlear auditory nerve. Their presence beside acoustic tissues does not establish that they encode echolocation echoes or directly relay them to auditory cortex.')
add('Cochlear hair cells and nerve fibers are distinguishable','prestin20','6e','Bottlenose dolphin organ of Corti with labeled hair cells and neurites.',
'The **cochlea** is the spiral inner-ear organ that converts mechanical vibration into electrical signals. The **organ of Corti** contains sensory hair cells and supporting tissues. Morell and colleagues examined whole-mount cochlear preparations from echolocating mammals, including a bottlenose dolphin, using antibodies that label particular cellular proteins.',
'The dolphin preparation combined staining for **prestin**, a membrane motor protein, **myosin VI**, a hair-cell marker, and **neurofilament H**, a neuronal structural protein. The published fluorescence separates outer hair cells from associated nerve processes. This establishes the position of identified cells and fibers within the sensory epithelium.',
'Hair-cell activation precedes signaling in auditory nerve fibers, but this fixed-tissue experiment did not measure synaptic currents or action potentials. Molecular localization supplies anatomical evidence for the reception apparatus. It does not by itself identify every dolphin mechanotransduction channel, synaptic receptor or transmitter responsible for ultrasonic hearing.',extra=('cranford10','12'))
add('Prestin localizes to dolphin outer hair cells','prestin20','4a','Prestin labeling in the bottlenose dolphin middle cochlear turn.',
'**Outer hair cells** are cochlear sensory cells whose voltage-dependent changes in length contribute to mammalian cochlear amplification. Prestin is the membrane motor associated with this **electromotility**. Morell and colleagues used immunofluorescence to determine whether echolocating mammals express prestin in the same cellular compartment.',
'The bottlenose dolphin middle cochlear turn contained prestin labeling around outer hair-cell membranes. A separate hair-cell marker identified the cellular rows, and a nuclear stain helped distinguish cells from surrounding tissue. Across the examined echolocating species, prestin labeling extended along the cochlear spiral.',
'The result establishes protein expression and location rather than a direct measurement of amplification during a click echo. Mammalian prestin function motivates the interpretation, but whether the protein operates cycle by cycle at the highest cetacean hearing frequencies remained unresolved. Expression alone cannot prove a complete mechanism for ultrasonic sensitivity.')
add('Staining controls separate protein from background','prestin20','4b','Specificity, secondary-antibody and autofluorescence controls.',
'**Immunofluorescence** uses antibodies linked directly or indirectly to fluorescent labels to locate proteins. A bright signal is informative only if it reflects binding to the intended target. Morell and colleagues compared prestin labeling with antibody controls and examined the tissue’s own fluorescence, called **autofluorescence**.',
'The dolphin controls included a specificity condition, a secondary-antibody condition and an autofluorescence condition. The broader study also compared three antibodies directed against prestin. These comparisons reduce the likelihood that the membrane-associated signal arose solely from background tissue fluorescence or nonspecific secondary-antibody binding.',
'The controls strengthen the inference that outer hair cells contain prestin. They do not convert protein staining into a functional test of electromotility. A mechanistic claim about hearing loss or ultrasonic amplification would require physiological or pathological evidence in addition to localization, especially when extrapolating from one mammalian group to another.',extra=('prestin20','4a'))
add('Diffusion imaging reconstructs candidate pathways','berns15','1','Original inferior-colliculus tractography and anatomical landmarks.',
'**Diffusion MRI** measures the directional movement of water in tissue. **Tractography** uses those measurements to estimate paths through white matter, the tissue containing many long neuronal axons. Berns and colleagues applied this method to preserved brains of a common dolphin and a pantropical spotted dolphin.',
'The researchers selected the **inferior colliculus**, a midbrain auditory structure, as a starting region and estimated connected paths. Structural scans supplied anatomical landmarks, including the thalamus and temporal lobe. Probabilistic tracking expresses uncertainty in possible paths rather than treating every voxel as one perfectly resolved fiber bundle.',
'The reconstructed paths support a connection between the midbrain auditory apparatus and temporal cortex. A tractography streamline is not an individual traced axon. Preserved-tissue MRI cannot determine the direction of neural transmission, count synapses or measure activity during echo discrimination, so the result is anatomical rather than functional.')
add('Auditory paths traverse the ventral thalamus','berns15','2','Thalamic parcellation relative to temporal and suprasylvian targets.',
'The **thalamus** is a forebrain structure containing nuclei that relay and integrate sensory signals. The **medial geniculate nucleus** is the thalamic auditory relay identified in other mammals. Berns and colleagues evaluated whether paths from dolphin inferior colliculus passed through a corresponding thalamic region before reaching cortex.',
'Tractography seeded in the inferior colliculus reached the ventral thalamus and a temporal cortical region near the sylvian fissure. Separate cortical target regions were used to partition estimated thalamic connections. Temporal-region paths preferentially related to a ventrocaudal thalamic location near the putative medial geniculate nucleus.',
'The pattern supports a midbrain–thalamus–temporal route rather than requiring all auditory input to terminate only in a dorsal cortical area. Anatomical position supports identification of a candidate nucleus; diffusion data alone do not establish its cellular boundaries, transmitter identities or echo-specific response properties.')
add('Temporal and suprasylvian regions are connected','berns15','3','Estimated paths from temporal targets toward suprasylvian cortex.',
'The **sylvian fissure** and **suprasylvian sulcus** are grooves used to locate cortical regions. Earlier physiological work placed dolphin auditory responses in dorsal suprasylvian cortex. Berns and colleagues examined whether a temporal region identified by inferior-colliculus tracking also had estimated connections with that dorsal area.',
'Temporal regions were selected from the auditory-path analysis, and probabilistic tracking was then directed toward suprasylvian cortex. A spatial constraint limited the search to paths reaching the specified cortical territory. Estimated streamlines linked the temporal target and the previously implicated dorsal auditory region.',
'The findings support an auditory system involving more than one cortical territory. They cannot decide which region first receives an echo, whether one contains a specialized prey representation or how information flows between them. Such conclusions would require activity measurements or selective manipulations beyond the preserved-brain imaging preparation.')
add('Cross-species scans recover a shared auditory route','flem25','5A_D','Original auditory tract reconstructions across whale species.',
'Flem and colleagues compared preserved brains from common, pantropical spotted and Atlantic white-sided dolphins with a sei whale, a baleen whale that does not use odontocete-style echolocation. A specialized diffusion sequence was used to improve imaging of fixed tissue, enabling the same general tracking framework across these species.',
'Paths seeded in the inferior colliculi reached temporal-lobe targets in all examined brains. The shared route replicates the earlier dolphin finding and places it within a broader cetacean comparison. The authors also checked different tracking conditions rather than relying on only one arbitrary display threshold.',
'A common anatomical route is consistent with an auditory pathway inherited across cetaceans. It is not unique proof of an echolocation specialization, because the non-echolocating sei whale also possessed it. Species differences in preservation, brain geometry and tracking sensitivity limit direct interpretation of numerical streamline measures as biological connection counts.')
add('Odontocete auditory tracts show asymmetric organization','flem25','4a_d','Cortical targets and laterality of estimated auditory pathways.',
'**Lateralization** means a difference between the two sides of a nervous system. Flem and colleagues seeded left and right inferior colliculi separately to compare reconstructed auditory paths in odontocete brains. Colored paths in the original publication distinguish the seed side; they do not represent measured excitation or inhibition.',
'The reconstructed pathways reached cortical targets through both direct ascending routes and additional estimated connections. Laterality varied with the selected path and species. Comparing seed sides within each brain helped distinguish an asymmetric organization from a claim based only on the overall size of a brain region.',
'These anatomical differences motivate hypotheses about integrating emitted sounds with returning echoes. They do not demonstrate that one hemisphere exclusively computes echo range or controls every click. The authors’ interpretation relating laterality to right-side phonic-lip production remains a proposed functional relationship, not a direct recording of a lateralized control circuit.')
add('Auditory–cerebellar paths differ across whale groups','flem25','7a_c','Inferior-colliculus to cerebellar pathways in three odontocetes.',
'The **cerebellum** contributes to coordination and sensorimotor integration in mammals. Flem and colleagues estimated connections between inferior colliculus and cerebellum in preserved cetacean brains. **Sensorimotor integration** means combining sensory information with processes that organize movement, a relevant candidate function during echo-guided prey pursuit.',
'In the odontocete brains, left-inferior-colliculus to right-cerebellum paths were approximately two to four times stronger by the study’s tractography measure than the opposite crossed paths. The sei whale had the reverse asymmetry. Tracking also identified differences in the cerebellar territories associated with these connections.',
'The results support an anatomical difference between the examined echolocating and non-echolocating species. “Tract strength” is an imaging-derived measure, not synaptic strength or firing rate. A contribution to rapid echo-guided movement is plausible, but the study did not measure these pathways during hunting or establish their causal necessity.')
add('Dolphin auditory cortex changes across age groups','cortex23','1','Original cortical sections and neuronal morphologies across ages.',
'**Cytoarchitecture** is the organization of cells within a tissue. Graïc and colleagues examined stained auditory-cortex sections from bottlenose dolphins in calf, adult and older age groups. They measured neuronal shape, size and neighborhood density separately within cortical layers rather than assuming that all cells change identically with age.',
'Upper-layer round and ellipsoid cell populations differed across the age groups. Calves had smaller, more closely spaced cells, whereas adult tissues contained more dispersed and varied forms. Layer IV was poorly differentiated compared with the conspicuous granular input layer often described in terrestrial sensory cortex.',
'The observations establish age-associated morphology in the sampled brains. Cell shape alone does not determine transmitter identity, and a cross-sectional comparison does not track the same neuron through life. Proposed changes in auditory connectivity require further evidence; the histology does not directly measure learned hunting skill or echo-processing performance.')
add('Evoked potentials measure synchronized auditory activity','finneran17','1abc','Bottlenose dolphin stationing and physical biosonar target.',
'An **auditory brainstem response**, or **ABR**, is a small, time-locked electrical response recorded from electrodes near the head after sound reaches the ear. Finneran and colleagues measured ABRs while bottlenose dolphins performed a target-discrimination task and while they listened passively to externally presented clicks.',
'Electrodes recorded an **electroencephalogram**, the voltage differences produced by combined electrical activity. Synchronizing and averaging repeated recordings enhanced consistent click-related responses while reducing unrelated background activity. Acoustic measurements established the emitted-click timing, and the analysis accounted for sound-propagation and electronic delays.',
'ABR peaks describe synchronized population activity, not the firing pattern of one identified neuron. The active and passive preparations allow comparison of self-generated and external sounds. Differences between them can reflect stimulus spectrum, level and transmission path as well as changes associated with active echolocation.',extra=('cranford10','12'))
add('Self-heard clicks recruit broad auditory frequencies','finneran17','5ab','Derived-band responses to dolphins’ own emitted clicks.',
'A dolphin hears its own emitted click as well as the returning echo. Finneran and colleagues used **high-pass masking noise**, noise containing frequencies above a selected cutoff, to suppress parts of the click-evoked response. Subtracting responses measured with successive cutoffs estimated activity associated with narrower frequency bands.',
'Derived-band responses covered center frequencies from 14 to 113 kHz during active biosonar. Adding these responses reproduced the major form of the unmasked response, supporting the decomposition into frequency-related contributions. Residual responses under the lowest cutoff indicated incomplete masking rather than complete elimination of auditory activity.',
'The results establish broad-frequency neural recruitment by a self-heard click. They do not indicate that each ABR peak maps to a separate cortical representation. Incomplete masking and the sound spectrum limit interpretation of response amplitudes, so the subtractive method must be evaluated against the passive-listening controls.',extra=('cranford10','12'))
add('Self-click response latency varies little with frequency','finneran17','6','Measured ABR amplitudes and latencies across derived frequency bands.',
'**Latency** is the interval between a defined stimulus event and a response. During active biosonar, Finneran and colleagues measured ABR peak latency relative to the estimated arrival of the self-generated click at the ear. Correcting for acoustic travel time prevents external propagation delay from being mistaken for neural processing time.',
'Across derived frequency bands, the self-click response showed relatively little systematic latency change, particularly for later peaks above 14 kHz. Mean fitted limiting latencies were approximately 1.48 ms for P1, 3.34 ms for P4 and 3.78 ms for N5. These named peaks mark successive features of the averaged response.',
'Passive listening produced stronger frequency-related latency differences under the tested conditions. The contrast is consistent with a different effective excitation pattern for self-heard sound, but it does not isolate a single cause. Stimulus level, spectrum, transmission through tissue and masking limitations all constrain mechanistic interpretation.',extra=('cranford10','12'))
add('Electrical activity can precede sound generation','finneran18','5','Electrode-position dependence of the pre-auditory wave and ABR.',
'Finneran and colleagues identified a **pre-auditory wave**, or **PAW**, in recordings synchronized to dolphin click production. Unlike the ABR, part of this electrical waveform began before the estimated acoustic source event. Contact hydrophones measured click timing, while electrodes were moved across positions near the blowhole.',
'The initial negative deflection began approximately 500 µs before click generation, and the overall waveform lasted about 2 ms. Its amplitude was greatest near the right side of the blowhole and declined with lateral displacement. Hydrophone arrival differences independently implicated the right-side phonic lips as the active click source.',
'A response that begins before the sound exists cannot be an auditory evoked response to that sound. The spatial pattern supports an origin associated with the nasal production apparatus. It does not by itself identify a particular motor neuron, muscle fiber or mechanoreceptor as the source.',extra=('finneran18','9ab'))
add('Masking separates auditory responses from production','finneran18','8','Masking changes the ABR but leaves the pre-auditory wave intact.',
'Acoustic **masking** occurs when one sound reduces the detectability or neural response to another. Finneran and colleagues compared click-synchronized electrical recordings obtained under different high-pass-noise conditions. The auditory response changed as masking restricted cochlear excitation, whereas the earlier PAW remained relatively insensitive to the masking noise.',
'Additional analyses examined individual recording epochs and small-group averages. Consistent timing supported repeated production-related activity rather than an average dominated by a few unusually large events. Changing electrode position strongly affected the PAW, providing spatial evidence complementary to the masking manipulation.',
'The controls argue against an auditory origin for the early waveform. A **myogenic** origin, meaning electrical activity arising from muscle activation, was proposed because nasal muscles participate in sound production. The study did not directly record a single identified muscle, so a precise cellular generator and its contraction mechanics remained unresolved.',extra=('finneran18','9ab'))
add('Echo amplitude depends on range and emitted level','gain14','1','Published apparatus with targets at 2.5, 4 and 7 m.',
'An echo’s amplitude depends both on the target and on the outgoing signal. **Source level** describes emitted sound referenced to a specified distance, conventionally 1 m. Kloepper and colleagues studied a bottlenose dolphin detecting a target at 2.5, 4 or 7 m while measuring clicks with a hydrophone array.',
'An acoustically opaque screen initially prevented target inspection; its removal began the trial. A separate acoustically transparent screen blocked vision of the target. Predictable blocks maintained one distance, whereas randomized trials changed the target distance. Target-present and target-absent conditions tested whether emitted-level changes required a returning target echo.',
'The design separates effects of previous experience from adjustment after new acoustic information arrives. Source-level regulation changes the signal sent into the environment; it is distinct from changing auditory receptor sensitivity. The measurements therefore test transmitter-side control rather than directly measuring a neural gain mechanism in the ear.')
add('Randomized distances delay range-specific adjustment','gain14','3AB','Click source-level sequences for randomized and predictable distances.',
'**Gain control** is regulation of signal strength or sensitivity so that useful information remains available across changing conditions. Kloepper and colleagues measured the source level of successive clicks when target distance was either predictable or randomized. The same dolphin and apparatus allowed the two conditions to be compared directly.',
'When distance changed unpredictably, early clicks did not immediately express the distance-dependent pattern. Range-specific differences emerged only after approximately the seventh click. Under predictable conditions, emitted levels differed according to the expected target distance, including early portions of the click sequence.',
'The delay in randomized trials is consistent with accumulating echo information before adjusting output. It argues against a wholly instantaneous, fixed relation between target distance and the first emitted click. The experiment does not specify how many central neurons or which neural memory mechanism supports the adjustment.')
add('Experience changes the first emitted click','gain14','4','First-click source levels early and late in predictable-distance sessions.',
'Predictable target placement allows previous trials to influence the next trial before any new echo returns. Kloepper and colleagues compared first-click source levels early and late within sessions containing targets at a constant distance. The first click is especially informative because its amplitude cannot depend on its own returning echo.',
'At 2.5 m, first-click source level decreased during the session. The change at 4 m was not comparably established, and the 7 m condition did not follow the close-target reduction. The result therefore concerns a distance-specific effect rather than a universal decline caused only by time spent clicking.',
'The pattern supports control based on recent experience with target range. It does not establish a consciously articulated expectation or identify a memory circuit. Target-absent trials further constrain interpretations because an animal can maintain a source-level pattern even when the expected physical target is missing.')
add('Free-swimming dolphins use different click schedules','pursuit19','1A_F','Interclick intervals plotted against target range for two dolphins.',
'An **interclick interval**, or **ICI**, is the time between consecutive emitted clicks. Ladegaard and colleagues measured this interval while bottlenose dolphins swam toward a target. Unlike a stationary target-detection preparation, the approach continuously changed the separation between the animal and the reflecting object.',
'At intermediate ranges of roughly 25–100 m, one dolphin commonly retained intervals longer than the target’s two-way travel time. The other emitted clicks at intervals shorter than that travel time, often about half of it. Both animals continued approaching the target successfully under these different schedules.',
'The comparison establishes behavioral flexibility within the same general task. An echo can return after a later click has already been emitted, so temporal overlap does not necessarily prevent target tracking. The acoustic recordings do not reveal the central computation that assigns each returning echo to its corresponding emission.')
add('Long-range tracking includes packets of clicks','pursuit19','2A_F','Within-packet timing and packet prevalence across target distances.',
'A **click packet** is a short group of clicks emitted with brief internal intervals and separated from other groups by a longer pause. During long-range target approaches, Ladegaard and colleagues found frequent packets beyond approximately 100 m. Manually identified packets contained between two and nine emitted clicks.',
'Within a packet, clicks occurred before the echo of an earlier packet click could return. The intervals between packets generally exceeded the target’s two-way travel time. This arrangement produces groups of returning echoes rather than a strictly alternating sequence containing one emission followed by one echo.',
'Packet use changed with target distance and differed between animals. The measurements support packets as a natural option during free-swimming target tracking, not merely an artifact of being held at a station. They leave unresolved how dolphins integrate the multiple echoes or resolve the identity of overlapping returns.')
add('Click level also changes during an approach','pursuit19','4AB','Measured on-axis source level as a function of target range.',
'Ladegaard and colleagues estimated emitted source levels from clicks received at the target, selecting recordings likely to be close to the beam axis. **On-axis** refers to the direction of strongest sound radiation. This selection matters because turning the head away can reduce received sound without any reduction at the source.',
'Across the approaches, source level changed on average by approximately 17 log10(range) dB, as reported in the paper. At short ranges below 25 m, regulation differed from some stationary-task descriptions. The animals therefore altered both the timing and amplitude of sonar while moving toward the target.',
'The result links acoustic output to changing distance under free-swimming conditions. It does not imply that distance alone sets every click level. Orientation, target characteristics and task demands can also matter, and the on-axis classification reduces rather than completely eliminates uncertainty about the emitted beam.')
add('Blindfolded dolphins discriminate objects by echoes','harley22','1','Original three-alternative echolocation matching preparation.',
'**Matching to sample** is a task in which an animal investigates a sample and selects the matching object from alternatives. Harley and colleagues tested the blindfolded bottlenose dolphin Calvin with object sets that differed in acoustic discriminability. Blocking vision required the animal to obtain identifying information through echolocation.',
'Three alternatives were suspended about 1.2 m apart, and their positions varied across trials. A hydrophone behind the sample measured investigation clicks, while video established when the dolphin approached, turned away and selected an alternative. Equal use of alternative positions reduced the usefulness of a fixed spatial-choice rule.',
'Performance ranged from near chance, approximately 33% for three choices, to high accuracy across different sets. The task measures the ability to distinguish reflected signals in a controlled scene. It does not by itself establish the particular echo feature used, such as material, shape or orientation.')
add('Sampling effort falls when objects remain confusable','harley22','6','Accuracy and investigation-click counts across repeated sessions.',
'**Discriminability** is the ease with which stimuli can be distinguished. Harley and colleagues used matching accuracy to characterize easy and difficult object sets, then compared investigation-click counts across repeated sessions. Clicks directed away from the sample were excluded from the main effort measure using synchronized acoustic and video information.',
'For easy sets, mean investigation counts declined from roughly 452 to 375 clicks per trial between the first and fifth sessions. For difficult sets they declined from roughly 363 to 238. Difficult-set accuracy remained much lower, while challenging but solvable sets improved from about 47% to 68% correct.',
'Repeated exposure therefore did not produce one uniform sampling pattern. The results are consistent with effort being adjusted to expected information value rather than only object unfamiliarity. Click count is an operational measure of acoustic investigation, not a direct measure of subjective certainty, attention neurons or conscious awareness.')
add('Interleaving controls for general changes in motivation','harley22','7ab','Published accuracy and click-count comparisons across trials.',
'A decline in investigation could reflect tiredness or reduced motivation rather than information about a particular object set. Harley and colleagues addressed this alternative by interleaving trials from easy and difficult sets within the same sessions. Shared session conditions made a purely session-wide explanation less sufficient.',
'Easy-set performance remained high, about 94% correct, while difficult-set performance was about 43% correct in the interleaved comparison. The corresponding original comparisons were about 90% and 40%. Sampling behavior continued to differ with the acoustic scene even when its trial order was mixed with another scene.',
'The control supports a relation between scene discriminability and investigation effort. It does not eliminate every motivational contribution, since task difficulty can itself affect reward expectation. The inference is about flexible sampling behavior in this trained dolphin, rather than a claim that all dolphins use an identical strategy.')
add('The same sample changes meaning in a new scene','harley22','3','Original scene-shift stimuli preserve a sample while changing alternatives.',
'An **auditory scene** includes the collection of objects whose echoes must be distinguished, not only one isolated target. Harley and colleagues moved familiar difficult samples into choice arrays containing easier alternatives. The sample remained the same while the comparison objects changed, separating sample identity from its relation to the scene.',
'Accuracy for a difficult sample in its original difficult scene was approximately 52%; with easier alternatives it rose to approximately 93%. A novel easy scene produced approximately 87% accuracy. The difficult sample therefore was not intrinsically impossible to identify under every arrangement of alternatives.',
'The scene manipulation supports comparative processing of echo information. It does not require assuming that the animal reconstructs a human-like visual image from sound. The behavioral result establishes context-dependent discrimination, while the neural representation of sample features and alternatives remains unmeasured in this experiment.')
add('Shallow rivers impose a different acoustic environment','river13','1ABC','Original field locations and study animals in the Sundarbans.',
'**Reverberation** is the persistence of sound through multiple reflections; **acoustic clutter** consists of returns from objects other than the target. Jensen and colleagues recorded Irrawaddy dolphins and Ganges river dolphins in the shallow waterways of the Sundarbans, where banks, surface and bottom can produce competing returns.',
'A calibrated hydrophone array measured click arrival differences and allowed source location and range to be estimated. The analysis selected clicks likely to be directed toward the array, reducing effects of recording far outside the sonar beam. These field observations sampled animals in their own riverine environment.',
'The study found rapid repetition and relatively low source levels compared with many marine delphinids. The pattern is consistent with shorter-range sensing in a reflective habitat. Because species and habitat were not independently manipulated, the observations do not isolate habitat alone as the cause of the acoustic differences.')
add('River-dolphin clicks differ in spectrum and level','river13','3ABCD','Recorded Ganges and Irrawaddy dolphin waveforms and spectra.',
'Jensen and colleagues compared the recorded click waveforms and spectra of Ganges river dolphins, _Platanista gangetica_, and Irrawaddy dolphins, _Orcaella brevirostris_. Calibration and source-range estimates allowed received signals to be related to emitted sound rather than comparing uncorrected recordings at arbitrary distances.',
'Mean peak-to-peak source levels were approximately 184 dB for Ganges dolphins and 195 dB for Irrawaddy dolphins, referenced to 1 µPa at 1 m. Median interclick intervals were approximately 27.8 and 30.1 ms respectively. The spectra also differed, with lower characteristic frequencies in the Ganges recordings.',
'These are field-measured properties of the emitted sonar. Proposed explanations include adaptation to shallow-water clutter and anatomical differences affecting directionality. The observations do not directly measure a neural clutter-suppression circuit, and differences among species cannot be assigned to a single receptor or brain region.')
add('Terminal buzzes increase the rate of prey sampling','buzz14','1A','False killer whale echogram and click timing during fish capture.',
'Wisniewska and colleagues aligned acoustic tag recordings with fish interception in a bottlenose dolphin and a false killer whale. During approach, the outgoing click train and returning prey echoes changed together. Close to interception, the animals shifted to a distinct terminal-buzz regime rather than continuing the same long-range sampling pattern.',
'Buzz repetition reached approximately 250–500 Hz, and interclick intervals fell more than tenfold relative to earlier approach clicking. The bottlenose dolphin and false killer whale therefore obtained much more frequent acoustic updates as the remaining distance to prey became small. Capture timing was checked using synchronized behavioral information.',
'The association supports rapid sonar feedback during the final maneuver. It does not prove that every emitted buzz click produces an independently processed motor correction. The tag records acoustic sampling and movement; it does not measure the latency or firing pattern of the central circuits that control interception.')
add('Buzzes combine fast timing with reduced output','buzz14','2ABC','Published click timing, received level and range near interception.',
'Increasing click rate without changing output would also change the energetic and acoustic conditions of close-range sensing. Wisniewska and colleagues found that the terminal buzz combined shorter intervals with substantially reduced emitted output. The transition was therefore an adjustment of both when signals were sent and how strong they were.',
'The measured output reduction exceeded tenfold, accompanying the 250–500 Hz repetition rates. Animal-borne recordings and estimated prey range related this change to the final capture phase. Outgoing level and echo level must be distinguished because a nearby prey item can return a useful echo even when the emitted pulse is weaker.',
'The authors interpreted low-output buzzing as supporting high-rate feedback at close range. Reduced output can restrict the acoustic region sampled, but the study did not experimentally manipulate output independently of repetition rate. Their joint change is measured; the separate causal contribution of each remains to be tested.')
add('Wild dolphins coordinate hunting with fishers','cooperate23','1B','Study location and genuine dolphin–fisher interaction in Laguna.',
'Cantor and colleagues studied bottlenose dolphins and artisanal fishers hunting mullet in Laguna, southern Brazil. **Behavioral synchrony** means that the timing of one participant’s actions matches that of the other. Dolphins approached the bank and provided visible cues, while fishers cast nets in response.',
'The investigators combined shore observations, drone recordings, underwater sonar, acoustic recordings and long-term individual identification. Sonar supplied information about fish availability that could otherwise confound a simple comparison of catches. The analysis also considered fishing effort rather than treating every interaction as equally sampled.',
'Synchronous interactions benefited both partners more than poorly coordinated interactions. The study documents a naturally occurring hunting association, not a laboratory training protocol. Observational controls strengthen the comparison, but they do not establish the dolphins’ subjective intentions or demonstrate a neural mechanism of interspecies cooperation.')
add('Echolocation intensifies after coordinated net casts','cooperate23','3A_C','Drone, underwater sonar and original acoustic capture records.',
'Cantor and colleagues examined the timing of dolphin foraging around fisher net casts using simultaneous measurements above and below water. Drone recordings captured the approach and surface cue, while imaging sonar recorded fish, sinking nets and dolphin movement. Hydrophones supplied a separate measure of echolocation activity.',
'During well-coordinated interactions, dolphins approached the netted region and intensified echolocation after nets entered the water. Terminal buzzes were concentrated in the capture-related interval, connecting an established acoustic prey-interception pattern with a natural cooperative hunting context. Sonar information helped distinguish prey availability from the timing of cooperation.',
'The observations support a benefit from properly timed nets that alter the prey-capture opportunity. They do not prove that a buzz always represents a successful swallowed fish. The multimodal evidence links acoustic behavior to coordinated hunting while preserving the distinction between measured activity, inferred capture attempts and proposed social mechanisms.')
assert len(slides)==44,len(slides)
# Native theme unique to this special-topic deck.
theme='silver-lake';themes=json.loads((BASE.parents[1]/'course/themes.json').read_text());themes['palettes'][theme]={'label':'silver lake / quiet blue','title_bg':'DAE2EB','title_text':'334D6C','title_muted':'334D6C','bg':'FFFFFF','heading':'334D6C','text':'000000','muted':'000000','tint':'F1F4F8','accent':'334D6C','rule':'D6DEE7'};(BASE.parents[1]/'course/themes.json').write_text(json.dumps(themes,indent=2)+'\n')
title=R['madsen13'];spec={'lecture':41,'theme':theme,'content_slides':44,'title_image':json.loads((BASE/'sources/title-photo.json').read_text()),'title_refs':[title['reference']],'slides':slides,'takeaways':{'items':[
{'lead':'Pneumatic nasal source.','text':'Pressurized air drives phonic-lip motion; recorded dolphins can produce dynamic echolocation clicks from a single right-side source.'},
{'lead':'Specialized reception anatomy.','text':'Mandibular fats contact the ear complex, while cochlear hair cells and associated fibers form the peripheral auditory apparatus. Protein localization alone is not a functional test.'},
{'lead':'Central pathways.','text':'Diffusion imaging supports midbrain–thalamus–temporal and auditory–cerebellar connections. Streamlines do not establish synapses, signal direction or activity during hunting.'},
{'lead':'Population responses and controls.','text':'Click-evoked auditory responses follow sound arrival. Earlier production-related potentials and their masking resistance distinguish them from responses to self-heard sound.'},
{'lead':'Flexible active sensing.','text':'Dolphins regulate click timing, packet use, output level and investigation effort according to distance, prior experience and the discriminability of the acoustic scene.'},
{'lead':'Prey capture and natural context.','text':'Terminal buzzes combine rapid sampling with reduced output. Tag and multimodal field studies link this acoustic behavior to fish interception and coordinated dolphin–fisher hunting.'}], 'cite':'Madsen et al. (2013, 2023); Berns et al. (2015); Finneran et al. (2017, 2018); Harley et al. (2022); Cantor et al. (2023)','refs':[R[k]['reference'] for k in R]}}
(BASE/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
for i,s in enumerate(slides,2):
 words=len(re.sub(r'\*\*|_','', ' '.join(s['body'])).split());print(i,words,s['title'])
