from pathlib import Path
import json
p=Path(__file__).parent;r=p.parents[1]
refs={
'O':"O'Keefe J, Dostrovsky J (1971). The hippocampus as a spatial map. Preliminary evidence from unit activity in the freely-moving rat. Brain Research 34(1): 171–175. https://doi.org/10.1016/0006-8993(71)90358-1",
'H':'Hafting T, Fyhn M, Molden S, Moser MB, Moser EI (2005). Microstructure of a spatial map in the entorhinal cortex. Nature 436(7052): 801–806. https://doi.org/10.1038/nature03721',
'G':'Giocomo LM, Hussaini SA, Zheng F, Kandel ER, Moser MB, Moser EI (2011). Grid cells use HCN1 channels for spatial scaling. Cell 147(5): 1159–1170. https://doi.org/10.1016/j.cell.2011.08.051'}
cites={'O':"O'Keefe & Dostrovsky (1971)",'H':'Hafting et al. (2005)','G':'Giocomo et al. (2011)'}
figs={'O1':'1. Spatially dependent CA1 response to restraint', 'animal':'1 (upper). Rat position and orientation on the platform','H1':'1(a–d). Recording site and repeated spatial firing','Ha':'1(a). Nissl-stained rat entorhinal recording site','H1b':'1(b). Trajectories, rates and spatial autocorrelations','H1d':'1(d). Grid fields in large and small arenas','H2a':'2(a,c). Rat recording site and dorsal grid fields','H2b':'2(b,d). Ventral recording site and grid fields','H2e':'2(e). Grid spacing and orientation at two sites','H2fg':'2(f–h). Recording depth and spatial scale','H3':'3(a–c). Spatial phases of neighboring grid cells','H3b':'3(b). Spatial cross-correlations of neighboring cells','H4':'4(a–d). Grid alignment during cue-card rotation','H5':'5(a–d). Grid activity during light and darkness','H5a':'5(a). Trajectory and rate maps across light conditions','H6a':'6(a). Spatial firing during novel-room exposure','H6b':'6(b,c). Rate-map stabilization across exploration','G1A':'1(A). Control grid-cell rates and autocorrelations','G1B':'1(B). Grid-cell patterns after HCN1 knockout','G2A':'2(A). Grid patterns at several recording depths','G2BC':'2(B,C). Grid spacing and field size versus depth','G3':'3(A,B). Grid fields and corresponding stained sections','Ga':'3(A, upper histology). Mouse sagittal brain section and entorhinal recording location','G4A':'4(A). Grid patterns along one knockout recording series','G4B':'4(B). Spacing versus depth within a knockout animal','G5A':'5(A). Spike-time and spatial autocorrelations','G5BC':'5(B,C). Theta timing and speed modulation','G6A':'6(A). Boundary-related firing in control mice','G7A':'7(A). Directional firing in control mice'}
def fig(k):
 z='O' if k=='animal' else k[0];return {'kind':'article','path':f'figures/{k}.png','caption':cites[z].replace(' & ',' & ')+', Fig. '+figs[k]+'.','source_url':refs[z].split('https://doi.org/')[1].join(['https://doi.org/',''])}
slides=[]
for block in (p/'content.txt').read_text().split('==='):
 lines=block.strip().splitlines();title,k=lines[0].split('|');body=lines[1:];z=k[0];an='Ga' if z in ['O','G'] else 'Ha';used=[z]+(['G'] if z=='O' else [])
 s={'layout':'figures-right','title':title,'body':body,'transcript':body,'cite':'; '.join(cites[v] for v in used),'refs':[refs[v] for v in used],'figures':[fig(k),fig(an)],'figure_arrangement':'side-by-side','primary_figure_width':4.0}
 slides.append(s)
assert len(slides)==44
items=[('Place coding.',"Hippocampal activity can depend on location together with sensory conditions, facing direction and behavioral state."),('Grid geometry.',"Entorhinal grid cells have repeated fields whose spacing, orientation and spatial phase are distinct properties."),('Landmarks and self-motion.',"Landmarks align grid activity; persistence in darkness supports movement-based updating without proving independence from all external cues."),('Anatomical scale.',"Grid spacing and field size increase toward ventral entorhinal recording locations."),('HCN1 contribution.',"Forebrain HCN1 deletion expands grid scale and slows theta-related timing while preserving periodicity and the anatomical scale gradient."),('Evidence and mechanism.',"Spatial firing establishes a representation; a complete causal account of navigation requires circuit and behavioral tests beyond these recordings.")]
spec={'lecture':37,'theme':'umber-pearl','content_slides':44,'title_image':fig('animal'),'slides':slides,'takeaways':{'cite':'; '.join(cites.values()),'refs':list(refs.values()),'items':[{'lead':a,'text':b} for a,b in items]}}
(p/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False))
t=json.loads((r/'course/themes.json').read_text());t['palettes']['umber-pearl']={'label':'muted umber / pearl','title_bg':'493B35','title_text':'FFFFFF','title_muted':'D9CEC8','bg':'FFFFFF','heading':'493B35','text':'000000','muted':'000000','tint':'F3F0EE','accent':'493B35','rule':'D8D1CC'};(r/'course/themes.json').write_text(json.dumps(t,indent=2)+'\n')
