"""Build Lecture 30 from verified primary studies and unmodified source panels."""
import copy,json
from pathlib import Path
B=Path(__file__).resolve().parent
sources={p['id']:p for p in json.loads((B/'research.json').read_text())['papers']}
CITE={'frost02':'Mouritsen & Frost (2002)','froy03':'Froy et al. (2003)','sauman05':'Sauman et al. (2005)','zhu08':'Zhu et al. (2008)','merlin09':'Merlin et al. (2009)','heinze11':'Heinze & Reppert (2011)','guerra12':'Guerra et al. (2012)','guerra13':'Guerra & Reppert (2013)','nguyen21':'Nguyen et al. (2021)','beetz23goal':'Beetz et al. (2023)','iiams24':'Iiams et al. (2024)','stalleicken05':'Stalleicken et al. (2005)'}
F={}
def fig(name,source,number,caption):
 F[name]={'path':f'figures/{name}.png','kind':'article','caption':f'{CITE[source]}, Fig. {number}. {caption}','source_url':'https://doi.org/'+sources[source]['doi']}
for args in [
 ('f02_f1bcd','frost02','1(B–D)','Published virtual trajectories derived from tethered headings.'),
 ('f02_f2abc','frost02','2(A–C)','Headings on local, advanced and delayed light cycles.'),
 ('f02_f2a','frost02','2(A)','Local-time migrants maintain southwest headings.'),
 ('f03_f1a','froy03','1(A)','Adult emergence under light–dark and constant conditions.'),
 ('f03_f1b','froy03','1(B)','Head per RNA: blue, light–dark; teal, darkness; magenta, constant light.'),
 ('f03_f2','froy03','2','Orientation after shifted cycles or constant light.'),
 ('f03_f3c','froy03','3(C)','Heading distributions before, during and after UV interference.'),
 ('f03_f3d','froy03','3(D)','Adult emergence entrained without ultraviolet light.'),
 ('s05_f2','sauman05','2(A–C)','UV, blue and long-wavelength opsin RNA in retinal cells.'),
 ('s05_f3','sauman05','3(A–D)','UV-specialized ommatidia in the dorsal rim area.'),
 ('s05_dra','sauman05','3(D)','UV opsin staining in the dorsal rim area.'),
 ('s05_f4','sauman05','4(A–D)','Filter rotation and UV interference during tethered flight.'),
 ('s05_f5','sauman05','5(B–J)','PER-stained cells and daily staining changes.'),
 ('s05_f6de','sauman05','6(D–E)','CRY1 and PER labeling in the same pars lateralis cell.'),
 ('z08_f2','zhu08','2(A–D)','Clock-protein levels after light and cry1 knockdown.'),
 ('z08_f3bc','zhu08','3(B–C)','TIM and corazonin labeling in pars lateralis cells.'),
 ('z08_f5a','zhu08','5(A)','Transcriptional reporter responses to clock proteins.'),
 ('z08_f5b','zhu08','5(B)','Protein knockdown and transcriptional reporter activity.'),
 ('z08_f5c','zhu08','5(C)','Clock-protein co-immunoprecipitation from brain and cells.'),
 ('z08_f5d','zhu08','5(D)','per RNA after cry2 knockdown across a light–dark cycle.'),
 ('z08_f6gh','zhu08','6(G–H)','Nuclear CRY2 and per RNA across circadian phase.'),
 ('z08_f6de','zhu08','6(D–E)','CRY2 and corazonin in pars lateralis cells.'),
 ('z08_f7ijk','zhu08','7(I–K)','Central-body CRY2 staining varies in constant darkness.'),
 ('m09_f1ab','merlin09','1(A–B)','Intact and antenna-less headings on two light cycles.'),
 ('m09_f1c','merlin09','1(C)','Released intact and antenna-less butterflies maintain flight.'),
 ('m09_f2ab','merlin09','2(A–B)','Antennal clock RNA in light–dark and constant darkness.'),
 ('m09_f2de','merlin09','2(D–E)','TIM rhythms in isolated antennal cultures.'),
 ('m09_f3ab','merlin09','3(A–B)','Paint transmission and light-dependent TIM depletion.'),
 ('m09_f4a','merlin09','4(A)','Orientation with clear or black antennal paint.'),
 ('g12_f1','guerra12','1(a–b)','A single antenna supports clock-shifted orientation.'),
 ('g12_f2','guerra12','2(A–C)','Conflicting antennae and rescue after black antenna removal.'),
 ('h11_f2','heinze11','2(A–J)','Synapsin-labeled central-complex and associated neuropils.'),
 ('h11_tl','heinze11','3(A)','Dye-filled tangential input neuron TL2.'),
 ('h11_tl3','heinze11','3(B)','Dye-filled tangential input neuron TL3.'),
 ('h11_f4b','heinze11','4(A–D)','Intracellular polarization responses and tuning.'),
 ('h11_f5','heinze11','5(A–F)','Azimuth tuning to UV, blue and green light spots.'),
 ('h11_f6','heinze11','6(A–F)','Dorsal masking separates polarization and azimuth responses.'),
 ('n21_f3','nguyen21','3(a–c)','Migratory and non-migratory tangential-neuron tuning.'),
 ('n21_f4','nguyen21','4(a–c)','Angular sensitivity and its inferred solar geometry.'),
 ('g13_f1bc','guerra13','1(A–C)','Migration map and seasonal bearings, including a clock shift.'),
 ('g13_f3bc','guerra13','3(B–C)','Northward headings after two cold-treatment schedules.'),
 ('g13_f4','guerra13','4(A–B)','Warm-housed fall migrants retain southward orientation.'),
 ('i24_f1','iiams24','1(A–C)','Cry1 loss alters emergence rhythms and brain clock RNA.'),
 ('i24_f3','iiams24','3(A–B)','Hourly flight activity in wild-type and Cry1 mutants.'),
 ('b23_f3bf','beetz23goal','3(b,f)','Neural tuning during heading and goal manipulations.'),
 ('st05_f4','stalleicken05','4(A–C)','Orientation with polarization, sun and unpolarized controls.'),
 ('st05_f5','stalleicken05','5(A–F)','Orientation with dorsal rim masking and the masked eye.')]:fig(*args)
WEB={'path':'figures/monarch_fws.jpg','kind':'web','caption':'Photo: Monarch butterfly with compound eye and antenna visible.','credit':'U.S. Fish and Wildlife Service','license':'Public Domain','source_url':'https://www.fws.gov/media/monarch-butterfly-danaus-plexippus'}
F['antenna']=WEB
S=[]
def add(title,refs,images,text,extra,side=False,primary_h=2.8):
 ids=refs.split();body=text.split('||')
 sd={'layout':'figure-right' if len(images)==1 else 'figures-right','title':title,'body':body,'cite':'; '.join(CITE[x] for x in ids),'refs':[sources[x]['reference'] for x in ids],'transcript':[body[0],[body[1],[extra]],*body[2:]],'figure_width':6.0}
 if len(images)==1:sd['figure']=copy.deepcopy(F[images[0]])
 else:
  sd['figures']=[copy.deepcopy(F[x]) for x in images]
  sd['primary_figure_height']=primary_h
  if side:sd.update(figure_arrangement='side-by-side',primary_figure_width=3.7)
 S.append(sd)

add('Autumn migrants maintain a southwest flight bearing','frost02',['f02_f2a'],'''Eastern North American monarch butterflies, _Danaus plexippus_, migrate toward overwintering sites in central Mexico. Some journeys exceed 3,500 km. A **bearing** is a direction measured around the horizon relative to geographic north.||Mouritsen and Frost recorded autumn migrants in an outdoor flight simulator that permitted turning around a vertical tether. Butterflies maintained southwest headings under a visible sky, with a group mean of 225° when their light schedule matched local time.||Their **sun compass** uses solar direction as an orientation reference. Sustained headings establish directional behavior in this preparation, but the tether prevents actual travel. A southwest bearing alone cannot establish destination recognition, route selection or how an insect corrects displacement during a complete migration.''','Geographic bearings increase clockwise from north: east is 90°, south 180° and west 270°. A southwest heading of 225° lies between south and west. The simulator measures the direction an animal attempts to fly, whereas arrival in Mexico would require additional observations of travel and destination finding.')
add('A vertical tether preserves turning without translation','frost02',['f02_f1bcd'],'''The simulator separated heading control from forward travel. A fine wire attached to the dorsal thorax allowed the butterfly to rotate freely, while a cylinder approximately 59 cm wide and 64 cm high restricted its view to the sky above.||Vertical airflow supported flight without supplying a horizontal wind direction. The apparatus sampled heading every 200 ms, preserving sustained orientation and changes in course during an individual trial.||Published **virtual trajectories** were reconstructed from those headings using an assumed flight speed. Their apparent distances are therefore calculated paths, not measured displacement. The original trajectories retain evidence of stable versus variable heading, while the preparation excludes landscape landmarks and limits conclusions about unrestricted flight. These constraints allow solar orientation to be tested under controlled visual access.''','The tether fixes position but leaves the relevant horizontal turning movement available. A virtual track integrates recorded headings under the authors’ speed assumption of 18 km/h. Neither a long reconstructed path nor a straight one means that the tethered insect actually covered that distance.')
add('Rotating the apparatus does not rotate the compass','frost02',['f02_f1bcd'],'''A consistent tethered heading could arise from an unnoticed feature of the simulator rather than a geographic cue. Mouritsen and Frost therefore rotated the entire apparatus and separately rotated its components during directional flight.||Butterflies did not follow the new apparatus orientation. When an individual was manually turned away from its established heading, it could return toward the previous geographic direction. The heading records contained sustained orientation despite the absence of forward movement.||These controls reduce explanations based on a fixed mark, mechanical asymmetry or the tether’s angular position. They do not specify which sky cue is necessary. An intervention that changes internal time while retaining the same external sky can distinguish solar orientation with time compensation from a response determined only by the current sun position.''','The same geographic direction has a different relationship to the apparatus after rotation. Maintaining that direction is therefore inconsistent with following a mark that rotates with the cylinder. This control does not eliminate every sensory artifact, and the virtual trajectories remain reconstructions rather than movement through a landscape.')
add('Advancing the clock rotates flight toward the southeast','frost02',['f02_f2abc'],'''**Time compensation** adjusts compass output as the sun changes its position during the day. A **circadian clock** is an internal timing system with a rhythm close to 24 h; **entrainment** aligns its phase with a recurring environmental cycle.||Migrants experienced a 12-h light:12-h dark cycle advanced by 6 h for at least five days. Tested outdoors under the same actual sky as local-time controls, the advanced group oriented near 136°, toward the southeast, rather than the controls’ 225° southwest.||The approximately 89° counterclockwise change links orientation to internal time. An insect treating the afternoon sun as a later time must select a different bearing to maintain its programmed compass relationship. The manipulation supports a time-compensated sun compass, without identifying the clock tissue or its neural output.''','Phase is the position within a repeating cycle, such as the timing of light onset. Advancing the light schedule changes the animal’s temporal interpretation while the testing sky remains shared with controls. The observed angular shift belongs to these dates and solar positions; a 6-h clock shift does not imply one universal rotation angle.')
add('Delaying the clock produces the opposite heading change','frost02',['f02_f2abc'],'''A reciprocal clock manipulation tests whether the heading change has the direction expected from solar time compensation. Mouritsen and Frost delayed the entraining 12-h light:12-h dark cycle by 6 h before testing autumn migrants in the same simulator.||Delayed butterflies oriented near 335°, toward the northwest. Relative to the local-time mean of 225°, their heading changed approximately 110° clockwise, opposite to the counterclockwise change after a 6-h advance.||The two shifts support a signed relationship between clock phase and compass direction rather than a nonspecific disturbance from laboratory housing. Their unequal magnitudes reflect the observed solar geometry and experimental conditions. These results establish a compass response to manipulated time, rather than a direct measure of the complete molecular clock or a geographic map.''','A geographic map would provide information about position or destination, whereas a compass provides a direction. Advancing and delaying time can alter a compass even if the insect has no positional information. The observed clock-shift responses therefore support directional time compensation without resolving a map mechanism.')
add('Constant light leaves orientation tied to the visible sun','froy03',['f03_f2'],'''Froy and colleagues compared migrants entrained to local or 6-h-advanced light schedules. Under normal light–dark conditions, their mean headings were 233° and 118°, respectively, retaining the expected dependence on internal time.||After five days in **constant light**, uninterrupted illumination rather than a daily light–dark cycle, the two groups no longer retained their distinct compass bearings. They oriented near 161° while the sun lay approximately between 136° and 160°.||A direction toward the current sun is compatible with **positive phototaxis**, movement toward a light source. Such orientation differs from maintaining a migration bearing as the sun moves. Constant light disrupts normal circadian organization, but it can affect other physiological processes; the treatment does not selectively isolate one clock molecule.''','The butterflies remained capable of directional flight after constant-light exposure. Losing the separation between previously entrained groups is therefore different from becoming unable to fly. Orientation close to the solar azimuth can persist when normal time compensation is disrupted, but that relationship alone does not establish the underlying sensory rule.')
add('Blocking ultraviolet light disrupts sustained flight','froy03 sauman05',['f03_f3c','s05_dra'],'''**Ultraviolet light**, or UV, has shorter wavelengths than human-visible violet light. Froy and colleagues placed a filter blocking wavelengths below 394 nm over outdoor flight tests while retaining approximately 87% of photopic luminous transmission.||The filter interrupted sustained flight or altered heading records; removing it restored sustained flight in most affected butterflies. Sauman and colleagues localized UV-sensitive visual pigment to the **dorsal rim area**, a specialized strip along the upper compound-eye margin.||The reversible effect associates the available UV signal with flight under these conditions. It does not uniquely establish a polarization compass, because the intervention changes spectral input and the continuity of flight together. A loss of stable heading may result partly from altered flight behavior rather than selective removal of directional information.''','Photopic luminous transmission weights light according to human daylight vision. Retaining most of that measure does not mean that a monarch receives an unchanged stimulus. Removing UV can alter a sensory channel disproportionately even when the scene remains visibly bright to a human observer. The eye staining identifies a UV-specialized region, while the flight manipulation tests behavior.',True)
add('Visible light can entrain the emergence rhythm','froy03',['f03_f3d'],'''The wavelengths needed for an oriented-flight assay need not be identical to those that entrain the clock. Froy and colleagues reared pupae under light–dark cycles with a UV-blocking filter and measured the timing of **eclosion**, adult emergence from the pupal case.||Emergence remained concentrated at a particular phase of the daily cycle. Advancing the UV-filtered light schedule by 6 h moved the emergence peaks approximately 5.5 h apart, establishing effective temporal entrainment without ultraviolet illumination.||The result separates a timing response from the previously observed flight disruption. Visible wavelengths can convey daily timing information in this preparation. Eclosion is an output of circadian organization, however, and its entrainment does not by itself identify the sensory pathway that supports migratory heading in an adult.''','The pupal emergence assay and the adult flight assay measure different behaviors at different developmental stages. A spectral treatment can preserve one while disrupting the other. The 5.5-h separation refers to observed emergence peaks after the two light schedules, rather than a measured angular change in flight direction.')
add('Retinal cells express distinct visual-pigment proteins','sauman05',['s05_f2'],'''A compound eye contains repeated optical units called **ommatidia**. Each monarch ommatidium contains photoreceptor cells whose light-sensitive membrane forms a **rhabdom**. An **opsin** is the protein component of a visual pigment that contributes to its spectral sensitivity.||Sauman and colleagues used **in situ hybridization**, labeled probes that locate specific RNA sequences in tissue sections, to identify UV-, blue- and long-wavelength opsin expression. UV and blue opsin RNA occupied R1 or R2 cells; long-wavelength opsin RNA occupied R3–R8.||These distributions establish distinct molecular receptor types in the main retina. They support multiple spectral inputs to vision, but RNA localization alone does not measure a cell’s electrical response or the sensitivity of an entire compass neuron. The reported patterns do not identify downstream transmitters, ion channels or synaptic connections.''','RNA is a molecular transcript used in producing a protein. The probes distinguish opsin transcripts rather than recording receptor voltage. Adjacent tissue sections allowed cells with different transcripts to be compared. An ommatidium’s spectral composition concerns its receptor molecules; the eventual compass response also depends on neural processing after light detection.')
add('The dorsal rim area is specialized for ultraviolet input','sauman05',['s05_f3'],'''The dorsal rim area differs molecularly from adjacent main-retina ommatidia. Sauman and colleagues found UV opsin RNA throughout R1–R8 in this strip, with no detected blue or long-wavelength opsin RNA in those dorsal-rim cells.||The specialization extended approximately 40–50 ommatidia along the eye margin and one to three ommatidia inward, totaling roughly 100 per eye. Antibody labeling localized UV opsin protein to their rhabdoms; adjacent retinal tissue provided a comparison with mixed receptor types.||A common spectral class is consistent with sampling polarization without mixing distinct color signals. **Linear polarization** specifies the orientation of the light wave’s electric field. Molecular specialization supports a candidate polarization input, but selective expression alone does not establish how the animal uses that input during migration.''','Antibody labeling detects the visual-pigment protein, complementing the RNA probes. The anatomical difference is localized to a narrow dorsal strip rather than the entire retina. Photoreceptor geometry and behavioral use are additional questions: UV expression identifies a sensory specialization but does not establish a complete navigational computation.')
add('Polarizer rotation changes flight in a restricted assay','sauman05',['s05_f4','s05_dra'],'''Sauman and colleagues tested tethered monarchs beneath a linear polarizing filter that restricted skylight access to an 80° field and excluded direct sight of the sun. Turning the filter by 90° changed the available electric-field orientation.||Sequential 5-min records compared flight before rotation, after rotation, during UV interference below 397 nm, and after removing the UV filter. UV interference often produced circling and reduced virtual progress by at least 70%; removal restored sustained directional flight.||The responses support sensitivity to manipulated polarized UV under this restricted arrangement. They do not establish that natural migration depends on the same cue. Spectral interference also altered flight continuity, and a polarizer can introduce brightness-dependent effects that require separate controls. The UV-specialized dorsal rim provides an anatomical candidate for this input.''','A polarization axis repeats after 180°, unlike a directed bearing that repeats after 360°. A 90° filter rotation therefore exchanges orthogonal axes. The assay combined an artificial polarizer with restricted sky access, and the reported virtual progress depends on flight stability as well as heading. It cannot by itself establish normal migratory use.',True)
add('Polarized-light behavior requires brightness controls','stalleicken05',['st05_f4'],'''Stalleicken and colleagues compared orientation under a polarizing filter when the sun was excluded, when the sun was visible, and with an unpolarized-light control. Their controlled tests did not establish reliable migratory orientation based on polarized skylight alone.||With the sun available, monarchs retained directional orientation. The study identified brightness-related cues associated with the experimental optical arrangement as a possible contributor to earlier polarizer responses; rotating a filter need not change only polarization direction.||These findings qualify the behavioral interpretation without denying polarization-sensitive visual physiology. A response to an artificial stimulus and a cue’s necessity for migration are different claims. Natural compass use requires controls that separate polarization from intensity patterns and access to other celestial cues, rather than treating every polarizer-induced turn as time-compensated navigation.''','A filter can interact with surrounding surfaces and illumination so that different viewing directions have different brightness. A butterfly could then follow an intensity feature instead of computing a skylight polarization axis. The study’s negative result concerns migratory orientation in its tested conditions and does not erase direct recordings of polarization-sensitive neurons.')
add('Dorsal-rim masking leaves sun-based orientation intact','stalleicken05',['st05_f5'],'''Selective masking asks whether the UV-specialized dorsal eye margin is necessary when other sky cues remain available. Stalleicken and colleagues covered the dorsal rim area and compared migratory orientation with that of untreated butterflies under a visible sun.||Masked animals retained directional flight, and the study’s clock-shifted tests remained consistent with a time-compensated sun compass. The published eye preparation documents the position of the mask rather than assuming that the whole retina was obstructed.||The result supports a sun-based pathway that can operate without normal dorsal-rim input in these conditions. It does not establish that polarization information is never used or that every possible sky condition yields the same outcome. Receptor specialization, neural responsiveness and behavioral necessity must be tested separately.''','The dorsal-rim mask targets a limited region, leaving much of the compound eye available. A retained compass response is evidence against strict necessity in that preparation. It does not determine whether polarization helps under other conditions, nor does it identify the retinal cells that carry the surviving solar-direction signal.')
add('Emergence persists without a daily light signal','froy03',['f03_f1a'],'''An endogenous rhythm continues after the external cycle is removed. Froy and colleagues entrained monarch pupae under a light–dark schedule and then compared adult emergence in continued cycling light, constant darkness and constant light.||Eclosion clustered early in the light phase and remained rhythmic in constant darkness. A 6-h shift in the prior light schedule altered the emergence phase. Constant light disrupted the normal temporal concentration of emergence.||Persistence in darkness supports an internal circadian oscillator rather than an immediate response only to lights turning on. **Free-running** means that a rhythm proceeds without daily entrainment. The emergence assay establishes an endogenous timing output, but its phase and tissue requirements should not automatically be equated with the adult migratory compass.''','An environmental cycle can impose a daily pattern even without an autonomous clock. Continued rhythmic emergence in darkness provides a stronger test because the light transition is absent. Constant light and constant darkness are biologically different treatments: removing the daily transition does not guarantee that both conditions affect clock organization in the same way.')
add('The per transcript changes with circadian phase','froy03',['f03_f1b'],'''The **period gene**, abbreviated _per_, encodes a clock-associated protein. Froy and colleagues measured its RNA in monarch heads across the day to connect behavioral timing with a molecular rhythm. **Transcription** is the production of RNA from a DNA template.||Head _per_ RNA was higher at night and lower during the day in a light–dark cycle. Its rhythm persisted, with altered amplitude and phase, in constant darkness; constant light maintained comparatively low, nonrhythmic levels in this assay.||The molecular and emergence measurements support endogenous circadian organization. Whole-head sampling combines multiple tissues, however, so the RNA profile does not locate a unique compass clock. A rhythmic transcript is a candidate component whose functional role requires perturbation, rather than proof that its abundance alone specifies flight direction.''','The daily RNA change is not a direct reading of an animal’s perceived hour. It is one molecular feature associated with clock phase. Pooling head tissue also combines signals that can differ among cell populations, so a strong aggregate rhythm cannot establish where the relevant timing information originates.')
add('PER marks candidate clock cells in the lateral brain','sauman05',['s05_f5'],'''Sauman and colleagues localized **PER**, the protein encoded by _per_, using antibodies in adult monarch brain sections. The **pars lateralis**, or PL, is a lateral brain region containing candidate clock cells; the **pars intercerebralis**, or PI, is a medial region with neurosecretory cells.||PL cells had little detectable PER at zeitgeber time 6 but strong labeling near zeitgeber time 18. **Zeitgeber time**, abbreviated ZT, measures hours relative to the entraining cycle, with ZT0 at lights-on. Daily PL staining persisted in constant darkness and was disrupted in constant light.||These observations localize rhythmic molecular components more precisely than a whole-head assay. They do not prove that PL clocks exclusively supply migratory time compensation. Rhythmic brain cells can coexist with timing oscillators elsewhere in the animal.''','An antibody signal indicates the location and relative abundance of the recognized protein. The nighttime increase in PL staining is compatible with a clock-associated rhythm, while the constant-dark condition tests persistence without daily illumination. Identifying a rhythmic brain population does not establish which behavior requires that population.')
add('CRY1 links light exposure to clock-protein depletion','zhu08 sauman05',['z08_f2','s05_f6de'],'''Monarchs possess two **cryptochromes**, proteins associated with light sensing and circadian timing. **CRY1** acts as a blue-light-responsive component. Zhu and colleagues used cultured monarch DpN1 cells to test how reducing CRY1 changes the response to illumination.||**RNA interference** reduces expression using complementary RNA. Compared with a control targeting green fluorescent protein, _cry1_ interference prevented the normal light-dependent decline of **TIM**, the TIMELESS clock protein. In controls, TIM decreased before PER and CRY2 during the light-exposure time course.||These protein measurements support CRY1-dependent light input to clock regulation. They do not identify a complete biochemical degradation pathway or prove that cultured cells reproduce every property of adult antennal clocks. Brain labeling places CRY1 with PER in candidate clock cells.''','The depletion sequence separates the timing of measured protein changes from an inferred molecular cascade. TIM declined from approximately 10 min of illumination, whereas substantial PER and CRY2 decreases occurred later, near 120 and 240 min. A control RNA interference treatment addresses effects of the manipulation that are unrelated to reducing CRY1.',True)
add('Brain TIMELESS responds to circadian phase and light','zhu08',['z08_f3bc'],'''Zhu and colleagues localized TIMELESS protein in monarch brain cells and compared its abundance across daily phases. In the pars lateralis, TIM labeling overlapped with **corazonin**, a neuropeptide marker identifying the same cell group.||TIM staining was stronger near ZT15 than ZT6, and PL differences persisted in constant darkness. A 1-h light pulse at ZT15 reduced the PL signal relative to the unpulsed condition. These measurements connect molecular phase with acute sensitivity to illumination.||The anatomical overlap identifies candidate timing cells, while the pulse tests their protein response. Corazonin labeling does not establish that corazonin transmits clock information to the compass. Neither the peptide’s downstream receptor nor a complete pathway from these cells to steering was identified by the staining experiment.''','The red TIM and green corazonin labels were obtained by double-labeling the same brain region. Co-localization means that both markers occur in the identified cells; it is not a measurement of peptide release. The light-pulse comparison concerns TIM abundance, whereas the identity of a synaptic output requires different experiments.')
add('CRY2 represses clock-controlled transcription','zhu08',['z08_f5a','z08_f6de'],'''**CRY2** is the second monarch cryptochrome and has a different tested role from CRY1. Zhu and colleagues introduced clock proteins into DpN1 cells and measured a _per_ regulatory sequence coupled to a **luciferase reporter**, a light-producing readout of transcriptional activity.||The transcription factors **CLOCK** and **CYCLE**, abbreviated CLK and CYC, activated the reporter. Adding CRY2 reduced this activity with increasing amounts of CRY2 expression construct, including 5, 15 and 50 ng; CRY1 did not provide the same repression.||This functional assay supports CRY2 as a negative regulator of clock transcription. Brain staining also localized CRY2 to corazonin-positive PL cells. A reporter assay identifies a regulatory relationship, but it does not directly measure migratory heading or prove how clock phase is communicated beyond the cell.''','A transcription factor is a protein that regulates expression through DNA-associated interactions. The reporter places light production under the tested per regulatory sequence, allowing its activation and repression to be compared. The nanogram values describe DNA introduced into cultured cells, rather than endogenous protein concentrations in a butterfly.',True)
add('Reducing CRY2 removes normal transcriptional repression','zhu08',['z08_f5b','z08_f5d'],'''A loss-of-function test complements adding CRY2 to a transcriptional reporter. Zhu and colleagues reduced endogenous CRY2 in DpN1 cells using RNA interference and compared the treatment with interference directed against a control sequence.||CRY2 reduction increased reporter activity approximately threefold. Across a 24-h light–dark cycle, _per_ RNA remained near peak values after _cry2_ interference instead of following the control’s rise and fall. The protein measurements confirmed depletion of the targeted regulator.||These findings support CRY2-mediated negative feedback: clock-associated proteins restrain the transcription that contributes to their production. The cells’ light-driven molecular changes were not sustained as autonomous rhythms in constant darkness, so this preparation does not establish a fully self-sustained cellular oscillator under every condition.''','Negative feedback means that an output acts back to reduce the process producing it. The knockdown and reporter assays support that relationship for CRY2, rather than merely correlating its abundance with time. The separate constant-dark result limits what can be inferred about autonomous timing from the cultured-cell light–dark cycle.')
add('Clock proteins form complexes that support CRY2 stability','zhu08',['z08_f5c','z08_f6de'],'''Clock regulation depends on protein interactions as well as transcription. Zhu and colleagues used **co-immunoprecipitation**, antibody capture of a protein together with associated molecules, to examine PER, TIM and CRY2 in monarch brain extracts and cultured cells.||The captured material contained combinations of PER, TIM and CRY2. Reducing PER also reduced CRY2 protein without a corresponding reduction in _cry2_ RNA, supporting regulation after transcription. TIM interference produced a more modest reduction of PER and CRY2.||The findings are consistent with PER and TIM helping stabilize CRY2-containing complexes. Co-capture does not prove that every pair binds directly, and protein depletion does not specify the degradation enzymes. The evidence constrains a molecular feedback mechanism without establishing a complete biochemical reaction sequence.''','Post-transcriptional regulation changes protein production or persistence without requiring a parallel change in the RNA encoding it. The association experiment and the knockdown experiment supply different evidence: one identifies co-captured complexes, and the other tests dependence of protein abundance on another clock component.',True)
add('Nuclear CRY2 varies with clock phase','zhu08',['z08_f6gh'],'''The **nucleus** contains the DNA used for transcription, so a transcriptional repressor’s cellular location affects its access to clock regulation. Zhu and colleagues compared CRY2 nuclear labeling with _per_ RNA across circadian phase.||In pars lateralis clock cells, nuclear CRY2 was concentrated around ZT2–4 and near circadian time 3 in constant darkness. **Circadian time**, or CT, refers to internal phase under free-running conditions. The measured nuclear signal changed with phase rather than remaining continuously high.||The relationship supports timed nuclear repression within the molecular feedback cycle. Tissue labeling and RNA measurements do not establish every transport step or the causal timing of each interaction. They also do not locate the downstream signal that turns an intracellular clock phase into a particular migratory bearing.''','The plotted nuclear signal is a measured localization outcome, distinct from total protein abundance. CRY2 can therefore change its regulatory availability without requiring an identical change in the whole-cell amount. Persistence of a phase-dependent signal in darkness supports endogenous timing, while the mechanism transporting CRY2 remains incompletely specified.')
add('Rhythmic CRY2 occurs in central-body fibers','zhu08 heinze11',['z08_f7ijk','h11_f2'],'''The **central body** is a component of the insect central complex, a group of brain neuropils associated with orientation. A **neuropil** is a region rich in neuronal processes and synaptic connections rather than only cell bodies.||Zhu and colleagues detected CRY2-containing fibers in the central body. Staining intensity varied in constant darkness, with a maximum near CT15 and a minimum near CT9. Independent synapsin labeling by Heinze and Reppert identifies the relevant central-complex anatomy.||Rhythmic protein labeling in an orientation-associated region supports a possible connection between clock state and compass processing. It does not establish a functional clock-output synapse or the route carrying antennal timing. A causal pathway would require identifying the connected cells and manipulating their signal while measuring compass output.''','Synapsin is a synapse-associated protein used to delineate neuropil boundaries, whereas CRY2 labeling identifies a clock-associated molecule. Their use in separate studies does not create a direct connection between the labeled populations. The proposed clock-output interpretation therefore remains distinct from the measured phase-dependent staining.',True)
add('Removing antennae disrupts the group compass bearing','merlin09',['m09_f1ab','antenna'],'''The **antennae** are paired head appendages that contain sensory tissue and molecular clocks. Merlin and colleagues removed the antennal flagella, the long distal portions, and compared migratory orientation with intact butterflies.||Intact animals oriented near 211° on the normal light schedule and near 355° after a 6-h delay. Antenna-less butterflies could sustain an individual heading, but their directions no longer formed the normal common migratory bearing across animals.||The dissociation identifies an antennal contribution to time-compensated orientation rather than a complete loss of flight or direction-holding ability. Removal affects several antennal functions, so this experiment alone cannot assign the deficit specifically to a molecular clock. Paint and isolated-tissue experiments test the timing explanation more selectively.''','A strongly directed individual can still belong to a disorganized group if different animals select different directions. The analysis distinguishes the stability of one flight from agreement among migratory bearings. The removed antennal flagella are visible external structures, but the relevant deficit cannot be attributed to one sensory modality from removal alone.',True)
add('Antenna-less butterflies remain capable of free flight','merlin09',['m09_f1c','antenna'],'''An orientation deficit requires a motor control when the manipulated organ could influence flight. Merlin and colleagues released intact and antenna-less monarchs outdoors and compared whether they could maintain normal upward flight.||Most butterflies in both conditions flew normally after release. In simulator trials, antenna-less individuals also retained directional flight within a recording, despite losing the consistent group bearing expected from the entraining light cycle.||The combined observations reduce an explanation based on general inability to fly. They do not prove that antennal removal leaves every aspect of aerodynamic control unchanged. The measured outcome is sufficient to separate severe flight incapacity from compass disorganization, while preserving the need to identify which antennal signal supports the shared migratory direction.''','Free-flight release is a motor check outside the tethered apparatus. It establishes that the manipulated animals can leave the release point and sustain upward flight, rather than testing an entire migration. Stable individual headings and normal release flight together constrain a motor explanation for the compass deficit.')
add('Antennal clock-gene RNA remains rhythmic in darkness','merlin09',['m09_f2ab','antenna'],'''Merlin and colleagues measured clock-associated RNA in isolated samples of monarch antennae. **Quantitative PCR** estimates the abundance of selected RNA sequences after conversion to DNA, allowing the same transcripts to be compared across time points.||Antennal _per_, _tim_ and _cry2_ RNA varied across a light–dark cycle and remained rhythmic after transfer to constant darkness. Their levels were lower near ZT6 than ZT18 in the cycling condition; _cry1_ RNA did not have the same phase difference.||These measurements place a circadian molecular program in the appendages required for normal orientation. Tissue-level rhythms do not identify which antennal cells contain the oscillator or how their output reaches the compass. Persistence without the light cycle supports endogenous timing, rather than merely a direct response to illumination.''','The RNA measurements sample the antenna as a tissue, so they can combine several cellular populations. Different clock components need not have identical expression profiles. The presence of rhythmic per, tim and cry2 therefore supports a local clock program without requiring cry1 RNA itself to oscillate strongly.',True)
add('Isolated antennae retain a locally entrainable rhythm','merlin09',['m09_f2de','antenna'],'''A clock measured in antennae could still depend continuously on another tissue. Merlin and colleagues cultured separated antennae and exposed different explants, isolated tissue maintained outside the animal, to oppositely phased light–dark schedules.||TIM protein was lower around ZT6 and higher around ZT18 relative to each explant’s own light schedule. The rhythm continued with reduced amplitude during the first day of constant darkness after entrainment. No intact nervous-system connection remained in the culture.||The result supports autonomous, light-entrainable timing within antennal tissue over the measured interval. It does not establish indefinite persistence in culture or identify every oscillator cell. Removing central input distinguishes a local molecular rhythm from one that must be continuously imposed by the rest of the animal.''','The two opposing schedules provide different time references for otherwise comparable tissue cultures. TIM following each local schedule is stronger evidence for local entrainment than simply finding a rhythm in an intact antenna. The dark interval was limited, so autonomy should be described over that tested duration.',True)
add('Black paint blocks the antennal light response','merlin09',['m09_f3ab','antenna'],'''Merlin and colleagues coated antennal flagella with either black or clear enamel to distinguish light access from the general consequences of painting. Black paint blocked transmission across the tested 300–800 nm range; clear paint preserved transmission.||A 2-h light pulse during CT16–18 reduced antennal TIM protein when the coating was clear, but not when it was black. The pulse compared a molecular response to illumination while keeping the appendage physically present.||The comparison supports direct photic input, meaning input from light, to the antennal clock. It does not establish the full sequence from photon absorption to protein turnover. Clear paint also controls for coating-related interference with odor reception, allowing a later behavioral difference to be linked more specifically to blocked light access.''','A physical coating can interfere with more than one sensory function. Comparing black with clear enamel retains coating effects while changing optical transmission. The TIM response measures a clock-associated molecular consequence of light exposure, rather than the butterfly’s directional decision. The spectral transmission test verifies that the intended optical difference was achieved.',True)
add('Optically blocking antennae changes the selected heading','merlin09',['m09_f4a','antenna'],'''Butterflies with clear-painted antennae retained a consistent orientation and shifted their heading after a 6-h delay in the light cycle. In this later-autumn experiment, clear-painted controls oriented near 162°, and delayed controls near 269°.||Black-painted animals instead selected an abnormal northward bearing near 344° on the normal schedule; delayed black-painted animals were disorganized as a group. The antennae remained physically present, and the clear coating supplied a control for the painting procedure.||The results connect antennal light access to normal time-compensated orientation. Different unshifted means across studies do not imply a universal fixed angle: collection date and testing conditions differed. Blocking light can desynchronize or free-run antennal clocks, but an abnormal heading alone does not identify the precise clock phase in each animal.''','Clear-coated antennae were not normal odor receptors, yet they supported an oriented compass response. That comparison weakens an explanation based solely on olfactory impairment. The abnormal black-painted heading is a behavioral outcome; the inferred loss of appropriate antennal entrainment requires the separate molecular light-response evidence.',True)
add('One functioning antenna is sufficient for compensation','guerra12',['g12_f1','antenna'],'''Guerra and colleagues tested migrants after removing either the left or the right antenna. The remaining appendage retained access to light, allowing its timing contribution to be evaluated without a second functional antenna.||Both single-antenna groups selected a southwest bearing, with a combined mean near 217°. After a 6-h delay of the light cycle, their combined heading shifted to about 359°, approximately 142° clockwise. Left and right removal produced comparable compass performance.||The results support functional sufficiency of either antenna under the tested conditions. They do not establish how outputs from two intact antennae are combined. A system can work with one source of timing yet become disrupted when a second source supplies a conflicting signal rather than no signal.''','Sufficiency means that the remaining antenna can support the measured behavior in this preparation. It does not establish that two antennae are redundant in every environment. The clockwise shift follows a delay, consistent with time compensation, while its magnitude belongs to the solar geometry of this particular experiment.',True)
add('Conflicting antennal timing disrupts the shared bearing','guerra12',['g12_f2','antenna'],'''Guerra and colleagues painted one antenna black and the other clear, leaving one light-accessible timing system alongside one deprived of normal photic entrainment. They compared the condition with the orientation supported by a single accessible antenna.||Butterflies with discordant coatings maintained directed individual flights but lacked a consistent group migratory bearing. Either side could be black-painted, so the effect was not restricted to one lateral antenna. The unblocked appendage did not simply dominate the conflicting condition.||These observations support integration of information from both antennae. Antennal clock measurements associated the blocked side with disrupted population rhythms, but the experiment did not record the signal sent by each clock. The central site and cellular rules combining those signals remain unresolved.''','Discordant means that the two timing sources are not appropriately aligned. A black coating prevents normal light entrainment, but the experiment does not directly measure a unique phase in each blocked clock cell. Disorganization despite an accessible antenna is evidence that the second appendage can interfere with otherwise sufficient timing information.',True)
add('Removing the conflicting antenna restores orientation','guerra12',['g12_f2','antenna'],'''A within-animal rescue tested whether the abnormal second antenna caused the compass deficit. Guerra and colleagues first flew migrants with one black-painted and one clear-painted antenna, then removed the black-painted appendage and tested flight again.||The previously disorganized animals regained a southwest group heading near 214°. Combining repeated-flight and first-flight removal controls gave a mean near 216°, reducing an explanation based on experience with the simulator alone. The clear antenna remained available throughout the intervention.||Restoring orientation by removing a conflicting source provides stronger causal evidence than comparing unrelated groups alone. It supports coordinated antennal timing input while leaving its neural integration mechanism unidentified. The rescue does not imply that antennal removal is generally beneficial; its effect depends on which timing source is removed.''','A rescue reverses a deficit by changing a proposed cause. Here the remaining clear antenna could support orientation once the blocked antenna was absent. First-flight controls address the possibility that the second simulator exposure, rather than removal of the conflicting signal, produced the recovered group bearing.',True)
add('Central-complex neuropils define a compass substrate','heinze11',['h11_f2'],'''Heinze and Reppert mapped the monarch **central complex** using synapsin antibody labeling and three-dimensional reconstruction. The central body has upper and lower divisions, associated with a **protocerebral bridge**, a transverse neuropil, and paired **noduli**, compact neighboring neuropils.||The **anterior optic tubercle** is an additional visual-processing region. The **lateral accessory lobe** lies beside the central complex and receives identified neuronal processes associated with compass circuitry. Source scale bars distinguish whole-brain organization at 500 µm from central-complex details at 50 µm.||This anatomy specifies locations for cell recording and dye reconstruction. Synapse-rich boundaries do not themselves identify information flow, transmitter identity or behavioral necessity. Combining the map with individual-cell physiology tests which neurons respond to skylight cues rather than assigning a compass function from location alone.''','Synapsin labeling delineates regions containing many synaptic processes. A reconstructed neuropil is an anatomical compartment, not a single neuron. The upper and lower central-body divisions, bridge and noduli can therefore be distinguished spatially before asking which recorded cell types connect them and what those cells encode.')
add('Dye-filled neurons connect visual input to compass regions','heinze11',['h11_tl','h11_tl3'],'''Heinze and Reppert combined intracellular recordings with dye injection to recover the anatomy of individual compass-related neurons. **Intracellular recording** measures electrical activity from within a cell; subsequent dye filling associates that response with its neuronal processes.||Tangential neurons TL2 and TL3 connected the **lateral triangle**, an input region near the lateral accessory lobe, with distinct layers of the lower central body. Their processes spread across this compass-associated neuropil. The recovered pathways provide candidate stages through which visual information reaches central-complex activity.||The recovered projections and light responses support a circuit-level organization, but morphological polarity does not establish every synaptic connection. The studies did not identify a complete sequence of neurotransmitters, postsynaptic receptors or ion channels through the migratory compass pathway.''','Tangential cells distribute processes across part of the central-body width, whereas columnar cells connect more restricted subdivisions with other central-complex regions. The single-cell fills associate one electrical response with one recovered morphology. A complete synaptic circuit would require direct connectivity evidence in addition to overlapping projection territories.')
add('Compass neurons respond to the polarization axis','heinze11',['h11_f4b','h11_tl'],'''Heinze and Reppert presented polarized 365-nm UV light from above while recording identified compass neurons. The electric-field orientation, called the **E-vector**, rotated through 360° at controlled speeds of 30° or 60° per second.||**Action potentials**, brief electrical spikes, occurred at different rates for different E-vector angles. Preferred and suppressed axes were approximately 90° apart, and the response repeated after 180°, matching the axial symmetry of linear polarization. Intracellular traces preserved voltage and time calibration.||These measurements establish neuronal sensitivity to polarization under controlled stimulation. They do not prove that this cue is necessary for migratory orientation when the sun is available. Behavioral masking and sensory recordings address different causal claims, even when they concern related input structures.''','Polarization describes an axis rather than a directed arrow, so orientations separated by 180° are equivalent. A repeating neuronal response at that interval is consistent with polarization-axis coding. Opponent excitation and suppression can distinguish orthogonal axes, but converting such activity into a geographic direction requires additional context.',True)
add('The same compass circuit represents solar azimuth','heinze11',['h11_f5','h11_tl'],'''**Azimuth** is the angular position of a stimulus around the horizon. Heinze and Reppert moved an unpolarized light spot around the animal at 30° elevation while recording compass-related cells responsive to skylight polarization.||The cells also changed spike rate with spot azimuth. Tests used UV at 365 nm, blue at 470 nm and green at 530 nm; many cells responded to multiple wavelengths with comparable preferred directions rather than opposite spectral preferences.||These responses support convergence of polarization and sun-like positional signals within the compass network. An isolated spot is a controlled proxy for solar direction, rather than the full natural sky. The experiment identifies neuronal coding of cue position, but not a complete transformation from retinal photoreceptors through named chemical synapses to steering muscles.''','The stimulus changes position while its wavelength can be held fixed, separating angular tuning from a response simply to light onset. Testing different wavelengths then asks whether the preferred angle reverses with spectral input. The reported cells lacked the consistent spectral opponency that would require opposite directional effects from different wavelength classes.',True)
add('Dorsal masking separates two converging visual inputs','heinze11 sauman05',['h11_f6','s05_dra'],'''A neuron responsive to both polarization and a light spot could receive those signals through the same receptors or through separate inputs. Heinze and Reppert covered the dorsal visual field and repeated both stimulus tests during intracellular recording.||The shield abolished or strongly reduced the response to zenithal polarized UV, while a green spot moving around the horizon retained its azimuth-dependent response. Sauman and colleagues’ dorsal-rim staining identifies the UV-specialized retinal territory associated with the overhead pathway.||The within-cell comparison supports distinct sensory routes converging on compass neurons. Masking identifies an input dependency, but it does not reveal each intervening synapse. The surviving spot response is consistent with a sun-related pathway that can function when the dorsal polarization signal is unavailable.''','The same recorded cell provides a control for differences between neuronal populations. Loss of one response while another remains also argues against a general failure of the recording or of the cell’s excitability. The shield manipulates visual access; it does not chemically isolate a transmitter or identify the full retinal-to-central pathway.',True)
add('Migratory butterflies have narrower green-light tuning','nguyen21 heinze11',['n21_f3','h11_tl'],'''Nguyen and colleagues compared tangential-neuron recordings from autumn migrants with non-migratory monarchs. They rotated a green 530-nm light spot at 30° elevation and measured the angular range producing elevated spike rates.||**Full width at half maximum** measures a tuning curve’s width at half its peak response. Mean green-light width was approximately 83° in migrants and 118° in non-migrants. Peak rates were broadly similar, so the distinction concerned angular selectivity more than a simple increase in firing.||The comparison associates migratory condition with narrower solar-proxy tuning. Wild migrants and commercially sourced non-migrants differed in origin and rearing, however, so migration state was not isolated experimentally. The measurements do not establish that narrower tuning causes improved migratory accuracy.''','A narrow tuning curve restricts elevated activity to a smaller range of stimulus angles. The source reported mean widths of 82.94° and 118.33° for green light, whereas polarization tuning widths were similar between groups. Similar maximum rates help separate tuning shape from a general difference in responsiveness.',True)
add('Migratory tuning concentrates sensitivity near the front','nguyen21 heinze11',['n21_f4','h11_tl'],'''Nguyen and colleagues analyzed how strongly a change in green-light azimuth altered tangential-neuron activity. This **angular sensitivity** depends on the slope of the tuning response, rather than its maximum firing rate alone.||Migrant recordings concentrated greater sensitivity within approximately 60° of the preferred direction. Non-migrant responses distributed more sensitivity along flanks roughly 60°–180° away. The published analysis used 5° angular bins and compared the pattern with solar geometry expected during migration.||The pattern supports a physiological difference in how nearby directions are discriminated. Its proposed relevance to frontal sun positions is an interpretation based on cue geometry. The study did not manipulate tuning width during free migration or establish a causal gain in arrival accuracy; cohort origin and rearing remained potential confounds.''','A slope measures how much the response changes when stimulus angle changes. A high peak can coexist with low angular sensitivity if nearby angles produce similar activity. The source’s geographical comparison relates recorded tuning to potential sun positions; those map-related predictions are distinct from direct measurements of a butterfly’s route.',False,2.6)
add('Spring remigrants reverse direction but retain compensation','guerra13',['g13_f1bc'],'''Guerra and Reppert measured freely released fall migrants and spring remigrants, butterflies leaving the overwintering phase. Fall animals disappeared toward a mean bearing of 209°, whereas spring animals selected approximately 45°, toward the northeast.||Spring migrants entrained to a 6-h-delayed light cycle instead departed near 142°, a clockwise shift of about 97°. The opposite seasonal direction therefore retained the response expected from a time-compensated sun compass.||The comparison supports a change in the selected migratory direction while preserving the timing-based orientation mechanism. A **disappearance bearing** is the final observed direction after release, rather than a complete travel route. Seasonal reversal does not establish a different clock tissue or reveal how the preferred direction is represented in the nervous system.''','The spring clock shift was imposed before release, while the geographic sky was available during the test. Its effect separates a seasonally selected heading from loss of time compensation. A disappearance bearing can establish initial travel direction, but it does not verify that the same direction was maintained over the entire return journey.')
add('Cold exposure triggers northward orientation','guerra13',['g13_f3bc'],'''Guerra and Reppert exposed fall migrants to 24 days resembling the overwintering thermal environment: 11°C during the light phase and 4°C during darkness. One treatment gradually increased day length; another maintained a constant 12-h light:12-h dark cycle.||Both cold-treated groups subsequently oriented near 358°, approximately north, after warming sufficiently for flight. Warm-housed comparison animals retained a southwest direction near 227°. Northward orientation therefore did not require the treatment’s changing photoperiod, the daily duration of light.||The intervention supports cold exposure as a trigger for seasonal compass reversal under these conditions. It does not identify the temperature-sensitive cells, molecular sensor or central switch. The 24-day treatment establishes an effective exposure, rather than the minimum cold duration required for reversal.''','The cold manipulation occurred during housing, and testing followed warming above approximately 15°C to permit flight. The direction change is therefore distinct from an immediate motor effect of trying to fly at 4°C. Holding photoperiod constant in one cold treatment separates the thermal effect from increasing day length.')
add('Age and calendar date do not replace the cold trigger','guerra13',['g13_f4'],'''Fall migrants kept warm for more than four months still selected a mean southward bearing near 166° when tested in March. Their housing alternated approximately 21°C by day and 12°C by night rather than imposing the colder overwintering treatment.||The animals had reached the calendar period associated with spring migration. Some females also contained mature eggs, so reproductive maturation and prolonged survival could occur without the experimental northward reversal. The recorded direction remained characteristic of aged fall migrants.||The comparison supports an environmental thermal contribution rather than a switch produced by elapsed time alone. It does not imply that age, reproduction or photoperiod never influence migration. Their insufficiency applies to the tested housing conditions and measured orientation, while the mechanism sensing the effective cold exposure remains unidentified.''','A calendar date is not a controlled internal signal available to the butterfly. Warm housing allowed time to pass without the tested cold experience. Continued southward orientation despite advanced age separates that experience from chronological aging, while the egg observations address one potential association with reproductive state.')
add('Loss of CRY1 weakens behavioral and molecular rhythms','iiams24',['i24_f1','i24_f3'],'''Iiams and colleagues tested monarchs lacking functional CRY1, comparing them with wild-type butterflies. After 12-h light:12-h dark entrainment at 25°C, mutant emergence rhythms weakened in constant darkness. Brain clock-gene rhythms were also disrupted in adults re-entrained to cycling light.||Adult flight-mill tests measured revolutions as distance traveled per hour during a 15-h light:9-h dark cycle at 21°C. Wild-type activity concentrated around midday; mutants distributed activity more broadly after a morning increase. Daily temperature cycles could restore some rhythmic outputs.||The results connect CRY1 function to robust timing and daytime flight organization. Flight activity is not migratory compass heading, and flight was not tested as a free-running rhythm in darkness. Neither altered activity nor emergence alone establishes that the same mutation abolishes time-compensated migration.''','A flight mill converts repeated movement around a fixed axis into an activity measure, rather than recording a geographic destination. Temperature cycles alternating 15°C and 25°C provided an additional entraining signal in the source experiments. Those daily cycles should not be equated with the multiweek cold exposure that changes seasonal compass direction.',True)
add('Goal coding differs from coding the current heading','beetz23goal heinze11',['b23_f3bf','h11_f2'],'''Beetz and colleagues recorded central-complex neurons while non-migratory monarchs oriented toward a virtual sun. A **heading signal** represents current orientation; a **goal-direction signal** represents the direction the animal attempts to maintain.||Moving the sun-like stimulus altered heading-related tuning, while candidate goal cells retained their association with the chosen target. Aversive conditioning using neck stimulation changed the selected goal by about 130° on average; goal-related neural tuning changed with that preference rather than simply following a solar displacement.||The dissociation supports distinct representations of present and desired direction. Controlled stimulation and stable recorded waveforms addressed alternative explanations. These were arbitrary laboratory goals in non-migrants: the experiment does not establish how antennal clocks set an autumn goal or how cold exposure reverses it.''','Aversive conditioning associates a heading sector with an unpleasant stimulus, allowing the preferred direction to change without treating that change as a natural seasonal migration. Putative goal cells followed the conditioned preference, whereas heading cells followed the animal’s current orientation. A cellular representation is supported, but the complete synaptic circuit combining time, goal and motor output remains unresolved.',True)

assert len(S)==44,len(S)
for i,s in enumerate(S,2):
 assert len(s['title'])<=62,(i,len(s['title']),s['title'])
 assert 3<=len(s['body'])<=5
 assert 90<=len(' '.join(s['body']).split())<=170,(i,len(' '.join(s['body']).split()))
 assert not s['title'].endswith('.')
TK=[
 ('Time compensation:', 'Advancing and delaying the entraining light cycle rotate migratory headings in opposite directions. A compass bearing is distinct from a geographic map or a complete migration route.'),
 ('Antennal clocks:', 'Either light-accessible antenna can support compensation. Conflicting antennal timing disrupts the shared bearing, and removing the conflicting antenna restores orientation.'),
 ('Molecular feedback:', 'CRY1 supplies light-sensitive clock input, while CRY2 represses clock-controlled transcription. Protein interactions and timed nuclear localization contribute to the feedback cycle.'),
 ('Converging visual cues:', 'Central-complex neurons encode polarization and sun-like azimuth. Neural sensitivity to polarization does not establish its necessity for migration when the sun is available.'),
 ('Seasonal reversal:', 'Effective multiweek cold exposure induces northward orientation while time compensation remains available. Warm aging alone did not produce reversal in the tested migrants.'),
 ('Representations and limits:', 'Current heading and desired direction have distinct neuronal correlates. A complete causal pathway from antennal timing through compass computation to steering remains unidentified.')]
keys=['frost02','zhu08','merlin09','guerra12','heinze11','guerra13','beetz23goal']
SPEC={'lecture':30,'theme':'flint-soft-blue','content_slides':44,'title_image':WEB,'title_refs':[sources['frost02']['reference']],'slides':S,'takeaways':{'items':[{'lead':lead,'text':txt} for lead,txt in TK],'cite':'Mouritsen & Frost (2002); Merlin et al. (2009); Guerra et al. (2012, 2013); Beetz et al. (2023)','refs':['References:']+[sources[x]['reference'] for x in keys]}}
(B/'lecture.json').write_text(json.dumps(SPEC,indent=2,ensure_ascii=False)+'\n')
print('Wrote 44 content slides, with original article images on all 44, and six exam takeaways.')
