"""Lecture 10 scientific content; figures are unchanged crops from six supplied PDFs."""
import json
from pathlib import Path
BASE=Path(__file__).resolve().parent
ROOT=BASE.parents[1]
R={
'E70':('Ewert (1970)','Ewert JP (1970). Neural mechanisms of prey-catching and avoidance behavior in the toad (Bufo bufo L.). Brain, Behavior and Evolution 3(1–4):36–56. https://doi.org/10.1159/000125462'),
'I73':('Ingle (1973)','Ingle D (1973). Disinhibition of tectal neurons by pretectal lesions in the frog. Science 180(4084):422–424. https://doi.org/10.1126/science.180.4084.422'),
'L83':('Laming & Ewert (1983)','Laming PR, Ewert JP (1983). The effects of pretectal lesions on neuronal, sustained potential shift and electroencephalographic responses of the toad tectum to presentation of a visual stimulus. Comparative Biochemistry and Physiology Part A: Physiology 76(2):247–252. https://doi.org/10.1016/0300-9629(83)90322-5'),
'P95':('Schwippert et al. (1995)','Schwippert WW, Beneke TW, Ewert JP (1995). Pretecto-tectal influences. II. How retinal and pretectal inputs to the toad’s superficial tectum interact: a study of electrically evoked field potentials. Journal of Comparative Physiology A 176(2):181–192. https://doi.org/10.1007/BF00239921'),
'S95':('Schwippert & Ewert (1995)','Schwippert WW, Ewert JP (1995). Effect of neuropeptide-Y on tectal field potentials in the toad. Brain Research 669(1):150–152. https://doi.org/10.1016/0006-8993(94)01260-O'),
'W07':('McConville & Laming (2007)','McConville J, Laming PR (2007). DC electrical stimulation of the pretectal thalamus and its effects on the feeding behavior of the toad (Bufo bufo). Developmental Neurobiology 67(7):875–883. https://doi.org/10.1002/dneu.20390')}
F={}
def f(name,key,number,desc):
 F[name]={'path':'figures/'+name+'.png','caption':f'{R[key][0]}, Fig. {number}. {desc}','kind':'article','source_url':R[key][1].split()[-1]}
f('e70_f1','E70','1(A–B)','Moving-object chamber and timed orienting responses.')
f('e70_f2','E70','2(a–b)','Disc diameter in degrees separates orienting and avoidance.')
f('e70_f3a','E70','3(Aa–Ab)','Intact toads respond differently to rectangle elongation along and across motion.')
f('e70_f3b','E70','3(Ba–Bb)','Lesioned toads lose the usual inhibition by vertical elongation.')
f('e70_f4','E70','4(a–b)','Paired moving objects inhibit orienting most strongly at 8° separation.')
f('e70_f5ab','E70','5(A–B)','Orienting declines with repetition and recovers after a pause.')
f('e70_f5c','E70','5(Ca–Cb)','Repeated habituation series suppress intact responses more than lesioned responses.')
f('e70_f6','E70','6(a–e)','Tectal stimulation sites and directed turning, snapping and gulping.')
f('e70_f7','E70','7(d–f)','Catching and avoidance stimulation sites.')
f('e70_f8','E70','8(a–c)','Prolonged stimulation changes ducking to mixed responses and snapping.')
f('e70_f9','E70','9(a–d)','Disinhibited toads pursue large and inappropriate objects.')
f('e70_f10','E70','10(A–D)','Lesion maps and visual fields.')
f('e70_f11','E70','11','Paired-object summation after lesions, with separation in degrees.')
f('i73_f1','I73','1','A lesion-side tectal unit fires persistently to a moving and stopped object.')
f('i73_f2','I73','2','Habituation-ratio distributions in retinal fibers and tectal cells.')
f('l83_f1','L83','1','Recording preparation.')
f('l83_f2','L83','2(A–B)','Unit, EEG and slow potentials before and after lesion.')
f('l83_f3','L83','3(A–C)','Lesion sites (1 mm).')
f('p95_f1','P95','1(A–B)','Surface recordings after tubocurarine and recordings at successive tectal depths.')
f('p95_f2','P95','2','Optic-nerve stimulation and tectal recording grid with original 1 mm calibration.')
f('p95_f3','P95','3(A–B)','Stimulus strength alters components of optic-nerve-evoked tectal field potentials.')
f('p95_f4','P95','4','Ipsilateral pretectal stimulation and regional tectal field responses.')
f('p95_hist','P95','4 (histology)','Marked Lpd site (250 μm).')
f('p95_f5','P95','5','Contralateral pretectal stimulation evokes a predominantly positive tectal wave.')
f('p95_f6','P95','6','Paired pretectal and optic-nerve stimuli separated by 10–100 ms.')
f('p95_f7','P95','7(A–B)','Delay effects at two input strengths; rows c are the authors’ theoretical summation comparison.')
f('p95_f8','P95','8(A–B)','Visual and pretectal conditioning attenuate optic-nerve-evoked tectal responses.')
f('p95_f9','P95','9(A–B)','Repetition and paired optic-nerve controls test an adaptation explanation.')
f('s95_f1','S95','1(A–B)','Pretectal stimulation arrangement and delay-dependent suppression of the negative wave.')
f('s95_f1a','S95','1(A)','Stimulation and recording sites.')
f('s95_f2','S95','2','NPY application reduces the negative tectal wave and partial recovery follows removal.')
f('w07_f1','W07','1','Original colored behavioral chamber for visual and electrical stimulation.')
f('w07_f3','W07','3','Lpd electrodes.')
f('w07_f4','W07','4','Arousal remains relatively constant across the DC current range.')
f('w07_f5','W07','5','Approach responses generally decline as DC current increases.')
f('w07_f6','W07','6','Retreat occurs at 100 and 300 μA, with both directions of visual motion.')
f('w07_f7','W07','7','Crouch responses emerge at high DC currents.')
S=[]
def slide(title,keys,figs,body,extra,side=False):
 keys=list(dict.fromkeys(keys+[n.split('_')[0].upper() for n in figs]))
 b=body.split('\n\n');assert len(b)==3,(title,len(b))
 d={'title':title,'body':b,'cite':'; '.join(R[k][0] for k in keys),'refs':[R[k][1] for k in keys],
 'transcript':b+[extra], 'layout':'figure-right' if len(figs)==1 else 'figures-right','figure_width':5.8}
 if len(figs)==1:d['figure']=F[figs[0]]
 else:
  assert len(figs)==2
  d['figures']=[F[n] for n in figs]
  if side:d.update(figure_arrangement='side-by-side',primary_figure_width=3.6)
  else:d['primary_figure_height']=2.8
 if len(figs)==2 and (figs[1]=='l83_f3' or title in ['Prolonged pretectal stimulation reverses behavior','Pretectal lesions release inappropriate prey capture']):
  d.update(figure_arrangement='side-by-side',primary_figure_width=3.3 if figs[1]=='l83_f3' else 2.5)
 if 'i73_' in ' '.join(figs):
  d['transcript'].append('The anatomical comparison from McConville and Laming locates homologous regions in a common toad; it is not an anatomical reconstruction of the frog operated on by Ingle.')
 if title=='Lesion effects follow sectors of visual space':
  d['transcript'].append('Large rostral thalamic lesions did not produce the same syndrome, providing a location control. The caudal lesion effect therefore cannot be explained simply by any brain operation increasing snapping.')
 if title=='Newness cells respond selectively to recent motion':
  d['transcript'].append('Ingle selected frogs with disinhibited pursuit after knife cuts or suction near the pretectal region, with some operations also interrupting commissural connections. The result applies to that selected syndrome, rather than to every pretectal operation.')
 if title=='Field polarity depends on tectal recording depth':
  d['transcript'].append('The same figure contains tubocurarine controls: optic-nerve responses remained qualitatively similar after immobilization. The control addresses the preparation, not the identity of a physiological inhibitory transmitter.')
 if title=='Stimulus strength changes which waves are suppressed':
  d['transcript'].append('Rows c in the original figure are the authors’ theoretical summation comparison, whereas rows a and b contain experimental response comparisons. The theoretical rows are not additional measured biological responses.')
 if title=='DC stimulation tests avoidance in behaving toads':
  d['transcript'].append('DC applications lasted 10 seconds; visual presentation began about 2 seconds after current onset, and trials were separated by 5 minutes. Most combinations were randomized, but zero current was always first and 300 μA last, leaving an order limitation at the endpoints.')
 if len(figs)==2 and figs[1] in ['l83_f3','l83_f1','e70_f10']:
  d.update(figure_arrangement='side-by-side',primary_figure_width=4.0,figure_width=6.0)
 if len(figs)==2 and figs[1]=='s95_f1a':
  d['primary_figure_height']=2.9
 if title=='Habituation changes after pretectal damage':
  d.update(figure_arrangement='side-by-side',primary_figure_width=3.3,figure_width=6.0)
 S.append(d)
slide('Large moving objects recruit defensive behavior',['E70'],['e70_f2'],'''**Predator avoidance** is a movement that reduces exposure to a threatening object. In common toads, _Bufo bufo_, large moving objects evoke ducking, turning away or jumping, whereas small objects often evoke orienting followed by prey capture.

Ewert varied the angular diameter of black discs moving at 30°/s against a white background. **Angular size** is the angle an object occupies at the eye. Orienting was strongest for discs approximately 4–8° across and nearly absent at 20°; avoidance became prominent above 30° and was optimal around 50°.

The controlled objects separate stimulus size from actual predator identity. These responses establish a size-dependent behavioral distinction; they do not imply that every large object is recognized as a particular predator.''','The discs provide controlled visual cues without the odor, texture or unpredictable movements of a living animal. A laboratory avoidance response measures the animal’s action toward that cue; predator recognition in a natural encounter contains additional information.')
slide('The same visual world supports approach and escape',['E70'],['e70_f1'],'''**Prey capture** includes orienting, following, snapping and swallowing. Ewert counted turns while a moving object circled a toad inside a glass cylinder; the timed records distinguish persistent orientation from occasional responses without requiring the animal to catch real prey.

A small moving object normally activates approach-related behavior. A large object can instead cause the toad to lower its body or move away. These alternatives depend on visual dimensions and behavioral state, rather than on the presence or absence of motion alone.

Electrical stimulation near the boundary between catching and avoidance regions could evoke both kinds of movement in rapid succession or together. The muscles can therefore execute these responses without an absolute peripheral incompatibility; normal separation requires central regulation.''','Turning counts quantify one component of the feeding sequence. Snapping and swallowing are distinct motor acts, so an increase in orienting should not be equated with successful feeding. The mixed responses produced by electrical stimulation concern motor compatibility, not normal simultaneous pursuit and escape.')
slide('Elongation across motion suppresses prey orientation',['E70'],['e70_f3a'],'''A **worm-like stimulus** is a narrow rectangle moving parallel to its long axis. An **antiworm stimulus** has the same elongated form but moves perpendicular to that axis. These terms describe stimulus geometry rather than real species of prey.

At 30°/s, Ewert held one rectangle dimension at 2° while changing the other. Increasing length parallel to motion increased orienting toward a maximum at approximately 16–32°. Increasing width perpendicular to motion reduced the response. A square became more effective up to about 8° before larger squares lost prey value.

The opposite effects of elongation require a relation between object dimensions and movement direction. Area alone cannot explain intact behavior, and the behavioral curves do not themselves identify the inhibitory neurons.''','The same rectangular dimensions can have different behavioral effects after the movement direction is changed. The manipulation tests configuration selectivity: sensitivity to how parts of the stimulus are arranged relative to motion. The original curves distinguish that selectivity from a simple preference for more dark area.')
slide('Neighboring objects can inhibit orienting',['E70'],['e70_f4'],'''**Spatial interaction** means that the response to one object depends on another object elsewhere in the visual field. Ewert compared orientation toward a single moving rectangle with orientation when a second rectangle moved alongside it, using the same 30°/s speed and high contrast.

For paired 2° × 16° objects, suppression was greatest at approximately 8° separation. Objects farther apart produced less inhibition. Adding a second potential prey item therefore did not necessarily add a second independent orienting response.

The manipulation supplies a behavioral constraint on visual processing: nearby signals interact before the final movement is selected. It does not localize the interaction exclusively to retina, pretectum or tectum without a separate intervention.''','The single-object condition provides the comparison needed to distinguish inhibition from simple failure to detect either object. Separation changes while the object dimensions are retained. The spatial dependence concerns response selection, and it does not establish a synapse between two identified cells.')
slide('Avoidance sites lie rostral to the tectum',['E70'],['e70_f7'],'''The **optic tectum** is the midbrain visual structure involved in directing movements toward visual targets. The **pretectum** lies immediately rostral to it, near the caudal diencephalon. Ewert mapped responses by stimulating localized sites in freely moving toads.

Stimulation in the pretectal and adjacent caudal dorsal thalamic regions evoked ducking, jumping or turning away from the opposite side. The published site maps distinguish these locations from tectal sites associated with catching movements and from boundary sites producing mixed responses.

Electrical stimulation establishes that activity introduced near these regions can recruit defensive motor behavior. Current can activate axons as well as nearby neurons, so a behavioral stimulation map does not identify a single specialized predator neuron.''','Rostral means toward the front of the brain, while caudal means toward the back. The anatomical names used in these classic papers partly overlap, which is why the original stimulation and lesion maps are more precise than assigning every effect to a modern nucleus label.')
slide('Tectal stimulation directs distinct catching movements',['E70'],['e70_f6'],'''Ewert implanted electrodes in the optic tectum and applied pulse trains to freely moving toads. Appropriate stimulation could evoke turning, snapping and gulping without a prey object passing through the corresponding part of the visual field.

Different tectal locations directed orienting or snapping toward different sectors of the opposite visual field. This **retinotopic organization** preserves spatial relationships from the retina, the light-sensitive neural tissue of the eye, in a central map used to direct movement.

The stimulation bypasses normal stimulus classification but preserves a relation between brain location and movement direction. It supports a tectal contribution to visuomotor output; it does not establish that the tectum operates independently of pretectal inhibition or other brain regions.''','The spatial map concerns where an action is directed, while stimulus selectivity concerns which visual objects release that action. A stimulation experiment can activate an output location without testing whether the same site would normally accept a large nonprey stimulus.')
slide('Prolonged pretectal stimulation reverses behavior',['E70'],['e70_f8','e70_f7'],'''Ewert prolonged stimulation of the pretectal and caudal thalamic region at 60 Hz. The initial effect was an avoidance response, but continued stimulation raised the avoidance threshold and eventually produced unresponsiveness to the stimulation.

During a later phase, toads oriented and snapped toward large moving objects that they would ordinarily avoid. The response progressed from ducking through mixed orienting–avoidance movements to catching movements. After approximately 10–30 minutes of recovery, appropriate avoidance could return.

This reversible sequence is consistent with temporary loss of a restraining influence on prey capture. It does not establish whether the loss results from adaptation, transmitter depletion, altered ionic conditions or another consequence of sustained electrical activation.''','A pulse frequency of 60 Hz means sixty stimulation pulses per second, not a measured firing rate of every pretectal cell. The recovery distinguishes the prolonged-stimulation effect from a permanently destroyed motor pathway, but it does not supply the cellular cause of the changing response.')
slide('Pretectal lesions release inappropriate prey capture',['E70'],['e70_f9','e70_f10'],'''A **lesion** is tissue damage introduced to test the contribution of a brain region or connection. Ewert used knife cuts and high-frequency coagulation in pretectal and caudal dorsal thalamic areas that normally participate in avoidance-related regulation.

After these lesions, toads snapped at their own legs, another toad, an experimenter’s hand or a moving shoe box. **Disinhibition** is increased activity or behavior after a restraining influence is removed. The abnormal catching could persist from 24 hours to several weeks, depending on lesion location.

The animals retained the motor capacity to orient and snap but lost normal restrictions on suitable targets. Because the lesions affected tissue and passing connections, they establish a regional contribution rather than the necessity of one transmitter or cell class.''','An animal that still snaps is not simply blind or paralyzed. Its visually released behavior has changed in selectivity. The variable duration and lesion extent also prevent treating every operated animal as a selective and identical removal of a single inhibitory nucleus.')
slide('Lesion effects follow sectors of visual space',['E70'],['e70_f10'],'''Ewert reconstructed the damaged tissue and compared lesion location with the visual-field region in which catching became disinhibited. A unilateral pretectal or caudal thalamic lesion generally released prey-catching through the opposite eye; bilateral damage affected both sides.

Small lesions could change orienting in restricted visual sectors. When damage extended into dorsal tectal tissue, responses could disappear in the upper visual field while remaining disinhibited in the lower field. Losing visual responsiveness and releasing an inappropriate response are therefore distinguishable outcomes.

The spatial correspondence supports organized pretectal–tectal regulation rather than a completely uniform increase in movement. Extensive lesions nevertheless combine loss of inputs, local neurons and connections, limiting assignment of the effect to an isolated synapse.''','Contralateral refers to the side opposite a lesion; ipsilateral refers to the same side. A visual-field sector with no response after tectal damage cannot be counted as improved selectivity. The lesion reconstructions connect the behavioral deficit to damaged tissue without claiming microscopic selectivity.')
slide('Lesions remove the effect of vertical elongation',['E70'],['e70_f3b','e70_f10'],'''Ewert repeated the rectangle-dimension experiment after pretectal and caudal thalamic lesions. In intact toads, elongating a rectangle perpendicular to its movement normally reduced prey-oriented turning, despite increasing the amount of visible object.

After the effective lesions, orienting instead increased with enlargement along either axis. Rectangles and squares no longer produced the same configuration-dependent reduction. The measured stimulus dimensions and 30°/s movement were retained, separating the lesion effect from a new set of visual objects.

The lost distinction supports a contribution of the damaged pathway to rejecting unsuitable configurations. It does not mean that the retina has ceased detecting motion or that every surviving tectal neuron has become equally responsive to all stimuli.''','The comparison is within the original stimulus family: horizontal, vertical and jointly enlarged dimensions. Increased response after damage is meaningful because the intact condition had a selective reduction for enlargement across motion, rather than a general failure to respond to large objects.')
slide('Paired objects sum after the restraint is removed',['E70'],['e70_f11','e70_f10'],'''Ewert tested pairs of moving 2° × 16° rectangles after effective caudal thalamic and pretectal lesions. The object dimensions and speed matched the earlier intact preparation, allowing the distance-dependent interaction to be compared directly.

The normal reduction around 8° separation was absent. At separations of approximately 1–8°, the pair could produce more orienting than one object alone. **Summation** describes that combined increase, without requiring a particular mathematical rule for addition of neuronal signals.

The lesion changed how multiple visible targets competed for behavior. The result supports a central inhibitory contribution to spatial filtering, but it does not determine whether the relevant normal interaction is carried by a direct pretectal projection or by an intervening network.''','The paired-object result differs from the size experiment because two spatially distinct targets are present. A common lesion can remove both configuration-dependent suppression and nearby-object suppression, but similar behavioral effects do not prove that the underlying neuronal operations are identical.')
slide('Habituation changes after pretectal damage',['E70'],['e70_f5ab','e70_f5c'],'''**Habituation** is a reduction in response during repeated presentations of a stimulus. In Ewert’s intact toads, orienting declined as a standard moving prey object was presented repeatedly. A pause allowed partial recovery, and repeated habituation series further reduced subsequent orienting.

After caudal thalamic and pretectal lesions, recovery could occur within approximately 5–10 minutes and the suppression accumulated much less across successive series. The same visual object remained capable of releasing movement after the normal persistent restraint was weakened.

The behavioral change connects the lesioned region to the time-dependent regulation of prey-catching. Habituation measured as turning behavior does not by itself distinguish retinal adaptation, tectal response changes, motivational changes and pretectal inhibition.''','Response reduction must be measured against a prior response to the same kind of stimulus. Recovery after a pause distinguishes a reversible change from permanent loss of vision or movement, but multiple central and peripheral processes can contribute to a reversible behavioral decrement.')
slide('Forebrain removal can silence catching indirectly',['E70'],['w07_f3'],'''The **telencephalon**, the anterior division of the forebrain, can regulate visually released behavior without supplying the entire catching motor sequence. Ewert removed the forebrain while sparing the thalamus and observed a pronounced reduction in prey-oriented responses.

Bilateral removal left animals unresponsive to prey dummies while avoidance increased. Additional damage to the pretectal and caudal thalamic region could restore disinhibited catching. Thus a missing forebrain did not necessarily remove the downstream capacity to execute prey-related movements.

The sequential interventions support regulation through an inhibitory intermediate, but the full lesion sequence also indicated additional forebrain influences. These regional operations cannot establish a complete two-node circuit or identify the transmitter linking forebrain activity to pretectal restraint.''','Removing a structure can suppress a behavior by releasing inhibition elsewhere, rather than by destroying the behavior’s output machinery. Recovery after a second lesion is especially informative about that possibility, although broad lesions leave the exact route of the regulation unresolved.')
slide('Newness cells respond selectively to recent motion',['I73'],['i73_f1','w07_f3'],'''Ingle recorded **newness cells**, a functional class of tectal neurons whose responses normally diminish rapidly when an object repeatedly traverses the same visual region. In intact frogs, these cells commonly had receptive fields about 15–20° across.

A **receptive field** is the region of sensory space in which a stimulus changes a neuron’s activity. Normal newness cells could cease responding after one or two passages of a small object. This property differs from the repeated contrast responses of retinal class 3 fibers.

Ingle compared these responses after pretectal lesions associated with disinhibited pursuit. The category describes measured visual response properties, not a molecularly defined cell type or a demonstrated neurotransmitter identity shared by every cell.''','A receptive field is defined experimentally by moving a stimulus through visual space while recording the cell. A rapidly habituating tectal unit and a retinal axon can both respond to a small dark object, so object preference alone is insufficient to identify the recording.')
slide('Disinhibited tectal cells keep firing after motion stops',['I73'],['i73_f1','w07_f3'],'''Ingle presented a black square about 4° across moving at approximately 10°/s on a screen 20 cm from the frog. In animals with behaviorally effective pretectal lesions, tectal units could produce prolonged activity unlike normal rapidly habituating newness cells.

A spot that stopped within the receptive field could evoke a discharge lasting approximately 5–10 seconds. In some cells, the highest firing occurred 2–3 seconds after the stimulus stopped, rather than immediately at motion onset or termination.

The persistence separates response regulation from simple tracking of instantaneous motion. The lesion results support a normal pretectal restraint on tectal responsiveness, but they do not identify whether the long discharge is generated by intrinsic currents or recurrent network activity.''','A delayed peak after motion stops cannot be interpreted as a precise neural report of the object’s current speed. Ingle also observed exceptionally intense, seizure-like activity in some preparations. Such pathological responses are evidence of disrupted regulation and should not be described as normal predator coding.')
slide('Pretectal damage can enlarge a tectal receptive field',['I73'],['i73_f1','w07_f3'],'''After behaviorally effective pretectal lesions, Ingle recorded tectal receptive fields approximately 30° across or larger, compared with the usual 15–20° range of normal newness cells. Some recorded fields enlarged from about 15° to 30° during the observation.

The lesion-side example contains a broad field with a particularly excitable zone, and movement of a small object could evoke activity that persisted when motion stopped. Other cells remained spatially responsive but discharged more strongly or for longer than normal.

Receptive-field enlargement is consistent with removal of inhibition that normally limits effective visual input. Extracellular spike recordings, which detect neuronal action potentials outside the cell, do not establish the membrane conductance or circuit connection responsible for the enlargement.''','A larger functional receptive field need not mean that new anatomical retinal connections appeared during the experiment. Previously ineffective inputs may become capable of producing spikes after inhibition is lost. The recording tests responsiveness rather than directly counting synapses.')
slide('The lesion alters tectal habituation more than retinal input',['I73'],['i73_f2','w07_f3'],'''Ingle quantified recovery after a 10-second pause relative to spike activity during a 60-second comparison interval. The **habituation ratio** expresses how much responsiveness remains after repeated stimulation and a short recovery period.

Retinal class 1 and class 2 fibers generally had ratios between 25% and 80%. Normal tectal newness cells were below 25%, and most were below 10%. After pretectal lesions, tectal ratios shifted toward the retinal range, whereas retinal fibers did not acquire a corresponding lesion-dependent change.

The retinal comparison argues against a purely peripheral explanation for the loss of tectal habituation. It supports central regulation of responsiveness, while leaving open the contributions of different pretectal connections and local tectal inhibitory circuitry.''','The ratio is a measurement defined by the original experiment, not a direct measure of an inhibitory synaptic current. Retinal fibers retain repeated responsiveness in both conditions, while the normal additional suppression at the tectal level is weakened after the lesion.')
slide('A same-unit experiment links lesion and visual response',['L83'],['l83_f2','l83_f1'],'''Laming and Ewert recorded tectal visual units while monitoring slower electrical signals in the same toad. Their **T5(2)** designation identifies units with prey-related configuration sensitivity; it is a physiological classification rather than a genetically labeled population.

They compared a 1.8° × 15° worm-like rectangle, a 15° × 1.8° antiworm and a 15° square moving at 22°/s. A knife cut disrupted ipsilateral pretectal and dorsal thalamic connections while the electrode remained in place, and recordings resumed after approximately 15–30 minutes.

Maintaining the unit provides a stronger comparison than replacing it with an unrelated post-lesion cell. Only preparations retaining suitable recordings support that comparison, and the knife cut still affects a regional set of connections.''','Holding the recording position reduces uncertainty about whether a changed response is due to sampling a different unit. The stimulus dimensions separate configuration from mere visibility, while the post-cut waiting interval reduces immediate recording disturbance without making the lesion anatomically selective.')
slide('Spikes, EEG and slow potentials measure different activity',['L83'],['l83_f2','l83_f3'],'''A **spike recording** detects action potentials from a unit, whereas an **electroencephalogram**, or EEG, records aggregate electrical activity over a broader neuronal population. Laming and Ewert also measured a **sustained potential shift**, a slower change in extracellular voltage associated with visual stimulation.

Their simultaneous traces compare tectal spikes, tectal EEG bands and slow potentials before and after a pretectal lesion. The EEG included a 14–18 Hz band and a wider 0–50 Hz band, while slow shifts were recorded separately from the rapid unit response.

These signals depend on different spatial and temporal properties of electrical activity. A stronger single-unit discharge can coexist with a smaller population field; field amplitude cannot be read as the firing rate of every neuron in the region.''','Extracellular voltage reflects currents distributed through tissue and depends on their geometry and coordination. Spikes count discrete events from a recorded unit. The simultaneous measurements therefore test related but distinct consequences of the same lesion and visual stimulus.')
slide('Immobilized toads fire more strongly after the lesion',['L83'],['l83_f2','l83_f3'],'''In immobilized toads, Laming and Ewert compared responses of maintained T5(2) units before and after disruption of pretectal and dorsal thalamic connections. A worm-like rectangle moved at 22°/s through the unit’s visual receptive field.

The reported response frequency increased from approximately 16.1 to 39.4 spikes/s, and the response duration increased from approximately 0.96 to 1.54 seconds. Some fields expanded from approximately 20–25° to 40–60°. The lesion therefore changed both the strength and spatial extent of effective visual input.

These measurements support removal of a restraining influence on tectal responsiveness. Because the toad was immobilized, the increases are not simply the consequence of additional prey-catching movements during the recording, but the precise inhibitory connection remains unresolved.''','Immobilization permits recording without the large movement artifacts of a freely moving animal. It also changes the behavioral preparation. Numerical changes obtained in that condition should not automatically be transferred to the firing rates of neurons during unrestricted prey capture.')
slide('Population potentials can shrink while spikes increase',['L83'],['l83_f2','l83_f3'],'''In the same immobilized preparations, pretectal lesions increased the frequency and duration of tectal unit responses but reduced the amplitude of sustained potential shifts and EEG responses. The measurements diverged despite being collected during the same kind of visual stimulation.

An extracellular population field depends on the location, timing and orientation of contributing currents. It is therefore possible for a recorded unit to produce more spikes while the aggregate voltage change becomes smaller. The wider 0–50 Hz EEG and the 14–18 Hz band provide population measurements rather than unit counts.

The experiment rejects a simple equivalence between field amplitude and neuronal excitation. It does not independently establish which changes in synchrony, current geometry or ionic redistribution caused the reduced population signals.''','A smaller field does not establish that every tectal neuron is less active. Conversely, the increased activity of the maintained unit does not establish that the entire population is more active in a coordinated way. The cellular and population responses must remain separate observations.')
slide('Freely moving toads mainly prolong the response',['L83'],['l83_f2','l83_f3'],'''Laming and Ewert also used chronically mounted electrodes in freely moving toads. In animals whose lesions produced disinhibited prey-catching, they compared responses to worm-like and antiworm objects while behavior was available rather than prevented.

Response duration increased from approximately 0.41 to 1.24 seconds for the worm-like stimulus and from approximately 0.51 to 1.51 seconds for the antiworm. In contrast to the immobilized preparation, the frequency of unit firing was not appreciably increased.

The common lesion effect was a longer period of responsiveness, while firing-rate effects depended on preparation. Sustained activity can therefore contribute to inappropriate catching without requiring the same increase in spikes/s reported in immobilized animals; correlation with movement alone does not prove a unit commands the response.''','A longer response means that spikes remain available to downstream circuits for more time, even if the rate within that response is unchanged. The freely moving and immobilized conditions test different states of the animal, so their results are complementary rather than interchangeable.')
slide('Anti-worm responses lose their normal restriction',['L83'],['l83_f2','l83_f3'],'''In the freely moving toads that became disinhibited, the tectal units lost their previous distinction between worm-like and antiworm configurations. Both 1.8° × 15° and 15° × 1.8° objects could evoke extended activity after the lesion.

The antiworm response duration increased to approximately 1.51 seconds, and the frequency of tectal EEG activity associated with antiworm presentation rose from approximately 15.2 to 18.8 Hz. Toads could orient or snap toward configurations that previously failed to release suitable prey-catching.

The neuronal and behavioral changes support a contribution of pretectal connections to selective response restriction. An increased EEG frequency is a population rhythm measurement, distinct from spikes/s, and it does not identify a particular inhibitory transmitter or direct pretectal synapse.''','The paper compared the two object configurations in a preparation where movements were recorded. The loss of discrimination is not equivalent to an increase in every measured electrical signal. The duration, EEG rhythm and amplitude have separate meanings and do not supply a complete causal chain on their own.')
slide('More firing need not mean lost discrimination',['L83'],['l83_f3'],'''Laming and Ewert reconstructed lesions from transverse sections and compared their positions with changes in visual responses. Lesions producing disinhibited catching lay near the relevant pretectal and dorsal thalamic connections, while other cuts could increase unit activity without the same behavioral syndrome.

More extreme lateral cuts increased firing by approximately 20–350% in some recordings but did not remove configuration selectivity. In freely moving animals, lesions closer to the midline could fail to cause the same motor disinhibition, despite altering the recording.

**Excitability**, the tendency to produce spikes, and **selectivity**, the distinction between stimulus configurations, are different properties. A regional increase in responsiveness does not establish that a neuron has lost the filtering necessary to reject nonprey.''','The anatomical comparison prevents reducing the experiment to a single statement that lesions increase activity. Different cuts can affect the response strength or the stimulus distinction differently. Behavioral disinhibition requires the appropriate pattern of changed input–output relationships, not merely more recorded spikes.')
slide('Electrical input separates timing from visual geometry',['P95'],['p95_f2'],'''Schwippert and colleagues stimulated the contralateral **optic nerve**, the bundle carrying retinal axons to the brain, and recorded field potentials from nine sites over the dorsal tectal surface. The grid spans the tectal map with an original 1 mm anatomical calibration.

Short pulses of approximately 0.1 ms at currents up to 10 μA supplied a precisely timed input. Repeated optic-nerve stimulation at 0.8 Hz produced reproducible waveforms that could be compared with responses evoked by stimulating the pretectal Lpd/P region.

Bypassing the retinal image permits an analysis of input timing and interactions without changing object size or shape. Electrical activation does not reproduce a natural visual spike pattern, and a surface field potential reports population currents rather than one identified neuron’s membrane voltage.''','A stimulus artifact is the electrical disturbance directly associated with the applied pulse. It must be distinguished from subsequent neural components. The nine-site grid allows the authors to compare where input effects are large, but it does not itself identify which cells generate the waveform.')
slide('The optic-nerve response has separable components',['P95'],['p95_f3'],'''The optic-nerve-evoked tectal field begins with a rapid presynaptic component, labeled PRE or P1 in the source recordings. **Presynaptic** denotes activity before transmission across a synapse; the later field waves reflect aggregate responses within the tectal layers.

Schwippert and colleagues distinguished the negative N1 wave and later positive and negative components. N1 began at approximately 11 ms and peaked around 18.7 ms; N2 began around 24 ms and peaked around 40.6 ms. Lower stimulus current could remove the later N2 component and merge positive components.

The timing permits selective comparison of an early retinotectal response with later activity. These wave labels describe measured extracellular polarities and latencies; they are not names of receptor types, channels or single identified synaptic connections.''','Negative and positive mean voltage relative to the recording reference. They do not mean that every cell is hyperpolarized or depolarized. The component separation is useful because conditioning can affect one part of the response while preserving others.')
slide('Field polarity depends on tectal recording depth',['P95'],['p95_f1'],'''Schwippert and colleagues compared field responses recorded at the tectal surface and at successive depths. The optic tectum is **laminated**, meaning that neural elements and their connections are organized in layers with different orientations and positions.

The original records at approximately 200–400 μm below the surface differed in polarity from the surface waveform. Retinal axons terminate superficially, while tectal dendrites extend through the layered structure, so the electrode samples different arrangements of current sources and sinks.

A **current sink** is a region where extracellular current enters cells; a source is a region where it returns outward. The depth dependence prevents equating a negative extracellular wave directly with membrane inhibition, excitation or a particular ionic conductance without additional physiological evidence.''','The original depth series retains the reference position and scale. Changing the electrode depth changes the geometry of the currents that dominate the recording. The field’s sign is therefore an anatomical and electrical property of the population measurement, not a substitute for an intracellular voltage recording.')
slide('Ipsilateral pretectal stimulation has regional effects',['P95'],['p95_f4'],'''The authors stimulated the **Lpd/P region**, comprising lateral posterodorsal and posterior pretectal areas, on the same side as the recorded tectum. The electrode approached beneath the rostral tectal lobe and stimulated at approximately 400–700 μm depth; histological marking verified the site.

Ipsilateral stimulation produced a negative wave beginning around 8–10 ms and peaking near 20 ms, followed by a positive component peaking around 40–45 ms. The negative response was largest at rostral dorsomedial recording sites, including sites E and F.

The spatial distribution supports an organized pretectal influence on the tectal map. Activation of tissue near the marked site does not by itself distinguish a direct inhibitory projection from recruitment of an excitatory input that activates a tectal inhibitory relay.''','The anatomical section identifies where the stimulation occurred, while the surface grid identifies where its effects were measured. The two positions are distinct. A negative population wave can accompany an inhibitory circuit effect because excitation of intermediary neurons may precede the final suppression.')
slide('The opposite pretectum produces a different field',['P95'],['p95_f5'],'''Schwippert and colleagues stimulated the pretectal Lpd/P region contralateral to the recorded tectum and compared the resulting waveform with ipsilateral stimulation. The same tectal grid allowed side-dependent input effects to be measured across corresponding locations.

Contralateral stimulation produced a small early component around 5–7 ms and a predominantly positive wave beginning around 14–16 ms and peaking approximately 35–45 ms. The conspicuous negative wave produced by ipsilateral pretectal stimulation was not a comparable feature of this response.

The side-dependent difference is consistent with different routes or local circuit recruitment by the two inputs. Extracellular polarity alone cannot establish a particular inhibitory receptor, prove that no excitatory cells are involved, or identify a single commissural connection as the entire pathway.''','The two stimulation conditions differ in anatomical side while the recording is made from the same tectal surface. Comparing them tests lateral organization. Similar broad anatomical regions can influence the tectum through physiologically different sequences of activity.')
slide('A pretectal lead suppresses the early retinal wave',['P95'],['p95_f6','p95_hist'],'''The paired-stimulation experiment delivered a pretectal Lpd/P pulse before an optic-nerve pulse. **Conditioning** is the earlier input whose effect on the later test response is measured; the interval between pulses controls when the pathways can interact.

When the pretectal input preceded the optic-nerve input by approximately 17–25 ms, the early negative N1 component was strongly attenuated or nearly absent. At longer intervals of about 30–100 ms, the same strong reduction was not evident. Some later components remained comparatively preserved.

The narrow effective interval supports a timed neural interaction rather than a permanent loss of retinal input. It does not mean that visual avoidance starts exactly 20 ms after a predator appears or that a single inhibitory synapse accounts for the population effect.''','The delay is imposed between two electrical pulses, not measured from the appearance of a natural object. The response remains after sufficiently long delays, making the time-dependent suppression different from cutting the optic nerve or permanently silencing the tectum.',True)
slide('Stimulus strength changes which waves are suppressed',['P95'],['p95_f7','p95_hist'],'''Schwippert and colleagues varied optic-nerve stimulus strength while changing the delay after pretectal stimulation. Weak and stronger test inputs recruited different combinations of early and later components, permitting the effect to be evaluated beyond a single waveform amplitude.

At effective delays near 20–25 ms, the early negative component was attenuated. With stronger optic-nerve stimulation, effects on the later negative component were also evident, while positive components could remain relatively unaffected. The original delay plots retain the timings and component-specific measurements.

The interaction therefore depends on both the timing and the recruited input population. Selective attenuation supports circuit regulation rather than uniform elimination of all tectal activity, but the recordings cannot assign each component to one chemically identified neuron class.''','A stronger nerve stimulus can recruit additional axons and response components. Its effect is not equivalent to simply making a natural prey object larger. The component-dependent changes constrain possible mechanisms without providing a receptor-level explanation.')
slide('A visual conditioner can reduce the retinal response',['P95'],['p95_f8','p95_hist'],'''The authors established a steady tectal field response with optic-nerve stimulation at 0.8 Hz, then moved a large black object across the corresponding visual input between electrical test pulses. The retinal image was therefore present as a conditioner rather than as the electrically timed test signal.

The subsequent negative N1 and N2 components were reduced, and suppression could persist after the visual stimulation. A brief train of pretectal pulses at 10 Hz for approximately 1 second produced a comparable attenuation of negative components.

The visual effect links the electrical interaction to a natural route of sensory activation. A large moving object can recruit several retinal and central pathways, so similar field suppression does not prove that visual and electrical conditioning use exactly the same cells.''','The comparison preserves the optic-nerve test pulse and changes the intervening conditioner. It is evidence that sensory stimulation can influence the same measured response components, rather than evidence that the visual object generates the same spike pattern as the pretectal electrode.')
slide('Repetition controls challenge a simple adaptation account',['P95'],['p95_f9','p95_hist'],'''**Adaptation** is a change in responsiveness caused by preceding activity. An alternative explanation for paired-input suppression was that the first pulse simply exhausted the same excitable pathway later recruited by the optic-nerve test pulse.

Schwippert and colleagues alternated optic-nerve and pretectal stimulation at 4 Hz, equivalent to a 125 ms separation. Their responses changed differently with repetition. Two optic-nerve pulses separated by 20 ms did not produce the same obvious attenuation of N1 in the second field response as the effective pretectal conditioning pulse.

The controls weaken a simple shared-pathway adaptation explanation and the possibility that pretectal current merely spreads to the adjacent optic tract. They support a pathway-specific interaction without excluding every possible form of network adaptation.''','An adaptation hypothesis predicts consequences of repeating the test input itself. The paired optic-nerve control tests that prediction at the effective short interval. A failed simple adaptation account does not establish the identity of the inhibitory relay or the final receptor mechanism.')
slide('Inhibitory network effects need not be a direct synapse',['P95'],['p95_f4'],'''Pretectal stimulation reduced a later retinally evoked tectal field component, but ipsilateral pretectal stimulation alone also produced a negative wave. Schwippert and colleagues considered multiple circuit arrangements compatible with this combination of recorded effects.

An excitatory pretectal input could recruit an inhibitory tectal interneuron, a neuron connecting cells within a local circuit. Alternatively, regulation could occur at retinal terminals through **presynaptic inhibition**, a reduction of transmission before the postsynaptic target receives its input. The paired effect is strongest at approximately 17–25 ms.

The population recordings support an inhibitory influence at the network level. They do not distinguish every synaptic step, establish which interneuron releases a transmitter, or directly measure an identified receptor-mediated inhibitory current.''','A pathway can have an excitatory first synapse and an inhibitory net effect. Direct pretectal inhibition, recruitment of local inhibition and regulation of retinal transmitter release are different mechanistic claims. The waveform alone is insufficient to choose conclusively among them.')
slide('NPY application reduces an evoked tectal response',['S95'],['s95_f2','s95_f1a'],'''**Neuropeptide Y**, or NPY, is a peptide signaling molecule investigated as a possible contributor to pretectal regulation. Schwippert and Ewert applied synthetic NPY locally to the superficial tectum of cane toads while measuring the field evoked by optic-nerve pulses at 0.8 Hz.

A solution at 10⁻⁴ mol/L, equivalent to 100 μM, was delivered by a micropipette near the recording site. Within approximately 5–10 minutes, the negative field component fell to about 24% of its initial amplitude. The initial and later positive components were affected much less.

Local NPY is therefore sufficient to attenuate a measured retinotectal population response under these conditions. Its effect does not establish that endogenous NPY is necessary for prey rejection or that a physiological release event reaches the applied concentration.''','A peptide application is a pharmacological intervention, not a recording of natural peptide release. The spatially local delivery and component-specific effect connect NPY to tectal input regulation, while the relatively high applied concentration limits direct inference about its normal extracellular level.')
slide('Vehicle and recovery constrain the peptide result',['S95'],['s95_f2','s95_f1a'],'''Schwippert and Ewert compared NPY delivery with delivery of Frog-Ringer solution alone. The **vehicle** is the solution carrying a drug or peptide; a vehicle control tests whether fluid application or the carrier produces the measured effect independently of the active substance.

Ringer solution did not produce the same strong attenuation of the negative wave. After removal of the NPY pipette, the response recovered to approximately 65% of its original amplitude over about 30 minutes. Recovery was substantial but incomplete over the reported interval.

The comparisons support a reversible peptide-dependent effect rather than irreversible destruction of the retinal input. They do not identify a receptor subtype, measure peptide clearance directly, or establish that the partial recovery corresponds to a normal behavioral recovery process.''','The vehicle condition separates application of liquid from application of NPY. The recovery measurement supports reversibility, but a return to 65% is not a complete return to baseline. No claim that the toad’s prey-catching behavior recovered accompanies this field-potential experiment.')
slide('The peptide effect is slower than electrical conditioning',['S95','P95'],['s95_f1'],'''Electrical pretectal conditioning attenuated the negative retinally evoked field at a pulse separation around 20–25 ms, whereas locally applied NPY required approximately 5–10 minutes for strong attenuation. The two interventions probe related response components on very different experimental timescales.

The NPY pipette was positioned approximately 200–300 μm from the recording site, so diffusion and delivery through tissue contribute to the application delay. That delay is not a measurement of how fast a pretectal neuron releases endogenous peptide during a visual encounter.

Similarity of the affected component supports a possible relation between peptide modulation and pretectal regulation. Different delivery conditions prevent equating the pharmacological time course with the latency of a naturally occurring synaptic inhibitory event.''','A bath or pipette application introduces transport through tissue before receptors are reached. A pulse delivered inside a pathway has a different starting point. Comparing their outcomes is informative, but assigning the millisecond conditioning effect to the minute-scale application curve would exceed the experiment.')
slide('NPY does not identify the complete inhibitory pathway',['S95'],['s95_f2','s95_f1a'],'''Schwippert and Ewert related their NPY effect to published anatomical evidence for NPY-containing pretectal projections and superficial tectal fibers near retinal terminals. This distribution is compatible with a peptide influence on incoming visual transmission.

They proposed that NPY might reduce excitation at retinal terminals, a form of presynaptic inhibition. The measured result remains a reduction of the negative field to approximately 24% after local peptide application; no individual retinal terminal or postsynaptic cell was recorded intracellularly in this test.

The study did not establish a particular NPY receptor subtype, demonstrate endogenous peptide release during avoidance, or block an identified ion channel to test its necessity. A candidate transmitter and a demonstrated complete synaptic mechanism are different levels of explanation.''','Receptor and channel specificity would require interventions that distinguish those molecular steps. Anatomical proximity and a similar population-field effect make a proposed mechanism plausible, but neither substitutes for measuring the relevant synaptic current or selectively preventing natural signaling.')
slide('DC stimulation tests avoidance in behaving toads',['W07'],['w07_f1','w07_f3'],'''McConville and Laming applied **direct current**, or DC, a sustained electrical current, over the pretectal region while adult common toads viewed a moving prey-like object. The positive electrode contacted the right surface over the lateral posterodorsal nucleus, or Lpd.

A black cardboard object 3 cm long and 0.75 cm wide moved at approximately 2 cm/s around a viewing window. Both clockwise and anticlockwise movement were tested, providing opposite directions of visual motion while retaining the same physical object and chamber.

The experiment tested whether stimulation could bias an intact behaving animal away from prey approach and toward defensive actions. Surface current is not selective for one neuron class, and changes in behavior cannot alone establish whether a particular pretectal cell population increased its firing.''','The stimulus dimensions here are physical lengths, unlike the angular dimensions used in several earlier experiments. They should not be converted into retinal angles without the required viewing geometry. The original apparatus and electrode placement define the behavioral preparation.')
slide('Pretectal DC generally reduces approach',['W07'],['w07_f5','w07_f3'],'''The **approach** component of prey-catching was scored as forward movement toward the moving worm-like stimulus. McConville and Laming counted its occurrence while varying pretectal DC current and presenting the same 3 cm × 0.75 cm visual object.

Approach generally declined as current increased, with very low occurrence through much of the higher-current range. At 300 μA there was a small increase relative to the preceding high-current conditions. The published original color bars retain both directions of stimulus movement.

The overall reduction is consistent with a pretectal influence that restrains feeding-related actions. The nonmonotonic endpoint prevents describing the relation as a perfectly graded suppression, and an approach movement by itself does not establish the animal’s recognition of the object as edible.''','The authors considered that movement at the highest current might accompany a defensive stance rather than ordinary feeding. That interpretation was proposed, not confirmed by a direct readout of stimulus identity. The measured variable is the observed approach component.',True)
slide('Arousal persists when approach is reduced',['W07'],['w07_f4','w07_f3'],'''McConville and Laming distinguished **arousal**, extension of the head and forelimbs, from approach, retreat and crouching. These components separate detection-related activation from the particular direction of the animal’s subsequent movement.

Across the 0–300 μA DC range, arousal was relatively constant, although reductions occurred at 0.1 and 50 μA. Approach was reduced much more broadly as current increased. The animal could therefore remain behaviorally responsive while its prey-directed movement declined.

The dissociation argues against treating reduced approach as complete visual unresponsiveness or generalized paralysis. It does not prove that sensation was unchanged in every respect, and it does not establish whether current altered perception, action selection, motivation or several processes together.''','Arousal and approach were scored separately in the same behavioral framework. A toad lifting its head or forelimbs can respond to the event without walking toward the object. Preserved arousal constrains the interpretation of reduced feeding behavior, but it is not a complete measure of visual perception.',True)
slide('High DC current recruits retreat',['W07'],['w07_f6','w07_f3'],'''**Retreat** was scored as backward movement away from the worm-like stimulus. McConville and Laming presented that same prey-like object during each DC condition, allowing a defensive action to emerge without substituting a larger predator-shaped visual cue.

Retreat was not observed at currents below 100 μA in the reported experiment. It appeared at 100 μA and increased at 300 μA, in the same range where prey-related approach was generally reduced. Both directions of object movement were represented in the source data.

The result supports a stimulation-dependent change in the action released by a constant visual stimulus. It does not show that the toad recognized an actual predator, and the current threshold should not be treated as a natural pretectal firing threshold.''','The apparent switch is a change in observed movement toward the same cue. Electrical stimulation can bias that selection without changing the object. A behavioral response compatible with defense does not identify the internal perceptual category or the individual neurons carrying the decision.',True)
slide('High DC current also recruits crouching',['W07'],['w07_f7','w07_f3'],'''**Crouching** was scored as lowering the head and shoulders rather than advancing toward the object. This posture is a defensive component distinct from retreat, which changes the animal’s position by moving backward.

McConville and Laming reported no crouching below 100 μA, followed by crouch responses at 100 and 300 μA. The same moving worm-like object was present, and high-current stimulation increased both this postural response and retreat while generally reducing approach.

The coordinated behavioral changes support a shift toward defensive responding rather than a simple uniform reduction of all movement. They do not establish that the pretectal Lpd region contains a single command neuron for crouching or that current selectively activated a naturally defined predator pathway.''','A posture and a translational movement are different motor outputs. Their emergence in the same current range makes a defensive interpretation of the behavioral change more plausible than interpreting reduced approach alone. The surface stimulation remains broader than a cell-specific causal manipulation.',True)
slide('Glial potassium modulation remains a proposed mechanism',['W07'],['w07_f7','w07_f3'],'''McConville and Laming proposed that DC stimulation could generate slow potential shifts associated with redistribution of potassium ions. **Glia** are non-neuronal cells that regulate the environment around neurons; their discussion emphasized radial glial processes in amphibian tissue.

Increasing extracellular potassium can bring neuronal membrane voltage closer to spike threshold and thereby increase excitability. The authors suggested that such modulation might prime pretectal nonprey-responsive cells and increase restraint of tectal feeding-related activity. Their behavioral effect included crouching only at currents of 100 μA and above.

The experiment did not directly measure potassium redistribution, glial currents, TH3-cell firing or a particular potassium channel. The ion-based account is an explanatory hypothesis for a measured behavioral change, rather than an established molecular sequence for predator avoidance.''','TH3 is a physiological designation for pretectal cells responsive to large moving or nonprey configurations, as discussed in the paper’s background. The DC behavioral experiment did not record those cells. No channel name or receptor subtype can be inferred simply from the observed current-dependent behavior.')
assert len(S)==44,len(S)
photo=json.loads((ROOT/'lectures/L9/lecture.json').read_text())['title_image'];photo=dict(photo,path='figures/title_toad.jpg')
items=[('Pretectal restraint','Effective pretectal and caudal thalamic damage releases catching toward large or unsuitable objects; preserved snapping separates this effect from loss of the motor capacity.'),('Selectivity and excitability','Configuration filtering and response strength are distinct: some cuts increase firing without eliminating the worm–antiworm distinction.'),('Timed input interaction','Pretectal conditioning strongly attenuates an early optic-nerve-evoked tectal component at a lead of approximately 17–25 ms; adaptation controls support a pathway-specific effect.'),('Distinct electrical measurements','Unit spikes, EEG and slow extracellular potentials measure different activity; more firing can coexist with a smaller population field.'),('NPY evidence','Local NPY reduces the negative tectal field component, but receptor identity, endogenous release and necessity for avoidance were not established by the application experiment.'),('Behavioral bias and molecular limits','High pretectal DC recruits retreat and crouching while generally reducing approach; glial potassium modulation remains a proposed explanation rather than a measured pathway.')]
tk={'items':[{'lead':a+'.','text':b} for a,b in items],'cite':'Ewert (1970); Ingle (1973); Laming & Ewert (1983); Schwippert et al. (1995); Schwippert & Ewert (1995); McConville & Laming (2007)','refs':[v[1] for v in R.values()],'transcript':[a+'. '+b for a,b in items]}
spec={'lecture':10,'theme':'oxford-cloud','content_slides':44,'title_image':photo,'slides':S,'takeaways':tk}
(BASE/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
if __name__=='__main__':
 for n,s in enumerate(S,2):
  words=sum(len(p.split()) for p in s['body'])
  print(n,words,s['title'])
