import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parent
R={
'KC76':('Kristan & Calabrese (1976)','W. B. Kristan Jr; R. L. Calabrese (1976). Rhythmic swimming activity in neurones of the isolated nerve cord of the leech. Journal of Experimental Biology 65(3):643–668','10.1242/jeb.65.3.643'),
'CM12':('Crisp et al. (2012)','K. M. Crisp; B. R. Gallagher; K. A. Mesce (2012). Mechanisms contributing to the dopamine induction of crawl-like bursting in leech motoneurons. Journal of Experimental Biology 215(17):3028–3036','10.1242/jeb.069245'),
'B06':('Briggman & Kristan (2006)','K. L. Briggman; W. B. Kristan Jr (2006). Imaging dedicated and multifunctional neural circuits generating distinct behaviors. Journal of Neuroscience 26(42):10925–10933','10.1523/JNEUROSCI.3265-06.2006'),
'C00':('Cacciatore et al. (2000)','T. W. Cacciatore; R. Rozenshteyn; W. B. Kristan Jr (2000). Kinematics and modeling of leech crawling: evidence for an oscillatory behavior produced by propagating waves of excitation. Journal of Neuroscience 20(4):1643–1655','10.1523/JNEUROSCI.20-04-01643.2000'),
'PM08':('Puhl & Mesce (2008)','J. G. Puhl; K. A. Mesce (2008). Dopamine activates the motor pattern for crawling in the medicinal leech. Journal of Neuroscience 28(16):4192–4200','10.1523/JNEUROSCI.0136-08.2008'),
'WP81':('Willard (1981)','A. L. Willard (1981). Effects of serotonin on the generation of the motor program for swimming by the medicinal leech. Journal of Neuroscience 1(9):936–944','10.1523/JNEUROSCI.01-09-00936.1981'),
'YN99':('Yu et al. (1999)','X. Yu; B. Nguyen; W. O. Friesen (1999). Sensory feedback can coordinate the swimming activity of the leech. Journal of Neuroscience 19(11):4634–4643','10.1523/JNEUROSCI.19-11-04634.1999'),
'P12':('Puhl et al. (2012)','J. G. Puhl; M. A. Masino; K. A. Mesce (2012). Necessary, sufficient and permissive: a single locomotor command neuron important for intersegmental coordination. Journal of Neuroscience 32(49):17646–17657','10.1523/JNEUROSCI.2249-12.2012'),
'A21':('Ashaber et al. (2021)','M. Ashaber; Y. Tomina; P. Kassraian; E. A. Bushong; W. B. Kristan Jr; M. H. Ellisman; D. A. Wagenaar (2021). Anatomy and activity patterns in a multifunctional motor neuron and its surrounding circuits. eLife 10:e61881','10.7554/eLife.61881'),
'K22':('Kearney et al. (2022)','G. Kearney; M. Radice; A. Sanchez Merlinsky; L. Szczupak (2022). Intersegmental interactions give rise to a global network. Frontiers in Neural Circuits 16:843731','10.3389/fncir.2022.843731')}
def ref(k):return R[k][1]+'. https://doi.org/'+R[k][2]
def fig(k,name,n,cap):return {'path':'figures/'+name+'.png','caption':R[k][0]+', Fig. '+n+'. '+cap,'source_url':'https://doi.org/'+R[k][2]}
DE3=('A21','A21_DE3','7(a)','Reconstructed DE-3 arbor over a dorsal micro-CT image.')
slides=[]
def add(title,k,name,n,caption,text,extra,anatomy=None):
 body=text.strip().split('\n\n');assert len(body)==3,(title,len(body));assert len(title)<=62,title
 s={'title':title,'layout':'figure-right','body':body,'transcript':[re.sub(r'\*\*|_', '',p)for p in body]+[extra],'cite':R[k][0],'refs':[ref(k)],'figure':fig(k,name,n,caption)}
 if anatomy:
  s.update(layout='figures-right',figure_width=6.0,primary_figure_height=3.2,figures=[s.pop('figure'),fig(*anatomy)])
  from PIL import Image
  im=Image.open(ROOT/s['figures'][0]['path'])
  if im.width/im.height<1.25:s.update(figure_arrangement='side-by-side',primary_figure_width=4.2)
  if anatomy[0]!=k:s['refs'].append(ref(anatomy[0]));s['cite']+='; '+R[anatomy[0]][0]
 slides.append(s)
add('Swimming and crawling reorganize the same muscles','B06','B06_1AB','1(A,B)','Published swimming and crawling movement sequences.', '''Leech swimming consists of alternating contractions of dorsal and ventral longitudinal muscles, producing a wave that travels toward the tail. Crawling instead alternates elongation, driven by circular muscles, with shortening, driven by longitudinal muscles. The front and rear suckers attach and release to convert these changes into forward movement.

Briggman and Kristan elicited both motor patterns in the same isolated nervous system while monitoring motor nerves and recording individual neurons. Swimming occurred at approximately 1–1.5 Hz, whereas crawling oscillations occurred at approximately 0.04–0.1 Hz. The different rhythms reorganized common motor outputs.

A **central pattern generator**, or CPG, is a neural circuit capable of producing a patterned rhythm without requiring rhythmic sensory input. Central generation does not imply that sensory feedback, descending signals, or the mechanical environment are irrelevant to the realized movement.''','Dorsal refers to the back surface and ventral to the belly surface. Longitudinal muscle contraction shortens the body; circular muscle contraction contributes to elongation. These muscle arrangements give the same animal two distinct forms of locomotion.')
add('Segmental markers resolve the components of a crawl','C00','C00_2A','2(A)','Marked leech and measured regional length changes.', '''**Kinematics** describes movement without assigning its underlying forces or neural causes. Cacciatore and colleagues attached small thread markers to segment boundaries in adult leeches and recorded crawling from above. Their analysis used vermiform steps, in which the body remained near the substrate, rather than steps with a raised body loop.

Video was digitized at 4–10 frames per second, with at least 25 frames per step. Distances between markers yielded segmental length changes. Anterior segments generally elongated earlier than posterior ones; the reverse transition to shortening also propagated toward the tail.

The preparation connects whole-animal movement to regional timing. Marker displacement measures body deformation, not motor-neuron firing. The investigators excluded searching movements, so these results characterize stereotyped steps on a smooth surface rather than every possible form of crawling.''','The study used adults weighing 2–4 g, allowed recovery after marker implantation, and calibrated spatial measurements with a visible grid. These controls reduced confusion between image scale, recovery effects, and actual changes in movement.')
add('Crawl duration changes the speed of traveling waves','C00','C00_3','3','Measured segment-length sequences during fast and slow steps.', '''Cacciatore and colleagues compared segmental length changes during fast and slow crawling steps. **Propagation** means that a change begins in successive body regions at different times. Both elongation and contraction propagated from anterior to posterior segments rather than occurring simultaneously throughout the body.

Typical stereotyped steps lasted approximately 2–10 s. Slower steps contained slower wave propagation and changes in the interval between elongation and contraction. Anterior regions could begin contracting while posterior regions were still elongating, so whole-body elongation and contraction were not strictly separate blocks.

These observations constrain a neural explanation of crawling to account for regional timing and variable step duration. The recorded waves are behavioral data. The paper’s proposed excitation-chain model is an explanatory construction and does not establish that its specific simulated neurons exist in the leech.''','A contour representation of measured length preserves the sequence of local lengthening and shortening. The important experimental relationship is that different portions of the body can occupy different movement phases during one step.')
add('Crawl waves can cross denervated body segments','C00','C00_7','7(A,B)','Movement timing after removal of peripheral innervation.', '''Cacciatore and colleagues severed the peripheral nerve roots of segments 7–12 while preserving the central connectives between ganglia. **Denervation** removes neural communication with the body wall. In this preparation it removed both sensory input and motor output in the operated segments, rather than selectively removing sensory neurons.

The denervated segments became flaccid, but elongation and contraction waves continued in the innervated regions on either side. Segmental delays and their relationship to step duration did not acquire a marked discontinuity across the operated region. The comparison used each animal’s movements before and after surgery.

Central communication can therefore coordinate crawl timing across a region deprived of its normal peripheral loop. This result does not establish that sensory feedback has no role in intact crawling, and it does not identify the central neurons that carry coordination across the lesion.''','Connectives are axon bundles linking successive ganglia. Preserving them was essential: cutting both the nerve roots and the connectives would have confounded loss of peripheral feedback with loss of communication along the nervous system.')
add('An isolated cord generates a swim-like motor rhythm','KC76','KC76_1','1(A)','Motor-nerve bursts and intracellular oscillations in an isolated cord.', '''Kristan and Calabrese removed the nerve cord from the body wall and recorded from segmental nerves in physiological saline. Brief electrical stimulation initiated repeated bursts in dorsal and ventral motor pathways. The isolated cord had no attached body capable of producing the usual stretch feedback.

A stimulus train of approximately 10–20 Hz for 0.5–1 s could initiate an episode that continued after the stimulation ended. Rhythmic motor activity resembled the pattern recorded during swimming in semi-intact animals. Intracellular motor-neuron recordings contained rhythmic membrane-potential changes associated with the nerve bursts.

The persistence of patterned activity without the peripheral body establishes a central source for the basic swim rhythm. It does not establish normal propulsion, intact sensory calibration, or a particular identified pacemaker neuron. A motor program recorded without the corresponding movement is called **fictive locomotion**.''','An intracellular electrode records voltage within an individual neuron; an extracellular electrode records signals outside cells, here from nerve bundles. The two methods connect membrane-potential oscillations to motor impulses without requiring actual movement.',DE3)
add('The same preparation retains rhythm after isolation','KC76','KC76_2AB','2(A,B)','Semi-intact and subsequently isolated motor-nerve recordings.', '''Kristan and Calabrese first recorded a swimming rhythm from a semi-intact preparation and then disconnected its remaining body wall. **Semi-intact** means that part of the animal remains capable of movement while another part is opened for recording. Keeping the same recording nerves permitted comparison before and after isolation.

Dorsal-excitor and ventral-excitor bursts continued to alternate after the cord was separated from peripheral tissue. In the illustrated semi-intact recording the cycle period was about 1 s, and homologous dorsal bursts in two segments were separated by approximately 50 ms.

The within-preparation comparison strengthens the interpretation that central circuitry can generate the alternating pattern. It also reveals why preserving a recognizable rhythm is different from preserving every aspect of normal timing. Peripheral removal can alter phase relationships even when the central oscillation remains active.''','A cycle period is the interval between successive equivalent events in one rhythm. The investigators used burst midpoints rather than the first spike alone, making their timing definition consistent across bursts of differing duration.',DE3)
add('Motor bursts predict alternating muscle contractions','KC76','KC76_3A','3(A)','Body-wall tension and motor-nerve activity in a nearly isolated preparation.', '''Kristan and Calabrese retained one innervated body segment while separating the rest of the nerve cord from the periphery. Tension transducers measured the dorsal and ventral longitudinal muscle contractions in that segment. Motor-nerve activity was recorded from another ganglion along the cord.

Dorsal and ventral tension rose in alternating phases. Bursts in the corresponding excitatory motor pathways were related to the matching muscle contractions. The body-wall segment and recorded ganglion were separated spatially, so their events included the delay associated with propagation along the cord.

An **excitor** is a motor neuron whose output promotes contraction of its target muscle. The agreement between nerve timing and tension links the electrical pattern to the expected motor action. It does not make an isolated nerve recording a direct measure of swimming thrust or whole-animal displacement.''','An inhibitory motor neuron can relax the matching muscle territory and inhibit its excitatory motor neurons. Alternating excitation and inhibition organize contraction across the dorsal and ventral body wall rather than simply turning every motor neuron on together.',DE3)
add('Isolation changes dorsal–ventral timing relationships','KC76','KC76_5','5(A–C)','Measured phase-delay and burst-duration relationships.', '''**Phase** describes the position of an event within a repeating cycle. Kristan and Calabrese compared dorsal-to-ventral burst delays over different swim periods. Some isolated preparations retained period-dependent delays, whereas others expressed an approximately constant fractional phase lag.

In semi-intact preparations, dorsal-excitor burst duration increased more strongly with cycle period. In constant-phase isolated preparations, its dependence on period was weaker. Ventral-excitor burst duration was comparatively less dependent on cycle period and did not distinguish the two timing states in the same way.

Central rhythm production and normal phase calibration are separate properties. The study supports a contribution of peripheral input to the timing relationships expressed during swimming. Isolation does not force every preparation into an identical state, and the comparisons do not identify a single receptor or synaptic connection responsible for the change.''','A time delay in milliseconds and a phase lag as a fraction of the cycle are related measurements, but they answer different questions. A fixed fraction requires the absolute delay to grow when the cycle becomes longer.',DE3)
add('Central delays do not fully reproduce the intact wave','KC76','KC76_6','6(A,B)','Intersegmental motor-burst delay versus swim period.', '''**Intersegmental delay** is the time separating equivalent activity in different segments. Kristan and Calabrese recorded homologous dorsal-excitor bursts from separated ganglia and expressed the resulting delay per segment. Posterior bursts generally followed anterior bursts, consistent with a rearward-moving motor pattern.

Delays in semi-intact and isolated cords were shorter than the delays inferred from intact swimming movements. The clear increase of intact movement delay with cycle period was absent in the reduced preparations. Their delay distributions remained variable despite a recognizable central rhythm.

A chain of centrally coupled neurons can generate directional timing without recreating the complete intact body wave. Peripheral feedback can adjust the relationship between propagation and period. The preparation comparison supports that contribution, but differences in movement and nerve-recording measures also limit a direct numerical equivalence.''','In intact animals the traveling wave is measured through body movement; in the isolated cord it is measured through motor impulses. The study explicitly compares these related levels without treating their delays as automatically identical.',DE3)
add('Stretch modifies bursts differently across preparations','KC76','KC76_9','9(A,B)','Body-wall stretch during semi-intact and nearly isolated rhythms.', '''Kristan and Calabrese attached a dorsal body-wall flap to a tension transducer and imposed longitudinal stretch during swimming activity. **Sensory feedback** is information generated by the body or environment that returns to the neural controller. Stretch provided a controlled perturbation rather than relying on spontaneous changes in movement.

In the semi-intact preparation, stretch prolonged dorsal-excitor bursts and shortened, or sometimes abolished, ventral-excitor bursts without changing the cycle period. In a nearly isolated preparation retaining one innervated segment, moderate stretch changed burst durations and could lengthen the overall period.

Feedback can alter both the motor output and, under reduced conditions, the rhythm-generating network. The experiment does not establish one uniform effect of stretch under every condition. The remaining innervation and the extent of peripheral removal determine which feedback pathways can influence the rhythm.''','A weak or moderate stretch and a strong stretch need not produce the same outcome. The source reports that stronger perturbations could stop the rhythm, so period lengthening is not an unrestricted linear rule.',DE3)
add('A dorsal inhibitor can slow the isolated swim rhythm','KC76','KC76_8','8(A–C)','Effects of current injection into identified inhibitory motor neurons.', '''Kristan and Calabrese injected depolarizing current into identified motor neurons during an isolated-cord swim episode. **Depolarization** moves membrane voltage toward a less negative value and can increase firing. The dorsal inhibitor, cell 1, was stimulated strongly enough to suppress the associated dorsal excitor locally.

Cell 1 stimulation lengthened the period across the cord, including a recording two segments away. In one episode, the period increased from approximately 825 to 940 ms during the first current passage. Comparable stimulation of the ventral inhibitor, cell 2, did not produce the same period change.

The effect is specific evidence that cell 1 can influence the isolated oscillator, rather than proof that every motor neuron is a rhythm generator. The same manipulation did not reset period in the semi-intact preparation. Network state and peripheral input therefore constrain the behavioral significance of this feedback route.''','An inhibitor can influence the motor pattern through more than its peripheral muscle connection. Current injection tests the functional effect of activating the identified cell; it does not by itself reveal all intervening synapses.',DE3)
add('Implanted electrodes connect swim impulses to movement','YN99','YN99_2','2(A,B)','Original recording preparation and implanted-electrode experiment.', '''Yu and colleagues implanted hook electrodes on dorsal posterior nerves in leeches whose bodies could still move. The largest motor unit in these nerves was used to monitor the dorsal excitor DE-3. Video and electrical recordings linked the progression of the body wave with activity on either side of a central cord transection.

The cord was cut between midbody ganglia M10 and M11. Recording sites at M7 and M14 bracketed the interruption. Intact preparations and preparations with a severed cord provided the critical comparison while retaining peripheral muscles and sensory receptors.

This design tests whether coordination can cross a central interruption through routes associated with the moving body. It does not isolate one stretch receptor or one reflex pathway. The implanted signals provide direct motor timing while the behavioral records establish whether the body remained coordinated.''','A transection is a surgical cut through a neural pathway. The lesion severed the connecting nerve cord while leaving the surrounding body continuous, which differs fundamentally from separating the animal into two physical halves.',DE3)
add('Body continuity permits swimming after cord transection','YN99','YN99_3','3(A,B)','Measured body-wave sequences before and after a central cut.', '''Yu and colleagues videotaped the same leeches before and after cutting the nerve cord between M10 and M11. Beads placed at M7 and M14 allowed timing of troughs and crests at defined body locations. Unimplanted controls and animals with beads helped separate surgery effects from effects of the movement markers.

The severed-cord animals could retain a rearward-progressing body wave spanning the lesion. Their phase lag between M7 and M14 increased from roughly 147° before the cut to roughly 170° afterward. They also swam more slowly, so persistence of coordination did not mean normal performance was fully preserved.

A continuous body provides a route through which movement-dependent feedback can coordinate separated central regions. The result supports peripheral coordination when direct central communication is interrupted. It does not imply that the intact animal normally dispenses with central intersegmental connections.''','The investigators later cut the animals physically into anterior and posterior halves. Those halves lacked the coordinated whole-body wave, strengthening the interpretation that continuity of the peripheral body matters after the neural lesion.')
add('Motor recordings confirm coordination across the lesion','YN99','YN99_6','6(A–C)','In situ motor-nerve records in intact and severed-cord leeches.', '''Yu and colleagues compared DE-3 burst timing at M7 and M14 while the body moved. This electrical measurement tested whether apparent coordination in video corresponded to coordinated neural output. The same implanted sites could be examined before and after the midbody nerve cord was cut.

Motor bursts remained phase related across the cut while the animal expressed coordinated swimming. The lag was larger and more variable than in intact preparations. Isolated cords whose direct intersegmental connections were severed lacked the comparable coordination available when the body was present.

The combined electrical and behavioral evidence supports feedback-dependent coupling between disconnected central regions. It does not establish that muscles alone transmit the signal without sensory neurons. The relevant peripheral route includes body mechanics and the return of movement-related information to each remaining neural circuit.''','A motor rhythm can remain centrally generated within each cord region while sensory signals coordinate the regions. Central generation and feedback-dependent coordination are compatible properties of the same behavior.',DE3)
add('Serotonin increases the availability of the swim program','WP81','WP81_1','1','Swim episodes before, during and after serotonin exposure.', '''**Serotonin**, also called 5-hydroxytryptamine or 5-HT, is a neurotransmitter that can modulate circuit activity. Willard applied serotonin to isolated leech nerve cords and monitored swim bursts in motor nerves. This preparation tested a neural effect without requiring a moving body.

Serotonin promoted repeated swimming episodes without additional electrical stimulation and increased responses to stimuli that previously evoked only one episode. Approximately 0.5–10 μM induced spontaneous swimming; concentrations as low as 50 nM elicited additional episodes after stimulation. Exposure and washout separated the drug effect from baseline excitability.

Serotonin changes the likelihood that a patterned program is expressed, rather than supplying a sequence of timed muscle commands. This pharmacology does not establish a particular serotonin receptor subtype or ion-channel target. The central circuit still supplies the rhythm once the modulated state permits its expression.''','A neuromodulator changes the operation of a circuit over a broader interval than a single precisely timed synaptic event. The observation concerns access to the swim pattern and should not be converted into an unsupported molecular receptor assignment.',DE3)
add('Serotonin can act on a restricted region of the cord','WP81','WP81_3','3','Restricted serotonin application and cord-disconnection tests.', '''Willard placed a barrier around two ganglia and applied serotonin only to that region of an isolated cord. Peripheral tissue was absent, and the remainder of the cord was maintained in normal saline. This localized exposure tested whether the drug had to reach every segment directly.

After serotonin reached the restricted chamber, the larger cord could generate swimming episodes. Crushing connectives between the exposed region and the remaining cord interrupted the relevant communication. The exposed region could therefore influence distant parts through connections along the central nervous system.

A local modulatory action can recruit a distributed motor circuit. The experiment does not establish that the two exposed ganglia contain the sole rhythm-generating kernel. The effect depends on their access to other ganglia, and crushing a connective interrupts many axons rather than a single identified pathway.''','The preparation separates the site of chemical exposure from the site of distributed motor expression. Keeping the bathing solutions separate made this a test of communication along the cord rather than simple drug diffusion throughout the dish.',DE3)
add('Retzius-cell stimulation releases an effective modulator','WP81','WP81_4','4','Retzius stimulation in a small chamber and resulting swim episodes.', '''Willard stimulated identified **Retzius neurons**, serotonin-containing cells in leech ganglia, while recording the swim program. A small chamber confined the saline around the stimulated cells. This design tested whether neuronal release could reproduce the effect of bath-applied serotonin.

Stimulation evoked swimming when the surrounding volume was small, less than approximately 50 μl. Serotonin was detected in the bathing solution after stimulation. Larger surrounding volumes did not provide the same reliable effect, consistent with dilution of a released substance.

The results link an identified serotonergic source with circuit modulation and chemical release. They do not prove that Retzius cells provide all serotonin acting during intact swimming. Willard also found serotonin in the blood sinus surrounding the cord, indicating that neuronal and circulating access must be distinguished.''','The source used biochemical purification followed by a calibrated snail-heart bioassay to detect serotonin. Detecting released substance supplies evidence beyond simply observing that current injection into a cell altered motor output.',DE3)
add('Voltage-sensitive imaging captures two rhythms in one cord','B06','B06_1DE','1(D,E)','Simultaneous optical and intracellular motor-cell signals.', '''A **voltage-sensitive dye** changes its optical signal with membrane voltage. Briggman and Kristan imaged an exposed segmental ganglion while eliciting swimming and crawling in the same isolated cord. Intracellular recordings from cells 1 and 3 checked whether the optical signals tracked the identified neurons.

Optical and electrical records preserved the different rhythms and phase relationships. Cell 1 and cell 3 oscillated approximately 180° apart during crawling but approximately 90° apart during swimming. Example frequencies were 0.09 Hz for crawling and 1.3 Hz for swimming.

The calibration supports interpreting optical fluctuations as neuronal activity rather than assuming every fluorescence change is a spike. Dye kinetics introduce a temporal lag, and the optical sampling was slower than the electrical recording. Phase-associated imaging is therefore evidence about population dynamics, not a substitute for every intracellular waveform.''','The investigators acquired swimming images at 20 frames per second and formed ratioed signals at 10 Hz. Crawling was slower and could be sampled less frequently. Simultaneous electrical records supplied the faster reference.',('B06','B06_1C','1(C)','Dorsal ganglion surface with identified recording cells.'))
add('Dorsal neurons change their phase across behaviors','B06','B06_2AB','2(A,B)','Measured dorsal-surface phase maps for crawling and swimming.', '''Briggman and Kristan calculated the phase of each optically recorded cell relative to a reference motor neuron. **Coherence** measures how consistently two signals share an oscillation at a specified frequency. Cells that oscillated consistently could be assigned a phase within the corresponding motor cycle.

The dorsal ganglion contained cells active during both rhythms, but their phases were reorganized. The relationship between longitudinal excitors and inhibitors differed because swimming alternates dorsal and ventral contraction whereas crawling coactivates longitudinal muscle groups during shortening. The measured phase maps came from the same preparation.

A cell’s participation in both rhythms does not imply that it serves the same functional role in each. Phase maps constrain which neurons are candidates for shared circuitry. They do not establish the direction or transmitter of a connection, which requires additional anatomical or physiological evidence.''','The displayed panels are the measured maps. The paper also contains predicted maps based on previously known motor functions, but predicted and recorded activity are different kinds of evidence and are kept separate.')
add('Circular-muscle cells participate selectively in crawling','B06','B06_3ABC','3(A–C)','Ventral ganglion and motor-cell activity during the two rhythms.', '''Briggman and Kristan recorded the ventral ganglion surface and simultaneously impaled cells CV and AE. CV is a circular-muscle excitor associated with body elongation. AE, the annulus erector motor neuron, provides a recognizable output associated with crawling and changes in body form.

CV and AE oscillated approximately 180° apart during crawling. Neither displayed the corresponding rhythmic oscillation during swimming in the same preparation. The optical and intracellular records agreed on this distinction, providing a control against mistaking a weak optical signal for behavioral inactivity.

Shared muscle and neural resources coexist with selectively participating cells. The absence of a coherent swim oscillation in these records does not mean that a neuron is permanently silent or incapable of responding to another stimulus. It specifies its recorded contribution under the elicited motor conditions.''','A dedicated component participates in one of the compared rhythms; a multifunctional component participates in more than one. These labels describe the tested behaviors and should not be extended automatically to all possible actions of the animal.')
add('Swimming neurons overlap the crawl population','B06','B06_5AB','5(A,B)','Summary maps of measured shared and selective participation.', '''Briggman and Kristan combined reproducible phase-associated activity across dorsal and ventral imaging experiments. The summary distinguished cells active in both rhythms from cells coherent with only swimming or only crawling. Cells lacking reliable activity were not assigned a behavior merely from anatomical position.

The identified population included about 90 swimming-associated and 188 crawling-associated cells. Of the swimming-associated cells, 84 also oscillated with crawling. Thus most of the observed swim population participated in the slower crawl rhythm, while crawling recruited many additional cells.

The numerical overlap describes recorded rhythmic participation, not proof that every participating neuron generates the rhythm. Some cells may receive the pattern rather than construct it. Nevertheless, the data reject a simple account in which the two behaviors use entirely separate, nonoverlapping neuronal populations.''','The summary maps merge measured participation across preparations. They provide a guide to shared network membership; they are not a complete synaptic wiring diagram and do not determine which connections are causally necessary.')
add('Shared cells change phase at a behavioral switch','B06','B06_6E','6(E)','Motor and intracellular signals at a crawl-to-swim transition.', '''Briggman and Kristan observed switches between crawling and swimming while maintaining recordings from identified motor cells. This comparison follows individual neurons across a state change rather than comparing separate animals assigned to different behaviors. Motor-nerve output identified the behavior expressed on either side of the switch.

Cells 3 and 4 were in phase during crawl-related longitudinal contraction but became approximately out of phase during swimming. The transition could occur within 1–2 s. Their relationship therefore changed on a time scale much shorter than any anatomical rebuilding of the neurons.

The shared circuit can express alternative dynamical configurations through changes in active interactions and input. The recordings establish rapid reorganization but do not identify its complete molecular trigger. Structural overlap permits flexible use of the same cells; it does not by itself specify the mechanism selecting one motor pattern.''','A dynamical configuration describes the timing and relationships of active neurons. The interpretation concerns changes in circuit operation, not a claim that the neuron’s anatomical identity changes when the animal switches locomotor behavior.')
add('Cell 255 can perturb both locomotor rhythms','B06','B06_7AD','7(A–E)','Identified cell 255 morphology and recordings with perturbations.', '''Briggman and Kristan identified cell 255 by its ventral soma position, morphology, and activity. An **interneuron** communicates within the nervous system rather than directly innervating a peripheral muscle. Cell 255 had bilateral arbors and projected through a central connective, supporting its interneuronal identity.

Cell 255 depolarized during crawl elongation and oscillated during swimming. Depolarizing it during crawl contraction ended that phase early and shortened the step period by approximately 21%. Depolarization during elongation did not change the period; stimulation during swimming could slow or terminate the episode.

Current injection supplies causal evidence beyond correlation with a rhythm. The phase specificity argues that the effect depends on the current circuit state. The absence of a consistent effect from hyperpolarizing the cell prevents treating this experiment as proof that cell 255 alone is necessary for either rhythm.''','The original figure includes the filled cell and recordings during both behaviors. A cell can influence two patterns in different ways: accelerating a transition in one and reducing or terminating activity in the other.')
add('Cell 257 is crawl-associated without a proven command role','B06','B06_8','8(A–C)','Cell 257 anatomy and crawl-versus-swim intracellular recordings.', '''Briggman and Kristan identified cell 257 as a ventral interneuron with a projection through an anterior connective. Its morphology differed from cell 255, and its activity was recorded together with the annulus erector cell. The comparison used crawling and swimming in the same preparation.

During crawling, cell 257 depolarized and fired with the elongation phase. During swimming it became strongly hyperpolarized and did not express a coherent swim rhythm. The published recordings preserve a 20 mV calibration and a 2 s time bar for the swimming comparison.

This pattern supports selectively crawl-associated participation. Depolarizing or hyperpolarizing a single cell 257 did not consistently perturb either rhythm, so participation does not establish an initiating or indispensable role. The distinction between observing a cell’s phase and causally controlling the pattern is essential to interpreting population maps.''','Hyperpolarization moves membrane voltage toward a more negative value and can reduce spiking. The recording establishes behavior-dependent suppression of cell 257, while leaving the full source of that inhibition unresolved.')
add('Dopamine recruits crawl-like activity in an isolated CNS','PM08','PM08_1BC','1(B,C)','Motor activity before and during dopamine exposure.', '''**Dopamine** is a neurotransmitter that can alter the functional state of locomotor circuits. Puhl and Mesce superfused isolated whole leech nervous systems with dopamine while monitoring motor nerves and an identified motor neuron. The preparation retained the cephalic and segmental ganglia but lacked the peripheral body.

At approximately 75 μM dopamine, previously quiet motor nerves developed repeated DE-3 bursts. Crawl-like activity could emerge after about 3 min and later acquire anterior-to-posterior propagation. Some preparations became coordinated during dopamine exposure, while others did so during washout.

Dopamine is sufficient to make a crawl-like motor program available in this preparation. The result is not a measurement of natural dopamine concentration at each receptor or proof that dopamine alone determines intact behavioral choice. Local pattern activation and intersegmental coordination remain distinguishable outcomes.''','The supplied concentration is a bath concentration chosen for the experimental preparation. It should not be equated with a measured concentration at an endogenous release site.',DE3)
add('Crawling alternates circular and longitudinal excitation','PM08','PM08_2DE','2(D,E)','CV and VE-4 activity relative to the DE-3 motor burst.', '''Puhl and Mesce recorded intracellularly from the circular excitor CV and the ventral longitudinal excitor VE-4 during dopamine-induced fictive crawling. Simultaneous dorsal posterior nerve recordings monitored DE-3, the dorsal longitudinal excitor. This pairing identified the motor pattern through several muscle-related outputs.

CV activity was approximately 180° out of phase with DE-3. During the DE-3 burst, CV hyperpolarized by approximately 2–4 mV and its spikes were suppressed. VE-4 instead depolarized and fired in phase with DE-3, consistent with coordinated dorsal and ventral shortening.

Correct muscle-group phasing is stronger evidence for a crawl program than a slow DE-3 burst alone. The recordings establish patterned excitation and suppression in the motor outputs. They do not identify every interneuron that imposes the phase relationships or directly measure the resulting muscle force.''','Antagonist muscle actions have opposing mechanical effects. Here circular-muscle activity favors elongation while longitudinal-muscle activity favors shortening; their alternating recruitment is part of the definition of the crawl pattern.',DE3)
add('A single ganglion can express the local crawl pattern','PM08','PM08_3','3(A–C)','Identified excitatory motor-cell activity in isolated ganglia.', '''Puhl and Mesce separated individual segmental ganglia from the rest of the nerve cord and applied dopamine. This reduction removed descending input and intersegmental communication. Intracellular recordings identified DE-3, VE-4, and CV while a motor-nerve recording monitored the local output.

Dopamine induced repeated, appropriately phased activity in all three motor-cell classes. DE-3 depolarizations reached approximately 12–16 mV, with smaller spikes riding on the slow voltage wave. Intracellular DE-3 spikes matched the largest extracellular motor unit one for one, validating the nerve-based monitor.

A segmental ganglion contains circuitry sufficient for local crawl-like pattern production under these conditions. A single ganglion cannot establish a full front-to-back behavioral sequence by itself. Local rhythm-generating capacity therefore does not settle how the intact cord coordinates segments or chooses the next movement.''','A slow wave is a membrane-potential fluctuation on which faster action potentials can ride. The agreement between intracellular spikes and the nerve unit checks cell identity, while the slow wave reflects the patterned drive reaching that motor neuron.',DE3)
add('Inhibitory motor cells alternate with contraction outputs','PM08','PM08_4','4(A,B)','DI-1 and VI-2 activity relative to DE-3 during fictive crawling.', '''Puhl and Mesce recorded the dorsal inhibitor DI-1 and ventral inhibitor VI-2 in isolated ganglia during dopamine-induced crawling. Both are motor neurons associated with inhibition of longitudinal muscle pathways. Simultaneous DE-3 recording identified the contraction-related output of the same local circuit.

Their activity was largely opposite to DE-3 bursting. DI-1 was suppressed during the contraction phase and became more active toward its termination. VI-2 could produce inhibitory potentials in VE-4, directly connecting an inhibitory motor pathway with reduced activity in a longitudinal excitor.

An **inhibitory postsynaptic potential** is a synaptic voltage change that reduces the likelihood of firing in the receiving neuron. These recordings support coordinated inhibitory and excitatory contributions to alternating movement phases. The experiment does not assign a transmitter or receptor subtype solely from the direction of the voltage change.''','Postsynaptic refers to the receiving side of a synapse. Recording a voltage change in VE-4 while identifying VI-2 activity links cell timing to inhibition, but molecular identification requires evidence beyond a membrane-potential trace.',DE3)
add('Fictive crawl rhythms resemble spontaneous crawling','PM08','PM08_7','7','Original quantitative comparisons of crawl period and duty cycle.', '''Puhl and Mesce compared dopamine-induced rhythms in whole cords and single ganglia with spontaneous or electrically induced fictive crawling. They also measured overt crawling from video. The comparisons used cycle period and the duration of contraction-related DE-3 bursts to test similarity of motor organization.

Fictive crawling had periods on the order of 10–15 s in these preparations, whereas overt crawling averaged approximately 3.3 s. The fraction of a fictive cycle occupied by DE-3 bursting was broadly similar across the neural preparations despite their differences in size and induction method.

A **duty cycle** is the fraction of a repeating cycle occupied by a defined active phase. Comparable duty cycles support a shared pattern, but slower fictive periods limit equivalence with intact movement. The reduced preparation exposes central activity without recreating every sensory, mechanical, or motivational condition of natural crawling.''','The overt contraction measurement used sucker release and attachment, while the fictive contraction proxy used DE-3 activity. Those measurements are related but not identical, so the result supports a motor-pattern comparison rather than complete behavioral identity.',DE3)
add('Phosphodiesterase inhibition can recruit slow bursting','CM12','CM12_1A','1(A)','Theophylline, saline and extracellular-action control recordings.', '''Crisp and colleagues tested whether cyclic AMP signaling could contribute to dopamine-associated crawling. **Cyclic AMP**, or cAMP, is an intracellular signaling molecule. A **phosphodiesterase** is an enzyme that breaks down cyclic nucleotides; inhibiting it can prolong their intracellular availability.

Bath application of 4.4 mM theophylline caused DE-3 bursting after approximately 10–20 min in isolated ganglia. A polar theophylline-related compound that blocked extracellular adenosine receptors without reproducing intracellular phosphodiesterase inhibition did not induce the same rhythm. Normal-saline recordings supplied the untreated comparison.

The control supports an intracellular contribution rather than attributing bursting simply to adenosine receptor blockade. It does not prove that theophylline acts exclusively through one enzyme or that dopamine uses an identical pathway. The measured endpoint is slow motor bursting, whose complete phase organization must be tested separately.''','A polar drug may cross membranes less readily than a related nonpolar compound. The control used this distinction to separate extracellular receptor effects from the intracellular effects being investigated.',DE3)
add('Elevating cyclic AMP does not identify a dopamine receptor','CM12','CM12_1B','1(B)','Measured burst periods and durations across experimental conditions.', '''Crisp and colleagues applied the phosphodiesterase inhibitor IBMX to leech neural tissue and measured cAMP using an enzyme immunoassay. An **immunoassay** uses molecular binding to quantify a target substance. This measurement checked whether the proposed intracellular signal actually increased after treatment.

After 30 min in 0.5 mM IBMX, extract cAMP increased from approximately 12.9 to 29.4 pmol per ml. IBMX and dopamine could each support DE-3 bursts with periods near 20 s, and their coapplication did not abolish rhythmic bursting.

The biochemical and physiological results are consistent with a cAMP-associated route to rhythmicity. They do not directly identify a DA1-like receptor or prove that dopamine and IBMX converge on one molecular pathway. That receptor-based explanation remains a proposal requiring receptor-specific evidence in the relevant circuit cells.''','DA1-like signaling often involves increases in cAMP, but similarity of downstream effects is not a receptor-identification assay. The original paper explicitly separates possible common pathways from mechanisms that could operate in parallel.',DE3)
add('Persistent sodium entry contributes to induced bursting','CM12','CM12_2','2(A–C)','IBMX-induced bursts, riluzole blockade and washout recovery.', '''Crisp and colleagues tested IBMX-induced bursting with **riluzole**, a drug used to inhibit a persistent sodium-current component. A persistent current continues beyond the brief inward current associated with an action potential. Sustained sodium entry can support a prolonged depolarization on which spikes occur.

Application of 200 μM riluzole stopped the rhythmic DE-3 bursts despite continued IBMX exposure. The preparations could still fire impulses, and washing out riluzole while retaining IBMX restored bursting. The within-preparation recovery distinguishes rhythm disruption from irreversible loss of neuronal viability.

The result supports a sodium-dependent contribution to the induced timing mechanism. It does not directly measure the persistent current in an identified oscillator neuron or establish a channel gene. Pharmacological sensitivity and preserved spiking constrain the explanation without completing its molecular identification.''','Riluzole was applied at 200 μM. Continued action potentials after loss of repetitive bursting help separate excitability from the slower dynamics that generate a rhythm; pharmacology still cannot establish the responsible sodium-channel gene.',DE3)
add('Crawl-like bursting persists without normal calcium influx','CM12','CM12_1B','1(B)','Original comparison of induced burst timing across treatments.', '''Crisp and colleagues replaced extracellular calcium with an equimolar concentration of nickel or cobalt while testing theophylline-induced DE-3 bursting. Calcium entry normally participates in several membrane and synaptic processes. Ion substitution tested whether normal calcium influx was required for the observed rhythmic output.

Bursting persisted in saline with 1.8 mM nickel replacing 1.8 mM calcium. Example average cycle periods were approximately 20.4 s in calcium-containing saline and 22.3 s in nickel-containing saline. Burst durations also remained in a similar range.

These observations favor a timing contribution that can operate without normal calcium entry under the experimental treatment. They do not imply that calcium is unnecessary for every synapse or for natural crawling. Ion substitution alters several processes, and the result must remain specific to the drug-induced bursting tested in the isolated preparation.''','The comparative timing panel contextualizes the induced bursts, while the ion-replacement result is reported in the article text. The timing comparison does not independently test the ion-replacement condition.',DE3)
add('Potassium-current blockade changes the active fraction','CM12','CM12_1B','1(B)','Published burst-period and burst-duration comparison.', '''Crisp and colleagues tested **clotrimazole**, a blocker associated with intermediate-conductance calcium-dependent potassium channels. Potassium efflux generally opposes depolarization under these conditions. Removing an outward current can therefore alter how long an excitable cell remains active during a burst.

At 25 μM clotrimazole, DE-3 bursts occurred with cycle periods near 20 s, comparable to the other induction methods. Their duration increased to approximately 13.5 s, compared with approximately 5 s under dopamine or phosphodiesterase inhibition. The active fraction of the cycle was consequently much larger.

The result separates period from burst termination and supports an outward-current contribution to pattern shape. Clotrimazole can also affect sodium–potassium pump activity, so this experiment does not uniquely identify one potassium-channel subtype as the endogenous dopamine target. The channel account remains pharmacologically supported and incomplete.''','The sodium–potassium pump uses energy to maintain ionic gradients and can contribute an outward electrical effect. A drug that influences both a channel and the pump requires caution when assigning its entire physiological effect to one target.',DE3)
add('A slow rhythm can retain the wrong motor-cell phase','CM12','CM12_3','3(A–D)','Identified motor-cell activity during IBMX-induced bursting.', '''Crisp and colleagues recorded several identified motor cells while IBMX induced DE-3 bursts in isolated ganglia. This tested whether a drug that reproduced approximate crawl timing also reproduced the full crawl motor pattern. Simultaneous intracellular and motor-nerve recordings established relative phase within the same cycle.

The longitudinal excitor VE-4 depolarized with DE-3, while inhibitors DI-1 and VI-2 were hyperpolarized during those bursts. However, the circular excitor CV fired in phase with DE-3 under IBMX. During the usual dopamine-induced crawl pattern, CV instead participates in the opposing elongation phase.

Rhythm generation and correct motor patterning are separable. Reproducing a slow period does not establish that every muscle group will be activated appropriately. The mismatch supports additional dopamine actions beyond the phosphodiesterase-sensitive timing route, without identifying all of the responsible receptor subtypes or interneurons.''','If circular and longitudinal excitors fire together, their usual antagonistic mechanical actions can conflict. The preparation records neural outputs rather than intact muscle deformation, so the predicted movement consequence remains distinct from the measured phase error.',DE3)
add('Dopamine reshapes rebound after inhibition','CM12','CM12_4AB','4(A,B)','Current pulses and rebound responses in CV and AE.', '''Crisp and colleagues applied hyperpolarizing current pulses to CV and AE motor neurons before and during dopamine exposure. **Post-inhibitory rebound** is increased depolarization or firing after an inhibitory influence ends. An **afterhyperpolarization** is a more negative voltage following activity or a rebound response.

At 75 μM dopamine, CV had a larger rebound peak but a shorter rebound duration and enhanced afterhyperpolarization. AE also had a shortened rebound response. Current pulses of −1 nA for 500 ms provided a defined perturbation rather than relying on variable network inhibition.

The effect shows that peak voltage, response duration, and subsequent inhibition can change differently under one modulator. It does not support a simple rule that dopamine uniformly increases excitability. The channel processes responsible for each component were not isolated directly by these current-pulse measurements.''','A sharper but shorter rebound can change when a motor neuron fires without increasing its total activity. The experiment measures the cell’s response to a controlled input, while its actual phase in the network also depends on synaptic drive.',DE3)
add('Dopamine can promote pattern while reducing excitability','CM12','CM12_5','5(A–D)','Motor-cell firing responses and original current–frequency plots.', '''Crisp and colleagues injected depolarizing current into CV and AE and compared firing before and during dopamine exposure. **Excitability** here refers to the relationship between injected current and the resulting discharge. Testing that relationship separates direct cellular responsiveness from the presence of a network rhythm.

For a +1 nA input, average AE firing fell from approximately 18 to 12.6 Hz during dopamine; average CV firing fell from approximately 41.2 to 23 Hz. Theophylline did not reproduce the same reduction and instead increased resting discharge in the tested cells.

Dopamine can favor a patterned output while reducing the response of particular motor neurons to steady excitation. Timing, phase, and input responsiveness are different properties. The mismatch with theophylline supports multiple modulatory effects, but does not prove which receptor or conductance accounts for each difference.''','The traces in the original figure represent individual examples, while the text here uses the article’s average current-response values. The distinction prevents an illustrative trace from being treated as the population average.',DE3)
add('A descending neuron reaches distributed crawl circuitry','P12','P12_2B','2(B)','Confocal anatomy of the identified descending R3b-1 neuron.', '''Puhl and colleagues identified the paired descending neuron R3b-1 within the subesophageal ganglion. A **descending projection** carries signals from an anterior neural region toward more posterior circuitry. Neurobiotin filling and confocal imaging established the cell’s soma and arborization in the cephalic region.

R3b-1 has an axon that extends through the nerve cord, with branches in segmental ganglia. Some processes cross the midline, providing anatomical access to both sides. The published cephalic and segmental images preserve 100 μm scale bars.

The anatomy permits one cell to influence many local motor circuits, but a visible arbor is not proof of a synapse onto every nearby neuron. Its functional role must be tested with recording and perturbation. The descending arrangement also does not make R3b-1 the sole possible source of local crawl rhythmicity.''','The subesophageal ganglion is a fused cephalic neural region below the esophagus. The bilateral pairing matters because manipulating one cell without excluding its counterpart could leave a parallel source of descending influence.')
add('R3b-1 activity controls coordination in a defined state','P12','P12_4CF','4(C–H)','Depolarization and hyperpolarization with multisegment recordings.', '''Puhl and colleagues excluded the contralateral R3b-1 influence and recorded DE-3 output from several segments while manipulating the remaining cell. Dopamine biased the preparation toward crawling. This design tested one descending neuron’s effect on a distributed rhythm under specified conditions.

A +3 nA current increased R3b-1 spiking and converted irregular segmental bursting into coordinated fictive crawling. In one example, periods changed from roughly 27–29 s to approximately 10 s across the recording sites. A −4 nA current disrupted their common period and crawl-specific coordination, even when some local bursts continued.

R3b-1 activity was sufficient and necessary for coordinated output in the tested preparation and state. Local burst persistence prevents equating disruption of coordination with complete abolition of every segmental oscillator. The result is a conditional causal role, not a universal claim that this cell is required for all rhythms under all conditions.''','The extracellular connective recording verified changes in R3b-1 spiking during intracellular current injection. This control separates an intended voltage manipulation from evidence that the neuron’s propagated activity actually changed.')
add('A command signal must interact with segmental networks','P12','P12_6','6(A–C)','Regional synaptic blockade during descending-neuron stimulation.', '''Puhl and colleagues tested whether R3b-1 commands coordination directly or must interact with local segmental circuits. High-magnesium, low-calcium saline blocked chemical transmission in a restricted region while the axon remained capable of conducting. Motor recordings sampled ganglia within and outside the blocked region.

The synaptic blockade altered the coordinated pattern. Depolarizing R3b-1 did not restore ordinary crawl coordination simply by sending more descending spikes through the affected region. Appropriate rhythmic activity could remain elsewhere without the expected full intersegmental organization.

A **permissive signal** enables a local network to operate rather than specifying every event independently. The results support cooperation between descending input and segmental circuitry. Regional saline blockade affects many synapses, so it does not identify a single local relay or prove that every coordinating interaction is chemical.''','In this experiment, preserving axonal conduction while reducing synaptic transmission made it possible to distinguish passage of the command neuron’s signal from successful interaction with the circuits that organize the rhythm.')
add('A motor follower tests a specific descending connection','P12','P12_7','7(A–C)','R3b-1 stimulation and the response of circular excitor CV.', '''Puhl and colleagues recorded R3b-1 together with CV while applying regional synaptic blockade and stimulating the descending cell. CV is a crawl-related circular-muscle excitor. A defined presynaptic spike train permits testing a more specific connection than simply observing that both cells oscillate during crawling.

R3b-1 stimulation produced excitatory responses in CV consistent with a synaptic follower relationship. The published expanded recording retains the relationship between the descending spike and the subsequent motor-cell potential. Comparing the response under reduced-transmission conditions supplied evidence about the connecting route.

This supports a functional pathway from descending input to a motor output associated with elongation. It does not establish that R3b-1 directly controls every crawl neuron or that this connection alone generates the entire rhythm. The broader pattern still depends on interactions among local circuits and motor pathways.''','An excitatory postsynaptic potential is a voltage change that promotes firing in a receiving neuron. A reproducible response to a defined presynaptic event is stronger evidence for connectivity than a shared phase during a long motor episode.')
add('Short ganglion chains can coordinate without the brain','K22','K22_3','3(A–D)','Measured chain activity and scrambled-recording comparisons.', '''Kearney and colleagues studied dopamine-induced crawling in isolated chains of three ganglia. This preparation lacked both the cephalic brain and the moving peripheral body. Motor-nerve recordings tested whether local circuits could express a coordinated sequence through their remaining central connections.

DE-3 bursts followed a consistent order through the chain, with a median phase lag near 0.12 of a cycle per segment. Combining recordings from different chains in a scrambled control eliminated the strong temporal relationship. The coordination therefore could not be explained simply by independent rhythms of similar average frequency.

The result establishes central coordination without a descending command in this reduced context. It qualifies broader necessity claims based on different preparations. The intact animal and a short, dopamine-treated chain need not use identical coordination mechanisms, and additional descending or sensory input may improve speed and flexibility. ''','A scrambled comparison preserves individual recordings but removes their shared experimental timing. It tests whether a temporal relationship depends on the cells having been active together, rather than on common average properties.',DE3)
add('Electron microscopy locates inputs onto a motor neuron','A21','A21_6','6(a–d)','Electron-microscopic neurites and synaptic contacts onto DE-3.', '''Ashaber and colleagues combined voltage-sensitive imaging with serial blockface electron microscopy in the same leech ganglion. **Electron microscopy** resolves fine cellular structure using electron-based imaging. The same-tissue design connects functional identity with an anatomical reconstruction rather than comparing unrelated specimens.

They reconstructed the DE-3 motor neuron and identified 531 input synapses. Presynaptic partners could be traced toward their somata, linking contacts to candidate neurons. Distinct terminal appearances were examined, and transmission electron microscopy from another ganglion helped check the interpretation of small vesicles.

A **synapse** is a specialized communication site between neurons. Structural contacts establish where anatomical input can reach DE-3, but their appearance alone does not identify transmitter, receptor, sign, or functional strength. Those assignments require physiological or independently established cell information.''','Serial blockface imaging repeatedly images and removes a thin surface layer from an embedded sample. The published electron micrographs preserve micrometer scale bars and distinguish an actual contact from a mere crossing of reconstructed processes.',DE3)
add('Behavior-specific inputs remain distributed along DE-3','A21','A21_10','10(a–e)','Original anatomical distribution of synapses and behavior-associated inputs.', '''Ashaber and colleagues matched presynaptic neurons in the anatomical reconstruction with their voltage-sensitive activity during fictive swimming and crawling. They then asked whether inputs associated with different behaviors occupied distinct regions of the shared DE-3 arbor. This combines functional participation with measured synapse locations.

Behavior-associated inputs were distributed across the motor neuron rather than segregated into separate large branches for swimming and crawling. Likewise, excitatory and inhibitory input categories did not form the simple large-scale spatial separation expected from a compartmentalized account. The activity and anatomical measurements came from the same ganglion.

A multifunctional motor neuron receives convergent inputs whose active relationships change with behavior. Distribution along the arbor does not mean that every synapse has equal effect or that local dendritic interactions are absent. The anatomy constrains spatial explanations while leaving state-dependent synaptic operation and conductance mechanisms for further testing.''','The functional association was based on measured activity during the elicited patterns, not a new simulated motor circuit. Anatomical input count is also not identical to physiological synaptic strength, so the two kinds of evidence remain distinct.')
assert len(slides)==44,len(slides)
for s in slides:
 n=len(re.sub(r'\*\*|_', '', ' '.join(s['body'])).split());assert 90<=n<=170,(s['title'],n)
take={'cite':'Kristan & Calabrese (1976); Briggman & Kristan (2006); Crisp et al. (2012); Kearney et al. (2022)','refs':[ref(k)for k in ['KC76','YN99','B06','PM08','CM12','P12','A21','K22']], 'items':[
{'lead':'Central generation.','text':'The isolated cord produces a swim-like motor rhythm after brief stimulation, establishing central rhythmic capability without requiring a repeating peripheral stimulus.'},
{'lead':'Feedback and coordination.','text':'Sensory input adjusts phase, burst shape and body-wave timing; central rhythm generation does not make feedback unnecessary for normal locomotion.'},
{'lead':'Shared neurons, different patterns.','text':'Swimming and crawling reorganize overlapping neuronal populations: longitudinal excitors alternate in swimming but cooperate during crawl shortening.'},
{'lead':'Timing differs from patterning.','text':'Drug-induced slow bursting can retain an incorrect circular-muscle phase, so matching period alone does not establish the complete crawl motor program.'},
{'lead':'Modulation changes circuit state.','text':'Serotonin promotes swim expression; dopamine promotes crawling through effects that include rhythm availability, motor-cell phase and altered membrane responsiveness.'},
{'lead':'Causality depends on preparation.','text':'Descending R3b-1 controls coordination in defined whole-cord conditions, while short ganglion chains can coordinate centrally without the brain; anatomical input maps do not alone establish synaptic function.'}]}
spec={'lecture':6,'theme':'cerulean-pearl','content_slides':44,'title_refs':[ref('A21')],'title_image':fig('A21','A21_animal','1','Medicinal leech Hirudo verbana; original 1 cm scale bar.'),'slides':slides,'takeaways':take}
(ROOT/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n');print('Wrote 44 content slides with three paragraphs and full references.')
