"""Lecture 23: experimental evidence and original published article panels."""
import json,re
from pathlib import Path
H=Path(__file__).resolve().parent;R=H.parents[1];crops=json.loads((H/'crops.json').read_text());extras=json.loads((H/'extra-crops.json').read_text());REF={}
for k in {x['paper'] for x in crops+extras}:
 d=json.loads((H/'sources'/(k+'-crossref.json')).read_text())
 def person(a):return a['family']+' '+''.join(w[0] for w in a.get('given','').replace('-',' ').split())
 title=re.sub('<[^>]+>','',d['title'][0]).rstrip('.')
 article=d.get('page') or d.get('article-number') or {'birdmap14':'11975','turtlepulse25':'jeb251243','uploaded_pone':'e0347104'}.get(k,'')
 REF[k]=f"{', '.join(person(a) for a in d['author'])} ({d['published']['date-parts'][0][0]}). {title}. {d['container-title'][0]} {d['volume']}"+(f"({d['issue']})" if d.get('issue')else '')+f":{article}. https://doi.org/{d['DOI']}"
slides=[]
def fig(x):return {'kind':'article','path':x['out'],'caption':x['caption'],'source_url':x['source_url']}
def short(k):
 d=json.loads((H/'sources'/(k+'-crossref.json')).read_text());a=d['author'];author=a[0]['family']+(' & '+a[1]['family'] if len(a)==2 else ' et al.' if len(a)>2 else '');return f"{author} ({d['published']['date-parts'][0][0]})"
def add(title,a,b,c,note,also=(),anatomy=None):
 row=crops[len(slides)];keys=list(dict.fromkeys([row['paper'],*also]));body=[a,b,c]
 sl={'title':title,'layout':'figure-right','figure_width':5.2,'body':body,'transcript':[[re.sub(r'\*\*|_','',a),[note]],re.sub(r'\*\*|_','',b),re.sub(r'\*\*|_','',c)],'cite':'; '.join(short(k)for k in keys),'refs':[REF[k]for k in keys],'figure':fig(row)}
 if anatomy is not None:
  x=extras[anatomy];sl.update(layout='figures-right',primary_figure_height=2.6 if anatomy==2 else 3.15,figures=[fig(row),fig(x)]);sl.pop('figure')
  if x['paper'] not in keys:sl['refs'].append(REF[x['paper']]);sl['cite']+='; '+short(x['paper'])
 slides.append(sl)

add('Hatchling turtles orient to the magnetic field',
'**Magnetoreception** is the detection of magnetic fields. Loggerhead sea turtles, _Caretta caretta_, leave their nesting beach before navigating offshore. Lohmann tested whether newly emerged hatchlings could derive a swimming direction from Earth-strength magnetic fields when visible landmarks were unavailable.',
'Hatchlings swam in a harness connected to a freely rotating lever. A rheostat converted lever position into an electrical record of heading. After exposure to a dim eastern light, turtles swam for 90–180 min in complete darkness under either the natural field or an experimentally reversed horizontal component.',
'The natural-field group preferred 42°, whereas the reversed-field group preferred 196°. The field manipulation therefore changed the directional response. This establishes magnetic influence on orientation in this preparation; it does not identify a receptor, prove an innate eastward preference, or reproduce an entire ocean crossing.',
'A compass provides direction rather than location. The light exposure preceding the dark test is part of the preparation, so the result cannot be interpreted as magnetic orientation without any previous visual experience.')
add('A tether separates heading from ocean transport',
'Lohmann’s **orientation arena** was a 1.02-m-diameter inverted satellite dish surrounded by a 130-cm magnetic coil. A harness encircled the carapace without preventing swimming. The turtle could pull the lever through a full circle while remaining inside a controlled water-filled preparation.',
'The recording system was calibrated against known directions and resolved heading within 15°. Investigators distinguished circling from oriented swimming, defined as remaining within a 90° sector for at least 3 min. This definition selected periods in which the animal maintained a course rather than repeatedly traversing every direction.',
'The experiment measured attempted swimming direction, not geographical displacement or migratory speed. Waves, ocean currents and distant landmarks were absent. Its strength is control over a single sensory variable; its limitation is that successful direction selection in an arena does not establish how multiple cues guide free-ranging turtles.',
'The harness and tracking system are a behavioral readout. They do not record magnetic receptor activity, and they do not reveal whether the turtle obtains magnetic information from its eyes, head or another tissue.')
add('Field reversal changes the preferred swimming course',
'The coil reversed the horizontal magnetic component while leaving the vertical component unchanged. The imposed field opposed the natural horizontal field, so magnetic north shifted by 180°. The reversed horizontal field ranged from 0.23 to 0.26 Oe within the swimming zone; the natural horizontal field was 0.26 Oe.',
'Both groups received the same initial eastern light and were subsequently tested in darkness. Preferred headings changed from 42° in the natural field to 196° after reversal, a reported shift of 154°. Orientation under reversal was more dispersed, so the behavioral response was not a perfectly rigid copy of the imposed rotation.',
'These controls weaken an explanation based solely on a fixed room direction. The experiment demonstrates sensitivity to the manipulated field geometry. Because only the horizontal component was reversed, it cannot by itself distinguish a polarity compass from a compass that depends on the inclination of the field axis.',
'Oersted is the magnetic field unit retained in this historical paper. Keep the reported units attached to their original measurements; the experiment compared controlled field configurations rather than testing responses to a modern everyday magnetic compass.')
add('Independent field components isolate inclination',
'**Magnetic inclination** is the angle at which field lines intersect the horizontal surface. Lohmann and Lohmann varied inclination while keeping total field strength approximately constant. Their preparation therefore separated the directional slope of the field from **intensity**, the magnitude of the magnetic field.',
'Two orthogonal coil systems controlled the horizontal and vertical components independently. Hatchlings swam in a 1.22-m arena, and a digital encoder recorded heading to the nearest 1.4° every 10 s. The measured total field strength was 0.044–0.045 mT across the experimental conditions.',
'Computers and power supplies remained active in every treatment and were located in an adjacent room. Similar sounds and vibrations were therefore present regardless of inclination. A change in behavior under these conditions can be attributed more specifically to field geometry than to equipment switching or a correlated change in field magnitude.',
'The total field is composed of horizontal and vertical components. Changing their relative contribution changes inclination, whereas the controlled overall magnitude prevents intensity from supplying the explanation for the treatment difference.')
add('Inclination changes evoke different turtle headings',
'Hatchlings first swam toward an eastern light for 10 min. After the light was extinguished, investigators changed inclination, allowed 3 min for adjustment, and recorded swimming for 5 min in darkness. Each animal experienced only one inclination treatment, avoiding repeated exposure to an unfamiliar sequence of fields.',
'At the local inclination of 57°, turtles preferred 90°, approximately east. At 60°, they preferred 200°, south-southwest. At 30°, their preferred heading was 57°, northeast. Fields inclined at 75°, 45° or 15° did not produce a consistent group direction under the same test procedure.',
'The contrast between 57° and 60° establishes discrimination between nearby inclination conditions while field strength remains constant. Different headings need not mean that every angle is assigned a geographical coordinate. The absence of a preferred group direction in some treatments does not establish an inability to detect those fields.',
'The experiment distinguishes sensory detection from the expression of an oriented motor response. A detectable field can fail to trigger a shared heading, especially when it lacks the ecological meaning of a field encountered near a route boundary.')
add('Magnetic slope can mark dangerous gyre boundaries',
'An **isoclinic** is a line connecting locations with the same magnetic inclination. The published North Atlantic map places inclination values alongside currents followed by young loggerheads. The northern gyre boundary approaches the region where the Gulf Stream divides and colder water lies farther north.',
'Turtles exposed to 60° inclination swam south-southwest, whereas those exposed to 30° swam northeast. These directions are consistent with movements away from the northern and southern extremes of the gyre. The controlled experiment established inclination-dependent behavior; the geographical interpretation connects that behavior to plausible survival consequences.',
'The authors proposed that inclination could contribute to approximate latitude detection and recognition of nesting regions. Those are hypotheses extending beyond the tethered hatchling experiment. The study did not track adult homing, isolate a magnetic memory of a natal beach, or establish a complete two-dimensional navigational map.',
'A latitude-related signal is not automatically a unique address. The same inclination can occur at multiple locations, so positional use requires an appropriate geographical range, additional magnetic parameters or information from other sensory systems.')
add('Regional magnetic signatures trigger route changes',
'A **magnetic signature** is the combination of magnetic parameters characteristic of a location. Lohmann and colleagues replicated three fields from the North Atlantic migratory route. Unlike experiments that changed inclination alone, these treatments used combinations of inclination and intensity that naturally occur in widely separated oceanic regions.',
'Hatchlings tethered inside a computerized coil system oriented east-southeast in the northern Florida field, approximately south in the northeastern gyre field, and west-northwest in the southern gyre field. The tracking apparatus recorded heading while the animals remained physically in the same laboratory arena.',
'The field-dependent changes are consistent with entering favorable currents and avoiding displacement beyond the gyre. They establish recognition of regional magnetic conditions with different motor responses. They do not establish a continuous representation of every position in the Atlantic or prove that each turtle knows its location relative to a destination.',
'The experimental variable was the regional magnetic field rather than physical travel. The hatchlings did not encounter different water masses, coastlines or currents during testing, so those cues cannot account for the between-treatment headings.')
add('Early route responses need not require prior travel',
'The hatchlings in the regional-field experiment had never entered the ocean. Their different headings therefore did not require previous experience of the tested oceanic regions. A directional response could be expressed upon first exposure to a magnetic signature encountered naturally near a critical route boundary.',
'An inherited large-scale map is one possible interpretation. A simpler alternative is a set of field-triggered instructions: swim south under one signature and west-northwest under another. Both accounts predict appropriate local heading changes, but only the first requires a more general representation of geographical position.',
'The laboratory responses distinguish regional fields without resolving these alternatives. The authors also emphasized that more sophisticated navigation could develop as turtles mature. Experience-dependent magnetic learning and early boundary responses can coexist; a response in an inexperienced hatchling does not establish that every later navigational decision is genetically specified.',
'A map sense determines something about position, whereas a compass sets a heading. The regional-field assay requires a location-dependent change in compass direction, but it does not reveal how the brain represents the field or chooses the resulting action.')
add('Juvenile turtles learn rewarded magnetic signatures',
'**Associative learning** links a sensory cue with an outcome. Goforth and colleagues conditioned captive juvenile loggerheads for 2 months using two replicated geographical fields. Animals spent equal amounts of time in the fields, but food was delivered only in one assigned magnetic signature.',
'The first pairing represented the Gulf of Mexico and New Hampshire. Reward assignments were counterbalanced: either field could predict food. This control separates recognition of a particular magnetic signature from a universal preference for a northern field, southern field or fixed condition of the coil apparatus.',
'After conditioning, turtles were tested without food. Their responses were stronger in the field previously paired with feeding. Magnetic information therefore acquired learned behavioral significance. The experiment supports learning of a magnetic signature; it does not show that a turtle navigated back to the corresponding real-world location.',
'Counterbalancing means that the relationship between a field and its reward differs between animals. A field that predicts food for one turtle predicts no food for another, allowing the learned association to be separated from an intrinsic response to that field.')
add('Food anticipation provides a compass-free map assay',
'The conditioned response was **turtle dancing**, a food-anticipatory pattern involving vertical body tilt, the head near or above water, mouth opening and alternating front-flipper movement. Investigators scored the duration of this behavior from video recordings while turtles experienced a magnetic field without receiving food.',
'Observers were blind to magnetic treatment. Turtles danced more in the rewarded signature than in the unrewarded signature after equivalent exposure to both during training. The measured output was time spent in a defined behavioral state rather than the direction of swimming toward a remembered destination.',
'This assay tests discrimination of location-related magnetic cues without requiring a magnetic compass heading. That separation permits selective tests of a map mechanism. A food-anticipatory response nevertheless remains an indirect behavioral measure: it does not identify a receptor cell or record a magnetic signal in a particular brain pathway.',
'Blind scoring reduces the chance that knowledge of the field influences behavioral classification. Testing without food also prevents the animal from using food odor or the immediate presence of a feeding reward to distinguish the two fields.')
add('Magnetic learning extends beyond one pair of fields',
'Additional cohorts learned pairs representing Cuba and Delaware, Florida and Maine, and locations elsewhere in the western Atlantic. These pairings differed in geographical and magnetic separation. Recognition therefore was not restricted to the first Gulf of Mexico–New Hampshire contrast used to establish the assay.',
'Turtles first conditioned with the Florida–Maine pair were subsequently conditioned with a second pair representing a second set of magnetic signatures. They also discriminated the rewarded and unrewarded signatures in that second pairing. The same animals could acquire an additional association after the first training period.',
'The result supports flexibility in magnetic learning rather than a single fixed regional response. It does not establish how many signatures can be stored simultaneously, whether the first association survives every later training episode, or whether a learned field alone specifies the direction and distance to a natural feeding site.',
'The evidence concerns acquisition under controlled reinforcement. A laboratory capacity to learn multiple signatures is compatible with natural return to different feeding areas, but the behavioral experiment does not directly document such a journey.')
add('A learned magnetic association persists for months',
'The Gulf of Mexico–New Hampshire cohort was tested again 4 months after initial conditioning. No conditioning to those two fields occurred during the intervening period. The follow-up therefore assessed persistence of the association rather than immediate responses after another reinforced training session.',
'Turtles continued to express more food-anticipatory behavior in their originally rewarded field. Magnetic signature information can remain behaviorally available for several months. Retention was assessed through the same compass-free discrimination task used after the initial 2-month conditioning period.',
'The result establishes a duration of memory under the tested captive conditions. It does not identify the neural storage site, measure the maximum lifetime of the association, or demonstrate retention across the many years separating a hatchling’s departure from an adult turtle’s return to a nesting region.',
'The learned response can persist without immediate reinforcement, but its expression still depends on the animal’s motivational and behavioral state. The experiment measures an available association through food anticipation, not an isolated physical trace of memory in neural tissue.')
add('Cue mixing tests what defines a learned signature',
'Inclination and intensity varied together during conditioning. To determine whether either parameter alone could explain recognition, Goforth and colleagues constructed **mismatched fields** that combined the inclination of one learned field with the intensity of the other. These combinations separated features that normally occurred as a pair.',
'Turtles were tested in the rewarded field, the unrewarded field and the two mismatched combinations. The manipulation retained one rewarded component while changing the other. It therefore tested whether a familiar inclination or a familiar intensity was sufficient to evoke the learned food-anticipatory response.',
'A signature can function as a compound cue rather than a single coordinate. This experimental design addresses the information used for discrimination, without requiring assumptions about a complete geographical map. It does not specify whether inclination and intensity are detected by one receptor population or are combined later in the nervous system.',
'The mismatched combinations were designed from the trained fields rather than from an animal’s physical displacement. Their purpose was to isolate the contribution of each magnetic parameter to recognition of the rewarded condition.')
add('Recognition requires the trained cue combination',
'Turtles responded more strongly to the rewarded signature than to either mismatched combination. Neither the rewarded inclination paired with the wrong intensity nor the rewarded intensity paired with the wrong inclination produced the response expected from the complete trained field.',
'The mismatch responses resembled those to the unrewarded field. The result supports joint use of inclination and intensity in this task. It does not mean that animals cannot detect either parameter individually; it means that one familiar component was insufficient to identify the rewarded compound under the tested conditions.',
'The distinction separates sensory discrimination from learned decision rules. An animal may detect several field properties but respond only when their combination matches a stored association. The experiment leaves unresolved whether that comparison occurs within peripheral transduction, sensory pathways, memory circuits or the selection of a food-anticipatory action.',
'The response criterion is learned recognition. The field measurements define the physical stimuli, while behavioral duration reports whether a stimulus has acquired reward-related meaning; neither measurement records the intermediate neural computation.')
add('Radiofrequency disruption separates two turtle tasks',
'**Radiofrequency fields** are rapidly oscillating electromagnetic fields. Goforth and colleagues used broadband magnetic noise spanning 0.1–10 MHz to compare a learned map-only assay with a hatchling orientation task requiring map and compass information. The same class of perturbation was tested against different behavioral outputs.',
'The learned rewarded-field response persisted with radiofrequency exposure. In contrast, hatchlings exposed to the Cape Verde signature lost their consistent group heading under the noise treatment. Without noise, their reported preferred direction was 293.1°, approximately westward; with noise, the group no longer maintained a shared direction.',
'The dissociation is consistent with different mechanisms contributing to map and compass behavior. It does not establish the molecular identity of either mechanism. The tasks also used different developmental stages and preparations, so the behavioral comparison cannot be treated as a direct recording of two receptors in the same animal.',
'A negative disruption result must be limited to the applied exposure. Persistence of map discrimination under 0.1–10 MHz noise does not prove that every possible oscillating field is ineffective, and compass disruption alone does not identify cryptochrome in turtles.')
add('A learned map response enables a magnetic-pulse test',
'Mackiewicz and colleagues conditioned young loggerheads with signatures representing Turks and Caicos and Haiti. Animals learned which field predicted food, with the rewarded location counterbalanced. Testing again quantified turtle dancing rather than a compass heading, preserving the separation between positional cue recognition and directed swimming.',
'Conditioning alternated rewarded and unrewarded sessions over 2 months. Turtles received food 5–15 min after the field changed during rewarded sessions. Initial tests without food confirmed greater responding in the rewarded field before the magnetic-pulse treatments were introduced.',
'A **magnetic pulse** is a strong, brief field intended to alter magnetization in iron-based candidate receptors. The task provides an opportunity to perturb a learned map response without requiring compass use. The experiment tests a mechanistic prediction; it does not begin with an anatomically identified turtle magnetoreceptor.',
'Magnetite is an iron oxide that can carry a magnetic moment. A particle-based transduction hypothesis predicts that remagnetization can disturb a sensory signal, but a behavioral pulse effect is not itself a microscopic identification of such a particle.',also=('turtle25',))
add('Sham handling controls the pulse experiment',
'Turtles were assessed after no-pulse, sham-pulse and actual-pulse treatments. Sham animals were handled in the magnetizer without receiving a pulse. The actual treatment lasted 5 ms and reached a maximum intensity of 85 mT, far stronger than the Earth-strength fields used for ordinary magnetic discrimination.',
'Sham and actual treatments were followed by at least 12 h of overnight recovery before testing. Controls were completed before the pulse treatment to prevent a previous pulse from contaminating control behavior. The order of the two control conditions was randomized, and observers scoring video were blind to treatment.',
'These precautions separate pulse exposure from much of the handling disturbance. The fixed placement of the pulse treatment after the controls remains a design limitation because treatment and sequence are not fully independent. The initial conditioning result establishes a measurable learned response against which the subsequent perturbation can be assessed.',
'A sham control reproduces the nonmagnetic components of an intervention. It cannot remove every conceivable effect of the actual pulse, but it tests whether placement in the apparatus and handling alone account for the change in behavior.')
add('A strong pulse weakens learned field recognition',
'After a magnetic pulse, turtles spent less time dancing in their rewarded field relative to the no-pulse condition. Sham handling did not cause the same reduction. Pulse directions parallel and antiparallel to the horizontal Earth field did not produce distinguishable responses in this preparation and were considered together.',
'The result is consistent with disturbance of a particle-based map mechanism. A brief pulse could alter the arrangement or magnetic moments of magnetite-containing structures, whereas it is not expected to leave the same persistent change in a radical-pair reaction. These are mechanistic predictions used to interpret the behavioral effect.',
'The study did not locate magnetite-bearing receptor cells or establish their connection to a turtle sensory nerve. It also did not identify the ion channel through which a particle might affect membrane voltage. Pulse sensitivity therefore supports a candidate class of mechanism while leaving the actual transduction pathway unresolved.',
'The map-only task is important because reduced directional swimming could reflect either compass impairment or failed location recognition. Here the measured change concerns a learned magnetic discrimination response rather than the ability to maintain a bearing.',also=('turtle25',))
add('Coastal disorientation can involve competing light cues',
'McNally and colleagues examined loggerhead nesting records from Pinellas County, Florida. Their study mapped nesting beaches alongside developed shorelines and classified hatchling disorientation events. This field context concerns the initial movement from nest to sea rather than the controlled offshore magnetic-compass preparations.',
'Across the recorded nests, disorientation occurred in 35.18%, and roughly 30.48% of hatchlings from affected nests were classified as disoriented. The authors evaluated shoreline context, nest characteristics and spatial patterns. These observational measures document a substantial problem at the transition between terrestrial emergence and marine migration.',
'The study did not manipulate magnetic fields or measure a magnetoreceptor. Artificial light can compete with orientation cues, but disorientation on a developed beach is not evidence that magnetic sensing has failed. Laboratory demonstrations of a magnetic compass must therefore remain distinct from explanations of every natural orientation error.',
'Disorientation refers to hatchlings failing to proceed appropriately toward the ocean. The field records describe an ecological outcome influenced by multiple cues; their observational associations cannot establish a specific neural or magnetic causal mechanism.')
add('European robins express a magnetic migratory heading',
'European robins, _Erithacus rubecula_, display **migratory restlessness**, directional activity expressed during the season when they would normally migrate. Wiltschko and Wiltschko used the frequency of perch activation in circular cages to measure preferred direction without requiring birds to undertake a free flight.',
'In spring, robins tested in the local field preferred 29°, north-northeast. The historical study reported a field strength of 0.46 gauss and an inclination of +66°. The behavioral readout therefore related a seasonal directional tendency to a controlled geomagnetic configuration.',
'The experiment concerns a compass because it measures direction rather than a location-dependent correction toward a distant target. Perch activation provides an orientation measure, not a record of retinal activity. The result does not establish that the same field response controls every part of navigation during natural migration.',
'Migratory state supplies the behavioral context. A sensory compass can guide different seasonal directions, so a spring northerly preference is an interaction between magnetic direction information and the animal’s current migratory program.')
add('The robin compass follows inclination rather than polarity',
'A **polarity compass** distinguishes the two directed ends of a magnetic vector. An **inclination compass** uses the axial slope of field lines relative to the horizontal or gravity. Wiltschko and Wiltschko reversed individual field components and then reversed both to distinguish these alternatives.',
'Reversing the horizontal component changed the preferred course from 29° to 240°. Reversing both horizontal and vertical components preserved the field axis despite reversing vector polarity. Robins then retained a northerly preference, which is incompatible with treating magnetic polarity alone as the directional cue.',
'The behavioral pattern supports an inclination-based compass. It does not reveal the receptor’s material composition or prove that a particular retinal molecule supplies the signal. The distinction is about the information encoded by the compass, whereas receptor identity requires additional anatomical, physiological or molecular evidence.',
'Field axis and field polarity are different properties. Reversing both components changes the direction of the vector while retaining the same undirected line in space, which is why the two compass hypotheses predict different behavioral outcomes.')
add('A horizontal field removes the robin directional preference',
'The historical experiments also used a field of 0.46 gauss with zero inclination. Its horizontal direction and total strength were maintained, but the field no longer had a downward or upward slope. This manipulation tested whether horizontal magnetic polarity was enough to guide a shared migratory preference.',
'Robins did not express a consistent direction under that horizontal condition. Together with the component-reversal experiments, this result supports use of inclination relative to the animal’s up–down reference. In the northern hemisphere, an inclined axis permits a distinction between poleward and equatorward directions.',
'Loss of directional preference does not establish loss of every magnetic sensation. Birds could detect the field but lack the information needed to resolve the relevant heading. The experiment therefore limits the directional code of the compass without locating a gravity comparator, magnetic receptor or specific brain circuit.',
'The conclusion depends on the pattern across several field configurations. A single disorientation treatment can have many explanations, whereas component reversal and preserved behavior after full polarity reversal constrain the information available to the animal.')
add('Cluster N is active during nocturnal vision',
'Mouritsen and colleagues used **activity-associated gene expression** to identify brain regions recruited during night vision. They measured ZENK, an immediate-early transcriptional marker whose expression changes with neuronal activation. Migratory garden warblers and European robins were compared with non-migratory zebra finches and canaries.',
'Birds were exposed to dim illumination approximating moonlight, 0.04 lux, or ordinary daytime room light. Brain sections revealed a dorsal forebrain region designated **Cluster N** with strong night-time expression in migrants. The anatomical preparation linked a defined group of forebrain regions to a controlled visual condition.',
'ZENK expression is an indirect activity measure integrated over time rather than an instantaneous spike recording. The experiment identifies a candidate processing region but does not establish magnetic selectivity. Night-time activity could reflect visual sensitivity, magnetic information, other orientation cues or several functions occurring together.',
'The authors collected brains after birds had been relatively still and awake, limiting movement-related expression. That control strengthens the association with the sensory condition without turning a gene-expression marker into proof of a magnetic receptor.')
add('Nocturnal activation differs across species and conditions',
'Cluster N expression was stronger during night vision in the migratory species than during daytime testing. Non-migratory zebra finches and canaries did not exhibit the same nocturnal increase. The comparison therefore connected the response to both illumination conditions and the tested species’ ecological specialization.',
'The dim-light condition was 0.04 lux, whereas daytime room illumination exceeded 275 lux. Investigators also minimized recent movement before collecting brain tissue. The published expression measurements compare sensory states while reducing the possibility that flight or gross locomotor activity alone produced the regional difference.',
'Species comparisons cannot establish that migration itself causes the expression pattern because species differ in many traits. The finding supports specialization for nocturnal sensory processing. It does not establish a universal absence of magnetic sensing in non-migratory birds or prove that Cluster N is dedicated exclusively to a magnetic compass.',
'A regional gene-expression difference provides an anatomical hypothesis that requires functional tests. A necessary pathway is established more directly when manipulating the region selectively changes the target behavior while suitable control behaviors remain available.',anatomy=1)
add('Covering the eyes suppresses Cluster N activation',
'To test dependence on visual input, Mouritsen and colleagues covered both eyes of European robins with light-tight caps during nocturnal testing. This manipulation prevented light from reaching the retina while retaining the general night-time context of the experiment. Control birds experienced the same dim-light period with uncovered eyes.',
'Cluster N activation fell markedly when both eyes were covered. The response therefore depends on input associated with vision rather than merely the time of night or an internal migratory state. The published histology pairs the anatomical signal with measurements of expression and observed behavior.',
'Eye covering blocks ordinary vision as well as any light-dependent magnetic process. It cannot by itself identify cryptochrome, prove magnetic coding or separate magnetic information from other dim-light visual signals. Its contribution is to place Cluster N within a visually dependent processing pathway that can be tested more selectively.',
'The retina is the light-sensitive tissue lining the eye. Removing retinal illumination changes many signals simultaneously, which is why eye occlusion is a pathway-dependence test rather than a molecularly selective magnetoreception experiment.',anatomy=1)
add('Cluster N lesions abolish magnetic compass orientation',
'Zapka and colleagues tested European robin orientation before and after bilateral chemical lesions of Cluster N. **Ibotenic acid**, the lesion agent, was injected locally; sham-operated birds underwent the corresponding procedure without the active injection. Subsequent tests followed at least 1 week of recovery.',
'Tests compared the natural magnetic field, a field with magnetic north rotated 120° anticlockwise, and an inverted vertical component. Sham-lesioned birds changed direction appropriately with the field manipulations. Cluster-N-lesioned birds failed to express coherent magnetic compass orientation across those conditions.',
'The intervention establishes that the damaged region is necessary for normal magnetic compass performance in this preparation. It does not establish that every neuron in Cluster N is magnetic, that the region is the peripheral receptor, or that the lesion identifies the molecular transduction mechanism generating its sensory input.',
'A regional lesion interrupts multiple cells and their local interactions. The behavioral loss localizes a necessary processing stage more strongly than gene expression alone, but it cannot assign magnetic computation to one identified cell type or synapse.',also=('cluster05',),anatomy=1)
add('Celestial orientation survives the visual-region lesion',
'Cluster-N-lesioned birds retained orientation under a stationary planetarium sky simulating local stars. Lesioned and sham-operated birds also oriented during natural sunset. These tests assessed whether the intervention had caused a general inability to move directionally or use visual orientation information.',
'The preserved celestial responses contrast with loss of magnetic compass orientation. The sunset response included a tendency toward the setting sun, so the authors considered the interaction between migratory direction and phototaxis. The star test supplied an additional orientation condition under controlled celestial information.',
'The controls support a relatively selective magnetic-compass deficit rather than complete blindness or loss of all orientation behavior. They do not prove that all aspects of night vision are intact. The lesion result must be interpreted within the tested behaviors rather than as proof that Cluster N serves only one sensory function.',
'Phototaxis is directed movement toward or away from light. A sunset response can contain both light attraction and compass information, so a preserved directional response is useful as a control without requiring that every component be magnetically mediated.',anatomy=1)
add('Trigeminal sections spare the robin magnetic compass',
'The **ophthalmic branch of the trigeminal nerve**, designated V1, carries sensory information from structures around the upper beak and head. Zapka and colleagues cut this branch bilaterally or performed sham surgery to test its necessity for the European robin’s magnetic compass.',
'Sham-operated birds preferred approximately 10° in the natural field and 245° after magnetic north was rotated. V1-sectioned birds preferred approximately 354° and 264°, respectively. Both groups therefore changed their headings with the experimentally rotated field despite the loss of this trigeminal input in one group.',
'The result means V1 is not necessary for the compass task under these conditions. It does not mean the nerve carries no magnetic information or has no role in navigation. Compass direction and location-related map information are different functions, and the experiment tested the former rather than a displacement correction.',
'A nerve-section experiment establishes necessity for the behavior actually tested. Preserved compass performance after V1 section cannot be generalized to every navigational problem, especially a task that requires the bird to recognize geographical displacement.')
add('Virtual displacement tests the bird magnetic map',
'Pakhomov and colleagues tested Eurasian reed warblers, _Acrocephalus scirpaceus_, in spring migration. **Virtual magnetic displacement** changes local magnetic parameters to those of another place while leaving the animal physically at its capture site. Celestial, olfactory and landmark information therefore remains associated with the original location.',
'The capture-site field had intensity 50,118 nT and inclination 70.1°. The replicated field from Zvenigorod, approximately 1,000 km east, had intensity 52,175 nT and inclination 71.2°. Declination also changed from +5.5° to +10.1°; **declination** is the angular difference between geographical and magnetic north.',
'Intact sensory pathways permit a response to this conflicting magnetic location cue. A heading change after virtual displacement can test map-based compensation more specifically than a simple compass rotation. The manipulation does not physically expose birds to a different habitat or demonstrate how a single magnetic parameter is decoded in isolation.',
'The coil changed several geographical field properties together. The experiment tests the combined magnetic signature, so it cannot assign the compensatory response solely to inclination, intensity or declination.',anatomy=5)
add('Trigeminal input is necessary for map compensation',
'After bilateral V1 section or sham surgery, reed warblers were exposed to the virtual displacement field. Sham-operated birds changed from a northeasterly capture-site course to approximately 323°, northwest, consistent with compensating for an eastward displacement relative to their breeding destinations.',
'V1-sectioned birds instead maintained a course near 34°, northeast, similar to their original direction. They remained directionally active but did not make the compensatory change. Preserved oriented behavior makes a complete failure of movement or all compass function an inadequate explanation of the result.',
'The experiment establishes a requirement for trigeminal input in this magnetic map task. It leaves the peripheral receptor unidentified. It also concerns reed warblers, whereas the preserved compass after V1 section was demonstrated in European robins; the complementary evidence should not be described as a single experiment on one species.',
'Map and compass functions can depend on different inputs. The loss of a location-dependent correction while a consistent heading remains available is a stronger distinction than disorientation alone, but it still does not reveal the nerve’s exact magnetic coding scheme.',also=('cluster09',),anatomy=5)
add('Electromagnetic shielding restores robin orientation',
'Engels and colleagues found that European robins in wooden huts on an urban campus failed to express their expected migratory direction. They added electrically connected, grounded aluminum screening to reduce ambient electromagnetic noise while leaving the static Earth field available.',
'The screening attenuated noise from about 50 kHz to at least 20 MHz by roughly two orders of magnitude. Birds then recovered seasonal magnetic orientation. Reported ambient noise had peak magnetic intensities of approximately 0.1–50 nT at individual frequencies, much smaller than the local static field of about 49,000 nT.',
'The intervention linked orientation performance to the electromagnetic environment. Screening alone changes more than one potential environmental variable, so the authors followed it with grounding and deliberate-noise controls. The result does not show that every urban orientation error is magnetic or establish a particular molecular receptor.',
'A static field remains approximately constant in time, whereas radiofrequency noise oscillates rapidly. The weak oscillating exposure can interfere with a sensory process even though its amplitude is far smaller than the static field that normally supplies compass information.')
add('Grounding reversibly changes the shielding effect',
'The aluminum screens lost much of their protective effect when disconnected from electrical ground. Engels and colleagues alternated tests of the same birds between grounded and ungrounded screened huts, while the experimenters evaluating orientation were unaware which hut carried which electrical condition.',
'Birds oriented toward their spring migratory direction in grounded huts but lacked a consistent direction in ungrounded huts. The accompanying field measurements documented the difference in electromagnetic noise rather than treating the presence of metal screening alone as a sufficient control.',
'The reversible manipulation strengthens the causal association between the screened electromagnetic environment and compass performance. It does not isolate one frequency or prove that magnetic rather than electric components of all exposures act through one identified molecule. Near-field electromagnetic measurements require attention to both components.',
'Grounding connects conductive screening to an electrical reference so that its effect on noise differs from an isolated metal enclosure. The behavioral comparison is tied to measured exposure conditions, not merely to the nominal construction of the huts.')
add('Reintroduced noise disrupts the recovered compass',
'Inside grounded screened huts, investigators deliberately introduced broadband electromagnetic noise from approximately 2 kHz to 9 MHz. Robins again became disoriented. The treatment therefore recreated the behavioral deficit in a preparation that otherwise supported normal magnetic orientation.',
'With the same electronics present but generator output reduced to its minimum, birds recovered their seasonal direction and responded to a 120° anticlockwise rotation of the static field. Separate bands near 20–450 kHz and 600 kHz–3 MHz also interfered with orientation in further tests.',
'The controls make the mere presence of a generator an inadequate explanation. The effects support an electromagnetic sensitivity relevant to compass processing, but broad disruption does not uniquely identify cryptochrome or specify how chemistry influences neuronal firing. Evidence for a candidate radical-pair mechanism requires independent molecular and anatomical tests.',
'The study measured behavioral direction and exposure spectra. It did not record a retinal ion channel or magnetic-sensitive neuron, so radiofrequency susceptibility constrains possible mechanisms without completing the transduction pathway.')
add('Retinal Cry4 expression varies with migratory season',
'**Cryptochromes** are flavoproteins, proteins containing a flavin cofactor, related to photolyases, proteins involved in light-dependent DNA repair. Günther and colleagues compared retinal cryptochrome messenger RNA, the transcript used to produce protein, across migratory and non-migratory seasons in European robins and domestic chickens.',
'Cry4 transcript abundance increased during spring and autumn migratory seasons in robins, whereas the same migratory-season increase was not observed in chickens. The study also measured 24-h expression profiles: Cry1 and Cry2 varied more strongly over the day than Cry4, which exhibited relatively weak circadian variation.',
'The expression pattern makes Cry4 a candidate relevant to nocturnal navigation rather than solely a strongly rhythmic clock transcript. Transcript abundance is not a direct measure of magnetic sensitivity, protein orientation or neural signaling. Seasonal expression can correlate with migratory physiology without establishing that Cry4 is necessary for a magnetic compass.',
'A circadian pattern is a roughly daily rhythm. A protein available across the night is compatible with a sensory role, but the expression experiment alone cannot separate that role from other physiological functions associated with the migratory season.',anatomy=2)
add('Cry4 staining localizes to photoreceptor outer segments',
'The **retina** contains light-sensitive photoreceptors, including cones and rods. A photoreceptor’s **outer segment** is the specialized compartment containing light-sensitive membrane structures. Günther and colleagues used immunohistochemistry, antibody-based protein localization, to examine where Cry4 occurs in robin retinal tissue.',
'Cry4 immunoreactivity was concentrated in photoreceptor outer segments and appeared across peripheral and central retinal regions. The authors compared the staining pattern in robins and chickens and used both monoclonal and polyclonal reagents rather than relying on one antibody preparation.',
'Localization places the candidate protein in a tissue compatible with a visually mediated magnetic process. It does not establish magnetic responses in those cells or prove that all detected Cry4 is correctly oriented for directional sensing. Fluorescence identifies the antibody’s target distribution, not the chemical reaction or electrical output of a magnetoreceptor.',
'Monoclonal antibodies recognize a selected antigenic target, whereas polyclonal preparations include several antibody populations. Agreement between independent reagents helps constrain a localization claim, provided that their specificity is tested rather than assumed.',anatomy=2)
add('Double staining identifies Cry4-positive cone classes',
'**Opsins** are light-sensitive receptor proteins that help distinguish photoreceptor classes. The study combined Cry4 staining with antibodies to iodopsin, ultraviolet opsin, blue opsin and rhodopsin. **Double staining** tests whether two molecular labels occupy the same cellular compartment rather than merely nearby tissue.',
'Cry4 signal overlapped iodopsin-positive outer segments, associated with long-wavelength single cones and double cones. It did not overlap the outer segments labeled by ultraviolet opsin, blue opsin or rhodopsin. Additional calbindin staining identified inner segments of double cones and supported the assignment of Cry4 to these cone classes.',
'The anatomical evidence narrows the candidate cellular location. It does not establish that these cones generate a magnetic signal, identify its downstream transmitter pathway or demonstrate a compass defect after selectively removing Cry4. Ordinary photoreceptor identity and a hypothesized magnetic role must remain experimentally separate.',
'Rhodopsin identifies rod photoreceptors in these comparisons. The absence of overlapping Cry4 signal in rod outer segments is a localization result, not proof that rods or other retinal cells are irrelevant to every stage of magnetic compass behavior.')
add('Antibody controls constrain the localization claim',
'Günther and colleagues tested antibody specificity by replacing the primary antibody with pre-immune serum, absorbing it with its antigenic peptide, and expressing different cryptochromes in cultured cells. These controls address background staining and cross-reaction with related proteins rather than treating any fluorescent signal as Cry4.',
'Western blots detected an approximately 61-kDa retinal protein and an approximately 89-kDa Cry4–GFP fusion protein in the expression preparation. GFP is green fluorescent protein used as a molecular tag. Cry4 antibody did not produce the corresponding signal in control cells expressing other tested cryptochromes or GFP alone.',
'The controls support identification of the stained protein and strengthen the anatomical result. They still do not test magnetic behavior after selective Cry4 loss. Reliable molecular localization is a prerequisite for a receptor hypothesis, but it is not equivalent to proving that the localized protein transduces the Earth field into a neural signal.',
'Antigenic-peptide absorption tests whether the staining depends on recognition of the antibody’s intended target sequence. A loss of signal after that control is useful evidence of specificity, while independent cell-expression controls address recognition of related proteins.')
add('Purified Cry4 binds the FAD cofactor',
'Xu and colleagues expressed and purified European robin Cry4 to test its photochemistry directly. **Flavin adenine dinucleotide**, or **FAD**, is the bound light-absorbing cofactor that can participate in electron transfer. A **cofactor** is a nonprotein component needed for a protein’s chemical function.',
'Optical spectroscopy and native mass spectrometry indicated that more than 97% of the purified wild-type Cry4 population carried FAD. The supplementary spectrum separated major FAD-bound protein peaks from minor peaks assigned to protein lacking the cofactor. This preparation supplied a controlled molecular system independent of an intact animal.',
'FAD binding establishes that the purified candidate possesses the component required for the studied radical-pair chemistry. The published structural model places FAD near a chain of tryptophan residues. Binding alone does not establish Earth-field sensitivity, directional coding in a retina or transmission to a brain pathway.',
'The structural image is the authors’ published model, not an experimentally solved robin Cry4 structure. Its role is to represent a proposed molecular arrangement; spectroscopy and mass measurements provide the experimental evidence for the purified preparation.',also=('retina18',),anatomy=3)
add('Tryptophan mutations change radical-pair lifetimes',
'A **radical** is a molecular species with an unpaired electron; a **radical pair** contains two radicals generated through a linked reaction. In Cry4, light-excited FAD can receive an electron through a chain of tryptophan residues, producing radicals whose subsequent reactions depend on their electronic states.',
'Xu and colleagues replaced individual tryptophans with redox-inactive phenylalanine. **Redox** refers to electron-transfer chemistry. After 450-nm excitation, transient absorption measurements tracked changes over time. In the supplementary measurements, interrupted early transfer pathways produced radical-loss time constants of 180 ps and 900 ps.',
'Longer transfer pathways supported radicals persisting beyond the earliest nanosecond responses. The nearest-tryptophan mutation prevented the normal radical production observed in the wild-type preparation. These interventions establish contributions of particular residues to photochemistry; they do not demonstrate that the same mutations impair a living bird’s compass.',
'The electron-transfer chain is a molecular pathway rather than a neural circuit. Changing radical lifetime alters the time available for magnetic interactions, but the experiment does not identify a neuronal membrane channel controlled by that chemistry.',anatomy=3)
add('Cry4 radical chemistry responds to magnetic fields',
'**Electron spin** is a quantum property of an electron, not literal mechanical spinning. Spin-correlated radical pairs can occupy singlet and triplet states with different reaction possibilities. A magnetic field can alter transitions between these states and thereby influence the yield of chemical products.',
'Xu and colleagues measured field-dependent radical absorption in purified Cry4 after 450-nm excitation. The supplementary comparison covered fields up to 30 mT and tested wild-type protein against a tryptophan mutant. The mutant and wild type exhibited different magnetic field effects, connecting molecular structure to measured photochemical sensitivity.',
'The measurements establish magnetic sensitivity in vitro, meaning outside the living animal. Millitesla fields exceed the geomagnetic field, and the preparation includes controlled temperature and chemical conditions. These results support a candidate reaction mechanism but do not by themselves establish Earth-strength directional sensing or prove that Cry4 causes magnetic orientation in birds.',
'Singlet and triplet describe different combined spin states of the two electrons. The proposed compass mechanism requires field direction to influence a biologically useful chemical signal; this experiment measures chemical sensitivity rather than a completed retinal-to-brain encoding pathway.',anatomy=3)
add('Photoreduced Cry4 can return toward its resting state',
'**Photoreduction** is light-driven electron gain. After illumination changes FAD’s oxidation state, a reusable sensory protein must return toward an appropriate starting state. Xu and colleagues measured optical spectra as photoreduced Cry4 reoxidized in contact with air without added redox reagents.',
'The supplementary experiment used 2 min of 450-nm illumination followed by spectra recorded at 2-min intervals. The main analysis reported recycling times of approximately 13 min from the neutral radical state toward oxidized FAD and approximately 1 min from the fully reduced state toward the neutral radical.',
'These measurements establish a route for chemical resetting under the tested conditions. Rates can differ in living cells because oxygen availability, reducing agents and protein interactions differ from a cuvette. Molecular recycling therefore supports plausibility as a reusable sensor without establishing the speed or coding of a bird’s behavioral compass.',
'A receptor cycle includes both activation and recovery. Demonstrating that the candidate can reset is different from demonstrating that its changing state is read by a neuron; the downstream signaling partner and membrane mechanism remain unresolved in these studies.',anatomy=3)
add('Iron staining does not identify a magnetic neuron',
'A proposed alternative receptor uses **magnetite**, an iron oxide whose particles can interact with magnetic fields. Treiber and colleagues reexamined iron-rich cells in pigeon upper beaks that had been proposed as magnetosensitive neurons. **Prussian blue** staining detects a form of iron accumulation but does not establish neuronal identity.',
'Iron-positive cells occurred in subepidermal tissue, respiratory epithelium and feather follicles. Their positions and abundance varied strongly across birds rather than forming the claimed stereotyped bilateral sensory arrangement. At least 97% of the stained cells in the examined compartments contained visible nuclei.',
'The anatomy challenged identification of this particular iron-rich population as an organized receptor system. It did not establish that all particle-based magnetoreception is impossible or that turtle magnetic-pulse effects lack a biological basis. A material sensitive to magnetism must still be linked to an identified sensory cell and pathway.',
'The pigeon is a different species from the robin and reed warbler. The negative anatomical finding constrains a specific upper-beak receptor claim, rather than directly locating the receptor responsible for every trigeminally mediated map response.')
add('Iron-rich upper-beak cells are macrophages',
'**Macrophages** are immune cells that can accumulate and process material within tissues. Treiber and colleagues combined iron staining with neuronal markers, immune-marker staining and electron microscopy. This approach tested cell identity rather than assuming that an iron deposit near a sensory nerve is part of a magnetoreceptor.',
'The iron-positive populations rarely overlapped the tested neuronal markers and overlapped MHC class II, an antigen-presentation marker. Electron microscopy revealed ferritin-like granules about 6–9 nm across and iron-containing structures including siderosomes approximately 300 nm in size.',
'These results support macrophage identity for the examined cells. They refute the claim that those particular iron-rich clusters are magnetosensitive neurons, while leaving the true peripheral source of trigeminal magnetic information unidentified. Neither iron staining nor a nearby nerve establishes a mechanosensitive ion channel or a functional magnetic synapse.',
'Ferritin stores iron, and siderosomes are iron-rich intracellular structures. Their presence can reflect immune-cell iron handling rather than a sensory transducer; chemical composition must be interpreted together with cellular identity and physiological function.',anatomy=4)
add('Map and compass evidence supports distinct mechanisms',
'The turtle studies distinguish regional-field recognition from the direction selected after recognition. A learned food-anticipatory assay tests magnetic signatures without requiring a compass heading, whereas hatchling swimming assays can require both positional cues and directional information to produce an appropriate course.',
'Radiofrequency exposure spared learned turtle map discrimination but disrupted the compass-dependent orientation task. A strong magnetic pulse reduced learned map responses. In birds, Cluster N lesions disrupted compass behavior, whereas trigeminal sections impaired map compensation in reed warblers while sparing the tested robin compass.',
'The converging evidence supports separable functions and candidate transduction processes, with important differences between species and preparations. Cry4 localization and purified photochemistry support a radical-pair hypothesis; particle-based maps remain plausible but lack an identified receptor pathway. The transmitters, ion channels and full receptor-to-behavior circuits remain incompletely established.',
'Functional separation does not require that a navigation system use each sense independently during natural travel. A map can select the appropriate course and a compass can maintain it, while other sensory information influences both decisions.',also=('turtlepulse25','cluster09','birdmap14','retina18','cry4_21'),anatomy=3)

assert len(slides)==44
for i,s in enumerate(slides,2):
 assert len(s['title'])<=62,(i,s['title'],len(s['title']))
 words=len(re.sub(r'\*\*|_','', ' '.join(s['body'])).split());assert 90<=words<=170,(i,words)
spec={'lecture':23,'theme':'charcoal-red-clay','content_slides':44,'title_image':fig(extras[0]),'slides':slides,'takeaways':{'items':[
 {'lead':'Compass and map differ','text':'A compass supplies direction; a magnetic map uses location-related field information. An orientation assay can require both.'},
 {'lead':'Turtles discriminate field geometry','text':'Controlled inclination and regional-field changes evoke different swimming headings, including appropriate responses in ocean-inexperienced hatchlings.'},
 {'lead':'Magnetic signatures can be learned','text':'Juvenile loggerheads learn compound inclination–intensity cues and retain rewarded-field discrimination for at least four months.'},
 {'lead':'Bird pathways serve different tasks','text':'Cluster N is necessary for the tested robin magnetic compass; V1 input is necessary for magnetic map compensation in reed warblers.'},
 {'lead':'Cry4 is a supported candidate','text':'Retinal localization, antibody controls and magnetic-sensitive purified photochemistry support a radical-pair hypothesis without proving its complete neural mechanism.'},
 {'lead':'Receptor identity remains unresolved','text':'Pulse effects support candidate particle-based maps, but iron-positive beak cells can be macrophages; a magnetic material alone is not an identified sensory receptor.'}
 ],'cite':'Lohmann et al. (2001); Goforth et al. (2025); Zapka et al. (2009); Pakhomov et al. (2018); Günther et al. (2018); Xu et al. (2021); Treiber et al. (2012)','refs':[REF[k]for k in ['turtle01','turtle25','turtlepulse25','cluster09','birdmap14','retina18','cry4_21','macrophage12']]}}
(H/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n');(H/'references.json').write_text(json.dumps(REF,indent=2,ensure_ascii=False)+'\n');print('44 slides; body word range:',min(len(' '.join(s['body']).split())for s in slides),max(len(' '.join(s['body']).split())for s in slides))
