"""Write Lecture 49 from verified published primary studies and original PDF crops."""
from pathlib import Path
import copy,json
B=Path(__file__).resolve().parent
R={s['id']:s for s in json.loads((B/'research.json').read_text())['sources']}
C={'bari':'Bari et al. (2020)','wimmer':'Wimmer et al. (2015)','moron':'Morón et al. (2002)','gamo':'Gamo et al. (2010)','gamo15':'Gamo et al. (2015)','shr':'Kim et al. (2012)','dat':'Leo et al. (2018)','phasic':'Sable et al. (2025)','fly':'Kirszenblat et al. (2018)'}
I=json.loads((B/'figure_sources.json').read_text())
F={name:{'path':f'figures/{name}.png','kind':'article','caption':f"{C[f['paper']]}, Fig. {f['figure']}. {f['description']}",'source_url':'https://doi.org/'+R[f['paper']]['doi']} for name,f in I.items()}
S=[]
def add(title,papers,images,body,teaching,height=2.15):
 ids=papers.split()
 for name in images:
  if I[name]['paper'] not in ids:ids.append(I[name]['paper'])
 paragraphs=body.split('||');assert len(paragraphs)==3
 assert len(title)<=62,(len(title),title)
 s={'title':title,'body':paragraphs,'cite':'; '.join(C[k] for k in ids),'refs':[R[k]['reference'] for k in ids], 'transcript':[paragraphs[0],[paragraphs[1],[teaching]],paragraphs[2]],'figure_width':6.0}
 if len(images)==1:s.update(layout='figure-right',figure=copy.deepcopy(F[images[0]]))
 else:s.update(layout='figures-right',figures=[copy.deepcopy(F[n]) for n in images],primary_figure_height=height)
 S.append(s)

add('Accuracy and premature responding are distinct','bari',['bari_task','lc_activation'],
'''**Attention** selects information relevant to an ongoing goal; **response inhibition** withholds an action until it is appropriate. Bari and colleagues trained mice to wait 7 s for a light that appeared for 0.5 s in one of two apertures. A nose poke into the illuminated aperture earned food.||Correct-response proportion indexed target selection, whereas **premature responses**, nose pokes before target onset, indexed failure to wait. Incorrect choices and premature actions were therefore distinct outcomes within the same preparation. Light-driven neural activation altered both measures without changing response speed.||A mouse can select the wrong location after waiting correctly, or respond too early before any target exists. The task separates these errors operationally; neither alone constitutes a clinical diagnosis of attention-deficit/hyperactivity disorder, or **ADHD**. Sensory, motivational and motor controls remain necessary when interpreting altered performance.''',
'An operant task links an animal’s action to a consequence such as food delivery. Accuracy concerns which aperture the mouse selects after the target appears. A premature nose poke concerns when it acts, so an improvement in waiting cannot be inferred simply from faster or more accurate choices.')

add('Impulsive action differs from impulsive choice','shr bari',['shr_task','shr_drinking'],
'''**Impulsive action** refers to inadequate restraint of a response; **impulsive choice** refers to preference for an immediate outcome over a more valuable delayed outcome. Kim and colleagues examined action restraint in spontaneously hypertensive rats, or **SHR**, using drinking that incurred an aversive consequence.||After training, drinking for at least 5 s triggered a 0.5-s, 2-mA foot shock. SHR entered the water area and completed punished drinking more often than Wistar-Kyoto, or **WKY**, controls. The preparation measures persistence despite punishment rather than choosing between different reward delays.||Premature nose pokes and punished drinking are related measures of action control, but their sensory cues, reinforcement and motivational demands differ. A **phenotype** is an observable characteristic under specified conditions. An animal phenotype resembling one ADHD-associated behavior does not reproduce the complete human disorder or identify its cause.''',
'Delay-dependent choice requires comparing outcomes that differ in waiting time. The drinking task instead offers the same water source with a consequence for sustained drinking. Thirst, sensitivity to shock and knowledge of the apparatus can all influence that behavior, so they must be examined separately.')

add('A sensory rule determines which stimulus guides choice','wimmer',['wimmer_task','wimmer_cost'],
'''**Selective attention** prioritizes one information source while competing information is present. Wimmer and colleagues trained mice to choose a reward location from conflicting visual and auditory signals. A preceding sound instructed the animal which sensory modality, vision or hearing, should govern its response.||One cue used noise low-pass filtered at 10 kHz; another used noise high-pass filtered at 11 kHz. Their assignments were counterbalanced across animals. Visual trials required locating a light, whereas auditory trials required distinguishing an upward from a downward frequency sweep.||Successful performance required the instructed rule rather than following whichever stimulus was most salient. Counterbalancing reduced the possibility that one cue intrinsically favored one modality. Because visual detection and auditory discrimination differ computationally, balanced accuracy does not establish identical processing demands or identical sensory pathways.''',
'The two target signals pointed toward competing response locations. A mouse that consistently followed the light would fail auditory-selection trials even if its vision were excellent. Cue-guided selection therefore concerns which information controls the response, rather than the presence of two detectable signals alone.')

add('Selection costs persist when a distractor is omitted','wimmer',['wimmer_cost','wimmer_task'],
'''Wimmer and colleagues measured a **detection threshold**, the stimulus strength associated with a specified level of visual performance. They varied light intensity while comparing visual-only trials with trials requiring a cue-dependent switch between vision and audition. Brief visual targets lasted 0.1 s during these measurements.||Visual detection required greater stimulus intensity under cross-modal conditions. Removing the conflicting auditory target did not restore the visual-only detection function. Conversely, learning over a session that auditory stimuli were unrewarded did not produce the same threshold change as trial-by-trial modality selection.||The cost therefore depends on the instructed task configuration, rather than merely acoustic interference from a simultaneous distractor. Expectation and sensory selection can modify measured visual sensitivity. This behavioral comparison does not by itself locate the circuit that changes sensitivity or distinguish every possible contribution of uncertainty and task switching.''',
'A psychometric function relates stimulus intensity to the probability of a correct response. Omission of the auditory distractor preserves the preceding selection cue, so the animal still prepares for the instructed modality. That control separates preparation for a competing task from the immediate physical presence of the competing stimulus.')

add('Flies balance fixation against wide-field motion','fly',['fly_task','fly_competition'],
'''Kirszenblat and colleagues measured visual selection in freely walking _Drosophila melanogaster_. **Fixation** was orientation toward a target stripe; an **optomotor response** was turning with wide-field motion. Wing-clipped flies walked on a platform inside an illuminated arena, allowing both behaviors to be measured in the same animal.||Targets flickered at 7 Hz, while a background grating moved at 54 degrees per second with a temporal frequency of 3 Hz. **Target deviation**, the angle between walking direction and the target, increased as distractor contrast increased. Angular turning velocity separately measured motion-following behavior.||Competition altered orientation even though flies retained responses to isolated targets and motion. These measurements support attention-like selection in insects without assuming that their neural architecture duplicates mammalian frontal circuits. Target deviation measures behavior, not conscious experience, clinical inattention or a directly recorded attention neuron.''',
'A smaller deviation angle means the fly walks more closely toward the target. Turning with the background is a separate response with units of degrees per second. The two readouts can change differently, allowing competition between orientation tendencies to be distinguished from a general inability to move or detect the display.')

add('Locus-coeruleus neurons supply cortical norepinephrine','bari',['lc','terminals'],
'''The **locus coeruleus**, or LC, is a brainstem nucleus whose neurons release **norepinephrine**, or NE, a chemical transmitter that modulates target-cell activity. NE and **dopamine**, or DA, belong to the catecholamine transmitter family. Bari and colleagues targeted LC neurons genetically and verified their identity in labeled tissue.||A **transporter** moves transmitter across a cell membrane. Expression of the norepinephrine transporter, or **NET**, helped identify the targeted neurons. Fluorescent markers localized light-sensitive proteins in LC cells and noradrenergic axon terminals in frontal cortex; source micrographs retain 100-µm and 50-µm reference scales.||The anatomical evidence links a transmitter-defined population to cortical projections. An **axon terminal** is the release-bearing ending of a neuronal process. Labeling establishes location and molecular identity, but it does not alone establish when release occurs, which receptor responds or whether a projection changes behavior.''',
'The nucleus contains the neuronal cell bodies, while their long axons reach distant cortical targets. A chemical transmitter can modify the operation of an existing circuit rather than specify one sensory feature. Anatomy establishes where that modulation is possible; release measurements and perturbation experiments establish additional functional properties.')

add('Light-driven LC activity increases cortical NE release','bari',['ne','lc'],
'''**Optogenetics** controls genetically targeted cells with light-sensitive proteins. Bari and colleagues expressed **channelrhodopsin-2**, or ChR2, a light-activated ion channel, in noradrenergic neurons. Channel opening permitted depolarization, a shift of membrane voltage toward excitation, and increased LC firing during blue-light stimulation.||The investigators paired 7-s stimulation with 10-ms light pulses at different frequencies. At 20 Hz and 1.5 mW, stimulation produced elevated LC output and a robust prefrontal NE signal. A fluorescent NE sensor in medial prefrontal cortex reported transmitter-related changes during stimulation.||An imposed pulse frequency is not automatically the neuronal firing rate: this protocol elevated sustained LC firing to approximately 5 Hz. Sensor fluorescence provides an extracellular transmitter readout rather than a direct count of released molecules. Together, electrical recording and transmitter photometry validate the manipulation beyond protein expression alone.''',
'Fiber photometry collects fluorescence from tissue through an optical fiber. The NE sensor responds to transmitter outside cells, whereas an electrode measures electrical spikes. Those measurements test different links between the light pulse, activity of the targeted neurons and chemical signaling at a distant target.')

add('LC activation improves accuracy and waiting','bari',['lc_activation','lc_control'],
'''During the two-choice task, Bari and colleagues activated LC neurons over the 7-s delay preceding the target. ChR2-expressing mice made more correct choices and fewer premature responses with the laser on. Littermate controls lacking the active protein received comparable illumination.||The brief 0.5-s target challenged accurate detection and selection. Activation did not shorten response times, and the stimulation protocol did not increase open-field locomotor distance. Food-related controls also argued against a simple increase in reward motivation as the explanation for improved task performance.||**Causal perturbation** tests whether deliberately changing neural activity changes an outcome. These results support an influence of LC activity on selection and restraint during preparation. They do not establish that every frequency, duration or behavioral state of LC activation is beneficial, or identify one cortical receptor responsible for both effects.''',
'A laser-on versus laser-off comparison in the same task tests the immediate consequence of the manipulation. The protein-negative controls account for illumination itself. Unchanged movement and response speed constrain a motor explanation, while the dependence on the delay identifies a time window in which preparation can be altered.')

add('LC suppression impairs accuracy and waiting','bari',['lc_inhibition','lc'],
'''Bari and colleagues expressed **archaerhodopsin**, or Arch, a light-driven proton pump, in noradrenergic neurons. Its activation suppressed LC electrical activity. Applying continuous illumination during the delay provided a complementary manipulation to the ChR2 activation experiment.||In the task with a 7-s waiting period and a 0.5-s target, LC suppression reduced correct responses and increased premature nose pokes. Response times did not change. Animals lacking Arch served as illumination controls, while electrical recordings verified that the pump suppressed the targeted neurons.||Opposite behavioral effects of activation and suppression strengthen the causal connection between LC output and attentional control under these conditions. They do not imply that attention is a single variable determined by overall LC activity. The same nucleus has multiple projections, and suppressing its output can affect more than one downstream circuit.''',
'A proton pump moves charged particles across the membrane rather than forming the light-gated cation channel used for activation. The manipulation therefore changes excitability in the opposite direction. Verification of electrical suppression is essential because expression of the protein alone would not prove that the illumination successfully reduced firing.')

add('Irrelevant spatial cues alter response timing','bari',['cue_task','cue_rt'],
'''A **valid cue** appears on the future target side; an **invalid cue** appears on the opposite side. Bari and colleagues also used neutral and absent cues. The cue lasted 0.5 s and preceded a 3-s target, but its position did not predict where reward-relevant information would appear.||Control mice responded more slowly following invalid than neutral cues. The **validity effect** compared response timing after invalid and valid cues. LC activation reduced this timing difference, whereas LC suppression increased it. The uninformative cues could therefore bias orientation even when following them was not a reliable strategy.||A smaller cue effect is consistent with stronger goal-directed selection of the target. Faster responding alone would not establish improved attention; changes must be interpreted relative to cue condition and accuracy. This preparation tests resistance to spatial distraction rather than all forms of vigilance, learning or impulsive choice.''',
'The target, rather than the preceding cue, determines which response earns food. A valid cue occasionally helps, but an invalid cue directs the animal away from the relevant location. Because the cue is uninformative overall, resistance to its influence can improve performance without making every response faster.')

add('LC output changes susceptibility to misleading cues','bari',['cue_accuracy','lc'],
'''**Goal-directed**, or top-down, attention follows task requirements; **stimulus-driven**, or bottom-up, attention follows salient events. Bari and colleagues compared correct choices after valid and invalid spatial cues while changing LC activity during preparation. Cue position was irrelevant to the rule for obtaining food.||The difference in accuracy between valid and invalid trials was smaller during LC activation and larger during LC suppression. The target remained available for 3 s, so the comparison tested distraction by the preceding 0.5-s cue rather than detection of a uniformly brief target alone.||The result supports LC modulation of the balance between goal-relevant and distracting information. It does not establish that a larger NE signal always eliminates distraction, or that every LC neuron has the same role. Accuracy and premature-response measures remain distinct even when one manipulation influences both.''',
'A misleading cue can produce an incorrect choice without requiring a premature response. That distinction is preserved when target duration is increased to make selection under distraction the principal challenge. The experiment links controlled changes in the noradrenergic population to sensitivity to an irrelevant event, rather than to sensory detection alone.')

add('Calcium photometry samples ongoing LC activity','bari',['calcium','calcium_timing'],
'''**Intracellular calcium** is a signaling ion whose concentration often changes with neuronal activity. Bari and colleagues expressed **GCaMP6f**, a calcium-sensitive fluorescent protein, in NET-positive LC neurons. Fiber photometry recorded the population signal while mice performed the cue-dependent two-choice task.||Activity was aligned to target onset, separating delay-period signals from cue- and target-evoked responses. Sensory-evoked activity was measured over 0.5-s windows. A wavelength that did not depend on calcium provided a comparison channel for separating activity-related fluorescence from some optical artifacts.||A calcium transient is a time-varying fluorescence response, rather than a direct measurement of every action potential. Population photometry averages signals from multiple cells and cannot establish whether individual projection-defined neurons respond identically. Its temporal relationship to behavior complements, but does not replace, electrical recording and causal manipulation.''',
'An action potential is a brief electrical spike, while the calcium sensor reports a biochemical consequence associated with activity. The sensor’s kinetics smooth the underlying events. Comparing spontaneous and event-locked signals requires specifying the analysis window, since a response to the target is different from activity before the target appears.')

add('Delay-period LC activity predicts response outcome','bari',['calcium_outcome','lc'],
'''Bari and colleagues compared LC calcium signals preceding correct, incorrect and premature responses. Activity during the latter portion of the waiting period was higher before correct responses and lower before errors or early nose pokes. The comparison concerned naturally occurring activity rather than imposed stimulation.||A 3-s pretarget analysis window reduced contamination by the animal turning toward the response panel. Cue-evoked activity was measured separately over 0.5 s. Premature responses were associated with lower preceding activity but stronger responses to the distracting cue, separating sustained preparation from stimulus-triggered activation.||These associations support a relationship between LC state and successful restraint or selection. They do not prove that the measured calcium fluctuation causes each individual response. Other behavioral and neural variables can covary with the signal, while the separate optogenetic experiments establish a causal influence of the targeted population.''',
'An event-evoked increase and elevated activity before an event need not have the same behavioral meaning. The distinction prevents the stronger response to a distractor from being equated with better task preparation. The recordings concern population activity, so the experiment does not identify the contribution of every individual LC neuron.')

add('Dorsomedial NE terminals improve distractor resistance','bari',['dmpfc','terminals'],
'''The **dorsomedial prefrontal cortex**, or dmPFC, is a frontal cortical region receiving noradrenergic axons from the LC. Bari and colleagues expressed ChR2 in LC neurons using a dopamine-β-hydroxylase-based genetic strategy and verified labeled terminals and optical-fiber placement in cortical tissue.||Stimulation of LC terminals at 5 Hz during the pretarget delay increased correct responses on trials containing distractors. It did not alter premature-response frequency. Response times increased specifically under distraction, consistent with additional time being used for successful selection among competing stimuli.||Terminal manipulation narrows the candidate pathway beyond whole-LC stimulation. The result supports a dmPFC contribution to target selection under distraction, rather than a general reduction of all forms of impulsivity. The experiment does not identify the postsynaptic receptor or local neuron class that mediates the behavioral improvement.''',
'Dopamine-β-hydroxylase is the enzyme that converts dopamine into norepinephrine and provides a marker for noradrenergic neurons. Illuminating axon terminals in one cortical region restricts where the intervention is delivered. Nevertheless, terminal stimulation is not equivalent to isolating a single synapse or proving that no other branches of the same neurons are affected.')

add('Orbitofrontal NE terminals reinforce response restraint','bari',['vlofc','terminals'],
'''The **ventrolateral orbitofrontal cortex**, or vlOFC, is a frontal region on the ventral and lateral cortical surface. Bari and colleagues verified noradrenergic terminal labeling and positioned optical fibers in this region, using the same LC-origin ChR2 strategy as for dmPFC targeting.||Terminal stimulation at 5 Hz decreased premature responding whether distractors were present or absent. It did not change correct-response proportion or response times. Histology supplied anatomical verification, including the original 400-µm scale reference for the cortical fiber-placement sections.||The vlOFC manipulation affected restraint, whereas dmPFC targeting primarily affected distractor-dependent accuracy. This **double dissociation**, different selective effects from two interventions, argues against treating attention and response inhibition as one behavioral process. It does not establish that either cortical region exclusively controls its associated function in every task.''',
'The same transmitter can have different behavioral effects when delivered to different cortical circuits. Response restraint depends on withholding the nose poke until the target appears, while accuracy depends on selecting the target location. The dissociation is defined by those measured outcomes rather than by a general label such as improved cognition.')

add('Prefrontal activity is required during sensory preparation','wimmer',['pfc','pfc_hist'],
'''The **prelimbic cortex** is a medial prefrontal region in mice. Wimmer and colleagues disrupted its activity by stimulating local **GABAergic neurons**, cells that release the inhibitory transmitter gamma-aminobutyric acid, or GABA. Activation of these inhibitory cells reduced activity in the surrounding excitatory network.||Blue-light pulses at 50 Hz were delivered during either anticipation or target presentation. Prefrontal disruption impaired cross-modal performance when applied during anticipation. Comparable manipulation did not alter visual-only performance, even when the visual task was difficult; histology and light-spread measurements verified the targeted tissue.||The result supports a prefrontal requirement for preparing a cue-dependent sensory selection. It does not imply that all difficult visual decisions require the same frontal circuit. Timing-specific perturbations distinguish a preparatory contribution from direct sensory processing after the stimulus appears.''',
'Inhibitory neurons were activated to suppress the local network, so light stimulation in this experiment has a different functional purpose from direct activation of noradrenergic cells. The visual-only comparison preserves a sensory decision while removing the requirement to select between modalities. That control constrains the role attributed to the prelimbic network.')

add('Visual cortex contributes when the stimulus is present','wimmer',['v1','pfc_hist'],
'''The **primary visual cortex**, or V1, is a cortical region that processes visual input. Wimmer and colleagues used light-driven local inhibition to compare its contribution during anticipation with its contribution during presentation of the visual target. The original anatomical targeting accompanies the perturbation results.||Disruption during target presentation impaired visual performance, whereas anticipatory disruption did not produce the prefrontal pattern. In a visual-only task, visual-cortex perturbation increased the detection threshold. The same general 50-Hz stimulation approach therefore produced different effects depending on location and timing.||These results support a sensory-processing role for V1 under the tested conditions. They do not exclude cortical attentional modulation in other tasks or species. The absence of a preparatory effect here constrains a specific proposed route for sensory selection; it does not establish that V1 never participates in top-down processing.''',
'A region can be essential for detecting a stimulus without being the location where the animal prepares which modality to select. The perturbation window separates those functions. The same behavioral error can follow interruption at different stages, so anatomical location and the timing of disruption both contribute to the inference.')

add('Reticular neurons inhibit a visual thalamic relay','wimmer',['trn_tag','trn_anatomy'],
'''The **thalamus** contains nuclei linking sensory input with cortical processing. The **lateral geniculate nucleus**, or LGN, is a visual relay. The **thalamic reticular nucleus**, or TRN, is a surrounding population of inhibitory neurons; its visual sector, **visTRN**, projects to the LGN.||Wimmer and colleagues combined genetic identity with projection tracing to label GABAergic neurons connected to the LGN. **Retrograde labeling** identifies cells by transport from a projection target back toward their cell bodies. Original histology localized reticular and geniculate tissue with 100-µm reference scales.||This preparation identifies a candidate inhibitory route for regulating visual transmission. It does not make the TRN a passive barrier or establish that every reticular cell performs the same computation. Projection identity must be combined with activity during selection and perturbation of those identified neurons.''',
'A relay neuron transmits information onward, while an inhibitory input can change how strongly that information reaches the next stage. The study selected reticular neurons by both their transmitter-related genetic marker and their connection to the visual thalamus. That intersection is more specific than recording from the thalamus without identifying the cells’ output target.')

add('Reticular activity depends on the selected modality','wimmer',['trn_tag'],
'''Wimmer and colleagues recorded spikes from projection-defined visTRN neurons while mice anticipated conflicting auditory and visual targets. Optogenetic identification linked the recorded cells to the previously labeled inhibitory population rather than relying only on electrode position. Firing rates were expressed in spikes per second, or hertz.||VisTRN activity decreased when the animal prepared to select vision and increased when it prepared to select audition. Disrupting prefrontal activity diminished this modality-dependent difference. The effect was not simply reproduced by naturally occurring errors, supporting a specific relationship to the preparatory frontal manipulation.||The pattern is consistent with reduced inhibition of the visual relay when vision is relevant and increased inhibition when it is distracting. Functional dependence on prefrontal activity does not by itself establish one direct monosynaptic connection. A **monosynaptic connection** is a link across a single synapse, which requires additional circuit evidence.''',
'A spike raster records the timing of individual electrical events across trials. The modality-dependent changes begin before the target, so they concern preparation rather than only a response to incoming light. Prefrontal disruption tests functional coupling, while the anatomical path between the two regions can still include intermediate neurons.')

add('Reticular perturbations bias sensory selection','wimmer',['trn_bidirectional','trn_anatomy'],
'''Wimmer and colleagues activated or inhibited the LGN-projecting reticular population during the divided-attention task. ChR2 activation increased activity, whereas **halorhodopsin**, a light-driven chloride pump, suppressed it. Projection tracing and histology constrained the manipulated neurons to the visual inhibitory subnetwork.||Activation impaired visual-selection trials, consistent with excessive inhibition of the visual relay. Suppression preferentially impaired auditory-selection trials, when visual information needed to be disregarded. Perturbations were compared during anticipation and target presentation rather than treating the complete trial as one undifferentiated time period.||The opposing effects support a causal role for regulated reticular inhibition in selecting the relevant modality. Simply increasing visual transmission is not beneficial when vision is the distractor. These results establish task-dependent behavioral consequences, while the precise downstream electrical and chemical changes require recordings from the relay itself.''',
'An inhibitory circuit can improve one kind of trial while impairing another. When the rule requires audition, releasing the visual pathway from inhibition permits irrelevant visual information to compete more strongly. The consequence of a manipulation therefore depends on the instructed sensory goal rather than on a universal preference for stronger sensory responses.')

add('Geniculate gain rises when vision is selected','wimmer',['lgn'],
'''**Sensory gain** describes the strength of a neural response to input under a particular processing state. Wimmer and colleagues recorded LGN neurons during the cross-modal task. Head-mounted lights reduced variability in retinal stimulation associated with changes in the animal’s position relative to wall-mounted targets.||LGN neurons had higher baseline and visually evoked firing when vision was selected than when audition was selected. The **visual evoked potential**, a stimulus-linked extracellular electrical signal, also increased. Recorded responses were aligned to light onset, with neuronal rates measured in hertz and evoked potentials in microvolts.||The results locate attention-dependent modulation within the visual thalamus, rather than only in a behavioral score. They do not identify which input changes the gain. Increased excitation and reduced inhibition can both elevate firing, so the inhibitory mechanism requires an additional physiological measurement and intervention.''',
'Baseline activity precedes the visual stimulus; evoked activity follows it. Both can change with the selected modality. A population electrical potential and a single neuron’s spike train measure different aspects of activity, and their agreement supports a relay-level modulation without making them identical readouts.')

add('Chloride measurements connect selection to inhibition','wimmer',['chloride','chloride_result'],
'''The **GABA-A receptor** is a transmitter-gated ion channel that permits chloride movement. Wimmer and colleagues expressed **SuperClomeleon**, a chloride-sensitive fluorescent indicator, in LGN neurons. Its paired fluorescent proteins report **fluorescence resonance energy transfer**, or FRET, an energy-transfer signal that changes with intracellular chloride.||Excitation at 430 nm allowed a ratio of the two emission signals to be measured. Visual stimulation produced a larger chloride-related response when audition was selected. Reticular inactivation eliminated that modality-dependent difference; drug and fluorescent-protein controls supported the signal’s relationship to GABA-mediated inhibition.||The combined measurements support regulated inhibitory input as a mechanism of visual gain control. Bulk photometry does not isolate every synapse or supply a complete conductance measurement. A chloride-sensitive signal must be interpreted with its calibration and controls, rather than equating any fluorescence change with neuronal inhibition.''',
'Chloride concentration is a chemical variable, whereas firing rate is an electrical output. Increased chloride-sensitive inhibition during auditory selection can suppress a competing visual signal. Eliminating the difference by reticular inactivation ties the chemical readout to a candidate source of inhibition, beyond the correlation between selected modality and relay firing.')

add('NET contributes to frontal dopamine clearance','moron bari',['moron_baseline','ne'],
'''**Reuptake** removes extracellular transmitter by transporting it into cells. The **dopamine transporter**, or DAT, and NET differ in their regional abundance and substrate selectivity. Morón and colleagues used mouse transporter deletions to test whether NET contributes to dopamine uptake in frontal cortex.||They measured radiolabeled dopamine accumulation in **synaptosomes**, isolated resealed nerve-terminal preparations. Incubation at 37°C was compared with a 4°C background control. Frontal dopamine uptake was retained after DAT deletion but reduced after NET deletion; the wild-type frontal rate was 0.45 pmol per minute per milligram of protein.||The result establishes a transporter contribution to uptake in this isolated preparation. It does not directly measure dopamine release, ongoing behavior or receptor stimulation in an intact animal. A transporter’s name identifies its usual association, rather than guaranteeing that it transports only the corresponding transmitter.''',
'A synaptosome retains part of a nerve terminal’s membrane machinery after tissue homogenization. Uptake of labeled dopamine tests membrane transport while separating it from an ongoing behavioral state. The low-temperature comparison estimates accumulation that is not due to normal active transporter function under the assay conditions.')

add('Dopamine uptake depends on the sampled brain region','moron phasic',['moron_net','phasic_anatomy'],
'''Morón and colleagues compared frontal cortex with the **caudate**, part of the dorsal striatum, and the **nucleus accumbens**, a ventral striatal region. The striatum is a collection of interconnected forebrain nuclei. The accompanying rat sections provide comparative regional anatomy, rather than histology of the assayed mouse tissue.||Wild-type uptake rates were 3.44 pmol per minute per milligram in caudate and 2.70 in accumbens, compared with 0.45 in frontal cortex. Nisoxetine, a NET inhibitor, reduced dopamine uptake in wild-type tissue, while NET deletion removed the NET-specific component of that response.||Regional uptake depends on transporter abundance as well as binding affinity. The result prevents a striatal clearance mechanism from being assumed to operate identically in frontal cortex. Differences in isolated uptake rates do not alone determine the transmitter concentration experienced by receptors in a behaving animal.''',
'The mouse assay sampled accumbens core and shell together, while the rat recording study targeted the core. Those anatomical sampling boundaries differ. A regional comparison can establish that clearance machinery varies across the brain without making two species or two subregions interchangeable preparations.')

add('Transporter selectivity depends on drug concentration','moron phasic',['moron_dat','phasic_anatomy'],
'''An **inhibitor** reduces a protein’s activity; pharmacological selectivity is the extent to which it acts on one target rather than alternatives. Morón and colleagues compared GBR12909, a DAT inhibitor, with nisoxetine and cocaine in mouse synaptosomes. Frontal, caudate and accumbens samples were assessed separately.||GBR12909 inhibited dopamine uptake strongly in caudate and accumbens but had little effect in frontal cortex over transporter-selective concentrations. Uptake in frontal tissue persisted after DAT deletion. Above approximately 100 nM, inhibitor effects could become less selective, as indicated by the original concentration-response plots.||Combining genetic deletion with drug concentration constrains which transporter accounts for uptake. A response to a high drug concentration alone does not prove a selective DAT or NET mechanism. The comparative rat anatomy identifies relevant regional relationships, while the molecular uptake evidence remains specific to the mouse preparations.''',
'An antagonist of a receptor and an inhibitor of a transporter affect different proteins. Receptor antagonism alters a cell’s response to transmitter; uptake inhibition changes removal of transmitter from extracellular space. Neither should be described as measuring release directly, and high concentrations can introduce additional molecular targets.')

add('Prefrontal neurons retain spatial information during delay','gamo',['monkey_wm'],
'''**Working memory** maintains information temporarily for an ongoing action. Gamo and colleagues recorded from rhesus macaque **dorsolateral prefrontal cortex**, or DLPFC, while animals remembered a visual cue location. A **saccade** is a rapid eye movement; the required saccade occurred only after the cue disappeared.||The cue appeared for 0.5 s and was followed by a 2.5-s delay. A **preferred direction** was the location associated with stronger firing by a recorded neuron. Some cells maintained firing during the delay for that direction, while firing was lower for nonpreferred directions.||Persistent activity supplies a physiological correlate of maintained spatial information. The task measures working memory rather than resistance to an explicit competing sensory target. Shared prefrontal mechanisms can inform hypotheses about attentional control, but memory-related firing is not automatically a direct measurement of attention or an ADHD phenotype.''',
'The monkey maintains gaze at the central fixation point during the delay, so the remembered location and the actual eye position differ. Direction-tuned delay firing cannot be reduced to the eye movement itself. The subsequent memory-guided saccade links the maintained representation to an observable behavioral report.')

add('Medication effects vary across dose and individual','gamo',['drug_doses','monkey_anatomy'],
'''Gamo and colleagues tested **methylphenidate**, which inhibits catecholamine uptake, and **atomoxetine**, a relatively selective NET inhibitor, on macaque spatial working memory. Food was hidden in a well, and the animal selected its remembered location after an opaque screen interrupted visibility. Vehicle treatments controlled for administration without active drug.||Oral methylphenidate doses ranged from 0.1 to 2.0 mg/kg; atomoxetine ranged from 0.001 to 5.0 mg/kg. Individual dose-response curves generally formed an **inverted U**: intermediate exposure improved performance, whereas lower or higher exposure did not consistently help and could impair it.||The effective dose differed among animals, including age-related variation in atomoxetine sensitivity. These are experimental macaque doses, not human treatment recommendations. Improved performance establishes a working-memory effect under controlled conditions without identifying a unique receptor or proving a clinical mechanism in every person with ADHD.''',
'A vehicle contains the administration medium without the active compound. Comparing medication with its vehicle controls for the handling and delivery procedure. An inverted-U relationship means that increasing drug exposure beyond a beneficial range can reduce the same function that improved at a lower exposure.')

add('Adrenergic and D1 receptors support medication benefits','gamo',['drug_receptors','monkey_anatomy'],
'''A **receptor agonist** activates a receptor, whereas a **receptor antagonist** blocks its activation. Gamo and colleagues challenged each macaque’s effective methylphenidate or atomoxetine dose with idazoxan, an **α2-adrenergic receptor** antagonist, or SCH23390, a **dopamine D1 receptor** antagonist.||Antagonist doses were selected to avoid impairment when administered alone. Idazoxan was tested over 0.01–0.5 mg/kg and SCH23390 over 0.001–0.06 mg/kg. Each antagonist reversed the medication-related improvement in remembered-location choices relative to the relevant drug-plus-vehicle condition.||The controls support participation of both receptor families rather than simple addition of two independent impairments. They do not identify one receptor subtype at every relevant synapse, and systemic administration affects multiple locations. Medication-related improvement can depend on NE and DA receptor actions even when the uptake inhibitor is relatively NET-selective.''',
'An interaction is interpretable when the antagonist itself does not substantially worsen the baseline task. Otherwise, loss of improvement could merely reflect an unrelated deficit added to the drug’s benefit. The behavioral experiment supports receptor involvement; local neuronal application provides a separate test of how firing changes within prefrontal tissue.')

add('Atomoxetine can strengthen or suppress delay firing','gamo',['atomoxetine','monkey_anatomy'],
'''**Iontophoresis** uses electrical current to deliver small quantities of a charged drug near a recorded neuron. Gamo and colleagues applied atomoxetine locally while recording macaque DLPFC cells during the delayed eye-movement task. The same neuron could be compared across control and drug conditions.||Low ejection currents, commonly 2–5 nA, increased preferred-direction delay firing or reduced nonpreferred-direction firing. Higher application, including 10 nA, suppressed delay activity more broadly. Ejection current controls local delivery; it is not a measured drug concentration in the tissue or a directly equivalent systemic dose.||The bidirectional effect connects exposure to the neuronal representation rather than assuming uniform excitation. Increased catecholamine availability can sharpen or weaken persistent activity depending on exposure. The published panel includes a conceptual dose-response model and recorded responses; the conceptual curve is the authors’ interpretation, not an independently measured continuous function.''',
'Local drug delivery reduces the spatial reach of the intervention compared with an oral dose. It still does not supply an exact concentration at every nearby receptor. The recorded firing pattern is the measured outcome, while the shape connecting low and high exposure is a model of the relationship rather than a new measurement at every point.')

add('α2 and D1 actions modify different firing components','gamo',['receptor_firing','monkey_anatomy'],
'''Gamo and colleagues combined atomoxetine with local receptor antagonists during macaque DLPFC recordings. **Spatial tuning** is a neuron’s unequal response to different cue locations. Enhanced preferred-direction firing and suppressed nonpreferred-direction firing can both improve tuning, but they are different changes in activity.||Yohimbine, an α2-receptor antagonist, blocked the atomoxetine-related increase in preferred-direction delay firing. SCH23390 reversed the reduction of nonpreferred-direction firing. Representative experiments used 5-nA atomoxetine application with 15-nA yohimbine or 25-nA SCH23390 delivery.||The authors’ molecular model links α2A activation to reduced **cyclic AMP**, or cAMP, an intracellular messenger that regulates cellular proteins. This strengthens preferred network inputs. D1 signaling can raise cAMP and reduce competing activity. These are receptor- and exposure-dependent effects, rather than universal excitatory NE and inhibitory DA actions.''',
'A preferred-direction response carries the cue location favored by the recorded cell, while nonpreferred activity reduces selectivity if it becomes too strong. The antagonists distinguish effects on those two components. These experiments concern a selected population of delay-active neurons and should not be generalized to every cortical cell type.')

add('Recurrent excitation sustains prefrontal representations','gamo15 gamo',['spine_model'],
'''**Recurrent excitation** occurs when connected neurons reinforce one another’s activity. The published prefrontal network model describes pyramidal neurons with shared spatial preferences linked through excitatory synapses. A **synapse** is a specialized cell-to-cell signaling junction; a **dendritic spine** is a small postsynaptic protrusion receiving many such contacts.||The model includes **glutamate**, an excitatory transmitter, acting at **NMDA receptors**, transmitter-gated cation channels. GABAergic lateral inhibition limits competing activity. Gamo and colleagues recorded maintained firing through a 2.5-s memory delay, while anatomical and pharmacological experiments tested molecular components associated with these networks.||This circuit organization provides an interpretation of persistent, direction-tuned activity. A single neuron’s delay response does not directly establish every recurrent connection in the published model. The anatomical and physiological evidence must remain distinct from the proposed network explanation of how a spatial representation persists.''',
'A postsynaptic structure belongs to the receiving side of a synapse. Glutamatergic contacts can reinforce a population’s activity, while inhibitory cells constrain activity in competing populations. The authors’ original circuit panel is retained as a published model; it has not been redrawn or promoted to a complete experimentally mapped circuit.')

add('D1 receptors and HCN channels share spine locations','gamo15',['spines'],
'''The **D1 receptor** is a G-protein-coupled receptor: ligand binding changes intracellular signaling through associated G proteins rather than directly opening a transmitter-gated channel. D1 signaling can increase the intracellular messenger cAMP, which regulates other proteins. Gamo and colleagues examined receptor proximity to candidate channel targets.||Dual-label **immunoelectron microscopy**, antibody-based protein localization at electron-microscope resolution, detected D1 receptors and **hyperpolarization-activated cyclic nucleotide-gated channels**, or HCN channels, in macaque layer-III DLPFC spines. Original panels retain 200-nm scale references and labels distinguishing spine head and neck.||HCN channels conduct cations and respond to membrane voltage and cyclic nucleotides. Nearby receptor and channel labeling provides a plausible location for local signaling. Colocalization means spatial association, not proof that the proteins bind directly or that every labeled spine changes its current during a behavioral task.''',
'The spine head receives the synaptic contact, while the neck connects it to the dendrite. Molecular proximity can permit a local messenger to regulate nearby channels. Electron-microscopic labeling establishes where proteins occur, but channel-current recordings and selective pharmacological intervention are needed to test functional consequences.')

add('D1 stimulation enhances the HCN-related voltage sag','gamo15',['hcnsag','spine_model'],
'''**Hyperpolarization** shifts membrane voltage in the negative direction. HCN channels activate with hyperpolarization and carry an inward mixed-cation current, **Ih**. Cyclic AMP can increase their open probability, linking D1 receptor signaling to an electrical membrane property rather than only a change in transmitter concentration.||Gamo and colleagues recorded mouse prefrontal layer-V pyramidal neurons in slices. A 400-ms, −300-pA current pulse produced a voltage deflection followed by a partial return toward baseline, a **voltage sag**. Bath application of 10-µM SKF81297, a D1 agonist, increased the sag-related measure.||The result supports D1 regulation of an HCN-associated response in this preparation. A sag measurement is not a direct recording of every spine channel, and these mouse layer-V cells differ from macaque layer-III spines. The proposed link to weakened recurrent signaling therefore requires complementary in vivo and behavioral evidence.''',
'An inward current can reduce the voltage impact of another synaptic input by increasing membrane conductance, even though it has a depolarizing direction. HCN action is therefore not equivalent to a simple excitatory drive. The slice experiment tests a membrane response under controlled current injection, not a maintained representation during an intact animal’s attention task.')

add('HCN blockade protects delay activity from D1 stimulation','gamo15',['hcn_firing','monkey_anatomy'],
'''An open channel changes **membrane conductance**, the ease with which ionic current crosses the membrane. In the authors’ model, excessive D1–cAMP signaling opens HCN channels and weakens the influence of recurrent synaptic inputs. Gamo and colleagues tested that mechanism during macaque working-memory recordings.||Local SKF38393, a D1 agonist, suppressed delay-related DLPFC firing. Co-application of **ZD7288**, an HCN-channel blocker, preserved firing closer to control levels. Representative delivery ranges were 20–25 nA for the agonist and 5–10 nA for the channel blocker; the published traces retain firing-rate and time axes.||Pharmacological rescue links the channel-sensitive mechanism to the effect of D1 stimulation. It does not establish that every D1 action uses HCN channels, or that all recorded neurons were affected identically. The analysis specifically examined neurons whose delay-related activity was suppressed by the agonist.''',
'The rescue experiment changes two steps in a candidate mechanism: receptor stimulation is maintained while a downstream channel is blocked. Protection of firing is consistent with a required channel contribution. It does not mean that the blocker restores every aspect of the animal’s behavior, since the local recording applications were too small to test a whole-animal behavioral rescue.')

add('Prefrontal HCN blockade protects memory under stress','gamo15',['rat_pfc','rat_stress'],
'''Gamo and colleagues trained rats to alternate choices in a delayed T-maze task, remembering the preceding arm choice. Drug infusions targeted **prelimbic prefrontal cortex**, while dorsal anterior cingulate cortex served as an anatomical control. The original source distinguishes the two locations within the same medial cortical section.||A 0.001-µg/0.5-µl ZD7288 infusion reversed impairment caused by local D1 stimulation or the **pharmacological stressor** FG7142. FG7142 is a partial inverse agonist at the benzodiazepine site associated with GABA-A receptors. Infusing the blocker into the control region did not protect performance.||Channel-blocker-alone and response-time controls constrained nonspecific facilitation and motor impairment. The results support a prefrontal channel contribution under this experimental stress manipulation. They do not equate drug-induced stress with every natural stressor or establish HCN blockade as a validated human ADHD treatment.''',
'A partial inverse agonist reduces receptor-related signaling at its modulatory site rather than acting as the transmitter itself. The investigators used a pharmacological stressor to limit habituation associated with repeated physical stress. Anatomical control infusions test whether the protective effect requires delivery near the prefrontal region implicated in the task.')

add('SHR persist in drinking despite an aversive consequence','shr',['shr_task','shr_drinking'],
'''Kim and colleagues used an **electro-foot-shock aversive drinking task** to examine action restraint in SHR and WKY rats. After two training days without punishment, animals could obtain water in a designated compartment. During testing, at least 5 s of drinking triggered a 0.5-s foot shock.||SHR entered the water area more often and completed punished drinking more frequently than WKY controls. Methylphenidate at 2 or 5 mg/kg reduced punished drinking but did not reduce water-area entry frequency. The same medication therefore affected two operational outcomes differently within this preparation.||Persistence in a punished action is consistent with impaired restraint, but entry into the area is not equivalent to completing that action. The test does not isolate delay-dependent choice or sustained visual attention. Its interpretation depends on excluding differences in thirst, punishment sensitivity and familiarity with the apparatus.''',
'The rat can enter the compartment without drinking long enough to receive shock. Those stages involve different opportunities for restraint, so the medication’s selective effect cannot be summarized as a uniform suppression of all approach behavior. The control strain is part of the experimental comparison rather than a universal reference for every rat behavior.')

add('Behavioral controls constrain the SHR interpretation','shr',['shr_controls','shr_animals'],
'''A **confound** is an alternative factor that could account for a measured difference. Kim and colleagues assessed locomotion, water consumption, shock-related freezing, elevated-plus-maze behavior and water-area recognition. These controls tested alternatives to an action-restraint explanation of the punished-drinking result.||SHR traveled farther in a 20-min open-field test. However, the strains did not differ in locomotion during apparatus training, measured water consumption, shock-related freezing or the tested anxiety-related measures. Both located the water region during training, limiting a simple failure to learn the apparatus as an explanation.||The controls support the authors’ interpretation without proving that every motivational or sensory variable is identical. Open-field hyperactivity and punished drinking remain distinct phenotypes. A negative result in one control assay constrains that measured factor under those conditions rather than excluding all effects of stress, learning or pain.''',
'Anxiety-related behavior in an elevated plus maze is an operational measure, not a complete readout of emotional state. Shock-related freezing similarly tests one response to punishment. Their value lies in checking plausible alternatives with separate measurements while preserving the limits of each assay.')

add('DAT deletion greatly prolongs extracellular dopamine','dat phasic',['dat_clearance','phasic_anatomy'],
'''A **knockout** removes functional expression of a gene. Leo and colleagues deleted functional DAT in rats and measured dopamine after electrical stimulation of striatal slices. **Fast-scan cyclic voltammetry** detects rapid electrochemical changes and uses the oxidation–reduction signature to identify dopamine-related signals.||Following a 1-ms stimulus, average clearance took approximately 1.3 s in wild-type slices, 10 s in heterozygotes and 50 s in knockout tissue. A **heterozygote** carries one disrupted and one functional gene copy. The prolonged signal links transporter loss to the persistence of extracellular transmitter.||Transporter deletion changes clearance rather than proving increased release per spike. Comparative rat sections provide forebrain context; they are not recordings from the slice experiment. Lifelong gene deletion can also alter synthesis, receptors and other compensatory processes, so the phenotype cannot be reduced to one acutely blocked transporter.''',
'The color voltammetry panels are the authors’ original measurements, with applied potential and time preserved. The decay of an evoked signal reflects removal as well as the release that initiated it. Comparing wild-type, heterozygous and knockout tissue tests how functional transporter expression influences that decay.')

add('Hyperactivity and cognitive deficits can coexist','dat',['dat_activity','dat_cognition'],
'''Leo and colleagues measured locomotion and cognition in DAT-knockout rats rather than treating one assay as the complete phenotype. Movement was elevated in both home-cage recordings and novel test chambers. Twenty-four-hour recordings also distinguished light- and dark-period activity.||Knockout animals displayed lower spontaneous alternation and impaired **prepulse inhibition**, reduced suppression of a startle response when a weaker sound precedes the startling stimulus. Methylphenidate at 1.5–5 mg/kg reduced knockout hyperlocomotion, whereas it increased locomotion in transporter-intact animals.||A medication-related reduction in movement is not itself proof of restored attention or a diagnosis of ADHD. The same genetic manipulation changes transmitter clearance, behavior and developmental physiology. Spontaneous alternation and sensorimotor gating identify additional impairments, but neither directly establishes a premature-response deficit in the two-choice attention task.''',
'Spontaneous alternation concerns the sequence of an animal’s exploratory choices, while prepulse inhibition concerns modulation of a reflexive startle. Hyperactivity is yet another measured output. Their coexistence supports a broad phenotype while preventing an improvement in one test from being assumed to rescue all the others.')

add('Lphn3 loss changes prefrontal dopamine decay','phasic',['lphn3','phasic_anatomy'],
'''**Latrophilin-3**, encoded by _Lphn3_, is an adhesion G-protein-coupled receptor associated with synapse formation. Sable and colleagues compared knockout rats with wild-type littermates using **fixed-potential amperometry**, an electrochemical method that records oxidation current at a constant electrode potential. Rats were anesthetized during these measurements.||The medial forebrain bundle was stimulated at 50 Hz; prefrontal measurements used 50 pulses of 0.5-ms duration. Medial-prefrontal dopamine peak amplitude did not differ by genotype, but the **half-life**, the time for the evoked increase to fall by half, was longer in knockout rats.||The result supports slower prefrontal signal decay without a detected difference in the measured release peak. Half-life is a clearance-related readout, not direct proof of a DAT-specific mechanism in low-DAT cortex. NET-mediated uptake and other removal processes complicate a transporter-specific interpretation; ongoing task-related attention was not measured during anesthesia.''',
'The medial forebrain bundle contains axons linking midbrain dopamine populations with forebrain targets. Electrical stimulation evokes a controlled response but does not reproduce every naturally occurring burst during behavior. The genotype comparison separates the height of that response from its duration, which can change independently.')

add('SHR dopamine differences are region-specific','phasic',['shr_release','phasic_anatomy'],
'''Sable and colleagues used the same stimulation-and-amperometry strategy to compare SHR with WKY controls. **Phasic signaling** is a transient change associated with brief neuronal activity, distinct from a sustained background concentration. Recordings sampled medial prefrontal cortex and nucleus accumbens core separately.||SHR had lower stimulation-evoked dopamine release in accumbens core, but no detected strain difference in prefrontal peak amplitude or half-life. Accumbens half-life also did not differ. Accumbens stimulation used 20 pulses at 50 Hz, whereas prefrontal stimulation used 50 pulses at the same frequency.||The result argues against a uniform dopamine deficit across the sampled regions. A regional release ratio is not a direct measurement of communication or electrical coherence between the regions. Different stimulation protocols and anatomical sampling must be retained when comparing the absolute sizes of cortical and accumbens signals.''',
'A lower peak with unchanged decay time differs mechanistically from a preserved peak with prolonged decay. The SHR and Lphn3 comparisons therefore cannot be summarized as identical dopamine abnormalities. The assays examine an evoked response under anesthesia rather than transmitter fluctuations while the animal decides whether to wait or choose a delayed reward.')

add('Rat models respond differently to uptake inhibition','phasic',['lphn3_drug','shr_drug'],
'''Sable and colleagues administered **nomifensine**, a catecholamine uptake inhibitor used here to test dopamine-clearance-related responses. A 10-mg/kg intraperitoneal dose was followed by accumbens-core measurements, with the 20-min response compared against each animal’s predrug baseline. **Intraperitoneal** administration delivers a substance into the abdominal cavity.||Nomifensine increased the evoked dopamine peak proportionally more in Lphn3-knockout than wild-type rats. The corresponding percent change did not differ between SHR and WKY controls. The drug-related half-life change did not differ by genotype or strain, and the measured autoreceptor responses also lacked a group difference.||An **autoreceptor** detects a neuron’s own transmitter and can regulate subsequent release. These results distinguish model-specific responses to the same intervention, rather than identifying one universal ADHD dopamine mechanism. Percent-of-baseline amplification does not establish identical absolute concentrations, clinical treatment efficacy or attention improvement.''',
'The Lphn3 and SHR comparisons each use their own appropriate control population. A larger proportional increase can depend on the baseline as well as the postdrug response. The amperometric outcomes establish neurochemical differences; they do not directly test whether the same drug improves waiting, choice or distractor resistance.')

add('Sleep loss selectively weakens competition performance','fly',['fly_sleep','fly_control'],
'''Kirszenblat and colleagues sleep-deprived flies for 24 h using repeated mechanical stimulation. Sleep was operationally scored as at least 5 min of immobility. Deprived animals exhibited subsequent **sleep rebound**, increased sleep following its loss, and were tested on target fixation competing with visual motion.||Sleep loss increased target deviation when the target and distractor were combined, while isolated fixation and optomotor responses were largely preserved. After 24 h of rest, attention-like behavior returned toward control levels. Matched mechanical stimulation with alternating rest periods did not produce the same impairment.||These controls support state-dependent disruption of selection beyond a general motor or visual failure. They do not identify a specific transmitter pathway or establish that flies have ADHD. The fly preparation tests visual competition and sleep state, whereas the mammalian tasks measure cue-guided choice, restraint or spatial working memory.''',
'A matched-stimulation control preserves the total number of mechanical events while allowing extended opportunities to sleep. That comparison constrains an explanation based solely on physical disturbance. Preserved responses to isolated stimuli also separate selection under competition from basic detection and turning.')

add('Sleep-related rescue depends on fly genotype','fly',['fly_rescue'],
'''Kirszenblat and colleagues compared wild-type flies with **dunce** and **rutabaga**, learning-related mutants with altered cAMP signaling. Dunce affects a cAMP-degrading phosphodiesterase; rutabaga affects a cAMP-producing adenylyl cyclase. Both mutants showed poorer visual selection and altered sleep relative to controls.||The sleep-promoting GABA-receptor agonist **THIP** was supplied at 0.1 mg/ml in food for 2 days and removed 1 h before testing. It increased sleep in both mutant backgrounds, but improved target selection in dunce rather than rutabaga. Wild-type improvement was not clearly established.||Genotype-dependent rescue supports separable relationships among sleep, molecular state and selection. It does not establish that the fly mutations reproduce mammalian prefrontal D1–HCN circuitry, or that manipulating cAMP has the same effect across species. A shared molecule does not guarantee an identical circuit, task computation or treatment response.''',
'A phosphodiesterase breaks down the intracellular messenger, while adenylyl cyclase produces it. Those mutations alter different steps in cAMP regulation. The behavioral rescue following increased sleep remains a distinct experiment from local receptor and channel manipulations in mammalian prefrontal tissue; the common messenger does not make the preparations equivalent.')

assert len(S)==44,len(S)
# Portrait source panels receive full-height columns rather than compressed stacks.
for content,width in {2:2.5,18:2.7,20:3.0,23:4.3,24:2.3,25:2.2,33:3.1,35:3.0,36:2.3,37:3.6,38:4.3,39:3.5,40:3.6,41:3.7,42:3.6}.items():
 s=S[content-1]
 if s['layout']=='figures-right':s.update(figure_arrangement='side-by-side',primary_figure_width=width)
# Enlarge the source evidence within the existing text/figure columns.
for content,height in {18:3.1,20:1.8,23:1.7,33:2.6,38:2.1,42:3.0}.items():
 s=S[content-1]
 if s['layout']=='figures-right':
  s.pop('figure_arrangement',None);s.pop('primary_figure_width',None)
  s['primary_figure_height']=height
# V1 is localized in the published perturbation panel; the separate image targets PFC.
s=S[16];s['layout']='figure-right';s['figure']=s.pop('figures')[0]
# Balance uptake evidence with the prefrontal-release preparation image.
s=S[22];s['primary_figure_width']=3.5

# Paper models remain explicitly identified as authors' models in the teaching text.
takeaways=[
 ('Operational measures:','Accuracy, premature responses, delayed choice, working memory and locomotion measure different functions; an animal task phenotype does not establish a human ADHD diagnosis.'),
 ('Noradrenergic pathways:','In the tested mouse task, LC projections to dorsomedial prefrontal cortex improved distractor resistance, while ventrolateral orbitofrontal targeting reduced premature responses.'),
 ('Thalamic selection:','Prefrontal-dependent reticular modulation changes geniculate inhibition and visual gain according to the selected sensory modality.'),
 ('Receptor and channel context:','Adrenergic and D1 actions can sharpen prefrontal firing at suitable exposure; excessive D1 signaling can suppress delay activity through an HCN-sensitive mechanism.'),
 ('Regional dopamine regulation:','NET contributes to frontal dopamine uptake; DAT deletion prolongs striatal signals, while SHR and Lphn3 models have distinct regional and drug-response profiles.'),
 ('Comparative limits:','Sleep loss weakens fly selection under visual competition, and sleep-related rescue depends on genotype; shared behavioral measures or molecules do not establish identical circuits across species.')]
spec={'lecture':49,'theme':'rosewood-paper','content_slides':44,'title_height':3.1,'title_image':F['shr_animals'],'title_refs':[R['shr']['reference']],'slides':S,'takeaways':{'items':[{'lead':l,'text':t} for l,t in takeaways],'cite':'; '.join(C[k] for k in ['bari','wimmer','gamo','gamo15','moron','phasic','fly']),'refs':['References:']+[s['reference'] for s in R.values()]}}
(B/'lecture.json').write_text(json.dumps(spec,ensure_ascii=False,indent=2)+'\n')
plan={'lecture':49,'slides':[{'slide':i+2,'title':s['title'],'sources':s['cite']} for i,s in enumerate(S)]}
(B/'plan.json').write_text(json.dumps(plan,ensure_ascii=False,indent=2)+'\n')
(B/'spine.md').write_text('# Lecture 49 claim sequence\n\n'+ '\n'.join(f"{i+2}. {s['title']} — {s['cite']}" for i,s in enumerate(S))+'\n')
print('Wrote 44 primary-study content slides, title and six exam takeaways.')
