"""Lecture 26: measured behavior, peripheral receptors and central tactile coding."""
import json,re,html
from pathlib import Path
H=Path(__file__).resolve().parent;F=json.loads((H/'figure-sources.json').read_text());REF={};SHORT={}
for k in {x['paper']for x in F.values()}:
 d=json.loads((H/'sources'/f'{k}-crossref.json').read_text());year=2016 if k=='topo16'else d['published']['date-parts'][0][0]
 def person(a):return a['family']+' '+''.join(w[0]for w in a.get('given','').replace('-',' ').split())
 REF[k]=f"{', '.join(person(a)for a in d['author'])} ({year}). {re.sub('<[^>]+>','',d['title'][0]).rstrip('.')}. {html.unescape(d['container-title'][0])} {d['volume']}"+(f"({d['issue']})"if d.get('issue')else '')+f":{d.get('page',d.get('article-number',''))}. https://doi.org/{d['DOI']}"
 a=d['author'];SHORT[k]=a[0]['family']+(' & '+a[1]['family']if len(a)==2 else ' et al.'if len(a)>2 else '')+f' ({year})'
def fig(n):x=F[n];return {'kind':'article','path':x['out'],'caption':x['caption'],'source_url':x['source_url']}
slides=[]
def add(title,f,a,b,c,note,anatomy=None,also=()):
 names=[f]+([anatomy]if anatomy else[]);ks=list(dict.fromkeys([F[n]['paper']for n in names]+list(also)))
 s={'title':title,'layout':'figure-right','figure_width':5.6,'body':[a,b,c],'transcript':[[re.sub(r'\*\*|_','',a),[note]],re.sub(r'\*\*|_','',b),re.sub(r'\*\*|_','',c)],'cite':'; '.join(SHORT[k]for k in ks),'refs':[REF[k]for k in ks],'figure':fig(f)}
 if anatomy and f not in ('stretch','responseclasses','transcript','qpcr','cngaganglia','onoff'):
  s.pop('figure');s.update(layout='figures-right',figure_width=5.9,primary_figure_height=3.1,figures=[fig(f),fig(anatomy)])
  if f in ['foveation','surround','distance','duration','afferentstar','velocity','raysize','density2','embryo','perorgan']:
   s.update(figure_arrangement='side-by-side',primary_figure_width=3.8)
 slides.append(s)

add('The star is a tactile surface for finding small prey','animal',
'The star-nosed mole, _Condylura cristata_, searches wetland substrates using 22 fleshy nasal rays. **Tactile sensing** means detecting mechanical contact rather than detecting airborne chemicals. The rays contact surrounding surfaces; they do not function as fingers that grasp food.',
'Catania and Kaas filmed captive animals from beneath transparent tunnel floors and scored which rays touched earthworm pieces. Contact initially occurred across the star, but subsequent exploration concentrated on the paired ventral eleventh rays, immediately in front of the mouth.',
'This directed sampling establishes a behavioral specialization within one sensory surface. The star provides broad initial coverage while a small region repeatedly inspects potential prey. Observations of normal behavior alone cannot identify the receptors or brain pathways necessary for selecting that region.',
'The term ray refers to one fleshy appendage surrounding a nostril. Eleven rays surround each nostril; matching ray numbers on the two sides describe corresponding positions.',also=('fovea97',))
add('Brief touches alternate with rapid searching movements','touchcycle',
'Catania and Remple recorded feeding through a glass-bottom tunnel at 500 frames per second. This **high-speed videography** separated periods of substrate contact from movements between contacts. Earthworm fragments supplied prey while the transparent floor preserved a clear view of the star.',
'Search movements lasted about 50 ms and touches about 25 ms, producing approximately 13 contacts per second. A contact could initiate feeding or be followed by another searching movement. Thus sensory sampling is intermittent even though the animal appears to explore continuously.',
'The timing describes the recorded laboratory search sequence, rather than a fixed rate under every natural condition. It constrains the time available for extracting information during each encounter but does not identify the neuronal decision or establish that cortical processing ends when contact ends.',
'At 500 frames per second, consecutive recorded frames are separated by 2 ms. The time labels in the published sequence are measurements of behavior, not spike times.')
add('Prey contact redirects the star toward ray 11','foveation',
'**Foveation** is movement that places a region of high sensory resolution onto a target. Catania and Kaas scored successive contacts in video recordings of feeding. The initial contact could involve a lateral ray; later contacts brought the prey toward the paired eleventh rays.',
'The original recordings used 30 frames per second, so frame numbers identify successive observations rather than millisecond-precise neural events. In individual encounters, the entire star changed position until ray 11 contacted the item. This is active positioning of a sensory surface.',
'The repeated use of ray 11 justifies calling it a tactile fovea. Its behavior resembles target-directed visual fixation, but resemblance does not establish identical visual and tactile circuitry. The observations also distinguish sensory inspection by the star from the subsequent grasping action of the teeth.',
'A fovea is defined by preferential, high-resolution sampling, not merely by occupying the center of an organ. The mole moves its entire nasal star to align this ventral region with prey.',anatomy='starphoto')
add('Tiny prey can be identified and eaten within 120 ms','handling',
'**Handling time** is the foraging time lost while taking a prey item instead of searching for another. Catania and Remple measured it from the end of the first prey contact until eating finished and the star began another searching movement.',
'For earthworm pieces 0.8–2.0 mm across, mean handling time was 227 ms and observed times ranged from 120 to 440 ms. The measured interval included foveation, grasping and consumption. It therefore exceeds a sensory latency and cannot be interpreted as perception time alone.',
'These exceptionally short intervals establish rapid performance for small, prepared prey under laboratory conditions. Large prey, environmental obstacles and unsuccessful encounters impose other costs. The experiment does not show that every natural prey item is consumed in 120 ms or that a single neuron controls the whole sequence.',
'The end of handling is defined behaviorally by resumed searching. Using the same endpoint across trials prevents a comparison of swallowing in one trial with first tooth contact in another.')
add('A double take exposes a delay in the feeding decision','doubletake',
'In a **double take**, the star initially moves away from a contacted prey item, then reverses and places the fovea onto it. Catania and Remple identified these sequences in high-speed video, preserving the time course and prey position across consecutive frames.',
'Double takes occurred in more than one-third of their feeding trials. A typical contact lasted about 25 ms, whereas prior cortical recordings placed tactile response onset near 12 ms. The authors additionally estimated about 5 ms for a motor command to reach the periphery.',
'These timings support their proposal that fast sampling sometimes outruns the completed feeding decision. The motor estimate was not a direct measurement during these encounters, and the video does not prove that cortex causes the reversal. A processing-speed limit is an interpretation of converging evidence.',
'A mistaken initial movement lengthens handling without implying that the animal permanently misidentified the prey. The correction indicates that useful tactile information can continue to affect movement after the first response starts.',also=('response02',))
add('Short handling times make tiny prey profitable','profit',
'**Prey profitability** is energy gained per unit handling time. Catania and Remple combined video measurements with published energetic estimates to evaluate small earthworm pieces. Their original figure compares predicted profitability with measured handling times; its curves are the authors’ published model.',
'A typical small fragment supplied approximately 10 J, with handling near 230 ms. The authors reported profitability near 44 J/s. Larger earthworm segments supplied about 1,100 J but took approximately 19 s to handle, reducing the advantage of their greater energy content.',
'Rapid handling can therefore make tiny prey valuable even when individual items contain little energy. The energetic values were estimates rather than direct calorimetry in each feeding trial. Profitability also excludes search costs, so it alone cannot establish the preferred diet across different prey densities.',
'The red curve is retained exactly as published. Its continuous shape is a theoretical relationship; the feeding durations associated with the animal are separate empirical measurements.')
add('A larger receptor sheet increases sampled area','searcharea',
'Catania and Remple measured the contact surface from close-up behavioral recordings and compared star-nosed moles with eastern moles, _Scalopus aquaticus_. **Sensory coverage** refers here to the area touched during one sampling event, rather than the sensitivity of an individual receptor.',
'The star contacted approximately 0.92 cm² per touch, compared with 0.11 cm² for the eastern mole’s snout. Search rates were about 13 and eight contacts per second, respectively. Combining coverage and rate predicted roughly fourteenfold greater encounter opportunity at equal small-prey density.',
'This comparison links expanded anatomy to a plausible search advantage. The encounter estimate assumes equivalent distributions and independent sampling; it was not a measured fourteenfold increase in captured prey. Eastern moles also did not eat the smallest items accepted by star-nosed moles.',
'Area per touch and the number of touches per second affect encounter opportunity independently. A dense receptor array cannot compensate for failing to bring the sensory surface into contact with an item.',anatomy='starphoto')
add('Specialized incisors complete close-range prey capture','dentition',
'After foveal inspection, the star-nosed mole captures small prey using its front teeth. Catania and Remple examined the dentition with scanning electron microscopy and compared it with eastern mole incisors. **Incisors** are the anterior teeth involved here in grasping, not sensory organs.',
'The star-nosed mole’s incisors are reduced and arranged in a tweezer-like configuration. High-speed sequences associate their use with the final movements of the star during capture of fragments as small as 0.8 mm across. Their proximity to the fovea minimizes the required approach.',
'The anatomical comparison and behavior support coordinated sensory and feeding specializations. They do not measure tooth force or establish an evolutionary sequence through a tooth-removal experiment. Selection for rapid handling is the authors’ explanatory proposal, supported by performance and morphology rather than directly observed historical selection.',
'The star detects and positions the target; the incisors grasp it. These are different mechanical functions even though they occur within a single brief feeding response.',anatomy='handling2')
add('Eimer’s organs tile the contact surface','starsem',
'An **Eimer’s organ** is a small epidermal sensory unit containing several types of nerve ending. The **epidermis** is the outer cellular layer of skin. Sawyer and Catania used scanning electron microscopy to map these units across the flattened front surface of the star.',
'The star contains roughly 25,000 organs across its 22 rays. Surface images reveal separate domes packed into a repeated array, making receptor-unit position measurable directly. Unlike many mammalian touch receptors, each unit has an external structure that can be identified without tracing its entire innervation.',
'The visible dome is not equivalent to one neuron: several endings supply an organ, and individual fibers may branch. Counting organs measures the distribution of anatomical units, not independent neural channels. Tissue flattening and preparation must also be considered when comparing measurements with the living, moving star.',
'A sensory unit can contain multiple transducers with different response properties. Surface microscopy identifies unit boundaries but does not assign their functional receptive fields.',anatomy='starphoto',also=('fovea97',))
add('Central and peripheral endings occupy distinct rings','historgan',
'Marasco and colleagues used fluorescent dyes and confocal microscopy to examine star-nosed mole Eimer’s organs. **Confocal microscopy** resolves selected optical depths, allowing the arrangement of nerve terminals to be compared in horizontal and vertical tissue sections rather than inferred from the surface alone.',
'About 15 µm below an organ’s apex, a central ending was surrounded by seven satellite fibers in the illustrated specimen. A second, outer ring contained smaller peripheral endings. Near the surface, terminal swellings of the satellite fibers approached the central terminal.',
'This organization provides several potential contact-sensitive elements within one dome. The ring arrangement is anatomical evidence; assigning separate signals for direction or pain requires physiological or molecular tests. A counted ring in one section does not establish an invariant number of endings in every organ.',
'An apex is the top of a sensory dome. An optical section at a specified depth samples a different part of an ending from a section through its final superficial swelling.',anatomy='organstain')
add('Merkel cells form complexes with sensory neurites','merkel',
'A **Merkel cell–neurite complex** couples a specialized epidermal cell to a sensory axon ending. Marasco and colleagues resolved these complexes near the base of star-nosed mole Eimer’s organs using dye labeling. The labeled neurite formed a disk associated with the Merkel cell.',
'Horizontal and vertical sections distinguished the neurite disk from the Merkel cell body. The neurite stained more strongly than the cell in the illustrated preparation, and the original panels retain 10-µm scale bars. The complex is separate from the superficial central and satellite endings.',
'Its position and morphology support a receptor system for maintained contact, but morphology alone does not identify its firing pattern. The physiological study found Merkel-like slowly adapting responses; these were assigned by response characteristics rather than by tracing each recorded axon to a labeled complex.',
'A neurite is a neuronal process; the disk is the terminal part contacting the Merkel cell. Dye brightness should not be converted into a quantitative estimate of membrane current.',anatomy='organstain',also=('afferent07',))
add('Lamellated corpuscles add a deep receptor component','corpuscle',
'A **lamellated corpuscle** contains a sensory ending surrounded by layered tissue. Marasco and colleagues localized this structure beneath the epidermis in Eimer’s organs. The terminal neurite ran through the capsule and lay approximately parallel to the skin surface.',
'The illustrated star-nosed mole organ contained one corpuscle, whereas coast mole organs commonly contained one or two. Dye labeled the sensory terminal while the surrounding capsule remained relatively unlabeled. The original 10-µm scale bar places this receptor below the much larger external ray.',
'The arrangement is consistent with sensitivity to changing mechanical input. Pacinian-like rapidly adapting responses were independently recorded from mole nasal afferents, but anatomical resemblance does not prove that every such response originated in this particular terminal. The skin unit integrates several receptor components.',
'The capsule and axon ending are different structures. A fluorescent terminal inside an unlabeled capsule supports anatomical localization without establishing how the capsule mechanically filters a stimulus.',anatomy='organstain',also=('afferent07',))
add('Molecular markers separate touch-associated endings','segregation',
'**NF200** is a neurofilament marker associated with many large, myelinated sensory fibers. **Substance P** is a neuropeptide associated with a subset of pain-signaling neurons. Marasco and colleagues double-labeled coast mole Eimer’s organs to compare these populations within the same structure.',
'Central and satellite endings labeled for NF200, whereas the outer peripheral ring labeled for substance P. Gerhold and colleagues subsequently found strong NF200 staining and sparse peripheral substance-P staining in star-nosed mole organs. The two studies distinguish terminal position from a single undifferentiated ring.',
'These markers support light-touch and nociceptive specialization, but do not directly measure transmitter release or behavioral pain. A **nociceptor** detects potentially damaging stimulation. Marker identity and anatomical position suggest function; a definitive functional assignment requires recording or selective intervention in the labeled fibers.',
'The coast-mole micrographs provide the clearest double-label comparison; the accompanying star-nosed mole panel supplies species-specific anatomy. Published fluorescence colors are preserved, including the original overlapping labels.',anatomy='organstain')
add('Dye fills reveal branching within the organ','dye',
'Marasco and colleagues applied **DiI**, a lipophilic dye that spreads within cell membranes, to trace free nerve endings in star-nosed mole Eimer’s organs. Tracing tests whether nearby terminal profiles belong to separate fibers or share an underlying neuronal process.',
'The central and satellite terminals could label together within a single organ. Adjacent organs sometimes also contained labeled central and satellite profiles. Across optical sections, the dye revealed branches and terminal swellings that would otherwise resemble separate isolated points.',
'These observations support branching of afferents across the organ’s specialized endings. Dye spread depends on exposure and membrane continuity, so an unlabeled profile does not prove lack of innervation. Tracing also identifies anatomy rather than mechanical threshold, electrical coupling or a synaptic connection between terminal profiles.',
'A branch can distribute one axon’s peripheral territory without adding another ganglion cell. Organ counts, terminal counts and sensory-neuron counts therefore measure different levels of the system.')
add('Separate nerve branches supply individual rays','bundles',
'Catania and Kaas sectioned the base of the star and examined its myelinated nerves. **Myelin** is the insulating sheath around many axons. A **primary afferent** is a sensory neuron carrying peripheral information toward the central nervous system.',
'One branch supplied each of the 11 rays on a side. Thin sections exposed separate nerve bundles and individual myelinated fibers, allowing counts to be related to the corresponding ray’s sensory organs and cortical stripe. This preserves the anatomical identity of peripheral inputs during comparison.',
'The branch arrangement provides a tractable way to measure afferent allocation, but myelinated-fiber counts omit unmyelinated fibers. They also do not specify the number of receptor endings supplied by each axon. Counting fibers and counting organs are complementary measurements, rather than interchangeable estimates of sensory resolution.',
'A nerve branch is a bundle containing many axons. The investigators counted profiles within those bundles; the bundle itself is not one functional sensory channel.',anatomy='organstain')
add('Ray 11 has more afferents per sensory organ','innervation',
'Catania and Kaas combined Eimer’s-organ counts with myelinated-fiber counts for each ray. **Innervation density per organ** describes the number of counted afferents relative to the number of anatomical sensory units, rather than the number of domes per square millimeter.',
'The small eleventh ray contained relatively few organs but the highest number of afferents per organ. Organ surface density did not display an equivalent special peak at ray 11. Foveal specialization therefore includes differences beneath the sensory surface that dome counts alone miss.',
'This association supports richer neural sampling of the foveal organs. It does not establish one independent signal for every counted fiber or prove that innervation alone determines behavioral acuity. Branching, response properties and central allocation all affect how the same anatomical surface can be represented.',
'An organ can have typical spacing while receiving unusually many sensory fibers. This distinguishes peripheral neural investment from a claim that the fovea simply contains the greatest number of visible domes.',anatomy='density2')
add('Receptor density rises toward the ray tips','density',
'Sawyer and Catania measured Eimer’s-organ positions on flattened stars using scanning electron microscopy. **Eccentricity** here means normalized distance along a ray from its base toward its tip. Comparing this coordinate across rays separates longitudinal position from ray identity.',
'Mean density increased from about 228 organs/mm² near the star center to 391 at ray bases, 516 in middle regions and 718 near the tips. Density rose near the base, plateaued through much of the ray, then increased again in its distal portion.',
'The gradient suggests that contact location changes the density of sampled units even within one ray. It does not directly measure a matching gradient in discrimination thresholds. Flattened-surface measurements and original fitted curves describe anatomy; they are not recordings of receptor activity during active searching.',
'The heat maps retain the authors’ original scale and colors. Their color represents measured organ density, not cortical magnification or the sensitivity of an individual axon.')
add('The fovea lacks an exceptional dome-density peak','density2',
'Sawyer and Catania compared receptor density across numbered rays while accounting for position along each ray. The distinction matters because distal regions are more densely packed than basal regions. Comparing an entire foveal ray with another ray’s tip would mix two effects.',
'Ray 11 did not possess higher overall Eimer’s-organ density than the other rays. Nevertheless, Catania and Kaas found much greater cortical area per organ for ray 11. The tactile fovea therefore differs from an explanation based solely on extra receptor units per surface area.',
'The findings establish a mismatch between dome density and central allocation. They do not rule out specialized ending types, greater afferent investment per organ or mechanical differences in foveal skin. Central magnification is one measured contributor, rather than a complete explanation of every aspect of foveal acuity.',
'The same anatomical density can support different neural representations. More cortical tissue assigned to an organ is not the same variable as more organs assigned to a millimeter of skin.',anatomy='perorgan')
add('Individual organ size varies across the star','organarea',
'Sawyer and Catania traced the frontal surface area of individual Eimer’s organs in scanning electron micrographs. **Surface area** here describes a dome’s visible footprint; it does not describe the receptive field of a recorded neuron or the full three-dimensional dome surface.',
'Large organs were generally more common near the star’s center, whereas smaller organs occurred toward densely packed distal regions. The published color maps preserve the measured values for individual units. In the examined stars, the largest organs had roughly 25 times the area of the smallest.',
'This spatial variation could change how a contacting object distributes force across sensory units. The study did not indent each mapped organ or measure its firing threshold, so a force-filtering role remains a proposed functional consequence. Anatomical size alone cannot identify which receptor component dominates a touch response.',
'A map of unit area is distinct from a map of unit density. Larger units can occupy more of the surface while fewer separate units fit into a given area.')
add('Peripheral afferents encode changing and held contact','afferentstar',
'Marasco and Catania recorded single sensory units from the trigeminal ganglion while controlled stimulators contacted the nose. **Adaptation** is a change in firing during continued stimulation. Their star-nosed mole traces compare responses to a maintained mechanical indentation rather than to freely chosen touches.',
'Some receptors fired throughout the static portion, producing slowly adapting, Merkel-like responses. Others responded mainly to changing indentation, giving rapidly adapting profiles; another rapidly adapting response produced a single onset impulse. The illustrated traces distinguish these patterns during 500-ms stimulation.',
'These classes provide complementary information about contact presence and contact change. Assignment to particular anatomical endings was based on response resemblance, not post-recording identification of every terminal. The recordings support multiple peripheral codes but do not establish their separate necessity for prey discrimination.',
'A rapidly adapting neuron can remain highly sensitive while becoming silent during an unchanged indentation. Silence in that interval reflects the stimulus feature it encodes, rather than failure of the sensory preparation.',anatomy='organstain')
add('Vibration tuning distinguishes afferent response classes','frequency',
'Marasco and Catania varied sinusoidal indentation frequency and amplitude in coast-mole nasal afferents. A **sinusoidal stimulus** repeatedly moves the skin inward and outward. This comparative preparation tests receptor dynamics in Eimer’s organs without assuming that all mole species have identical tuning.',
'Pacinian-like rapidly adapting units were most active near 250–300 Hz at relatively small displacements of about 10–28 µm. Other rapidly adapting units responded over broader ranges, approximately 5–150 Hz, especially at larger displacement amplitudes. Frequency preference therefore depended on receptor class and stimulus magnitude.',
'The results support parallel channels for distinct mechanical changes. These quantitative tuning measurements mainly concern coast moles; the star-nosed mole recordings established comparable response classes but not identical tuning curves. The putative anatomical assignments remain hypotheses because the recorded axons were not individually traced to terminal types.',
'A frequency peak is conditional on stimulus amplitude. Comparing two neurons at different amplitudes can confound frequency selectivity with their different indentation thresholds.',anatomy='segregation')
add('Some afferents respond best at natural contact speeds','velocity',
'Marasco and Catania tested ramp indentations in coast-mole afferents, changing onset speed while holding displacement at 500 µm. **Indentation velocity** describes how quickly the probe moves into the skin; it is separate from the final indentation depth and the duration of maintained contact.',
'The tested speeds extended to 84.5 mm/s. One velocity, 46.2 mm/s, matched the measured nose speed during foraging. Some rapidly adapting units followed every stimulus at this speed; two units changed firing non-monotonically as velocity increased rather than simply preferring the fastest ramp.',
'The findings support sensitivity to the temporal mechanics of natural sampling. They do not prove evolutionary tuning to a unique optimal velocity or establish the same numerical preferences in star-nosed moles. Skin geometry, preparation and afferent class can all influence the relationship between probe movement and neural discharge.',
'Keeping displacement constant makes velocity the intended variable. A higher spike count at one speed can still reflect that receptor’s mechanical filtering rather than an abstract neural representation of speed.',anatomy='segregation')
add('The trigeminal ganglion favors touch-associated neurons','TG',
'The **trigeminal ganglion**, or TG, contains sensory-neuron cell bodies serving the face. **Dorsal root ganglia**, or DRG, serve the body. Gerhold and colleagues compared these tissues in star-nosed moles using NF200 and peripherin, a marker associated with many small sensory neurons.',
'About 57% of TG neurons labeled for NF200 and 13% for peripherin. In DRG, the corresponding proportions were about 36% and 35%. Thus the face-associated ganglion had a different neuronal composition from the body-associated comparison tissue within the same animal.',
'The enrichment supports specialization of the input population supplying the star, rather than peripheral branching alone. Marker-defined groups are not exhaustive functional categories, and the TG supplies facial tissues beyond the star. Immunolabeling therefore motivates physiological tests instead of establishing a unique function for every labeled neuron.',
'A ganglion contains cell bodies outside the brain. Differences in this population can change what kinds of signals enter central pathways before cortical magnification occurs.',anatomy='DRG')
add('Stretch activates many cultured facial sensory neurons','stretch',
'Gerhold and colleagues isolated TG and DRG neurons and monitored intracellular calcium with **Fura-2**, a fluorescent calcium indicator. Neurons were cultured on deformable substrates, allowing a 10% radial stretch to be compared between tissues under a shared mechanical stimulation protocol.',
'Approximately 80% of TG neurons responded to stretch, compared with 34% of DRG neurons. The original images retain the authors’ calcium-response colors. This functional enrichment agrees with the greater fraction of touch-associated markers in the facial ganglion.',
'Cultured-cell deformation removes the intact organ’s capsule, epidermis and receptor geometry. A calcium rise reports cellular activation rather than the exact mechanically gated current or the number of propagated spikes. The comparison supports a mechanosensitive neuronal population, but does not directly measure tactile acuity in an exploring mole.',
'Calcium imaging can compare responsive fractions while leaving the initial transduction channel unresolved. Mechanical activation may recruit additional conductances before calcium increases enough to be detected.',anatomy='TG')
add('Chemical and mechanical sensitivity differ by ganglion','responseclasses',
'Gerhold and colleagues challenged cultured TG and DRG neurons with mechanical stimuli and chemical agonists. An **agonist** activates a receptor or channel. Capsaicin targets TRPV1, mustard oil targets TRPA1 and menthol targets TRPM8; these probes separate cellular sensitivities beyond anatomical marker labeling.',
'Capsaicin activated about 15% of TG neurons but 36% of DRG neurons. Mechanical stretch, hypotonic solution and hydroxy-alpha-sanshool activated greater fractions in TG. A **hypotonic solution** has lower solute concentration and can deform cells as water enters them.',
'The results support a sensory trade-off favoring facial mechanosensitivity over several chemical sensitivities. They do not show that the star lacks pain detection, because some TG neurons responded and the tested agonists cover only selected pathways. Dissociated cells also cannot identify how these signals guide natural feeding.',
'TRP denotes a family of transient receptor potential ion channels. Their activation can depolarize a neuron, but a chemical sensitivity in culture does not identify that neuron’s complete natural stimulus range.',anatomy='DRG')
add('Transcript comparisons reveal molecular specialization','transcript',
'Gerhold and colleagues used **RNA sequencing** to measure expressed messenger RNAs in TG and DRG. A **transcriptome** is the collection of these RNA transcripts. Because an annotated star-nosed mole genome was unavailable, reads were aligned successively against human, dog and mouse transcript sequences.',
'The approach assigned approximately 42–65% of sequenced reads. Thousands of genes differed between the two mole ganglia. A parallel mouse TG–DRG comparison helped separate differences shared across mammals from those potentially associated with the mole’s unusually specialized facial sensory population.',
'This comparison identifies expression patterns, not receptor function. Incomplete cross-species alignment can miss divergent transcripts, and bulk tissue includes neurons and supporting cells. A higher transcript abundance can reflect more cells of one type rather than greater expression in each neuron.',
'RNA abundance is several steps removed from behavior: a transcript must produce protein, the protein must act in an appropriate cell, and its activity must contribute to a relevant sensory response.',anatomy='ontology')
add('Expression nominates channels without proving causality','channels',
'An **ion channel** is a membrane protein that permits ions to cross the cell membrane. Gerhold and colleagues focused their expression comparison on channels and modulators. Facial-ganglion candidates included ASIC3, Piezo1, cyclic-nucleotide-gated channels and stomatin-related proteins.',
'DRG enrichment included TRPV1, TRPA1, TRPM8 and sodium-channel genes associated with nociceptive neurons. Piezo2 was also DRG-enriched in this dataset, despite its proposed mechanosensory role. Enrichment therefore did not divide every known mechanosensory candidate neatly into the facial ganglion.',
'These results nominate molecules for functional testing rather than assigning a complete star transduction pathway. No targeted mole knockout established which candidate converts dome deformation into current. The unusual expression contrast also cautions against transferring a receptor’s function from another species without testing its cell type and context.',
'The published conductance table is retained as an original article panel. Channel enrichment and channel conductance are different properties: abundant expression does not determine the effect of opening the channel.',anatomy='organstain')
add('Independent assays qualify the expression screen','qpcr',
'**Quantitative PCR**, or qPCR, measures selected RNA targets independently of a sequencing screen. Gerhold and colleagues tested several TG- and DRG-enriched candidates, normalizing their expression to a reference transcript. Agreement across assays strengthens an expression claim while leaving function unresolved.',
'Cnga2 and Stoml3 were more highly expressed in TG, whereas Trpa1 and Trpv1 were more highly expressed in DRG. Fam38a, the Piezo1 gene, followed the TG-directed trend but its qPCR difference was not established convincingly in this follow-up assay.',
'The qualification prevents treating every sequencing candidate as independently confirmed. Expression measurements neither show that a channel is mechanically gated in the mole nor identify its physiological contribution. Stomatin-related proteins may modulate channels, so an enriched molecule need not itself form the pore carrying a transduction current.',
'A reference transcript supplies a common normalization baseline. It does not correct every possible difference in tissue composition, RNA preservation or cell-type abundance.',anatomy='TG')
add('CNGA2 protein occurs in touch-associated cells','cngaganglia',
'**CNGA2** is a cyclic-nucleotide-gated channel subunit. Such channels can respond to intracellular cyclic nucleotides; expression does not make them automatically direct mechanical detectors. Gerhold and colleagues tested whether the RNA enrichment corresponded to detectable protein in star-nosed mole sensory ganglia.',
'Immunofluorescence revealed a larger fraction of CNGA2-positive cells in TG than DRG. These cells also displayed strong NF200 labeling. In peripheral Eimer’s-organ fibers, more than 90% of CNGA2-positive profiles also labeled for NF200, linking the candidate to touch-associated anatomy.',
'This provides spatial validation beyond a bulk RNA comparison. It remains evidence of protein localization, not a recorded CNGA2 current or a demonstrated requirement for prey capture. Antibody staining also cannot establish the complete channel-subunit composition or which intracellular pathway gates it during a touch.',
'Co-labeling associates proteins with the same cellular profiles at the resolution of the assay. It does not establish a physical protein complex or direct interaction between CNGA2 and neurofilament.',anatomy='cngafibers')
add('Cross-species tests retain candidates for functional work','mouse',
'Gerhold and colleagues examined candidate channels in mouse sensory ganglia using **reverse-transcription PCR**, which detects RNA after converting it to DNA. The mouse supplied a more experimentally tractable comparison, rather than a replacement measurement of the mole’s sensory behavior.',
'About 85% of the strongest mole ganglion-enriched channel candidates were detected in mouse TG and DRG. Additional qPCR confirmed expression of cyclic-nucleotide-gated subunits, Piezo1 and selected TRP channels. Detection in both tissues established availability for further testing, not identical expression patterns across species.',
'The approach connects a specialized animal’s molecular screen with possible mechanistic experiments. It does not show that mouse channels explain the mole’s tactile fovea or that expression causes cortical expansion. Species differences in receptor anatomy and neuronal composition remain relevant even when an orthologous gene is present.',
'An orthologous gene is a corresponding gene inherited from a common ancestor. Shared sequence identity permits comparisons while leaving species-specific expression and physiological roles open.',anatomy='cngafibers')
add('The principal trigeminal nucleus is enlarged','PrVcompare',
'The **principal trigeminal nucleus**, or PrV, is a brainstem relay for facial mechanosensory input. Catania, Leitch and Gauthier compared stained brainstem sections from star-nosed and hairy-tailed moles, _Parascalops breweri_, relating central anatomy to their different nasal receptor surfaces.',
'PrV in the star-nosed mole was greatly expanded and bulged from the brainstem toward the incoming trigeminal nerve. Cytochrome-oxidase staining revealed strong internal subdivisions. The adjacent spinal trigeminal complex provided an anatomical comparison rather than evidence that all facial nuclei expanded equally.',
'The enlargement establishes a major specialization before signals reach cortex. Tissue size alone does not reveal individual synaptic strength, firing rate or the neurotransmitter responsible. The study combined histology with receptive-field mapping to determine whether the visible subdivisions actually represented specific rays.',
'Cytochrome oxidase is a metabolic enzyme used to reveal tissue organization. A darkly stained module is an anatomical compartment, not a direct quantitative recording of momentary neural activity.')
add('Eleven brainstem modules correspond to eleven rays','PrVstar',
'**Somatotopy** is an orderly relationship between positions on the body and their neural representations. Catania and colleagues sectioned PrV at an orientation that exposed its ray-related compartments. The star’s separate peripheral rays supplied a natural set of identifiable sensory territories.',
'Appropriately oriented sections revealed 11 modules corresponding to the 11 rays on one side of the nose. Ray 11 had a particularly large representation despite its small peripheral size. The modules formed a star-like arrangement, but the tissue is a relay nucleus rather than a miniature physical nose.',
'The histological pattern supports a topographic organization, and electrophysiology tested the assignments. A visible outline alone cannot distinguish local neurons from traversing axons or establish the precise projection to the next relay. The module correspondence depends on relating anatomy to responses from controlled stimulation.',
'The brainstem star is a map of ray identities. Its dimensions represent allocated neural tissue and need not preserve the physical dimensions of the skin.',anatomy='brainsection')
add('Recordings validate the brainstem ray assignments','PrVmapping',
'Catania and colleagues recorded neural responses while gently stimulating identified nasal rays. They marked selected electrode locations with small lesions, then aligned these marks with stained sections. A **receptive field** is the peripheral region whose stimulation changes a recorded neuron’s activity.',
'Responses encountered along penetrations changed according to the module entered. Lesion positions and serial sections related these functional assignments to the 11-module PrV pattern. The paired record of stimulation territory and recording location is stronger evidence than labeling modules from resemblance alone.',
'The results establish ray-related activity within PrV. Some penetrations also encountered trigeminal-nerve or spinal-nucleus responses, so location had to be checked anatomically. These experiments did not isolate every synaptic input or show that a given module is behaviorally necessary through selective inactivation.',
'A recording lesion marks the electrode’s position after physiological measurements. It is a localization tool here, rather than an experimental lesion used to measure a loss of feeding behavior.',anatomy='PrVmapping2')
add('Foveal magnification increases beyond the brainstem','PrVallocation',
'Catania and colleagues reconstructed serial PrV sections to measure each ray representation’s volume. They compared these volumes with previously measured myelinated-afferent counts and S1 cortical areas. **Magnification** describes unequal allocation of neural tissue to different regions of the sensory surface.',
'The reconstructed star subnucleus averaged about 7.1 mm³. Ray 11 supplied about 11% of the star’s counted afferents, occupied 14% of its PrV representation and occupied 25% of the S1 star representation. Foveal investment therefore increased across these measured stages.',
'The comparison establishes a distributional transformation rather than a uniform scaling of the periphery. Brainstem volume and cortical surface area have different units, so their absolute numerical values cannot be directly equated. Nor do these anatomical proportions identify where each additional synapse or neuron is added.',
'Comparing proportions within each structure avoids confusing cubic millimeters of brainstem with square millimeters of cortex. The measured percentages refer to the star representation, not the entire brain.',anatomy='PrVcompare')
add('The cortical star consists of histological stripes','cortex',
'**Primary somatosensory cortex**, or S1, is a cortical area receiving somatic sensory information. **Secondary somatosensory cortex**, or S2, is another processing area with its own map. Catania and Kaas flattened cortex and cut tangential sections to expose its ray-related organization.',
'Cytochrome-oxidase processing revealed two pinwheel-like sets of stripes, corresponding to S1 and S2 star representations. Electrophysiological mapping associated stripes with tactile input from rays on the opposite side of the nose. The foveal ray occupied an especially large S1 territory.',
'The visible stripes allow anatomical area to be compared with measured peripheral innervation. They do not imply that cortex is divided into isolated channels without interaction. The staining also does not specify the neurotransmitters or ion channels used by neurons within a stripe; those require separate cellular experiments.',
'A tangential section runs approximately parallel to the cortical surface. Flattening makes the map easier to measure, while changing the tissue’s original three-dimensional configuration.',anatomy='starphoto')
add('Afferent number does not fully explain cortical area','perfiber',
'Catania and Kaas defined **afferent magnification** as cortical representational area per primary sensory afferent. They divided measured S1 ray territories by the corresponding myelinated-fiber counts. This differs from cortical area per skin area or per Eimer’s organ.',
'Ray 11 retained the largest cortical allocation after normalization by afferent number. The later PrV analysis found a much smaller foveal excess at the brainstem stage. Thus the unusually large S1 fovea cannot be explained simply by every incoming fiber receiving identical cortical space.',
'The result establishes unequal central investment per counted input, but not a complete causal mechanism. Myelinated counts omit other inputs, and cortical area does not directly measure processing capacity. The association with preferential behavioral use is consistent with functional specialization without proving that repeated use produced the map.',
'Normalization asks whether a difference remains after accounting for a measured input variable. A remaining difference is evidence against that variable being the sole explanation; it does not identify the only alternative mechanism.',anatomy='magnification')
add('Foveal receptive fields are exceptionally small','fields',
'Sachdev and Catania mapped excitatory receptive fields while recording multiunit activity in anesthetized moles. A fine glass probe contacted individual parts of the star under a microscope. **Multiunit activity** combines spikes from nearby neurons, so its field differs from a single isolated neuron’s field.',
'Mean excitatory field area was 0.59 mm² on ray 11 and 0.82 mm² on rays 1–10. Boundaries were sharply defined by the fall in evoked activity outside each field. Most fields occupied a continuous patch within one ray rather than spanning the whole star.',
'The smaller foveal fields support finer spatial sampling in the disproportionately large representation. The measurements do not constitute a behavioral discrimination threshold, and anesthesia may alter network responses. Probe-based mapping also depends on the contact region and the criterion used to recognize a response.',
'A small receptive field means that local contact can activate a more restricted neuronal population. It does not by itself determine how reliably an animal discriminates two nearby objects.',anatomy='cortex')
add('Controlled indentation separates contact from movement','population',
'Sachdev and Catania isolated cortical units and stimulated the mapped field with a piezoelectrically controlled probe. **Piezoelectric actuation** converts an applied voltage into a small mechanical displacement. Stimuli lasting 5 or 500 ms separated brief contact from a prolonged hold.',
'The probe was approximately 0.2–0.5 mm across and depressed the skin about 200 µm. The authors recorded baseline spontaneous activity and compared responses at different locations. Mean excitatory onset latency was 11.6 ms, similar for brief and prolonged stimuli.',
'The common onset latency supports fast transmission that is not simply determined by total contact duration. The preparation controlled indentation rather than natural prey shape, and recorded activity under anesthesia. It therefore constrains sensory timing without establishing the entire awake decision pathway or a particular transduction channel.',
'A poststimulus time histogram pools spike timing relative to stimulus onset. Its peak describes a response across trials; it should not be interpreted as every trial producing a spike at the same instant.',anatomy='cortex')
add('Contact onset and release evoke distinct responses','onoff',
'Sachdev and Catania measured cortical firing during 500-ms indentations. An **ON response** is evoked at contact onset; an **OFF response** follows its release. The two events can both change mechanical strain even though their effects on the skin have opposite directions.',
'About 61% of recorded neurons had an excitatory OFF response. Its mean latency was 12.2 ms and mean duration 39.1 ms, comparable to the brief ON discharge. Many units showed suppression after onset instead of maintaining an elevated rate throughout the hold.',
'The timing supports a code sensitive to transitions as well as continuing contact. It does not mean the OFF response signals prey rejection or that inhibition requires a specific transmitter identified here. Extracellular firing records establish response dynamics while leaving synaptic and intrinsic mechanisms partly unresolved.',
'A neuron’s response to release can carry information about contact ending. The experiment measured mechanical release directly; it did not ask the animal to report whether an object had departed.',anatomy='organstain')
add('Surround stimulation can suppress a cortical neuron','surround',
'Sachdev and Catania used simultaneous recordings at electrodes separated by 200 µm while moving the probe among mapped sites. **Center–surround organization** means that stimulation in a central receptive region can excite a neuron while stimulation outside that region reduces its activity.',
'In paired examples, one contact excited a neuron whose field included that position and suppressed another whose field lay elsewhere. Suppression was measured relative to spontaneous firing. This separates an inhibitory influence from merely failing to excite a neuron at an unrelated location.',
'The findings support interactions that sharpen the spatial pattern of cortical activity. They do not identify whether suppression originates within cortex, in earlier relays or through a particular inhibitory synapse. No pharmacological blockade in this study established GABA receptor involvement, so transmitter-specific mechanisms should not be assigned from firing suppression alone.',
'Extracellular suppression describes a reduction in spikes. Synaptic inhibition is one possible mechanism, but reduced excitation or other network effects can also lower a neuron’s firing rate.',anatomy='cortex')
add('Moving contact changes excitation into suppression','distance',
'Sachdev and Catania moved a controlled mechanical stimulus progressively away from a mapped field center. This tests whether a response boundary is only an absence of excitation or includes active suppression. Baseline spontaneous activity provided the reference for detecting decreases.',
'In the illustrated neuron, central contact elicited a strong discharge. A more distal position on ray 11 suppressed firing for approximately 40 ms, and other positions produced different response magnitudes. Most inhibitory surrounds were larger than the central excitatory patch, yet remained largely confined to one ray.',
'The positional dependence supports a spatially structured response rather than a uniform sensitivity across the appendage. The single example does not establish the same suppression duration for every neuron. It also leaves unresolved whether these interactions improve awake prey discrimination or depend on the tested contact mechanics.',
'A receptive-field border is measured from responses, not inferred from the physical outline of the ray. Several response zones can therefore occupy one appendage.',anatomy='organstain')
add('Contact duration recruits transient and sustained codes','duration',
'Sachdev and Catania compared cortical responses to 5-, 20- and 500-ms stimuli delivered to the same receptive fields. **Transient responses** emphasize short changes near onset, whereas **sustained responses** continue during contact. These categories concern recorded activity rather than an assumed receptor identity.',
'The 5- and 20-ms stimuli mainly produced brief responses. The 500-ms stimulus separated neurons whose activity persisted from neurons with an initial discharge followed by suppression. Some sustained units also varied in their timing rather than responding as a perfectly constant firing-rate signal.',
'The comparison supports multiple temporal representations of contact duration within cortex. A short natural touch can activate these neurons without reproducing their response to a long hold. The data do not prove that transient and sustained cortical units correspond one-to-one to the peripheral rapidly and slowly adapting receptor classes.',
'Applying different durations to the same mapped site limits a spatial confound. The neuronal class is defined by the prolonged-stimulus response, not by an anatomical identification of its peripheral input.',anatomy='cortex')
add('The star forms within the embryonic facial epidermis','embryo',
'Catania, Northcutt and Kaas examined embryos with scanning microscopy and stained sections. **Morphogenesis** is the formation of an anatomical structure during development. The mole’s rays formed as patterned epidermal waves before becoming free appendages, rather than initially projecting outward as separate limbs.',
'At a 9-mm embryonic stage, the nose lacked differentiated rays. At 11 mm, a series of epidermal crests appeared; by 13–15 mm, the 22-ray pattern was apparent. The original sections locate developing nerves relative to the tissue layers that later separate.',
'This developmental sequence establishes how the star’s basic structure emerges. Embryo length is a staging measure, not elapsed time in days. The observations do not identify a gene controlling the pattern or demonstrate that the sequence recapitulates the evolutionary history of the star.',
'A crest is a raised part of the developing epidermis. The later ray derives from reorganized facial tissue, so adult appearance alone would not reveal this developmental route.',anatomy='innervationdev')
add('Ray-specific innervation develops before free movement','innervationdev',
'Catania and colleagues traced embryonic facial nerves with DiI while the star’s rays were still embedded in the facial epidermis. The preparation relates nerve organization to tissue morphogenesis before the newborn possesses the freely moving adult sensory surface.',
'An initially broad nerve network became organized into fascicles supplying epidermal crests. Subsequent tissue growth displaced the nerves around a deeper epidermal layer. By later embryonic stages, terminal arrangements approached the rings characteristic of adult Eimer’s organs; rays emerged approximately one week after birth.',
'The sequence supports coordinated development of the receptor surface and its innervation. It does not establish which molecular signal directs axons or whether early experience determines adult cortical magnification. Anatomical specialization preceding free ray movement also cautions against explaining the entire system solely through repeated adult foveation.',
'A fascicle is a bundle of axons traveling together. The tracing records an evolving anatomical pathway, not neuronal firing during embryonic touch.',anatomy='refinement')

assert len(slides)==44,len(slides)
for i,s in enumerate(slides,2):
 assert len(s['title'])<=62,(i,len(s['title']))
 w=len(re.sub(r'\*\*|_','',' '.join(s['body'])).split());assert 90<=w<=170,(i,w)
keys=['fovea97','speed05','afferent07','hist06','touch13','brain11','response02','duration02','topo16','develop99']
spec={'lecture':26,'theme':'aluminum-atlantic','content_slides':44,'title_image':fig('animal'),'slides':slides,'takeaways':{'items':[
{'lead':'Active touch uses a fovea','text':'Broad initial contact is followed by repositioning of ray 11; the star senses and positions prey while incisors grasp it.'},
{'lead':'Fast handling changes prey value','text':'Small-prey handling averages 227 ms; low handling costs make tiny prey profitable, while search costs still depend on encounter rate.'},
{'lead':'Peripheral specialization has several levels','text':'Eimer’s organs contain multiple endings; foveal specialization involves afferent investment and cannot be explained solely by dome density.'},
{'lead':'Molecular evidence has limits','text':'TG neurons are enriched for mechanosensitivity; transcript and protein enrichment identify candidate channels without proving their causal role.'},
{'lead':'Central allocation magnifies ray 11','text':'Ray 11 accounts for about 11% of afferents, 14% of the PrV star representation and 25% of the S1 star representation.'},
{'lead':'Spatial and temporal codes complement each other','text':'Small foveal fields, center–surround suppression and distinct onset, release and sustained responses encode different aspects of contact.'}
],'cite':'; '.join(SHORT[k]for k in ['fovea97','speed05','touch13','brain11','response02']),'refs':[REF[k]for k in keys]}}
(H/'lecture.json').write_text(json.dumps(spec,indent=2,ensure_ascii=False)+'\n');(H/'references.json').write_text(json.dumps(REF,indent=2,ensure_ascii=False)+'\n');print('44 content slides written; word range',min(len(' '.join(x['body']).split())for x in slides),max(len(' '.join(x['body']).split())for x in slides))
